### ISSUE TITLE
Text to speech plugin

### ISSUE THREAD

**Issue by Voyajer** [runelite/runelite#12714] opened 2020-10-28 23:52 UTC
**Describe the solution you'd like**
A plugin that would pipe player messages from the chat box into a text to speech engine in a way that resembles this video: https://old.reddit.com/r/2007scape/comments/jjqgwi/fish_lvls/

This would most likely fit best in the plugin hub rather than be included with the base client.

**Comment by raiyni** [comment] 2020-10-29 00:02
Duplicate of #8350

**Closed by raiyni** 2020-10-29 00:02 UTC
