### ISSUE TITLE
Spec counter with fake exp drops

### ISSUE THREAD

**Issue by adambtwl0l** [runelite/runelite#10519] opened 2019-12-29 08:01 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
If you don't get a valid exp drop (fake exp drops don't count), it doesn't register on the special attack counter. Though it's not incredibly common some people do have multiple 200m combat 99s or just enough to be effected by certain special attacks (str/hp for bgs as an example, or attack/hp for dwh if dwh on accurate.)  For instance someone with 200m str/hp even if they successfully hit a special attack, their specs won't register on the counter even if they have fake exp drops enabled which are an actual game/jagex feature. 

**Describe the solution you'd like**
Make special attack counter take fake exp drops into account so that it's accurate for those who have reached applicable 200ms from camping pvm or even other methods who still would like the counter to work for them.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Hydrox6** [comment] 2019-12-29 15:50
Duplicate of #7125

**Closed by Hydrox6** 2019-12-29 15:50 UTC
