### ISSUE TITLE
Change default for boost amount threshold

### ISSUE THREAD

**Issue by longflin** [runelite/runelite#11787] opened 2020-06-01 14:44 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be notified when my boost hits 0 levels up sometimes when I'm doing something that requires only a 1 level boost. ex. Only needing 1 mage lvl to hit next trident max hit.

**Describe the solution you'd like**
Change default value to -1 or -99 to disable the feature

**Describe alternatives you've considered**
Add a tick box for 0 value if above is not possible.

**Comment by Hydrox6** [comment] 2020-06-01 14:48
Duplicate of #8961

**Closed by Hydrox6** 2020-06-01 14:48 UTC
