### ISSUE TITLE
Optional time tracking infoboxes or add to canvas option 

### ISSUE THREAD

**Issue by twisted1one** [runelite/runelite#13388] opened 2021-03-26 14:04 UTC
**Is your feature request related to a problem? Please describe.**
Playing with chat box and sidebar minimized you can't really view the farming patches timers or birdhouse
and if you have windows 10 notifications enabled you just get a bunch of idle notifications, which I want this sound to prompt me to start an action too, it's not configurable enough to determine what notification are for what.

**Describe the solution you'd like**
Either a toggle able info box for each time tracking patch or perhaps an ad to canvas option like the XP tracking would be brilliant. Perhaps even a system to define further which notifications get sent to windows 10 notifications

Extra tick able boxes in the timers plugin to add time tracking info boxes or right mouse clickable option in time trackers to add to canvas 

**Describe alternatives you've considered**
Chat notifications and tray notifications 

**Additional context**
PLEASE :)

**Comment by Hydrox6** [comment] 2021-03-26 15:16
Duplicate of #13293
Would be a dupe of #11371 if it wasn't closed

And if you don't want Idle Notifications, then you can turn them off; it's just another plugin. 
> Perhaps even a system to define further which notifications get sent to windows 10 notifications

we already have that in the sense that notifications can be configured already. Could also be considered a duplicate of #11679

**Closed** 2021-09-09 19:36 UTC
Labels: duplicate
