### ISSUE TITLE
OSRS Wiki Plugin

### ISSUE THREAD

**Issue by dhharris** [runelite/runelite#4316] opened 2018-07-14 03:32 UTC
**Problem Description**
One of the issues I have when playing is when I need to go open up a browser and search google for game advice, etc. Almost every time I end up clicking a link to the RS wiki.

**Solution**
I think that a OSRS Wiki sidebar-plugin would be a very welcome addition for many players. They can click the plugin and be directed to the main page of the OSRS Wiki, which includes a searchbar. 

We can work with the OSRS Wiki team to help make the feature as streamlined as possible. I believe it would benefit both parties because players would have easier access to OSRS-related help, and the Wiki team will likely get more readers and contributors. 

There are obviously some things that need to be considered, namely
* **Performance**: we want it to load as fast as a browser would
* **Interface**: how do we fit wiki pages in a small window like a sidebar? Perhaps using the mobile website could work.

Although I am usually very busy with work, if I have any free time I'd love to start working on this new feature. Any feedback would be appreciated!

**Comment by Nightfirecat** [comment] 2018-07-14 06:49
Mostly a duplicate of #3038? I don't think we want to implement an in-client browser.

**Comment by deathbeam** [comment] 2018-07-14 07:12
Duplicate of #3038

**Closed by deathbeam** 2018-07-14 07:12 UTC
