### ISSUE TITLE
Agility obstacle timer countdown until off the obstacle

### ISSUE THREAD

**Issue by aelfric222** [runelite/runelite#12525] opened 2020-09-21 06:25 UTC
To help with doing agility + another window on side, it'd be nice to keep track in corner of our eye a countdown timer until we have to move the mouse to click on the next obstacle. It can begin once the animation starts. Could possibly be a number in a square or over your head.

**Comment by Nightfirecat** [comment] 2020-09-21 06:47
Duplicate of #12407

**Closed by Nightfirecat** 2020-09-21 06:47 UTC
Labels: duplicate
