### ISSUE TITLE
Loot Tracker: Truncate NPC name rather than kill amount

### ISSUE THREAD

**Issue by AntiTcb** [runelite/runelite#5673] opened 2018-09-27 17:15 UTC
**Is your feature request related to a problem? Please describe.**
If the loot tracker is tracking an NPC with a particularly long name (Thermonuclear Smoke Devil) with over a 3 digit kill count (100+), the amount of NPCs killed in the title gets turned into a set of ellipses, obscuring your kill count for that npc.

**Describe the solution you'd like**
Rather than ellipsing the full line of text in the header, truncate the NPC's name, so that the kill amount is always visible.

**Comment by grabartley** [comment] 2018-10-09 17:35
I will have a look into this

**Comment by grabartley** [comment] 2018-10-10 21:35
So the issue is that in order to truncate the NPC name it needs to have `BorderLayout.CENTER`... If I give it that then kill count and price will need to be together and both be `BorderLayout.EAST` but that means that for short names the kill count will appear on the right side rather than just after the name. There must be another way to truncate the name?

**Comment by raiyni** [comment] 2018-10-11 00:51
Without using a custom layout manager or changing the layout, it's not realistically possible with any of the current layout managers. It has been extensively investigated already. 

Might be `wontfix` worthy for the time being.

**Closed** 2019-09-16 15:35 UTC
Labels: enhancement, loot-tracker
