### ISSUE TITLE
Notifications for timers

### ISSUE THREAD

**Issue by flizzflobking** [runelite/runelite#10007] opened 2019-10-08 05:06 UTC
Currently, there are notifications for when you go idle/out of combat. It would be cool to have notifications for timers (such as potions). Good uses would probably include overloads in NMZ and and the 5 minute divine potions when afking crabs or slayer.

**Comment by Nightfirecat** [comment] 2019-10-08 06:43
This is mostly (or entirely?) a duplicate of #9913

**Closed** 2019-10-08 08:13 UTC
