### ISSUE TITLE
Please add an option so you can make screenshots go to different folders.

### ISSUE THREAD

**Issue by mmoseppe** [runelite/runelite#9193] opened 2019-06-23 12:32 UTC
**Is your feature request related to a problem? Please describe.**
It's not a problem it's just annoying to filter my sceenshots 24/7

**Describe the solution you'd like**
1 map per type of screenshot (eg. Levels/drops/quests)

**Comment by Hydrox6** [comment] 2019-06-23 12:40
Duplicate of #8711

**Closed by Hydrox6** 2019-06-23 12:40 UTC
