### ISSUE TITLE
Monster database (Perhaps linked to Osrs Wikia) 

### ISSUE THREAD

**Issue by RuneliteFtw** [runelite/runelite#4643] opened 2018-08-02 14:28 UTC
Stats like this 
![afbeelding](https://user-images.githubusercontent.com/41970701/43590141-a3350108-9670-11e8-93fe-05820f464c04.png)

This will help a lot knowing the enemy is half of the battle. Having this information will give us a lot of advantage.

**Comment by RuneliteFtw** [comment] 2018-08-02 14:31
How do I add label to this ?

**Comment by deathbeam** [comment] 2018-08-02 15:25
Duplicate of #4004

**Closed by deathbeam** 2018-08-02 15:25 UTC
