### ISSUE TITLE
Several bugs on Ubuntu

### ISSUE THREAD

**Issue by steffenag97** [runelite/runelite#6323] opened 2018-11-03 12:27 UTC
Issue 1: Often when using sidebar-features (Whether to enable/disable plugins)
or retrieving hiscore-data, the entire application freezes and needs to be killed in order to play

Issue 2: Upon restarting the application, all configurations may sometimes be lost.

 - OS: Ubuntu 18.04.1 LTS
 - RuneLite version: 1.4.24
 - Launcher version: 1.6.1

If useful:
To run the application I use the following command in the terminal
"java -jar ~/Documents/Runelite/RuneLite.jar --mode=OFF"

- Java version: openjdk 10.0.2 2018-07-17

**Comment by deathbeam** [comment] 2018-11-03 17:40
Duplicate of #3999

**Closed by deathbeam** 2018-11-03 17:40 UTC
