### ISSUE TITLE
Menu Entry Swapper - Stray dog

### ISSUE THREAD

**Issue by jdmalter** [runelite/runelite#12970] opened 2020-12-23 18:45 UTC
**Is your feature request related to a problem? Please describe.**
Feature request is not related to any issue with the client.

**Describe the solution you'd like**
Add toggle to Menu Entry Swapper plugin "Shoo-away" to "Pet" for Stray dog.

**Describe alternatives you've considered**
Submitted similar [feature request](https://github.com/raiyni/menu-swapper-extended/issues/63) to Menu Entry Swapper Extended plugin. After waiting, decided to wait and see which request is implemented first.

**Additional context**
While request is both low severity and low impact, request is desirable to dog-loving users.

**Who's a good doggy!**
![image](https://user-images.githubusercontent.com/12487602/103028009-f23aa180-4524-11eb-9782-0e5ee81115d0.png)

**Comment by makingcomment** [comment] 2020-12-24 15:16
I think the comments on #11215 are still valid.

**Comment by Hydrox6** [comment] 2020-12-24 15:18
Agreed. Knew this had come up but couldn't find it.

So technically a duplicate of #11215, despite that being a PR

**Closed by Hydrox6** 2020-12-24 15:18 UTC
