### ISSUE TITLE
Health Bar Customization

### ISSUE THREAD

**Issue by Smeewth** [runelite/runelite#1573] opened 2018-04-15 19:11 UTC
I'd like to request a feature I loved on Konduit. Which is the ability to customize the opponent health bar (the one displayed in the top left).
You could stretch it out and drag it to, for example, the bottom of the screen.

**Comment by deathbeam** [comment] 2018-07-20 18:21
Duplicate of #3916

**Closed by deathbeam** 2018-07-20 18:21 UTC
Labels: feature-request
