### ISSUE TITLE
Custom Cursors

### ISSUE THREAD

**Issue by 0hi** [runelite/runelite#6253] opened 2018-10-29 18:02 UTC
Hello, I was wondering runelite could have a custom cursor feature like the one in OSB and Konduit that uses a RS2 2010/2012 style cursor on the client. Thank you

**Comment by deathbeam** [comment] 2018-10-29 18:02
Duplicate of #2068

**Closed by deathbeam** 2018-10-29 18:02 UTC

**Comment by 0hi** [comment] 2018-10-29 19:41
> Duplicate of #2068

Hey, I know this is a duplicate. But the original suggestion was closed with the answer "No because it could cause problems". So this could never be suggested or implemented because of that response?

**Comment by Nightfirecat** [comment] 2018-10-29 19:41
Until/unless we find a way to work around that issue, that's correct.

**Comment by deathbeam** [comment] 2018-10-29 19:42
#2068 is still open
