### ISSUE TITLE
Add the ability to reorder the side icons.

### ISSUE THREAD

**Issue by hihi9190** [runelite/runelite#1591] opened 2018-04-16 16:40 UTC

**Comment by deathbeam** [comment] 2018-04-16 17:00
Any reason why this should be implemented? Mainly the pros of it, I feel like just creating blank feature requests without any description why it should be implemented or what is the reasoning you want it is kind of meh and people should stop doing that.

**Comment by deathbeam** [comment] 2018-05-19 01:18
Duplicate of #783

**Closed by deathbeam** 2018-05-19 01:18 UTC
Labels: feature-request
