### ISSUE TITLE
[suggestion] Legacy Hitsplats

### ISSUE THREAD

**Issue by lolplayer509845** [runelite/runelite#14534] opened 2021-12-31 01:58 UTC
![Screenshot 2021-12-30 at 20-56-48 Soloing Corporeal Beast without Food Brews  Runescape](https://user-images.githubusercontent.com/96413024/147798602-d11ca556-c73e-4132-a3ee-70e98e6d1222.png)
Any way for osrs to add the old 2010 legacy hitsplats? I thought they looked pretty neat with the little icons next to the damage number and they would fit with the legacy resource packs as well :D.

**Comment by Nightfirecat** [comment] 2021-12-31 02:10
Duplicate of #3912 and #9849

**Closed by Nightfirecat** 2021-12-31 02:10 UTC
Labels: duplicate
