### ISSUE TITLE
GPU usage hits 99%-100% after game has been played, not played for hours/in taskbar/or closed, then played again.

### ISSUE THREAD

**Issue by Xnate13X** [runelite/runelite#14046] opened 2021-08-20 03:38 UTC
**Describe the bug**
When turning on PC & opening RuneLite, everything runs smoothly. The GPU usage stays around 20-40% max and CPU around 20%-ish (any window mode, doesn't matter). When I minimize it and let it sit in taskbar for a few hours and play it again, no matter if I use that same client or close it to open a new RuneLite, the GPU usage caps out at 99-100%. This leads to constant frame drops. This happens even if I close RuneLite and do other things and want to play it later. As long as it's been open at any point and I close it or let it sit in task bar, when I go to play it later on, it'll use 99-100%. This is usually after a few hours. It doesn't give me any problem while I'm playing for 8hrs straight though. It's SOO weird. I don't understand it. Everything fixes itself though after I restart the PC again. It allows me to either play continuously, or if I want to take a break for a few hours, I have to restart PC to play again if I want to use GPU mode. I've only noticed this within the last week or two because I've been training agility at the Hallowed Sep. It requires GPU use, so it's only now became an issue for me. I've noticed somewhat similar issued to GPU usage hitting 99-100% on other complains online, going back years, but nothing exactly like this. I have pictures to help show what I'm talking about too.

**To Reproduce**
1. RuneLite open for first time (I modern resizable) and GPU use on. The exact settings are in my pictures.
2. Play for a little or whatever, then minimize it to taskbar for a few hours. (sometimes I play other games or go make food/watch YT/put PC to sleep&open later)
3. Try to play again hours later and watch GPU hit 99-100% and you're super laggy.

**Expected behavior**
The lag only happens on RuneLite, nothing else. RuneLite is the problem. I'm not sure why, but it's causing it.

**Screenshots**
4 SS are being added.

**Environment (please complete the following information):**
 - OS: Win10 64bit
 - RuneLite version: 1.7.20.1
 - Launcher version: 2.1.0

**Additional context**
Pictures will be added. Only restarting PC fixes this for the time being until your one play through is done and you try to play again later :/
1. GPU on after PC been on
![GPU on after PC been on](https://user-images.githubusercontent.com/89235646/130175238-7621bfe7-6795-4266-b150-e79f8d8540c3.png)
2. GPU off after PC been on (CPU barely being used!)
![GPU off after PC been on (CPU barely being used!)](https://user-images.githubusercontent.com/89235646/130175249-f478b51e-cc82-42bb-af4b-5e5d00a287bc.png)
3. GPU on after RESTART PC
![GPU on after RESTART PC](https://user-images.githubusercontent.com/89235646/130175253-37e58b56-921f-433b-b7c6-a5b30b533b13.png)
4. GPU off after RESTART PC
![GPU off after RESTART PC](https://user-images.githubusercontent.com/89235646/130175261-41f0003d-7c3e-46b9-8d62-7fdb931e8776.png)

**Comment by Nightfirecat** [comment] 2022-07-10 04:09
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:09 UTC
Labels: needs-information, gpu
