### ISSUE TITLE
Obelisk Destination.  similar to fairy rings

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#4423] opened 2018-07-20 12:09 UTC
when you click on the minimap and you hoover your mouse on top of a fairy ring it will tell you the code to get there.
![image](https://user-images.githubusercontent.com/37475765/43001490-50b27be8-8c1d-11e8-9835-9fb929fd6ba6.png)

 can you do that for obelisk which you can have it at your player owned house?
![image](https://user-images.githubusercontent.com/37475765/43001538-73747ee2-8c1d-11e8-8bb6-cc970dd205cd.png)

an example
![image](https://user-images.githubusercontent.com/37475765/43001572-977d5ffc-8c1d-11e8-875a-5ae4aa16d73c.png)
this obelik is at level 50 wilderness, so when you hoover your mouse on top of the obelisk it should say **Level 50 Wilderness**  etc just similar to fairy rings?

![image](https://user-images.githubusercontent.com/37475765/43001605-b7564438-8c1d-11e8-8b8c-56b6d6897b14.png)
it should say the things thats on that list. ^^

**Comment by deathbeam** [comment] 2018-07-20 12:10
Duplicate of #4216

**Closed by deathbeam** 2018-07-20 12:10 UTC
Labels: feature-request
