### ISSUE TITLE
Agility plugin not tracking laps/laps per hour at Agility Pyramid

### ISSUE THREAD

**Issue by Kittai** [runelite/runelite#16820] opened 2023-07-21 21:21 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Simply put, the agility plugin is not tracking any laps at the Agility Pyramid. I tried every rooftop and it works, except when I'm at Agility Pyramid.

### RuneLite version

Runelite version: 1.10.8.3
Launcher version: 2.5.0

**Comment by Nightfirecat** [comment] 2023-07-21 23:25
I believe this is a regression caused by the threaded map loading. I'm seeing the StatChanged event for the last obstacle happen with the player standing on `WorldPoint(x=3044, y=4694, plane=0)`, which isn't a real tile you can access. The two tiles next to the door at the top of the pyramid are `WorldPoint(x=3044, y=4694, plane=3)` and `WorldPoint(x=3045, y=4694, plane=3)`

**Comment by Adam-** [comment] 2023-07-22 22:26
fixed in ecbc61f906e01bb0d7fcba4154d8cf99d204a067

**Closed by Adam-** 2023-07-22 22:26 UTC
Labels: bug, regression
