### ISSUE TITLE
RuneScape HD XP Bar & XP Drops

### ISSUE THREAD

**Issue by RLLover** [runelite/runelite#14151] opened 2021-09-14 20:09 UTC
![3F851F2F-5A8B-45F9-BE84-7FE6F4B5EB11](https://user-images.githubusercontent.com/90725049/133326665-89837698-e91e-44e9-840f-a40da7b5a358.png)

inspired by 117s HD plug-in :p

**Comment by Vukkyy** [comment] 2021-09-15 12:01
Duplicate of #5106?

**Closed** 2021-09-15 12:05 UTC
Labels: duplicate
