### ISSUE TITLE
A right click option to only reset XP/H while keeping XP Gained

### ISSUE THREAD

**Issue by iVilux** [runelite/runelite#3344] opened 2018-05-26 15:31 UTC

**Comment by psikoi** [comment] 2018-05-26 15:32
@LeviSchuck

**Comment by deathbeam** [comment] 2018-05-26 15:32
Uuuh, that do not makes much sense tbh.

**Comment by psikoi** [comment] 2018-05-26 15:34
Kinda does, I like seeing big numbers on Exp gained but i also like to know my exp rates even if I have to take a break, not high priority at all, but nice

**Comment by iVilux** [comment] 2018-05-26 15:34
I want to see the total how much XP I've gotten throughout the session, but XP/H decreases if I go AFK or do something else.

**Comment by LeviSchuck** [comment] 2018-07-01 02:52
@iVilux I think I have a PR that will address your concern: #4114

**Comment by Nightfirecat** [comment] 2019-04-12 06:16
Duplicate of #3413.

**Closed by Nightfirecat** 2019-04-12 06:16 UTC
Labels: feature-request
