### ISSUE TITLE
Loot tracker loot going invisible in sidepanel

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#6776] opened 2018-12-01 04:01 UTC
Steps to reproduce:

1. Kill a goblin and have the loot tracker show bones + any other drop
2. Hide the bones (right click -> toggle item)
3. Kill goblins until it drops nothing but bones
4. Sidepanel loot does not render until repainted by either scrolling or obtaining another drop

**Comment by deathbeam** [comment] 2018-12-01 12:09
Duplicate of #6240

**Closed by deathbeam** 2018-12-01 12:09 UTC
Labels: duplicate
