### ISSUE TITLE
Suggestion: Rune Pouches that degraded, more noticeable visually.

### ISSUE THREAD

**Issue by adm1n1stra1tor** [runelite/runelite#4831] opened 2018-08-11 09:24 UTC
Maybe make the "number" that shows how many essence it carries red, in case it's degraded. 
Or put a red "?" in the left bottom corner of the icon.

**Comment by deathbeam** [comment] 2018-08-11 09:52
Duplicate of #1007

**Closed by deathbeam** 2018-08-11 09:52 UTC
