### ISSUE TITLE
On screen indicator for NMZ power ups

### ISSUE THREAD

**Issue by shogunreaper** [runelite/runelite#4531] opened 2018-07-27 12:18 UTC
Can an on-screen indicator showing which power ups are currently spawned in nmz be added?

Sometimes the chat just goes by too fast and if i'm not paying 100% attention i'll miss it.

I think right beside the potion icons would be a good spot.

**Comment by Nightfirecat** [comment] 2018-07-27 16:04
I'd recommend using the Chat Notifier to get notifications when powerups spawn.

**Comment by deathbeam** [comment] 2018-07-27 17:16
Duplicate of #2278

**Closed by deathbeam** 2018-07-27 17:16 UTC
