### ISSUE TITLE
Hide remove all option on bank fillers

### ISSUE THREAD

**Issue by Nantoriousbb** [runelite/runelite#11635] opened 2020-05-17 12:13 UTC
**Is your feature request related to a problem? Please describe.**
I get fustrated when i am orginising my bank with fillers and i missclick the all option when removing the ones that i dont use, which then clears all of the bank fillers instead of the one i were ment to clear

**Describe the solution you'd like**
An extension in menu entry swapper or bank option that allows removing the option from the client.

**Describe alternatives you've considered**
alternetivly i've tought that the runelite developers could add a warning when you try to click the all option, i know this one would take alot of more work ive worked with some java before.

**Additional context**
n/a

**Comment by raiyni** [comment] 2020-05-17 12:28
It already takes 2 clicks to clear all fillers

**Comment by Nantoriousbb** [comment] 2020-05-17 12:29
yes but i want the clear-all option gone since it is easy to misclick while orginising bank

**Comment by raiyni** [comment] 2020-05-17 12:46
Duplicate of #6910

**Closed by raiyni** 2020-05-17 12:46 UTC
