### ISSUE TITLE
Slayer Task Counter Desync with Multiple Kills on the Same Tick

### ISSUE THREAD

**Issue by Lapask** [runelite/runelite#10451] opened 2019-12-16 18:37 UTC
When doing barrage tasks (Dust Devils, Jellies, Nechrael, etc), the slayer task counter desyncs when more than one monster is killed during the same game tick.

**Comment by Hydrox6** [comment] 2019-12-16 18:40
Duplicate of #1046

**Closed by Hydrox6** 2019-12-16 18:40 UTC
