### ISSUE TITLE
Highlighting on dark essence mine to show depleted or active.

### ISSUE THREAD

**Issue by Unclaimednubz** [runelite/runelite#10163] opened 2019-10-30 13:44 UTC
Issue -
I like to do runecrafting at work as im currently going for max cape and i get frustrated when mining the dark essence it can be hard to see at a quick glance if you are mining and/or if the rock is depleted.

Potential Idea and alternatives.
Idea of highliting a depleted dark essence pile as red and a non depleted dark essence pile as green or similair overlay as wintertodt to show you are mining/not mining and how much dark essence has been mined and/or how many souls/bloods have been made.

![image](https://user-images.githubusercontent.com/49118935/67863045-16fed900-fb1b-11e9-9fcd-fa08e138c42e.png)

![image](https://user-images.githubusercontent.com/49118935/67863112-30a02080-fb1b-11e9-849f-b0911ad2ab6d.png)

**Comment by Hydrox6** [comment] 2019-10-30 13:45
Duplicate of #7976 and #2164

**Closed by Hydrox6** 2019-10-30 13:45 UTC
