### ISSUE TITLE
XP-tracker: killcount when fighting controlled

### ISSUE THREAD

**Issue by OSRSOcaya** [runelite/runelite#7016] opened 2018-12-19 06:03 UTC
When training melee combat with controlled instread of focusing on either Defence, Strenght or Attack you still get the kill count for when you're focused.

Example, a Moss Giant got 60 HP, he's worth 240 XP per kill. If you need 480 XP to level when training on a focused stat (Def / Str / Att) it correctly states "2 kills remaining" (but with the correct format).
But if you're training controlled it still states "2 kills remaining" even tho the XP is split 3-ways which means you need 6 kills to level up all three skills.

**Comment by Nightfirecat** [comment] 2018-12-19 07:02
Duplicate of #6576

**Closed** 2018-12-19 12:03 UTC
