### ISSUE TITLE
Friends names in right click menu don't get highlighted consistently

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#4485] opened 2018-07-24 19:15 UTC
![screenshot](https://user-images.githubusercontent.com/5851433/43160878-6ac30d06-8f54-11e8-88c0-71a2ef82e8b6.png)

**Comment by ShaunDreclin** [comment] 2018-07-24 19:16
Possibly also effects other things that highlight people's names in the right click menu

**Comment by deathbeam** [comment] 2018-07-24 19:16
Duplicate of #3806

**Closed by deathbeam** 2018-07-24 19:16 UTC
