### ISSUE TITLE
Slayer plugin highlight tiles option

### ISSUE THREAD

**Issue by cox34** [runelite/runelite#5135] opened 2018-08-26 08:08 UTC
NPC Highlighter plugin has an option to highlight tiles or to draw around the mob.

Slayer plugin only has option to draw around the mob. 

May the slayer plugin please get the tiles option?

**Comment by Nightfirecat** [comment] 2018-08-26 21:27
Duplicate of #4606?

**Comment by Berry-95** [comment] 2018-11-28 20:20
Working on this now, following on from the work of ItsSebas
As well as taking into consideration the player indicators plugin, as mentioned in #4606

**Closed** 2020-03-14 20:43 UTC
Labels: duplicate
