### ISSUE TITLE
"Show Menu Item Quantities" item count is sometimes incorrect

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#3544] opened 2018-05-31 23:28 UTC
The "Show Menu Item Quantities" on these do not add up to the same amount as the ground items overlay.
![img](https://i.imgur.com/QKyVlcX.png)
![img](https://i.imgur.com/oAvn2jn.png)

I was killing minotaurs with iron arrows. One of their drops are iron arrows. When they drop these, I notice inconsistencies with the numbers displayed.
The number shown as the total is correct (the very top one).

**Comment by Nightfirecat** [comment] 2018-05-31 23:32
Duplicate of #1220

**Closed** 2018-05-31 23:33 UTC
