### ISSUE TITLE
Export Banktags to text file

### ISSUE THREAD

**Issue by Claws14124** [runelite/runelite#3764] opened 2018-06-13 04:07 UTC
I think it would be really nice if there was a settings cog on the bank tag that would let you export all your bank tags to a text file. Another setting would be to have the ability to import text files to bank tags. This would allow you to:

- back up your tags in case you have to reinstall (I'm not sure if they stay saved somewhere through reinstalls)

- send frends your tags for them to import into their own clients to use as well

- allow people to more easily share inventory setups with each other if you can instantly import them and reflect that within your bank.

**Comment by Abextm** [comment] 2018-06-13 04:19
Related #3748

**Comment by deathbeam** [comment] 2018-07-08 00:32
Duplicate of #3748 as that solves this problem.

**Closed by deathbeam** 2018-07-08 00:32 UTC
Labels: feature-request
