### ISSUE TITLE
Stretched Resizable mode

### ISSUE THREAD

**Issue by nickowz** [runelite/runelite#2508] opened 2018-05-09 10:19 UTC
Runelite currently offers Stretched Fixed mode, and it works great. My suggestion was to add this feature to resizable mode with some sort of value, eg: 10% ui scale increase. That would help with small interfaces and improve overall performance whilst maintaining the same window size.

**Comment by deathbeam** [comment] 2018-05-24 17:29
I guess duplicate of #858

**Closed by deathbeam** 2018-05-24 17:29 UTC
Labels: feature-request
