### ISSUE TITLE
Have the Markers/Overlays Behind The Character

### ISSUE THREAD

**Issue by GitHubQueenn** [runelite/runelite#14146] opened 2021-09-14 14:11 UTC
**Is your feature request related to a problem? Please describe.**
Just had a request: Have the quest markers/layouts not be forced on top of your character.

**Describe the solution you'd like**
Instead, allow the character to show up on top of the marker/layouts.

**Describe alternatives you've considered**
N/A

**Additional context**
Here is a photo of what I mean: [Example Photo](https://i.imgur.com/JSp0A9f.png
)

**Comment by Hydrox6** [comment] 2021-09-14 14:12
Duplicate of #635

**Closed by Hydrox6** 2021-09-14 14:12 UTC

**Comment by GitHubQueenn** [comment] 2021-09-14 14:13
> 
> 
> Duplicate of #635

Ah, ok. If it's a duplicate, definitely seems like a wanted feature. Is it coming? Or at least, what are the dev's thoughts on it? Honestly.
