### ISSUE TITLE
Please add a visual indicator when crops are composted

### ISSUE THREAD

**Issue by TheL0rd0fSpace** [runelite/runelite#11548] opened 2020-05-11 08:44 UTC
There's already a visual change between when a crop is ready to be harvested, and when it's dead and needs to be cleared out.

I'd appreciate if something similar was done to the progress bar/icon in the time tracking plugin, where the progress bar shifts color after it's composted. That way, I can tell at a glance if I've forgotten to compost any of my crops.

Alternatively, there could be a visual change done in the main game screen to the actual crop/herb patch itself to indicate this. But, I've no idea what this change could be, so I won't focus on it.

**Comment by Hydrox6** [comment] 2020-05-11 08:47
Duplicate of #2472

**Closed by Hydrox6** 2020-05-11 08:47 UTC
