### ISSUE TITLE
Wrong Squire for Easy Cryptic Clue

### ISSUE THREAD

**Issue by momopahbles** [runelite/runelite#16419] opened 2023-03-25 18:05 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10 Home 19044.2728

### Bug description

Cryptic easy clue "Talk to the Squire in the White Knights' castle in Falador." points to the Squire on top on the Camelot castle outside of the Knight Waves minigame. This is not the correct Squire.

### Screenshots or videos

![2023-03-25_13-51-08](https://user-images.githubusercontent.com/61907845/227734004-3116f32f-4d17-4328-9b1e-7e3c45060fa6.png)

### RuneLite version

RuneLite version: 1.9.13.1
Oldschool revision: Rev 212
Launcher version: 2.1.0

**Comment by Felanbird** [comment] 2023-03-25 18:19
Duplicate of #5231

**Closed** 2023-03-26 05:13 UTC
Labels: duplicate
