### ISSUE TITLE
Runelite randomly closing without warning or popups

### ISSUE THREAD

**Issue by madmarvels** [runelite/runelite#15593] opened 2022-08-31 03:01 UTC
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10

### Bug description

At any point the client will randomly close itself.  Normally the client will completely close and I won't get any popups. I tried toggling various options off in the GPU plugin since I really didn't want to lose out on such a great plugin. The client won't freeze up and I won't get any popups saying the client or Runelite has crashed, the application will suddenly close no matter what I'm doing. For some reason I can't add the crash logs I found in an edit, it gives me an error. The crash logs are in my comment below.

### RuneLite version

Runelite 1.8.32.2
Launcher 2.4.2
Java 8 update 341

### Logs

[client.log](https://github.com/runelite/runelite/files/9457944/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9457945/launcher.log)

**Comment by Nightfirecat** [comment] 2022-08-31 04:14
Please upload any recently-created `jvm_crash_pid` files found in your logs folder

**Comment by madmarvels** [comment] 2022-08-31 15:13
I guess I looked in the wrong spot before, but I found two for yesterday.

[jvm_crash_pid_6468.log](https://github.com/runelite/runelite/files/9462687/jvm_crash_pid_6468.log)
[jvm_crash_pid_6644.log](https://github.com/runelite/runelite/files/9462688/jvm_crash_pid_6644.log)

**Comment by Karua51** [comment] 2022-09-08 18:16
Same exact thing happens to me any updates?

**Comment by madmarvels** [comment] 2022-09-10 18:29
> 

Nothing yet, which sucks immeasurably

**Comment by gtoilet** [comment] 2022-11-04 10:19
was playing logged out and slept pc
came home woke up pc RL was closed rest of programs were still as i left them...

**Comment by Felanbird** [comment] 2023-03-27 16:23
> Did you ever get this figured out? I'm also having the same issue now.

You're better off joining the discord for this sort of support
![image](https://user-images.githubusercontent.com/41973452/220680975-ebe95451-e020-4d35-822e-9b7df6561d27.png)

**Comment by Felanbird** [comment] 2024-06-18 00:46
This was a duplicate of #10628 but fortunately in the time since, that issue has been updated with resolution(s) that a large amount of people have confirmed to have resolved their issue.

**Closed by Felanbird** 2024-06-18 00:46 UTC
Labels: needs-triage
