### ISSUE TITLE
Floating Ground Item Names (With Video)

### ISSUE THREAD

**Issue by OliverBroadbent** [runelite/runelite#9306] opened 2019-07-07 17:21 UTC
**Bug description**
Some ground item names randomly appear to be floating, about 1 building floor higher than the ground.

FYI: This can be recreated all around the world, but in this example i am using the Cabbage patch and Seers' bank as it has been the most consistent for me. 

**To Reproduce**
Steps to reproduce the behavior: https://streamable.com/4z37s

**Expected behavior**
The ground item name should be in the correct place. 

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.28
 - Launcher version: 1.6.0

**Additional context**
[Logs.zip](https://github.com/runelite/runelite/files/3365918/Logs.zip)

**Comment by Nightfirecat** [comment] 2019-07-09 22:56
This has been fixed internally with build `246877236.189`.

Also, related to/duplicate of #5330.

**Closed by Nightfirecat** 2019-07-09 22:56 UTC
Labels: bug, internal
