### ISSUE TITLE
JEP 382 Support? (MAC) (OSX) (METAL)

### ISSUE THREAD

**Issue by Vulki0** [runelite/runelite#14000] opened 2021-08-08 22:38 UTC
do you think its a possibility to have JEP 382 support for runelite? @fatfingers23 @LlemonDuck 

https://openjdk.java.net/jeps/382

**Comment by Vulki0** [comment] 2021-08-10 19:53
It also came to my attention about JEP 391. Hopefully this is included in runelite 

https://openjdk.java.net/jeps/391

**Comment by Adam-** [comment] 2021-08-10 19:56
duplicate of #12959

**Closed by Adam-** 2021-08-10 19:56 UTC

**Comment by makingcomment** [comment] 2021-08-10 23:15
@Adam- Are you sure this is a duplicate of #12959? The metal rendering pipeline added with JEP 382 doesn't require Apple Silicon, and Apple Silicon doesn't require use of the metal rendering pipeline.

**Comment by Adam-** [comment] 2021-08-11 00:03
The j2d metal pipeline is just part of jdk 17 is not something we have to actually do work for, so this is really n/a to us. At best he could be asking us to use it by default in our launcher, which I am probably not going to do at this time, but that doesn't preclude him from using it.
