### ISSUE TITLE
Werewolves incorrectly highlighted for Wolves Slayer assignment

### ISSUE THREAD

**Issue by FemixZn** [runelite/runelite#7156] opened 2019-01-02 23:15 UTC
Werewolves are highlighted for Wolves Slayer assignment, despite not counting towards that particular assignment.
I'm guessing this is because the slayer plugin checks for the string "wolf" in the NPC name.

https://imgur.com/UsfApHq

This issue is very minor, but I thought I'd report it anyway.

**Comment by Nightfirecat** [comment] 2019-01-02 23:16
Duplicate of #6285

**Closed** 2019-01-02 23:17 UTC
