### ISSUE TITLE
GPU Plugin crashes RuneLite on turning on.

### ISSUE THREAD

**Issue by MrMinimarshall** [runelite/runelite#12157] opened 2020-07-16 08:42 UTC
**Describe the bug**
RuneLite boots correctly with gpu option turned off, when turned on it immdiatly crashes and comes up with with the following error this error has only just started happening, was playing yesterday with no problems when gpu was on.

'OpenGL ES Error cant find the intel graphics'

![image](https://user-images.githubusercontent.com/68373145/87649184-fda0ca00-c747-11ea-9411-29344bd93c4c.png)

1. Go to RuneLite
2. Click on Gpu toggle
3. See error

**Expected behavior**
Yesterday was running the gpu plugin without an issue, should expect game to use my gpu to render map

**Screenshots**
Please see above error

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.21.1
 - Launcher version: 2.1.3

**Additional context**
Please see below crash log.

[jvm_crash_pid_1564.log](https://github.com/runelite/runelite/files/4930257/jvm_crash_pid_1564.log)

**Comment by Nightfirecat** [comment] 2020-07-17 04:38
We didn't make any changes to the client between the time you made this issue and the day before that, so whatever changed was likely something else on your computer. Can you try rolling back your graphics drivers to an earlier version to see if that changes the behavior?/

**Comment by MrMinimarshall** [comment] 2020-07-17 08:20
Hi Nightfirecat,

I have tried rolling back the drivers as per your request, but unfortunately this hasn't helped, is there a way of possibly getting a fresh reset of RuneLite, Whenever i seem to reinstall it already has all of my plugin preferences, would this help at all?

Please let me know :)

**Comment by diblaze** [comment] 2020-08-15 19:03
Same thing has started to happen to me as well. Was working fine, then two days ago the client freezes (the renderer) with the GPU plugin turned on. I have not updated any drivers, nor done any other changes to my PC since last time it was working. 

However, I do not get that error message. My client just freezes without any errors.

**Comment by Nightfirecat** [comment] 2022-07-10 04:03
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:03 UTC
Labels: needs-information, gpu
