### ISSUE TITLE
The loot tracker does not seem to work with a Ring of wealth

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#9757] opened 2019-08-28 12:14 UTC
When I am wearing a ring of wealth, the coins it auto picks are not logged in the loot tracker. Furthermore, if there were no other drops besides the auto picked coins, the kill count in the loot tracker is not even incremented. I noticed this, while killing jellies (no bones drop).

**Comment by Hydrox6** [comment] 2019-08-28 12:15
Duplicate of #5077

**Closed by Hydrox6** 2019-08-28 12:15 UTC
