### ISSUE TITLE
Popout xp tracker

### ISSUE THREAD

**Issue by DreamyRS** [runelite/runelite#8483] opened 2019-04-11 19:01 UTC
Konduit had a similar feature where you could pop out the xp tracker from the sidebar onto the screen, and you could basically relocate it anywhere on the screen. Would it be possible to have this for Runelite too? This is how it looked: https://i.imgur.com/9KNJ2lY.png

**Comment by Nightfirecat** [comment] 2019-04-11 19:19
Duplicate of #1749

**Closed** 2019-04-11 19:21 UTC
