### ISSUE TITLE
Language Packs for OSRS 

### ISSUE THREAD

**Issue by mperelman86** [runelite/runelite#12100] opened 2020-07-09 19:15 UTC
**Is your feature request related to a problem? Please describe.**

Back in the day I loved to play on RS servers with different languages as I knew all the items and interfaces by heart  and it gave me a chance to learn new words in new languages. A lot of people actually learned English just by playing RuneScape . Those worlds exist today but only for the RS3 variant, and are limited to ~10 servers total for the German, French, and Portguese languages. (<1.4k players total)

**Describe the solution you'd like**

Instead of dedicated servers, the RS interface can be translated by mapping values from language packs through RuneLite.  
Only basic things such as menu text and item text needs to be mapped making it a potentially a medium sized problem. 

I can assist in the translation part by funding & handling MTurk jobs once data is collected. 

I would like to be able to use different languages when I'm playing Runescape.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

Checking game code for control texts or building OCR for capturing text and compiling db. (1 to many Languages)
This will have to be maintained. Spineweilder from rswiki is a good friend of mine so maybe they can assist.

**Additional context**

This would allow for non-english speaking communities to form, further expanding the player base. Since this
is only a graphical change, they would not need to be separated from the rest of the game like in RS3. This would be a
very monumental addition that would push RuneLite forward.

We can start language by language with Spanish being among the first to be added.

**Comment by ThatGamerBlue** [comment] 2020-07-09 19:18
Duplicate of #4407

**Closed** 2020-07-09 19:46 UTC
Labels: duplicate, wontfix
