### ISSUE TITLE
Feature Request: Reordering Farming Timers

### ISSUE THREAD

**Issue by Nealon01** [runelite/runelite#11661] opened 2020-05-21 19:56 UTC
It would be really nice if we could click and drag the different timers within a group to put them in any order we want and it would save that to the account.  This would allow you to put them in the order you visit them, making it easier to keep track of your run by watching that tab.

**Comment by Nightfirecat** [comment] 2020-05-22 04:46
Duplicate of #3056

**Closed by Nightfirecat** 2020-05-22 04:46 UTC
Labels: duplicate
