### ISSUE TITLE
Status indicator for use/type of compost and disease protection on farming patches

### ISSUE THREAD

**Issue by Ballistikk** [runelite/runelite#11646] opened 2020-05-18 23:10 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes while doing farm, specifically herb runs I don't remember whether or not I added (ultra/super)compost on certain patches. Although I don't typically do other types of runs, I think it would also be useful (such as in fruit tree runs) for the client to indicate whether or not a farming NPC was paid to watch over their corresponding patch.

**Describe the solution you'd like**
Ideally this would be a short status indicator/description under the "time tracking" plugin for each patch. More info under **additional context**.

**Describe alternatives you've considered**
I am aware that the chat menu states whether or not you added compost/paid the NPC, but this can often be hard to find/(not) notice, as well as keep track of if you don't remember the exact sequence of patches that you went to.

**Additional context**
The color of the status text would indicate a yes/no state (green/red) to make the statuses stand out more, and yellow for a state in between (such as using normal or supercompost - better than no compost but not the best). I'm no graphic designer but I added a concept screenshot below.
![Screenshot_42](https://user-images.githubusercontent.com/64110204/82267661-de411880-9921-11ea-8d4f-280c440c8ed1.png)

**Comment by Nightfirecat** [comment] 2020-05-18 23:12
Duplicate of #2472

**Closed by Nightfirecat** 2020-05-18 23:12 UTC
Labels: duplicate
