### ISSUE TITLE
Upgrade the menu entry swapper and option to disable enter to chat on key remap

### ISSUE THREAD

**Issue by CnPx98** [runelite/runelite#12653] opened 2020-10-16 20:29 UTC
Upgrade to the "Menu Entry Swapper" plugin
I think it would be awesome if you could be able to edit the Left click like how you can edit the shift click. I keep accidentally selecting wield item all the time and also eating foods when trying to use instead. 

Option to disable Enter to chat on the "Key remapping plugin" 
I use a MacBook so this plugin would be great for me as the F keys are changing to things like brightness, key led, media buttons, etc... It would be perfect if I and others could use this plugin but be able to disable Enter to chat if we didnt want that option. Maybe have to so when camera remap is disabled enter to chat is disabled with it. 

Thank you for taking the time to read and let me know what you think.

**Comment by Nightfirecat** [comment] 2021-01-22 23:19
The first of these requests is mostly a duplicate of #9882 insofar as using the configured shift-click behavior by default.

As for disabling "Enter to chat" while still having F key remapping enabled, how would you type the remapped keys then? i.e. The defaults for these remaps are the number keys and `-` and `=` keys. If we didn't add "Enter to chat", you wouldn't be able to type numbers ingame

**Comment by CnPx98** [comment] 2021-01-23 10:37
> The first of these requests is mostly a duplicate of #9882 insofar as using the configured shift-click behavior by default.
> 
> As for disabling "Enter to chat" while still having F key remapping enabled, how would you type the remapped keys then? i.e. The defaults for these remaps are the number keys and `-` and `=` keys. If we didn't add "Enter to chat", you wouldn't be able to type numbers ingame

I never use the chat box anyways. I only check the game option every now and then to see if something happened. Loosing the ability to type numbers means nothing to me anyways. But I suppose if most people disagree then I cant see this being a priority.

**Comment by Nightfirecat** [comment] 2021-01-23 18:13
Given that this would break the ability to type in chat, we won't be adding it.

**Closed by Nightfirecat** 2021-01-23 18:13 UTC
Labels: wontfix
