### ISSUE TITLE
Custom Adjustable Audio Bars Bug

### ISSUE THREAD

**Issue by chrispratt00** [runelite/runelite#10632] opened 2020-01-22 04:16 UTC
![unknown](https://user-images.githubusercontent.com/42954098/72864926-d7700500-3ca3-11ea-96f4-5232c9e7555d.png)

**Comment by Nightfirecat** [comment] 2020-01-22 07:01
We've observed this bug numerous times but never had enough information to figure out what causes it exactly, since nobody who encounters it is ever able to reproduce it.

For clarity, you can fix this on your end by disabling and re-enabling the "Music" plugin. If you know any way to get this bug to happen again, please post here with said information.

**Comment by josCharm** [comment] 2020-01-23 14:04
Hello Nightfirecat,

I have this same issue, disabling and re-enabling the music plugin alone won't help for me.
When I disable the music plugin and double click on the slider I can force it to work again.
However, when I turn on the music plugin again it starts happening again. 
What information can I provide you regarding this bug?

**Comment by dekvall** [comment] 2020-01-23 14:21
@josCharm That is a different issue which had to do with a game update and it has been fixed in 84a3f838b2bb1fb8dfd517cbc980b98a62bb966c

**Comment by gabrielamboss** [comment] 2020-03-09 04:07
I managed to reproduce this issue. It consistently happens on my client (v1.6.9) when I do the following:

1. With resizeable mode activated, have the music plugin on.
2. Log off, then modify the client size
3. Log back in again. Sliders should be clumped as shown in the screenshot above, requiring to toggle the music plugin to work again.

This issue does not happen if you are in fixed mode.

**Comment by abextm** [comment] 2020-03-09 07:29
Fixed in 480a5ab921942598c2aca45e49994ef9a744c1a8
Thanks for finding a reproducer @gabrielamboss

**Closed by abextm** 2020-03-09 07:29 UTC
Labels: bug
