### ISSUE TITLE
Notification customization based on source

### ISSUE THREAD

**Issue by Moremackles** [runelite/runelite#14609] opened 2022-01-18 10:30 UTC
Notifications from plugins are nice but there is a problem in that if you have multiple sources of notifications, it can be hard to see what specifically caused it. The option to output the text to the game chat is helpful but still remains ambiguous unless you have timestamps on and correlate it with the current time, which for me ruins the entire point of using notifications to minimize attention. 

My suggestion is to allow for configuring notifications separately for each plugin or perhaps have notification presets that plugin developers could use to  allow you to customize how you want each event triggering a notification to be handled (Idle plugin for example -> Sound enabled, solid screen notification, vs combat stats draining single flash/game message)

**Comment by Nightfirecat** [comment] 2022-01-18 10:46
This is mostly a duplicate of #11679

**Closed by Nightfirecat** 2022-01-18 10:46 UTC
Labels: duplicate
