### ISSUE TITLE
Menu Entry swapper teleport to house spell

### ISSUE THREAD

**Issue by Philiw00t** [runelite/runelite#5720] opened 2018-09-30 20:31 UTC
Frustrated having to right click teleport to home when karambwan fishing, or just trying to use ornate pool. Would like to be able to have it on left click in the spellbook. It seems for other options that are unlocked through diaries you can set it but for some reason you cant with teleport to home

**Comment by deathbeam** [comment] 2018-09-30 20:37
Duplicate of #5440

**Closed by deathbeam** 2018-09-30 20:37 UTC
