### ISSUE TITLE
Random client crash

### ISSUE THREAD

**Issue by kecleon** [runelite/runelite#5749] opened 2018-10-02 03:38 UTC
Could not find an exact duplicate.

**Describe the bug**
Out of nowhere, the client will just exit with no warning.

**To Reproduce**
Nothing I've found reproduces it, It has crashed while my character is idle with runelite not focused, it has crashed while walking in game, it has happened after 5 minutes of playing, and it has also gone multiple hours with no crash at all.

**Expected behavior**
No crash.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10 64bit
 - RuneLite version: 1.4.19
 - Launcher version: "Unknown"
 - OSRS version: Rev 175

**Additional context**
Log with the same timestamp as when my client crashed the most recent time.
https://pastebin.com/VTRWhAJf

**Comment by deathbeam** [comment] 2018-10-02 08:44
Duplicate of #3539

**Closed by deathbeam** 2018-10-02 08:44 UTC
