### ISSUE TITLE
Holding "e" crashes chat/text input on mac

### ISSUE THREAD

**Issue by dappersnapper456** [runelite/runelite#9232] opened 2019-06-27 17:30 UTC
Hold down "e" on the mac client. You won't be able to type anything in the chatbox
and if you try logging out you won't be able to type your username/password either. You have to shut the client and reopen it to cancel this effect.

**Comment by dappersnapper456** [comment] 2019-06-30 13:41
@abextm what extra information do you need?

**Comment by Nightfirecat** [comment] 2019-07-01 22:46
Probably logs so we can have an idea of what code might be causing this error.

**Comment by Zirro** [comment] 2019-08-12 14:42
Duplicate of #3514.

**Closed** 2019-08-12 15:26 UTC
Labels: needs-information
