### ISSUE TITLE
Separable Groups of Indicators

### ISSUE THREAD

**Issue by tomcylke** [runelite/runelite#5624] opened 2018-09-24 20:49 UTC
I think it would amazing if we could separate some of the indicators from the RuneLite client. Konduit, for example, lets you put boost information in one place, slayer information in a different place, active prayers in a different place, etc. 

Not hugely important, but if this is something that can be implemented I'd be very happy about it.

**Comment by deathbeam** [comment] 2018-09-24 20:51
Duplicate of #1785

**Closed by deathbeam** 2018-09-24 20:51 UTC
