### ISSUE TITLE
Screenshot plugin includes windows on top of Runelite when Runelite is in background

### ISSUE THREAD

**Issue by cox34** [runelite/runelite#12630] opened 2020-10-12 03:51 UTC
Runelite 1.6.14, launcher 2.1.0 (May 2020)
Arch Linux 5.6.11-arch1-1
nvidia Driver Version: 440.82

and 
Runelite 1.6.28, launcher 2.1.3 (Oct 2020)
Arch Linux 5.8.10-arch1-1
nvidia Driver Version: 455.23.04, 455.28

using AppImage
however, issue also present when using .jar and java-13-openjdk set to default
Arch is using nvidia driver package and KDE plasma desktop environment

issue only occurs when GPU plugin is enabled.

screenshot plugin includes windows on top of runelite when runelite is not active window/in the background. this could mean a part of or all of runelite is covered by another window in the screenshot.

understandable if the issue is too specific to my machine. any suggestions welcome.

example, I died in clan wars:
![Death 2020-10-12_12-46-42](https://user-images.githubusercontent.com/17260496/95703244-37e21080-0c3e-11eb-8158-859c87ea811f.png)

**Comment by cox34** [comment] 2020-10-12 10:56
Issue also occurs when using nouveau drivers.
Issue is not specific to nvidia drivers.

**Comment by Nightfirecat** [comment] 2022-07-10 04:04
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:04 UTC
Labels: gpu, not-our-bug, platform:linux

**Comment by Mm2PL** [comment] 2022-11-17 23:50
Can replicate:
 - OS: Arch Linux
 - Window system: X11
 - WM: i3
 - Compositor: picom
 - GPU drivers: nvidia
 - two monitors

Just happened for me with RuneLite being on another workspace.
This bug is weird, it sometimes doesn't happen, I feel like changing the monitor/xrandr settings sometimes fixes it?
