### ISSUE TITLE
Loot tracker no longer allows single session saves

### ISSUE THREAD

**Issue by JonathanOuwens** [runelite/runelite#14755] opened 2022-03-17 10:25 UTC
Why was the loot tracker updated to no longer be able to see your session kills? I don't care about my long term gains, I want to see how much I made in that session.

Could synchronize panel contents be re-added in the next update? Maybe default it to on, but don't break my gameflow pls.

**Comment by Hydrox6** [comment] 2022-03-17 10:28
Duplicate of #14745

**Closed by Hydrox6** 2022-03-17 10:28 UTC
