### ISSUE TITLE
Regex filtering the less-than and greater-than symbols is a pain

### ISSUE THREAD

**Issue by towelcat** [runelite/runelite#10688] opened 2020-01-29 19:46 UTC
Due to how Jagex encodes < and > (`<lt>` and `<gt>` respectively), it's a huge hassle when writing chat filters at the moment.

What I currently use (not ideal as it can *potentially* lead to some false positives):
`r[\W_ltg]*u[\W_ltg]*n[\W_ltg]*e[\W_ltg]*c[\W_ltg]*h[\W_ltg]*a[\W_ltg]*t[\W_ltg]*`
Technically I could use this to avoid any potential false positives, but it's even _more_ bloat:
`r([\W_]|<lt>|<gt>)*u([\W_]|<lt>|<gt>)*n([\W_]|<lt>|<gt>)*e([\W_]|<lt>|<gt>)*c([\W_]|<lt>|<gt>)*h([\W_]|<lt>|<gt>)*a([\W_]|<lt>|<gt>)*t([\W_]|<lt>|<gt>)*`
What I wish I could use:
`r[\W_]*u[\W_]*n[\W_]*e[\W_]*c[\W_]*h[\W_]*a[\W_]*t[\W_]*`

**Comment by dekvall** [comment] 2020-01-30 23:43
Duplicate of #9155

**Closed by dekvall** 2020-01-30 23:43 UTC
