### ISSUE TITLE
Ability to mark tiles

### ISSUE THREAD

**Issue by CaraPis** [runelite/runelite#949] opened 2018-03-13 07:00 UTC
I know right now you have a tile marker where you click, but it disappears. Would it be possible to mark certain tiles for a longer period of time/permanently. The only place i'd really see this being useful is if you're learning to solo raid and maybe inferno?

**Comment by Adam-** [comment] 2018-03-13 11:33
Duplicate of #722

**Comment by deathbeam** [comment] 2018-03-13 11:58
Reopening as #722 is about screen markers feature present in OSB and Konduit, and that is just drawing rectangle on screen, so not about marking anything specific like tiles in this issue.

**Comment by CaraPis** [comment] 2018-03-13 18:22
well it's not really an issue for me, but it would just be a nice feature i guess :p

**Comment by TomMartow** [comment] 2018-03-13 18:33
Adam, this is what CaraPis is talking about.

![untitled-1](https://user-images.githubusercontent.com/10462926/37362386-efa3ec78-26ec-11e8-90dd-c9791245a63e.png)

**Comment by ShaunDreclin** [comment] 2018-03-14 14:59
iirc somebody already did this, I dont know if it ever got PR'd but they were showing it on the discord

**Comment by CaraPis** [comment] 2018-03-15 18:55
yea tom, that's exactly it :)

**Comment by TheLonelyDev** [comment] 2018-03-24 21:38
ShaunDreclin is/was talking about me (afaik). I am trying to get a working version done around next Monday-ish as the "ux" has been a bit of a struggle for me haha.

**Comment by ShaunDreclin** [comment] 2018-03-24 22:34
Yay! I would say go with shift-right-click to tag tiles, since that's what we will probably be going with to tag NPCs

**Comment by TheLonelyDev** [comment] 2018-03-24 22:38
Great idea for the shift right click, sounds much better than right click and then using a menu option (as I have it now).

**Comment by Adam-** [comment] 2018-04-23 00:38
Done in #1812

**Closed by Adam-** 2018-04-23 00:38 UTC
Labels: feature-request
