### ISSUE TITLE
POH servant 'Cook' gets marked as a clue step.

### ISSUE THREAD

**Issue by Klievan** [runelite/runelite#12439] opened 2020-09-02 18:50 UTC
**Describe the bug**
A cook servant in a POH (and possibly other locations) gets marked as the Lumbridge cook medium clue step when entering a POH.

**To Reproduce**
1. Get medium anagram clue "OK CO"
2. Enter a POH with a cook servant

**Expected behavior**
The cook shouldn't be marked with an arrow as it's not the cook you're supposed to talk to :p 

**Screenshots**
![Schermafbeelding 2020-09-02 om 20 46 15](https://user-images.githubusercontent.com/5279685/92023978-d33db700-ed5d-11ea-9fa0-c0439f4a39a5.png)

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: 1.6.1

**Comment by Hydrox6** [comment] 2020-09-02 18:55
Duplicate of #3164

**Closed by Hydrox6** 2020-09-02 18:55 UTC
