### ISSUE TITLE
RS3 Music Plugin

### ISSUE THREAD

**Issue by oogaboogadoogydoogy** [runelite/runelite#13304] opened 2021-03-03 20:08 UTC
Would it be possible for the Music plugin to have an option to replace the original soundtrack with their RS3 counterparts where applicable? 

As good as the soundtrack is, RS3's orchestral melodies are phenomenal & I think a lot of people would play without the game muted if implemented.

**Comment by Hydrox6** [comment] 2021-03-03 20:15
Duplicate of #3390 (see final comment btw)

**Closed by Hydrox6** 2021-03-03 20:15 UTC
