### ISSUE TITLE
RuneLite Settings Export/Import

### ISSUE THREAD

**Issue by danielsmth97** [runelite/runelite#9479] opened 2019-07-27 01:27 UTC
I realize there is a file in the /.runelite directory with RuneLite settings, but it would be a bunch of extra hassle to find the file and transport it around it different clients just to have the same settings.

A client plugin import/export settings by fetching your current settings and allow you to download a file so you can move your settings around much easier. This would also assist less tech-savvy, resulting is an easier to use UI for this issue

**Comment by Alexsuperfly** [comment] 2019-07-27 01:28
the account plugin does this exact thing, use a google account to login to a RL "Account" and its syncs settings to the cloud where ever you are

**Comment by danielsmth97** [comment] 2019-07-27 01:30
Weird, recently I used a different client and the settings did not sync so I assume I didn't have something configured properly. Thank you for letting me know

**Comment by dekvall** [comment] 2019-07-27 17:50
Syncing local settings to your remote account has been added to the wiki under [Account](https://github.com/runelite/runelite/wiki/Account) along with a reference in the  [FAQ](https://github.com/runelite/runelite/wiki/FAQ).

**Comment by Alexsuperfly** [comment] 2019-07-28 18:26
duplicate of #3748

**Closed** 2019-07-29 00:07 UTC
Labels: duplicate
