### ISSUE TITLE
Mac OS download gives corrupt image

### ISSUE THREAD

**Issue by Lenus1** [runelite/runelite#3021] opened 2018-05-20 15:26 UTC
I've lurked OSRS reddit and youtube for a few months now, haven't played since the first android beta ended. I've noticed the drama and would like to support runelite through this tough time. Unfortunately I only have a mac laptop right now and every time I download, I get a warning and it says "corrupt image". I was wondering if this is something on my end or what exactly it is. Thank you

**Comment by deathbeam** [comment] 2018-05-20 15:27
Duplicate of https://github.com/runelite/launcher/issues/16

**Closed by deathbeam** 2018-05-20 15:27 UTC
