### ISSUE TITLE
JDK 13

### ISSUE THREAD

**Issue by LovinLifee** [runelite/runelite#9879] opened 2019-09-18 02:14 UTC
RL doesn't work well with JDK 13, I get a bunch of weird artifacting (especially) whilst using the GPU plugin.

**Comment by Kamielvf** [comment] 2019-10-06 14:56
I think we ship Java 11 with the launcher, so I suggest using a version of java that we do support. Things can change between java versions and I guess that's what's going wrong for you.

**Comment by Wynadorn** [comment] 2020-04-18 15:56
This might be the same issue I'm having, I've described the issue here some time ago:
https://discordapp.com/channels/301497432909414422/442492468307427330/678674291696336906

I think it's caused by JDK 13 (and up) being incompatible with JOGL 2.3.2 though don't take my word for it, I'm trying to take a closer look at it at the moment.

`jogamp.opengl.awt.Java2D` calls `getOGLUtilitiesIntField("PBUFFER");`
however `sun.java2d.opengl.OGLUtilities` (in `java.desktop`) doesn't have a variable `public static final int PBUFFER`

```
java.lang.NoSuchFieldException: PBUFFER
	at java.base/java.lang.Class.getField(Class.java:2013) //public static final int sun.java2d.opengl.OGLUtilities.UNDEFINED
	at jogamp.opengl.awt.Java2D$2.run(Java2D.java:574) 
	at jogamp.opengl.awt.Java2D$2.run(Java2D.java:569)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at jogamp.opengl.awt.Java2D.getOGLUtilitiesIntField(Java2D.java:569)   //Parameter NAME is "UNDIFINED"
	at jogamp.opengl.awt.Java2D.<clinit>(Java2D.java:92)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:340)
	at jogamp.nativewindow.jawt.JAWTUtil.<clinit>(JAWTUtil.java:345)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at com.jogamp.nativewindow.NativeWindowFactory$3.run(NativeWindowFactory.java:344)
	at com.jogamp.nativewindow.NativeWindowFactory$3.run(NativeWindowFactory.java:340)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at com.jogamp.nativewindow.NativeWindowFactory.initSingleton(NativeWindowFactory.java:340)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1721)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
	at program.main(program.java:34)
```

**Comment by Nightfirecat** [comment] 2022-07-10 04:32
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:32 UTC
Labels: jvm-bug
