### ISSUE TITLE
Shadow dungeon clue step POST DT2.

### ISSUE THREAD

**Issue by Jaecn** [runelite/runelite#16844] opened 2023-07-27 10:26 UTC
### Type

Crash or hang

### Operating System

None

### Bug description

When doing the elite emote clue inside the shadow dungoen, the equipped items are a ring of visibility. Post DT2 the ring changes to the ring of shadows and the visibility can no longer be claimed, but with the RoS equipped it doesn't specify that you've met the item requirements for the clue helper. 
Just posting so it can potentially be added as a RoV/RoS option to prevent people running around to banks in the event they haven't realised.

### Screenshots or videos

![1](https://github.com/runelite/runelite/assets/140708752/f187dcc1-0985-4eb9-8ce9-d00ccbcde631)

![2](https://github.com/runelite/runelite/assets/140708752/87b9e43b-917d-4fb8-84fb-d1992eec131c)

### RuneLite version

1.10.8.3

**Comment by Nightfirecat** [comment] 2023-07-27 14:57
Duplicate of #16819

**Closed** 2023-07-27 14:57 UTC
Labels: duplicate
