### ISSUE TITLE
[Mouse Tooltips] Hide Top-Left Contextual Text

### ISSUE THREAD

**Issue by oogaboogadoogydoogy** [runelite/runelite#14193] opened 2021-09-26 19:38 UTC
Could we add an option to remove the text in the upper-left hand corner when hovering over anything? These same tooltips now show up as mouse tooltips so the option to disable it should be an option within the Mouse Tooltips plugin. 

Jagex themselves have already implemented this very feature into their C++ Steam client.

**Comment by Adam-** [comment] 2021-09-26 19:47
This is already in the Jagex java client, it just isn't documented, I think its `::mouseovertext`

**Comment by oogaboogadoogydoogy** [comment] 2021-09-26 20:47
> This is already in the Jagex java client, it just isn't documented, I think its `::mouseovertext`

This is true, thanks for pointing it out! Problem is, when you log out, the text reappears. Meaning, as much of a first-world problem as it is, you have to reenter “::mouseovertext” everytime you login. Even switching worlds resets it. 

An option in the plugin could fix this issue.

**Comment by oogaboogadoogydoogy** [comment] 2021-09-28 03:21
@Adam- any idea on how to keep “::mouseovertext” persistent through logins?

**Comment by Adam-** [comment] 2021-09-28 03:27
It's not possible currently. It's something we could make but I don't really know where we would put it.

**Comment by Nightfirecat** [comment] 2023-02-20 20:12
Duplicate of #12590

**Closed by Nightfirecat** 2023-02-20 20:12 UTC
Labels: feature-request, internal
