### ISSUE TITLE
Open plugin guides from within the client

### ISSUE THREAD

**Issue by devLotto** [runelite/runelite#8178] opened 2019-03-11 23:11 UTC
I think there should be a very obvious way of opening a guide for a plugin. 

I have gathered some intel that people don't use the Party plugin because it's hard to know how to use it/how to use it to its full potential. I imagine this can be applied to a few other plugins too.

Maybe we can add a guide button next to the config cogwheel and on-off button, that opens the plugin's wiki article upon being pressed?

**Comment by Nightfirecat** [comment] 2019-03-11 23:54
Duplicate of #1518

**Closed** 2019-03-12 00:01 UTC
