### ISSUE TITLE
Display the range of combat levels in Wilderness

### ISSUE THREAD

**Issue by supermxn** [runelite/runelite#3619] opened 2018-06-04 15:02 UTC
It currently only shows in PvP worlds. I think it would be a nice thing to have, since you're aware of what combat levels are able to attack you. Something similar to this: https://i.imgur.com/DGpoU0Y.png

**Comment by deathbeam** [comment] 2018-06-04 15:04
Duplicate of #3103

**Closed by deathbeam** 2018-06-04 15:04 UTC
