### ISSUE TITLE
Add farming harvest to loot tracker or perhaps a new section like the latter

### ISSUE THREAD

**Issue by sunset904** [runelite/runelite#5626] opened 2018-09-24 22:40 UTC
Title, i think it would be a neat addition knowing how much gp is worth the entire harvest before selling it all to GE or just at least have a track of profit on a run

**Comment by Alexsuperfly** [comment] 2018-09-24 22:49
click this button when you finish your farm run 

![](https://i.imgur.com/fPxjvFg.png)

**Comment by oplosthee** [comment] 2018-09-24 22:50
I believe this is a duplicate of https://github.com/runelite/runelite/issues/5088 as well.

**Comment by deathbeam** [comment] 2018-09-25 05:57
Duplicate of #5088

**Closed by deathbeam** 2018-09-25 05:57 UTC
