### ISSUE TITLE
GE Plugin (Time stamps)

### ISSUE THREAD

**Issue by stoddy15** [runelite/runelite#11281] opened 2020-04-16 15:19 UTC
Would it be possible that the creator of the grand exchange plugin include timestamps in the chat notification? This would allow us to judge when the item was last sold. 

<img width="784" alt="Screenshot 2020-04-16 at 16 15 52" src="https://user-images.githubusercontent.com/63739578/79474089-e5f95e80-7ffd-11ea-9a3a-b3719f598f39.png">

**Comment by stoddy15** [comment] 2020-04-16 15:34
also we only get the chat notifcation when you are not at the grand exchange can you give us the option to still get them if we're there? Sometimes you can't tell what has sold if it was a small amount

**Comment by Nightfirecat** [comment] 2020-04-16 16:08
If you enable the Chat Timestamps plugin, do you see timestamps applied as you would expect already?

**Comment by Nightfirecat** [comment] 2020-04-16 16:08
Also, these are ingame messages, not generated by the Grand Exchange plugin.

**Comment by stoddy15** [comment] 2020-04-16 17:08
> If you enable the Chat Timestamps plugin, do you see timestamps applied as you would expect already?

nope

<img width="500" alt="Screenshot 2020-04-16 at 18 07 00" src="https://user-images.githubusercontent.com/63739578/79485462-2f9d7580-800d-11ea-8da8-b9c31965ca55.png">

**Comment by Nightfirecat** [comment] 2020-04-16 17:12
Duplicate of #8542

**Closed by Nightfirecat** 2020-04-16 17:12 UTC
Labels: duplicate
