### ISSUE TITLE
Add a payment and ultracompost indicator

### ISSUE THREAD

**Issue by Arodab** [runelite/runelite#13259] opened 2021-02-23 18:48 UTC
Ocasionally, I teleport away too fast and the payment for my trees don't go through, but I only notice the next time I do a tree run and it's dead. It would be nice if the Time Tracking plugin showed if the patch is protected.

Very rarely I forget to ultracompost my herbs too, but I only notice when I get less than 6. I track my herb run yields so an ultracompost indicator would be helpful too to make sure I"m not adding bad data without having to inspect every patch manually.

**Comment by Hydrox6** [comment] 2021-02-23 19:47
Duplicate of #2472

**Closed by Hydrox6** 2021-02-23 19:47 UTC
