### ISSUE TITLE
A Viggora's chainmace/Craw's bow/Thammaron's sceptre ether counter in the top left of the screen

### ISSUE THREAD

**Issue by gitfred1** [runelite/runelite#10545] opened 2020-01-03 21:46 UTC
A box counting down the amount of ether left in the 3 wilderness weapons  added next to the other box counters on the top left side of the screen (Slayer kill count, Stamina Potion timer, etc.). Not counting the 1000 it takes to "activate" the weapons.

**Comment by Hydrox6** [comment] 2020-01-03 22:02
Duplicate of #953 (It's the same issue, just for different items)

**Closed by Hydrox6** 2020-01-03 22:02 UTC
