### ISSUE TITLE
New overlay lock position

### ISSUE THREAD

**Issue by LLandsem** [runelite/runelite#13477] opened 2021-04-13 16:15 UTC
I would like to suggest a new overlay/ infobox lock position. I find having my overlays above the inventory is much easier to manage and keep track of. If there is a way to change this myself I would be willing to try it out. I don't know much about coding but I could figure it out with some help in the right direction. 

I have attachments to illustrate the suggestion.

![Overlay Fig 1](https://user-images.githubusercontent.com/79777597/114585215-683c5300-9c51-11eb-8d14-7f50ef777b2b.png)

![Overlay Fig 2](https://user-images.githubusercontent.com/79777597/114584145-5a3a0280-9c50-11eb-80a2-d5d479da36be.png)

**Comment by Hydrox6** [comment] 2021-04-13 16:24
Duplicate of #8515

**Closed by Hydrox6** 2021-04-13 16:24 UTC
