### ISSUE TITLE
"DARN DRAKE" anagram clue not implemented

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#10905] opened 2020-02-28 16:16 UTC
Apparently, there is a new hard clue anagram step "DARN DRAKE". The solution is, Daer Krand, upstairs in the eastern wing of the Sisterhood Sanctuary, just north of the the Nightmare's arena.
Perhaps there are more new clue steps with the addition of Nightmare, I have not checked.

**Comment by Nightfirecat** [comment] 2020-02-28 16:23
Duplicate of #10747

**Closed by Nightfirecat** 2020-02-28 16:23 UTC
Labels: duplicate
