### ISSUE TITLE
(FEATURE REQUEST) This feature would save my life, add "escort" to the Menu Entry Swapper

### ISSUE THREAD

**Issue by reswin555** [runelite/runelite#9985] opened 2019-10-05 19:31 UTC
Please add a feature to the menu entry swapper that changes the left click of **Temple Trekking** characters in Burgh de Rott that you escort from "Talk To" to "Escort". Since you have to right click and press escort every time, I think this would help me personally so much, as I do Temple Trekking very very often, It would save a lot of clicks and I could do more runs faster. Thank you so much if you add this!

**Comment by Hydrox6** [comment] 2019-10-05 19:40
Duplicate of #5380

**Closed by Hydrox6** 2019-10-05 19:40 UTC
