### ISSUE TITLE
Barrows Prayer Double Prayer Drain Timers

### ISSUE THREAD

**Issue by vScizor** [runelite/runelite#12166] opened 2020-07-16 18:23 UTC
Not sure what triggers it but sometimes the Barrows Brothers Prayer Drain Timer creates a second timer that constantly cycles regardless of activity. I've also noticed the only way to get rid of it is to restart RuneLite. See screenshots. Within the crypts, the regular timer still works properly, but I have no way of telling which one is correct if I'm not paying attention to the extra one when I dig into them.

![prayerdrain2](https://user-images.githubusercontent.com/68255098/87707735-3bf9b180-c767-11ea-9e8e-b4a12f6b9359.png)

![prayerdrain1](https://user-images.githubusercontent.com/68255098/87707728-3603d080-c767-11ea-89fc-fb4b60f446f1.png)

**Comment by Nightfirecat** [comment] 2020-07-17 03:57
Duplicate of #10902

**Closed by Nightfirecat** 2020-07-17 03:57 UTC
Labels: duplicate
