### ISSUE TITLE
Chat color changes.

### ISSUE THREAD

**Issue by Justin222111** [runelite/runelite#2942] opened 2018-05-19 13:33 UTC
I was thinking it might be useful to be able to change the color of different chat types, (public, private, clan) since personally for me it is pretty difficult to see chat over top of different colors while i have transparent mode set.

**Comment by Hydrox6** [comment] 2018-05-19 13:37
Duplicate of #2224

**Comment by Justin222111** [comment] 2018-05-19 13:45
oh, alright, sorry, should i remove this or something?

**Closed** 2018-05-19 16:20 UTC
