### ISSUE TITLE
FPS counter width issue

### ISSUE THREAD

**Issue by HPApples** [runelite/runelite#2929] opened 2018-05-19 10:01 UTC
Hi,

The FPS counter seems to track the right corner of the window rather than the game therefore this leads to issues with the stretched fixed mode when resizing the window.

https://gyazo.com/bf1f1a910a6b7854ddfb78a0c9d1b420

Thanks HPApples

**Comment by Hydrox6** [comment] 2018-05-19 10:06
Duplicate of #2544, though this issue is more descriptive

**Closed** 2018-05-19 11:32 UTC
