### ISSUE TITLE
Hotkey to alternate zoom amount

### ISSUE THREAD

**Issue by teachable** [runelite/runelite#2783] opened 2018-05-15 23:19 UTC
A feature that I regularly used for Konduit and Osbuddy was the ability to quickly alternate being fully zoomed in and having a regular camera angle with the ability to disable the third party client zoom feature with control + middle mouse click. If RuneLite could add this (or something like this) I'd have no reason to ever touch any client again, not sure if the desire is there beyond me and the Barbarian Assault community though; maybe PKers looking for a QoL upgrade when zooming into their fights?

**Comment by deathbeam** [comment] 2018-05-17 17:52
Duplicate of #919

**Closed by deathbeam** 2018-05-17 17:52 UTC
