### ISSUE TITLE
Gaining slayer exp from other sources (such as slayer tomes from Temple Trekking) count as kills for slayer tasks

### ISSUE THREAD

**Issue by gwilliamsmith** [runelite/runelite#7984] opened 2019-02-23 04:01 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Using a slayer tome reward from Temple Trekking erroneously counts as a kill of an assigned monster for a slayer task. Checking the remaining kills via an enchanted gem/slayer helm confirms that the actual count has not changed.

**To Reproduce**
1. Get a slayer tome reward from Temple Trekking
2. Use the slayer tome while on a slayer task, with the Task InfoBox open
3. The remaining kill count will go down by one
4. Checking the number of kills remaining using a slayer helm/enchanted gem will reset the Task InfoBox to the appropriate value

**Expected behavior**
Using a slayer tome reward should not reduce the remaining kills needed.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.13.1
 - Launcher version: unknown
**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Nightfirecat** [comment] 2019-02-23 04:26
Related to/duplicate of #1865

**Comment by Hydrox6** [comment] 2020-07-31 21:05
With the approach used in commit 67030e38a44f355a0131cff5250ed45c7b01dc53, it might actually be possible to fix this issue. More testing is needed though.

**Comment by Cyborger1** [comment] 2021-05-18 18:19
I'd like to add that receiving Slayer xp from Tears of Guthix also causes this issue.

**Comment by Adam-** [comment] 2023-02-26 02:46
fixed in 1f6ae893d732cf3a022fe6d9662cd2a42ff2b217

**Closed by Adam-** 2023-02-26 02:46 UTC
Labels: bug
