### ISSUE TITLE
Bank Viewer Addon

### ISSUE THREAD

**Issue by JohnSmith12345623** [runelite/runelite#4623] opened 2018-08-01 20:56 UTC
An addon to view your bank while you are not at a bank.

Implementation would go like this. When the player opens the bank the addon will store all the items on the client. When the user clicks the addon tab, the items will be displayed.

**Comment by Kamielvf** [comment] 2018-08-01 20:59
Duplicate of #4343

**Closed** 2018-08-01 21:00 UTC
