### ISSUE TITLE
Faster Hotkey option

### ISSUE THREAD

**Issue by EVOuser94** [runelite/runelite#6343] opened 2018-11-04 14:59 UTC
Make it where you can bind Numkeys in place of F keys for swapping between inventory/prayer/skills/magic book easier.

**Comment by raiyni** [comment] 2018-11-04 15:01
Just use AHK

**Comment by ShwekBoii** [comment] 2018-11-04 16:50
@raiyni Might as well say the same about WASD camera.

**Comment by deathbeam** [comment] 2018-11-04 16:51
Duplicate of #5070

**Closed by deathbeam** 2018-11-04 16:51 UTC
