### ISSUE TITLE
Make hover text more useful on Hi-Scores

### ISSUE THREAD

**Issue by chasef** [runelite/runelite#6872] opened 2018-12-08 10:21 UTC
https://i.imgur.com/psJFDbe.png

I suggest we list what these things are on hover over, as it's not clear to most users what all but the clue scroll actually *mean*

**Comment by jakewilson** [comment] 2018-12-09 02:04
I think that's already enabled:
![screen shot 2018-12-08 at 9 04 02 pm](https://user-images.githubusercontent.com/3004336/49692613-d70ebc00-fb2c-11e8-85f9-ad250b02a2a4.png)

**Comment by SomeZer0** [comment] 2018-12-09 21:18
I think he means that they should have a title when you hover over them

For example, on clues, it would add "Clue Scrolls:" on a line above what's already displayed, and something similar for the others (BH / BH Rogue / LMS)

**Comment by Nightfirecat** [comment] 2018-12-09 23:53
@chasef Can you elaborate what you mean? It seems fairly understandable to me.

**Comment by chasef** [comment] 2018-12-10 03:14
The red and green skulls as well as the icon above the green one

**Comment by chasef** [comment] 2018-12-10 03:17
@jakewilson yeah for clue scrolls but the other 3 only show rank and no indication of what they actually represent

**Comment by deathbeam** [comment] 2018-12-10 07:04
Duplicate of #6368

**Closed by deathbeam** 2018-12-10 07:04 UTC
