### ISSUE TITLE
move fps

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#2301] opened 2018-05-03 17:59 UTC
![image](https://user-images.githubusercontent.com/37475765/39594230-f4cfcc8c-4f03-11e8-8526-75f264cc21a7.png)
move the fps on the right side where the arrow is pointing and we should able to toggle on and off if we want to see mem:..... example me i dont like seeing mem...

the other reason i want it to be moved to the right is this 
![image](https://user-images.githubusercontent.com/37475765/39594265-1765e7c2-4f04-11e8-89d3-7901b9fdc09a.png)
i can hardly see the 'X' at bank so ,please move the fps

**Comment by Adam-** [comment] 2018-05-05 01:46
Duplicate of #1870

**Closed by Adam-** 2018-05-05 01:46 UTC
Labels: feature-request
