### ISSUE TITLE
!task chat command

### ISSUE THREAD

**Issue by Digbigpig** [runelite/runelite#7376] opened 2019-01-15 22:45 UTC
I didn't see any open issues for the !task chat command.

I'll start working on this over the next few days/week. 
Feel free to discuss which format you think we should use for the message in the comments.

**Comment by deathbeam** [comment] 2019-01-15 22:46
Duplicate of #798

**Comment by deathbeam** [comment] 2019-01-15 22:46
This is not google, page 2 (and 3) has valid results too :d

**Closed by deathbeam** 2019-01-15 22:46 UTC
