### ISSUE TITLE
add an option to set "wasd" to rotate camera

### ISSUE THREAD

**Issue by Arkantos500** [runelite/runelite#4617] opened 2018-08-01 15:27 UTC
Hi! In OSBuddy there's an option that lets you rotate the camera with "wasd" instead of arrow keys. This is very useful so that you don't have to move your hand everytime you want to rotate the camera. If you want to chat something you press "enter" and write whatever you want to say. Can you add this option or something similar?

**Comment by Nightfirecat** [comment] 2018-08-01 16:15
Duplicate of #1008

**Closed** 2018-08-01 16:17 UTC
