### ISSUE TITLE
Have loot tracker track over a login sessions rather than client lifetime

### ISSUE THREAD

**Issue by CONNELD** [runelite/runelite#6906] opened 2018-12-11 16:31 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Adam-** [comment] 2018-12-11 16:35
duplicate of #4671

**Closed by Adam-** 2018-12-11 16:35 UTC
