### ISSUE TITLE
XP Orb not disappearing after catching Impling

### ISSUE THREAD

**Issue by tgeene** [runelite/runelite#6588] opened 2018-11-19 18:10 UTC
This is an issue my wife is having with her client. After catching a random impling (unsure if issue only happens on certain impling types) the XP Orb will stay on the screen until a complete reload of the RuneLite client. She told me she has tried logging out and back in as well as clearing her xp tracker.

 - OS: Windows 10

**Comment by raiyni** [comment] 2018-11-19 18:15
The globe or what?

Going to need a screenshot for this one.

**Comment by tgeene** [comment] 2018-11-19 21:02
Okay, so I have more information and a screenshot highlighting what I am talking about.

According to her, what happens is she catches an impling while doing agility. If she goes right back to doing agility the Hunter XP Orb won't disappear, but if she waits before going back to agility the orb will disappear.

Screenshot: https://imgur.com/a/NOOPJdF

**Comment by daviscook477** [comment] 2018-11-25 06:00
I couldn't reproduce the issue by:
1. doing an agility obstacle (and seeing the agility orb appear)
2. immediately burying a bone (and seeing the prayer orb appear)
3. returning to agility immediately and continuing to do obstacles
the prayer orb did disappear as expected after a while of doing agility and not burying bones.

so perhaps this issue is particular to imp catching and hunter?

**Comment by deathbeam** [comment] 2018-11-25 10:08
This should be already fixed in master branch

**Closed by deathbeam** 2018-11-25 10:08 UTC
Labels: bug
