### ISSUE TITLE
Suggestion: Scythe damage consolidation

### ISSUE THREAD

**Issue by aidanrwt** [runelite/runelite#12038] opened 2020-06-30 04:31 UTC
It's nice to know exactly how much damage you deal on every attack. Adding up the 3 hitsplats from every single scythe attack can be distracting.

An optional plugin which consolodates all of the scythe's damage from every attack into one hitsplat would be great.

**Comment by Matsyir** [comment] 2020-09-22 15:22
I don't think it's possible for us to add new hitsplats or modify existing ones (aside from just not displaying them), but I'm not certain. Alternative suggestion in case it's not possible: estimate hitsplats/damage dealt alongside xp drops (if they contain HP). I'm not sure if this would be viable when xp drop grouping is off, but I'd imagine it should be simple if grouping is on. Might be tricky for some magic weapons, but it could just be for melee/range. This might raise balancing concerns for pvp though (my idea, not yours).

**Comment by Nightfirecat** [comment] 2021-01-22 05:07
Duplicate of #11653

**Closed by Nightfirecat** 2021-01-22 05:07 UTC
Labels: duplicate
