### ISSUE TITLE
World Map

### ISSUE THREAD

**Issue by blancoek** [runelite/runelite#2103] opened 2018-04-28 18:35 UTC
Hi, is there a chance the instance map could be reworked into a world map like OSBuddy's? I like it that it shows up to where the game is rendered but I feel like OSBuddy's is much more useful since I can move the map's position, which helps a lot for getting to where one would want to. Also, since the helper for coordinate clue scrolls is _kind of_ useless, it would be nice if the map would also show world coordinates so that it's easier to get _close_ to the clue scroll's spot. I know there's a world map already but Jagex's is WAY too slow.

**Comment by deathbeam** [comment] 2018-04-28 20:34
Duplicate of #1067

**Closed by deathbeam** 2018-04-28 20:34 UTC
