### ISSUE TITLE
timetracking: Add ability to display specific patches in a dedicated tab

### ISSUE THREAD

**Issue by asmith-personal** [runelite/runelite#13293] opened 2021-03-01 10:34 UTC
**Is your feature request related to a problem? Please describe.**
The time tracking plugin doesn't allow for a single-pane view of how the specific patches I care about are doing. 

When I log in for the day, I have to click a number of different tabs to figure out what I need to go do (herb, tree, fruit tree, special, etc...) or I have to parse out the specific items I care about from the overview tab. Neither of these solutions work very well.

**Describe the solution you'd like**
Have a section dedicated to "Notification-enabled" patches where anything with notifications turned on appears there. Could drop it in the 'timers/stopwatches' tab if there's concern over messing up the 2x6 tab layout.

Having this single-pane view would easily let users see "ok seaweed/herbs/fruit trees should be done, so I'll grab supplies to replant those, but my hardwood/mushrooms/hespori aren't so I won't grab those."

**Describe alternatives you've considered**
Secondary tracking mechanism for what does/doesn't appear in this new pane instead of using the notification status, although a second button on each patch/birdhouse might make things cluttered.

**Additional context**
Happy to implement this myself if I could get pointed in the right direction by someone who already knows the timetracking plugin. @Hannah-GBS seems to be a recent contributer, dunno if they'd be up for it.

**Comment by Hydrox6** [comment] 2022-02-27 11:06
Duplicate of #3056

**Closed by Hydrox6** 2022-02-27 11:06 UTC
Labels: feature-request
