### ISSUE TITLE
Session Stats for Loot Tracker

### ISSUE THREAD

**Issue by KakronPrime** [runelite/runelite#11963] opened 2020-06-23 16:49 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to have my drops tracked all the time. However I find being able to track my session loot more useful thus end up resetting my loot tracker often.

**Describe the solution you'd like**
A separate tab within the loot tracker widget that tracks session loot.

**Comment by Hydrox6** [comment] 2020-06-23 16:56
Duplicate of #10346

**Closed by Hydrox6** 2020-06-23 16:56 UTC
