### ISSUE TITLE
Top item value in active bank tab

### ISSUE THREAD

**Issue by joshuaboele** [runelite/runelite#4789] opened 2018-08-08 21:20 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

It would be very helpful to be able to track down what makes your bankvalue the number you see on top

**Describe the solution you'd like**

I'd love to see a feature like Runeloader had, i.e a row/tab of your most valuable items in the active tab. This would make it easy to check out value you have laying around.

**Comment by Abextm** [comment] 2018-08-11 07:37
Duplicate of #4649

**Closed by Abextm** 2018-08-11 07:37 UTC
Labels: duplicate
