### ISSUE TITLE
Suggestion: Add thieving plug-in/notification for dodgy necklace.

### ISSUE THREAD

**Issue by Symplystic** [runelite/runelite#3031] opened 2018-05-20 20:45 UTC
Much like you get idle notifications etc when the screen flashes red. Could someone add this for the dodgy necklace for when it breaks. Would help people who are thieving to remind them to equipped a new one. If flashing the screen is to much maybe highlight the next dodgy necklace in green in the inventory when it breaks for a small reminder ? 

Many thanks

**Comment by deathbeam** [comment] 2018-05-20 21:56
Duplicate of #504

**Closed by deathbeam** 2018-05-20 21:56 UTC
