### ISSUE TITLE
Update time tracking on casting geomancy

### ISSUE THREAD

**Issue by jorisreichert** [runelite/runelite#11075] opened 2020-03-26 10:32 UTC
**Related problem**
When using mobile, or especially when using the Kronos anima patch, the time tracking plugin loses it's value to keep track of your farming patches.

**The solution I'd like**
Casting the Lunar spell Geomancy retrieves most of the usefull data for the time tracking plugin. It would be great it the plugin could update it's times when you cast Geomancy.

**Alternatives I've considered**
Without it, a player has to either remember all possibly relevant patches, make a note of them, or repeatedly cast geomancy.

**Comment by Hydrox6** [comment] 2020-03-26 10:36
Duplicate of #7350

**Closed by Hydrox6** 2020-03-26 10:36 UTC
