### ISSUE TITLE
Add Custom, or different idle notification sounds

### ISSUE THREAD

**Issue by Righca** [runelite/runelite#7052] opened 2018-12-22 03:03 UTC
**Is your feature request related to a problem? Please describe.**
I've always drained out my pc's default notification sound and think it would be cool to have custom or in built Runelite specific sounds :)

**Describe the solution you'd like**
The option to change the idle notification sound

**Describe alternatives you've considered**
Or any other sound that's not the default windows sound

**Comment by deathbeam** [comment] 2018-12-23 09:52
Duplicate of #2060

**Closed by deathbeam** 2018-12-23 09:52 UTC
