### ISSUE TITLE
Tile marker duplication in POH rooms with multiple of same room

### ISSUE THREAD

**Issue by iffyosrs** [runelite/runelite#14283] opened 2021-10-19 03:24 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When a tile marker (or tile marker with text) is placed in a POH room, it appears on that tile in every single copy of that room that is in the POH.
This makes things like tile marking POH portals not feasible.

**To Reproduce**
1. Make multiple copies of the same room in the POH
2. Place a tile marker in one of the rooms
3. All of the copies of that room will have the tile marker

**Expected behavior**
Tile markers should be unique to the tile, not to the room type.

**Screenshots**
https://imgur.com/a/mSarH9V

**Comment by Hydrox6** [comment] 2021-10-19 03:28
Duplicate of #12686

**Closed by Hydrox6** 2021-10-19 03:28 UTC
