### ISSUE TITLE
Unable to enable GPU plugin.

### ISSUE THREAD

**Issue by KrzysztofJeszke** [runelite/runelite#10564] opened 2020-01-07 17:46 UTC
**Describe the bug**
Basically it turns the gpu plugin off after enabling in some seconds

**To Reproduce**
1. Go to '"Configuratiom'
2. Enable on 'GPU'
4. "GPU" plugin turns itself off

**Expected behavior**
I definetly expected it to work with my gpu. It isn't the greatest experience with a dual core embedded processor.

**Enviroment:**
Peppermint 10 (Based on Ubuntu)
 - RuneLite version: 1.6.0.1
 - Launcher version: 2.1.0

**Additional context**
A part of the logs: [Here](https://hastebin.com/raw/nikuponoro)

**Comment by Hydrox6** [comment] 2020-01-07 17:49
Your GPU is not supported
Duplicate of #6552

**Comment by Hydrox6** [comment] 2020-01-07 17:49
For further questions of support, please join the [Discord](https://runelite.net/discord)

**Closed by Hydrox6** 2020-01-07 17:49 UTC

**Comment by tugendbold** [comment] 2021-05-08 01:58
I wish you fools would provide a more useful analysis rather than "your GPU is not supported", this happens for people with modern installs of Java 8/OpenJDK 15 even and top of the line hardware, don't be so vain and useless.

**Comment by aHooder** [comment] 2021-05-08 02:01
What prompted you to resurrect this issue?

People regularly get support in RuneLite's Discord and there's a wiki page dedicated to troubleshooting GPU issues [here](https://github.com/runelite/runelite/wiki/GPU-FAQ).

**Comment by tugendbold** [comment] 2021-05-08 02:08
Because that FAQ references the same, blasé response of "not supported fuck off" and immediately closing the thread, without even pointing the user in the right direction, it's a really shitty response. 

Are there rules are commenting on an issue that I'm not aware of, as I am facing the same issue to no avail following all documented troubleshooting steps- I have a feeling if I join your Discord to ask about it, I'll get the same "fuck off" response and be told to re-read that FAQ page somehow?
