### ISSUE TITLE
2005 gameframe inventory sprite

### ISSUE THREAD

**Issue by Gongor** [runelite/runelite#6734] opened 2018-11-29 12:01 UTC
the inventory sprite is incorrect, small size and missaligned,
here is the real one you can crop the bag sprite and re add it to runelite 
https://i.gyazo.com/6b911462549bcbed938ace551d46717f.png

**Comment by deathbeam** [comment] 2018-11-29 12:09
Duplicate of #6041

**Comment by deathbeam** [comment] 2018-11-29 12:09
Oh actually

**Comment by deathbeam** [comment] 2018-11-29 12:12
And also I am pretty sure our inventory sprite is correct

**Closed** 2018-11-30 09:16 UTC
