### ISSUE TITLE
Client randomly crashes, repeatedly

### ISSUE THREAD

**Issue by christopher-caldwell** [runelite/runelite#14815] opened 2022-03-31 23:04 UTC
**Describe the bug**
At random times, under normal load, the client will crash. 

**To Reproduce**
- MacOS
- Enable GPU plugin ( potentially relevant )
- Play game?

**Expected behavior**
Client doesn't crash

**Screenshots**
GitHub won't allow me to post the error log from crash as it's too long.
![Screen Shot 2022-03-31 at 5 03 50 PM](https://user-images.githubusercontent.com/62559469/161163618-cf7c15ca-abe0-4158-b9c6-f9a8fd412aef.png)

</details>

**Environment (please complete the following information):**
 - OS: macOS, 32gb RAM, 2.3GHz i7
 - RuneLite version: 2.4.3
 - Launcher version: I don't think I have a different version for the launcher?
 - 
**Additional context**
Can provide crash logs, but I'm sot sure which is applicable. `jvm_crash_pid_41854.log` ◀️ They are all like this with different PIDs.

GitHub won't let me post the error as it's too long.

**Comment by Nightfirecat** [comment] 2022-03-31 23:12
Please upload the most recently-creatd jvm_crash_pid file, that will include more information.

**Comment by christopher-caldwell** [comment] 2022-03-31 23:32
[jvm_crash_pid_16062.log](https://github.com/runelite/runelite/files/8393643/jvm_crash_pid_16062.log)

**Comment by Adam-** [comment] 2022-04-01 01:38
This is crashing in the Apple Intel GL driver:

```
C  [AppleIntelICLGraphicsGLDriver+0x1992dd]  gldExecuteKernel+0x7d
C  [OpenCL+0x12eb4]  clFlush+0xc747
C  [OpenCL+0x2ae6a]  clSetEventCallback+0x1553
C  [OpenCL+0x2cdc4]  clCreateCommandQueueWithPropertiesAPPLE+0xb39
C  [libdispatch.dylib+0x2cc9]  _dispatch_client_callout+0x8
C  [libdispatch.dylib+0x8cee]  _dispatch_lane_serial_drain+0x2b8
C  [libdispatch.dylib+0x97c8]  _dispatch_lane_invoke+0x16e
C  [libdispatch.dylib+0x137e1]  _dispatch_workloop_worker_thread+0x2f6
C  [libsystem_pthread.dylib+0x308f]  _pthread_wqthread+0x146
C  [libsystem_pthread.dylib+0x201b]  start_wqthread+0xf
```

We probably don't know why and can't figure out why. This is specifically crashing in the compute stuff though so if you disabled "use compute shaders" it may workaround it.

**Comment by peroa** [comment] 2022-04-27 02:48
I've seen two crashes today that seem to be caused by the GpuPlugin. Pasting the relevant snippets from my client.log file below in case they are relevant or helpful. Both crashes occurred while I was standing still in the GE, not moving nor looking around. This is on an M1 chip, RuneLite version: 1.8.18.3. Launcher version: 2.1.5

> 2022-04-26 13:11:19 [pool-6-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - non-echo reply
2022-04-26 13:24:00 [pool-6-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - non-echo reply
2022-04-26 13:40:02 [Client] ERROR client-patch - Client error: null
java.lang.RuntimeException: java.lang.NullPointerException
	at jogamp.nativewindow.macosx.OSXUtil.RunOnMainThread(OSXUtil.java:324)
	at net.runelite.client.plugins.gpu.GpuPlugin.invokeOnMainThread(GpuPlugin.java:1824)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1123)
	at ao.b(ao.java:50290)
	at ao.run(ao.java:340)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at net.runelite.client.plugins.gpu.GpuPlugin.prepareInterfaceTexture(GpuPlugin.java:1165)
	at net.runelite.client.plugins.gpu.GpuPlugin.drawFrame(GpuPlugin.java:1186)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$draw$9(GpuPlugin.java:1123)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:143)
2022-04-26 14:02:45 [AWT-EventQueue-0] INFO  c.f.controller.DataHandler - storing data

and
> 2022-04-26 17:54:42 [Client] INFO  c.f.controller.FlippingPlugin - $$$$$$$ has just logged in!
2022-04-26 17:54:42 [Client] INFO  c.f.controller.FlippingPlugin - starting slot timers on login
2022-04-26 18:04:06 [Client] ERROR client-patch - Client error: null
java.lang.RuntimeException: java.lang.NullPointerException
	at jogamp.nativewindow.macosx.OSXUtil.RunOnMainThread(OSXUtil.java:324)
	at net.runelite.client.plugins.gpu.GpuPlugin.invokeOnMainThread(GpuPlugin.java:1824)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1123)
	at ao.b(ao.java:50290)
	at ao.run(ao.java:340)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at net.runelite.client.plugins.gpu.GpuPlugin.prepareInterfaceTexture(GpuPlugin.java:1165)
	at net.runelite.client.plugins.gpu.GpuPlugin.drawFrame(GpuPlugin.java:1186)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$draw$9(GpuPlugin.java:1123)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:143)
2022-04-26 18:11:08 [pool-6-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - non-echo reply
2022-04-26 18:41:49 [pool-6-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - non-echo reply

**Comment by Nightfirecat** [comment] 2022-07-10 04:17
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:17 UTC
Labels: gpu, platform:macos
