### ISSUE TITLE
Musical Metronome - An option to play music in time with game ticks.

### ISSUE THREAD

**Issue by invertedbox** [runelite/runelite#7768] opened 2019-02-08 20:13 UTC
I'm someone that enjoys the music in runescape, but the one time I have to turn it off is when doing anything advanced like boss fighting. This is because most music is out of time with game ticks.

My proposed solution is to make a plugin that when enabled, sets the tempo of all music so beats always land on game ticks. This would mean songs would be slightly faster or slower.

I have heard osrs uses midi's for all music tracks so changing the tempo should be somewhat trivial to implement as speeding up or slowing the music won't affect quality or pitch. Only a new tempo is needed for every track that exists.

**Comment by eioo** [comment] 2019-02-08 23:42
You can't predict the bpm from MIDI file. [Relevant discussion](https://cycling74.com/forums/detect-midi-files-bpm).

**Comment by deathbeam** [comment] 2019-02-11 20:29
Duplicate of #530

**Comment by deathbeam** [comment] 2019-02-11 20:29
And rest of request is nonsense mostly

**Closed by deathbeam** 2019-02-11 20:29 UTC
