### ISSUE TITLE
Ge plugin: Show how many you can afford with the money you have

### ISSUE THREAD

**Issue by TerrorNisse** [runelite/runelite#13312] opened 2021-03-05 15:15 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. When horrible at math it would be nice to easily see how many I can buy with the cash I have in my inventory.

**Describe the solution you'd like**
Show the exact number of how many I can afford in the buy window of ge

**Describe alternatives you've considered**
No alternatives :P

**Additional context**
https://i.imgur.com/A225mKw.png

**Comment by Hydrox6** [comment] 2021-03-05 15:17
Duplicate of #8912

**Closed by Hydrox6** 2021-03-05 15:17 UTC
