### ISSUE TITLE
Saving runelite configuration presets

### ISSUE THREAD

**Issue by Twiglet1022** [runelite/runelite#4105] opened 2018-06-30 12:43 UTC
**Is your feature request related to a problem? Please describe.**
The particular settings I like to use vary by activity. It can take a while to go through multiple settings when switching between activities.

**Describe the solution you'd like**
The ability to save and give a name to various configuration presets.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by deathbeam** [comment] 2018-06-30 14:09
Duplicate of #2220

**Closed by deathbeam** 2018-06-30 14:09 UTC
