### ISSUE TITLE
Client Fullscreen Issue

### ISSUE THREAD

**Issue by Stryder123** [runelite/runelite#9715] opened 2019-08-22 01:06 UTC
Runelite will not go fullscreen on the client. 

I had a runelite client that would go fullscreen earlier, but was having this issue https://github.com/runelite/runelite/issues/1449 . I redownloaded the runelite client from the website and now it will not go fullscreen. See picture
![image](https://user-images.githubusercontent.com/54382739/63478342-17aa2d80-c44f-11e9-938b-a83e1c6d44c2.png)

**Comment by Alexsuperfly** [comment] 2019-08-22 01:09
duplicate of #9696
try the launcher at this [comment](https://github.com/runelite/runelite/issues/9696#issuecomment-522385946) in the issue

**Comment by Stryder123** [comment] 2019-08-24 19:50
I fixed the fullscreen issue but im still having problems with the sidebar glitch #1449. None of the previous solutions have been able to help and i have downloaded a new client twice.

**Comment by Alexsuperfly** [comment] 2019-08-24 19:51
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Stryder123** [comment] 2019-08-24 19:54
I will let you know if this works. thank you for the quick response

**Comment by Stryder123** [comment] 2019-08-24 21:52
This is still an issue. Any other ideas @Alexsuperfly ?

**Comment by Stryder123** [comment] 2019-08-24 21:53
even with the earlier fix 
![image](https://user-images.githubusercontent.com/54382739/63643110-9ee5e400-c68f-11e9-8a7e-db9794c27c20.png)

**Comment by Alexsuperfly** [comment] 2019-08-24 21:55
hop in discord, its more suited to this kind of support

**Comment by Alexsuperfly** [comment] 2019-08-31 15:08
The individual who made this entered the discord and we were able to resolve the issue, it was hw acceleration and after messing around with the different methods to disable it he managed to finally get one to work.
This can be closed now.

**Closed** 2019-08-31 15:09 UTC
