### ISSUE TITLE
[Feature Request] Notify on XP-Giving Random Events

### ISSUE THREAD

**Issue by DivineInsanity** [runelite/runelite#3187] opened 2018-05-24 06:13 UTC
Would it be possible to have a "Random Event" plugin that gives a notification (similar to idle notifications) on a Genie or Classroom random event spawning? Help with afk'ing and not missing useful or wanted random events (i know some Irons like the Herb giving one, and possibly people looking to finish outfits / music).

**Comment by deathbeam** [comment] 2018-05-24 06:15
Duplicate of #1634

**Closed by deathbeam** 2018-05-24 06:15 UTC
