### ISSUE TITLE
Status Bar - Right Bar Disappears 

### ISSUE THREAD

**Issue by DaddiJad** [runelite/runelite#18613] opened 2024-12-14 23:38 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

11

### Bug description

When I hover over food, the "Right" bar disappears and the number on Left bar disappears. 
Does not matter what the right bar is showing, I have prayer selected. 

### Screenshots or videos

![image](https://github.com/user-attachments/assets/db88caed-46c0-46e5-a83d-05aac0e7d01a)

![image](https://github.com/user-attachments/assets/5e0c54a7-0e2c-4c85-aeb1-bcda4952767c)

### RuneLite version

1.10.46.1
2.6.3

### Logs

[launcher.log](https://github.com/user-attachments/files/18138159/launcher.log)
[client.log](https://github.com/user-attachments/files/18138160/client.log)

**Comment by Felanbird** [comment] 2024-12-14 23:42
Equip a piece of armour, it will be fixed by 00e6d98fd5b65f218802fd6d08aeabeec12c20cc in the next RuneLite version

**Closed by Felanbird** 2024-12-14 23:42 UTC
Labels: needs-triage

**Comment by DaddiJad** [comment] 2024-12-14 23:45
thanks!

**Comment by FistBumpXD** [comment] 2025-01-11 07:28
I can confirm this is still an issue thank you for the fix though

**Comment by cdfisher** [comment] 2025-01-11 08:58
> I can confirm this is still an issue thank you for the fix though

That's because there hasn't been a release since the change was made. The issue will be resolved with the next RuneLite release.
