### ISSUE TITLE
Client Sway

### ISSUE THREAD

**Issue by tremus2** [runelite/runelite#9030] opened 2019-06-05 15:22 UTC
When you drink a keg of beer, the client doesn't sway like it does on the official client. I can see why this would be beneficial for most circumstances but is it possible to make an exception for drinking a keg of beer because without it you don't get the full experience. Thanks.

**Comment by deathbeam** [comment] 2019-06-05 15:23
Duplicate of #7585

**Closed by deathbeam** 2019-06-05 15:23 UTC
