### ISSUE TITLE
Custom Camera Turn Speed

### ISSUE THREAD

**Issue by Arithium** [runelite/runelite#13141] opened 2021-02-02 22:57 UTC
**Is your feature request related to a problem? Please describe.**
The camera spins pretty slow when using the arrow keys on the keyboard.

**Describe the solution you'd like**
The ability to turn the camera at a faster or slower speed, depending on what the user sets it to.

**Comment by Nightfirecat** [comment] 2021-02-02 23:04
Duplicate of #7744

**Closed by Nightfirecat** 2021-02-02 23:04 UTC
Labels: duplicate
