### ISSUE TITLE
Skilling Tracker similar to Loot Tracker

### ISSUE THREAD

**Issue by Vgamer989** [runelite/runelite#12197] opened 2020-07-20 22:03 UTC
I prefer to do Skilling over combat for money making. I know the loot tracker is great for showing value of drops, so I'm looking for a plug-in that does the same thing, but for skills. That way, I can quickly see profit made from mlm or wc without checking bank/inventory prices.

PS: I'm a amateur coder, but if this is doable, I would be willing to help contribute.

**Comment by Hydrox6** [comment] 2020-07-21 09:16
Duplicate of #4126

**Closed by Hydrox6** 2020-07-21 09:16 UTC
