### ISSUE TITLE
Add hotkey for toggling Entity Hider plugin

### ISSUE THREAD

**Issue by QuestingPet** [runelite/runelite#13806] opened 2021-06-28 22:28 UTC
**Is your feature request related to a problem? Please describe.**
Turning the entity hider plugin on and off is useful for certain activities, like skilling in peace, or during HM bloat because it's hard enough to see the falling hands while straining your eyes but then teammates running around everywhere just make it that much worse and then you end up getting handing the ONE second that you look to your inventory to switch to your chally and then you miss your last hit while brewing to tank the stomp and flies and end up pking a teammate around the corner and having a 3-4 down bloat just to reset anyway and continue the cycle.     /rant

**Describe the solution you'd like**
A (optionally configurable) hotkey to disable and enable the Entity Hider plugin. This could potentially be abstracted to allow for *any* plugin(s).

**Describe alternatives you've considered**
Remember to turn off Entity Hider before Nylo so everyone isn't just a bunch of floating names, though having to move the mouse all the way to the config panel at the top-right and click the radio button proves too difficult for tobbers. Don't even get me started on if "Entity Hider" is no longer showing in the list of plugins because you cleared it for some reason.

Another alternative is just getting good and not relying on Entity Hider anymore for Bloat HM. Unfortunately, my friends insist on using it and always forget to turn it back off and complain. I'm making this issue so that I don't have to hear the complaints anymore (and as someone who used to use Entity Hider for Bloat HM but stopped because I got too lazy to turn it back off, I might go back to doing that now).

**Additional context**
Jagex, please make those shadows *any* amount easier to see so I don't lose my eyesight pre-30 years old.

**Comment by Nightfirecat** [comment] 2021-06-28 23:40
Duplicate of #2686

**Closed by Nightfirecat** 2021-06-28 23:40 UTC
Labels: duplicate
