### ISSUE TITLE
Let us change which system sound notifications use

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2275] opened 2018-05-03 00:59 UTC
If any plans to make it the notification sound play from the client itself are shelved for the forseeable future, is it possible (and easier) to allow us to change the OS sound used? I assume this is possible because on Windows 8.1 it plays from the 'Default Beep' and not the 'Notification' sound. Would be nice to change the sound it plays from to something that is basically never played otherwise, to curtail any annoyance on hearing system sounds that I don't want or need.

**Comment by LeviSchuck** [comment] 2018-05-03 01:02
I plan to do something like that, relying on the client itself to play a selectable sound. For example, a duck quack. Constants for this were introduced in my PR #1546.

External sounds are another possibility, for example rune loader (defunct) allowed one to select a wav file to play on idle. I personally selected a "thump" sound from an air pipe as it wasn't searing to my ears.

Still, I'd like RL to quack at me.

**Comment by Jalopyy** [comment] 2018-05-03 01:08
Obviously Runelite not using an OS sound would be the end goal in mind for me (I don't like Chrome pinging me when my ctrl+f gets zero results for every letter until I stop typing).

I just assume doing that takes a lot more code work than just having a drop down list of what system sounds/locations the notification can be played from.

**Comment by deathbeam** [comment] 2018-05-03 08:13
I don't like adding user ability to select their own .wav file. We should just provide some selected list and use that, or, just use some default sound and don't even give the choice to the user.

**Comment by Jalopyy** [comment] 2018-05-03 08:38
Honestly at the end of the day I don't care about sound file customization, I just suggested this because I thought it'd be easier to implement than the eventual making the sound play from Runelite itself and not use hook the OS events for sounds.

**Comment by deathbeam** [comment] 2018-05-08 18:25
Duplicate of #920

**Closed by deathbeam** 2018-05-08 18:25 UTC
Labels: feature-request
