### ISSUE TITLE
Bank Value Ignore Graceful

### ISSUE THREAD

**Issue by Adam-F-Foster** [runelite/runelite#13007] opened 2021-01-04 21:01 UTC
**Is your feature request related to a problem? Please describe.**
I'm always a little sad when I see my bank value while saving up for something and then realize that 2M of it is in graceful/marks.

**Describe the solution you'd like**
I think a toggle in the Bank settings to be able to ignore the cost of graceful/marks would be nice.

**Describe alternatives you've considered**
Honestly I don't know if there is a good alternative to a simple toggle in settings.

**Additional context**
![with](https://user-images.githubusercontent.com/8825263/103579299-0b890980-4ea6-11eb-89cc-d2bf3e2bd2ff.png)
![without](https://user-images.githubusercontent.com/8825263/103579306-0e83fa00-4ea6-11eb-86a7-78cd3e42b607.png)

**Comment by Hydrox6** [comment] 2021-01-04 21:06
Duplicate of #7053

**Closed by Hydrox6** 2021-01-04 21:06 UTC
