### ISSUE TITLE
Update the RC Pouches to display held essence when using Bank Fill

### ISSUE THREAD

**Issue by MidnightBree** [runelite/runelite#5677] opened 2018-09-27 19:13 UTC
Currently, the number only displays if you fill the pouches outside of the bank.
![image](https://user-images.githubusercontent.com/22117752/46168974-df629500-c267-11e8-9e0a-726eb97fc370.png)

**Comment by deathbeam** [comment] 2018-09-27 19:17
Duplicate of #5667

**Closed** 2018-09-27 19:17 UTC
