### ISSUE TITLE
Hovering mouse tooltips not showing up after latest update

### ISSUE THREAD

**Issue by hofferjo1** [runelite/runelite#5089] opened 2018-08-23 20:26 UTC
Hovering Mouse Tooltips (i beilieve they would be called) are not showing up after the update today.
What I  mean by this is that when I hover my mouse over items, objects, NPC's etc there is not a text that appears (as in the text in top left part of screen, which still appears for me) in the little box like usual.  I dont know if this is unique to my client  or if this is a widespread issue?  Tried looking through  all the settings and I definitly has tooltips turned on.  Tried restarting client to no avail.  Thank you for an amazing free product!

**Comment by deathbeam** [comment] 2018-08-23 20:27
Duplicate of #5080

**Closed by deathbeam** 2018-08-23 20:27 UTC
