### ISSUE TITLE
'Ignore NPC' list for loot tracker

### ISSUE THREAD

**Issue by reowmeowmew** [runelite/runelite#9748] opened 2019-08-27 12:04 UTC
I like to keep bosses/good drops in my loot tracker, but often have to reset a bunch of different things I kill throughout the day/week to make it so they're not there anymore taking up space.

I know you can now collapse each one to help a little bit, but I think it would be nice to have a right click 'do not track' to add certain monsters to that list, and a button to view your filtered list.

https://i.imgur.com/eYJ3K5A.png

Would be nice to completely get rid of all this ever even being tracked

**Comment by Hydrox6** [comment] 2020-01-28 22:28
Duplicate of #7482

**Closed by Hydrox6** 2020-01-28 22:28 UTC
Labels: feature-request
