### ISSUE TITLE
Feature request - add the ability to use custom 35x35 animated cursors 

### ISSUE THREAD

**Issue by dappersnapper456** [runelite/runelite#2892] opened 2018-05-18 20:00 UTC
I think the ability to use these would be sweet:

http://www.cursors-4u.com/animated/
http://www.totallyfreecursors.com/category.cfm/id/4/Animated.htm
etc.

**Comment by jplsek** [comment] 2018-05-18 20:01
Somewhat duplicate of #2068

**Comment by dappersnapper456** [comment] 2018-05-18 20:13
http://www.rw-designer.com/cursor-set/runescape-jagex-animated-dragon- omg this needs to be added

**Comment by deathbeam** [comment] 2018-05-18 23:26
Duplicate of #2068

**Closed by deathbeam** 2018-05-18 23:26 UTC
