### ISSUE TITLE
Prayer boost indicator and task infobox keep moving to default location

### ISSUE THREAD

**Issue by idniilzo** [runelite/runelite#3849] opened 2018-06-16 19:57 UTC
Everytime I reset the client both indicators jump from location I choose ( bottom right of the screen) to the default location (below the stat boost indicator- top left).

**Comment by deathbeam** [comment] 2018-06-16 19:59
Duplicate of #3799

**Comment by deathbeam** [comment] 2018-06-16 19:59
This has been already fixed in master, but it is not in release yet

**Closed by deathbeam** 2018-06-16 19:59 UTC
