### ISSUE TITLE
'Ignore NPC' list for loot tracker

### ISSUE THREAD

**Issue by Quoze** [runelite/runelite#10284] opened 2019-11-17 16:25 UTC
The loot tracker is amazing. Also, the feature where you can ignore certain items is amazing, and ignoring things like Xerics Aids and Prayer Enhances stops the loot from Tekton and Vasa appearing on my loot tracker, which I love.
My suggestion is to add a list of 'Ignored NPC's' like Vasa and Tekton, so any loot from that specific monster wouldn't be added to the tab. A good example where this feature would be beneficial is for when I do my master clues; I usually have to kill ancient wizards and brassican mages which I do not care about tracking their loot. They do drop some items that I would otherwise track though, like runes and potions, so ignoring their drop table inst really a solution for me.
Of course I can easily right click and clear their tracked loot, but I think it would be super nice to not have to do this every time I kill something that I have no interest in.
My suggestion is to have the feature work exactly like it already does with items; right clicking an item on the loot tracker enables to you 'Toggle Item', maybe right clicking the NPC title on the loot tracker could show 'Toggle NPC', which will add that NPC to the ignore list.

Thank you for your time.

**Comment by Alexsuperfly** [comment] 2019-11-17 16:26
duplicate of #9748

**Closed** 2019-11-17 16:31 UTC
