### ISSUE TITLE
Varrock museum antique lamps decreases task counter when used on slayer

### ISSUE THREAD

**Issue by adam-bentley** [runelite/runelite#12262] opened 2020-07-31 21:00 UTC
**Describe the bug**
When rubbing an Antique lamp given from the Varrock museum, choosing to give the XP to the slayer skill will cause the slayer plugin counter to decrease by one for each lamp consumed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Complete a fossil island display
2. Rub the lamp, choosing the slayer task
3. Counter will decrease

**Comment by Hydrox6** [comment] 2020-07-31 21:06
Duplicate of #7984

**Closed by Hydrox6** 2020-07-31 21:06 UTC
