### ISSUE TITLE
Bank tags - Withdraw-x option looses tag tab focus.

### ISSUE THREAD

**Issue by MalakaJones** [runelite/runelite#6073] opened 2018-10-18 21:58 UTC
**Describe the bug**
When withdrawing-x from a tag tab, you get pulled out of it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Withdraw-x from a tag tab.
2. Watch yourself being pulled out of the tab.

**Expected behavior**
Keep focus on the tag tab.

**Screenshots**
![bank_tags_wx_bug](https://user-images.githubusercontent.com/15826583/47186636-34417a80-d2ff-11e8-85b6-2462cffcf020.gif)

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - RuneLite version: [1.4.22]
 - Launcher version: [Unknown]

**Comment by deathbeam** [comment] 2018-10-18 22:01
Duplicate of #1297

**Closed by deathbeam** 2018-10-18 22:01 UTC

**Comment by troypressley1** [comment] 2019-02-13 07:44
Still an issues
