### ISSUE TITLE
friend notifier 

### ISSUE THREAD

**Issue by mo3khalifa** [runelite/runelite#2663] opened 2018-05-13 01:34 UTC
can you code it so friends that dont have you added can still be shown on your mini map just like konduit/osbuddy/runeloader

**Comment by CustardGod** [comment] 2018-05-13 01:35
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
Under not currently being considered #951

**Comment by deathbeam** [comment] 2018-05-13 11:52
Duplicate of #951

**Closed by deathbeam** 2018-05-13 11:52 UTC
