### ISSUE TITLE
Suggestion: Add Inventory Viewer Grid Alignment/Snap with Inventory

### ISSUE THREAD

**Issue by Elite386** [runelite/runelite#12042] opened 2020-06-30 21:12 UTC
**Is your feature request related to a problem? Please describe.**
When I'm using inventory viewer I'd like to be able to align the inventory grid with where the grid of the backpack would be. This is easy to do if I don't snap it but I'd like to be able to snap it so I can resize my clients and the inventory viewer stays aligned.

**Describe the solution you'd like**
Currently the Alt-Drag snap spot to the left of the backpack/open tab places the inventory (from what I can tell) on that spot based on the bottom-right corner. I'd like for the widget snap of the inventory viewer grid to be aligned with the inventory grid of the backpack. I'd also like a widget snap added to the top of the inventory.

**Describe alternatives you've considered**
In the plugin itself there could be a preset position so no other plugins need to use a snap and the grid could align based upon a snap point defined only for this plugin.

**Additional context**
Current snap on left: https://i.imgur.com/y6ESpKf.png
Proposed snap for grid to be aligned on top: https://i.imgur.com/yZTQPzD.png
Proposed snap for grid to be aligned on left: https://i.imgur.com/qsYeMR7.png

**Comment by Alexsuperfly** [comment] 2020-06-30 21:37
duplicate of #8515

**Closed** 2020-06-30 23:34 UTC
