### ISSUE TITLE
HiScore plugin - Skotizo/Scorpia kill count swapped post Nex

### ISSUE THREAD

**Issue by twcalder** [runelite/runelite#14576] opened 2022-01-09 18:22 UTC
Since the addition of Nex to the boss kill counts on the Hiscores tab, I've noticed that the kill counts for the bosses Scorpia and Skotizo are displayed the wrong way around. On my ironman for example, who has 9 Skotizo kills and 0 Scorpia kills, the Hiscores tab displays me as unranked in Skotizo and having 9 Scorpia kills.

This issue persisted regardless of Hiscore plugin settings, and even if I reset them.

Of the other boss killcounts I have on my accounts, I see no other issues where they are out of order.

**Comment by Hydrox6** [comment] 2022-01-09 18:23
Duplicate of #14564

**Closed by Hydrox6** 2022-01-09 18:23 UTC

**Comment by twcalder** [comment] 2022-01-09 18:26
> Duplicate of #14564

Apologies, thought I had searched closed items as well but apparently not!
