### ISSUE TITLE
JVM Crash

### ISSUE THREAD

**Issue by CreativeTechGuy** [runelite/runelite#17687] opened 2024-04-05 19:11 UTC
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Occurred when entering an essence mine portal in Guardians of the Rift. It is random as this is the first time it has ever happened to me despite seemingly doing the same thing multiple times, even in this session.

### RuneLite version

RuneLite Version: 1.10.26.4
OldSchool Version: Rev 221

### Logs

[launcher.log](https://github.com/runelite/runelite/files/14889777/launcher.log)
[client.log](https://github.com/runelite/runelite/files/14889778/client.log)
[jvm_crash_pid_10436.log](https://github.com/runelite/runelite/files/14889779/jvm_crash_pid_10436.log)

**Comment by Nightfirecat** [comment] 2024-04-05 19:12
Duplicate of #10628

**Closed by Nightfirecat** 2024-04-05 19:12 UTC
Labels: duplicate
