### ISSUE TITLE
Threshold on coins on the ground

### ISSUE THREAD

**Issue by plaighdoh** [runelite/runelite#8295] opened 2019-03-23 04:45 UTC
**Is your feature request related to a problem? Please describe.**
Cluttered ground if you keep the coins text on when they're on the ground, very annoying in places like KBD lair since he has 1 coin everywhere.

**Describe the solution you'd like**
A setting that would allow you to make a threshold amount to have the coin value show when it's on the ground. Example would be a coin stack of 5k will appear but anything 4999 and below the coins text wouldn't show up like normal black listed items.

**Describe alternatives you've considered**
Maybe monster specific black listed lists but i feel like that would be a lot more work than needs to be done.

**Additional context**
This would make it a lot easier when doing things such as slayer when going from a task that the monsters drop 150-350gp then going to a task that drops 5k+ and not seeing the coin drop because you black listed coins from the last task.

**Comment by Nightfirecat** [comment] 2019-03-23 04:53
Duplicate of #1123

**Closed** 2019-03-23 12:55 UTC
