### ISSUE TITLE
Colour Changing Screen Markers

### ISSUE THREAD

**Issue by Castro3halo** [runelite/runelite#7204] opened 2019-01-06 04:52 UTC
Creating and option for screen markers to change colour based on the last screen marker clicked. This would allow for screen markers to be made for agility courses while always showing the next marker to click as green. Similar for banking and skilling allowing you to create custom screen makers that follow an organised path based on the last screen marker clicked.

**Comment by Spedwards** [comment] 2019-01-06 06:04
Duplicate of #6822

**Closed** 2019-01-06 06:06 UTC
