### ISSUE TITLE
Remove line-smoothing on the XP tracker

### ISSUE THREAD

**Issue by Lorentary** [runelite/runelite#2536] opened 2018-05-10 11:17 UTC
Having plots with lines that curve is pretty and all. However, when looking at a graph of total XP and where the points rise too far an then drops seems strange as XP cannot be decreased in runescape

**Comment by deathbeam** [comment] 2018-05-10 13:27
Duplicate of https://github.com/runelite/runelite.net/issues/56

**Closed by deathbeam** 2018-05-10 13:27 UTC
