### ISSUE TITLE
Sounds not working

### ISSUE THREAD

**Issue by tonydelo1** [runelite/runelite#2782] opened 2018-05-15 22:59 UTC
Not sure if the client itself has sound settings that I've changed accidentally and unknowingly. But I have no game sounds at all and can't seem to find out why. Sounds work on osrs client, and konduit. But not runelite. Please help me fix this

**Comment by sanderdegroot** [comment] 2018-05-17 15:48
Someone mentioned in Discord that this can happen when the client is started in low detail mode - I can confirm this is one potential cause. Try disabling low detail mode and restarting the client.

**Comment by deathbeam** [comment] 2018-05-17 17:52
Duplicate of #696

**Closed by deathbeam** 2018-05-17 17:52 UTC
Labels: duplicate

**Comment by tonydelo1** [comment] 2018-05-17 18:07
So how am I able to fix this issue? 
--------------------------------------------
On Thu, 5/17/18, Tomas Slusny <notifications@github.com> wrote:

 Subject: Re: [runelite/runelite] Sounds not working (#2782)
 To: "runelite/runelite" <runelite@noreply.github.com>
 Cc: "tonydelo1" <tonydelorenzo@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Thursday, May 17, 2018, 1:52 PM
 
 Duplicate of #696
 
 —
 You are
 receiving this because you authored the thread.
 Reply
 to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by deathbeam** [comment] 2018-05-17 18:07
Check https://github.com/runelite/runelite/issues/696
