### ISSUE TITLE
Attack style improvement suggestion

### ISSUE THREAD

**Issue by Meow764** [runelite/runelite#1973] opened 2018-04-26 12:37 UTC
* Attack Styles
  * A threshold for warning (and removing) of selected attack styles
  * Good workaround until support for different settings for different accounts is implemented
  * Example: So you'd set for example defence threshold to 5
    * If you're on an account that is under 5 defence, the defence attack style will be removed (your pure account) 
    * If you're on an account that has higher than 5 defence the attack style will not me removed (your main account)

**Comment by deathbeam** [comment] 2018-04-26 12:40
- 1st point will be solved when support for account related settings will be added, no need for thresholds or anything just to differentiate between mutliple accounts.
- 2nd point is a bit subjective, and adding toggle for it do not makes sense at all. I would just leave it as it is. If that is deal breaker for you, then what can I say.

**Comment by SoyChai** [comment] 2018-04-26 12:42
Thanks for taking the time to offer this feedback, Meow. Would you be able to split up this issue into its two main suggestions? It'd help us refer back to them if somebody starts working on these features, especially when we're ready to mark one of them as resolved.

**Comment by Meow764** [comment] 2018-04-26 12:43
Ok, I'll split it. One sec

**Comment by Meow764** [comment] 2018-04-26 12:46
@deathbeam can you edit your comment, and comment the 2nd part on the new issue I made, so I'll reply there.

**Comment by deathbeam** [comment] 2018-11-26 13:35
We should still implement the account-specific settings first instead of workarounds (and someone is already working on that), so, lets do that, closing this as duplicate of that.

**Closed by deathbeam** 2018-11-26 13:35 UTC
Labels: feature-request
