### ISSUE TITLE
[Suggestion] Ability to adjust metronome plugin sound level.

### ISSUE THREAD

**Issue by Devasten** [runelite/runelite#10579] opened 2020-01-10 05:45 UTC
What the title says, a lot of the time i find i am not able to hear the metronome over game sounds and it would be really helpful to be able to adjust it.

Thank you!

**Comment by Hydrox6** [comment] 2020-01-10 11:55
Duplicate of #10347

**Closed by Hydrox6** 2020-01-10 11:55 UTC
