### ISSUE TITLE
Tree paid for plugin

### ISSUE THREAD

**Issue by ChrisDotson1** [runelite/runelite#8419] opened 2019-04-05 12:00 UTC
**Is your feature request related to a problem? Please describe.**
Yes, sometimes when we click pay on an NPC the chat comes up but we click away on the same tick and lose the payment being processed

**Describe the solution you'd like**
Runelite may be able to detect the payment having gone through and confirm it in the timer section beside the tree - perhaps by the Done at ##:##

**Describe alternatives you've considered**
Another window for payment complete/incomplete, something clear

**Additional context**
I think that's about it, you guys know what you're doing so I don't need to coddle

**Comment by Hydrox6** [comment] 2019-04-05 12:03
Duplicate of #7941

**Closed** 2019-04-05 12:03 UTC
Labels: duplicate
