### ISSUE TITLE
Add fossil island underwater swimming and agility timer

### ISSUE THREAD

**Issue by fortnitelover12** [runelite/runelite#11565] opened 2020-05-13 09:04 UTC
The location of the correct chest/clam changes exactly every 1 minute. Underwater swimming is the most efficient method for training thieving to 200m, so it would be great if a simple timer could be added to make the method more manageable ^_^

**Comment by Hydrox6** [comment] 2020-05-13 09:11
Duplicate of #5334

**Closed by Hydrox6** 2020-05-13 09:11 UTC
