### ISSUE TITLE
Idle Notification not sent when interrupted by interface popup

### ISSUE THREAD

**Issue by zwilkin** [runelite/runelite#9714] opened 2019-08-21 17:22 UTC
**Describe the bug**
A system notification is not sent when a character goes idle due to gaining a level.

**_Example:_**
If a fishing spot depletes/inventory fills up - a system notification is received when the character is idle.
However, if a Fishing level is gained - causing the character to idle - a system notification is not sent.

NOTE: I have already enabled _'Send notifications when focused'_ in the _RuneLite_ settings - it is not that.

**To Reproduce**
1. Start performing a non-combat skill of which you are about to obtain a level.
2. Gain the level, and wait as no notifications are sent even though the character ends up idle.

**Expected behavior**
A system notification should be sent on either a level granted, or properly detect idle status.
_--> It would be really cool to be able to toggle a notification upon a level being achieved!_

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10, Version 1809 _(OS Build 17763.678)_
 - RuneLite version: 1.5.31.1
 - Launcher version: 1.6.0

**Additional context**
N/A

**Comment by Alexsuperfly** [comment] 2019-08-21 17:23
is it only fishing?

**Comment by zwilkin** [comment] 2019-08-21 17:25
> is it only fishing?

I have only been fishing and noticed it. Give me a few minutes to do something else quick and test.

**Comment by zwilkin** [comment] 2019-08-21 17:29
@Alexsuperfly I just tried with fletching and the notification worked perfectly. Maybe it's just something with Fishing?

**Comment by Alexsuperfly** [comment] 2019-08-21 17:30
as i thought, this is a duplicate of #8429 then
ive got a pr to fix that already so maybe your issue brings more attention to it and it can finally get merged

**Comment by zwilkin** [comment] 2019-08-21 17:30
> as i thought, this is a duplicate of #8429 then
> ive got a pr to fix that already so maybe your issue brings more attention to it and it can finally get merged

Oh, Okay cool. I will commetn on #8429 then to hopefully get this further noticed

**Comment by zwilkin** [comment] 2019-08-21 17:32
Re-opened because it contains additional details that may be used/looked at for #8429

**Comment by deathbeam** [comment] 2019-08-23 09:07
I closed #8429 then and updated title of issue

**Comment by rdp1408** [comment] 2019-12-29 20:52
I would love it if this could get fixed.

**Closed** 2020-02-02 18:19 UTC
Labels: bug
