### ISSUE TITLE
Zulrah

### ISSUE THREAD

**Issue by artrown** [runelite/runelite#3710] opened 2018-06-09 08:04 UTC
a plugin would be very good that would make it easier to see the rotations of the zulrah

**Comment by Shieldeh** [comment] 2018-06-09 08:05
There was one, however it was removed as Jagex did not want it in the client. Have a look at https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features to make sure what you are requesting hasn't already been rejected/removed.

**Comment by Abextm** [comment] 2018-06-10 02:09
Duplicate of #1386

**Closed by Abextm** 2018-06-10 02:09 UTC
