### ISSUE TITLE
Remember last opened clue scroll when you have multiple in inventory

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4841] opened 2018-08-11 10:39 UTC
If you have a hard clue and a medium clue in your inventory, and you open and close your hard clue, the clue scroll plugin will give you the solution for the medium clue: https://youtu.be/VC4jQ1wSM3Y

**Comment by JeljoGb** [comment] 2018-08-11 13:10
I think that's only with map clues. Usually it does remember the last clue opened.

**Comment by oplosthee** [comment] 2018-08-11 13:16
To add to this: for challenge clues it doesn't show you the solution when the NPCs asks for it, which can be troublesome if you don't remember the solution.

**Comment by JeljoGb** [comment] 2018-08-11 13:17
That's only for elites, no? Because they're designed differently for some reason.
I think I made a request for that some time ago, or at least, I wanted to.

**Comment by Nightfirecat** [comment] 2018-08-11 17:50
Duplicate of #4607

**Closed** 2018-08-11 17:51 UTC
Labels: bug
