### ISSUE TITLE
"Ready at" change for "Time Tracking > Overview"

### ISSUE THREAD

**Issue by OliverBroadbent** [runelite/runelite#11263] opened 2020-04-14 04:43 UTC
**Is your feature request related to a problem? Please describe.**
I've been thinking for a while about the Overview tab in Time Tracking. I'm pretty sure the "Ready at" is displaying the wrong time when 2 different times are available.

Currently, if for example your fruit tree patches are ready and Calquat will be ready in an hour, in the overview tab you'll see "Ready at xx:xx" under fruit tree patches. The problem with this is that I keep harvesting my fruit trees late, because the the overview told me they weren't ready. This is amplified even more in the Special patches, when Hespori takes days, and cactus takes hours. you never know when it's ready without checking all tabs. It's annoying.

**Describe the solution you'd like**
My suggestion is to change the overview tab to display information on the NEXT ready plot in that category. This way if Hespori still has 24 hours left and my Cactus has 1 hour, i'll know to check back in 1 hour just by looking at the overview tab.

**Image example**
https://imgur.com/a/RxCGSyO

**Comment by Nightfirecat** [comment] 2020-04-14 05:09
Duplicate of #9445

**Closed by Nightfirecat** 2020-04-14 05:09 UTC
Labels: duplicate
