### ISSUE TITLE
cannonballs low notification

### ISSUE THREAD

**Issue by eeennnooo** [runelite/runelite#7465] opened 2019-01-20 18:43 UTC
Choose when you get a notification for how many cannonballs you have left. 

Example: **Cannonball Notification: 5** would notify you when there are 5 cannonballs left
This would give you time to load the cannon before it depletes and stops firing.

original request for this feature:
https://github.com/runelite/runelite/issues/1820

**Comment by deathbeam** [comment] 2019-01-20 21:30
Duplicate of #1820

You even found the duplicate so why you made new issue?

**Closed by deathbeam** 2019-01-20 21:30 UTC

**Comment by eeennnooo** [comment] 2019-01-21 17:58
because it was 10 months old with no activity or even mentioned thereafter??

**Comment by deathbeam** [comment] 2019-01-21 17:59
That is not how issue trackers work

**Comment by eeennnooo** [comment] 2019-01-21 18:13
oops guess i should have just bumped the thread ¯\_(ツ)_/¯ thanks anyway i see a pull request was made
