### ISSUE TITLE
Special counter plugin counting "absolute unit" reflect damage

### ISSUE THREAD

**Issue by vitorebom** [runelite/runelite#14663] opened 2022-02-03 15:04 UTC
I was doing Corp on SRL and noticed that the spec counter plugin would fail to track my spec damage if my absolute unit effect would recoil damage at the moment I used the BGS spec. I then tested with Arclight and the same would happen, the plugin would register the recoil damage as the spec hit.
One thing worth pointing is that the "Damage" counter at Corp would properly pickup weapon damage only and ignore the recoil damage.

**Comment by Hydrox6** [comment] 2022-02-03 15:08
Duplicate of #12008

btw, why the corp plugin works fine is due to the vanilla corp damage overlay; we take the data used from that for your damage.

**Closed by Hydrox6** 2022-02-03 15:08 UTC
