### ISSUE TITLE
SideBar Glitches - Hardware Acceleration Disabled

### ISSUE THREAD

**Issue by lordsherman** [runelite/runelite#12088] opened 2020-07-09 03:23 UTC
**Describe the bug**
I seem to get the well-known sidebar glitchiness in runelite.  I have tried all methods of disabling hardware acceleration and none seem to work.

**Screenshots**
https://prnt.sc/tegk10

**Environment (please complete the following information):**
 - OS: Windows 10 Home Build 18363
 - RuneLite version: 1.6.21.1
 - Launcher version: 2.1.3

PC is running a Ryzen 9 3900X and RTX 2080 Super

Only seem to have gotten this issue on this newer PC I have.  I do not recall it on my last PC though.

**Comment by Nightfirecat** [comment] 2020-07-09 04:11
Duplicate of #11727

**Closed by Nightfirecat** 2020-07-09 04:11 UTC
Labels: duplicate
