### ISSUE TITLE
Item stats are showing on map, chat box and empty spots in inventory

### ISSUE THREAD

**Issue by Monose** [runelite/runelite#7006] opened 2018-12-18 06:05 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
 
Item stats show on map, chat box, and empty spots in inventory instead of just on items.

**To Reproduce**
Steps to reproduce the behavior: shows automatically upon logging in for me

**Expected behavior**

**Screenshots**

https://gyazo.com/dcb2f95bca451a8b8b93b3790980ac58
   
**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by deathbeam** [comment] 2018-12-18 16:58
I never experienced this. So is the tooltip just following your mouse or something?

**Comment by deathbeam** [comment] 2018-12-18 17:01
Duplicate of #5579

**Closed by deathbeam** 2018-12-18 17:01 UTC
Labels: bug, item-stats, needs-information

**Comment by Monose** [comment] 2018-12-18 19:47
Yes it is, but it only follows the mouse over the map, inventory, and chat box. If you move your mouse onto the screen to click on something the tooltip moves to the top left corner and stays there until you mouse back over your inventory or one of the other areas mentioned.
