### ISSUE TITLE
Allowing for different fonts for ground items

### ISSUE THREAD

**Issue by ruiz165** [runelite/runelite#1683] opened 2018-04-19 06:34 UTC
Hello
First off thanks for the absolutely amazing client. 
I was just wondering if it would be possible to make an option to select different fonts for the ground items in the client. I found shrinking the font did make it a bit better, but I really prefer the osbuddy/runeloader fonts a bit more appealing, but I am not going to use those just for fonts. It really is only a small issue personally and really is no big deal. I'd love having the option though. 
Thanks!

**Comment by Kamielvf** [comment] 2018-04-19 06:40
See #1651

**Comment by ruiz165** [comment] 2018-04-19 06:44
@Kamielvf  Thank You for the reference!

**Comment by deathbeam** [comment] 2018-04-19 06:47
Is that what you want? As OSB uses the bold font I think. And adding non-rs font support would destroy the look if that is your request.

**Comment by ruiz165** [comment] 2018-04-19 06:54
@deathbeam #1605 #1651 I think answered my question. Sorry for the confusing post but yes the bold font option is really what i was looking for. I was under the impression that they were just different fonts. Shall I delete the issue?

**Comment by deathbeam** [comment] 2018-04-19 06:55
I will close it as duplicate of #1605 then.

**Closed by deathbeam** 2018-04-19 06:55 UTC
Labels: duplicate, feature-request
