### ISSUE TITLE
multiple highlight colours for ground items plug-in

### ISSUE THREAD

**Issue by red-eye-jedi** [runelite/runelite#13595] opened 2021-05-12 18:01 UTC
**Is your feature request related to a problem? Please describe.** I would like to be able to recolour different ground items different colours that are either all untradable or in the same price bracket.

A clear and concise description of what the problem is** only 1 highlight colour option in ground items

**Describe the solution you'd like**
A clear and concise description of what you want to happen. up to 3 different highlight colours that can be selected and cycled through (clicking the little + sign on a item on the ground would cycle the set colours you have chosen)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.  im not sure but maybe a customisable colour for individual or specific items, though i feel like this could be a bit messy or cause clutter in the settings with too many individual items coloured.

**Additional context**
![image](https://user-images.githubusercontent.com/78451641/118022491-53d49e80-b354-11eb-9c67-353b12ebe9bf.png)

i would like to colour the mallignum root planks differently to secondaries and would also like to change the colour of the iron axe and lockpick seperately too. its a minor but nice quality of life update (:

**Comment by raiyni** [comment] 2021-05-12 18:04
duplicate of https://github.com/runelite/runelite/issues/12274

**Closed by raiyni** 2021-05-12 18:04 UTC
