### ISSUE TITLE
Runelite Tabs for multiple game sessions

### ISSUE THREAD

**Issue by stoddy15** [runelite/runelite#11449] opened 2020-05-03 16:48 UTC
I currently use 3rd party software to get this to work. I think it would be a good feature to implement into the actual client. Jagex allows multi logging. I know this is possible to code because bot clients do it and they use java

100's of people are muling their accounts on the DMM tournament (its allowed) so have 2 clients open. This would be a great option for them and many other scernerios like flipping or skilling alts.

![client](https://user-images.githubusercontent.com/63739578/80920148-d0a66300-8d65-11ea-871a-1c359275cf42.png)

**Comment by deathbeam** [comment] 2020-05-04 12:14
Duplicate of https://github.com/runelite/runelite/issues/5540

**Closed by deathbeam** 2020-05-04 12:14 UTC
