### ISSUE TITLE
Add the option to show the profit/loss of High Alchemy on items

### ISSUE THREAD

**Issue by medesetmedes** [runelite/runelite#7913] opened 2019-02-18 13:34 UTC
**HA Profit/Loss**
As an extension of the Item Prices plugin, you could show if alching an item is profitable.
The profit is calculated by subtracting the GE price of the item and a nature rune from the HA price.

It currently supports single items
![single](https://user-images.githubusercontent.com/5855463/52953938-2709ca80-3389-11e9-95c3-07d560af88d8.jpg)
and stacks.
![stack](https://user-images.githubusercontent.com/5855463/52953969-3852d700-3389-11e9-9f69-04be96d42846.jpg)
It can be toggled off.
![toggle](https://user-images.githubusercontent.com/5855463/52953984-41dc3f00-3389-11e9-859b-cd947450a7de.jpg)

The plugin could also display an estimated profit per hour by alching that certain item.

**Comment by Adam-** [comment] 2019-02-18 15:12
Context on this: https://www.reddit.com/r/2007scape/comments/arvtct/i_edited_the_item_prices_plugin_in_runelite_to/

**Comment by deathbeam** [comment] 2019-02-18 17:12
Duplicate of #1075

**Closed by deathbeam** 2019-02-18 17:12 UTC
