### ISSUE TITLE
Reset Camera Zoom on CTRL+Middle Mouse Button

### ISSUE THREAD

**Issue by tomcylke** [runelite/runelite#5846] opened 2018-10-06 06:36 UTC
Runelite recently received an update that makes it possible to control camera zoom only while the control key is held. This was one of my favorite updates, as it makes it much easier to move the camera with the middle button without accidentally zooming in or out. 

The Konduit client has a feature where you can reset the camera zoom to the default by holding CTRL and pressing the middle mouse button. If we could get that for Runlite, it would be fantastic. 

Thank you my dudes.

**Comment by deathbeam** [comment] 2018-10-06 07:03
Duplicate of #919

**Closed by deathbeam** 2018-10-06 07:03 UTC
