### ISSUE TITLE
MSAA x16 not working on GTX 1080

### ISSUE THREAD

**Issue by dillypickles** [runelite/runelite#7197] opened 2019-01-05 07:00 UTC
EDIT: Turning OFF the interface styling and setting anti-aliasing to MSAA x16 worked! I switched interface styling back on and it's still working so far!

Whenever I select MSAA above x4 the screen starts ghosting and freezing up. I've attached a screenshot below. The only thing that repsonds are the in-game menus and minimap. However MSAA x4 is working normally and looks fantastic. 

OS: Windows 10 64-bit
Client Version: 1.5.6.1
CPU : Intel i5-7600k
GPU : Nvidia GTX 1080
RAM : 16GB 3200Mhz DDR4

![2019-01-04_22-59-06](https://user-images.githubusercontent.com/46393214/50721434-75326b00-1074-11e9-9102-c10ec46245f1.png)

**Comment by JourneyOver** [comment] 2019-01-05 16:07
Wouldn't say it's all Nvidia GPUs, as I'm running with a GTX 760 and have no issues with anything above MSAA x4 on both the default client, and my own build.

**Comment by dillypickles** [comment] 2019-01-05 17:49
Okay thanks for your input, I'll keep messing around with other settings that I have enabled and see if I can get it to work. I'll set Runelite configuration to default and Nvidia control panel to default and report back to see if it's still having issues.

**Comment by Adam-** [comment] 2019-01-05 17:52
We recently added a check to not set the MSAA level higher than supported, so this is weird.

**Comment by dillypickles** [comment] 2019-01-05 19:01
Strange. I reset all my Nvidia Control Panel and Runelite settings to
default and it's still giving me the sam symptoms. Are you saying MSAA X16
isn't suppprted by my GPU?

**Comment by AustinGarrettRichards** [comment] 2019-01-06 00:44
Nvidia GPUs only support MSAA x8.

**Comment by steffenhauge** [comment] 2019-01-06 00:49
> 
> 
> Nvidia GPUs only support MSAA x8.

This is not true, x16 works fine on a GTX 1060

**Comment by dillypickles** [comment] 2019-01-06 02:45
MSAA x8 gives me the same problem. x4 or lower is the only one that works.

**Comment by dillypickles** [comment] 2019-01-06 07:09
> I am running a Nvidia GTX 1080 on Windows 7 at MSAA x16 without issue(whether it truly is that value per above comments).
> 
> Have you tried turning off the interface styling?

That fixed it! Looks like I missed it when resetting to default settings. Thank you!

**Comment by JMox** [comment] 2019-03-23 14:31
> 
> 
> > I am running a Nvidia GTX 1080 on Windows 7 at MSAA x16 without issue(whether it truly is that value per above comments).
> > Have you tried turning off the interface styling?
> 
> That fixed it! Looks like I missed it when resetting to default settings. Thank you!

Also getting the exact same issue with a GTX 1080 Ti, Interface styling is off and did not fix the issue for me.

This is on Windows 10 x64, Driver version: 419.35 (latest as of writing this)

**Comment by Nightfirecat** [comment] 2022-07-10 04:00
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:00 UTC
Labels: bug, gpu
