### ISSUE TITLE
Vorkath helper

### ISSUE THREAD

**Issue by twoodward1** [runelite/runelite#2775] opened 2018-05-15 20:31 UTC
This feature would:
- Count Vorkath hits (predict occurrence of poison/scorpion phase)
- Show the hit radius of a fireball

**Comment by cmg5461** [comment] 2018-05-16 13:48
AoE overlays have already been removed by request of Jagex.

**Comment by deathbeam** [comment] 2018-05-17 17:48
Duplicate of #2447

**Closed by deathbeam** 2018-05-17 17:48 UTC
