### ISSUE TITLE
Pressing key to toggle zoom

### ISSUE THREAD

**Issue by laagone** [runelite/runelite#4146] opened 2018-07-03 00:34 UTC
One of my favorite features of Konduit was that the client's zoom could be toggled on and off with Ctrl+MiddleClick, effectively giving two levels of zoom toggled by pressing a button instead of scrolling (switching between the in-game and Konduit's zoom).

I recognize that RuneLite's zoom is not a client-specific one, but rather depending on the in-game zoom, however it would be great if there were some way to make a similar feature. An alternative could be an option to accelerate the zoom amount (like make it twice as fast), the problem in the first place is that I feel the scrolling is too sluggish.

**Comment by Nightfirecat** [comment] 2018-07-03 00:36
Duplicate of #919

**Closed** 2018-07-03 00:42 UTC
Labels: duplicate
