### ISSUE TITLE
Marci Medium Clue Step Wrong

### ISSUE THREAD

**Issue by iancoolidge89** [runelite/runelite#9094] opened 2019-06-13 06:40 UTC
"I AM SIR" anagram points near old Hosidious location instead of near new Hosidious farm location.

It does resolve itself near the farm patch and attaches itself to Marci when she loads in, but initial arrow points to old location.

**Comment by Nightfirecat** [comment] 2019-06-13 07:12
Duplicate of #9039, and a fix has already been merged and will be present in the next release.

**Closed by Nightfirecat** 2019-06-13 07:12 UTC
Labels: duplicate
