### ISSUE TITLE
Menu Entry Swapper Attack option sometimes disappears

### ISSUE THREAD

**Issue by BlueSun288** [runelite/runelite#16490] opened 2023-04-14 05:21 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Sometimes with MES on it will remove the attack option. 

### Screenshots or videos
With MES on
![With MES on](https://user-images.githubusercontent.com/26097775/231948036-0aa4da6b-a174-450d-b03a-6c4d9955030e.png)
With MES off
![With MES off](https://user-images.githubusercontent.com/26097775/231948075-b03b50a3-43df-4ede-bcd9-bdd7d0e9776c.png)

### RuneLite version

RL: 1.9.14
OSRS: Rev 212
Launcher: 2.3.0

**Comment by Nightfirecat** [comment] 2023-04-14 06:09
This is a likely duplicate of #15490, unless there's some special behavior for Runite Golems specifically which breaks with MES. If you can consistently reproduce this issue for these monsters specifically, please comment back here and we can look at issuing a fix for them.

**Closed by Nightfirecat** 2023-04-14 06:09 UTC
Labels: duplicate
