### ISSUE TITLE
Add EHP and EHB to the HiScore plugin

### ISSUE THREAD

**Issue by datashe12** [runelite/runelite#12780] opened 2020-11-12 07:46 UTC
I think it would be useful if there was a setting to display EHP and EHB of a player on the HiScore plugin

Rates for EHP and EHB can be taken from templeosrs or wiseoldman

**Comment by psikoi** [comment] 2020-11-12 10:19
`GET https://api.wiseoldman.net/players/username/psikoi` only returns the cached version of the player's stats and ehp/ehb, so the player would need to be updated for accurate values.

I could create a new endpoint that receives the player's stats and outputs ehp/ehb/ttm/tt200m values, if needed.

**Comment by psikoi** [comment] 2020-11-12 10:24
Also duplicate of https://github.com/runelite/runelite/issues/720

**Closed** 2020-11-12 13:52 UTC
Labels: duplicate

**Comment by datashe12** [comment] 2020-11-13 03:42
Ah thanks, I think I searched for "EHB" instead of EHP and didn't see any posts, my bad for not seeing it's a dupe.
Yeah I was also thinking it could be calculated by Runelite rather than taken from those sites, only problem is that the rates do change every now and then, so this would need to be updated to remain consistent with those sites.
