### ISSUE TITLE
Th.

### ISSUE THREAD

**Issue by lfcdeco** [runelite/runelite#8495] opened 2019-04-12 07:30 UTC
Have the option to make the screen flash green when your coin pouch has reached a certain number that the user can edit.

E.g. when 26 coin pouches obtained, the screen flashes green.

**Comment by Nightfirecat** [comment] 2019-04-12 07:39
Basically duplicate of #4308. A configuration might be useful for that feature, so maybe comment on that request saying that.

**Closed by Nightfirecat** 2019-04-12 07:39 UTC
