### ISSUE TITLE
Feature Request: Notification when selected crop(s) are finished growing/ready to be picked again

### ISSUE THREAD

**Issue by NEETboxing** [runelite/runelite#2646] opened 2018-05-12 18:11 UTC
If the chosen crops finished growing while logged off then perhaps the notification(s) would set off upon logging back in. This would be great to have for farming runs of all types while you're multi tasking especially  doing herb runs or other fast growing crops.

Thank you for your time.

**Comment by deathbeam** [comment] 2018-05-13 11:47
Duplicate of #2212

**Closed by deathbeam** 2018-05-13 11:47 UTC
