### ISSUE TITLE
Chat command for slayer points and streak

### ISSUE THREAD

**Issue by NickelSickle** [runelite/runelite#14083] opened 2021-08-31 00:12 UTC
**Describe the solution you'd like**
Add a new command like !slayer, !streak, !slayerpoints or something similar to share with others how many slayer points I have and how big my streak is.  I just wanna flex on the homies.

**Comment by Hydrox6** [comment] 2021-08-31 00:15
Duplicate of #13116

**Comment by NickelSickle** [comment] 2021-08-31 00:16
Thanks, @Hydrox6!

**Closed by Hydrox6** 2021-08-31 00:15 UTC
