### ISSUE TITLE
Constant CTD at random, with random frequency

### ISSUE THREAD

**Issue by ZhangC1459** [runelite/runelite#16341] opened 2023-03-02 18:46 UTC
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10 Pro

### Bug description

Very similar issue to the various other "constant crash" issue tickets - https://github.com/runelite/runelite/issues/15839 is the most recent one, but since it's several months old I decided to create a new issue - sorry if that's not kosher but I'm turbo annoyed right now, as this crash has happened over 7 times today within an hour even after a full delete and reinstall of the Runelite client.  I am currently running 3rd party plugins such as 117 HD, but I have experienced this same crash with full vanilla plugins as well.

I have not yet tested on safe mode, but I did add the -XnoOpt flag in my config.json earlier (following a rec in some other issue post) and have gone 8 and a half minutes without a crash so far since that, which is a significant improvement over earlier today.

EDIT: just checked and apparently i did not save that setting, so not sure why i stopped crashing now? Been a couple hours

HOWEVER - while looking through the other issues, i did notice that **every single crash dump from those folks had Ryzen processors (which I also have)**.  Is this an AMD-specific issue perhaps?  Nobody else seems to have mentioned or noticed this yet, but I haven't had a chance to view every single issue related to this type of crash.

e.g.:
https://github.com/runelite/runelite/issues/15216 - jvm_crash_pid_5452.log shows a ryzen 9 5900X
https://github.com/runelite/runelite/issues/15511 - jvm_crash_pid_19904.log shows the same
https://github.com/runelite/runelite/issues/15554 - jvm_crash_pid_14388.log shows a Ryzen 7 5800X
https://github.com/runelite/runelite/issues/15593 - jvm_crash_pid-6468.log shows a Ryzen 5 5600X
https://github.com/runelite/runelite/issues/15639 - jvm_crash_pid_13308.log shows a Ryzen 9 5900X again

I myself have a Ryzen 9 5900X

Anyways, the crash logs all have the following Exception events listed (or similar) at the time of crash:

```
Internal exceptions (20 events):
Event: 53.760 Thread 0x00000172ba26b800 Implicit null exception at 0x000001729a8445ae to 0x000001729a84482a
Event: 53.760 Thread 0x00000172ba26b800 Exception <a 'java/lang/NullPointerException'{0x00000000f80de448}> (0x00000000f80de448) thrown at [./src/hotspot/share/runtime/sharedRuntime.cpp, line 606]
Event: 57.366 Thread 0x00000172ba26b800 Exception <a 'java/lang/NullPointerException'{0x00000000f4dca288}> (0x00000000f4dca288) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 1358]
Event: 63.133 Thread 0x00000172ba26b800 Implicit null exception at 0x00000172a14ff4aa to 0x00000172a1502dc8
Event: 63.713 Thread 0x00000172ba26b800 Implicit null exception at 0x00000172a14ff4aa to 0x00000172a1502dc8
Event: 65.154 Thread 0x00000172ba26b800 Implicit null exception at 0x00000172a1594297 to 0x00000172a1594888
Event: 66.992 Thread 0x00000172ba26b800 Implicit null exception at 0x00000172a105847f to 0x00000172a1061804
Event: 67.162 Thread 0x00000172ba26b800 Implicit null exception at 0x00000172a105847f to 0x00000172a1061804
Event: 68.503 Thread 0x00000172ba26b800 Implicit null exception at 0x00000172a13053f9 to 0x00000172a130e038
Event: 68.503 Thread 0x00000172ba26b800 Implicit null exception at 0x00000172a13053f9 to 0x00000172a130e038
Event: 72.046 Thread 0x00000172ae3db800 Implicit null exception at 0x00000172a13de720 to 0x00000172a13df344
Event: 75.336 Thread 0x00000172ba26b800 Implicit null exception at 0x00000172a105555f to 0x00000172a10558d8
Event: 75.354 Thread 0x00000172ba26b800 Implicit null exception at 0x000001729a8445ae to 0x000001729a84482a
Event: 75.354 Thread 0x00000172ba26b800 Exception <a 'java/lang/NullPointerException'{0x00000000f52f5fa8}> (0x00000000f52f5fa8) thrown at [./src/hotspot/share/runtime/sharedRuntime.cpp, line 606]
Event: 75.934 Thread 0x00000172ba26b800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000f4a63460}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.lang.Object, java.lang.Object, java.lang.Object, int, int)'> (0x00000000f4a63460) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 773]
Event: 75.934 Thread 0x00000172ba26b800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000f4a66cf0}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeSpecial(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, int, int)'> (0x00000000f4a66cf0) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 773]
Event: 75.935 Thread 0x00000172ba26b800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000f4a69df8}: 'java.lang.Object java.lang.invoke.Invokers$Holder.linkToTargetMethod(java.lang.Object, java.lang.Object, int, int, java.lang.Object)'> (0x00000000f4a69df8) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 773]
Event: 85.894 Thread 0x00000172ba26b800 Implicit null exception at 0x00000172a12f70a1 to 0x00000172a12f92f4
Event: 93.375 Thread 0x00000172ba26b800 Implicit null exception at 0x000001729a8445ae to 0x000001729a84482a
Event: 93.375 Thread 0x00000172ba26b800 Exception <a 'java/lang/NullPointerException'{0x00000000f4aa9c30}> (0x00000000f4aa9c30) thrown at [./src/hotspot/share/runtime/sharedRuntime.cpp, line 606]
```

### RuneLite version

Runelite Version: 1.9.11.2

Oldschool revision: Rev 211

Launcher version: 2.6.2

### Logs

[jvm_crash_pid_27008.log](https://github.com/runelite/runelite/files/10874834/jvm_crash_pid_27008.log)
[jvm_crash_pid_25160.log](https://github.com/runelite/runelite/files/10874835/jvm_crash_pid_25160.log)
[launcher.log](https://github.com/runelite/runelite/files/10874839/launcher.log)
[client.log](https://github.com/runelite/runelite/files/10874840/client.log)

**Comment by teuneboon** [comment] 2023-03-11 09:42
I have the issue as well on a 5950X, so seems pretty consistent so far. Added bonus info: I dual boot Windows and Linux, on Windows I have the issue, on Linux with the exact same hardware I don't. 117HD **seems** to make it crash more often, but without it I still crash sometimes.  90% of my crashes have no error popup at all, Runelite just closes. I haven't tried the -XnoOpt flag yet and I can't play too much this weekend, but I'll try it and see if it solves things.

**Comment by Dane-Ramen** [comment] 2023-03-17 08:46
I too have this issue, am running a 5900x, 3080ti. sometimes its stable for hours, sometimes i log in, and when im standing at the GE it will crash. typically always a "A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION" etc.

Let me know if you guys solve this.

https://github.com/runelite/runelite/issues/16357#issue-1615896446

**Comment by Nightfirecat** [comment] 2023-05-22 17:44
Duplicate of #10628, we don't know what causes this crash.

**Closed by Nightfirecat** 2023-05-22 17:44 UTC
Labels: duplicate
