### ISSUE TITLE
Screenshot Default Location

### ISSUE THREAD

**Issue by 14ky** [runelite/runelite#4212] opened 2018-07-07 16:45 UTC
**Is your feature request related to a problem? Please describe.** There is no way to change the default location of screenshots in RuneLite at the moment. Meaning that all my screenshots keep clogging up my C:/ drive.

**Describe the solution you'd like** It would be great to have an option to choose the file location in the current "Screenshot" settings. For example a "Browse..." addition, so we can re-route the current default pathway. 

**Describe alternatives you've considered** I've tried to move the entire ".runelite" file over to my D:/ drive but there is no option for "locations" in properties therefore I can't move the file.

**Additional context** I also tried to cut and paste the ".runelite" file to my D:/ drive in hopes of it fixing the problem but to no avail.
 Thanks in advance guys.

**Comment by deathbeam** [comment] 2018-07-07 16:50
Duplicate of #1324

**Comment by deathbeam** [comment] 2018-07-07 16:51
You can also make symlink in Windows btw

**Closed by deathbeam** 2018-07-07 16:50 UTC
