### ISSUE TITLE
Degrading item display

### ISSUE THREAD

**Issue by Dragon911XX** [runelite/runelite#7777] opened 2019-02-09 20:13 UTC
I was runecrafting and often did not pay attention to the chat bar with how quick it moves some times. But it would be neat to have a little box (similar to the slayer task display) That shows how many charges are left on an item. Then maybe include or exclude specific items. Like if I don't want it to display barrows equipment, but show a binding necklace. 

Just kind of annoying having to flip between inventory and armor while skilling to check charges left on stuff like binding necklaces.

**Comment by deathbeam** [comment] 2019-02-09 20:14
Duplicate of #1318

**Closed by deathbeam** 2019-02-09 20:14 UTC
