### ISSUE TITLE
Music shuffle and skip button [Feature Request]

### ISSUE THREAD

**Issue by A-Sergio** [runelite/runelite#11847] opened 2020-06-07 20:09 UTC
I dunno if its possible to create a music shuffle + skip button in the same way how Runescape 3's functions or similar. I listen to Runescape music all day, unironically. Jagex won't create it due to engine work, despite constant asking... So, I figured, can Runelite do this? It would improve my Runescape experience.

**Comment by ThatGamerBlue** [comment] 2020-06-07 20:10
Duplicate of #1916

**Closed** 2020-06-07 20:10 UTC
