### ISSUE TITLE
Client freezes for 2-3 seconds then closes. 

### ISSUE THREAD

**Issue by rosghub** [runelite/runelite#14608] opened 2022-01-18 07:06 UTC
**Describe the bug**
During combat in a raid (observed in cox and tob), my runelite client freezes for 2-3 seconds then closes. There are no errors in my runelite logs but using windows event viewer I'm able to see the application crash is related to my display driver. I am using the GPU plugin. Please advise a workaround because it's limiting my ability to do raids contain.

**To Reproduce**
I cannot reproduce it but found it happens commonly during verzik at tob, and either vanguards or olm at chambers.

**Screenshots**
![Screenshot 2022-01-18 015214](https://user-images.githubusercontent.com/9300522/149886016-0fb3ddd4-14e8-437e-89c0-f424b960801a.png)
![Screenshot 2022-01-18 015414](https://user-images.githubusercontent.com/9300522/149886152-eff72cbf-1442-4e8d-a661-7730f7bbf77e.png)

**Environment (please complete the following information):**
 - OS: Windows 10 (Lenovo X1 yoga 6th gen intel tiger lake/1135G7 iGPU)
 - RuneLite version: 1.8.9 (latest incident)
 - Launcher version: 2.1.7

**Additional context**
```
Faulting application name: RuneLite.exe, version: 0.0.0.0, time stamp: 0x5b50f2a4
Faulting module name: igxelpicd32.dll, version: 30.0.100.9955, time stamp: 0x615eb2d0
Exception code: 0xc0000005
Fault offset: 0x0004bb3c
Faulting process id: 0x303c
Faulting application start time: 0x01d80c30daf3f627
Faulting application path: C:\Users\(removed)\AppData\Local\RuneLite\RuneLite.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_2e4b2a5d1c43fba7\igxelpicd32.dll
Report Id: 6ef25626-2a6f-4c24-b02f-57d2ebef1804
```
Again, leaving out runelite logs because there are no errors.

**Comment by Nightfirecat** [comment] 2022-07-10 05:12
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 05:12 UTC
