### ISSUE TITLE
Issues relating to Time tracking (Farming Related Stuff)

### ISSUE THREAD

**Issue by ProAdz7** [runelite/runelite#13773] opened 2021-06-23 11:17 UTC
There will be times where time tracking shows wrong progression bar at times. In addition there are issues where diseased or dead plants only show when you are right next to the plant. If the player is not next to the dead plant it may show as green (making them think it is still healthy) until they go near it.

**Comment by Hydrox6** [comment] 2021-06-23 11:19
The times can be fixed by calibrating the tracker. This is done by observing a tree grow

For years now (since around the release of the Geomancy spell), the client has been unaware of the state of patches globally. This is not a bug; Jagex intentionally changed that, and it's impossible to get it back.

**Closed by Hydrox6** 2021-06-23 11:19 UTC
