### ISSUE TITLE
player indicators (attackable players only)

### ISSUE THREAD

**Issue by 123qwez3** [runelite/runelite#14829] opened 2022-04-04 03:06 UTC
I hate being in popular areas like the grand exchange and seeing hundreds of names when the primary use for player indicators for me is pvp and making quick determination of who is friend/foe.

another toggle within player indicator plugin that allows you to toggle players who you can attack. so it would remove names of players in safe areas and only allow them in pvp areas. also removing people who are outside of your combat bracket. (if you are in 10 wild and are 126 combat and see someone who is 126 their name will appear above head, but if someone level 100 comes along theirs will not since they cannot be attacked.)

**Comment by LlemonDuck** [comment] 2022-05-12 02:11
duplicate of #3684 and #6567

**Closed by LlemonDuck** 2022-05-12 02:11 UTC
