### ISSUE TITLE
(Suggestion) "Hide ignored players" option in the Entity Hider plugin

### ISSUE THREAD

**Issue by sven8100** [runelite/runelite#5600] opened 2018-09-23 12:52 UTC
**Is your feature request related to a problem? Please describe.**
Yes, some people are harassing other people like standing 24/7 on a fire, or walking in your fight so you missclick etc.

**Describe the solution you'd like**
A option "Hide ignored people" to the Entity Hider plugin.

**Comment by deathbeam** [comment] 2018-09-23 12:53
Duplicate of #3349

**Closed by deathbeam** 2018-09-23 12:53 UTC
