### ISSUE TITLE
Kingdom of Miscellania reminder

### ISSUE THREAD

**Issue by MrJudly** [runelite/runelite#12241] opened 2020-07-28 08:43 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I think it would be an awesome addition to have a Kingdom of Misc reminder added to the plugin daily tasks indicator as people like me keep forgetting :)

**Describe alternatives you've considered**
I did check the kingdom plugin but doesn't seem to be able to be done on there.

Let me know what you think - Jed

**Comment by Hydrox6** [comment] 2020-07-28 09:09
Duplicate of #10939

**Closed by Hydrox6** 2020-07-28 09:09 UTC

**Comment by BrandtHill** [comment] 2020-08-04 20:49
@MrJudly I've implemented this feature in pull request 10933 (linked issue 10939). It's been awaiting final review for approval for a few months. Check it out if you're interested
