### ISSUE TITLE
Add a timer until Slayer task is completed.

### ISSUE THREAD

**Issue by kleinaeinar** [runelite/runelite#5392] opened 2018-09-08 10:23 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When hovering over the current slayer assignment infobox, there is a timer there, estimating how long time is left until you finish your task.  This could be calculated in a few ways.  Lets say you have a task of 100 Greater Demons, and each kill gives you 115 slayer xp.  That means that in 100 kills you would get 11.500 Slayer XP.  The timer would calculate how often you are getting the 115 xp and estimate how long until you reach 11.500 slayer xp.  Only problem with this is with tasks that have different combat level monsters grouped together, as those would give different slayer xp.

**Describe alternatives you've considered**
No clue

**Additional context**

**Comment by deathbeam** [comment] 2018-09-08 11:06
This is duplicate of showing kills instead of actions in xp tracker, for what we already have an issue.

**Closed by deathbeam** 2018-09-08 11:06 UTC

**Comment by kleinaeinar** [comment] 2018-09-08 19:40
No, this is not that.  That is to show kills left until level.  This request is to add a timer to the "Slayer Infobox" that shows how much time until your task is completed.  Has nothing to do with showing kills instead of actions in xp tracker.

**Comment by deathbeam** [comment] 2018-09-08 19:41
yeah, but it would achieve what you want to, as XP tracker would show kills/hr, from what you would basically have your result.

**Comment by kleinaeinar** [comment] 2018-09-08 19:42
It already shows approximately kills per hour, by showing action/hr.  This would do the calculations for you in a easier manner.

**Comment by kleinaeinar** [comment] 2018-09-08 19:44
If you are referring my "solution" to how to add the timer, it doesn't have to be that way.  It was just the first thing that popped in my head.   There is probably an easier way to calculate it

**Comment by deathbeam** [comment] 2018-09-08 19:46
atm the action/hr is xp drop based tho so that is not very useful in this case. that is why i mentioned that kills/hr would solve that. E.g it would show that you are getting 50 kills/hr at black demon task and your task is 150, then it is simple, 3 hrs. I have generally good idea how to calculate that and there are like 2 PRs already open for it what would solve it in better way than it being only slayer specific like you are requesting as then it would be useful for a lot more scenarios than just slay tasks.

**Comment by kleinaeinar** [comment] 2018-09-08 19:49
All I'm asking for is a timer that shows when your task is complete, based on the speed you are killing the monster.  I would love to know if I have to sit here for 20 minutes doing this task before bed or 2 hours.  That's basically what I'm asking for.  But if there is a request for something similar than I'm happy.

**Comment by deathbeam** [comment] 2018-09-08 19:50
Yeah, that is exactly what you will know after the other request will be implemented.
