### ISSUE TITLE
Mac Client Download Corrupt

### ISSUE THREAD

**Issue by washac** [runelite/runelite#2926] opened 2018-05-19 09:09 UTC
I raised this issue the other day and it was closed pointing me to a duplicate, the duplicate is not the same issue at all, and installing Homebrew etc does not solve my issue.

My issue is in that I can download the Mac Client .dmg file but when I try to open it I get an error window open that says this..........

The following disk image could'nt be opened
Image - Runelite.dmg
Reason - Corrupt image

Only other information I can give is that I run Mavericks OS X 10.9.5

**Comment by Abextm** [comment] 2018-05-19 09:11
I think deathbeam mentioned the wrong issue
Duplicate of runelite/launcher#16

**Comment by deathbeam** [comment] 2018-05-19 11:31
Try downloading version for all platforms.

**Closed** 2018-05-19 11:31 UTC

**Comment by washac** [comment] 2018-05-19 12:33
Hi ya

Yea that works but is version 1.0 and Runelite according to the website is now unto
version 1.3.9

Regards
