### ISSUE TITLE
Add more placements for custom UI

### ISSUE THREAD

**Issue by Stormagen** [runelite/runelite#11491] opened 2020-05-07 07:28 UTC
I been wanting to use the custom overlay option for a while but there is two things that ruins it for me. 

1. There is no areabox to stick it to above the menues (Backpack, prayer and such) which messes it up when showing/hiding the sidebar of runelite as it wont follow the placement above the menues.
There is only an option to stick it next to the backpack which doesn't work for me. 

2. There is no areabox on the middle left side of the screen where i'd like the place the xp bar to make the xp drop apear next to the menues (Backpack and such). When it is placed just above the chatbar the xp drops will only show for 0.5 seconds and when placing it on the top side of the screen the xp drops is too far up to work well with the rest of the UI.

The soloutions for this would to be to add a couple of extra placements for the UI as those are the only palced where you really can change the overlay to without getting it messed up.

I have attached a couple of images to show where i'd like the addditional placements to be.

![osrs overlay](https://user-images.githubusercontent.com/64950045/81266253-c2499700-9044-11ea-97b4-af51b96fa57a.PNG)
![osrs xp drop](https://user-images.githubusercontent.com/64950045/81266264-c675b480-9044-11ea-8655-7fe8c102ceb3.PNG)

**Comment by raiyni** [comment] 2020-05-07 07:38
The xp drops are restricted to a specific viewport

**Comment by raiyni** [comment] 2020-05-07 07:44
Duplicate of #8515

**Closed** 2020-05-07 07:46 UTC

**Comment by Stormagen** [comment] 2020-05-07 09:57
Yes I know they are, but you can change the altitude of them as in the Picture, it depends on where xp xp gained icon on the left are placed in height.

**Comment by Stormagen** [comment] 2020-05-07 09:59
So you Close a topic where the 1st issue is not even mentioned and it's clearly not a duplicate as I ask for a areabox (The green square thing) In the middle.

**Comment by Hydrox6** [comment] 2020-05-07 10:00
That's what the duplicate is
