### ISSUE TITLE
Keyboard shortcuts for toggling settings

### ISSUE THREAD

**Issue by SquigsOSRS** [runelite/runelite#3267] opened 2018-05-25 00:08 UTC
A useful feature of OSBuddy that I am sadly missing when using RuneLite is the ability to toggle certain client settings on and off using simple keyboard shortcuts. Obviously not every setting or plugin needs one, but for certain things (mainly overlays) it is very useful. The ones I used frequently while using OSBuddy were Alt, which toggled ground item text overlays, and Ctrl-B, which toggled the boosted stat info overlay. I like to be able to toggle these specific overlays because, while are very useful to me in certain situations, other times I don't want them in my way (mainly when I'm PKing). The added quickness of using a keyboard shortcut to turn things on and off is really nice for when you are doing fast paced stuff like PKing where you might want to quickly check what loot is all over the ground without keeping the overlays on all the time blocking your view and you obviously can't dig into settings mid-fight.

I know that the Alt key in RuneLite is currently already used for the feature where you can include/exclude specific items from showing up, but that doesn't really cut it, because I'd like to be able to completely turn on/off the entire plugin, rather than having to hold down Alt to see items. 

I think that the ability to make customizable key shortcuts, which would beat out the OSBuddy feature, would be the obvious next step beyond just adding a few hardcoded shortcuts and would be really awesome. Thanks for the awesome client!

**Comment by deathbeam** [comment] 2018-05-25 05:50
Duplicate of #977

**Closed by deathbeam** 2018-05-25 05:50 UTC
