### ISSUE TITLE
"Configure Clue Scroll overlay" can be clicked through the floating map

### ISSUE THREAD

**Issue by mitchasdf** [runelite/runelite#7571] opened 2019-01-26 11:19 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The option to open the runelite configuration for clue scrolls by right clicking the box for your current clue being tracked, if the tracker box is found behind where the map is located, it can be clicked (or on mouse down when dragging) while the floating map is open.

**To Reproduce**
1.  Ensure "Clue Scroll" is turned on in runelite configuration
2. "Read" a clue scroll
3. Open the floating map
4. Try to click or click-drag at any point where the clue tracker box is located behind the map
5. Runelite configuration menu for "Clue Scroll" should open

**Expected behavior**
Expected map to respond to left mouse button without opening runelite config.

**Screenshots**
![image](https://user-images.githubusercontent.com/22111845/51786436-fbdbf300-21af-11e9-8dad-07237f49f8bf.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.9
 - Launcher version: 1.6.0

**Additional context**
Not sure if applicable to this problem.

**Comment by deathbeam** [comment] 2019-01-26 11:20
Duplicate of #7539

**Closed by deathbeam** 2019-01-26 11:20 UTC
