### ISSUE TITLE
Bank tabs not working

### ISSUE THREAD

**Issue by rafaelntom** [runelite/runelite#11590] opened 2020-05-14 13:04 UTC
My bank tabs randomly disappeared, i was in game when it happen, but i did not change any settings at all

Now i cant even creat new ones

Also the bank value is not appearing anymore.

![image](https://user-images.githubusercontent.com/52077974/81937658-4a421a80-95ca-11ea-82aa-5f435c0f9576.png)

**Comment by raiyni** [comment] 2020-05-14 13:05
Duplicate of #11585

**Closed by raiyni** 2020-05-14 13:05 UTC
