### ISSUE TITLE
Runelite Feature Request- Make status indicators, and overlays resizable 

### ISSUE THREAD

**Issue by GoEasyImBad** [runelite/runelite#3681] opened 2018-06-08 03:16 UTC
Making overhead prayer status, boosts, potion timers etc. resizable.. mainly just smaller.

**Comment by Hydrox6** [comment] 2018-06-08 03:17
Implemented in #3294

**Comment by Abextm** [comment] 2018-06-08 07:46
Duplicate of #1016

**Closed by Abextm** 2018-06-08 07:46 UTC
Labels: duplicate
