### ISSUE TITLE
Allow partial matches in GE item search

### ISSUE THREAD

**Issue by ManIkWeet** [runelite/runelite#4845] opened 2018-08-11 11:07 UTC
**Is your feature request related to a problem? Please describe.**
I currently have to enter complete words, like "Dragonfire" or "dueling" to get a result for "Dragonfire shield" or "Ring of dueling(8)"

**Describe the solution you'd like**
A checkbox or setting that allows to search for partial matches, like "ire sh" or "duel". Seperate segments of words still have to be sequential, you won't be able to do "sh ire" to get a "Dragonfire shield" for example. 

**Describe alternatives you've considered**
An alternative solution seems to be to use the OSBuddy exchange... Through a stinky browser!

**Additional context**
It seems to be a limit imposed by the web api that RuneLite uses to request for a search-result. "https://api.runelite.net/runelite-1.4.12-SNAPSHOT/item/search?query=drag" returns an empty json while "https://api.runelite.net/runelite-1.4.12-SNAPSHOT/item/search?query=dragon" returns a beefy json full of matches.

The checkbox would simply add another argument to the API request, for example "https://api.runelite.net/runelite-1.4.12-SNAPSHOT/item/search?query=drag&partial=true"

**Comment by deathbeam** [comment] 2018-08-11 11:37
Duplicate of already existing issue

**Closed by deathbeam** 2018-08-11 11:37 UTC
