### ISSUE TITLE
Idle logout notification toggle

### ISSUE THREAD

**Issue by QdpqbQ** [runelite/runelite#5035] opened 2018-08-21 01:46 UTC
Like the title says, would be nice to get an option to turn off the  4:40 logout notification without affecting the skill/combat notifications. Would also improve the experience for afk combating. (Although having it on 19:40 would obviously be better). I know similar issues have been posted but couldn't find any fixes.

**Comment by deathbeam** [comment] 2018-08-21 05:46
Duplicate of #3322

**Closed by deathbeam** 2018-08-21 05:46 UTC
