### ISSUE TITLE
Wrong Charles NPC is highlighted for Easy Clue

### ISSUE THREAD

**Issue by apolya01** [runelite/runelite#15258] opened 2022-07-02 21:25 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Win 10

### Bug description

Check easy clue step "tak to Charles at Port Piscarilius" at Fossil Island camp
See Charles NPC on Fossil island is highlighted

### Screenshots or videos

![image](https://user-images.githubusercontent.com/57806706/177016543-86888679-deee-43c2-9a60-8868b66a0df3.png)

**Comment by Hydrox6** [comment] 2022-07-02 21:25
Duplicate of #3164

**Closed by Hydrox6** 2022-07-02 21:25 UTC
Labels: needs-triage
