### ISSUE TITLE
Add Expeditious Bracelets / Slaughter Bracelets to Item Charge Plugin

### ISSUE THREAD

**Issue by Kai-Jones** [runelite/runelite#9969] opened 2019-10-03 17:32 UTC
Add an option to view charges left of the slayer bracelets in the form of an infobox. This feature is present for other jewellery in the item charges plugin, but the bracelets are tracked within the slayer plugin.

---

As the title says add the option to view the charges left on your Expeditious Bracelet / Slaughter Bracelet while equipped like you can with Amulet of Glory Dueling rings etc.

**Comment by huddy987** [comment] 2019-10-03 17:46
Related issue: https://github.com/runelite/runelite/issues/9916

**Comment by Hydrox6** [comment] 2019-10-03 17:52
You can already view the charges as an overlay on the item itself; this is part of the Slayer plugin. If you want an infobox like Item Charges items have, please update your issue to mention that.

**Comment by Kai-Jones** [comment] 2019-10-03 17:54
> You can already view the charges as an overlay on the item itself; this is part of the Slayer plugin. If you want an infobox like Item Charges items have, please update your issue to mention that.

Sorry I didn't realise it was unclear. I meant a counter similar to the other pieces of jewellery and how many monsters you have on your task. I have amended my initial post.

**Comment by Hydrox6** [comment] 2019-10-03 18:05
The boxes that appear on screen (eg. See below) are called Infoboxes.
![image](https://user-images.githubusercontent.com/2979691/66152040-76e38c00-e610-11e9-9dd6-a21ff117393c.png)
I'm only mentioning that it's unclear so that someone else doesn't look at it, misinterpret it, and then close it.

**Comment by Kamielvf** [comment] 2019-10-06 14:28
This feature already exists in the slayer plugin under the setting called `Count on items`

**Comment by Hydrox6** [comment] 2020-03-31 08:26
Duplicate of #2407

**Closed by Hydrox6** 2020-03-31 08:26 UTC
Labels: feature-request
