### ISSUE TITLE
Show high alchemy values on price check screen

### ISSUE THREAD

**Issue by follmer** [runelite/runelite#9674] opened 2019-08-16 16:58 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the ability to see high alchemy values in the in-game price checker. This would allow for ironmen to see the high alchemy value of their inventory, rather than a grand exchange value which wouldn't be useful.

**Describe alternatives you've considered**
Checking the high alchemy value of every item in the inventory

**Additional context**

**Comment by Lightness248** [comment] 2019-08-22 21:02
I'm working on it :)

**Comment by oplosthee** [comment] 2019-10-07 10:33
This is a duplicate of https://github.com/runelite/runelite/issues/8502

**Closed** 2019-10-07 10:48 UTC
Labels: feature-request
