### ISSUE TITLE
Make camera zoom work when cursor is hovering minimap

### ISSUE THREAD

**Issue by joaovicentekrzyzaniak** [runelite/runelite#3348] opened 2018-05-26 16:29 UTC
Currently is a feature on OSBuddy, don't see why this couldn't also be on RuneLite. Helps a lot when you're navigating. Currently you can only zoom if your cursor is anywhere but in the inventory and minimap.

**Comment by Kamielvf** [comment] 2018-05-26 16:30
Duplicate of #2316

**Closed** 2018-05-26 16:30 UTC
