### ISSUE TITLE
Add a reminder if we forget Salve amulet on undead tasks

### ISSUE THREAD

**Issue by divinitize** [runelite/runelite#4219] opened 2018-07-07 23:05 UTC

**Comment by divinitize** [comment] 2018-07-07 23:38
Similar to the current slayer counter. Maybe have a picture of the salve underneath it


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Martin Tuskevicius <notifications@github.com> Date: 08/07/2018  00:25  (GMT+00:00) To: runelite/runelite <runelite@noreply.github.com> Cc: Craig Bryant <craigbryant09@googlemail.com>, Author <author@noreply.github.com> Subject: Re: [runelite/runelite] Add a reminder if we forget Salve amulet on undead tasks (#4219) 
How would you want the reminder to look?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/runelite/runelite","title":"runelite/runelite","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/runelite/runelite"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DudeMartin in #4219: How would you want the reminder to look?"}],"action":{"name":"View Issue","url":"https://github.com/runelite/runelite/issues/4219#issuecomment-403249464"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/runelite/runelite/issues/4219#issuecomment-403249464",
"url": "https://github.com/runelite/runelite/issues/4219#issuecomment-403249464",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [runelite/runelite] Add a reminder if we forget Salve amulet on undead tasks (#4219)",
"sections": [
{
"text": "",
"activityTitle": "**Martin Tuskevicius**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DudeMartin",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"runelite/runelite\",\n\"issueId\": 4219,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"runelite/runelite\",\n\"issueId\": 4219\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/runelite/runelite/issues/4219#issuecomment-403249464"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 354031624\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by deathbeam** [comment] 2018-11-26 13:32
Duplicate of #1470

**Closed by deathbeam** 2018-11-26 13:32 UTC
Labels: feature-request
