### ISSUE TITLE
Current Expereince and Target Experience difference on Skill Calculator plugin tab

### ISSUE THREAD

**Issue by JWalty** [runelite/runelite#11656] opened 2020-05-20 19:59 UTC
**Is your feature request related to a problem? Please describe.**
When using the skill calculator, I'd like to see the difference in the two levels. Often times I'm wondering how much xp is between two levels and I have to launch my windows calculator just to see how much xp is from 90-95 woodcutting or something dumb like that.

**Describe the solution you'd like**
I'd like to see a small difference of the XPs between the 'Current Experience' and 'Target Experience' on the skill calculator plugin tab

**Describe alternatives you've considered**
This could be easily achieved with some elbow grease and a calculator but what is RuneLite for if not making life just a little easier

**Comment by Nightfirecat** [comment] 2020-05-20 20:00
Duplicate of #4816

**Closed by Nightfirecat** 2020-05-20 20:00 UTC
Labels: duplicate
