### ISSUE TITLE
Ardougne Nature Chest Timer (thieving) 

### ISSUE THREAD

**Issue by Zavec** [runelite/runelite#4240] opened 2018-07-09 00:25 UTC
**Describe the solution you'd like**
There is a chest that you can loot at 28 thieving which gives you 1 nature rune and some coins. Every 8 seconds you can search for traps again. I was hoping there could be a in game timer like on hunter traps so that as soon as you loot it will count down so you know when you can loot again without switching worlds which ultimately log you out.

**Describe alternatives you've considered**
A stop watch?

**Additional context**

**Comment by SolveSoul** [comment] 2018-07-09 07:50
Also, see this feature request #3924

**Comment by forsco** [comment] 2018-07-09 09:53
I may look into creating something for thieving soon, with this included.

If someone else wants to take this up in the mean time im also fine with that.

**Comment by deathbeam** [comment] 2018-09-18 10:55
Duplicate of #3924

**Closed by deathbeam** 2018-09-18 10:55 UTC
Labels: feature-request
