### ISSUE TITLE
Within the Ground Items plugin, add an optional value threshold after which to show hidden items

### ISSUE THREAD

**Issue by qnnplmr** [runelite/runelite#8260] opened 2019-03-19 15:49 UTC
**Is your feature request related to a problem? Please describe.**
There are some items that I would not like to see in small quantities, but would like to see in larger quantities. For example, a single iron arrow is not valuable, but 5,000 iron arrows are.

**Describe the solution you'd like**
Create an option within the Ground Items plugin to set a GE value threshold or a simple Quantity threshold to override hidden items.

**Comment by qnnplmr** [comment] 2019-03-19 15:57
**Note**
The existing "Highlight < Value" option still prioritizes hidden items and does not serve the function of this feature request.

**Comment by Alexsuperfly** [comment] 2019-03-19 16:01
just use `hide < value`

**Comment by qnnplmr** [comment] 2019-03-19 16:02
> just use `hide < value`

This is too general, and hides lower value items that I do want to see.

**Comment by Alexsuperfly** [comment] 2019-03-19 16:04
then this is a duplicate of #1123

**Closed** 2019-03-19 17:25 UTC
