### ISSUE TITLE
Switch runelite panel sides from right to left

### ISSUE THREAD

**Issue by L33tspeek** [runelite/runelite#12215] opened 2020-07-24 01:27 UTC
I play with Runelite on my left screen, and the panel falls closest to the middle, it would be nice to switch the panel to the left side of the client so I can easier see the game

**Describe the solution you'd like**
Have the panel side toggle able

**Describe alternatives you've considered**
I don't see any clear alternatives besides moving the game to my right monitor which I don't want to do

**Additional context**

![panel](https://user-images.githubusercontent.com/29013305/88353392-84424200-cd1a-11ea-8ebd-5241d8cb031f.png)

**Comment by Hydrox6** [comment] 2020-07-24 07:56
Duplicate of #1641

**Closed by Hydrox6** 2020-07-24 07:56 UTC
