### ISSUE TITLE
On default farming plugin, add icons to show if you've ultracomposted/protected a patch

### ISSUE THREAD

**Issue by ragsmaroon** [runelite/runelite#12367] opened 2020-08-19 14:58 UTC
**Is your feature request related to a problem? Please describe.**
When I'm doing my herb runs sometimes I end up with an unused ultracompost in my inventory and I don't know which patch I didn't use it on.

**Describe the solution you'd like**
I think something pretty easy would be to just have an compost/supercompost/ultracompost/protected icon on the herb patch in the default farming plugin on each patch if you've done that action on it.

**Describe alternatives you've considered**
You could also show the icons above the patch? That might be cool too. But I think in the side panel is where it is most important.

**Additional context**

**Comment by Hydrox6** [comment] 2020-08-19 14:59
Duplicate of #2472

**Closed by Hydrox6** 2020-08-19 14:59 UTC
