### ISSUE TITLE
Custom login screen music

### ISSUE THREAD

**Issue by calebhammett** [runelite/runelite#12504] opened 2020-09-17 04:36 UTC
We have custom login screen image, it would be great to have the option of using an audio file we have to replace the music for the login screen, for example I would use the 2009 Scape Theme found at https://www.youtube.com/watch?v=JXisdFMEw8g

I usually just keep the login screen music muted but if I were able to use this piece instead, I'd let it play every time.

**Comment by Hydrox6** [comment] 2020-09-17 08:33
Duplicate of #11747

**Closed by Hydrox6** 2020-09-17 08:33 UTC
Labels: feature-request
