### ISSUE TITLE
hide item vs hide noted item

### ISSUE THREAD

**Issue by Joffe24** [runelite/runelite#10558] opened 2020-01-06 14:04 UTC
ive browsed through this issue but i have not seen anyone suggesting a searchable list with a "check" box for hide item / hide noted item and hide coins with a set value > X. would be fairly simple to put together and simple to use.

if this is a duplicate thread, please give me the link to it so i can read through it properly.

**Comment by Alexsuperfly** [comment] 2020-01-06 14:06
basically duplicate of #1123

**Comment by Joffe24** [comment] 2020-01-06 14:08
much appericiated, thanks. its the same but not excatly what i tried to suggest. purpose of it was to add a simple feature for a dumdum like myself.

**Comment by Hydrox6** [comment] 2020-01-06 14:12
Duplicate of #1988

**Closed by Hydrox6** 2020-01-06 14:12 UTC
