### ISSUE TITLE
Ardougne Course Missing Highlight

### ISSUE THREAD

**Issue by ryanv09** [runelite/runelite#3534] opened 2018-05-31 18:11 UTC
After the latest update, the Ardougne rooftop agility course is missing one of the highlights. Attached image.
![missing highlight-2018-05-31](https://user-images.githubusercontent.com/3219792/40799793-21f016c8-64d4-11e8-808e-52ed85774761.png)

**Comment by deathbeam** [comment] 2018-05-31 18:20
Duplicate of #3522

**Closed by deathbeam** 2018-05-31 18:20 UTC
Labels: bug, regression
