### ISSUE TITLE
Time Tracking

### ISSUE THREAD

**Issue by iPepeep** [runelite/runelite#11791] opened 2020-06-01 22:02 UTC
time tracking need one think to be completed, Growth timing (farm tick)

Ex: Allotments, hops, Potato cactus, Seaweed
00:00, 00:10, 00:20, 00:30, 00:40, 00:50
Ex: Tree
12:00, 12:40, 1:20, 2:00, 2:40, 3:20, 4:00, 4:40, 5:20, 6:00, 6:40, 7:20, 8:00, 8:40, 9:20, 10:00, 10:40, 11:20

it means on every tap we can see some bar or timing for this growth tick timing 
Ex: if I click on tree patches i see 40mins timer on top of all patches
if I click on allotments patches i see 10mins timer on top of all patches

**Comment by Hydrox6** [comment] 2020-06-02 07:21
Duplicate of #8381

**Closed by Hydrox6** 2020-06-02 07:21 UTC
