### ISSUE TITLE
Chest Respawn Timer

### ISSUE THREAD

**Issue by ScrPits** [runelite/runelite#5539] opened 2018-09-18 08:26 UTC
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Respawn timer for "theving" chest 
pull the time the chest is thevable

**Describe alternatives you've considered**
Chest Respawn timer Gui paint.

**Additional context**
Search for traps "respawn" timer (this is to help even your elvish adventures) (the traps around the elv kingdom

**Comment by deathbeam** [comment] 2018-09-18 10:55
Duplicate of #3924

**Closed by deathbeam** 2018-09-18 10:55 UTC
