### ISSUE TITLE
GPU render bug - transparent lines and dots

### ISSUE THREAD

**Issue by Dercik** [runelite/runelite#8680] opened 2019-04-28 18:28 UTC
**Describe the bug**
As in the title. More accurate description in the screenshots

**To Reproduce**
1. Just turn on GPU plugin.
(settings:
draw distance 90
antialiasing msaa x8)
2. Take a walk in the game (Make game load new sectors)

**Expected behavior**
The game after a while will stop rendering properly and transparent dots and lines will appear.

**Screenshots**
https://imgur.com/a/zy24JEn

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.21
 - Launcher version: 1.6.0

**Additional context**
My GPU card - Geforce GT 740M
I disabled hardware accelaration by adding" --mode=OFF" in Runelite shortcut

**Comment by Nelzer22** [comment] 2019-05-02 11:39
I got the same problem on my laptop.

**Comment by noeyx** [comment] 2019-05-12 06:44
I have the same issue when the GPU plugin is turned on with default values. May video card is NVIDIA GeForce 920M.

![runelite_glitch](https://user-images.githubusercontent.com/11681955/57578701-f470f900-74c3-11e9-8262-a79ecfdbf3b0.PNG)

**Comment by JadenCP1** [comment] 2019-06-25 22:32
Any fixes ? Having the same issue with varying degrees of severity.

**Comment by Nightfirecat** [comment] 2022-07-10 04:01
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:01 UTC
Labels: bug, gpu
