### ISSUE TITLE
Add Pre-EOC (2012) XP drops to the XP Drop plugin

### ISSUE THREAD

**Issue by Omega4Head** [runelite/runelite#8114] opened 2019-03-05 14:01 UTC
I think this would be a nice little addition since we have retro options like the 2005 and 2010 gameframes, and I always liked the pre-eoc XP drops. I know you can customise xp drops to be in the centre and all that but there's no way to make them look exactly like they did

Example:
![](https://i.imgur.com/MiE5z0u.png)
Might be a bad example since it says EP but that screenshot was from another language world, but you get the idea

**Comment by deathbeam** [comment] 2019-03-05 14:04
Duplicate of #2323

**Closed by deathbeam** 2019-03-05 14:04 UTC
