### ISSUE TITLE
The Crystal Math Labs plugin is broken and no longer updating the site

### ISSUE THREAD

**Issue by Shugy0** [runelite/runelite#8619] opened 2019-04-23 00:06 UTC
The crystal math labs plugin no longer updates after every logout. This can be re-created by logging in then logging out, and refreshing your user page on crystalmathlabs, and seeing that it wasn't updated.

**Comment by Adam-** [comment] 2019-04-23 00:16
Can you get logs of it sending a request and failing? It doesn't look like their api changed...

**Comment by Nightfirecat** [comment] 2019-04-23 01:46
If you're only logging in and out, we're likely not firing off a request. iirc the plugin doesn't send requests unless you gain at least 1k exp in a login session to keep from spamming CML with tons of requests.

**Comment by Shugy0** [comment] 2019-04-23 01:58
I tried logging out after getting >1k exp and it still didn't work. There weren't any logs about it in the log files.

**Comment by SRLJustin** [comment] 2019-04-23 07:18
2019-04-21 15:59:17 [OkHttp https://crystalmathlabs.com/...] WARN  n.r.c.p.c.CrystalMathLabs - Error submitting CML update, caused by Read timed out.

**Comment by deathbeam** [comment] 2019-04-23 07:57
Yeah this is because CML is rejecting requests, nothing we can really do about that on our side

**Comment by chiragbharadwaj** [comment] 2019-07-01 17:15
Hi, do you have any suggestions on why this might be the case? I have the same issue even now, and it says "failed to update... caused by crystalmathlabs.com" on every log. I've asked them as well as to why this might be the case but haven't received a reply yet.

**Comment by Lorentary** [comment] 2019-10-26 11:39
I think the plugin should be removed as it is automatically rejected and just causes extra serverdelay when manually updating on the website

**Comment by deathbeam** [comment] 2019-10-26 12:04
I think so to, its pointless to have plugin for some malfunctioning 3rd party api.

**Comment by Nightfirecat** [comment] 2020-02-13 08:04
Is this reproduceable since 553e568?

**Comment by deathbeam** [comment] 2020-02-14 08:10
I mean the plugin code was just moved to different place but do not really changes anything about how CML api works right.

**Comment by Nightfirecat** [comment] 2020-02-15 07:47
Then is this bug still valid? Are players still experiencing timeouts when attempting to connect?

**Comment by Nightfirecat** [comment] 2021-02-19 00:45
Given that this was never a RuneLite issue in the first place (it's caused by rejected requests on CML's end) and we've since moved the player xp updates behind a toggle for each site in the XP Updater plugin, I am closing this issue. I recommend anyone following this to contact CML to resolve this issue on their end.

**Closed by Nightfirecat** 2021-02-19 00:45 UTC
Labels: bug
