### ISSUE TITLE
Random "disconnects" from party 

### ISSUE THREAD

**Issue by lacaze** [runelite/runelite#9133] opened 2019-06-18 04:59 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When in a party that is connected to discord. Randomly, a person will disconnect from the party. other people will still see that they are in the party but the person them selves will not see the party any more on their top left. 

**To Reproduce**
Simply happens when in a party. Neither me nor any of my friends have noticed any patterned yet to why it randomly does not show the party

**Expected behavior**
The party to stay online and consistent till we all leave

**Screenshots**
I don't have a ss because we couldnt replicate it (even though it usualy happens quite often), but it simply says at the top left in red to join a party.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.26
 - Launcher version: 1.6.0

**Comment by Twiglet1022** [comment] 2019-06-18 21:24
This is the same as #8395

**Comment by deathbeam** [comment] 2019-07-12 11:39
Duplicate of #8395

**Closed by deathbeam** 2019-07-12 11:39 UTC
Labels: bug, discord, needs-information
