### ISSUE TITLE
Loot tracker Kc Count

### ISSUE THREAD

**Issue by IronWhy** [runelite/runelite#8969] opened 2019-05-31 13:50 UTC
currently the loot tracker counts the kills of npc's that drop something, if a npc drops nothing it doesnt count it as a kill.

I want the loot tracker to count the kills of npc's that drop nothing.

**Comment by Hydrox6** [comment] 2019-05-31 14:13
Duplicate of #7994

**Closed by Hydrox6** 2019-05-31 14:13 UTC
