### ISSUE TITLE
Bat Finder for Raids Thieving Room

### ISSUE THREAD

**Issue by Honestidade** [runelite/runelite#3115] opened 2018-05-22 19:04 UTC
The bats inside the thieving room in raids are not random and there is a site where you can enter in what chests are poisoned and it will show you where the bats are.

There are 3 room layouts so the plugin would have to figure out the room layout and then take into account when you\someone else finds a poisoned chest and similar to the hot\cold plugin slowly figure out where the bats are.

https://twitter.com/EndlessDawnRS/status/998991141159751685
https://t.co/4EoAzdLvgW
https://dikkenoob.github.io/

**Comment by deathbeam** [comment] 2018-05-23 07:01
Duplicate of #2592

**Closed by deathbeam** 2018-05-23 07:01 UTC
