### ISSUE TITLE
Barrage Timer

### ISSUE THREAD

**Issue by xandyman999** [runelite/runelite#2396] opened 2018-05-06 07:32 UTC
Upon successful cast of spell that restricts opponents movement, timer gui appears which counts down the time until your target would become unfrozen. Similar to how boss timers are implemented, but instead of bosses death triggering being used in the conditional statement, perhaps checking spell's base xp drop vs achieved to see if the spell splashed, a successful ice barrage, burst, entangle, tentacle whip spec  would trigger its related count down gui.

Drawbacks, wouldn't sync for teams, but teams could rely on their dedicated barragers to ensure timely refreezes.

Perhaps multiple gui's could be enabled for barraging multiple targets. Opponent would be assigned a number which could show up on screen, similarly to players on friends list having their username displayed on screen, but instead of username, its the number (set as a background) in the freeze GUI.

**Comment by Nightfirecat** [comment] 2018-06-19 22:02
Duplicate of #2011?

**Closed** 2018-09-02 18:58 UTC
Labels: feature-request
