### ISSUE TITLE
Suggestion: Add Pyramid Plunder chest and sarcophagus counter

### ISSUE THREAD

**Issue by Aealm** [runelite/runelite#9595] opened 2019-08-06 12:30 UTC
Possible to add a counter for the chests and sarcophagi opened in PP? Maybe under Loot Tracker?

**Comment by jachymb** [comment] 2019-09-02 09:37
+1 for adding to loot tracker

**Comment by JJGrootveld** [comment] 2020-03-17 17:51
Bumping this, would be awesome

**Comment by jachymb** [comment] 2020-07-09 09:53
Related: #12084

**Comment by Nightfirecat** [comment] 2020-07-30 06:52
Given the similarities of the request, and that we're more likely to implement loot tracker expansions than a PP-specific counter, I am closing this as a duplicate of #12084.

**Closed by Nightfirecat** 2020-07-30 06:52 UTC
Labels: duplicate
