### ISSUE TITLE
Client crashes when external monitor plugged in

### ISSUE THREAD

**Issue by LukeWood** [runelite/runelite#12005] opened 2020-06-27 22:02 UTC
**Describe the bug**
Client crashes when external monitor plugged in on macos catalina.   Verified on my own and friends' computers.

**To Reproduce**
1. log in to runelite
2. plugin external monitor
3. observe crash (frozen characters not animating)

**Environment (please complete the following information):**
 - OS: macos
 - RuneLite version: 2.1.1
 - Launcher version: unsure how to check

**Comment by LukeWood** [comment] 2020-07-12 18:12
Update:

Both my friend and I have confirmed that we can turn the gpu plugin off and on again and things will work again after plugging the monitor in.

Seems it's in the GPU plugin

**Comment by MESLewis** [comment] 2021-01-13 02:44
Duplicate of #12930

**Closed by MESLewis** 2021-01-13 02:44 UTC
