### ISSUE TITLE
Make the notification for cannonballs customizable

### ISSUE THREAD

**Issue by ayyyyllmao** [runelite/runelite#1820] opened 2018-04-23 00:18 UTC
To be able customize at what point you get a notification that cannon is empty.
e.g "Cannonball notification 1 - 30: '5' " This will give a notificaiton when cannon has 5 cannonballs inside. 

This gives you enough time to fill the cannon, before it stops. Also less clicking.

**Comment by jpabeem** [comment] 2018-04-23 14:32
Shouldn't be too hard to make. After seeing [this](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java#L247), a partial rewrite of the cannon plugin might be needed though.

**Comment by Kamielvf** [comment] 2018-04-23 14:34
@jpabeem if you're interested in doing this, you can just check it [here](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java#L205).

**Comment by Nightfirecat** [comment] 2023-07-17 05:30
This was added in #10375 to address #10365, which was actually a duplicate of this issue.

**Closed by Nightfirecat** 2023-07-17 05:30 UTC
Labels: feature-request
