### ISSUE TITLE
Multiple "profiles" for RuneLite

### ISSUE THREAD

**Issue by Mantas1452** [runelite/runelite#3709] opened 2018-06-09 06:42 UTC
I'm sorry if this has been asked somewhere, I just don't know what exactly to look for.

Is there a way to have multiple instances of the client with different plugins enabled and remembered? For example, I want to have a, b, c, and d plugins enabled for my main account, but only want a, b and e plugins for my alt.

**Comment by supermxn** [comment] 2018-06-09 08:34
hmm that's actually interesting, meaning youll have a section where you get your settings saved into a profile for different accounts. I actually would like to see that to be honest.

**Comment by Mantas1452** [comment] 2018-06-09 08:45
Yeah, I probably worded it very poorly, english isn't my primary language. Maybe someone has done something like this? Maybe there's a bit of a workaround someone can share.

**Comment by Unmoon** [comment] 2018-06-09 08:47
Duplicate of #2220. See Kamiel's comment for the workaround.

**Closed** 2018-06-10 02:08 UTC
