### ISSUE TITLE
On world visible map marker

### ISSUE THREAD

**Issue by Demonbl00d** [runelite/runelite#8691] opened 2019-04-30 04:47 UTC
Since I started doing Mage arena 2, I have been thinking about a solution to be able to find the bosses.
The feature request would not only be able useful for my case but several other scenarios.

The feature would be a marker you could set on the map which would then show on the the on-world as guidance arrow or compass to lead you to that exact place that you marked.

You would be able to put multiple markers if necessary. Kinda like ground markers but then a compass like guidance tool for some specific place you marked

**Comment by Nightfirecat** [comment] 2019-04-30 05:59
Sounds like a duplicate of #5795 and/or #4496?

**Closed by Nightfirecat** 2019-04-30 05:59 UTC
