### ISSUE TITLE
Group screen markers

### ISSUE THREAD

**Issue by pettrs** [runelite/runelite#13085] opened 2021-01-18 12:19 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to group screenmarkers together and label them more organized

**Describe alternatives you've considered**

**Additional context**
nop

**Comment by Hydrox6** [comment] 2021-01-18 12:20
Duplicate of #3205

**Closed by Hydrox6** 2021-01-18 12:20 UTC
