### ISSUE TITLE
Set color and opacity of the notification flash

### ISSUE THREAD

**Issue by Snowflak3** [runelite/runelite#12128] opened 2020-07-13 15:05 UTC
This is a feature request to add a setting under the 'RuneLite' client settings to change the color and opacity of the notification flash.

The settings should allow for RGBA values to be set manually by the user, and default to the current settings.

Alternative solutions:
 - Color picker
 - Default colors in a list

No additional context

**Comment by Snowflak3** [comment] 2020-07-13 15:05
I will attempt to add this feature myself.

**Comment by Broooklyn** [comment] 2020-07-13 15:08
Duplicate of https://github.com/runelite/runelite/issues/10761

If you're wanting to tackle it yourself, do take a look at https://github.com/runelite/runelite/pull/10650. It has been abandoned but some of the work is already there

**Closed** 2020-07-13 15:09 UTC
Labels: duplicate
