### ISSUE TITLE
Item charges resets to one less than max after jewelry breaks

### ISSUE THREAD

**Issue by BeefaloKing** [runelite/runelite#14153] opened 2021-09-15 06:24 UTC
When equipped RoF breaks after final use the item charges plugin resets the charges displayed to 139 instead of 140. Manually checking charges will correctly update the display to 140.

No idea if this happens with other jewelry, I've only taken notice to RoF.

**Expected behavior**
Jewelry should have the correct charges displayed after it breaks.

**Environment (please complete the following information):**
 - RuneLite version: 1.7.24
 - Launcher version: 1.6.0

**Additional context**
I'm fairly certain this is a regression. I don't remember exactly when the behavior changed, but I do remember it behaving correctly before.

**Comment by Nightfirecat** [comment] 2021-09-15 06:26
Duplicate of #12725

**Closed by Nightfirecat** 2021-09-15 06:26 UTC
Labels: duplicate
