### ISSUE TITLE
Window Interface Screen Tearing

### ISSUE THREAD

**Issue by SpellledWrong** [runelite/runelite#13368] opened 2021-03-21 20:54 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The Runelite client is unusable due to an issue with the window tearing whenever a menu item description appears.

**To Reproduce**
Open the client
Click the right arrow next to the minimize and screenshot button
Any menu opened (for example plugin menu)
scroll through plugins and they all cause weird screen tearing issue

Tried reinstalling with old launcher and redownloaded new launcher and reinstalled, still have the same issue

**Expected behavior**
I wouldn't expect the screen to tear and stay that way. the only solution is to resize the window to see the actual menu again.

**Screenshots**
![image](https://user-images.githubusercontent.com/81115593/111920535-c60fbd80-8a4c-11eb-964f-d97b0fcc999a.png)
![image](https://user-images.githubusercontent.com/81115593/111920544-cf992580-8a4c-11eb-8234-40244a28a815.png)
![image](https://user-images.githubusercontent.com/81115593/111920564-f0617b00-8a4c-11eb-8874-0b597d8601a1.png)

**Environment (please complete the following information):**
 - OS: Windows 10 64bit
 - RuneLite version: 1.7.2.2
 - Launcher version: **not sure, but its the newest version offered on the site

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Bram91** [comment] 2021-03-21 21:02
Duplicate of #11727

**Closed** 2021-03-21 21:07 UTC
