### ISSUE TITLE
al kharid rooftop agility course hidden mark of grace in low detail

### ISSUE THREAD

**Issue by oob1234** [runelite/runelite#13483] opened 2021-04-14 15:01 UTC
I found a spot on the al kharid agility course where the mark of grace will be hidden when playing in low detail mode.

edit:
Ok I got lucky and it happened again before I got 30 agility and left for varrock course. here is the proof!
https://i.imgur.com/3oOYztd.png
https://i.imgur.com/5BFBOKw.png

**Comment by Hydrox6** [comment] 2021-04-15 15:37
Duplicate of #1481

Low Detail is a remnant of the client from 2007 that was left in. Jagex don't support it, so most new places break in some way with it.

**Closed by Hydrox6** 2021-04-15 15:37 UTC
