### ISSUE TITLE
Runelite Overlay Font Settings

### ISSUE THREAD

**Issue by ChoofHead** [runelite/runelite#13443] opened 2021-04-06 13:36 UTC
**Is your feature request related to a problem? Please describe.**
Not really a problem but when useing Bold font overlay it just seems to big.

**Describe the solution you'd like**
I would like to have the option for changing the size of the Bold font in Runelite > Overlay settings, maybe a Small, medium and large option.

**Describe alternatives you've considered**
Not useing the Bold font option but thats about it.

**Additional context**

![2021-04-06_23-33-54](https://user-images.githubusercontent.com/82038468/113719293-cee0de80-9730-11eb-85f5-e82813298f8d.png)

**Comment by Hydrox6** [comment] 2021-04-06 13:38
Duplicate of #5546

**Closed by Hydrox6** 2021-04-06 13:38 UTC

**Comment by ChoofHead** [comment] 2021-04-06 13:43
not sure why this was closed, the other post/issue is from 2018/2019

**Comment by Hydrox6** [comment] 2021-04-06 13:44
because this is a duplicate of that issue
