### ISSUE TITLE
Add charge tracker for Iban's Staff

### ISSUE THREAD

**Issue by JerwuQu** [runelite/runelite#1408] opened 2018-04-12 11:01 UTC
An overlay and/or a notification in chat when charges are running low to prevent them running out mid-combat.

I don't know if any other client does it, but I would find it very useful.

Is this a good idea? Feel free to close if not.

There's already an issue open for a (very) similar suggestion at #953, but that issue is targeted at weapons which you can have multiple of, and with different charges. Iban's Staff has shared charges among all owned staves and they are therefore a lot easier to track.

**Comment by Alexsuperfly** [comment] 2019-07-28 18:52
duplicate of #953

**Comment by JerwuQu** [comment] 2019-07-28 21:15
> duplicate of 953

I specifically mentioned in my original post why this is not an exact duplicate. 

I even went ahead and implemented this myself in PR #3023, but this was shot down in the RuneLite discord by other devs because "it could make people ask for more", referring to things like the blowpipe charges (which are a lot harder to implement). 
It doesn't really makes any sense to me to reject a feature because of that, but I don't get to decide. 

Mods can close this issue if their stance still stands. Otherwise, feel free to inform me and I'll update the (over a year old) PR.

**Comment by Nightfirecat** [comment] 2022-06-02 23:28
This is covered by runelite.net/plugin-hub/show/weapon-charges-2

**Closed by Nightfirecat** 2022-06-02 23:28 UTC
Labels: should-be-external
