### ISSUE TITLE
Loot Tracker "Show Each Kill Separately" broken

### ISSUE THREAD

**Issue by dabezian** [runelite/runelite#11582] opened 2020-05-14 06:14 UTC
**Describe the bug**
When clicking to show each kill separately, nothing happens (it stays on grouped page) for 90% of clicks. If I spam click it, it will switch over but not show any kills tracked before the switch even from the same session. I have restarted the client and my PC multiple times times, it has not worked since the last update to 1.6.14.

**To Reproduce**
Go to loot tracker tab. Switch to separate kill view.

**Expected behavior**
Should switch and show all kills for the past session/day as previous to this patch

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.14
 - Launcher version: 2.1.0

**Comment by Nightfirecat** [comment] 2020-05-14 06:19
Duplicate of #11546. This has been addressed in master and will be fixed in our next release.

**Closed by Nightfirecat** 2020-05-14 06:19 UTC
Labels: duplicate
