### ISSUE TITLE
Re-add Withdraw-X menu entry swapping now that Mobile has it

### ISSUE THREAD

**Issue by belinxi** [runelite/runelite#4732] opened 2018-08-06 05:35 UTC
Now that OSRS mobile has toggleable single click Withdraw-X it's hard to imagine jagex would have a problem with it?

**Comment by Abextm** [comment] 2018-08-06 05:37
Duplicate of #1647

runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Closed by Abextm** 2018-08-06 05:37 UTC
Labels: duplicate
