### ISSUE TITLE
Using "Open/Close Sidebar" and "Maximize/Restore" in a pattern can cause the client to increase the minimum width of the 'Restored' client 

### ISSUE THREAD

**Issue by Snowflak3** [runelite/runelite#9910] opened 2019-09-24 01:46 UTC
Overview of the Issue - When using the "Open Sidebar" and "Maximize/Restore" buttons in a specific order the minimum width of the screen increases (that is to say you cannot make it as small width-wise as the default), the process can be reversed by doing the pattern in the reverse order.

Java Version and Operating System - 
![image](https://user-images.githubusercontent.com/2498278/65473683-637d3780-de3e-11e9-80e5-ddce0207364c.png)

Reproduce the Error - Press the buttons in this order from 'Restored' screen:
- Open Sidebar
- Maximize
- Close Sidebar
- Restore
Reverse the sequence to reduce the minimum width back to normal.
This change is more noticeable on the login screen because of the black bars on the side.

Related Issues - I did not see one from my searches
Suggest a Fix - None

**Comment by justindecunha** [comment] 2019-10-09 15:12
Hello, I believe this is a duplicate of #2612. On the surface they don't look the same, but they stem from the same problem in the ContainableFrame class.

**Comment by Adam-** [comment] 2021-10-04 17:46
I think this is a duplicate of #2612 which is fixed in 38f1d2e71fd6ed17bb56d0baad463feaac1a8575

**Closed by Adam-** 2021-10-04 17:46 UTC
Labels: bug, duplicate
