### ISSUE TITLE
Pin button in the title bar to toggle always on top

### ISSUE THREAD

**Issue by Volney47** [runelite/runelite#6019] opened 2018-10-14 23:00 UTC
I think it's an underused feature since it's not easily toggle-able and is annoying to keep on. If for example you play 2 accounts where one you only need to use the inventory, pinning one client over the other to only leave the inv visible saves a lot of screen space.

**Comment by Nightfirecat** [comment] 2018-10-14 23:43
This would basically be solved by multi-account configs, which has already been requested and has a PR open, I believe.

**Comment by Volney47** [comment] 2018-10-14 23:55
I was more focused on the ease of access of the feature. If you have one monitor and have the feature turned on and want to look at your browser for example it's 3 clicks away to turn it off, assuming you have Runelite favourited. I just see the screenshot button on top and know that I use use a pin button much more often, but that's just me.

**Comment by deathbeam** [comment] 2018-10-15 06:02
Duplicate of #3586 also bad idea

**Closed by deathbeam** 2018-10-15 06:02 UTC
