### ISSUE TITLE
Rearrange quest feature

### ISSUE THREAD

**Issue by Fox4148** [runelite/runelite#2342] opened 2018-05-04 20:34 UTC
- Toggle : Remove completed quests from the list
- Toggle : Put Ongoing quests on top of the list arranged in alphabetical order, same for not started quests.

Maybe something can be done inside the diaries too, like, Removing the checked ones on the interface that shows up when you click on a diary.

**Comment by jpabeem** [comment] 2018-05-05 07:07
Partial duplicate of #1905

**Comment by deathbeam** [comment] 2018-05-05 13:05
Duplicate of #1905

**Closed by deathbeam** 2018-05-05 13:05 UTC
