### ISSUE TITLE
Freezing on "Connecting to update server" when GPU plugin is enabled

### ISSUE THREAD

**Issue by creamcast** [runelite/runelite#6763] opened 2018-11-30 16:23 UTC
**Describe the bug**
Runelite freezes on "Connecting to update server" when the GPU plugin is enabled. Disabling the GPU plugin and restarting the client allows it to continue. Previous version didn't seem to have this problem.

**To Reproduce**
1. Launch Runelite while GPU is enabled

**Environment (please complete the following information):**
 - OS: OpenSuse Leap 15
 - RuneLite version: 1.5.2.1
 - Launcher version: 1.6.1

**Additional context**
`2018-11-30 11:08:04 [main] INFO  net.runelite.client.RuneLite - Client initialization took 8980ms. Uptime: 9367ms
2018-11-30 11:08:59 [main] INFO  n.r.client.account.SessionManager - No session file exists
2018-11-30 11:09:00 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-11-30 11:09:01 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,76,210,811x533,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,5,25,801x503,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-11-30 11:09:01 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-11-30 11:09:05 [main] INFO  net.runelite.client.RuneLite - Client initialization took 8713ms. Uptime: 9099ms
2018-11-30 11:17:43 [main] INFO  n.r.client.account.SessionManager - No session file exists
2018-11-30 11:17:44 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-11-30 11:17:45 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,76,210,811x533,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,5,25,801x503,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-11-30 11:17:45 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-11-30 11:17:49 [main] INFO  net.runelite.client.RuneLite - Client initialization took 8630ms. Uptime: 9030ms
2018-11-30 11:18:36 [main] INFO  n.r.client.account.SessionManager - No session file exists
2018-11-30 11:18:36 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-11-30 11:18:38 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,76,210,811x533,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,5,25,801x503,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-11-30 11:18:38 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-11-30 11:18:40 [Thread-4] WARN  n.r.client.plugins.gpu.GpuPlugin - Canvas invalidated!
2018-11-30 11:18:40 [Thread-4] ERROR net.runelite.client.RuneLite - Game crash
com.jogamp.opengl.GLException: Surface not ready to lock: X11OnscreenGLXDrawable[Realized true,
	Factory   jogamp.opengl.x11.glx.X11GLXDrawableFactory@33dc6014,
	Handle    0x6400027,
	Surface   JAWTWindow[0x573a1c5b][JVM version: 1.8.0_181 (1.8.0 update 181)
JAWT version: 0x10004, CA_LAYER: false, isLayeredSurface false, bounds [ 0 / 0  1404 x 842 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], pixelScale 1.0x1.0, shallUseOffscreenLayer false, isOffscreenLayerSurface false, attachedSurfaceLayer 0x0, windowHandle 0x6400027, surfaceHandle 0x6400027, bounds [ 0 / 0  1404 x 842 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], window [0/0 1404x842], pixels[scale 1.0, 1.0 -> 1404x842], visible true, lockedExt false,
	config AWTGraphicsConfiguration[AWTGraphicsScreen[AWTGraphicsDevice[type .awt, connection :0.0, unitID 0, awtDevice X11GraphicsDevice[screen=0], handle 0x0], idx 0],
	chosen    GLCaps[glx vid 0x27, fbc 0xad: rgba 8/8/8/0, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4/GL4.hw], on-scr[.]],
	requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL4/GL4.hw], on-scr[.]],
	X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x27],
	encapsulated X11GLXGraphicsConfiguration[X11GraphicsScreen[X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x7f3e605c7810, owner true, JAWTToolkitLock[obj 0x77033a37, isOwner false, <3edd8891, 6e51939e>[count 0, qsz 0, owner <NULL>]]], idx 0], visualID 0x27, fbConfigID 0xad,
	requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL4/GL4.hw], on-scr[.]],
	chosen    GLCaps[glx vid 0x27, fbc 0xad: rgba 8/8/8/0, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4/GL4.hw], on-scr[.]]]],
	awtComponent al[canvas0,0,0,1404x842,invalid],
	surfaceLock <698e82cb, 7b2df4f>[count 0, qsz 0, owner <NULL>]]]
	at jogamp.opengl.GLContextImpl.destroy(GLContextImpl.java:454)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$shutDown$1(GpuPlugin.java:390)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:61)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:46)
	at net.runelite.client.plugins.gpu.GpuPlugin.shutDown(GpuPlugin.java:344)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:768)
	at ah.onPost(ah.java:84)
	at ah.p(ah.java)
	at ah.run(ah.java:311)
	at java.lang.Thread.run(Thread.java:748)
2018-11-30 11:18:41 [main] INFO  net.runelite.client.RuneLite - Client initialization took 8201ms. Uptime: 8599ms`

**Comment by deathbeam** [comment] 2018-11-30 17:30
Can you try with #6578? I had this exact issue, and that solved it

**Comment by deathbeam** [comment] 2018-12-07 20:29
Duplicate of #6523

**Closed by deathbeam** 2018-12-07 20:29 UTC
Labels: bug, gpu
