### ISSUE TITLE
Runelite GPU Plugin doesn't turn on anymore since the latest update

### ISSUE THREAD

**Issue by 3123123123monki** [runelite/runelite#6942] opened 2018-12-14 12:46 UTC
Hi,

My English won't be perfect since I'm dutch but I hope this will be understandable.
Since yesterday my GPU Plugin wont turn on anymore.
I've been using it since it came out and it has worked fine until the new client after the update.
My laptop isn't great but meets all the requirements and has always worked fine with it.

When I startup the client I try turning GPU on but my screen freezes and goes back to off immediately.
I was hoping that the client would give me the GPU plugin and make the game smooth for me again but now 50 fps feels like 30 again. (With the GPU plugin it would be so smooth)

I'm using the latest RuneLite version, I've tried reopening the client several times and I've also tried reinstalling but nothing has worked yet.

I'm playing on Windows 10, Runelite version 1.5.4. Launcher version 1.6.0.

**Comment by Adam-** [comment] 2018-12-14 12:57
Duplicate of #6931

**Closed by Adam-** 2018-12-14 12:57 UTC
