### ISSUE TITLE
Prevent dragging items when holding shift

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#2299] opened 2018-05-03 17:46 UTC
this will gain a lot of new players + a lot of pkers!

**Comment by permedd** [comment] 2018-05-03 18:03
https://gyazo.com/32234173b40d30b3dcd46e2e77df8d63
^this gyzo shows where i drag but we want a anti drag version where you are not able to drag at all meaning that when you try to move your items it wouldn't move @jpabeem do you get it?

**Comment by cam121** [comment] 2018-05-03 18:48
https://i.imgur.com/JwEaPQp.gifv

**Comment by MagicfTail** [comment] 2018-05-03 18:51
Do not add that unless it is *purely* cosmetic. I'm a Dh'er and that would be very op

**Comment by cam121** [comment] 2018-05-03 19:07
Maybe have a switch like click shift to enable no dragging then shift to allow it something like that

**Comment by Adam-** [comment] 2018-05-03 19:25
OSB prevents dragging when holding shift, so I do not see why we cannot add an equivalent feature.

**Comment by cam121** [comment] 2018-05-03 19:40
I understand that Adam but hes talking about pking with this , holding shift the entire time while switching is hell why not just an off/on button

**Comment by Fox4148** [comment] 2018-05-03 20:08
Just make the hotkey to be custom bind.

**Comment by jerwuqu** [comment] 2018-05-03 20:10
This is a duplicate of #1062 afaik

**Comment by permedd** [comment] 2018-05-03 21:33
i agree with fox4148 i would like to enable and disable it.
having to hold shift for no drag its no fun you are not able to pk properly and will be the same as other clients, this client is awesome it has its own features i think there should be a feature where you can enable and disable it and not copy osb where they have to hold shift and it wouldn't drag. :(

**Comment by jplsek** [comment] 2018-05-03 21:51
¿porque no los dos?

Similar to @Fox4148 said, we could have it where right clicking the inventory icon can toggle between dragging and not dragging AND the shift action gets inverted. So by default (can drag freely), pressing shift prevents dragging, but when toggled (cannot drag freely), pressing shift allows dragging.

**Comment by jerwuqu** [comment] 2018-05-03 21:55
I agree with @jplsek.

**Comment by cam121** [comment] 2018-05-05 16:56
Yes toggling options would make this great !

**Comment by Adam-** [comment] 2018-05-10 21:11
Duplicate of #1062

**Closed by Adam-** 2018-05-10 21:11 UTC
Labels: feature-request
