### ISSUE TITLE
World hopping

### ISSUE THREAD

**Issue by Justinas95** [runelite/runelite#1657] opened 2018-04-18 14:26 UTC
Hello.

I wanted to request for option for world hopping in friends list screen. if i right click friends name I would like to see option to: Hop to world. By that I mean that I would like to hop to his world by clicking his name and not going to world selector screen.

**Comment by MESLewis** [comment] 2018-04-18 14:30
Duplicate of #1617 
You can give a thumbs up to that issue to show you are also interested in it

**Closed** 2018-04-18 14:33 UTC
