### ISSUE TITLE
Bank Tag Profiles

### ISSUE THREAD

**Issue by Waldrin73** [runelite/runelite#14619] opened 2022-01-21 08:52 UTC
**Is your feature request related to a problem? Please describe.**
Yes. It's problematic because there isn't any point for me having my main account bank tag layout on a fresh HCIM or a new GIM account.

**Describe the solution you'd like**
There should be a way to switch between profiles for the Bank Layout plugin so you can have different layouts for different accounts.

**Describe alternatives you've considered**
I'm aware you can setup multiple Runelite accounts, however it doesn't seem to be a viable option for most people. It's also tedious to setup/use.

**Additional context**

**Comment by adamk33n3r** [comment] 2022-01-21 09:03
Shouldn't this be reported here? https://github.com/geheur/bank-tag-custom-layouts/issues

**Comment by raiyni** [comment] 2022-01-22 03:04
Duplicate of https://github.com/runelite/runelite/issues/6118 if this is just for bank tags, otherwise make an issue on the plugins repo.

**Closed by raiyni** 2022-01-22 03:04 UTC
