### ISSUE TITLE
Swap "Activate" and "Teleport to destination" on wildy obelisk

### ISSUE THREAD

**Issue by CaraPis** [runelite/runelite#4424] opened 2018-07-20 13:14 UTC
Ability to swap "Activate" and "Teleport to destination".
https://i.imgur.com/vrtVG7k.png

**Comment by CaraPis** [comment] 2018-07-20 14:57
Ok, so i have checked a bit in the menu entry swapper code and i managed to create what i wanted, pretty proud of myself tbh. Don't judge me, i'm nub at this xD. https://i.imgur.com/H7wOtCm.png
Anyways, how do i submit the code for it?

**Comment by deathbeam** [comment] 2018-07-20 18:42
Duplicate of #1644

**Closed by deathbeam** 2018-07-20 18:42 UTC
Labels: feature-request
