### ISSUE TITLE
QoL PK'ing & Clanning Features Request

### ISSUE THREAD

**Issue by tsenif** [runelite/runelite#5074] opened 2018-08-23 08:02 UTC
**Is your feature request related to a problem? Please describe.**
Freeze timers are incorrect, pretty frustrating. Teleblock timer is also inaccurate as well.

**Describe the solution you'd like**
- A simpler team-cape overlay, something that isn't so intrusive/large. The icon of the team-cape, for example team-37 cape. Rather than displaying team-37 cape: 1, have a small image of that team-cape with the number of that cape, followed by the quantity of people wearing that team-cape. Konduit does this very well.

- Menu-entry swap for clan-mates (without wearing the team-cape, so long as they're in the same clan chat) & friends, so avoid miss-clicking your clan-mates or friends if you're not wearing team-capes. https://i.imgur.com/OjrqMYJ.png - here is an example.

- Fixed freeze timers. The current barrage/freeze timers are always off by a few seconds. Also, a freeze timer for your opponent & when they're unfrozen would be a great feature.

- 
**Describe alternatives you've considered**
Other clients have these features.

**Additional context**
- Team-cape overlay re-design: https://i.imgur.com/OjrqMYJ.png
- Freeze timer displayed next to the opponent, freeze timers/tb timers fixed.

**Comment by datashe12** [comment] 2018-08-23 12:09
Freeze and tb timers on opponents have already been suggested quite a few times just so you know

**Comment by Nightfirecat** [comment] 2018-08-23 16:53
Freeze timers should now be pretty much accurate. Could you get a gif or video of this inaccuracy you're talking about?

**Comment by deathbeam** [comment] 2018-08-23 18:31
Duplicate of multiple issues looks like

**Closed by deathbeam** 2018-08-23 18:31 UTC
