### ISSUE TITLE
Gauntlet loot plugin

### ISSUE THREAD

**Issue by The1Investigator** [runelite/runelite#13837] opened 2021-07-05 21:46 UTC
Gauntlet currently tracks both failed and successful loot attempts. Proposal is to make a plugin to track both failed and successful loot, which will either add or subtract the kill count counter respective to it being enabled/ disabled.

Example displayed below :

Loot tracker with plugin disabled
![](https://i.imgur.com/9rxGoMU.png)

Loot tracker with plugin enabled
![](https://i.imgur.com/9h2X6Q1.png)

**Comment by Hydrox6** [comment] 2021-07-05 21:48
Duplicate of #11279

Also, it's not really a thing to make a plugin for a plugin

**Closed by Hydrox6** 2021-07-05 21:48 UTC

**Comment by The1Investigator** [comment] 2021-07-05 21:50
Oop. Didn't realise someone had suggested this!
