### ISSUE TITLE
"Hide auto retaliate" breaks the special attack bar

### ISSUE THREAD

**Issue by tsmfinal** [runelite/runelite#8921] opened 2019-05-25 01:40 UTC
This bug is a duplicate, but the implications of the bug are massive and the previous report was over 3 months ago.

The bug is that when using the "hide auto retaliate" feature within the "Attack Styles" plugin, the special attack bar gets screwed up. Specifically, depending on what special attack (or lack thereof) the player has equipped when the feature is enabled, the combat styles interface will maintain that weapon's special attack bar, even when another weapon has been equipped.

For example, if the player is holding a magic shortbow and then turns on the "hide auto retaliate" feature, any other weapons will keep the magic shortbow's special attack bar and its description. 

Another example would be that if the player turns on the feature while bare-handed, no other weapons will be able to use their special attack.

The implication of this is that players can use the plugin to one-tick a special attack **from a weapon without a special attack, such as rune knives**. What you do is enable the plugin while holding a weapon with a special attack bar, then switch to the knives. You have the special attack bar, but still get to use rune knives (or a rune crossbow or whatever).

To reproduce:
1) Equip a magic shortbow (or any weapon with a special attack)
2) Turn on "Hide auto retaliate"
3) Switch to any weapon without one
4) Observe how the special attack bar stays

OR

1) Be bare-handed
2) Turn on the feature
3) Switch to any weapon with a spec. bar
4) You cannot spec

What should happen is that the feature only gets rid of the auto-retaliate button, and doesn't mess with the special attack bar at all. 

**Screenshots**
![brojken spec2](https://user-images.githubusercontent.com/51010322/58363040-60604380-7e6c-11e9-89dd-33df7df1afa0.png)

![broken spec](https://user-images.githubusercontent.com/51010322/58363039-59393580-7e6c-11e9-92d2-5ace92babc47.png)

Environment:
Windows 10
RuneLite version: 1.5.24
Launcher: 1.60

**Comment by deathbeam** [comment] 2019-05-25 14:12
Duplicate of #7851

**Closed by deathbeam** 2019-05-25 14:12 UTC
