### ISSUE TITLE
Add "Search for traps" to Menu Entry Swapper

### ISSUE THREAD

**Issue by jrite09** [runelite/runelite#8099] opened 2019-03-04 14:04 UTC
**Is your feature request related to a problem? Please describe.**
Specifically on the thievable chests like the Nature Rune chest in Ardougne/Rellekka.

**Describe the solution you'd like**
Ability to swap "Open" with "Search for traps" as the left-click option.

**Comment by Hydrox6** [comment] 2019-03-04 14:06
Duplicate of #7622, which is denied

**Comment by jrite09** [comment] 2019-03-04 14:08
Ah, rip. I didn't find that issue when searching. Thanks!

**Closed** 2019-03-04 14:10 UTC
