### ISSUE TITLE
Experience tracker incorrectly calculating xp/hr

### ISSUE THREAD

**Issue by alexschex** [runelite/runelite#15079] opened 2022-06-10 04:31 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

While building oak dungeon doors, the xp/hr tracker doesn't seem to be functioning properly. Each door built adds 36k to the xp/hr and the value doesn't decrease when I stop building doors. 

### RuneLite version

Runelite version: 1.8.21
Launcher version: 1.6.0

### Logs

[client.log](https://github.com/runelite/runelite/files/8875768/client.log)
[launcher.log](https://github.com/runelite/runelite/files/8875769/launcher.log)

**Comment by Nightfirecat** [comment] 2022-06-10 04:35
Duplicate of #10099

We don't currently know what causes this and have no way to reproduce it. (it seems to be very rare, and is fixed by restarting the client)

**Closed by Nightfirecat** 2022-06-10 04:35 UTC
Labels: duplicate

**Comment by alexschex** [comment] 2022-06-10 04:48
> Duplicate of #10099
> 
> We don't currently know what causes this and have no way to reproduce it. (it seems to be very rare, and is fixed by restarting the client)

I haven't restarted my client yet, is there anything you'd like me to do to help find the bug?

**Comment by RedSparr0w** [comment] 2022-12-10 01:37
Just had this same bug.
![image](https://user-images.githubusercontent.com/7288322/206822295-5ade2d1e-a42c-44cb-8ce9-c9a1d9e33ae9.png)

Seems it was caused by my computers date going backwards (even after reseting the tracking, it would still just go up and up)

**Comment by alexschex** [comment] 2022-12-10 03:15
> Just had this same bug.
> 
> ![image](https://user-images.githubusercontent.com/7288322/206822295-5ade2d1e-a42c-44cb-8ce9-c9a1d9e33ae9.png)
> 
> 
> 
> Seems it was caused by my computers date going backwards (even after reseting the tracking, it would still just go up and up)

Nice catch, my computer's clock has also been off after restart for a long time so that's likely the culprit.
