### ISSUE TITLE
World hopping - mining Adamant / Runite timer and world logger

### ISSUE THREAD

**Issue by M-a-x-y** [runelite/runelite#6659] opened 2018-11-24 07:59 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

When mining rune ore and keeping track of the timer for re-spawn, I find it frustrating to start various different timers and trackers to know which world will next re-spawn for me to mine.

**Describe the solution you'd like**

I would like a plugin that displays a list of worlds that I've mined a certain rock in even after I've hopped world. As well as a 'countdown' until that resource is available again in that world. This could include Adamant and Runite rocks as most others are not hop-mined.

**Describe alternatives you've considered**

Running timers and stopwatches. This quickly falls apart as it can take a varied amount of time to mine something.

**Additional context**

**Comment by deathbeam** [comment] 2018-11-24 12:53
Duplicate of #3097

**Closed by deathbeam** 2018-11-24 12:53 UTC

**Comment by M-a-x-y** [comment] 2018-11-27 04:12
Hi @deathbeam I opened this from your advise received on #6600 and considered it different to #3097 (which seems very broad and without scope for world tracking?). 

Should I contribute on #3097 (or #3924 for the thieving aspect) or should I make a seperate thieving world tracking feature request? 

Thank you again.

**Comment by M-a-x-y** [comment] 2018-11-27 04:15
or #4557 would be a nice canidate to include world tracking functionality?

**Comment by Nightfirecat** [comment] 2018-11-27 04:35
#4557 seems like one possible implementation to address/close #3097, of which this issue seems to be a duplicate of.

**Comment by M-a-x-y** [comment] 2018-11-27 04:57
#3097 or #4577 doesn't look to log a list of worlds and spawn times - this is the core feature of my request for mining rune while world hopping. 

Or am I missing something??

**Comment by Nightfirecat** [comment] 2018-11-27 05:37
I guess this would be better as a comment on 3097 mentioning that you'd find it helpful to persist timers across world hops as well. It's essentially the same request with a small bit of extra functionality.

**Comment by M-a-x-y** [comment] 2018-11-27 05:39
Thanks @Nightfirecat
