### ISSUE TITLE
My client keeps crashing in roughly the same time frame

### ISSUE THREAD

**Issue by Lesser16** [runelite/runelite#16700] opened 2023-06-22 18:08 UTC
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When running Runelite I can easily load into the game no issues. However as of recently when I launch and play for around 2 minutes I crash. 
Additional notes
I have a good computer so hardware specs are not the issue I don't think
I just recently updated my drivers and then the issues started occurring
I use the HD plugin

### RuneLite version

1.10.5
2.5.0

### Logs

![c2c4aa4202fa9069927a7ba0247007b2](https://github.com/runelite/runelite/assets/67518861/bcab94b2-e887-482c-b380-0622bef0650d)

**Comment by Lesser16** [comment] 2023-06-22 18:17
If anyone who could help me would like to see the issue in action I can email it to you

**Comment by Nightfirecat** [comment] 2023-06-22 18:30
Please upload the log file, not just a screenshot of it. Thanks

**Comment by Lesser16** [comment] 2023-06-22 18:57
Sorry about that
[jvm_crash_pid_3436.log](https://github.com/runelite/runelite/files/11839290/jvm_crash_pid_3436.log)
I fixed the issue by removing my ram however the crash log says nothing about ram as the issue.

**Comment by Nightfirecat** [comment] 2023-06-22 18:59
Duplicate of #10628, we don't know what causes this crash. We've heard hearsay that it only affects people with ADM Ryzen processors, but we don't have any kind of information which would lead to a fix for it.

**Closed by Nightfirecat** 2023-06-22 18:59 UTC
Labels: duplicate
