### ISSUE TITLE
Runelite not loading

### ISSUE THREAD

**Issue by Vedzitas** [runelite/runelite#2708] opened 2018-05-14 08:19 UTC
The launcher stucks at 0% and turns off,nothing helps for it to work.
![screenshot_34](https://user-images.githubusercontent.com/39259869/39985869-a1fb8830-5768-11e8-8ac6-feeeb2f3f8d0.png)

would like to play on the runelite...

**Comment by deathbeam** [comment] 2018-05-14 08:36
Duplicate of https://github.com/runelite/launcher/issues/18

**Closed by deathbeam** 2018-05-14 08:36 UTC
