### ISSUE TITLE
Display current prices of items in Grand Exchange 

### ISSUE THREAD

**Issue by Cwade789** [runelite/runelite#1541] opened 2018-04-14 23:03 UTC
I am curious if this is possible? So in theory, we would look up abyssal whip in the grand exchange menu and it would show: how many abyssal whips are currently selling in the ge and/or show what price the whips are selling for (not the average price, but the actual price the whip is sitting in the ge for).
This feature would be awesome for deadmanmode because prices vary so largely, but in the main game as well. -feature!

**Comment by deathbeam** [comment] 2018-04-15 00:08
Duplicate of #733

**Closed by deathbeam** 2018-04-15 00:08 UTC
Labels: duplicate

**Comment by Cwade789** [comment] 2018-04-15 00:11
Thanks deathbeam, I will read up on what that post talked about!
