### ISSUE TITLE
Suggestion: A plugin for ironmen which only displays the name of items on the ground that can be picked up and ignores the name of items I can't pick up.

### ISSUE THREAD

**Issue by SaranethPrime** [runelite/runelite#14048] opened 2021-08-20 22:20 UTC
**Is your feature request related to a problem? Please describe.** 
As an Iron Man player, it can be annoying to see so many items on the ground that you can't actually pick up. This is especially troublesome as I am a new player. I sometimes assume I can't pick up an item on the ground because I thought it was left by a player. In actuality, it was naturally spawning so I could take it. 

**Describe the solution you'd like** 
It would be cool to have a plugin that only shows the text for items that can be picked up and does not display text for things that can't be picked up.

**Comment by Hydrox6** [comment] 2021-08-20 22:21
`Ground Items` has an option called `Only show loot` that does this. If you mean removing menu entries, Duplicate of #12902

**Closed by Hydrox6** 2021-08-20 22:21 UTC

**Comment by SaranethPrime** [comment] 2021-08-20 22:32
> `Ground Items` has an option called `Only show loot` that does this. If you mean removing menu entries, Duplicate of #12902

Thank you for the help bro!
