### ISSUE TITLE
Player Indicator Wilderness Only Option

### ISSUE THREAD

**Issue by geo9955** [runelite/runelite#13205] opened 2021-02-12 05:31 UTC
Being able to have a bright red outline to show me potential pkers is very useful,
however I don't need the same functionality when safe from them.

While a quick an easy check box is all that needs to change to disable Other indicators,
it's still cumbersome to do that every time I'm doing a clue in the Wild for example.

If there were an option to have it so that other players were only outlined when in the Wilderness,
and not in the rest of the world (except for friends, clanmates, etc.), this would save the effort.

**Comment by Nightfirecat** [comment] 2021-02-12 06:21
Duplicate of #3684

**Closed by Nightfirecat** 2021-02-12 06:21 UTC
Labels: duplicate
