### ISSUE TITLE
Player Indicators: Highlight other players only in wilderness

### ISSUE THREAD

**Issue by pluffindonk** [runelite/runelite#9807] opened 2019-09-04 05:38 UTC
**Is your feature request related to a problem? Please describe.**
You can already achieve this by enabling highlight non-clan members whenever you enter the wildy.  The only thing this would really change is the need to toggle it every time you leave so you're not bombarded by dozens of names at the GE.

**Describe the solution you'd like**
Give us the option to highlight other players only when in the wilderness.  Not asking it to take into consideration whether or not they're attackable or not, just that they're there.

**Comment by Hydrox6** [comment] 2019-09-04 14:38
Duplicate of #3684

**Closed by Hydrox6** 2019-09-04 14:38 UTC
