### ISSUE TITLE
Custom key binding for moving UI around

### ISSUE THREAD

**Issue by Ogieeeeee** [runelite/runelite#14143] opened 2021-09-14 09:18 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
Right now to move the UI you have to press the ALT key and then you can drag stuff around. The problem is that I'm using the alt and left mouse click to turn my screen around. I don't like using the middle mouse button. Every time I press alt to turn my screen around I also see the text of the items that are dropped on the ground which I don't want to see when they are below in some threshold. This is specially annoying in COX when doing scavs. I know this was like this always and I'm kinda used to it but it's still a bit annoying. 

**Describe the solution you'd like**
In the settings (maybe under Runelite) it would be great if the user is able to change it to a custom key or multiple keys pressed for for the dragging behaviour to trigger. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
Ehhm, maybe change it to CTRL + ALT ?

**Additional context**
![image](https://user-images.githubusercontent.com/22215187/133231148-5b9f16c2-5667-4c56-a632-4238b503d11a.png)

**Comment by Hydrox6** [comment] 2021-09-14 09:39
Duplicate of #7831

**Closed by Hydrox6** 2021-09-14 09:39 UTC
