### ISSUE TITLE
[Loot Tracker] Track ores/gems obtained via Motherlode Mine

### ISSUE THREAD

**Issue by Veeeeeeeee** [runelite/runelite#5865] opened 2018-10-07 16:12 UTC
Not sure how impossible this feature is but it would certainly be a nice way to keep track of what ores/gems I receive through a long stint of MLM.

**Comment by deathbeam** [comment] 2018-10-07 16:53
Duplicate of #4126

**Closed by deathbeam** 2018-10-07 16:53 UTC
