### ISSUE TITLE
Progress bar to a goal

### ISSUE THREAD

**Issue by Juzzed** [runelite/runelite#2364] opened 2018-05-05 09:46 UTC
Add a feature that allows you to set a goal for a skill so you can see the % progress for it 
![48341acb41100b768f02abf75cc2e119](https://user-images.githubusercontent.com/25037124/39661892-dc4e4038-5059-11e8-940b-7665781224e6.png)

**Comment by jpabeem** [comment] 2018-05-05 15:37
Duplicate of #1168

**Closed** 2018-05-05 15:38 UTC
Labels: feature-request
