### ISSUE TITLE
Ability to filter out NPCs from Loot Tracker

### ISSUE THREAD

**Issue by follmer** [runelite/runelite#11369] opened 2020-04-25 20:29 UTC
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Input box on the Loot tracker plugin for "Ignored NPCs"

**Describe alternatives you've considered**
None, you currently just have to clear all unwanted npcs

**Additional context**

**Comment by Hydrox6** [comment] 2020-04-25 20:31
Duplicate of #7482

**Closed by Hydrox6** 2020-04-25 20:31 UTC
