### ISSUE TITLE
[Farming Tracker] Show if patch has been treated with compost

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#3978] opened 2018-06-23 17:59 UTC
Sometimes I forget to ultracompost a patch and then I have to play the guessing game with which one it is. Would be nice if there was an icon/text/etc if a specific patch has been treated with compost while it is growing.

**Comment by deathbeam** [comment] 2018-06-23 20:35
Duplicate of #2472

**Closed by deathbeam** 2018-06-23 20:35 UTC
