### ISSUE TITLE
Skyboxes

### ISSUE THREAD

**Issue by majorvegas** [runelite/runelite#5181] opened 2018-08-28 21:44 UTC
Would it be possible to add a toggle that allows a skybox? Not asking for anything crazy, a simple shade of light blue would work for me.

I think you could probably just add a polygon/texture behind the rendering, I'm not super sure how it works. 

While I don't care that deeply how the skybox changes based on context, I think it would be possible to add night modes, or cave modes if this functionality was added.

**Comment by deathbeam** [comment] 2018-08-29 05:26
Duplicate of #3941

**Closed by deathbeam** 2018-08-29 05:26 UTC
