### ISSUE TITLE
Fishing spots (barbarian heavy rod fishing)

### ISSUE THREAD

**Issue by ReinierAarnink1996** [runelite/runelite#13663] opened 2021-05-30 13:28 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I'm fishing at baxtorian falls, heavy rod fishing. I turn on hide npcs to hide random event npcs. It does that, but it also makes me unable to click the fishing spot. I do not get the option "Use-rod". 

**Expected behavior**

To  be able to fish after I checked on hide NPCs. 
**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Hydrox6** [comment] 2021-05-30 13:29
Duplicate of #2558

**Closed by Hydrox6** 2021-05-30 13:29 UTC
