### ISSUE TITLE
Mage Training Arena helper

### ISSUE THREAD

**Issue by DuhFonzz** [runelite/runelite#2848] opened 2018-05-17 23:58 UTC
Some helpful overlays in the mage training arena would be very nice for anyone going through for btp etc.

Ideas I had without actually doing much MTA 

Guide path for the telekinetic room so you don't need to memorize the correct routes (overlay the path to take, or highlight the spot to telegrab from, or both)

Showing the items in the cupboards in the alchemy room, since the pattern is known after looting an item.

I have yet to try enchanting or graveyard, but I'm sure others could input useful overlays those rooms could use.

**Comment by psikoi** [comment] 2018-05-18 00:15
This is interesting, id like a go at this. Hopefully get a mages book in the process.

**Comment by deathbeam** [comment] 2018-05-18 16:36
Duplicate of #2218

**Closed by deathbeam** 2018-05-18 16:36 UTC
