### ISSUE TITLE
Count how many times a monster has attacked you

### ISSUE THREAD

**Issue by andrewterra** [runelite/runelite#6372] opened 2018-11-06 17:19 UTC
I'm always frustrated when I'm doing Vorkath and usually I can easily count how many times he has attacked and when he will go into poison phase but I always have trouble the first phase because I'm focusing on speccing with my BGS. 

I'd like a counter (really anywhere on the screen) that counts how many time the monster has attacked me. This would be extremely helpful for people trying to learn bosses with phases as well as people trying to get more efficient. 

I think you should have the ability to configure what monsters will have their attacks counted. Maybe the monsters that are tagged have their attacks counted for instance.

**Comment by deathbeam** [comment] 2018-11-06 21:47
Duplicate of #2447

**Closed by deathbeam** 2018-11-06 21:47 UTC
