### ISSUE TITLE
Custom Cursor Change

### ISSUE THREAD

**Issue by Iniuria** [runelite/runelite#11160] opened 2020-04-01 02:26 UTC
Similar to RS3. If the 'Equipped Weapon' was used when the 'Attack' option has hovered that'd be cool. Say I'm ranging then I'd be able to tell which switch I did or didn't hit. This could also lead to other things such as coins appearing for trade. Something along those lines. Felt like it might be possible but have no clue tbh.

Thanks

**Comment by Nightfirecat** [comment] 2020-04-01 02:36
Duplicate of #4207

**Closed by Nightfirecat** 2020-04-01 02:36 UTC
Labels: duplicate
