### ISSUE TITLE
Puzzle Box Solver Missing Puzzle

### ISSUE THREAD

**Issue by xdenvy** [runelite/runelite#4490] opened 2018-07-24 23:11 UTC
Puzzle Box solver missing Monkey Madness puzzle box  received from Daero (gnome glider puzzlebox)
Expected outcome would be to show solve method like all other puzzle boxes received from clue scrolls.

Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Nightfirecat** [comment] 2018-07-24 23:14
Duplicate of #2063.

**Closed** 2018-07-25 00:38 UTC
Labels: duplicate
