### ISSUE TITLE
client crashing not related to login crash guy 

### ISSUE THREAD

**Issue by ListerRs** [runelite/runelite#3330] opened 2018-05-26 01:14 UTC
no clients will load they all just crash ive un and reinstalled java runelite and anythign relating to runescape still not working i just want to play runescape

**Comment by ListerRs** [comment] 2018-05-26 01:16
also thanks for just closing my other issue and not helping at all :)

**Comment by deathbeam** [comment] 2018-05-26 02:11
What if you try this? https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration. Also, next time just comment on your original issue so it can be reopened.

**Comment by Kamielvf** [comment] 2018-05-26 02:12
Also possibly delete jagexcache in your home dir

**Comment by Mithooen** [comment] 2018-10-01 15:41
Neither did that work..

**Comment by deathbeam** [comment] 2018-10-01 17:20
I believe this was similar thing as the current login crash, e.g related to JVM bug. Also the author did not provided any info, so we can just close it as duplicate of that now. Duplicate of #5675

**Closed by deathbeam** 2018-10-01 17:20 UTC
Labels: bug
