### ISSUE TITLE
Graphical issue when opening runelite addons tab

### ISSUE THREAD

**Issue by thefirstastro** [runelite/runelite#12535] opened 2020-09-22 14:13 UTC
When you open the Runelite addons tab after moving my mouse around for a little while my addons page will start to glitch out.  There used to be an open case discussing this issue but it was closed with a redirection link to https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

Unfortunately, every solution in that link did not resolve my issue so I was wondering if there is anyone that knows another fix.  I really want to fix this because I basically can't change any of my plugin settings because of this.

![issue](https://user-images.githubusercontent.com/23348165/93893815-11bef580-fcbc-11ea-849a-573066185f12.png)

**Comment by Hydrox6** [comment] 2020-09-22 14:20
Duplicate of #11727

**Closed by Hydrox6** 2020-09-22 14:20 UTC
