### ISSUE TITLE
Display fairy rings/codes (and other teleportation methods?) on world map

### ISSUE THREAD

**Issue by JustANull** [runelite/runelite#902] opened 2018-03-08 21:43 UTC
The idea is some kind of overlay on the world map that could show fairy ring destinations with codes attached, potentially along with highlighting other transportation networks like the spirit tree network.

(feature request, I'd tag it myself but no perms)

**Comment by ShaunDreclin** [comment] 2018-03-09 21:58
Do we have a way to attach overlays to certain locations on the world map?

**Comment by MESLewis** [comment] 2018-05-15 14:01
Fairy rings will be in the client Thursday per #2451 

I'm going to work on some other transportation methods today as well.

**Comment by deathbeam** [comment] 2018-05-15 14:02
Duplicate of #1067 . Comment your other ideas there.

**Closed by deathbeam** 2018-05-15 14:02 UTC
Labels: feature-request
