### ISSUE TITLE
!task for slayer task

### ISSUE THREAD

**Issue by edgarsaurus** [runelite/runelite#3794] opened 2018-06-14 16:44 UTC
since RuneLite supports tracking tasks as well as chat commands, seems like it should be easy to program. !task should put in chat what my task is and how many I have left.

**Comment by Hydrox6** [comment] 2018-06-14 16:46
This information is already available to you through an infobox (which may or may not be a bit broken atm), as well as a number on your slayer helmet/enchanted gem/ring of slaying.

**Comment by deathbeam** [comment] 2018-06-14 17:28
Duplicate of #798

**Closed by deathbeam** 2018-06-14 17:28 UTC
