### ISSUE TITLE
 Ability to setup Screen Markers into "Groups"

### ISSUE THREAD

**Issue by JoshuaNLG** [runelite/runelite#13555] opened 2021-05-01 02:49 UTC
The ability to setup screen markers as a group, so that a simple click would toggle all of them would be a nice feature to have I think.

For example let's say i have 10 screen markers set up
1-5 are for activity A
6-10 are for activity B

Simply click the group and all of the markers in that group are enabled at the same time, perhaps add the ability to also expand the group so othat you can toggle on and off individual markers in the group if needed.

**Comment by Nightfirecat** [comment] 2021-05-01 03:07
Duplicate of #3205

**Closed by Nightfirecat** 2021-05-01 03:07 UTC
Labels: duplicate
