### ISSUE TITLE
Entity Hider plugin no longer hiding pets

### ISSUE THREAD

**Issue by BegMe2Stop** [runelite/runelite#15101] opened 2022-06-13 03:15 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

At GoTR, I can hide players and npcs, but the hide pets option does nothing

### Screenshots or videos

![2022-06-12_23-14-03](https://user-images.githubusercontent.com/107380572/173273160-b787740a-d888-497b-8a33-3a182017ae59.png)

**Comment by Nightfirecat** [comment] 2022-06-13 03:28
Duplicate of #15088, this has been fixed and will be working as expected as of our next release.

**Closed by Nightfirecat** 2022-06-13 03:28 UTC
Labels: duplicate
