### ISSUE TITLE
Ability to export the Loot from the Loot tracker into Excel/google sheets etc.

### ISSUE THREAD

**Issue by Castro3halo** [runelite/runelite#5823] opened 2018-10-05 08:40 UTC
The ability to export the data for use in excel, for calculation of drop % much better than manually recording data. (specifically just the local client not tracking all clients drops and exporting that data)

**Comment by deathbeam** [comment] 2018-10-05 08:49
Duplicate of #4671

**Closed by deathbeam** 2018-10-05 08:49 UTC
