### ISSUE TITLE
Ring of Suffering (r) overrides Special Attack Counter for Bandos God Sword

### ISSUE THREAD

**Issue by tgeene** [runelite/runelite#12008] opened 2020-06-28 06:15 UTC
**Describe the bug**
If you are wearing a Ring of Suffering (r) (maybe Recoils as well) and a Recoil charge is used at the same time that you use your BGS Special on a creature the display at the top can end up showing the Recoil damage instead of the BGS damage. I don't know if this is a problem that will be fixable, as it depends on how your system pulls the damage done. I just wanted to let you know.

**Comment by auteriman** [comment] 2020-11-08 04:23
This is also an issue with Dragon warhammer, and i believe with arc/darklight aswell as the special attack counter plugin tracks those too. This bug is easy to reproduce at Corporeal beast as you often proc the ring of recoil damage to him at the same time while you spec it.

**Comment by DivineInsanity** [comment] 2021-03-08 21:22
I believe this issue may also occur with Vengeance damage, as i'm experiencing this at KQ too (am wearing a suffering, so its also likely triggering by that, will test without a suffering to see if I can reproduce with just Vengeance damage).

**Comment by Adam-** [comment] 2021-03-08 21:24
This happens with any damage that can happen in between you using the spec and the hitsplat appearing. We don't believe it is fixable currently since we can't tell the damage type of hitsplats.

**Comment by Adam-** [comment] 2022-06-24 02:30
There's a decent chance this is fixed by 5e038b726c514cfbe4380f019d120178b24edd6d, assuming it works similarly to veng - let me know if it doesn't.

**Closed by Adam-** 2022-06-24 02:30 UTC
Labels: bug
