### ISSUE TITLE
Extra Attack option

### ISSUE THREAD

**Issue by TheArbalist** [runelite/runelite#1627] opened 2018-04-17 07:44 UTC
Could we get an extra attack option that works opposite to the "Depends on combat levels" option? 
Namely, that you'd only be able to left-click attack NPCs that are lower level than you; Im requesting an extra option that allows you to make the attack option on lower level monsters be right-click only. This would help a fair bit at Sire, for example.

**Comment by king-koda** [comment] 2018-04-17 15:18
**current implementation**
Depends on combat levels - This is the default setting. If a monster's combat level is lower than yours, the first option will be 'attack'. If it is higher, the first option will be 'walk here'. Monsters above level 126 will also have 'attack' as the first option.

I think what TheArbalist is hoping to get added is the prevention of attack being the first option on monsters above 126 combat, whilst the left click attack option remaining for monsters lower level than you. Perhaps this suggestion is for the first phase in case a minion spawns, then you could walk under the boss and prioritize attacking the minion instead ??

**Comment by TheArbalist** [comment] 2018-04-17 17:00
king-koda is correct in his explanation of the feature I'm correcting, though his reasoning is a bit off. Kamielvf hit the nail on the head.

**Comment by deathbeam** [comment] 2018-11-27 12:50
Basicaly duplicate of #2667

**Closed by deathbeam** 2018-11-27 12:50 UTC
Labels: feature-request
