### ISSUE TITLE
Jad prayer indicator did not appear 6/19/18

### ISSUE THREAD

**Issue by y0nv** [runelite/runelite#3904] opened 2018-06-19 20:53 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
|installed runelite specifically to get the Jad prayer indicator, but it did not appear at all when I got to him.| ---------------
| Java Version | x.y.z
| Operating System | e.g. Ubuntu/Windows/MacOS

<details>
 <summary>stack trace</summary>
 
 ```
  %paste your stack trace here%
 ```
</details>

**Comment by Nightfirecat** [comment] 2018-06-19 20:54
Without any information, this is a duplicate of #603.

What client size were you using? (fixed, stretched, etc.)

**Comment by y0nv** [comment] 2018-06-19 21:00
It was full screen. I have viewed the Jad indicator working on the same screen setting on a friend's computer, and this was my reason for getting it myself. The plugin is turned on, so I don;t know what's up. The only difference between me and my friend's situation is he has windows and I have Mac.

**Comment by nicklit** [comment] 2018-06-22 12:09
Was Jad in view on your screen during his animation? Although I haven't looked at the code, I believe the code is based on Jad's animation rather than the sound he makes. When I got to Jad, I ran until he was offscreen and the prayer indicator did not appear, so I had to use sound. Was this the case for you? @y0nv

**Comment by deathbeam** [comment] 2018-06-22 12:16
I got report by other user that the Jad overlay switched to wrong prayer while Jad being in the view for entire time. Maybe the issue is we are scheduling the checks wrong (instead of using GameTick we use fixed 600ms schedule)

**Closed** 2018-06-25 16:24 UTC
Labels: bug
