### ISSUE TITLE
SUGGESTION/Request - Different fonts

### ISSUE THREAD

**Issue by Beastly55** [runelite/runelite#8130] opened 2019-03-06 22:55 UTC
Would love to see different font types available for ground items, mouse tool tips, etc. Perhaps also adding a star beside highlighted items for example from Konduit. Any feedback or info is greatly appreciated!

**Comment by Hydrox6** [comment] 2019-03-06 22:55
Duplicate of #5546

**Closed** 2019-03-06 22:56 UTC
