### ISSUE TITLE
Bank Tag Folders/Groups

### ISSUE THREAD

**Issue by OliverBroadbent** [runelite/runelite#10045] opened 2019-10-12 22:19 UTC
**Is your feature request related to a problem? Please describe.**
Bank tags are amazing, and we use them a lot. The issue it that I have so many tags that i have to scroll through the list for so long, that it's become faster to just withdraw the items via normal navigation. This is even worse when playing in fixed mode... Browsing through the issues I see other people agree.

**Describe the solution you'd like**
Bank tag folders. They would look and function exactly like Discord server folders. (Might add concept art later)

For example, I would have a folder called "bosses", which would have all my gear tags for bossing. another for daily farm runs, etc etc.

**Describe alternatives you've considered**
This is also an interesting idea that I came across - https://github.com/runelite/runelite/issues/9625 but i feel this integration would flow better

**Comment by Alexsuperfly** [comment] 2019-10-12 22:25
duplicate of #9625

**Comment by OliverBroadbent** [comment] 2019-10-12 22:26
> duplicate of #9625

Not a duplicate. I reference this in my post. Same issue, different solution.

**Comment by OliverBroadbent** [comment] 2019-10-12 22:56
Is this getting closed? Should I post my concept art here or at #9625?

**Comment by Nightfirecat** [comment] 2020-02-18 04:05
I agree with alex. This is generally the same concept as 9625, but expanded in scope to have more configurable "folders" of tags, essentially. Any concept art you have for this feature is welcome there!

**Closed by Nightfirecat** 2020-02-18 04:05 UTC
