### ISSUE TITLE
Old Varrock guards

### ISSUE THREAD

**Issue by kingOfvarrock** [runelite/runelite#4024] opened 2018-06-26 19:07 UTC
I would love to be able to swap out the current ugly, too-many-polygons RS3 type guards roaming around Varrock with the better suited old model which was similar to Falador guards.

Is it possible to add a feature to use the old guards just like we can change the game-frame?

**Comment by MESLewis** [comment] 2021-01-13 04:26
Depends on #7954

**Comment by Hydrox6** [comment] 2021-04-25 15:17
Duplicate of #3261

**Closed by Hydrox6** 2021-04-25 15:17 UTC
Labels: feature-request
