### ISSUE TITLE
Drop Text Not Working

### ISSUE THREAD

**Issue by IronPerish** [runelite/runelite#2695] opened 2018-05-13 23:35 UTC
I mentioned this before, but when an item is dropped on the ground and you've set your a minimum amount for text to show up, (for instance mine is 1,000 GP EX/HA) the item doesn't always appear in drop text. Like it will have a blue/purple/green or whatever text if you right click it on the ground but it wont just show up.
For instance, if I drop my ranger boots on the ground, it should show up in purple text, but it doesn't. If I right click it, I can clearly see a different colored text. And if I'm killing things that drop seeds or herbs, the expensive herbs wont show up. Like Ranar weed should pop up as blue because they're over 1k on GE, if I right click it, it is blue, but again, wont just show up on the floor. This worries me because I fear I'm going to miss a big drop one day if I go bossing or killing wyverns bla bla bla.
Please fix! 

(In the image I'm attaching, I have dropped ranger boots on the ground. They should have purple text above them, but they don't.) 
![image](https://user-images.githubusercontent.com/38304133/39972773-03344e8e-56d3-11e8-9192-33ed9f67f596.png)

And here's a picture to prove my settings are correct and should let me see drop text. Not all items have this issue, but some do. Most commonly seeds and herbs from what I'm noticing. And no, I do not have ranger boots or anything besides bones in the hidden items list. 
![image](https://user-images.githubusercontent.com/38304133/39972806-a62c2526-56d3-11e8-912c-85aa4f8fb8b2.png)

And here's an image proving some items do have drop text that does show up. Again, it's just certain items. But it freaks me out if I were to miss something big or rare.
![image](https://user-images.githubusercontent.com/38304133/39972823-dba292a8-56d3-11e8-88a2-f6c5bc6040b2.png)

**Comment by Infinitay** [comment] 2018-05-14 01:58
I've had the same problem, and I wish we would rework this.

The problem is that Ranger boots, although have a high GE price, their HA price is only 120 gp. Because in your settings you have it set to display items that are above 1,000 gp for both GE/HA, the Ranger boots won't show because it doesn't meet both conditions. That's why your mist battlestaff shows.

To fix this, just decrease your HA price.

**Comment by IronPerish** [comment] 2018-05-14 02:11
Oh. I see. Yeah, the text shows up if I turn my HA down. But I still think it should be reworked to as long as it meets one or both requirements, the text will show up.

**Comment by Hydrox6** [comment] 2018-05-14 02:14
Since the current system is Hide if less than, it's working 100% as intended. @deathbeam has a fix in #2287 but it's not been merged yet.

**Closed** 2018-06-11 23:04 UTC
Labels: feature-request
