### ISSUE TITLE
Kingdom of Miscellania Favor using wrong quest requirement

### ISSUE THREAD

**Issue by adrianped** [runelite/runelite#1980] opened 2018-04-26 16:27 UTC
Does not display Favor during and after quest complete of throne of miscellania even if standing in miscellania

**Comment by ShaunDreclin** [comment] 2018-04-26 16:31
Can confirm, having this issue myself. The overlay just never seems to show up

**Comment by TheSexyNerd** [comment] 2018-04-26 16:42
I've never seen the code for this plugin, but try asking an NPC what your favour is and then re-log, see if that works!

**Comment by adrianped** [comment] 2018-04-26 16:42
Did not make a difference.

**Comment by Infinitay** [comment] 2018-04-26 16:44
I think it may be a logic error under the `hasCompletedQuest` method so I'm trying to see if thats the case. Hopefully it's not an issue elsewhere because my membership conveniently ran out

**Comment by MagicfTail** [comment] 2018-04-26 16:47
Mine is working. Have the people having issues completed royal trouble?

**Comment by ShaunDreclin** [comment] 2018-04-26 16:48
Hm I didn't even consider that as a potential issue. I have completed royal trouble

**Comment by Infinitay** [comment] 2018-04-26 16:51
That shouldn't be an issue seeing as Throne of Misc is a pre-req for Royal Trouble

**Comment by adrianped** [comment] 2018-04-26 16:52
i have not completed royal trouble but code only asks to check for throne of misc

**Comment by ShaunDreclin** [comment] 2018-04-26 16:53
It's possible that the varbit/flag/whatever for throne of misc changes after completion of royal trouble

**Comment by Infinitay** [comment] 2018-04-26 16:54
Thats a very good point, I will look into it

**Comment by Lorenso0** [comment] 2018-06-09 09:10
Happening to me aswell - https://i.imgur.com/m3JOvtd.png, nothing shows up at all even after I cut a tree or ask a NPC what my favor is

**Comment by Gieliron** [comment] 2018-07-04 10:35
I can confirm that this is still a bug.  I've got both Misc quests completed and this plugin has never worked for me.  I've toggled it many times, spoken to NPC's to check approval etc.  Nothing.

**Comment by Nightfirecat** [comment] 2018-09-21 21:56
Fixed by #5212?

**Closed** 2018-10-08 07:00 UTC
Labels: bug
