### ISSUE TITLE
Slayer plugin decrements from XP Drop plugin's fake XP drop feature

### ISSUE THREAD

**Issue by Fjara-h** [runelite/runelite#14581] opened 2022-01-10 19:16 UTC
Each kill during a wilderness slayer task does not always properly decrement by 1. At least half of the time it more than 1, seemingly a random amount. Teleporting also decrements the remaining count by a random amount.

**To Reproduce**
1. Get a Wilderness Slayer task from Krystalia
2. Check the Slayer gem
3. Teleport to the location - optional but may be the issue
4. Kill slayer target

**Expected behavior**
Only on each kill should remaining slayer task counter decrement by 1, and teleports should not affect the kill remaining counter.

**Screenshots**
[In this set of images, I've checked my slayer gem, killed 1 ice warrior, ran away and did nothing else. The kill counter decremented by ~4 on initial kill and then every tick after by 1.](https://i.imgur.com/libgJYk.png)

That was the first time THAT particular thing happened. Normally, it would just go down by some number and wait for the next kill. 

**Environment (please complete the following information):**
 - OS: Win10 home 21H1 19043.1415
 - RuneLite version: 1.8.9
 - Launcher version: 2.1.7

**Additional context**
[client.log](https://github.com/runelite/runelite/files/7841327/client.log)

**Comment by robuhde** [comment] 2022-01-10 19:52
Here is a video of it: https://www.youtube.com/watch?v=8mZlsWZhNsU

**Comment by Nightfirecat** [comment] 2022-01-10 20:03
This is caused by the fake XP drop feature of the `XP Drop` plugin, and the slayer plugin picking up those fake drops, which was added in 409a4ab4e92a74946beb1cea1920f40de3ac2419.

We could add a clause to check whether slayer is `MAX_EXPERIENCE`, but that will still run into the (admittedly extreme) edge case of 200m players with the fake XP drop feature enabled having this same problem.

**Comment by Adam-** [comment] 2022-01-11 00:11
Do 0 xp fake xp drops work? We could make the fake xp drops use that maybe

**Comment by Adam-** [comment] 2023-02-26 02:44
fixed in 1f6ae893d732cf3a022fe6d9662cd2a42ff2b217

**Closed by Adam-** 2023-02-26 02:44 UTC
Labels: bug, regression
