### ISSUE TITLE
Mage Training Arena Telekinetic Puzzle Solver Broken

### ISSUE THREAD

**Issue by dappersnapper456** [runelite/runelite#9318] opened 2019-07-09 01:19 UTC
On most of the mazes the solver is telling me to stand in the wrong spot. Initially I just ended up wasting law runes but I have to solve the step myself. After I intervene the solver usually shows the correct squares to cast from afterwards. Below are multiple examples of the solver being broken and telling me to stand on the wrong side, as casting from there doesn't move the character at all.

Fun fact: screenshot 3 & 4 were on the same maze. As well as 5, 6 & 7 for another maze. So RIP this solver.

1.
![Screenshot 2019-07-09 at 02 05 15](https://user-images.githubusercontent.com/39419158/60852071-08985480-a1ee-11e9-8781-78c38a668208.png)

2.

![Screenshot 2019-07-09 at 02 07 59](https://user-images.githubusercontent.com/39419158/60852158-6462dd80-a1ee-11e9-8b8f-cf3bf09e54ef.png)

3.

![Screenshot 2019-07-09 at 02 13 03](https://user-images.githubusercontent.com/39419158/60852320-1ef2e000-a1ef-11e9-977c-d1f86651f254.png)

4.

![Screenshot 2019-07-09 at 02 13 56](https://user-images.githubusercontent.com/39419158/60852338-38942780-a1ef-11e9-843b-87be051eedca.png)

5.

![Screenshot 2019-07-09 at 02 17 35](https://user-images.githubusercontent.com/39419158/60852468-be17d780-a1ef-11e9-9aec-ec4c3bc789a9.png)

6. (I corrected the scenario in 5 but then it told me to stand on the same wrong tile)

![Screenshot 2019-07-09 at 02 18 13](https://user-images.githubusercontent.com/39419158/60852506-dee02d00-a1ef-11e9-8b57-d6a3f1576fe2.png)

7.

![Screenshot 2019-07-09 at 02 19 44](https://user-images.githubusercontent.com/39419158/60852557-118a2580-a1f0-11e9-8d3b-27fb2d54e66a.png)

**Comment by Adam-** [comment] 2019-07-10 00:56
duplicate of #3946

**Closed by Adam-** 2019-07-10 00:56 UTC
