### ISSUE TITLE
Idle Notifier does not consider depleted resources

### ISSUE THREAD

**Issue by Leo288** [runelite/runelite#13148] opened 2021-02-03 17:22 UTC
**Describe the bug**

If my character is mining at motherlode mine, and another character is on top, the resource depleting does not interrupt the mining animation, and thus at times the idle notifier can take a prolonged time to notify that the character is idle.

**To Reproduce**
1. Go to motherlode mine.
2. Go to a spot with someone else mining
3. Start mining the same resource
4. Wait for resource depletion -- Idle Notifier will not trigger as the character is left mining 'nothing'.

**Expected behavior**
Understandably, the idle notifier is going by the character's animation, but it'd be good if it could also factor in the interaction object having depleted. Otherwise, over time, considerable time is spent idle without a notification.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.3.38
 - Launcher version: 2.1.6

**Additional context**

**Comment by Hydrox6** [comment] 2021-02-03 17:27
Duplicate of #9052

**Closed by Hydrox6** 2021-02-03 17:27 UTC
