### ISSUE TITLE
Add Opacity to Inventory Tags

### ISSUE THREAD

**Issue by IdeaGuy17** [runelite/runelite#5407] opened 2018-09-09 12:31 UTC
Despite making the colors lighter, it's still makes many items far to too difficult to see. Which makes the feature practically useless, despite the flexibility in choosing colors. If we could have the ability to tweak the Opacity, I believe it would resolve this issue entirely.

Another alternative is to add the option to highlight the square the item is in, rather than an outline of the item itself. 
[Example](https://i.imgur.com/hzypQKI.png)

**Comment by deathbeam** [comment] 2018-09-09 12:33
Duplicate of #890

**Closed by deathbeam** 2018-09-09 12:33 UTC
