### ISSUE TITLE
compact the cooking fishing etc options into one option

### ISSUE THREAD

**Issue by McTerr** [runelite/runelite#9098] opened 2019-06-13 19:36 UTC

**Comment by Hydrox6** [comment] 2019-06-13 19:50
What is this requesting?

**Comment by McTerr** [comment] 2019-06-13 19:51
runelite has different tabs in to option menu for tracking cooking fishing etc, and i would like it to be compacted into a singular tab

**Comment by Hydrox6** [comment] 2019-06-13 19:53
Have you got an example, maybe with images?

**Comment by McTerr** [comment] 2019-06-13 19:56
![Capture](https://user-images.githubusercontent.com/34163782/59463313-feb94680-8e25-11e9-88bb-6fb8d59cfc43.PNG)
![Capture2](https://user-images.githubusercontent.com/34163782/59463321-04af2780-8e26-11e9-9a0c-053fc686a520.PNG)
![Capture1](https://user-images.githubusercontent.com/34163782/59463322-0547be00-8e26-11e9-8f25-dcca2a8003d6.PNG)

**Comment by McTerr** [comment] 2019-06-13 19:56
i would like it top be in one option

**Comment by Nightfirecat** [comment] 2019-06-13 19:58
Each of those plugins do separate things though, it would not make sense to collapse them into a single plugin.

**Comment by McTerr** [comment] 2019-06-13 19:59
they all track the different skills, anad i thought that it would be easier to reset them etc in one option, instead of searching for all of them seperately

**Comment by Hydrox6** [comment] 2019-06-13 20:01
They're partially the same in concept, but each plugin also does extra stuff that wouldn't make sense in another plugin. Being able to toggle each individually is also a better user experience.
If you really want to group them for quick resetting (though there's no reason to reset the configs of each plugin that often), click the star beside them to favourite that plugin

Otherwise, this looks like a duplicate of #2411

**Closed** 2019-06-13 20:02 UTC
Labels: needs-information
