### ISSUE TITLE
game closes random amount of time

### ISSUE THREAD

**Issue by thomasdelamp** [runelite/runelite#10852] opened 2020-02-22 20:23 UTC
**Describe the bug**
game closes after random amount of time. 

**To Reproduce**

**Environment **
windows 10
i5 9600k
rtx 2080 super
16gb ram
using the newest version of runelite

**Additional context**
[client.log](https://github.com/runelite/runelite/files/4239874/client.log)

**Comment by Nightfirecat** [comment] 2020-02-23 08:08
Duplicate of #9889. Unfortunately, we do not have any resolution for this bug currently.

**Closed by Nightfirecat** 2020-02-23 08:08 UTC
