### ISSUE TITLE
Clue scroll (hard) cryptic for General Hining

### ISSUE THREAD

**Issue by WarnABrotha** [runelite/runelite#9620] opened 2019-08-08 19:02 UTC
it isnt entirely necessary but the Cryptic clue for General Hining isn't in the client just thought id mention this in case anyone else hasn't yet.

(personally i don't mind opening a tab to search it up still but some people would probably bring this up if it happens to them)

**Comment by Alexsuperfly** [comment] 2019-08-08 19:04
duplicate of #9459

**Closed** 2019-08-08 19:07 UTC
Labels: duplicate, feature-request
