### ISSUE TITLE
Entity Hider region filter

### ISSUE THREAD

**Issue by Carsillas** [runelite/runelite#14883] opened 2022-04-21 23:10 UTC
**Is your feature request related to a problem? Please describe.**
I forget to turn on entity hider frequently after spending some time at wintertodt and thieving, it would be nice to specify regions that hide entities instead of a global toggle.

**Describe the solution you'd like**
Ideally there would be a way to specify a rectangle (or many) in which entities are hidden, but would be a great start to just have checkboxes for very crowded places (wintertodt, gotr, ardougne south bank, etc)

This would be an alternative to the global toggle currently available.

**Describe alternatives you've considered**
I've considered just remembering to disable it when I'm not thieving anymore, but I think that's slightly too much for my brain to handle.

**Additional context**

**Comment by Hydrox6** [comment] 2022-04-22 08:21
Duplicate of #6287

I would recommend marking the plugin as a favourite, and make it a habit to turn the plugin off after doing Todt or a thieve session. Can apply this to a lot more than just Entity Hider.

**Closed by Hydrox6** 2022-04-22 08:21 UTC
