### ISSUE TITLE
XP Drops: Allow canvas-centering of the vanilla XP drops

### ISSUE THREAD

**Issue by SoyChai** [runelite/runelite#1757] opened 2018-04-21 11:32 UTC
The game client has two different centering points: the `CENTER_CANVAS` which is the exact middle of the window (best for resizeable mode), and `CENTER_VIEWPORT` which is the exact middle of the game screen (best for fixed mode).

XP drops currently align to `CENTER_VIEWPORT` when set to Position: Middle in-game, and have none of the customization offered by the XP Globes plugin, so users are forced to use the slightly displaced `CENTER_VIEWPORT` even in resizeable mode to line up the two, otherwise this happens:

![image](https://user-images.githubusercontent.com/37604308/39083669-73548456-45ab-11e8-9431-49de1c5f86e2.png)

I think we can make this customizeable.

**Comment by YezziRS** [comment] 2018-05-19 17:11
Would be amazing if someone could make the xp drop follow the `CENTER_CANVAS` center point!

**Comment by deathbeam** [comment] 2018-10-19 12:35
Duplicate of #5075

**Closed by deathbeam** 2018-10-19 12:35 UTC
Labels: feature-request
