### ISSUE TITLE
The Increased Performance Mode tickbox in the Stretched Mode plugin no longer works. It remains blurry when turned off.

### ISSUE THREAD

**Issue by Tylemagne** [runelite/runelite#11242] opened 2020-04-10 18:43 UTC
**To Reproduce**
Steps to reproduce the behavior: Toggle it on and off. When turned off (unchecked), stretched viewports should go from blurry to sharp (no blending).

**Expected behavior**
It used to snap back to native appearance without blending/filtering.

**Screenshots**
It looks like Increased Performance Mode is still on.

**Environment (please complete the following information):**
 - OS: Windows 10, latest
 - RuneLite version: 1.6.10.1
 - Launcher version: 2.0.2

**Comment by Hydrox6** [comment] 2020-04-10 18:45
Duplicate of #10898

**Closed by Hydrox6** 2020-04-10 18:45 UTC
