### ISSUE TITLE
Allow modifier+click to make 'walk here' first option

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2145] opened 2018-04-29 19:59 UTC
IE shift/ctrl/alt+click always chooses 'Walk Here' instead of accidentally interacting with something on the ground.

Doing hunter recently and thought of this, since to efficiently move between traps you can't actually click on the traps themselves or you'll move slower/at them indirectly.

**Comment by deathbeam** [comment] 2018-09-21 08:32
Duplicate of #1412

**Closed by deathbeam** 2018-09-21 08:32 UTC
Labels: feature-request
