### ISSUE TITLE
(suggestion) Ground items option

### ISSUE THREAD

**Issue by yrrah2** [runelite/runelite#2859] opened 2018-05-18 04:37 UTC
Add an option to hide non stackable items.

 I am much more likely to pick up an item if it stacks / will pick up much cheaper items than usual should they stack.

**Comment by deathbeam** [comment] 2018-05-18 16:33
Duplicate of #2572

**Closed by deathbeam** 2018-05-18 16:33 UTC

**Comment by yrrah2** [comment] 2018-05-20 11:12
is this really similar at all?

**Comment by deathbeam** [comment] 2018-05-20 11:14
yeah, i guess, when you set it to 1 with that proposal
