### ISSUE TITLE
!lvl commands for tob hm and phosani's nm

### ISSUE THREAD

**Issue by Neal4D** [runelite/runelite#13931] opened 2021-07-23 13:27 UTC
It seems the client hasn't been updated to support either Hard Mode ToB or Phosani's Nightmare yet regarding !lvl commands. (shows rank AND kc)

**Comment by Hydrox6** [comment] 2021-07-23 13:31
Using !lvl in this way is kinda abusing a system not designed to do such a thing.

As such, Duplicate of #10897

**Closed by Hydrox6** 2021-07-23 13:31 UTC

**Comment by Neal4D** [comment] 2021-07-23 14:01
Interesting. I assumed it was intended to be this way and simply not updated yet as !lvl still works for other bosses on the current version of RuneLite. 

Thanks for your insight.
