### ISSUE TITLE
Incorrect fullscreen scaling on secondary displays

### ISSUE THREAD

**Issue by Norska** [runelite/runelite#9026] opened 2019-06-05 10:12 UTC
If a secondary monitor has different aspect ratio to main monitor full screening scaling does not work properly. Videos were taken with a 16:9 main display and 16:10 and 4:3 secondary displays
[Videos.zip](https://github.com/runelite/runelite/files/3256640/Videos.zip)

**Comment by Kamielvf** [comment] 2019-06-10 01:54
Duplicate of #5153

**Closed by Kamielvf** 2019-06-10 01:54 UTC
