### ISSUE TITLE
Doesn't start/ Stuck at 0%

### ISSUE THREAD

**Issue by mccomas** [runelite/runelite#3722] opened 2018-06-10 00:58 UTC
**Launcher log file:**
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:294)
	at net.runelite.launcher.Launcher.main(Launcher.java:146)

**Comment by Alexsuperfly** [comment] 2018-06-10 01:00
if your launcher is older than 2 weeks, redownload.  There was a change done to it and can cause that to happen.

**Comment by mccomas** [comment] 2018-06-10 01:02
I just downloaded and installed it today for the first time. Downloaded from runelite.net

**Comment by Alexsuperfly** [comment] 2018-06-10 01:05
perhaps try the all platforms version. the jar file

**Comment by mccomas** [comment] 2018-06-10 01:08
Same result sadly.

**Comment by supermxn** [comment] 2018-06-10 06:34
Try deleting your cache.

**Comment by deathbeam** [comment] 2018-06-10 06:55
Duplicate of https://github.com/runelite/launcher/issues/18

**Closed by deathbeam** 2018-06-10 06:55 UTC
