### ISSUE TITLE
Boost/Examine Re-color

### ISSUE THREAD

**Issue by Slyzuh** [runelite/runelite#3824] opened 2018-06-15 20:07 UTC
When I drag my boost icons to positions where I went them, they will move back up to top left corner everytime I close my client. Also the Blue text when you examine an item will not change. I set both examine and examine text to white and stays that deep hard to see blue color.

**Comment by deathbeam** [comment] 2018-06-15 20:40
Duplicate of #3799 . For the examine text, check chat recolor settings

**Closed by deathbeam** 2018-06-15 20:40 UTC
