### ISSUE TITLE
ESC to close the world map

### ISSUE THREAD

**Issue by rogierdevries** [runelite/runelite#2250] opened 2018-05-02 06:36 UTC
When opening the world map and continue walking. This world map isn't focused anymore and when ESC is pressed it doesn't close the world map. This is with ESC to close interface enabled.
Is this possible to implement a feature that closes the world map with ESC even if it isn't focused?

**Comment by Nightfirecat** [comment] 2018-05-02 20:50
That would likely require simulated clicks, which could flag the client as a bot client.

**Comment by jerwuqu** [comment] 2018-05-02 20:52
I'm not so sure since the world map should be mostly client-side. You might be correct though.

**Comment by deathbeam** [comment] 2018-07-08 00:49
Duplicate of #1067

**Closed by deathbeam** 2018-07-08 00:49 UTC
Labels: feature-request
