### ISSUE TITLE
Separate failed gauntlets and successful gauntlets in loot tracker

### ISSUE THREAD

**Issue by jcharles8246** [runelite/runelite#12017] opened 2020-06-28 13:12 UTC
If you fail a gauntlet attempt (die at boss), the loot falls into the same loot tracker table. While this is correct behaviour, it would be useful to instead provide an configuration to allow the failed attempts and successful attempts to go to separate loot tables.

Would be nice to show how many failed in a session etc and the separate value of failing vs succeeding.

**Comment by Hydrox6** [comment] 2021-07-05 21:47
Duplicate of #11279

**Closed by Hydrox6** 2021-07-05 21:47 UTC
Labels: feature-request
