### ISSUE TITLE
side tab for clue stash units

### ISSUE THREAD

**Issue by azzawoody** [runelite/runelite#11008] opened 2020-03-14 00:43 UTC
would be nice to be able to see all the stash units in a side tab

shows if stash unit has been built  
shows the items that go into that unit
green tick item in the the stash 
blue circle if items in the bank or inventory 
Red Cross if do not have item
Notification in chat if you pick up an item that is needed for stash units
option to show stash units location on map

**Comment by Nightfirecat** [comment] 2020-03-14 02:46
Duplicate of #1662

**Closed by Nightfirecat** 2020-03-14 02:46 UTC
Labels: duplicate
