### ISSUE TITLE
Flashing When using GPU Plug-in (Intel iGPU)

### ISSUE THREAD

**Issue by SallustRS** [runelite/runelite#6536] opened 2018-11-17 14:30 UTC
different parts of my screen are continually flashing bright white when GPU is turned on.

**Comment by cernodile** [comment] 2018-11-17 14:33
Would be nice if you could provide information about your system and GPU.

**Comment by deathbeam** [comment] 2018-11-19 15:16
This issue was fixed for me with https://github.com/runelite/runelite/commit/3286594d6b583aa261483a73ddf30823c102e923, so I guess we can close it, unless someone else wants to try it as well?

**Comment by deathbeam** [comment] 2018-11-19 19:52
As I cant reproduce this anymore, closing. Reopen if issue still occurs (on master branch, its not in release yet)

**Closed by deathbeam** 2018-11-19 19:52 UTC
Labels: bug, gpu

**Comment by Delphik** [comment] 2018-11-25 11:01
Im having the same issue using a GTX 1080 with the 415 drivers.

**Comment by deathbeam** [comment] 2018-11-25 12:05
So the issue is still present even on latest release @Delphik ?

**Comment by jorenham** [comment] 2018-11-30 10:18
I have the same on Ubuntu with GeForce GTX 1050 Ti on version 1.5.2.1.
Same behavior when opening with OpenJDK 8, Oracle Java 8, 9 10 and 11.

**Comment by Borancer** [comment] 2019-01-07 21:33
Still facing same problem. im using linux mint 19 64 bit. Might be too because im using 4k. Especially does that when i do something else and it gets worse when using 3 accs same time.
