### ISSUE TITLE
RuneLite HD mode

### ISSUE THREAD

**Issue by calvinkoch** [runelite/runelite#2489] opened 2018-05-08 19:38 UTC
So can you make a mode like Runescape HD

**Comment by Infinitay** [comment] 2018-05-08 19:48
See: https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

"OpenGL: Jagex is working on their own implementation (see #1165)"

**Comment by Gamer1120** [comment] 2018-05-09 11:15
Can be closed.

**Comment by deathbeam** [comment] 2018-05-09 11:16
Duplicate of #1165

**Closed by deathbeam** 2018-05-09 11:16 UTC
Labels: feature-request
