### ISSUE TITLE
Bank Tag Multi Item Selector

### ISSUE THREAD

**Issue by Kurama2121** [runelite/runelite#4986] opened 2018-08-18 05:19 UTC
While the current item tagger in the bank is useful it would be nice if you could set a tag and then click all of the items that you wish to apply to that tag, versus having to right click each item and apply the tag that way. 

Example: You type the tag in PK and then click each item you want to have said PK tag.

**Comment by deathbeam** [comment] 2018-08-18 11:40
Duplicate of #4426

**Closed by deathbeam** 2018-08-18 11:40 UTC
