### ISSUE TITLE
Ability to change overlay font to approved fonts.

### ISSUE THREAD

**Issue by terryit3** [runelite/runelite#13012] opened 2021-01-06 03:21 UTC
OSBuddy has added the ability to change your overlay font (to approved fonts only). Is there any chance RuneLite will be adding this soon? I've been using RL for years now, but I still miss the Lato Black font from OSBuddy . 

Thanks for everything you guys do!

**Comment by Hydrox6** [comment] 2021-01-06 03:25
Duplicate of #5546

**Closed by Hydrox6** 2021-01-06 03:25 UTC
