### ISSUE TITLE
Account types in Hiscores plugin

### ISSUE THREAD

**Issue by Sybke** [runelite/runelite#13173] opened 2021-02-07 18:59 UTC
Hi,

I'd like to see a small update happen with the Hiscore plugin. I think it's annoying that when you look someone up, you automatically end up in the general hiscores, regardless the account type. And you'd have to manually check whether someone is an (hardcore/ultimate) ironman.

What I propose is either of the following solutions:
1.  If you look up a certain type of iron man account, runelite would automatically swap panels to the most relevant account type's highscores
2.  The relevant account types are highlighted on the buttons for the different hiscores. Eg. When looking up a UIM, you'd still automatically get the normal highscores, but the grey and white helmet buttons would be highlighted to make clear what other highscores are available

Doesn't look like a large update, but I think it would a great QoL for the Hiscores plugin
Tyvm,
Sybke
![runelite hiscores](https://user-images.githubusercontent.com/78700527/107156469-d0836580-697e-11eb-9acc-79adbe48eafc.png)

**Comment by Hydrox6** [comment] 2021-02-07 19:03
Duplicate of #2403

**Closed by Hydrox6** 2021-02-07 19:03 UTC
