### ISSUE TITLE
Swap "Activate" and "Teleport to destination" on wildy obelisk

### ISSUE THREAD

**Issue by akhenat** [runelite/runelite#1644] opened 2018-04-17 22:35 UTC
Re-order option for ancient obelisk to show "tp to destination" as 1st option.

**Comment by winterdaze-rs** [comment] 2018-04-17 22:41
- xp/hr duplicate of #1041 
- overlay for prayers duplicate of #1537
- kc command is not going to be implemented, see [rejected features](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features)
- custom world map is duplicate of #1446
- untradables in bank value is duplicate of #1045 
- window size is duplicate of #1574
please check for duplicates before making suggestions :p

**Comment by akhenat** [comment] 2018-04-17 22:48
@winterdaze-rs Oh thanks for linking those suggestions and sorry for the duplicates, I am new to GitHub. Will keep that in mind next time.

**Comment by winterdaze-rs** [comment] 2018-04-17 22:49
I think the re-order for ancient obelisk is a unique suggestion though, so maybe change the title and description to specifically ask for that request

**Comment by Gamer1120** [comment] 2018-04-18 21:53
Can you provide me with a screenshot of the right-click menu please, as I don't have access to Ancient Obelisks. I might fix this tomorrow.

**Comment by akhenat** [comment] 2018-04-19 02:02
@Gamer1120 http://prntscr.com/j75v4d
Would be nice if the "teleport to destination" was set as the 1st option and maybe the "set destination" as shift click if possible. Also the obelisks on the wilderness have the same options as the one in POH.

**Comment by Nightfirecat** [comment] 2020-02-12 00:27
This is a niche feature that is best suited for the plugin hub, and is currently covered by the Menu swapper extented plugin there. See runelite/plugin-hub#42

**Closed by Nightfirecat** 2020-02-12 00:27 UTC
Labels: feature-request
