### ISSUE TITLE
Minimap icons displaying only in fixed mode

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#431] opened 2018-01-25 07:31 UTC
Currently, the minimap icons (f.e. for fishing spots) are displayed on minimap only in fixed mode, but when changed to resizable mode, they dissapear.

**Comment by Sethtroll** [comment] 2018-01-26 02:22
So, this "bug" is actually caused by the OverlayLayer.UNDER_WIDGETS making the dots appear under the minimap.

**Comment by Adam-** [comment] 2018-02-09 20:16
Fixed in 4b2e8cd1cdb0ef8c8aa4f0c8fadc03898870851d

**Closed by Adam-** 2018-02-09 20:16 UTC
Labels: bug
