### ISSUE TITLE
When i launch runelite it either does not appear or loads the plug ins and frame but not the game and it just loads a black screen.

### ISSUE THREAD

**Issue by djjotheman** [runelite/runelite#10083] opened 2019-10-17 06:05 UTC
[launcher.log](https://github.com/runelite/runelite/files/3737591/launcher.log)
![bandicam 2019-10-17 17-05-24-950](https://user-images.githubusercontent.com/56283882/66981751-5c291100-f100-11e9-9c79-cb6f77e5ea46.jpg)

Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by FatherLewy** [comment] 2019-10-17 07:37
I'm still getting this problem, tried all the troubleshoots but have been unable to fix it!

**Comment by deathbeam** [comment] 2019-10-17 08:54
Can you attach client.log too?

**Comment by djjotheman** [comment] 2019-10-17 11:03
[client.log](https://github.com/runelite/runelite/files/3738865/client.log)

**Comment by Alexsuperfly** [comment] 2019-10-17 13:36
if you normally have gpu enabled, see if this does anything <https://github.com/runelite/runelite/wiki/GPU-FAQ#client-is-freezing-after-enabling-gpu-plugin>

**Comment by djjotheman** [comment] 2019-10-17 20:10
gave it all a try did nothing to help

**Comment by djjotheman** [comment] 2019-10-20 10:48
can someone please look into this with the picture put before i either get that or the game doesn't appear at all and it i hover my mouse over were its meant to appear it just shows a loading symbol

**Comment by deathbeam** [comment] 2019-10-21 08:41
You can also try to disable HW accel: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by djjotheman** [comment] 2019-10-22 00:48
yea that was one of the first things i tried

**Comment by djjotheman** [comment] 2019-10-22 01:05
not its loads but wont actually launch anymore

**Comment by Alexsuperfly** [comment] 2019-11-14 21:12
duplicate of #9993 

solution: turn off GPU plugin

**Closed** 2020-02-18 04:08 UTC
Labels: duplicate
