### ISSUE TITLE
[Sidepanel] Filter options/Widget auto-repositioning

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#13579] opened 2021-05-08 11:29 UTC
Filter Options based on:

_a) Show Favorites only
b) Show Enabled plugins only.
c) Show Disabled plugins only.
d) Show Default plugins only.
e) Show only plugins that were downloaded from the Plugin Hub._

**Plugin Hub:**
_a) Show downloaded plugins only.
b) Show non-downloaded plugins only._

**Widgets:**
Currently, the widgets don't follow the Side Panel.
_I would like to have an option, so the widgets would follow the game window's right frame, when the sidebar is (partially or completely) hidden._

**Comment by Hydrox6** [comment] 2021-05-08 11:34
Don't make two completely different suggestions in an issue
Duplicate of #11342
Duplicate of #3784

**Closed by Hydrox6** 2021-05-08 11:34 UTC
