### ISSUE TITLE
Highlight the Dense Runestones at Zeah just like the agility shortcuts

### ISSUE THREAD

**Issue by day2406** [runelite/runelite#4503] opened 2018-07-26 03:34 UTC
**_This is not a duplicate of https://github.com/runelite/runelite/issues/2164. That is asking for a mining icon, just like it was commented this should go under the Runecrafting tab NOT Mining, and it needs to be highlighted not have a tiny pickaxe on it. It's too large to have a small pickaxe on it._**

Kind of a lazy request but I'm hoping it's easy to do, but is there any chance that the Dense Runestones can be highlighted the same way agility shortcuts are? And obviously unhighlighted when they're empty?

Because the color difference is very slim and it's a bit hard to see when its on the right side of your screen if its gone empty of not. If it switchd from green highlighted to not highlighted it would be much easier to notice.

Is your feature request related to a problem? Please describe.
It's difficult to tell the difference between Dense and Empty runestones because of a minor color difference.

Describe the solution you'd like
Dense runestones are highlighted just like Agility shortcuts or RC Rifts. This would obviously be toggled in the Runecrafting tab.

Describe alternatives you've considered
Not really sure

Additional context
Thanks

**Comment by Abextm** [comment] 2018-07-26 03:37
It is close enough to be a duplicate of #2164.
If you would like to comment on this you can do it on the closed issue, without opening a new one.

**Closed by Abextm** 2018-07-26 03:37 UTC
Labels: duplicate
