### ISSUE TITLE
Random event notifier

### ISSUE THREAD

**Issue by robinwithes** [runelite/runelite#6234] opened 2018-10-28 15:07 UTC
I'm looking for a Dr Jekyll random event on my iron-man currently. I am afk-fishing in the meantime and i'm scared i wont see it if he pops up since I'll be afk.

A way to send me a notification when a specific random event spawns for me would be nice.

**Comment by deathbeam** [comment] 2018-10-28 15:08
Duplicate of #1634

**Closed by deathbeam** 2018-10-28 15:08 UTC
