### ISSUE TITLE
[BUG] Current Experience goes outside of box when hovering over exp orb

### ISSUE THREAD

**Issue by robbo1996** [runelite/runelite#2981] opened 2018-05-19 22:34 UTC

**Comment by robbo1996** [comment] 2018-05-19 22:35
![image](https://user-images.githubusercontent.com/24456147/40273689-49b7b92e-5bbd-11e8-9c5d-193f219aac96.png)

**Comment by deathbeam** [comment] 2018-05-19 23:09
Duplicate of some issue.

**Closed by deathbeam** 2018-05-19 23:09 UTC
