### ISSUE TITLE
Mining/not mining overlay when doing zeah runecrafting (mining essence blocks)

### ISSUE THREAD

**Issue by w355osrs** [runelite/runelite#10471] opened 2019-12-18 20:46 UTC
provide the currently mining/not mining overlay when mining essence block so its easier to afk when runecrafting bloods and souls. This helps because sometimes you will stop mining the essence block and not be able to tell if you are not mining because you're so zoomed out.

**Comment by Nightfirecat** [comment] 2019-12-18 20:48
Duplicate of #7976

**Closed by Nightfirecat** 2019-12-18 20:48 UTC
