### ISSUE TITLE
Odd shadowing

### ISSUE THREAD

**Issue by TheLimpDaddy** [runelite/runelite#13512] opened 2021-04-21 23:58 UTC
Whenever I am in the toolbar area of Runelite it is almost as if the whole toolbar hovers itself over and over and shadows itself. Makes it super hard to use. I have the windows 64 bit version. I’ve tried redownloading and installing multiple times.

**Comment by Hydrox6** [comment] 2021-04-22 07:47
Duplicate of #11727

**Closed by Hydrox6** 2021-04-22 07:47 UTC
