### ISSUE TITLE
Save chat logs locally as txt files

### ISSUE THREAD

**Issue by andaiakudj** [runelite/runelite#8386] opened 2019-04-03 00:50 UTC
Hi everybody! This is a request for Runelite to save chatlogs of public and private chat on your machine as .TXT files, for the corresponding date. Maybe separate public and private if possible.

Logging the chat locally would be really nice to have so you can look back at what was said at a earlier time. In case you forgot something important you were told by somebody in-game, or you potentially missed something that was said.

Thank you for reading, and thank you for your work on RuneLite!

**Comment by Hydrox6** [comment] 2019-04-03 01:18
Duplicate of #8119

**Comment by Atrolantra** [comment] 2019-04-03 01:42
The Chat History plugin preserves chat history in-client across world switches and log ins/outs but doesn't save history to file. Could likely be enhanced to add functionality to save date/timestamped messages to text files based on the type of message (friends, clanchat, mod, game, engine, public, etc).

**Closed** 2019-04-03 02:58 UTC
Labels: duplicate
