### ISSUE TITLE
xp drop, align middle is not lined up with globe

### ISSUE THREAD

**Issue by kyleboyle** [runelite/runelite#4081] opened 2018-06-29 13:54 UTC
``` 
> java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```
 Operating System: win10

![capture](https://user-images.githubusercontent.com/6877108/42095937-6b24af62-7b8a-11e8-9a5e-b0017a6c8937.PNG)

![capture2](https://user-images.githubusercontent.com/6877108/42095955-78b088f4-7b8a-11e8-9256-28707e947728.PNG)

**Comment by deathbeam** [comment] 2018-06-29 14:03
Duplicate of #1857

**Closed by deathbeam** 2018-06-29 14:03 UTC

**Comment by Nightfirecat** [comment] 2018-06-29 17:36
Should be marked as duplicate of #1757

**Comment by deathbeam** [comment] 2018-06-29 17:37
OOps, typos again
