### ISSUE TITLE
Enable which NPC's to hide in Entity Hider?

### ISSUE THREAD

**Issue by Nitro-m** [runelite/runelite#13074] opened 2021-01-17 03:00 UTC
**Is your feature request related to a problem? Please describe.**
When doing some runecrafting at ZMI or some other activities there are some npcs that get in front of the things you need to click, making this an annoying situation. Can't disable all npcs because i need the banking one.

**Describe the solution you'd like**
An expansion to the entity hider plugin where you would be able to choose which NPC's to hide when typing their names.

**Comment by Nightfirecat** [comment] 2021-01-17 03:03
Duplicate of #6854

**Closed by Nightfirecat** 2021-01-17 03:03 UTC
Labels: duplicate
