### ISSUE TITLE
Plugin to see ressource used and their cost to see the exact profit you made

### ISSUE THREAD

**Issue by samiboy1511** [runelite/runelite#8061] opened 2019-03-01 22:00 UTC
So the idea is basically a loot tracker but the other way, all the potion you drink, all the food you eat would be display and that way you could see exactly how much you made during a boss, or a task without having to calculate it all.

And if it possible mayble implement it with the loot tracker so you could see directly the profit, if it not possible just another tab and we calculate directly profit - lost. It would be legen .... wait for it DARY !!

**Comment by Hydrox6** [comment] 2019-03-01 22:03
Duplicate of #6700

**Closed** 2019-03-01 22:13 UTC
