### ISSUE TITLE
Highlight Style dropdown for Slayer plugin

### ISSUE THREAD

**Issue by Jbluehdorn** [runelite/runelite#11014] opened 2020-03-14 20:33 UTC
Currently, the slayer plugin allows you to highlight your current target but only does it with the "hull" style highlight which highlights the entire mesh around the target. This can be visually obtrusive and takes away from some of the visual components of the game.

I would request a Highlight Style dropdown much like the one found in the NPC Indicators plugin which allows the user to select between Tile, South West Tile, and Hull.

**Comment by Nightfirecat** [comment] 2020-03-14 20:39
Duplicate of #4606

**Closed by Nightfirecat** 2020-03-14 20:39 UTC
Labels: duplicate
