### ISSUE TITLE
Don't close clue scroll helper box on load screens/etc

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2912] opened 2018-05-19 02:17 UTC
Doing an elite clue. Challenge scroll replaces the clue scroll, which makes the helper box (and the answer to the challenge) disappear. Very annoying. Helper box also disappears during load screens like a glider, forcing you to reopen the clue.

Keep the helper box open as long as the clue is in your inventory. If replaced by a challenge scroll, don't update the box until the challenge is completed.

**Comment by Nightfirecat** [comment] 2018-09-21 23:40
Duplicate of #2043 and/or #2740

**Closed** 2018-11-26 13:51 UTC
Labels: bug, clues
