### ISSUE TITLE
Alt to move map, xp orb and other details issue

### ISSUE THREAD

**Issue by Arastaiel** [runelite/runelite#4939] opened 2018-08-16 14:03 UTC
**Is your feature request related to a problem? Please describe.**
I really get quite frustrated when accidentally press my Alt key and move around items on my screen like XP orbs and map

**Describe the solution you'd like**
I would like there to be an option to turn on and off the Alt to move option.

**Comment by whitehooder** [comment] 2018-08-16 14:05
You can reset the position with alt + right click, though it is still a reasonable request.

**Comment by deathbeam** [comment] 2018-08-16 14:09
Duplicate of #3826

**Closed by deathbeam** 2018-08-16 14:09 UTC
