### ISSUE TITLE
Bandos boss timer off

### ISSUE THREAD

**Issue by vikke1234** [runelite/runelite#869] opened 2018-03-06 20:05 UTC
it's off by around 7 seconds, I don't know if it's the same for the other bosses

**Comment by Adam-** [comment] 2018-03-06 20:07
Duplicate of #439

**Closed by Adam-** 2018-03-06 20:07 UTC

**Comment by SomeoneWithAnInternetConnection** [comment] 2018-03-06 20:08
7 seconds seems like a lot for this to just be a ticks vs timers issue
