### ISSUE TITLE
Highlight Others - Player Indicator Improvements

### ISSUE THREAD

**Issue by lineyosrs** [runelite/runelite#12969] opened 2020-12-23 18:21 UTC
**Is your feature request related to a problem? Please describe.**
The highlight others option in the player indicator plugin is especially useful when in the wilderness. I normally toggle it between off/on depending if I'm doing wilderness content or not. 

**Describe the solution you'd like**
Add a toggle that automatically allows highlight others to activate within the wilderness (if you have the highlight others option selected). That way, people who only use it in the wilderness wouldn't have to switch it off and on! 
Perhaps adding a toggle for it to activate only in PVP worlds could be useful for other players as well. 

**Describe alternatives you've considered**
I could just stop being lazy and manually turn it off and on.

**Additional context**
:)

**Comment by Alexsuperfly** [comment] 2020-12-23 18:28
duplicate of #3684

**Closed** 2020-12-23 18:50 UTC
