### ISSUE TITLE
MTA plugin: Telekinetic solver fails to update 

### ISSUE THREAD

**Issue by abextm** [runelite/runelite#3946] opened 2018-06-22 08:07 UTC
On commit 26fbf78399e328b73fee72d6a1d7f1841e528b50

Sometimes the telekinetic solver fails to update after the room has changed state. I don't know exactly what causes it, but it happens every 10 rooms on average.

![2018-06-22_02-06-11](https://user-images.githubusercontent.com/12366911/41765279-da077a4c-75c0-11e8-8b3d-e754a3e21876.png)

**Comment by Jasper-ketelaar** [comment] 2018-06-22 10:09
Should also be fixed now in #3947

**Comment by Adam-** [comment] 2018-06-25 14:13
Do you know why #3947 fixes this or what the issue is?

**Comment by troypressley1** [comment] 2018-10-11 04:03
I wonder if this'll ever be able to be fixed

**Comment by Spedwards** [comment] 2018-12-31 07:56
Doesn't look like this is getting fixed anytime soon. Shame.

**Comment by MalakaJones** [comment] 2019-02-25 01:49
Still an issue.

**Comment by Adam-** [comment] 2019-07-12 00:33
Sorry for the wait. This is now fixed.

**Closed** 2019-07-12 00:32 UTC
Labels: bug
