### ISSUE TITLE
Port Piscarilius stealing artifacts plugin

### ISSUE THREAD

**Issue by ersthgf** [runelite/runelite#11942] opened 2020-06-20 08:01 UTC
When doing this training method i occasionally would forget which house i would need to steal from meaning i would have to go back to captain Khaled to know. This lowered xp per hour and was generally pretty annoying when it happened. A plugin which says which house you need to steal from would fix this issue.
Here's a link to a video that Woox made which explains this training method for those who are not aware or if you don't wanna click the link, the video's name is "210k Thieving & 310k Firemaking xp/h - Stealing Booty From Piscarilius Houses"
https://www.youtube.com/watch?v=PNKQbuQsiLE

**Comment by loldudester** [comment] 2020-06-20 08:05
Duplicate of #10348

**Closed** 2020-06-20 08:20 UTC
