### ISSUE TITLE
Checkbox Based Custom Task List

### ISSUE THREAD

**Issue by jlduhaime** [runelite/runelite#13502] opened 2021-04-20 12:04 UTC
**Is your feature request related to a problem? Please describe.**
I love the note plugin where i can list things I'm working on or goals I have however it's tedious to edit/ remove/ easily see completed items i have on the note list.

**Describe the solution you'd like**
It would be great to have a check-box list that I could create and click to check things off. For example, I add an item for 25 GWD kills. Once complete I click the box and it strikethroughs the line (or some other visual display of completion). Expansion on this plugin could include repeatable items for daily, weekly, monthly / etc based goals. For example, a personal goal to hunt 1000 black chins a week could auto un-check every week. Another expansion could be to import data from external sources. The first example that comes to mind is OzirisRS's ironman guide which lends itself perfectly to a check-box based to-do list.

**Describe alternatives you've considered**
Currently I use Visual Studio Code's todo-list plugin on my second monitor to track items in game. In the past I've used notepad but it has the same limitations as the RuneLite notes plugin.

**Additional context**
This plugin would go a long way to help set clear enumerated goals for an account where the user could see a visual sign of progression by the number of thing checked off.

**Comment by Nightfirecat** [comment] 2021-08-20 01:32
Duplicate of #3507

**Closed by Nightfirecat** 2021-08-20 01:32 UTC
Labels: duplicate
