### ISSUE TITLE
Add a !kc command for barbarian assault elite gambles.

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#8443] opened 2019-04-08 01:51 UTC
It has the kc in game somewhere, would be nice to flex.

**Comment by Hydrox6** [comment] 2019-04-08 01:52
Duplicate of #7691

**Comment by JeljoGb** [comment] 2019-04-08 01:52
Ah sorry, couldn't search on the mobile page

**Closed** 2019-04-11 23:08 UTC
Labels: duplicate
