### ISSUE TITLE
Farming timer plugin panel

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1145] opened 2018-03-27 10:29 UTC
Timer for Farming. Preferably a side plugin panel so it doesnt clutter main screen so much

**Comment by NotFoxtrot** [comment] 2018-03-27 10:35
Duplicate of #511

**Comment by Stickaplex** [comment] 2018-03-27 10:40
Didn't see it when I searched for it. Mb

**Closed** 2018-03-27 10:47 UTC
