### ISSUE TITLE
When training combat skills instead of showing "actions left" to level show "kills left" to level

### ISSUE THREAD

**Issue by Sheepio** [runelite/runelite#2796] opened 2018-05-16 14:40 UTC
Because the "actions left" is really inaccurate while training combat skills (str, atk, def, ranged,magic),since it goes up and down depending on what you hit
and maybe you can have a toggle for magic if you are splashing since you get a fixed amount of exp and it would be accurate in this case

**Comment by drnfc** [comment] 2018-05-16 16:52
Only OSB does this, it is not a bug.

**Comment by deathbeam** [comment] 2018-05-17 17:58
Duplicate of #1594

**Closed by deathbeam** 2018-05-17 17:58 UTC
