### ISSUE TITLE
Having issues with COX health bar

### ISSUE THREAD

**Issue by honkmydonk** [runelite/runelite#12852] opened 2020-11-27 02:54 UTC
For whatever reason I am unable to have my opponents health bar in COX show the actual HP and not the percentage. I have the setting set in opponent information set to hitpoints as well. I don't understand why it doesnt show that

**Comment by Hydrox6** [comment] 2020-11-27 09:06
How the `Opponent Info` bar works is it pulls the health value essentially from the wiki (with some caching on our end). The problem with bosses in CoX is that they don't have one health value; their health scales depending on the team size (and maybe some other factors like average level, I forget). As a result, it's not really possible for the plugin as it works now to properly show it.

Jagex themselves have added an official health bar overlay (as seen on Zuk, Hunllef, Zalcano, etc) to the Chambers for all bosses, so you could use that instead; it can be found in the Advanced section of the vanilla settings menu.

In theory, we could have code to pull the health from the vanilla bar and use it in `Opponent Info`, though I'm not sure how well that would work.

**Comment by MESLewis** [comment] 2021-01-13 03:22
Duplicate of #12137

**Closed by MESLewis** 2021-01-13 03:22 UTC
