### ISSUE TITLE
xp globes stop working with the xp tracker plugin turned off.

### ISSUE THREAD

**Issue by polakweg** [runelite/runelite#6276] opened 2018-10-31 13:39 UTC
recently the xp globes have started to display the wrong information. 

I have found out that that they behave correctly with the xp tracker plugin turned on, and it has registered a couple of actions. 

But whenever I turn the xp tracker plugin back off again they start to give the same wrong information as before the xp tracker was turned on.

https://imgur.com/gallery/DOQrhNq - screenshots

while the large percentage number doesn't in- or decrease the total xp does seem to track it correctly.

**Comment by deathbeam** [comment] 2018-10-31 13:40
Duplicate of #6262

**Closed by deathbeam** 2018-10-31 13:40 UTC
