### ISSUE TITLE
Using 'WASD' for controlling the camera.

### ISSUE THREAD

**Issue by Mamboosun** [runelite/runelite#3528] opened 2018-05-31 15:51 UTC
I just wondered if there was anyone who could write a plugin that made it available for the 'WASD'  keys to be used to control the camera as opposed to the arrow keys. (i'm a lefty so would be very helpful)

**Comment by deathbeam** [comment] 2018-05-31 15:54
Duplicate of #1008

**Closed by deathbeam** 2018-05-31 15:54 UTC
