### ISSUE TITLE
Is an auto-ignore for the gambling bots available?

### ISSUE THREAD

**Issue by Schmitzky** [runelite/runelite#8120] opened 2019-03-05 22:22 UTC
**Is your feature request related to a problem? Please describe.**
Due to sudden influx of spamming gambling bots, I'm wondering if someone can develop something to auto-mute them? 

Ignoring them yourself is becoming a daily occurrence as they are making tons of new accounts.

**Describe the solution you'd like**
I'm not sure if there is a common thing that can be detected amongst all the accounts that could be a trigger to mute them. 

Maybe if the message already exists in the chat log within a period of time, suppress multiple instances?

**Describe alternatives you've considered**
Manually adding to ignore is the only alternative.

**Comment by Nightfirecat** [comment] 2019-03-05 22:33
Duplicate of #1798

**Closed** 2019-03-05 22:34 UTC
