### ISSUE TITLE
Hunter Plugin: Red salamander traps , two spots not registering when caught.

### ISSUE THREAD

**Issue by Whitessss** [runelite/runelite#1502] opened 2018-04-14 01:18 UTC
Hi there,

I was training some hunter and noticed that two spots are not registering when the salamander is caught. It registers when the trap fails and it is set up. It just stays as pending / marks the trap as still placed waiting when it catches something.

Notice the the one at the top of the picture is already caught and still shows pending:
https://i.imgur.com/4t6qNEv.png

Notice in this screenshot right after, the one on the left catches and stays yellow:
https://i.imgur.com/pqV3yT8.png
This is the only two spots ive noticed.

**Comment by Adam-** [comment] 2018-04-14 02:13
Duplicate of #1169

**Closed by Adam-** 2018-04-14 02:13 UTC
