### ISSUE TITLE
Mouse lagging/stuttering when hovered or used in Runelite if Windows HDR setting is on

### ISSUE THREAD

**Issue by Mollium** [runelite/runelite#12247] opened 2020-07-29 10:02 UTC
When I enable Windows 10 HDR settings and want to use Runelite, my mouse drastically loses smoothness if hovered over or is used in Runelite. Even with hardware acceleration disabled, the mouse cursor won't get to its original refresh rate (160Hz on my monitor).

**Steps to reproduce are simple:**

1. Go to Windows 10 settings and turn on Windows HDR color settings on a high refresh rate and HDR-enabled screen
2. Open Runelite (hardware acceleration disabled or not, problem persists in both instances)
3. Try to play and notice that the mouse's refresh rate is drastically lower than before
4. Close the game and turn off Windows HDR color settings
5. Restart the game and notice that the refresh rate of the mouse is back to its original smoothness

I'm on the latest Windows 10 Pro update with a GTX 1080TI running an ultrawide LG 38GN950 at 3840x1600.
The screen has HDR600 capabilities and every other app but Runelite works.

**Comment by Nightfirecat** [comment] 2020-07-30 03:02
Do you have the GPU plugin enabled? Does this happen with the vanilla client, or any other program on your computer?

**Comment by Mollium** [comment] 2020-07-30 14:06
> 
> 
> Do you have the GPU plugin enabled? Does this happen with the vanilla client, or any other program on your computer?

The GPU plugin is enabled. When I disable it, the problem disappears. Is there a known bug between the GPU plugin and HDR on/off through Windows 10?

**Comment by Nightfirecat** [comment] 2022-07-10 04:34
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:34 UTC
Labels: needs-information
