### ISSUE TITLE
Feature Request - Puzzle Solver Numbers

### ISSUE THREAD

**Issue by Sopison** [runelite/runelite#9101] opened 2019-06-14 05:22 UTC
I would like the puzzle box solver to have it's own option to list the puzzle blocks 1 - 25 so we can solve it ourselves without needed the solver.

People might find clue scrolls more fun being able to solve it with just the numbers listed instead of trying to piece together images that don't make sense to begin with. 

It would look like the normal picture but just with small numbers at the top left of each block.

1   2   3   4   5
6   7   8   9   10
11 12 13 14 15
16 17 18 19 20 
21 22 23 24 25

**Comment by Nightfirecat** [comment] 2019-06-14 06:01
Duplicate of #2970

**Closed by Nightfirecat** 2019-06-14 06:01 UTC
