### ISSUE TITLE
getting hackeD????!

### ISSUE THREAD

**Issue by revenanttax** [runelite/runelite#5114] opened 2018-08-25 10:15 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by deathbeam** [comment] 2018-08-25 10:18
Duplicate of #5115

**Closed by deathbeam** 2018-08-25 10:18 UTC
