### ISSUE TITLE
Enabling ground items plugin does not work until client restart

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#5034] opened 2018-08-21 01:12 UTC
Only happening on latest build (1.4.13), not on release version.

**Comment by Adam-** [comment] 2018-08-21 01:17
Can you please bisect this and find the breaking commit?

**Comment by ShaunDreclin** [comment] 2018-08-21 02:15
Just tried, the oldest commit it'll let me compile still has the issue.

**Comment by Nightfirecat** [comment] 2018-08-21 04:51
Hm... Does this behavior also exhibit itself if you have ground items enabled on client start, then disable it and enable it again, or only if it is disabled upon client start?

**Comment by ShaunDreclin** [comment] 2018-08-21 04:54
I tried starting with it disabled and enabling it, and starting with it enabled, disabling it, and enabling it again. Same issue both times

**Comment by ToMuchMayo** [comment] 2018-08-23 21:09
I'm having issues with the ground items plugin as well. On one my osrs accounts the plugin works but on the other account it doesn't work. Completely confused as they both on same setups.

**Comment by raiyni** [comment] 2018-10-02 15:21
Is this still an issue? I can't reproduce it. 

Share your settings if it is still an issue.

**Comment by Nightfirecat** [comment] 2020-07-17 04:59
Since this issue is very old and without any updates, I am closing it.

**Closed by Nightfirecat** 2020-07-17 04:59 UTC
Labels: bug
