### ISSUE TITLE
Music will not play, then all sound will cut out

### ISSUE THREAD

**Issue by ase1590** [runelite/runelite#6345] opened 2018-11-04 18:17 UTC
System:
Arch Linux, using java-10-openjdk
AMD RX 480
RuneLite 1.4.24
Oldschool revision: Rev 176
Launcher: 1.6.1

I have the following audio setup:
1 pair of headphones that plug into the stereo jack (this is the default device)
1 pair of speakers that plug in to a simple usb to audio jack device

While using the headphones, the client will fail to play music at all, and will only play game sounds, such as casting sounds or attacking sounds. It may randomly cut out after a few minutes. 

If I attempt to switch my audio device to my usb speakers, the game sounds will cut out after a few seconds, making the game totally silent. 

Application.log: http://ix.io/1qXA

Launcher log: http://ix.io/1qXB

Edit: Low Detail mode is not on either. temporarily moving the .runelite directory and letting it re-build did not affect the bug's behavior. 

Edit2: It's possible this is a oldschool client issue, as OSBuddy exhibited having no sound.

**Comment by deathbeam** [comment] 2018-11-04 18:52
Duplicate of #4891

**Closed by deathbeam** 2018-11-04 18:52 UTC
