### ISSUE TITLE
Bug with the ground item plugin making the alt key get "stuck"

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1042] opened 2018-03-21 06:35 UTC
~~If you're holding alt to show the options on ground items and the client loses focus, the alt key gets "stuck" down and makes you unable to left click on anything until you tap alt again.~~

~~Disabling the ground items plugin resolves the issue, so it's somewhere in there.~~

**Comment by sethtroll** [comment] 2018-03-21 06:43
Duplicate of #1015 and a fix was merged a little bit ago that fixes this.

**Comment by Adam-** [comment] 2018-03-21 11:37
Duplicate of #1015

**Closed by Adam-** 2018-03-21 11:37 UTC
