### ISSUE TITLE
Herb Sack value

### ISSUE THREAD

**Issue by michaelcubel** [runelite/runelite#8236] opened 2019-03-16 19:23 UTC
**Is your feature request related to a problem? Please describe.**
Currently no way to tell value of herbs in sack.

**Describe the solution you'd like**
Upon checking herbs or examine, show total value and/or total value for each herb type.

**Describe alternatives you've considered**
When you fill the sack, runelite could also display the value of added herbs.

**Comment by Nightfirecat** [comment] 2019-03-16 19:44
Duplicate of  #4573

**Comment by michaelcubel** [comment] 2019-03-16 19:47
> Duplicate of #4573

Wouldn't be a duplicate if it was already a feature. Can you explain why it has not been implemented yet?

**Comment by Nightfirecat** [comment] 2019-03-16 19:53
I'm not saying this is already a feature in the client. I'm saying that issue 4573 is a request for this same feature which is already open; it doesn't help for us to track duplicate feature requests.

**Comment by michaelcubel** [comment] 2019-03-16 20:02
> I'm not saying this is already a feature in the client. I'm saying that issue 4573 is a request for this same feature which is already open; it doesn't help for us to track duplicate feature requests.

You misunderstand. That request is almost a year old. Why is the feature not available on runelite yet?

**Comment by psikoi** [comment] 2019-03-16 20:11
Because no one thought it was important enough to be developed, are you under the impression that the developers owe you anything?

**Comment by michaelcubel** [comment] 2019-03-16 20:17
> Because no one thought it was important enough to be developed, are you under the impression that the developers owe you anything?

They don't owe anyone anything. I'm trying to understand why they like receiving duplicate requests. I'm simply asking for an explaination. Don't get offended

**Comment by TheStonedTurtle** [comment] 2019-03-16 20:30
Having multiple issues for the same feature requests just makes it harder to keep stuff organized. There are hundreds of issues and pull requests opened every month and everyone who works on the client is volunteering their time.

> Can you explain why it has not been implemented yet?

PRs can be stuck in limbo for a few reasons.
* Got lost in the shuffle
* Could be implemented better
* Bad coding standards
* Feature was decided against

If PR hasn't been reviewed yet and it's been a few weeks the author may want to rebase it and mention it, nicely, in the discord.

**Closed** 2019-03-17 17:48 UTC
