### ISSUE TITLE
Runelite Client - Green lines on screen

### ISSUE THREAD

**Issue by KidtryingtoplayRS** [runelite/runelite#12053] opened 2020-07-02 06:09 UTC
Bug: Not sure if this has to do with my graphics card but I had no problems earlier today and now it seems I can't get rid of the of these green lines on the Runelite client. These don't appear on the regular Old School client so it makes me believe it's just Runelite. 

See attached screenshot. https://imgur.com/3IMk5Tb
 
 - OS: Windows 10 64bit 
 - RuneLite version: latest version (I uninstalled and reinstalled and the issue persists)

![Runelite Image - Green lines 07-01-2020 ](https://user-images.githubusercontent.com/67727978/86322176-5ff9b680-bbef-11ea-9022-957004928582.png)

**Comment by Nightfirecat** [comment] 2020-07-02 06:18
Duplicate of #11795

**Closed by Nightfirecat** 2020-07-02 06:18 UTC
Labels: duplicate
