### ISSUE TITLE
Herbiboar improvements

### ISSUE THREAD

**Issue by schneky** [runelite/runelite#10438] opened 2019-12-14 19:45 UTC
**Why does the Herbiboar plugin need to be changed?**
When tracking herbiboars, you follow the footprints and search an object. It is supposedly 50/50 which object will reveal the next set of footprints. However, there are 11 situations where you can know for certain which object is the correct one to search. 

**Proposed change**
If one of the 11 situations presents itself, have runelite only highlight the object that is guaranteed to be the correct one. 

**"SMH, Why is this even worth suggesting?"**
Its not super important, but I think it could make for a pretty decent side project for anyone. I personally am not all that familiar with runelite's code, so i am not 100% on how the client detects what you just did, but i believe if a script was added to wait for certain tiles to be highlighted, then tests to see where the footprints originated from, if a path meets the conditions to be a "guaranteed path," only highlight the correct object to be searched.

**Additional context**
For example, if you begin tracking by inspecting the rock just east of the Mushroom Meadow Mushtree, you always know what to click on to continue. If the tracks lead northwest past the birdhouse hot-spot it will always be the mushroom, if the tracks lead directly east it will always be the muddy patch, and if they lead south it will be the smelly mushroom. Guaranteed paths are as follows...
![8325ef793d33989dc77858ecd0abcd99](https://user-images.githubusercontent.com/58889944/70853654-84ba5680-1e76-11ea-8846-b99b7ef75c56.png)

**Comment by Alexsuperfly** [comment] 2019-12-14 19:46
duplicate of #5466

**Closed** 2019-12-14 19:47 UTC
Labels: duplicate
