### ISSUE TITLE
Real-time ping plugin

### ISSUE THREAD

**Issue by MattRKing** [runelite/runelite#8941] opened 2019-05-28 08:52 UTC
I would really like an expansion of the ping plugin in the world hopper.  What I mean by this, is to have the option to also have your ping displayed on screen (perhaps with the FPS).  This ping indicator will also display your current ping in real-time, rather than having to manually check your ping.  Currently the ping plugin for the world hopper has to test every single world and because of this it can take a while before it even show the world you are on.  It also only tests the ping once and will display what it gets back, this can lead to it saying that your ping to the world you are on is only 25ms when you are actually spiking to 200ms every now and then.  With a real-time ping plugin it shows ping that is actually relevent and accurate to your osrs experience.

Pros-
Can see the stability of your connection.
Could possibly save a HCIM from lag related deaths.
Automatic and accurate.
Shows your ping to that world instead of having to bother with 90+ worlds you may never play on.
QoL.
On-par with most games that have the same ping displayer.

Cons-
As far as I know, none.
There might be client stability issues from it but I'm no coder so this one may very well be entirely inaccurate.

**Comment by Hydrox6** [comment] 2019-05-28 08:55
Duplicate of #2640 (It's closed because ping was added to the World Hopper, but there  is #8871 which will do what you want)

**Closed by Hydrox6** 2019-05-28 08:55 UTC
