### ISSUE TITLE
Minimap entity hider

### ISSUE THREAD

**Issue by diglett809** [runelite/runelite#13738] opened 2021-06-15 06:21 UTC
**Is your feature request related to a problem? Please describe.**
I like doing new quests as soon as they're released guideless, but the minimap is generally full of people who go to the correct areas so spoils how to solve the quest.

**Describe the solution you'd like**
Make it so you can hide all dots on your minimap.

**Describe alternatives you've considered**
I currently hide minimap, but it makes it harder to move around the game/can't look at the area I'm in if its a new area for the quest.

**Comment by Hydrox6** [comment] 2021-06-15 08:53
Duplicate of #12070

**Closed by Hydrox6** 2021-06-15 08:53 UTC
