### ISSUE TITLE
Player Indicators won't display friend's names if that friend has private off

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#1719] opened 2018-04-20 02:28 UTC

**Comment by Adam-** [comment] 2018-04-20 02:29
I think this was intentional as it seems OP otherwise.

**Comment by Infinitay** [comment] 2018-04-20 02:34
#950 and #951 IIRC we were against this

**Comment by deathbeam** [comment] 2018-04-20 06:45
Duplicate of #950

**Closed by deathbeam** 2018-04-20 06:45 UTC
Labels: duplicate
