### ISSUE TITLE
Add customization of flash notifications

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2593] opened 2018-05-11 06:03 UTC
Color, number of times it flashes, tenths of seconds/milliseconds each flash is. At least the second two.

Also with how eye-grabbing flash notifications are and the inability to toggle which idle actions I want to be alerted of, re-plugging #2215. Not looking forward to repeatedly turning flash notifications on and off based on what I'm doing.

**Comment by dicrypt** [comment] 2018-06-21 14:40
Would having color picking options alongside the various plugin properties that enable notifications be good? For example: I want low health red, low prayer teal, action idle black, etc. 
I wouldn't mind picking up this feature if that's the case.

**Comment by Jalopyy** [comment] 2018-06-21 15:06
Doesn't matter to me, personally.

**Comment by deathbeam** [comment] 2018-10-29 13:16
I dont think this should be implemented, and part of issue is duplicate of #2215

**Closed by deathbeam** 2018-10-29 13:16 UTC
Labels: feature-request

**Comment by JorgeFernandezH** [comment] 2020-06-26 03:06
I hope this gets implemented, having a red light flash in ur face sucks
