### ISSUE TITLE
Customizable audio notification system (chat/status notifications) 

### ISSUE THREAD

**Issue by SaintJuniper** [runelite/runelite#13926] opened 2021-07-22 22:47 UTC
**Is your feature request related to a problem? Please describe.**
The problem of trying to track different timers/statuses such as Resurrect Thrall timer, Divine potion timer, Prayer drain through different audio cues 

**Describe the solution you'd like**
A way to pair up a certain chat notification (such as 'thrall returns to the grave') or in-game status (such as prayer points going below 5) with unique (DIFFERENT) audio files 

**Describe alternatives you've considered**
Currently trying 'Idle Notifier' plugin for prayer notifications, 'Chat Notifications' plugin for chatbox (thrall, divine potions) notifications. 

a) Chat Notifications plugin where you'd use the 'Highlight words' section and 'Notify on highlight' to get a notification for a custom event written in the chat box
b) Idle Notifier plugin where you'd use the 'Prayer Threshold' section to get a notification for prayer going below a certain threshold 

However they both use the same base notification.wav file and can't be distinguished between. Ideally I'd love to see a system where you can map a certain event with a certain audio file

**Comment by Hydrox6** [comment] 2021-07-22 22:49
Duplicate of #11679

**Closed by Hydrox6** 2021-07-22 22:49 UTC
