### ISSUE TITLE
!Lvl & !Total Not working

### ISSUE THREAD

**Issue by xCrimin4L** [runelite/runelite#10619] opened 2020-01-18 23:52 UTC
So all other commands work except !lvl and !total:
![](https://puu.sh/F1jeJ/65a4597c7f.png)

I have chat commands enabled and all options inside enabled and still nothing 
![](https://puu.sh/F1jgU/751cf7345a.png)

It seems that it wasn't working for someone else too who was near me when I was trying to get it to work.

**Comment by Hydrox6** [comment] 2020-01-18 23:53
Duplicate of #10592

**Closed by Hydrox6** 2020-01-18 23:53 UTC

**Comment by xCrimin4L** [comment] 2020-01-19 00:00
> Duplicate of #10592
> This uses the same system as the Hiscores, see linked post

So there is nothing that can fix this?

**Comment by Hydrox6** [comment] 2020-01-19 00:07
Nothing we can do, no
