### ISSUE TITLE
Left Click to Withdraw X

### ISSUE THREAD

**Issue by BoulderFalcon** [runelite/runelite#1855] opened 2018-04-23 22:20 UTC
Simple suggestion, if possible: Enable left clicking to withdraw a custom amount. Would be helpful for bankstanding activities like Battlestaves, Wines, Herblore, etc.  Hopefully this would be in-line with Jagex rules?

**Comment by deathbeam** [comment] 2018-04-24 09:53
Duplicate of #1647

**Closed by deathbeam** 2018-04-24 09:53 UTC
