### ISSUE TITLE
Collapsing right panel settings via a Command/Button

### ISSUE THREAD

**Issue by Gum13** [runelite/runelite#921] opened 2018-03-09 21:52 UTC
Completely collapsing right panel, so theres nothing on the right hand side.
(Konduit also had a ctrl+f1 feature where it will hide the side panel, making your client symmetrical with nothing on the right hand side).

**Comment by ShaunDreclin** [comment] 2018-03-09 21:57
Duplicate of #449 & #656
Related to #783

**Comment by deathbeam** [comment] 2018-03-10 00:57
Closing as duplicate of #656

**Closed by deathbeam** 2018-03-10 00:57 UTC
