### ISSUE TITLE
Menu Entry Swapper

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#1452] opened 2018-04-12 20:10 UTC
please separate the 'Teleport item' for the dueling ring and the crafting skill cape please make two different options for them because i want to enable one and not the other.
also for the construction cape are we able to change it to tele to home? and not the teleport or are we able to customize that without clicking the shift and just the left click?

**Comment by jplsek** [comment] 2018-04-13 01:03
See #1335. Teleport swap may be getting removed. I recommend setting it up with the shift-click
customization plugin, which should give you what you want.

**Comment by Adam-** [comment] 2018-04-15 02:15
This is mostly a duplicate of #971. Ended up not removing left click teleports for now, but the default has been changed to not swap. I think that the shift click is a good compromise for this.

**Comment by deathbeam** [comment] 2018-07-20 18:18
Duplicate

**Closed by deathbeam** 2018-07-20 18:18 UTC
Labels: feature-request
