### ISSUE TITLE
Teleport Jewelry and Inventory tagging

### ISSUE THREAD

**Issue by o-d-a-z** [runelite/runelite#9280] opened 2019-07-04 08:06 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...] When using Inventory Tags to set up equipment, every piece of Teleport Jewelry needs to be added individually, so say if I have two slots for teleport jewelry in one of my tags, 1 for a fully charged Amulet of Glory (6) and one for an amulet of Glory that is currently being used (charges 5-1) If I take out my Amulet of Glory (5) and use a charge, it becomes an Amulet of Glory (4) and needs to be added to the inventory tags again. This is pretty frustrating and requires constantly sorting your inventory tags and moving the pieces of jewelry back into the tag.

**Describe the solution you'd like**
It would be nice if the teleport jewelry kept its tag, so that a glory that has 5 charges that then goes down to 4 charges, should be stored in the same bank tag as the 5 charge jewelry. This would prevent you having to have every single charged glory state (1-6) tagged so that it doesn't leave the tag tab.

This would also be useful for stuff like birdhouse runs, so I can simply have 2 Digsite Pendants tagged, 1 fully charged digsite pendant, and another slot for any pendants charged 4-1.
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
Maybe make it so just any jewelry that has less than max charges is stored in the same inventory tag, so you would only ever need 2 slots for your jewelry in a tag tab, the fully charged jewelry and a currently in use piece of jewelry.
**Additional context**

**Comment by Hydrox6** [comment] 2019-07-04 08:38
Inventory Tagging and Bank Tag Tabs are two entirely different things. If you could clarify which you are talking about, that would be great.

If it's Inventory Tagging not affecting the same jewellery with different charges, this is a duplicate of #8204.

If it's Bank Tag Tabs losing the placeholder when you remove some charged jewellery from it, this is already implemented in the form of Variation Tags. Simply drag the item to the tag tab while holding shift.

If it's something entirely different, do let us know.

**Closed by Hydrox6** 2019-07-04 08:38 UTC

**Comment by o-d-a-z** [comment] 2019-07-04 09:05
> Inventory Tagging and Bank Tag Tabs are two entirely different things. If you could clarify which you are talking about, that would be great.
> 
> If it's Inventory Tagging not affecting the same jewellery with different charges, this is a duplicate of #8204.
> 
> If it's Bank Tag Tabs losing the placeholder when you remove some charged jewellery from it, this is already implemented in the form of Variation Tags. Simply drag the item to the tag tab while holding shift.
> 
> If it's something entirely different, do let us know.

Hi, I changed the instances of me using "Inventory Tags" to "Bank Tags", sorry I must of gotten them mixed up.

Using the Shift Click and Drop onto the Bank Tabs seems to be exactly what I was talking about, and keeps the teleport jewelry in the tab even if I didn't set up individual placeholders for them. Thank you!
