### ISSUE TITLE
Runecrafting pouch quality of life

### ISSUE THREAD

**Issue by letos11** [runelite/runelite#5971] opened 2018-10-12 19:16 UTC
Is it possible to swap the first option while at the bank interface, and when holding the essence pouches on the inventory , "Deposit-All" [pouch] to the last option "Fill" [Pouch].

**Comment by Kamielvf** [comment] 2018-10-12 19:17
No. Also duplicate of some issue, and on the rejected list.

**Closed** 2018-10-12 19:19 UTC
