### ISSUE TITLE
Folders for screen markers

### ISSUE THREAD

**Issue by nuwvndv** [runelite/runelite#12420] opened 2020-08-31 06:21 UTC
Hi,
I use alot runelite and use alot of the screen markers plugin to help remember essential mouse clicks position for different activities.

For a same activity (agility course, blast furnace, etc.) i usually have 3 to 10 screen markers to help me. so i usually title them to help me remember the marker (blast furnace 1, blast furnace 2, blast furnace 3, .... ).
It works well but it creates a long list of all my screen markers, and it's hard to find and remember each of my screen markers.

So my suggestion is to add some kind of folder's system or anything else to help rearranged and reorder our multiple screen markers. 

Thank you guys for reading my suggestion, and thank you for this amazing client !!!

nuwanda

**Comment by deathbeam** [comment] 2020-08-31 06:51
Duplicate of #3205

**Closed by deathbeam** 2020-08-31 06:51 UTC
Labels: duplicate
