### ISSUE TITLE
Dragon Crossbow and Karil's Coif make the GPU plugin go wild

### ISSUE THREAD

**Issue by Azebu** [runelite/runelite#13697] opened 2021-06-05 22:06 UTC
**Overview of the Issue** - Equipping these two items causes the GPU renderer to artifact, some triangles pop in and out on character's mesh and around them. Disabling the GPU plugin makes the problem go away. 

**Java Version and Operating System** - Java Version 8 Update 291, Windows 10 Version 20H2
**Reproduce the Error** - Equip Dragon Crossbow and Karil's Coif, rotate the camera so that it shows back of the character, angled slightly up.

https://user-images.githubusercontent.com/7274942/120906573-eff37c00-c65a-11eb-8d25-e4c55ecf5900.mp4

**Comment by Adam-** [comment] 2021-06-05 22:08
I can't reproduce this 
![image](https://user-images.githubusercontent.com/309739/120906629-0da7ed80-c629-11eb-873c-911029c96705.png)

**Comment by Azebu** [comment] 2021-06-06 00:19
Interesting, Artifacting didn't happen on another computer I tried (with same Runelite settings). Faulty one has a 3000 series NVIDIA GPU, the other uses integrated graphics. 
"Compute Shaders" seems to be at fault here, as turning it off makes the issue disappear. Updated drivers, but no luck.

**Comment by Azebu** [comment] 2021-06-06 00:23
One more thing I noticed, the problem seems to disappear when equipping a cape. Tried Graceful, Fire Cape, and Ava's Assembler. This probably makes the issue a small quirk not worth fixing, but could help with reproducing the error.

**Comment by Nightfirecat** [comment] 2022-07-10 05:01
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 05:01 UTC
