### ISSUE TITLE
Spirit angler not counting for anglerfish step in master clue

### ISSUE THREAD

**Issue by enriquevilla** [runelite/runelite#13463] opened 2021-04-10 19:26 UTC
The new spirit angler pieces currently don't make the angler outfit list item to be checked on the master clue step to fish an anglerfish for Sherlock. Same deal as #13454

**Comment by Nightfirecat** [comment] 2021-04-10 19:27
Duplicate of #13420

**Closed by Nightfirecat** 2021-04-10 19:27 UTC
Labels: duplicate
