### ISSUE TITLE
drinking antidote++ in bank doesnt trigger timer

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#10724] opened 2020-02-03 19:31 UTC
Drinking an antidote++ from the bank inventory does not create the timer infobox, drinking outside the bank works correctly.

Oddly enough i have tried to reproduce this with other antipoison style potions and all the ones ive tried have correctly created the timer

inspecting the bank inventory widget containing the antipoison potion displays the same itemID as outside the bank aswell

**Comment by Alexsuperfly** [comment] 2020-02-03 19:41
upon further logging, the item id thats returned by clicking to drink any potion in the bank inventory is `9` but most of the other potions have chat messages that the timer plugin goes off of to create the timer and that is why they were able to function correctly

**Comment by Nightfirecat** [comment] 2020-02-04 01:50
Duplicate of/related to #1471.

I would really like to revisit #7956 to get this solved in a more general way.

**Closed** 2020-02-16 00:37 UTC
Labels: bug
