### ISSUE TITLE
getCollisionMaps() pulling null from API

### ISSUE THREAD

**Issue by RumbleCrumble** [runelite/runelite#11613] opened 2020-05-15 17:56 UTC
**Describe the bug**
CollisionData[] collisionData = client.getCollisionMaps(); returns null which is a Runelite API function

**To Reproduce**
CollisionData[] collisionData = client.getCollisionMaps();

**Expected behavior**
The Array not to be null

**Environment (please complete the following information):**
Runelite Newest Version as of today. Windows

**Additional context**

**Comment by melkypie** [comment] 2020-05-15 17:59
Duplicate of #9792

**Closed by melkypie** 2020-05-15 17:59 UTC

**Comment by Adam-** [comment] 2020-05-15 18:08
I'm curious what your use case is for this? Most of the reason why it was limited in the first place was people kept using it to make 1-way safespots clients for pvp, but since Jagex has fixed that now I'm not sure its still necessary.

**Comment by RumbleCrumble** [comment] 2020-05-15 18:40
I was playing around with the Developer Tools tab so I can see how they work and learn Java from them. One of the options "Valid Movements" wasn't working so I tried to see if I could find out why. Led to this.
