### ISSUE TITLE
[Suggestion] Ability to reset only xp/hr

### ISSUE THREAD

**Issue by Keskari** [runelite/runelite#11919] opened 2020-06-18 11:10 UTC
I take breaks every so often, sometimes forced by the game.

However, my xp/hr calculations sometimes don't take account into these breaks, hence it goes down.

Also, perhaps make the xp/hr calculations only calculate xp gathered in the last hour, not just from the whole session. For an example, if you're doing an agility course for a time, and you level up and thus fail less and get more XP. The xp/hr calculation skews the actual xp/hr rates this way.

**Comment by while-loop** [comment] 2020-06-18 13:15
Duplicate of #11345

**Closed** 2020-06-18 13:18 UTC
