### ISSUE TITLE
Drop List table tab.

### ISSUE THREAD

**Issue by andiedee** [runelite/runelite#6303] opened 2018-11-01 21:35 UTC
Basically a tab much like the ground loot tab, just you will be able to search a monster and have the drop list there to show us quick and easy information about the monster you're killing :)
I've googled if anyone had mention this but no one seems to have my mistake if it has before, and i'm sure it has but just planting a seed here if it hasn't before. Thanks and i hope to see this feature in the client, would work nice with the ground loot tab.

**Comment by KasparRosin** [comment] 2018-11-02 08:55
duplicate of #4004

**Closed** 2018-11-02 14:05 UTC
