### ISSUE TITLE
Plugin tag category dropdown button does not display properly

### ISSUE THREAD

**Issue by makingcomment** [runelite/runelite#11809] opened 2020-06-04 18:47 UTC
**Describe the bug**
For me, the button for the plugin tag discoverability dropdown added with #11606 displays as:
<img width="221" alt="badbutton" src="https://user-images.githubusercontent.com/49528120/83797866-45c0cd00-a671-11ea-8e35-2c389fd4781f.png">

**To Reproduce**
Open RuneLite, open the sidebar to see the list of plugins, and then look at the search field.
(I assume the reproduction steps will generally be more complicated or OS specific than this, since the issue would have immediately been caught in testing if it happened all the time, but this is enough for me to reproduce it)

**Expected behavior**
Based on the image in #11606, it's supposed to display as:
<img width="221" alt="goodbutton" src="https://user-images.githubusercontent.com/12366911/82029379-29bea280-9654-11ea-80e6-58ab347e87cb.png">

**Environment:**
 - OS: macOS (10.14.3)
 - RuneLite version: 1.6.18.1
 - Launcher version: 2.1.2

**Comment by Hydrox6** [comment] 2020-06-04 19:36
iirc it's something to do with a "fallback" font. We use the OSRS font for basically all text in the client, but that font doesn't contain a tick or cross, so it falls back onto a system font. I'm not sure how it's chosen, but as can been seen with the barrows and clue overlays, it's been around for a long time.

**Comment by deathbeam** [comment] 2020-06-04 19:48
Duplicate of #7992

**Closed by deathbeam** 2020-06-04 19:48 UTC
Labels: bug, platform:macos
