### ISSUE TITLE
Unlocked Frame Rate (Similar to Steam & Mobile Client)

### ISSUE THREAD

**Issue by NataIynn** [runelite/runelite#14114] opened 2021-09-09 22:14 UTC
With the launch of RuneLite HD near, it would be VERY nice if we can have unlocked frame rates. The steam client and mobile clients already have this feature, and HDOS Client. I've recently switched from the Steam Client and now using RuneLite, having 50 FPS, doesn't look that great with my gaming monitor.

Please Adam <3.

**Comment by Hydrox6** [comment] 2021-09-09 22:19
Duplicate of #3890

**Closed by Hydrox6** 2021-09-09 22:19 UTC
