### ISSUE TITLE
Prevent opening impling jars, when clue is in inventory

### ISSUE THREAD

**Issue by rogierdevries** [runelite/runelite#9351] opened 2019-07-12 12:29 UTC
For any clue hunters out there who want to save some impling jars.

**Comment by Nightfirecat** [comment] 2019-07-12 15:45
I don't think we're interested in adding any further left-click inventory menu entry swaps. I would personally recommend just opening your impling jars more slowly. :)

**Comment by Hydrox6** [comment] 2020-11-18 14:04
Duplicate of #4927

**Closed by Hydrox6** 2020-11-18 14:04 UTC
