### ISSUE TITLE
Farming Timer Sort/Highlight

### ISSUE THREAD

**Issue by madman1391** [runelite/runelite#11777] opened 2020-05-31 18:15 UTC
**Is your feature request related to a problem? Please describe.**
It is not related to a problem or issue just a small feature to make Farm/Herb runs easier to complete.

**Describe the solution you'd like**
I would like to see either the ability to sort all of the farming timers by when they are complete or highlighting of timers that correspond to patches that are fully grown, allowing you to easily determine which patches still need to be harvested.  

**Describe alternatives you've considered**
The alternatives are always doing farm runs in the same order,  or looking closer at the list of patches to see which are done. 

EDIT: It appears there is a color difference at the bottom of the timer however this color difference is very hard to differentiate between the shades of green. Maybe utilize different colors or make the difference easier to notice.

**Comment by Hydrox6** [comment] 2020-05-31 18:43
Duplicate of #3056

**Closed by Hydrox6** 2020-05-31 18:43 UTC
