### ISSUE TITLE
JVM crashing on login

### ISSUE THREAD

**Issue by Chillouh** [runelite/runelite#5675] opened 2018-09-27 18:13 UTC
I open runelite it load succesfully and than i write down my username and password, also fine but than the programm will close it self i tried multiple times but it dont work

I also tried to login from offical client and move my account to other places like ge
deleted runelite and downloaded again but i everytime have the same problem

please help

**Comment by biz0** [comment] 2018-09-27 20:31
Having the same issue.

**Comment by Chillouh** [comment] 2018-09-27 20:33
and no one replys for a solution... tbh

**Comment by Chillouh** [comment] 2018-09-27 20:34
ANY1? help plz?

**Comment by Alexsuperfly** [comment] 2018-09-27 20:35
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client

**Comment by devLotto** [comment] 2018-09-27 20:45
**Client closing when loading**

This looks like corrupted jagex cache issue. Try to delete %userprofile%\jagexcache on Windows or $HOME/jagexcache on macOS and Linux.

Reply if it worked.

**Comment by ThyMexicunt** [comment] 2018-09-27 20:46
I've tried all avaiable options (Uninstalling Runelite, deleting JagexCache, installing Jagex's OSRS Client and teleporting somewhere else, using another account) and yet a crash everytime I log in.

**Comment by Chillouh** [comment] 2018-09-27 20:47
> 
> 
> I've tried all avaiable options (Uninstalling Runelite, deleting JagexCache, installing Jagex's OSRS Client and teleporting somewhere else, using another account) and yet a crash everytime I log in.

SAME!

**Comment by Chillouh** [comment] 2018-09-27 20:55
tried everything but can still not log in the client really frustrating...

**Comment by raiyni** [comment] 2018-09-27 20:56
Post your logs in a pastebin.

**Comment by Chillouh** [comment] 2018-09-27 20:57
> 
> 
> Post your logs in a pastebin.

im a noob at the subject u talking about can u give me more info to post the logs

**Comment by raiyni** [comment] 2018-09-27 20:59
It says in the above link where your logs are located.

**Comment by Chillouh** [comment] 2018-09-27 21:03
> 
> 
> I've tried all avaiable options (Uninstalling Runelite, deleting JagexCache, installing Jagex's OSRS Client and teleporting somewhere else, using another account) and yet a crash everytime I log in.

Can u please post the logs in a pastebin

**Comment by ThyMexicunt** [comment] 2018-09-27 21:08
Application Log: https://pastebin.com/4W18brUp
Launcher Log: https://pastebin.com/6GFbm0pM

**Comment by Pyromunky** [comment] 2018-09-28 02:48
Your going to have to delete all 1.4.19 jar files, so Runelite re loads it all back in properly. I deleted just the client one and didnt help, delete them all and they will get re downloaded.

If you dont know how to get to that point just plug in client-1.4.19 into your search bar in my computer.

**Comment by ThyMexicunt** [comment] 2018-09-28 03:36
> 
> 
> Your going to have to delete all 1.4.19 jar files, so Runelite re loads it all back in properly. I deleted just the client one and didnt help, delete them all and they will get re downloaded.
> 
> If you dont know how to get to that point just plug in client-1.4.19 into your search bar in my computer.

Doesn't work here, still seems to crash.

**Comment by Killemezy** [comment] 2018-09-28 06:33
Ok so this isnt a fix but a band-aid. Go into the folder where the runelite launcher is located. Instead of running the exe run the runelite jar file. It will be the one with the java icon. Worked for me when nothing else did

**Comment by Chillouh** [comment] 2018-09-28 07:29
> 
> 
> Ok so this isnt a fix but a band-aid. Go into the folder where the runelite launcher is located (if you dont know where that is easiest way to get to the folder is to just open up runelite hit ctrl alt and delete right click it on the task manager then click open file location) Instead of running the exe run the runelite jar file. It will be the one with the java icon. Worked for me when nothing else did

I tried this and deleted the jar files.... but now runelite dont even open... tbhhhhhhhhhhhhhhhhhh

**Comment by Killemezy** [comment] 2018-09-28 07:32
Re install runelite and try the method listed above

**Comment by Chillouh** [comment] 2018-09-28 07:40
![afbeelding](https://user-images.githubusercontent.com/43651517/46194692-6cf2c300-c302-11e8-9338-bba32c4d4299.png)

The runelite.jar dont open with java, or is it a other file i have to open?

**Comment by uriperfumo** [comment] 2018-09-29 17:00
Same thing happens to me, i cant do anything, PLEASE HELP

**Comment by Killemezy** [comment] 2018-09-29 18:46
Do you have the latest version of java?

**Comment by uriperfumo** [comment] 2018-09-29 23:37
yes i do man

**Comment by uriperfumo** [comment] 2018-09-29 23:44
Please help, i still have this annoying error

**Comment by Abextm** [comment] 2018-10-01 02:33
If you are experiencing this issue and have some time, ping me on Discord and I will give you a tool to help us figure out the cause of this.

**Comment by Fumeio** [comment] 2018-10-01 11:32
Same issue occurring for me, here are both of my logs - https://pastebin.com/k9Z7uguV 

Tried deleting jagexcache and I only have 1.4.19 jar on my computer so I can't revert to 1.4.18 if I delete it.

**Comment by Katakylsm** [comment] 2018-10-03 05:13
Yesterday when I tried to run runelite the program was crashing for me after pressing the log in button where runescape pops up the "loading..." box in the top left corner. I tried all of the stated fixes in this post, and I also cleared my java/runescape cache and nothing fixed it. I opened it up to try again to today and it worked on the first try. Not sure why but maybe they have fixed this?

**Comment by haneyUltraInstinct** [comment] 2018-10-03 13:43
Not fixed yet, still cant log in in anyway, too sad this problem has been for longtime now and no fixed, think i'll just play on vanilla and delete it, pointless to try everyday for half an hour just to get 1 lucky login

**Comment by Pyromunky** [comment] 2018-10-08 16:53
This issue is dead, latest release along with java update eliminates this issue, this can be closed

**Comment by Nat3Dogg** [comment] 2019-06-18 17:00
@Pyromunky is correct. This issue should be closed. The fix is having the most recent version of Java + latest release of runelite.

**Closed** 2020-01-31 01:47 UTC
Labels: bug, needs-information
