### ISSUE TITLE
Add infobox for remaining fills on rune pouch

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2660] opened 2018-05-12 23:50 UTC
http://oldschoolrunescape.wikia.com/wiki/Pouch_(Runecrafting) for # of fills before they degrade.

Add infobox for the remaining fills left of the biggest pouch you have until degradation. Reset counter after an NPC contact/talking to abyss mage.

**Comment by deathbeam** [comment] 2018-05-13 11:51
Duplicate of #1007

**Closed by deathbeam** 2018-05-13 11:51 UTC
