### ISSUE TITLE
Runelite crashed when trying to turn on GPU plugin

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#10694] opened 2020-01-30 08:08 UTC
After the latest update (I am using 1:1.6.5) my runelite crashes without any error message on the screen, when I try to turn on the GPU plugin. The following can be seen when at the end of the standard output. I can provide more info if requested, not sure what is relevant. I am running on Arch Linux 5.4.8. 

    2020-01-30 09:03:10 [main] INFO  net.runelite.client.RuneLite - Client initialization took 17002ms. Uptime: 18807ms
    2020-01-30 09:03:10 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,17,640x783,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1280x783,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@683fe13b,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
    Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

**Comment by jachymb** [comment] 2020-01-30 08:15
Observation: When I downgrade jdk from 13 to 11, its the same. When I downgrade to 10, it does not crash, but the plugin does toggle button switches off immediately and apparently the plugin is not active.

**Comment by jachymb** [comment] 2020-01-30 08:34
This is the error message shown at stdout with jdk 10 or 8.

    2020-01-30 09:33:12 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
    com.jogamp.opengl.GLException: Profile GL4 is not available on X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x4a63619a, isOwner false, <4024751a, 16f5c85c>[count 0, qsz 0, owner <NULL>]]], but: [GLProfile[GLES1/GLES1.hw], GLProfile[GLES2/GLES2.hw], GLProfile[GL2ES1/GL2.hw], GLProfile[GL2ES2/GL2.hw], GLProfile[GL2/GL2.hw], GLProfile[GL2/GL2.hw], GLProfile[GL2GL3/GL2.hw]]
	    at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
	    at com.jogamp.opengl.GLProfile.get(GLProfile.java:1004)
	    at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$0(GpuPlugin.java:261)
	    at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	    at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:193)
    	    at eh.ta(eh.java:5814)
	    at client.ac(client.java)
	    at bf.hv(bf.java:373)
	    at bf.run(bf.java:327)
	    at java.lang.Thread.run(Thread.java:748)

**Comment by jachymb** [comment] 2020-01-30 11:08
There is some related discussion on the archlinux AUR package page: https://aur.archlinux.org/packages/runelite/ May contain some relevant info.

**Comment by MrCarroll** [comment] 2020-01-30 11:34
The first error is that JOGL used by RuneLite has versioned symbols, and is looking for a function in Java that doesn't correctly match what Arch is providing. This is a problem for a lot of Linux distributions with RuneLite at the moment, and there's quite a few considerations on how to approach the issue, but by far the most simple fix to just run the AppImage raw, since it contains AdoptOpenJDK 11, which happens to work absolutely fine.

The second error is that Java doesn't believe your GPU to be capable enough to run RuneLite. The GPU needs to have OpenGL 4.3 support, Google your GPU's OpenGL support and see if it's suitable. If it is suitable and still doesn't work, it implies you might not have installed graphics drivers properly on Arch, which should just be as simple as installing the "mesa" package for Intel/AMD, and the "nvidia" package for NVidia cards, although if using NVidia, I'd look into the wiki first, as there's some special cases.

https://wiki.archlinux.org/index.php/NVIDIA

**Comment by jachymb** [comment] 2020-01-30 13:14
It was working just fine until this update. Have the GPU requirements changed in any way? My graphics card is:

    $ glxinfo|grep "Device"
    Device: Mesa DRI Mobile Intel® GM45 Express Chipset  (0x2a42)

**Comment by MrCarroll** [comment] 2020-01-30 17:39
Just to be clear, the AppImage bit is exclusively for the first problem and your issues here are two distinctly seperate problems, every Arch user and a lot of general Linux users will have the first issue and this is worsened by the fact the AUR clients aren't produced by RL whatsoever, that issue is 100% an incompatible JRE, and the RL official response would be to use the AppImage in this scenario because the AUR are third party.

As for the second, I don't think anything has changed wrt the GPU rendering. Honestly, your GPU seems pretty old and I can't be 100% sure on an explaination for this scenario,  but you can try setting ` export MESA_GL_VERSION_OVERRIDE='4.3' in the terminal prior to `./runelite.appimage' - it will lie about the level of support your GPU has, which isn't the same as actually enabling that support. Frankly, I don't expect it to work, but in some rare scenarios GPU drivers can underreport the compatability they have, usually for stability reasons, and might work fine with some encouragement. I haven't been able to Google just what support is specified by Intel for that GPU. It could be an update has artificially lowered it if it was working fine before.

Beyond that, I'd recommend popping into the support channel of the RL Discord, the answers should be a fairly quicker and you can probably find help quicker there.

**Comment by jachymb** [comment] 2020-01-30 18:39
Thank you for taking the time to reapond to this, Carroll.

**Comment by telans** [comment] 2020-04-11 21:40
> Just to be clear, the AppImage bit is exclusively for the first problem and your issues here are two distinctly seperate problems, every Arch user and a lot of general Linux users will have the first issue and this is worsened by the fact the AUR clients aren't produced by RL whatsoever, that issue is 100% an incompatible JRE, and the RL official response would be to use the AppImage in this scenario because the AUR are third party.

For anyone looking to solve this when using RuneLite via Intellij IDEA, I managed to get it working via installing the `jdk-adoptopenjdk` AUR package and exporting `IDEA_JDK=/usr/lib/jvm/java-14-adoptopenjdk/`.

Setting that variable seemed to be the only way I could get maven to build with adoptopenjdk (set via "Use Internal JRE". Running with the same version.

`jdk11-adoptopenjdk` exists in the AUR, but I haven't tested it as the GPU plugin works fine for me with the java-14 version.

**Comment by MESLewis** [comment] 2021-01-13 03:14
Does this happen on the latest release of RuneLite?

**Comment by Nightfirecat** [comment] 2022-07-10 04:06
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:06 UTC
Labels: gpu
