### ISSUE TITLE
Add notifications for all time tracking sections

### ISSUE THREAD

**Issue by snitgaard** [runelite/runelite#12629] opened 2020-10-11 11:49 UTC
I feel like the client needs infoboxes for farm contracts / herbs being done and birdhouses to keep track of when u can do your hourlies. Either that, or add notifications for each activity so whenever one is ready say "Your herbs have fully grown and is ready to be picked" and contract "You have completed your farming contract". I know it would make me do my hourlies a bit more consistently if this was possible

**Comment by Nightfirecat** [comment] 2020-10-11 17:51
Infoboxes have been requested in #8500. That said, we could probably add options for notifying on other time tracking sections besides bird houses.

**Comment by snitgaard** [comment] 2020-10-11 18:32
> Infoboxes have been requested in #8500. That said, we could probably add options for notifying on other time tracking sections besides bird houses.

I would love the ability to do this. Hopefully itll happen!

**Comment by Hydrox6** [comment] 2020-12-07 12:10
Duplicate of #2212

**Closed by Hydrox6** 2020-12-07 12:10 UTC
Labels: feature-request
