### ISSUE TITLE
Add an option to toggle 2010 hitsplats

### ISSUE THREAD

**Issue by ShreditRS** [runelite/runelite#11647] opened 2020-05-19 14:16 UTC
Requesting to add the new hitsplats as seen on the 2010 update for the previous game version of RuneScape.

We already have the HD Healthbars, which came with the same update as mentioned above, adding these would complete the look and fit way better, thanks!

Reference:
https://runescape.wiki/images/2/26/HitpointsBar.png?75871

![HitpointsBar](https://user-images.githubusercontent.com/65608942/82337499-832c2600-99f4-11ea-9baa-4bfc1f197ee4.png)

**Comment by raiyni** [comment] 2020-05-19 14:36
Duplicate of #9849

**Closed by raiyni** 2020-05-19 14:36 UTC
