### ISSUE TITLE
Include 'Overall Profit' in online Loot Tracker view

### ISSUE THREAD

**Issue by kzisme** [runelite/runelite#8207] opened 2019-03-14 06:44 UTC
**Is your feature request related to a problem? Please describe.**

Issue: A player may want to track loot  amounts >1000 and currently the plugin does not allow for that.  However, when logging into RL online you can view _all_ synced loot data, but prices aren't included.  

**Describe the solution you'd like**
The 1000 loot limitation of the Loot Tracker plugin (inside the client) could be improved by making a slight change to the .json that is synced with your Google account to also include "Overall" profit gained from loot.  

It does seem that the [item id's](https://github.com/runelite/runelite/blob/c2a054ca26d1a0deb894d44d588e62de8e59a24d/http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerService.java#L60) are included in the json, so they might be able to be queried against a GE lookup service (I'm assuming that exists since there is already a plugin for it)

**Describe alternatives you've considered**
Aside from manually looking up each item on the GE/GE Tracker/etc it would be fairly painful to lookup your total profits over time.  This can also be expanded on in the future possibly into graphs of profit over time with specific monsters which would be interesting.

**Additional context**
None currently.

**Comment by deathbeam** [comment] 2019-03-17 17:47
Duplicate of https://github.com/runelite/runelite.net/issues/213

**Closed by deathbeam** 2019-03-17 17:47 UTC
