### ISSUE TITLE
loot tracker does not register kills with no drops

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#10831] opened 2020-02-19 14:18 UTC
Apparently, the kc counter in the loot tracker does not increment on kills that have no drops. There are some monsters that can drop nothing, but this also happens with monsters that only drop bones but are auto-burried with bonecrusher and monsters that only drop coins which are auto-picked by ring of wealth (or both of the above). 

Probably related to #5077

**Comment by Alexsuperfly** [comment] 2020-02-19 14:39
the loot tracker is there for just that, loot.  If there is no loot there is nothing to track, in the case of auto picked up/buried items it cannot track them since the monster never technically drops them as loot.

**Comment by jachymb** [comment] 2020-02-19 14:52
But I think it can lead to skewed/misleading outputs. Example: I am farming Falador Guards for med clues, wearing ring of wealth and using the bonecrusher. In the long term, the loot tracker would show better rate for the clues than the actual droprate. So in my opinion the kc counter should increment on each kill, regardless of whether there is a drop or not.

**Comment by Adam-** [comment] 2020-02-19 14:56
Currently we don't have a way to determine if an npc death is your kill or not. Maybe once Ash adds the new hitsplat stuff we could compute it based off of that.

**Comment by Nightfirecat** [comment] 2020-02-23 07:44
This is in fact a duplicate of #5077, as it's caused the same way. If we are able to fix that issue (using the new hitsplat changes Jagex will be implementing soon), it will address crushed bones and ring-of-wealth-picked-up coins.

**Closed by Nightfirecat** 2020-02-23 07:44 UTC
