### ISSUE TITLE
!pets command not showing icons for each pet

### ISSUE THREAD

**Issue by Anonagonn** [runelite/runelite#14862] opened 2022-04-14 19:18 UTC
Whenever I or anyone else uses the !pets command, I am unable to see the icons for each pet, though others can. 

I have tried looking for any plugins or options that may be affecting it but was unable to find any, nor was I able to find anything on the runelite website or github that indicates that the behavior of the command has been changed. I also tried viewing my pet list in both collection logs, the physical item and the character summary menu, as well as disabling and enabling both the !pets command itself and the entire "chat commands" plugin.

![RuneLite_udxpI4qswR](https://user-images.githubusercontent.com/93434225/163457704-7ccfbf35-cad5-45ef-9941-f9c29fa24736.png)

 - OS: Windows 10
 - RuneLite version: 1.8.17
 - Launcher version: 2.0.1

**Comment by Adam-** [comment] 2022-04-14 19:44
Probably this is caused by a 3rd party plugin, try running in safe mode to confirm it. The APIs to adding chat icons is difficult to use correctly and most 3rd party plugins use it incorrectly, so this is a common issue they're known to cause.

**Comment by Anonagonn** [comment] 2022-04-14 20:39
Starting Runelite in safe mode fixed the issue, so I started removing 3rd party plugins one at a time until I was able to see the pet icons without safe mode enabled, closing and restarting the client after removing each plugin. I thought I had identified the plugin responsible, but upon restarting the client once more with the identified plugin uninstalled, the issue occurred again. After closing and restarting the game a few more times without changing any plugins, I determined that the issue does not occur 100% of the time. So after repeating this process with each 3rd party plugin, I eventually made it to the point where I had uninstalled every plugin and the issue was still occurring.

![RuneLite_owNopOHO1O](https://user-images.githubusercontent.com/93434225/163471579-636898cb-d3b3-4c1e-9fa6-a24f7722381e.png)

**Comment by Adam-** [comment] 2022-04-14 20:44
Can you get the issue to happen when launched in safe mode? I would be interested in looking at it further if so. If you uninstall a plugin you would have to restart the client first before knowing if it fixes the issue.

**Comment by Anonagonn** [comment] 2022-04-14 20:53
After about 7 attempts the issue occurred while in safe mode. I fully closed the Runelite window and launched it again via the command line interface in between each attempt.
![RuneLite_oOa8m3ptXV](https://user-images.githubusercontent.com/93434225/163473339-09b74890-40ee-4cf4-a783-dd88dd04e15c.png)

**Comment by Adam-** [comment] 2022-05-07 14:52
fixed in 026395fad5dcf15b6166ae71b271a5606a031ec1

**Closed by Adam-** 2022-05-07 14:52 UTC
Labels: bug
