### ISSUE TITLE
Some overlays stop working after going to god wars

### ISSUE THREAD

**Issue by NewGuy274** [runelite/runelite#7568] opened 2019-01-26 06:10 UTC
It seems after going in to god wars dungeon and having stats drained can break overlays. This has only happened twice but I believe both were caused by the same thing. I'm killing vorkath and doing elites when I get them, after a step has me go to godwars this starts happening. Boost information and clue locations on map don't show up less I reload client.

1. Go to 'Godwars, maybe during clue'
2. See error

Some overlays stop working

**Environment (please complete the following information):**
 - OS: win10
 - RuneLite version: latest
 - Launcher version: latest

**Comment by Alexsuperfly** [comment] 2019-07-28 20:08
duplicate of #7632

**Closed** 2019-08-12 16:15 UTC
Labels: duplicate
