### ISSUE TITLE
!pb tempoross using in game stats board next to bank at tempoross

### ISSUE THREAD

**Issue by red-eye-jedi** [runelite/runelite#13423] opened 2021-03-31 18:20 UTC
can we get !pb tempoross added using the in game interface that is currently tracking in game personal and global best times.
the board is next to the bank at tempoross. please/thanks

**Comment by Hydrox6** [comment] 2021-03-31 18:34
Duplicate of #13414

**Closed by Hydrox6** 2021-03-31 18:34 UTC
