### ISSUE TITLE
Animation Smoothing Feature Breaks Strut Animation in Motherload Mine

### ISSUE THREAD

**Issue by Psyphin** [runelite/runelite#10511] opened 2019-12-28 15:13 UTC
When the Animation Smoothing feature is enabled, the rotating animation for the Struts in the Motherload Mine break and create a non-circular loop. The default animation provided by Jagex is consistently rotating where Runelite's spins partially and resets. 

I know this is small stuff, but it's driving me nuts going for 99 mining.

1. Go to Motherload Mine next to the Struts and enable "Animation Smoothing"
2. Watch the Strut rotate
3. Disable animation smoothing

**Expected behavior**
The animation of the strut rotating is improved or at least maintained.

**Screenshots**
N/A - animated bug

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: December 2019

**Comment by Adam-** [comment] 2019-12-28 15:18
this is a duplicate of #5435. As far as I know the only way we really have to fix this is to just prevent the anim from being smoothed altogether.

**Comment by Psyphin** [comment] 2019-12-28 15:23
@Adam-ah thanks I searched for Motherload Mine for dupes but not MLM - is that something i can toggle myself specifically for this animation or is that something the client needs to update?

**Comment by Adam-** [comment] 2019-12-28 15:24
No, we would have to update it.

**Closed** 2020-01-07 13:46 UTC
Labels: duplicate
