### ISSUE TITLE
Unable to load client bug

### ISSUE THREAD

**Issue by DeadlyLink** [runelite/runelite#8977] opened 2019-06-01 07:42 UTC
**Describe the bug**
Was hoping worlds on the alt to scout raids, world swapper (the vanilla clients in game world switcher) suddenly just went blank, thought nothing of it because I could still click where worlds would be on the list/ click on favorited worlds, the issue duplicated onto a 2nd Runelite client i had open so I decided to just restart the computer. Relaunched runelite and was greeted with "Unable to launch client please review logs"

**To Reproduce**
Not Able to reproduce due to not being able to log in / access runescape

**Expected behavior**
N/a

**Screenshots**
![image](https://user-images.githubusercontent.com/51258358/58745442-cb82ba80-8416-11e9-8852-3667c7ae1371.png)
Above is what I saw initially which prompted me to restart the client
Below is my current status with the client
![image](https://user-images.githubusercontent.com/51258358/58745429-9d04df80-8416-11e9-8a9a-75f1312e6e3e.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.24.1
 - Launcher version: 1.5.24.1

[client.log](https://github.com/runelite/runelite/files/3243536/client.log)
[launcher.log](https://github.com/runelite/runelite/files/3243537/launcher.log)

**Comment by DeadlyLink** [comment] 2019-06-01 07:45
Was able to fix the issue by logging out of runelite then force running the program as an administrator

**Comment by Kamielvf** [comment] 2019-06-10 01:46
Most likely not something caused by RuneLite - rather your internet connection with the Jagex servers. Closing as author marked issue as resolved.

**Closed by Kamielvf** 2019-06-10 01:46 UTC
