### ISSUE TITLE
GPU ISSUES

### ISSUE THREAD

**Issue by JadenCP1** [runelite/runelite#9207] opened 2019-06-25 22:33 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
This will most likely be marked as a duplicate, however I cant find any threads outlining an actual fix to this issue. Upon logging into the game on runelite, black dotted lines will appear in the water after about a minute of playtime and get larger over time. Quickly toggling the GPU plugin off and back on erases them but only for a minute. Have tried messing with settings in NVIDIA Control Panel and I cant seem to find out whats causing it. Any anti aliasing option via the client seems to produce the same result.

**To Reproduce**
1. Open Runelite
2. Enable GPU Plugin
3. Wait for a minute or so near an area affected area/ Water

**Expected behavior**
After a minute or less, regardless of any movement in game or clicking anything at all, thick black dotted lines will appear in a grid like shape across any water like terrain.

**Screenshots**
![2019-06-25_18-21-16](https://user-images.githubusercontent.com/52222104/60139022-694d7900-977a-11e9-975e-e72d883ad269.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.27
 - Launcher version: 1.6.0

Any help would be appreciated.

**Comment by Kamielvf** [comment] 2019-06-25 23:19
Duplicate of #8680 8680

**Closed by Kamielvf** 2019-06-25 23:19 UTC

**Comment by JadenCP1** [comment] 2019-06-25 23:24
Awesome (:
