### ISSUE TITLE
Runelite crashes when GPU plugin turned on at startup

### ISSUE THREAD

**Issue by ESTcrystal** [runelite/runelite#10276] opened 2019-11-16 10:12 UTC
Hello.

I have noticed this issue happened recently a couple patches ago . The first time i used runelite i had no issues and no crashes. These days Runelite runs usually like 21 to 30 seconds and then crashes when GPU plugin is turned on at startup . If i start runelite with GPU plugin turned off then it works perfectly and if i turn the GPU plugin later on , Runelite dosent crash . Playing GPU off all the time results in no crashes also.

My computer specs:
Intel Core 2 Duo E8400 3GHZ
4GB DDR 2RAM
Nvidia Geforce GT 740 2GB GDDR5
Windows 7 Ultimate SP1 32Bit

<details><summary>client.log</summary><pre><code>2019-11-16 11:36:08 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 350661832.318
2019-11-16 11:36:08 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-11-16 11:36:09 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-11-16 11:36:10 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-11-16 11:36:13 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 11457ms. Uptime: 15605ms
2019-11-16 11:36:13 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1280x984,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@108aa80,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-11-16 11:37:48 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 350661832.318
2019-11-16 11:37:49 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-11-16 11:37:50 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-11-16 11:37:51 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-11-16 11:37:53 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 10596ms. Uptime: 13567ms
2019-11-16 11:37:53 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1280x984,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@7babe3,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-11-16 11:54:49 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 350661832.318
2019-11-16 11:54:49 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-11-16 11:54:50 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-11-16 11:54:52 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-11-16 11:54:55 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 15743ms. Uptime: 19439ms
2019-11-16 11:54:56 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1280x984,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@1ec709,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-11-16 11:56:52 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
com.jogamp.opengl.GLException: Error swapping buffers
	at jogamp.opengl.windows.wgl.WindowsWGLDrawable.swapBuffersImpl(WindowsWGLDrawable.java:93)
	at jogamp.opengl.GLDrawableImpl.swapBuffers(GLDrawableImpl.java:88)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1121)
	at bg.bi(bg.java:45176)
	at bg.ju(bg.java)
	at bg.run(bg.java:336)
	at java.base/java.lang.Thread.run(Unknown Source)
2019-11-16 11:59:52 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 350661832.318
2019-11-16 11:59:52 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-11-16 11:59:57 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-11-16 11:59:58 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-11-16 12:00:00 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 16894ms. Uptime: 20821ms
2019-11-16 12:00:00 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1280x984,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@69882e,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]</code></pre></details>

<details><summary>launcher.log</summary><pre><code>2019-11-16 11:35:59 [main] INFO  net.runelite.launcher.Launcher - RuneLite Launcher version 2.0.2
2019-11-16 11:35:59 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-11-16 11:36:00 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-1.5.40.jar
2019-11-16 11:36:00 [main] INFO  net.runelite.launcher.Launcher - Verified hash of slf4j-api-1.7.25.jar
2019-11-16 11:36:00 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-classic-1.2.3.jar
2019-11-16 11:36:00 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-core-1.2.3.jar
2019-11-16 11:36:00 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jopt-simple-5.0.1.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guava-23.2-jre.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jsr305-1.3.9.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of error_prone_annotations-2.0.18.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of j2objc-annotations-1.1.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of animal-sniffer-annotations-1.14.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guice-4.1.0-no_aop.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of javax.inject-1.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of aopalliance-1.0.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gson-2.8.5.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of substance-8.0.02.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of trident-1.5.00.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-text-1.2.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-lang3-3.7.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-amd64.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-i586.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-amd64.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-i586.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-amd64.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-i586.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-linux-amd64.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-linux-i586.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jbsdiff-1.0.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-compress-1.5.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-4.5.1.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-platform-4.5.1.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runelite-api-1.5.40.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-patch-1.5.40.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of http-api-1.5.40.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okhttp-3.7.0.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okio-1.12.0.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-csv-1.4.jar
2019-11-16 11:36:01 [main] INFO  net.runelite.launcher.Launcher - Verified hash of discord-1.1.jar
2019-11-16 11:37:40 [main] INFO  net.runelite.launcher.Launcher - RuneLite Launcher version 2.0.2
2019-11-16 11:37:40 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-1.5.40.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of slf4j-api-1.7.25.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-classic-1.2.3.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-core-1.2.3.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jopt-simple-5.0.1.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guava-23.2-jre.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jsr305-1.3.9.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of error_prone_annotations-2.0.18.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of j2objc-annotations-1.1.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of animal-sniffer-annotations-1.14.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guice-4.1.0-no_aop.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of javax.inject-1.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of aopalliance-1.0.jar
2019-11-16 11:37:41 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gson-2.8.5.jar
2019-11-16 11:37:42 [main] INFO  net.runelite.launcher.Launcher - Verified hash of substance-8.0.02.jar
2019-11-16 11:37:42 [main] INFO  net.runelite.launcher.Launcher - Verified hash of trident-1.5.00.jar
2019-11-16 11:37:42 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-text-1.2.jar
2019-11-16 11:37:42 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-lang3-3.7.jar
2019-11-16 11:37:42 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2.jar
2019-11-16 11:37:42 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-amd64.jar
2019-11-16 11:37:42 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-i586.jar
2019-11-16 11:37:42 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-amd64.jar
2019-11-16 11:37:42 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-i586.jar
2019-11-16 11:37:42 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2.jar
2019-11-16 11:37:42 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-amd64.jar
2019-11-16 11:37:42 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-i586.jar</code></pre></details>

**Comment by Nightfirecat** [comment] 2019-11-20 07:44
Related to/duplicate of #9889

**Comment by ESTcrystal** [comment] 2019-11-29 17:58
Hello.
Im not sure what more information this needs.
I have nvidia 391.35 drivers

**Closed** 2020-02-23 08:08 UTC
Labels: duplicate
