### ISSUE TITLE
RuneLite OSRS Steam Version Client

### ISSUE THREAD

**Issue by rickprins** [runelite/runelite#13267] opened 2021-02-25 01:54 UTC
As many of you might have noticed, today OSRS dropped on Steam. 

Upon starting the game I immediately noticed the crispier graphics and unlocked framerate and it felt like heaven. It got me thinking. How amazing would it be if in an update, RuneLite would work as overlay for the steam version of the game?!

Maybe through steam itself or maybe still through a standalone client, but it should be possible since the same thing is done on top of the old OSRS client.

Please let me know what u think!

**Comment by iligalodin** [comment] 2021-02-25 04:48
for a temporary fix it could be an option to have the launch options for the game set via the installations:
the launch options you'd want to set are in a players localconfig, not sure how you'd handle it but you could search for the Old school runescape entry and change it to:

```
"1343370"
					{
						"1343370_eula_1"		"2"
						"LastPlayed"		"1614224331"
						"BadgeData"		"020000000821"
						"Playtime2wks"		"6"
						"Playtime"		"6"
						"LaunchOptions"		"\"C:\\Users\\<this is the local user>\\AppData\\Local\\Runelite\\Runelite.exe\" %command%"
					}
```

**Comment by iligalodin** [comment] 2021-02-25 04:49
or you could instruct the users to set their launch options to` "C:\Users\<this is the local user>\AppData\Local\Runelite\Runelite.exe" %command%`

**Comment by rickprins** [comment] 2021-02-25 08:15
Thats what i did right now, but it doesnt u lock the fps and better graphics tho since it basically just runs the current runelite through steam

**Comment by oogaboogadoogydoogy** [comment] 2021-03-06 08:04
this needs more attention. at least a comment if it's feasible or in the works.

runelite for the steam client, basically current runelite but with uncapped fps. please.

**Comment by Mento-s** [comment] 2021-08-04 15:04
Something like this would be amazing, i beg runelite lords.

**Comment by Hydrox6** [comment] 2021-09-09 22:20
Essentially a duplicate of #3890
Otherwise, not really actionable, given the C++ client is entirely different

**Closed by Hydrox6** 2021-09-09 22:20 UTC
