### ISSUE TITLE
Client Crash: Fatal error - Problematic frame: [AppleIntelKBLGraphicsGLDriver+0x1a67fd]  gldExecuteKernel+0x7d

### ISSUE THREAD

**Issue by AndreasJJ** [runelite/runelite#14394] opened 2021-11-21 10:28 UTC
**Describe the bug**
Runelite crashes unexpectedly with no common reason as to what happens in-game.

**To Reproduce**
Non as far as I know.

**Expected behavior**
The client crashes

**Screenshots**
![Skjermbilde 2021-11-21 kl  11 22 53](https://user-images.githubusercontent.com/15128509/142758246-815ed92d-cee8-4cb9-84c4-2751850ccb10.png)

**Environment (please complete the following information):**
 - OS: macOS Big Sur 11.5.2
 - RuneLite version: 2.2.0

**Additional context**
![aa622d34794e1d016017a36fb4a6c7ad](https://user-images.githubusercontent.com/15128509/142758262-5fe1f98a-4c9f-4280-ada7-18e9d0eca300.png)

[jvm_crash_pid_50094.log](https://github.com/runelite/runelite/files/7576079/jvm_crash_pid_50094.log)

**Comment by Nightfirecat** [comment] 2022-07-10 04:15
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:15 UTC
Labels: gpu, not-our-bug, platform:macos
