### ISSUE TITLE
Farming Timer Tray Notification While Not Logged in

### ISSUE THREAD

**Issue by Hajsas** [runelite/runelite#2936] opened 2018-05-19 11:17 UTC
A seemingly "Simple" modification to the current farming plugin that would push tray notifications, similar to idle notifications, upon patch growth while logged in, and while not logged in. Assuming there is already an estimated finish timer between farming ticks that stays the same upon logging out, this should be possible.
Thanks.

**Comment by deathbeam** [comment] 2018-05-19 11:35
Duplicate of #2212

**Closed by deathbeam** 2018-05-19 11:35 UTC
