### ISSUE TITLE
Left click bankers and GE clerks

### ISSUE THREAD

**Issue by GothicLogic** [runelite/runelite#966] opened 2018-03-15 00:14 UTC
Used to it from other clients and it keeps messing me up so being able to left click to bank and use the GE would be nice :)

**Comment by Kamielvf** [comment] 2018-03-15 00:15
Added since #627, will be on release next update.

**Comment by Adam-** [comment] 2018-03-15 00:16
Duplicate of #447

**Closed by Adam-** 2018-03-15 00:16 UTC
