### ISSUE TITLE
Runelite not going fullscreen on 2nd monitor

### ISSUE THREAD

**Issue by TBBRKCK** [runelite/runelite#6447] opened 2018-11-12 21:47 UTC
When trying to put Runelite on my 2nd monitor, it won't take up all the screen space. It leaves an open space at the bottom as if there were a task bar there (but there isn't), and also small open spaces on the left and right hand side.

If I go into my taskbar settings in Windows and turn "Show taskbar on all displays" on and off again it makes runelite go full screen on my 2nd monitor as it should be, but only until I try and move the client again then it reverts back to the original problem.

![](https://puu.sh/C0JYB/7fcac4348a.jpg)

**Comment by deathbeam** [comment] 2018-11-12 22:04
Duplicate of #5153

**Closed by deathbeam** 2018-11-12 22:04 UTC
