### ISSUE TITLE
[Feature Request] Runelite Price

### ISSUE THREAD

**Issue by throwaway34343** [runelite/runelite#10432] opened 2019-12-13 05:23 UTC
OSBuddy Price is inaccurate because nobody uses their client anymore. This does, however, create the risk that the few people still using OSBuddy engage in price manipulation. To combat this, please consider creating an alternative Runelite price system. Since basically everyone uses Runelite, this would be much more accurate.

**Comment by Nightfirecat** [comment] 2019-12-13 05:27
Duplicate of #733

**Closed by Nightfirecat** 2019-12-13 05:27 UTC
