### ISSUE TITLE
!log command

### ISSUE THREAD

**Issue by ajmaj2** [runelite/runelite#13912] opened 2021-07-21 00:30 UTC
**Is your feature request related to a problem?**
I don't believe there is currently a way to share unique drop counts with others players in game for items contained  within your collection log.

**Describe the solution you'd like**
!log command to quickly share your collection log counts for specific items.

**Describe alternatives you've considered**
Currently people just manually type what they have received in game or share screenshots of their logs on discord.

**Additional context**
An example is as below:
Input:
!log elysian spirit shield
or
!log ely

Output:
Elysian Spirit Shield log count 1

Thanks :)

**Comment by geheur** [comment] 2021-07-21 00:34
duplicate of #9025

**Closed** 2021-07-21 00:34 UTC
