### ISSUE TITLE
Weird lines from overlay???

### ISSUE THREAD

**Issue by derpyderpaderp** [runelite/runelite#4922] opened 2018-08-16 00:41 UTC
I am currently on the latest version of Runelite and I am having this weird graphical thing where a line comes straight down from the top of the screen. It happens when I hover my mouse over something in my inventory, over the map, over the XP ball thing on top and sometimes when I click on a monster or NPC. I am on windows 10. I am unaware if this is a settings or a bug. If not a bug can someone provide me with a way to disable it? Thanks. Also attached is a video of what I am explaining. https://www.youtube.com/watch?v=-6KTuVLza70&feature=youtu.be

**Comment by Nightfirecat** [comment] 2018-08-16 01:48
Are you running with hardware acceleration on? (default) If so, try following this and see if it still happens: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by derpyderpaderp** [comment] 2018-08-16 02:35
After about 10 minutes the problem came back again. This was not happening on my other PC that died unfortunately. Any other ideas would be greatly appreciated.

**Comment by Abextm** [comment] 2018-08-16 02:53
Could you post an unscaled still image of the bug? The youtube compression makes some details difficult to see.

**Comment by Kamielvf** [comment] 2018-08-16 03:10
Any chance your graphic drivers are out of date? I've seen this problem before and I don't know what exactly causes it.

**Comment by derpyderpaderp** [comment] 2018-08-16 03:15
I checked that and they are all up to date. I have made sure that Runlite is up to date. I also tried re installing my drivers and Runlite itself and still having this issue. I have disabled hardware acceleration. Still persisting. On my desktop which sadly died I didn't have these but on a laptop if that makes a difference it is there and it is annoying, although still playable. Just seeing if this is a bug with the update or if others have had this issue and had a fix to it. I have looked around and not found anything like this. Only thing close was a bug to where things would duplicate but for me no duplication is happening. I am lost.

**Comment by derpyderpaderp** [comment] 2018-08-16 03:26
Nope still having the issue. I think I just noticed why it is happening though. I moved stuff around on my overlay and it started happening again. I wonder if it has something to do with that in the recent update. I will restart and not mess with it to see what happens

**Comment by derpyderpaderp** [comment] 2018-08-16 03:38
Still doing it. Oddly I found a way to remove it temporarily by hitting my windows key then clicking back into game. I is definitely with the overlay though. I'm assuming a bug with being able to move the overlay around now. I will check back to see if anyone has recommendations but for now this is not solved.

**Comment by derpyderpaderp** [comment] 2018-08-16 04:03
Okay weird but hitting the windows key fixed it for some reason. But that is only temporary.

**Comment by deathbeam** [comment] 2018-08-16 06:41
This looks like bug with your graphic card/JVM and not RuneLite, I dont think we can do anything about that.

**Comment by derpyderpaderp** [comment] 2018-08-17 04:40
I have tried other launchers, not going to mention names here and this is not a problem in those and I have no issue with any other games so it leaves me to believe it is a bug with Runelite. It wasn't happening until the overlays were movable. Had my graphics card checked today to make sure it is working correctly and they said it was working perfectly. I even had them go through and make sure the drivers were correctly installed and no errors were occurring and they said their were none. and I have the latest version of Java so it is not on my end. If I'm not mistaken someone above stated someone else was having the same issue. As of Runelite version 1.4.12.1 this is a bug.

**Comment by deathbeam** [comment] 2018-08-22 18:37
This was definitely not caused by movable overlays. And the .exe is not using your PC installed JVM. This is still nothing we can solve on our side, so idk what to do with this.

**Comment by Abextm** [comment] 2018-08-23 02:03
I've seen a similar bug in Konduit, and since it looks like this is a java2d bug, whatever their fix was may be pertinent to us as well.

**Comment by deathbeam** [comment] 2018-08-23 04:58
I dont think Konduit ever had fix for this as well

**Comment by u47700** [comment] 2018-09-03 02:07
Still receiving same issue on Konduit/Runelite

**Comment by Abextm** [comment] 2018-09-04 10:05
Some questions for those experiencing this bug:
What OS are you on?
Did you use the exe or jar version of RuneLite?
If you use the jar version what version of java do you have installed on your system?
If you use the exe version what launcher version do you have? (It says in the info panel)
What GPU do you have, and what driver version are you running? (`dxdiag` will say this)
What date/version did this start happening?

**Comment by derpyderpaderp** [comment] 2018-09-04 19:40
I am on Windows 10
I have tried the exe and the jar version of runelite and still an issue both latest versions
GPU: Intel (R) hd graphics with latest drivers confirmed from intel and my manufacture website.

**Comment by MESLewis** [comment] 2021-01-13 02:48
Does this still happen on the latest release of RuneLite?

**Comment by derpyderpaderp** [comment] 2021-01-16 01:59
> Does this still happen on the latest release of RuneLite?

Not that I am aware of. Although I cannot give a definitive answer because I do not use that laptop anymore nor do I have it. I will say before I got rid of that laptop I didn't notice it happening and that was a few months ago so either it stopped or I just got so used to it that it just because invisible to my eyes.

**Closed** 2021-01-16 02:00 UTC
Labels: bug, jvm-bug
