### ISSUE TITLE
Grouped markers

### ISSUE THREAD

**Issue by The1Investigator** [runelite/runelite#14707] opened 2022-02-20 22:18 UTC
As it currently stands, screen markers are somewhat clunky, having to individually click each one for activation and likewise for turning them off. What i'd like to propose for a QOL(?) is to have grouped markers.

Grouped markers will be able to turn on (and off) multiple screen markers with the addition of what screen markers currently have to offer.

As a basic example: 
![image](https://user-images.githubusercontent.com/84506788/154866783-b9fb5f0a-334b-4476-a0d3-373423f96e2f.png)

**Comment by Bram91** [comment] 2022-02-20 22:20
Duplicate of #3205

**Closed** 2022-02-20 22:22 UTC
Labels: duplicate
