### ISSUE TITLE
Chat Influence Highlighter - A border highlight showing how far you can read chat messages

### ISSUE THREAD

**Issue by ElusiveEllie** [runelite/runelite#13832] opened 2021-07-03 21:33 UTC
Sometimes when you're skilling, you like to talk to the people around you to pass the time. But some skills, like fishing and woodcutting, make you run out of the chat range of those around you. There's no visible way to tell how far you can chat with someone, and players are still rendered a few tiles out of your chat range, even though you can't hear them. It can get a little frustrating when you're in a conversation with two people and you move to another tree, and realize you've missed half of the conversation.

A small highlight, one which the player can change the color and opacity of to suit their needs, around the player's range of influence, would completely solve this problem. You would never be confused if you're missing messages or if that person is just not typing anything. I've done some experiments and found that the chat range is a 17x17 square centered on the player, so it would be a very simple idea to implement.

I've tried messing around with Tile Indicators and True Tile Locations to mimic this feature, but the window size makes it too variable to apply to everyone. There could be two or more types of highlights, one being a small line surrounding your chat influence area, and one highlighting the entire area, and maybe more options depending on the player's taste. 

https://i.imgur.com/Ld65qO1.png Example made using tile markers. Only the outer border needs to be highlighted, not the entire tile of the border pieces. The brown-clothed individual outside of the border is outside the range of chat influence and cannot be heard.

**Comment by Bram91** [comment] 2021-07-03 21:43
Duplicate of #10423.

**Comment by geheur** [comment] 2021-07-03 21:46
One thing that could be less obnoxious than a giant tile indicator is, when you say a message, temporarily pop up a message, or other indicator, over the heads of every player who cannot hear your message. That way, it isn't present all the time.

**Closed by geheur** 2021-07-03 21:46 UTC
