### ISSUE TITLE
World Map

### ISSUE THREAD

**Issue by Toplii** [runelite/runelite#2978] opened 2018-05-19 21:56 UTC
Is it possible to set it where esc button would close the vanilla client map and be able to switch the order so you could left click to open instanced map.

**Comment by Nightfirecat** [comment] 2018-05-19 23:01
Closing the map with ESC is a duplicate of #2250.

**Comment by deathbeam** [comment] 2018-05-19 23:04
For both requests there are issues open already.

**Closed by deathbeam** 2018-05-19 23:04 UTC
