### ISSUE TITLE
RS 2010 - 2011 Orbs on right side

### ISSUE THREAD

**Issue by lugia00** [runelite/runelite#9163] opened 2019-06-20 20:24 UTC
If this is possible, that would be great!

**Comment by Hydrox6** [comment] 2019-06-20 20:33
A picture example would be great

**Comment by lugia00** [comment] 2019-06-20 21:10
https://imgur.com/a/uk1yL58 like the orbs.

**Comment by lugia00** [comment] 2019-07-02 19:10
Any updates on this? :)

**Comment by Hydrox6** [comment] 2021-04-28 11:36
Duplicate of #11152

**Closed by Hydrox6** 2021-04-28 11:36 UTC
Labels: feature-request
