### ISSUE TITLE
Different draw distances for overworld and underground?

### ISSUE THREAD

**Issue by DelVision** [runelite/runelite#14119] opened 2021-09-10 22:09 UTC
- **Is your feature request related to a problem? Please describe.**

Underground areas in runescape have been designed for you to only see 25 tiles, while overworld isn't. So by having draw distance over 25 tiles you constantly see very broken looking walls of other dungeons near you, which I personally find really annoying.

- **Describe the solution you'd like**

Different draw distance option for underground and Runescape Surface under GPU plugin

- **Additional context**

I just like more immersive experience when I'm underground or doing quests that also take you to the underground locations so I'd love to have option to have shorter draw distance in those places and just enjoy the long draw distance on the surface map where it benefits for you to see further.

**Comment by raiyni** [comment] 2021-09-10 22:12
Duplicate of https://github.com/runelite/runelite/issues/6478

**Closed by raiyni** 2021-09-10 22:12 UTC
