### ISSUE TITLE
Slayer Points not updated after spending points

### ISSUE THREAD

**Issue by danxgh10** [runelite/runelite#9400] opened 2019-07-19 00:39 UTC
When you spend slayer points on skipping a task, the info box for slayer doesn't update your points. I assume it's the same for spending points on other things but have not checked.

**Comment by Serpa88** [comment] 2019-07-22 03:47
I was unable to reproduce the issue, I have tried cancelling my task, but it updated my points properly.
Please include better steps on how to reproduce the issue, if you have anything else to add.
Just for reference the important way the points are updated are when the rewards window is open or after you finish a task. This means after you cancel a task your points are updated in the next game tick as long as the rewards window is still open.

**Comment by Adam-** [comment] 2023-02-26 02:46
fixed in 1f6ae893d732cf3a022fe6d9662cd2a42ff2b217

**Closed by Adam-** 2023-02-26 02:46 UTC
Labels: bug
