### ISSUE TITLE
Suggestion: Show what world cannon was placed on mouse hover of cannon indicator

### ISSUE THREAD

**Issue by MitchWeaver** [runelite/runelite#4232] opened 2018-07-08 12:58 UTC
Title.

Example: If hopping around worlds or reopening client after setting down cannon, there is currently no way of knowing which world it was. This would prevent players from having to wait til it decays and talk to the dwarf.

**Comment by deathbeam** [comment] 2018-07-08 13:01
Duplicate of #3700

**Closed by deathbeam** 2018-07-08 13:01 UTC
