### ISSUE TITLE
Waypoint in default Runelite

### ISSUE THREAD

**Issue by Eliofx92** [runelite/runelite#11446] opened 2020-05-03 11:43 UTC
Would it be possible for a waypoint system to be in the default runelite and not as an external plugin. The one in the hub isn't that great and personally I would like to see a waypoint system like the one in tutorial island

![minimap](https://user-images.githubusercontent.com/63731741/80913275-61b41480-8d3b-11ea-818c-4f54cbb85b9a.png)

https://youtu.be/8ZoJuVbL1cU

**Comment by Hydrox6** [comment] 2020-05-03 11:45
Duplicate of #4496

**Closed by Hydrox6** 2020-05-03 11:45 UTC
