### ISSUE TITLE
Slayer Plugin: NPC Respawn Timer

### ISSUE THREAD

**Issue by HuntMiller** [runelite/runelite#14553] opened 2022-01-04 18:47 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently, the NPC Indicator Plugin contains code that allows respawn timers to be rendered for tagged NPC's upon death. It would be nice for that same functionality to exist within the Slayer Plugin, so that you could optionally display respawn timers for killed slayer mobs.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Hydrox6** [comment] 2022-01-04 18:48
Duplicate of #3730

**Closed by Hydrox6** 2022-01-04 18:48 UTC
