### ISSUE TITLE
[Feature Request] Sort Plugins by type

### ISSUE THREAD

**Issue by yourkittenishungry** [runelite/runelite#3426] opened 2018-05-28 20:06 UTC
Looking at the Plugins list is a bit daunting, it would be easier if the list was or could be sorted by type. Something like this:

Barrows Brothers,Activity
Clue Scroll,Activity
Fight Cave,Activity
Kingdom of Miscellania,Activity
Kourend Library,Activity
Motherlode Mine,Activity
Puzzle Solver,Activity
Rogue’s Den,Activity
Boss Timers,Boss
Cerberus,Boss
Chambers Of Xeric,Boss
Attack Styles,Combat
Boosts Information,Combat
Cannon,Combat
Combat Level,Combat
Opponent Information,Combat
Prayer Flicking,Combat
Slayer,Combat
Special attack Counter,Combat
Camera Zoom,Game Interface
Chat Commands,Game Interface
Chat History,Game Interface
Clan Chat,Game Interface
Entity Hider,Game Interface
Examine,Game Interface
Fairy Ring Helper,Game Interface
Friend Notes,Game Interface
Instance Map,Game Interface
Interface Styles,Game Interface
Jewellery Count,Game Interface
Menu Entry Swapper,Game Interface
Minimap,Game Interface
Mouse Tooltips,Game Interface
NPC Indicators,Game Interface
Player Indicators,Game Interface
Regeneration Meter,Game Interface
Reorder Prayers,Game Interface
Report Button,Game Interface
Rune Pouch,Game Interface
Screen Markers,Game Interface
Shift anti Drag,Game Interface
Team Capes,Game Interface
Tile Indicators,Game Interface
World Map,Game Interface
XP Drop,Game Interface
XP Globes,Game Interface
Bank Tags,Items
Bank Value,Items
Grand Exchange,Items
Ground Items,Items
Ground Markers,Items
Item Prices,Items
Item Stats,Items
Barbarian Assault,Minigame
Blast Furnace,Minigame
Nightmare Zone,Minigame
Pest Control,Minigame
Tithe Farm,Minigame
Account,Runelite
Animation Smoothing,Runelite
Default World,Runelite
FPS Control,Runelite
Idle Notifier,Runelite
Low Detail,Runelite
RuneLite,Runelite
Screenshot,Runelite
Stretched Fixed Mode,Runelite
Username Syncer,Runelite
Agility,Skills
Fishing,Skills
Herbiboar,Skills
Hunter,Skills
Implings,Skills
Player-owned House,Skills
Runecraft,Skills
Woodcutting,Skills
Daily Task Indicator,Tools
Discord,Tools
Farming Tracker,Tools
HiScore,Tools
Info Panel,Tools
Metronome,Tools
News Feed,Tools
Notes,Tools
Skill Calculator,Tools
Timers,Tools
XP Tracker,Tools

**Comment by jplsek** [comment] 2018-05-28 20:13
Duplicate of #2411

**Closed** 2018-05-28 20:14 UTC
