### ISSUE TITLE
Slayer plug-in: Highlight South west tile of the task monster.

### ISSUE THREAD

**Issue by ReinierAarnink1996** [runelite/runelite#12185] opened 2020-07-18 12:06 UTC
****Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]**
No. An improvement suggestion. I'm talking about the Slayer plug-in. With slayer a cannon is most often used and it is very handy to know which South west tile the NPC is standing on.

I pretty much always use a cannon and its annoying to type in the name of the monster at npc indicator whenever I get a new monster.. sometimes I have too many monsters highlighted aswell it makes my gameplay experience less.. beautiful... so I also remove names off the list.

****Describe the solution you'd like**
A clear and concise description of what you want to happen.**
When a monster is on a certain tile then the cannon can double hit the monster. For this it's important to highlight the South west tile of the monster. Just a check box where you can switch this on and off, the same way as it is with NPC indicator.

Please also add "highlight a tile" (see npc indicator plug-in, the same way as there). This doesn't only highlight the South-west tile, but more than that. This is useful to know whether it is a big or small monster. A small monster uses 1 tile. A big one more than 1 tile. A big more can be killed with a Halberd and a small monster not. Useful for example at Bloodvelds gnome dungeon or identifying new slayer monsters...

Please also add respawn timer. And also hide death NPC's in menu; when I blood barrage Dust Devils I right click and see Dust Devils that I just barraged to death aswell.. if I click those then I miss 1 barrage.. there is no way of telling which one is dead as they are all stacked together on top of eachother if you know how blood barraging works.

****Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.**
This can be done via NPC Indicator but not with the Slayer plug-in. Right now with NPC Indicator you can highlight NPC that you wish and the Slayer plug-in Highlights the monsters of your current task.. so they both highlight. So why not add the option under the Slayer plug-in to "Highlight south west tile" as this is very handy when using a cannon.

**Comment by Nightfirecat** [comment] 2020-07-18 16:39
Duplicate of #4606

**Closed by Nightfirecat** 2020-07-18 16:39 UTC
Labels: duplicate
