### ISSUE TITLE
Add timer/countdown stopwatch with sound.

### ISSUE THREAD

**Issue by holydeltawings** [runelite/runelite#3270] opened 2018-05-25 00:46 UTC
Adding a simple timer/countdown that can be set would be useful tool in many aspects in and out of the game.

Some options would be repeatable time that once set say to 5 minutes would count down and chime once time is up and repeat. This feature could be turned on or off for a single timer use. The OSB timer is nice but lacks a chime sound which could be toggled as well as a repeating timer out countdown.

**Comment by Infinitay** [comment] 2018-05-25 00:48
Duplicate of #1612 and #1686

**Closed** 2018-05-25 05:46 UTC
