### ISSUE TITLE
Attackable players

### ISSUE THREAD

**Issue by Jmac191** [runelite/runelite#5056] opened 2018-08-22 13:20 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

I'd like there to be an "attackable players" option for the wilderness if possible. So if me and someone else was 1 level apart or X levels (My level 100 and his 101) in level 30 it would have a green circle inside of the current box at his feet showing that we're safe from each others attacks and in level 31 it would have a red circle to show we're able to attack each other. It could be in Player Indicators for something like "Highlight attackable players" or something of the sorts with a custom color option for both "attackable" and "safe".

**Additional context**

https://imgur.com/npgB577

**Comment by ShaunDreclin** [comment] 2018-08-22 15:39
One suggestion per issue, please.

**Comment by deathbeam** [comment] 2018-08-25 09:53
This seems quite OP when in wilderness as it would basically tell you that some player can attack you so you will just hop/leave

**Comment by deathbeam** [comment] 2018-08-25 09:55
Also duplicate of #512 looks like

**Closed by deathbeam** 2018-08-25 09:55 UTC
Labels: feature-request

**Comment by Jmac191** [comment] 2018-08-26 00:04
Ah, I looked for "attackable players" and "attackable" but didn't see it on there. I guess since the name was player indicators instead of attackable players I didn't see it. I shoulda looked up player indicators also my bad lol. So I reckon this is a no go at the moment? Thanks for the info bro
