### ISSUE TITLE
No sound at all

### ISSUE THREAD

**Issue by drumsetmonkey** [runelite/runelite#7793] opened 2019-02-10 20:52 UTC
RuneLite version: 1.5.11
RuneLite launcher version: 1.6.1
OS: Void Linux 
Kernel version: 4.19.17

RuneLite doesn't output any audio, and upon further inspection, it doesn't show up at all in `pavucontrol` either. I've tried running the jar using: `java -jar RuneLite.jar --debug` and that doesn't seem to show anything being wrong.

I've also tried using Java versions 8 and 9 and still haven't had any luck.

I was told this was maybe a problem with `alsa-lib` version 1.1.7 or later, so I tried downgrading to 1.1.6_1, but still, RuneLite doesn't seem to be connecting to Pulseaudio at all.

I should also add that my game is not in low detail mode.

**Comment by deathbeam** [comment] 2019-02-10 20:53
Possibly duplicate of #3525

**Closed by deathbeam** 2019-02-10 20:53 UTC

**Comment by drumsetmonkey** [comment] 2019-02-10 21:15
Okay I figured it out,
I had my `.asoundrc` configured to allow ALSA to bridge into Pulseaudio (which is all the `pulseaudio-alsa` package provides anyways)

Where the issue came was in converting the audio to a higher bitrate. Inside my `pcm.!default` section I had the following
```
pcm.!default {
  type pulse
  fallback "sysdefault"
  rate_converter "speexrate_best"
  hint {
    show on
    description "Default ALSA Output (currently PulseAudio Sound Server)"
  }

  slave {
    pcm "hw:0,0"
    #period_time 0
    period_size 1028
    buffer_size 4096
    buffer_time 0
    periods 128
    format S24_LE
    rate 192000
    channels 2
  }
  bindings {
    0 0
    1 1
  }
}
```
It appears that the issue had to do with me either changing the bitrate, bit depth, or just converting it in the first place. 

I found that by removing all of the entries that had to do with changing audio quality Runelite started outputting audio!
