### ISSUE TITLE
Simple inventory tracker

### ISSUE THREAD

**Issue by strifeII** [runelite/runelite#10848] opened 2020-02-22 11:58 UTC
When doing PvM runs, the current loot tab doesn't take into account what you spend in consumables to get said loot, just the overall value of drops.

While a full tracker inc. bolts/scales etc would be useful I guess the coding would be difficult and complex.

A simple option to record GE value of inventory when you dump into the RuneScape GE value estimator screen, then a small inbuilt calculator to calculate the difference between inventories each time you do that, would give a fairly good indication of profit/loss after each trip, although not 100% accurate.

The ideal would include all consumables inc. equipped, barrows repairs, zulrahs scales, bolts, crystal charges etc, but that could be difficult.

**Comment by TheStonedTurtle** [comment] 2020-02-22 12:46
I believe what you want exists on the plugin hub as the ![Supplies Tracker](https://github.com/Dyldozer/SuppliesTrackerExternal), which records what supplies you've used.

**Comment by Hydrox6** [comment] 2020-02-22 12:47
Duplicate of #6700
A plugin like this is available in the Plugin Hub

**Closed by Hydrox6** 2020-02-22 12:47 UTC
