### ISSUE TITLE
Add-on to current "time tracking" plugin

### ISSUE THREAD

**Issue by joshmarksman** [runelite/runelite#14012] opened 2021-08-11 18:18 UTC
I like to stay in other tabs but am forced to watch when my next run is coming up.

Can we get something like what is in the "XP Tracker" and a "Add to canvas" feature.

I know some would love this for the more afk skills its easier to follow.

The notification currently doesn't work for me because I have desktop notifications off due to it interfering with my interface when I am bossing and what not.

**Comment by Nightfirecat** [comment] 2021-08-11 18:19
Duplicate of #8500

**Closed by Nightfirecat** 2021-08-11 18:19 UTC
Labels: duplicate
