### ISSUE TITLE
Add wintertodt drops to the loot tracker

### ISSUE THREAD

**Issue by gracetbh** [runelite/runelite#11315] opened 2020-04-19 02:08 UTC
**Is your feature request related to a problem? Please describe.**
While at Wintertodt it would be nice to see your crate loot displayed in the loot tab.

**Describe the solution you'd like**
With each wintertodt kill it displays the loot you've gained from it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dekvall** [comment] 2020-04-19 02:10
Duplicate of #5824

**Closed by dekvall** 2020-04-19 02:10 UTC
