### ISSUE TITLE
Skybox colors the ground below vorkath

### ISSUE THREAD

**Issue by 15987632** [runelite/runelite#7226] opened 2019-01-07 23:00 UTC
https://streamable.com/84cay

**Comment by Adam-** [comment] 2019-01-07 23:40
I think this is just #1481

**Comment by 15987632** [comment] 2019-01-07 23:40
I am not on low detail mode

**Comment by 15987632** [comment] 2019-01-07 23:53
this is what it looks like in low detail mode https://streamable.com/8o37w

**Comment by Abextm** [comment] 2019-01-08 01:08
I'm assuming that this is because whatever is under Vorkath is transparent, so I doubt we can fix this

**Comment by 15987632** [comment] 2019-01-08 03:13
Probably a stupid idea but how would it look if you made the skybox in that area the same color as the ground it replaced. The blue doesn't look terrible but will probably be too dark to look nice in the area.

**Comment by deathbeam** [comment] 2019-02-07 11:26
Duplicate of #7250 (lets keep this in 1 issue)

**Closed by deathbeam** 2019-02-07 11:26 UTC
Labels: bug, skybox
