### ISSUE TITLE
1.4.0 broken barrows screenshots

### ISSUE THREAD

**Issue by EatSleepSlay** [runelite/runelite#3260] opened 2018-05-24 22:36 UTC
As the title says, 1.3.9 was taking chest screenshots just fine.

Now with 1.4.0 the screenshots seem broken!

Otherwise, love the new UI it's smexy!

**Comment by nickwigton** [comment] 2018-05-24 22:38
When you say they seem broken, do you mean that it's failing to take screenshots at all?

**Comment by nickwigton** [comment] 2018-05-25 01:10
Did a Barrows run, screenshot was taken automatically just fine running client 1.4.1:
https://imgur.com/hX0rcGF

**Comment by Nightfirecat** [comment] 2018-05-25 01:40
I also did a Barrows run today and got an automatic screenshot just fine.

**Comment by EatSleepSlay** [comment] 2018-05-25 04:48
Hmm, must just be me? I've dont about 10 before work and none have screenshots.

Have the option enabled.

**Comment by EatSleepSlay** [comment] 2018-05-25 04:50
I have also done a crap load of quests, over the past few weeks and no screenshots of them either

**Comment by EatSleepSlay** [comment] 2018-05-25 05:11
Okay so I just got an item and it didn't grab that screenshot of it.

It did grab the last however. Got 236, skipped 237 (ahrims hood).

**Comment by deathbeam** [comment] 2018-05-25 05:47
Duplicate of #2114

**Closed by deathbeam** 2018-05-25 05:47 UTC
