### ISSUE TITLE
Don't show "Daily Task Indicator" while on tutorial island.

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#3092] opened 2018-05-21 23:05 UTC
You can't possibly have access to these dailies yet if you're on tutorial island. (F2P account BTW)
![Image](https://vgy.me/iRkYUA.png)
![Image2](https://vgy.me/78k4Du.png)

**Comment by Infinitay** [comment] 2018-05-21 23:07
#1129 just waiting on another PR that fixes the event issue and to delay it

**Comment by deathbeam** [comment] 2018-05-22 06:27
Duplicate of #2337

**Closed by deathbeam** 2018-05-22 06:27 UTC
