### ISSUE TITLE
Reverse order of ground item prioritization

### ISSUE THREAD

**Issue by eX-C0n** [runelite/runelite#8141] opened 2019-03-07 18:28 UTC
Change the prioritization currently as:
Highlight specific > Block Specific > Highlight Wildcard > Block Wildcard

use-case:    I have "Dragon *" in my Highlighted Items, thus allowing and dragon items to highlight. It also highlights Dragon Bones, as it fits the wildcard. Putting "Dragon Bones" or " *bones " in Hidden Items, does nothing

**Comment by deathbeam** [comment] 2019-03-07 18:30
Basically duplicate of #3942

**Closed by deathbeam** 2019-03-07 18:30 UTC
