### ISSUE TITLE
PMod tools

### ISSUE THREAD

**Issue by OSRSBotKiller** [runelite/runelite#13048] opened 2021-01-13 15:59 UTC
Can you please implement better tools for pmods for surveillance and monitoring players?

Maybe something that highlights players ingame and the minimap

I have contacted Jagex to do it themselves but they are not interested. Please add this as I am on a mission to remove all bots as its ruining our game

**Comment by OSRSBotKiller** [comment] 2021-01-13 16:04
I am also thinking of making a database of users who are bots that are manually inspected by trusted members. We could attach it to runelite so other users are aware and maybe report them again

please keep this movement alive we need to stop the bots and provide better tools for the pmods

**Comment by Hydrox6** [comment] 2021-01-13 16:06
Given that this is so generic and non-actionable...
Duplicate of #11484
Duplicate of #12245
Duplicate of #12331

What you probably want is to make a system like RuneWatch, but for bots, which sounds like trying to empty a desert with a fork.

You're best off asking Jagex for a better system; PMods can barely do anything as is, and nothing we do can reasonably affect this.

**Closed by Hydrox6** 2021-01-13 16:06 UTC

**Comment by OSRSBotKiller** [comment] 2021-01-13 16:08
> What you probably want is to make a system like RuneWatch, but for bots, which sounds like trying to empty a desert with a fork.

THIS IS EXACTLY WHAT I AM TRYING TO DO.

Why is this a bad idea? We can all agree that bots are ruining the game we love.

**Comment by Hydrox6** [comment] 2021-01-13 16:09
This is a RuneScape client, not a general request forum for external software.

**Comment by OSRSBotKiller** [comment] 2021-01-13 16:09
Maybe in a few years we could even use AI to identify these bots

**Comment by OSRSBotKiller** [comment] 2021-01-13 16:12
> This is a RuneScape client, not a general request forum for external software.

I am a pmod and its been stated many times that most jagex staff use Runelite. Adam can be in control of making sure the blacklist is legitimate. I know he is not corrupt.

**Comment by LlemonDuck** [comment] 2021-01-13 16:14
Adam in discord
> the reason its out of scope is the project isn't meant to cleanup the game. mostly since thats jagex's job
and because we cant do it

It's not gonna happen, issue's closed and will stay that way

**Comment by OSRSBotKiller** [comment] 2021-01-13 16:14
https://old.reddit.com/r/2007scape/comments/k8fsj0/steam_beta_announcement/gexq7bx/?context=3
