### ISSUE TITLE
Heavy RAM Usage on rooftop courses

### ISSUE THREAD

**Issue by Jschellenbach** [runelite/runelite#9951] opened 2019-10-01 03:30 UTC
After a few minutes of training agility at the rooftop courses, my RAM usage skyrockets to 11-13gb. I have 16gb of RAM. Anyone know of a fix? Cheers

**Comment by Darkkgreen** [comment] 2019-10-02 02:40
Provide more info. Which courses, maybe logs?

**Comment by nugget2020** [comment] 2019-10-03 14:09
i have the same issue, not just on rooftops though. with gpu plugin enabled it can randomly jump from 500mb ram usage to 4.5-8gb, and as soon as i disable gpu it drops back down instantly. 

have 16gb ram and an amd rx 5700xt

using most up to date version of RL

**Comment by NorbertasL** [comment] 2019-10-14 14:49
I can confirm this with rooftops(Varrock and Canifis). It starts happening after 20-30min. Restarting the client seems to solve it for 20-30min :).

**Comment by Adam-** [comment] 2019-10-14 14:50
This could be related to bdd9feb3ea5825d267e97876b5c9ff0c2ca2a461 - do any of you have item charges infoboxes on?

**Comment by NorbertasL** [comment] 2019-10-14 16:03
> This could be related to [bdd9feb](https://github.com/runelite/runelite/commit/bdd9feb3ea5825d267e97876b5c9ff0c2ca2a461) - do any of you have item charges infoboxes on?

I have that on, but I have nothing equip and nothing in my inventory(Except Marks of Grace), so this should not couse the leak.I will test it with it off to make sure)

**Comment by sargeantPig** [comment] 2020-01-10 15:23
Same issue as the above posters. Extremely high memory usage (4-6Gb) when using the gpu plugin, seems to occur once you zoom out and also only seems to happen on rooftop courses.

When gpu is off it's fine.

**Comment by Nightfirecat** [comment] 2022-07-10 04:02
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:02 UTC
Labels: bug, needs-information, gpu
