### ISSUE TITLE
highlight the ladder to upper level in MLM

### ISSUE THREAD

**Issue by 8bitslacker** [runelite/runelite#10061] opened 2019-10-14 14:14 UTC
**Is your feature request related to a problem? Please describe.**
I suck at clicking objects that are hard to click like the ladder going up to MLM upper level. Ladders are usually troublesome because I always want to click in the middle.

**Describe the solution you'd like**
I like how you highlight agility obstacles in green, maybe you could do the click box of the ladder in green? If it's too much of an issue, no worries. 

**Describe alternatives you've considered**
No alternative, if it's too much of an issue don't worry about it

**Additional context**
[This is the ladder I'm talking about](https://i.imgur.com/2Rhk8xr.png)

**Comment by Hydrox6** [comment] 2019-10-14 14:15
Duplicate of #9860

**Closed by Hydrox6** 2019-10-14 14:15 UTC
