### ISSUE TITLE
Client resolution issue

### ISSUE THREAD

**Issue by legitstitch** [runelite/runelite#11632] opened 2020-05-17 07:53 UTC
I've been having issues with my runelite window's resolution. When I click to expand the size of the window to full screen, it doesn't cover my entire screen. Also the game is in an even smaller box in the window (shown in screenshot). Also, the black bars surrounding the game screen will allow the green runelite click-boxes to show through and duplicate. (also shown). I am using the latest version of the client and have downloaded it fresh multiple times.

i am on windows 10

![RL Prob](https://user-images.githubusercontent.com/40655734/82138903-33294580-97e1-11ea-945f-ae4f83db32b4.PNG)

**Comment by legitstitch** [comment] 2020-05-17 08:05
please help me.

**Comment by Nightfirecat** [comment] 2020-05-17 08:07
What are your client and launcher versions? (found in the info tab) What are your GPU plugin settings? What operating system are you running?

**Comment by legitstitch** [comment] 2020-05-17 08:17
RuneLite verison 1.6.15
OSRS version Rev 189
launcher version 2.1.0

GPU: Screenshot
![Capture](https://user-images.githubusercontent.com/40655734/82139330-35d96a00-97e4-11ea-840d-46ecf7944275.PNG)

Im running windows 10

Turning off anti-aliasing seems to fix the large black bars, but i cant seem to fix the issue where pressing the maximize button in the top right doesn't make the window fill my screen as usual. On top of this my framerate is really low, it fluctuates from 15 to 30 fps.

I have a ryzen 7 1700X and a gtx 1080 along with a 1440p monitor.

**Comment by Xortrox** [comment] 2020-05-17 13:08
Maybe it's related, I sometimes use a weird resolution to run 2x3 runelites in a grid, so I have like 2305x1305 monitor virtually, if I maximize runelite on that monitor it only maximizes as if it's 1080p (I don't get the black bars tho)

**Comment by Alexsuperfly** [comment] 2020-05-17 13:18
disable dpi scaling in your os

**Comment by legitstitch** [comment] 2020-05-17 18:05
I tried tweaking all of the dpi scaling options under compatibility quite a bit already. Also it seems that it is opening in 1080p which is why it wont fill the screen. I would really like it to fill my screen. Also I did manage to fix the black bars on the side, just need help figuring out how to maximize the window.

**Comment by legitstitch** [comment] 2020-05-17 18:09
I just measured the window size when it maximizes, it seems to be just a bit smaller than 1600x900 in resolution when maximized. Quite a bit smaller than 1080p

**Comment by Nightfirecat** [comment] 2020-05-17 18:12
Are you opening RuneLite on a second monitor? What is the resolution of your monitor(s)?

**Comment by tre3tre** [comment] 2020-07-16 17:30
Did you happen to find a solution? I'm having this problem now.

**Comment by Runemoro** [comment] 2020-09-16 18:50
The same bug is happening to me too. Turning off the "Enable custom window chrome" option in RuneLite's window options fixes it.

The bug seems to be caused by Substance: https://github.com/kirill-grouchnikov/radiance/issues/264
It was fixed in this PR: https://github.com/kirill-grouchnikov/radiance/pull/243

**Comment by Nightfirecat** [comment] 2021-01-12 07:44
From [Adam's comment](https://github.com/runelite/runelite/pull/12501#issuecomment-695153788), this should be fixed as of f7606c7

**Closed by Nightfirecat** 2021-01-12 07:44 UTC
Labels: needs-information
