### ISSUE TITLE
Idle Notifier Inconsistent Behavior

### ISSUE THREAD

**Issue by dpedu** [runelite/runelite#9761] opened 2019-08-29 00:38 UTC
On macOs 10.14, whenever the Idle Notifier plugin sends a notification, the RuneLite window jumps to the foreground. E.g. if I was using a different application, RuneLite jumps in front of it as if I had command-tabbed to it.

On windows 10, RuneLite is not brought to the foreground when it sends a notification.

These behaviors should be consistent. 

Ideally, this behavior should be a toggle option in the plugin. Personally, I'm a fan of it jumping to the front.

**Comment by Alexsuperfly** [comment] 2019-08-29 00:40
duplicate of #2335

**Closed** 2019-08-29 06:01 UTC
Labels: duplicate
