### ISSUE TITLE
Create a full screen login screen background like the mobile app has

### ISSUE THREAD

**Issue by Millc** [runelite/runelite#8739] opened 2019-05-03 13:25 UTC
Currently, the login screen is very small. I think that it would be nice if the login screen would fit the whole window, so that the black regions are gone.

Maybe something like this could be implemented;
![login](https://user-images.githubusercontent.com/21034060/57140132-51c7c480-6db7-11e9-9fb3-cb15b025bf17.png)

In my opinion, this would be a good solution to tackle #7605

Thanks to Reddit user "daydreams-xiaoqiang" for the image.

**Comment by ShaunDreclin** [comment] 2019-05-03 19:04
I doubt we'll get something like this given Adam's comment on the issue you linked, but maybe the stretched mode plugin could be set up to stretch the login screen independently from the rest of the game?

**Comment by Millc** [comment] 2019-05-13 19:59
> plugin could be set up to stretch the login screen independently from the rest of

Yeah, why not? If this doesn't result in bad quality because of the stretching, I'm in! 👍

**Comment by Alexsuperfly** [comment] 2019-07-28 20:46
duplicate of #7605

**Closed** 2019-08-12 16:17 UTC
Labels: feature-request
