### ISSUE TITLE
No metronome sound! :(

### ISSUE THREAD

**Issue by Toahsty** [runelite/runelite#13615] opened 2021-05-19 15:47 UTC
The built-in metronome plugin is not working, it hasn't worked since the most recent clan update.
No matter what I do the tick/tock sound doesn't work, I've tried restarting my client and even tried using another metronome plugin and that one doesn't even work, really need the metronome to do inferno lol

**Comment by Hydrox6** [comment] 2021-05-19 15:52
Duplicate of #13613

**Closed by Hydrox6** 2021-05-19 15:52 UTC
