### ISSUE TITLE
Compute Shaders broken on macOS

### ISSUE THREAD

**Issue by FromDarkHell** [runelite/runelite#17324] opened 2023-12-31 17:19 UTC
### Type

GPU

### Operating System

MacOS

### OS Version

Sonoma 14.2.1

### Bug description

Enabling computer shaders causes the GPU plugin to error/disable itself on 1.10.18 (was fine on 1.10.17).

### RuneLite version

RuneLite: 1.10.18
Launcher: 2.6.12

### Logs

[client.log](https://github.com/runelite/runelite/files/13801783/client.log)
[launcher.log](https://github.com/runelite/runelite/files/13801784/launcher.log)

**Comment by Boudewijnvs** [comment] 2023-12-31 18:23
<img width="236" alt="Screenshot 2023-12-31 at 19 18 35" src="https://github.com/runelite/runelite/assets/9085931/9c2f82c8-2069-4360-b950-62f00fe665b5">

Adding to this, on macOS when the GPU-plugin is enabled with Compute Shaders on, certain actions/animations like teleporting or campfires have black shaders showing for a single animation frame.

**Comment by Adam-** [comment] 2023-12-31 18:48
> <img alt="Screenshot 2023-12-31 at 19 18 35" width="236" src="https://private-user-images.githubusercontent.com/9085931/293518693-9c2f82c8-2069-4360-b950-62f00fe665b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNDczMDcsIm5iZiI6MTcwNDA0NzAwNywicGF0aCI6Ii85MDg1OTMxLzI5MzUxODY5My05YzJmODJjOC0yMDY5LTQzNjAtYjk1MC02MmYwMGZlNjY1YjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzFUMTgyMzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGIzMmM2YjQwOWQ2OWExMTFkNzQ5NTI0Y2VjMGJhYTE1NzY2NTRlZWFhNGJmNWQzZjUzYTYyMmY0ZTk1OWNhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LSUBUuwloZkQMOFa1SCfRsJ9y-kNB1MFzmrcatRQsGM">
> 
> Adding to this, on macOS when the GPU-plugin is enabled with Compute Shaders on, certain actions/animations like teleporting or campfires have black shaders showing for a single animation frame.

Do you have any more details about this? macos version? gpu version? I don't see it happening on either of my systems.

**Comment by Boudewijnvs** [comment] 2023-12-31 19:39
MacOS version: 14.2.1
Macbook Pro M2 (13.3 inch)

Runelite version: 1.10.18


Any teleport from the normal spellbook gives the following black shaders:
<img width="715" alt="Screenshot 2023-12-31 at 20 37 42" src="https://github.com/runelite/runelite/assets/9085931/eafc4801-17a7-4615-9c3b-b176218db95f">

**Comment by Adam-** [comment] 2023-12-31 19:46
This issue is fixed in 7935a7615ce3fc6aa668e78416997e3fec88223f. I don't know about the black shadows thing, me and also another person I asked to test it cannot reproduce it between 3 different test systems.

**Closed by Adam-** 2023-12-31 19:46 UTC
Labels: bug, regression, gpu, platform:macos
