### ISSUE TITLE
Skybox issue

### ISSUE THREAD

**Issue by lutrom121** [runelite/runelite#9062] opened 2019-06-08 10:35 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Visual bug.
Varrock west bank cellar staircase entrance is blue when skyboxes are turned on.

**To Reproduce**
1. Go to configuration
2. Click on skybox
3. Scroll down to ???
4. See error!

**Expected behavior**
I am expecting not to have darkness of the cellar represented as cyan.

**Screenshots**
![image](https://user-images.githubusercontent.com/51507376/59145827-7d0e8680-89e9-11e9-9d34-e023f37472d4.png)

**Environment (please complete the following information):**
 - OS:  Windows
 - RuneLite version: 1.5.25
 - Launcher version: Unknown

**Additional context**

**Comment by vardy** [comment] 2019-06-08 10:40
This isn't really a bug but a byproduct of how the skyboxes work by recolouring the unloaded areas - the cellar isn't painted black, it takes on the colour of an unloaded chunk which is now recoloured by the skybox.

**Comment by Unmoon** [comment] 2019-06-08 10:42
@vardy Rather, when rendering a frame, the frame is first filled by black (without skybox) or skybox color, and then everything is drawn on top of that. If something is missing (for example with the stairs here, or normally sky), it will remain the same color.

**Comment by Unmoon** [comment] 2019-06-08 10:44
Duplicate of #7250

**Comment by vardy** [comment] 2019-06-08 10:47
> @vardy Rather, when rendering a frame, the frame is first filled by black (without skybox) or skybox color, and then everything is drawn on top of that. If something is missing (for example with the stairs here, or normally sky), it will remain the same color.

There we go, makes a lot of sense, thanks for explaining! :)

**Closed** 2019-06-08 11:24 UTC
