### ISSUE TITLE
A calculator.

### ISSUE THREAD

**Issue by Pingstery** [runelite/runelite#9865] opened 2019-09-14 16:19 UTC
Not having to open another window (a calculator) and having it within RuneLite would be a nice QoL update. 

Would be nice to have it in it's own separate tab on the right hand side menu, and ability to have multiple calculations at the same time, ie tabs within that tab. Sometimes you just gotta do some basic math without going through fancy skill calculators and stuff. 

Thanks

**Comment by Hydrox6** [comment] 2019-09-14 16:20
Duplicate of #3967

**Closed by Hydrox6** 2019-09-14 16:20 UTC
