### ISSUE TITLE
NPC Indicators "Ignore Dead NPCs" considering Nightmare a "dead" npc when shield drops

### ISSUE THREAD

**Issue by vitorebom** [runelite/runelite#15074] opened 2022-06-06 12:21 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

W10

### Bug description

I was doing some Nightmare yesterday and I noticed that the boss would no longer be highlighted after I dropped her shields to 0, the client would consider her a "dead" NPC and no longer highlight. I then tested it on Phosani and it also happened there.

**Comment by Nightfirecat** [comment] 2022-06-06 18:48
This is basically a duplicate of #12453--the NPC reaches 0 hp, but has other mechanics which prevent it from actually dying.

**Closed by Nightfirecat** 2022-06-06 18:48 UTC
Labels: duplicate
