### ISSUE TITLE
"Highlight marks of grace" doesnt work on bridges

### ISSUE THREAD

**Issue by Nithe** [runelite/runelite#1976] opened 2018-04-26 14:30 UTC
Ive only yet noticed 2 places on the varrock course where this is the case, but there might be more.
https://imgur.com/gallery/2WeC3as
https://imgur.com/gallery/HipEUI0 (idk if this is a bridge, but it doesnt work)

**Comment by samrobben** [comment] 2018-04-26 16:14
I'm working on a fix for this. Currently testing my fix.

**Comment by Adam-** [comment] 2018-04-29 15:09
Tried to reproduce this today and couldn't do it. Maybe it is unrelated to bridges.
https://cdn.discordapp.com/attachments/419891709883973642/440165992300150805/unknown.png

**Comment by Nithe** [comment] 2018-04-29 15:26
hmm yea it might be, i also have a problem with the ground item overlay is not showing once i a while

**Comment by Nightfirecat** [comment] 2018-08-01 04:26
This is unrelated to bridges, it's caused because of the issue described here: #4076

**Comment by Nightfirecat** [comment] 2018-09-06 07:17
This can be closed as duplicate

**Closed** 2018-09-06 19:59 UTC
Labels: bug, duplicate
