### ISSUE TITLE
Extension to MENU SWAPPER (enchanted jewelry TPs)

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#2477] opened 2018-05-08 15:07 UTC
Make it possible to left-click (selected TP) from the 'worn equipment' tab instead of 'Remove' or to shift-left-click
https://i.imgur.com/7xxKl6J.gif

**Comment by Nightfirecat** [comment] 2018-05-08 18:38
Duplicate of #2203?

**Closed** 2018-05-08 18:43 UTC
