### ISSUE TITLE
Camera Zoom Options

### ISSUE THREAD

**Issue by ptfo-rs** [runelite/runelite#4349] opened 2018-07-16 01:33 UTC
Ability to change camera zoom with ctrl+scroll wheel to zoom in/out without going into ingame settings.
Also a feature to reset zoom to default with ctrl+middle mouse button click.

**Comment by Abextm** [comment] 2018-07-16 01:34
Duplicate of #1124

**Closed by Abextm** 2018-07-16 01:34 UTC
