### ISSUE TITLE
GPU Issue

### ISSUE THREAD

**Issue by StuartGreenwood1** [runelite/runelite#12777] opened 2020-11-11 20:20 UTC
Blue and red tint to screen.

Was not having issue on previous builds.

![GPU Issue](https://user-images.githubusercontent.com/51379613/98860266-4bf67900-245b-11eb-9e7d-6b9153e619ac.png)

**Comment by benpoulson** [comment] 2020-11-11 20:20
What GPU settings do you have enabled?

**Comment by StuartGreenwood1** [comment] 2020-11-11 20:25
Reinstalled RuneLite and that's from clean install with the GPU toggle on, nothing extra. Even with RTSS turned off it's still displaying the above problem.

Tried a few other games and not a GPU problem on my end.

**Comment by Adam-** [comment] 2020-11-11 20:27
From what I've heard in Discord, this is specific to gpu+stretched mode, and changing the gpu's ui scaling mode can fix it.

**Comment by StuartGreenwood1** [comment] 2020-11-11 20:29
Without stretched mode enabled.

![GPU Issue 2](https://user-images.githubusercontent.com/51379613/98861106-a3e1af80-245c-11eb-9e55-ed090e993ac3.png)

**Comment by StuartGreenwood1** [comment] 2020-11-11 20:36
Yeah found the problem as mentioned above, "Nearest Neighbor" & "Bilinear" both have the issue. Any of the other UI scaling modes are fine, no problems.

**Comment by Nightfirecat** [comment] 2020-11-13 16:57
Duplicate of #12794

**Closed by Nightfirecat** 2020-11-13 16:57 UTC
Labels: duplicate
