### ISSUE TITLE
Feature Request: Filtering spam from private messages

### ISSUE THREAD

**Issue by gccltl** [runelite/runelite#3232] opened 2018-05-24 16:52 UTC
**Filtering spam messages (those would be recognized with keywords) from PMs** 

The user could write the keywords to filter out from private messages, or there could be the pre-determined list.
![capture](https://user-images.githubusercontent.com/28257966/40499821-efc7e028-5f37-11e8-919b-6e2b1844bd8b.PNG)

The filtering list could consist of:

- Every RSPS

- Every botting site (well not maybe every, but a majority)

- Discord Links & and other links

- etc

**Comment by vikke1234** [comment] 2018-05-24 23:34
out of curiosity, why don't you just have private friends on? so that noone but people on your friends list can message you?

**Comment by SoyChai** [comment] 2018-05-24 23:45
A *user-customized* chat filter is always an idea. I don't think a default blacklist would be practical, since adbots would simply adjust their messages and the list would be unreliable.

**Comment by christian-mann** [comment] 2018-05-25 03:54
@vikke1234 I like to have my private open to anyone, so that if someone from my clan or whatever wants to message me, then they can without having to get me to add them first.

**Comment by SoyChai** [comment] 2018-05-25 04:17
Makes sense. It sucks that public DMs are such a trainwreck in crowded places at the moment.

**Comment by isuckbtw** [comment] 2018-07-02 06:50
I'd love something like this, especially with options to import/export lists.

**Comment by deathbeam** [comment] 2018-08-05 10:00
Duplicate of #1798

**Closed by deathbeam** 2018-08-05 10:00 UTC
Labels: feature-request
