### ISSUE TITLE
Notification when "not fishing"

### ISSUE THREAD

**Issue by Zerk7** [runelite/runelite#5857] opened 2018-10-07 05:10 UTC
I'm suggesting a notification when you are not fishing. Currently the Idle Notification feature is being used to notify when my fishing spot has moved, but the issue is this notification is only set off when my character's fishing _animation_ is over, which ends 1-2 seconds after the character is actually _NOT_ fishing. 

For example: While fishing minnows, when the fishing spot moves a space over, your character remains in the fishing animation for 1-2 seconds even though it is not actually fishing anymore. 1-2 seconds may not seem like much, but by the time I receive the notification, the next fishing spot has already been nearly half-way depleted. 

Solution: When the Fishing sessions stats box is checked, the box on the top left corner will show when  your character is "NOT fishing." It changes from "Fishing" to "NOT fishing" about a tick before the fishing spot actually moves (_as it should_); I believe that adding a notification when the client detects that you're _actually_ NOT fishing would be better than the current method of waiting for the skilling animation to end in order to trigger the 0ms Idle Notification.

**Comment by Alexsuperfly** [comment] 2018-10-07 05:13
duplicate of #3910

**Closed** 2018-10-07 08:06 UTC
