### ISSUE TITLE
Custom/Fullscreen Login Screen

### ISSUE THREAD

**Issue by AildirMike** [runelite/runelite#9403] opened 2019-07-19 09:17 UTC
Would it be possible to change the background of the loading screen when you open the client? Also, would be nice if it went full-size in stretched mode. Don't know what the possibility of this is, but it would be a nice feature.

**Comment by Alexsuperfly** [comment] 2019-07-28 20:45
duplicate of #9082 and #7605

**Closed** 2019-07-29 00:37 UTC
Labels: duplicate
