### ISSUE TITLE
idle notifier customization 

### ISSUE THREAD

**Issue by Justin222111** [runelite/runelite#3002] opened 2018-05-20 07:03 UTC
I have found that i don't use the idle notifier, because for my it's a little too abrasive. i disabled tray notifications and flash notifications, and i still find that the inability to change the sound that plays as well as easily adjust the volume of the notification problematic. i used to use runeloader, and found that the i liked the sound that played as it felt less disruptive. 

so i'm proposing the idea that it be made possible to change the notification sound and perhaps the volume too. I can't think of other things to improve this feature atm, but I'm sure there are other ways it could be improved.

**Comment by deathbeam** [comment] 2018-05-20 08:29
Duplicate of #920

**Closed by deathbeam** 2018-05-20 08:29 UTC
