### ISSUE TITLE
Recolor the dirt on farming patches that have been treated with (ultra/super) compost

### ISSUE THREAD

**Issue by Ckmpls** [runelite/runelite#12111] opened 2020-07-11 07:55 UTC
A plugin that slightly recolors the dirt once treated with any type of compost so the player can visualize which patches have been or need to be treated. Currently, if you cant remember if you treated a patch or not, you have to click "inspect" and a message appears in the chat box that gives information including if it has been treated, which is kind of a pain in the ass when the leprechaun is on the other side of the farming area

**Describe the solution you'd like**
A slightly darker or more textured appearance to 

**Describe alternatives you've considered**
Orange/Green overlay similar to Tithe Farm

**Additional context**
Am I doing this right? and is this too picky? lol

**Comment by melkypie** [comment] 2020-07-13 05:46
Duplicate of #2472

**Closed by melkypie** 2020-07-13 05:46 UTC
