### ISSUE TITLE
Mage Arena Telekinetic room

### ISSUE THREAD

**Issue by Joneees** [runelite/runelite#7067] opened 2018-12-23 18:01 UTC
It keeps suggesting the old spot after the guardian has already moved. Not sure what's causing it but keeps happening regularly.

![image](https://user-images.githubusercontent.com/22350850/50386370-9054c080-06ed-11e9-891d-22bbd3459d96.png)

**Comment by Adam-** [comment] 2018-12-23 18:09
duplicate of #3946

**Closed by Adam-** 2018-12-23 18:09 UTC
