### ISSUE TITLE
Client occasionally crashes when teleporting - On Mac M1

### ISSUE THREAD

**Issue by JG955** [runelite/runelite#13814] opened 2021-06-30 21:33 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Character will get to the end of the teleport animation and then just before location changes the client freezes. Have to force quit client and restart. It only happens occasionally, but enough for me to report it. 

**To Reproduce**
Teleport to any location.. 

**Environment (please complete the following information):**
 - OS: [macOS - Apple M1 Chip]
 - RuneLite version: [e.g 1.7.14]
 - Launcher version: [e.g 2.1.0]

**Comment by dan-drews** [comment] 2021-07-01 15:30
This has been happening frequently to me as well for a while. I'm not at my computer so I can't provide full details, but I'm running Windows 10 on a 9900k, so it's likely not related to M1

For me, it's generally happened when I tele to Prif, but with the Shayzien re-work, I've had a few crashes while I'm in that area as well. My hunch is that it is related to heavy GPU areas being loaded.

**Comment by alexandrabush** [comment] 2021-07-11 02:08
This has happened to me 3 times now. I didn't notice at the time if it was happening when teleporting. The last time this happened I had just teleported to the farming guild and was about 10 seconds after I TP'd and started running to the shamans area. I'm running runelite on a MacBook 2017 with an m3 processor. I've attached the 3 crash reports in a zip here.

[Runelite Mac Crash Reports.zip](https://github.com/runelite/runelite/files/6796236/Runelite.Mac.Crash.Reports.zip)

**Comment by alexandrabush** [comment] 2021-07-11 02:13
I've had Mac client crashes 3 times now. I can't see any pattern with it. I commented this on another issue, but I'm posting here too in case they are related. The last time this happened I had just teleported to the farming guild and had started running to the shamans area. I've attached the 3 crash reports in a zip here.

Environment:
OS: macOS Mojave 10.14.6, 1.2 GHz Intel Core m3 
Runelite version: 1.7.15
Launcher version: 2.0.0

[Runelite Mac Crash Reports.zip](https://github.com/runelite/runelite/files/6796239/Runelite.Mac.Crash.Reports.zip)

**Comment by Stoddy15m** [comment] 2021-07-12 20:52
Sorry for your poor experience. Runelite is not natively supported on the M1. Adam, Hydrox, llemonduck and melky will do everything in their power to not support mac.

**Comment by Adam-** [comment] 2021-07-12 21:12
1. no one on the team has the hardware to debug this
2. if it isn't reproducible, it is probably not debuggable, anyway
3. since we do not have a native osx arm launcher, there is a lot of complexity here, from Rosetta emulating the jitted code from the vm. It's possible using a native VM such as described here could fix it https://github.com/runelite/runelite/wiki/MacOS-Arm64-(M1-chips)-Native-Support
4. we should be able to provide a native launcher around September at which point we would probably no longer even try to support the current configuration (RL on Rosetta) so this is probably not worth looking anyway for us currently. #12959

**Comment by piacsek** [comment] 2021-07-28 14:13
I've had the same issues. It happens very often when I use my Portal Nexus to teleport to GE, which has been set to left-click.
![image](https://user-images.githubusercontent.com/9383701/127336925-fb0ec796-5737-409d-9ecd-01a6324c7cf5.png)

**Comment by Stoddy15m** [comment] 2021-08-06 16:38
@piacsek wait till September and hopefully this will be fixed but realistically speaking until Adam steps down there will be zero development for macs. He is in denial its in the future. We need a more forward thinking project manager for runelite.

**Comment by Adam-** [comment] 2021-09-25 20:45
reopen if this still happens on launcher v2.2.0

**Closed by Adam-** 2021-09-25 20:45 UTC
Labels: needs-information, jvm-bug, platform:macos
