### ISSUE TITLE
Discord Rich Presence, only display presence when logged in

### ISSUE THREAD

**Issue by rudes** [runelite/runelite#8765] opened 2019-05-06 01:30 UTC
**Is your feature request related to a problem? Please describe.**
When you aren't logged in RuneLite still shows as your game in discord.

**Describe the solution you'd like**
Have the rich presence only display once an account is logged in to RuneLite.

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://user-images.githubusercontent.com/7551802/57203310-ee878f00-6f7c-11e9-9316-14ac9dd1eaeb.png)

**Comment by deathbeam** [comment] 2019-05-22 19:20
Duplicate of #667

**Closed by deathbeam** 2019-05-22 19:20 UTC
Labels: feature-request
