### ISSUE TITLE
Slayer Plugin highlights Scorpia's offspring on Scorpia boss task

### ISSUE THREAD

**Issue by Abi1024** [runelite/runelite#10197] opened 2019-11-04 04:40 UTC
**Describe the bug**
If you get scorpia as a boss task, and have highlight targets enabled in the Slayer plugin, then Scorpia's offspring and Scorpia's guardians get highlighted as well, even though only the boss should be highlighted. 

**To Reproduce**
1) Get Scorpia boss task
2) Enabled highlight targets in slayer plugin
3) Go to Scorpia's cave
4) Note that Scorpia's offspring are erroneously highlighted

**Expected behavior**
On a Scorpia task, nothing other than Scorpia should be highlighted by the slayer plugin. Possibly the Scorpia's guardians should be highlighted, but the offspring definitely should not be highlighted.

**Environment (please complete the following information):**
 - OS: Windows 10
-  Latest Runelite version

**Additional context**
The offending line of code is referenced. Perhaps it is worthwhile to check for scorpia as a special case in this code block.

https://github.com/runelite/runelite/blob/71e548052470332a25c56d26e6f1d70b0ea9bac5/runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java#L610-L629

**Comment by Nightfirecat** [comment] 2019-11-04 04:57
Duplicate of #6285

**Closed by Nightfirecat** 2019-11-04 04:57 UTC
