### ISSUE TITLE
CTRL + backspace should remove only the last word

### ISSUE THREAD

**Issue by gc** [runelite/runelite#9391] opened 2019-07-18 10:25 UTC
In runelite, when you type a message in the chat input box, ctrl+backspace clears the entire chat input box. Whereas, in every single other input box I've ever used anywhere (examples: windows OS, discord, spotify, IDE's, league of legends, inputs on websites, photoshop, etc), ctrl + backspace only removes the last word. I think it would make sense for it to behave the same in runelite.  

EDIT: The search input in runelite (where you search for plugins) also has the suggested behaviour. Thus RuneLite contains both behaviors of CTRL+backspace?

EDIT2: As suggested by deathbeam, this behavior should perhaps be OS/platform-based.

**Comment by kecleon** [comment] 2019-07-18 10:33
For some reason in RL, ctrl+w deletes one word, while ctrl+backspace deletes the whole line. That's one reason I compile my own copy of RL.

**Comment by deathbeam** [comment] 2019-07-19 11:55
Our current behaviour is intented, and we decided to implement it like that, because I think either OSB or Konduit were using those bindings. If you want for them to be same as your OS (because that behaviour is OS-specific), open issue titled like that.

**Comment by gc** [comment] 2019-07-19 12:37
How is it OS specific if its acting in both ways (in separate parts) of the same program (runelite)? I dont understand what you mean.

**Comment by deathbeam** [comment] 2019-07-19 12:38
Well I mean that the keybinds are different on Mac and Linux

**Comment by gc** [comment] 2019-07-19 12:51
Are you just saying it would be OS-based and the same hardcoded behaviour across all OS's? If so I will edit my suggestion slightly so it can be reopened.

**Comment by gc** [comment] 2019-07-22 07:07
@deathbeam

**Comment by deathbeam** [comment] 2019-07-22 07:09
It should use keybinds based on OS and not same everywhere if you want to change it to anything.

**Comment by abextm** [comment] 2019-07-22 07:13
Why do you think the os has anything to do with input control keybinds?

**Comment by deathbeam** [comment] 2019-07-22 08:00
Because it does, at least for Windows and Mac (or at least there are some standard keybindings, that are different for input boxes between those 2 and applications generally use those)

**Comment by abextm** [comment] 2019-07-22 08:01
Between windows and linux I see zero difference in what applications use which keybinds. Its always application specific, not platform specific.

**Comment by gc** [comment] 2019-07-22 10:23
I've edited my issue to say that it should be platform/OS-based as you suggested, so if it could be reopened that'd be nice.

Regarding your discussion, from what I understand: input fields in RuneLite are using the "delete-last word" behavior, except for the ingame chat input box, which "deletes-entire-input", I'm suggesting that it "deletes last word" so it matches everything else, and deathbeam is saying that the behavior is determined by the OS, so the ingame chat input box was coded to not care about this OS-setting, and the other input boxes were coded to respect the OS-setting, so my issue should be just "make the chat input match the OS setting".

I'll leave you guys to it though I don't know how any of it works. Thanks

**Comment by gc** [comment] 2019-08-01 19:54
@deathbeam

**Comment by devLotto** [comment] 2019-08-01 20:00
Just make it customizable with a Keybind and everyone will be happy

**Comment by Nightfirecat** [comment] 2019-11-22 03:18
Duplicate of #6929

**Closed by Nightfirecat** 2019-11-22 03:18 UTC
Labels: feature-request
