### ISSUE TITLE
Indicate when it is too early to click after crossing an Agility Course Obstacle

### ISSUE THREAD

**Issue by SaferHaul** [runelite/runelite#10583] opened 2020-01-10 17:14 UTC
Wasted clicks are extremely frustrating and when added up can really demoralize the grind; I think something as simple as changing the cursor from red (indicating that it is too early for a click to be registered successfully) to green (when you're all clear for the next click) would help to remedy this in most cases. 

This could also help in many other scenarios besides the Agility Courses example, as it the same logic could apply anywhere multiple sequential clicks are required, but may not register if you do it at the wrong times such as with Performing High Alchemy and not being able to casts it again until the xp drop is finished or using the Humidify spell followed by trying to bank too soon into the animation.

I apologize if this has been requested before under a different name or with different wording, and I hope this will be of some interest to anyone else =).

**Comment by Nightfirecat** [comment] 2020-01-10 23:16
I feel we should not add such a feature. Generally speaking, agility courses (and most other activities) will have XP drops when an action is completed which can signal to players when they can interact with something afterward.

**Comment by SaferHaul** [comment] 2020-01-11 02:44
> 
> 
> I feel we should not add such a feature. Generally speaking, agility courses (and most other activities) will have XP drops when an action is completed which can signal to players when they can interact with something afterward.

That is a valid point, however, it is important to note that the xp drop cannot always be used reliably (especially late at night or after longer sessions), and unless I am mistaken, with different methods having different tick speeds that will also influence how far the xp drop has to travel before you can click again, making it even more difficult to keep track of across skills/activities. 

What I liked about my suggestion was that unlike the former, this visual indicator is absolute, it can only be red or green, nothing in between; Ultimately, timing clicks properly will still be up to the player to perform correctly, this just helps to remove the guesswork in between clicks, which would be excellent for longer sessions when you can't quite keep up so well as that first hour.

Obviously, this is not a priority to implement in the grand scheme of things, and as you mentioned, the xp drop method more or less provides the same utility, but I stand by my point of this being a potentially nice QOL improvement over using XP drops as a visual aid to skilling.

**Comment by Nightfirecat** [comment] 2020-01-11 04:41
> with different methods having different tick speeds that will also influence how far the xp drop has to travel before you can click again

Can you elaborate on that? I can't speak for everyone, but I'd prefer to see more specific examples fitting this criteria to justify a feature which implements this. (which aren't covered [by using the "Fake XP Drop" feature of the XP Drop plugin](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropConfig.java#L79-L84))

**Comment by raiyni** [comment] 2020-06-17 03:51
Duplicate of https://github.com/runelite/runelite/issues/4717

**Closed by raiyni** 2020-06-17 03:51 UTC
