### ISSUE TITLE
Client Crashes on login

### ISSUE THREAD

**Issue by SleepySora** [runelite/runelite#10263] opened 2019-11-14 22:41 UTC
**Describe the bug**
Client crashes upon login after an unspecified amount of time.

**To Reproduce**
1. Open the Client
2. Log-in
3. Walk around for any amount of time
4. Client crashes

**Expected behavior**
The client shouldn't crash as such

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 
 - RuneLite version: 1.5.40
 - Launcher version: unknown

**Additional context**
<details><summary>client.log</summary><pre><code>2019-11-14 12:22:38 [pool-5-thread-1] WARN  n.runelite.http.api.item.ItemClient - Error looking up prices: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.runelite.net/runelite-1.5.39/item/prices.js}
2019-11-14 12:52:38 [pool-5-thread-1] WARN  n.runelite.http.api.item.ItemClient - Error looking up prices: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.runelite.net/runelite-1.5.39/item/prices.js}
2019-11-14 13:22:38 [pool-5-thread-1] WARN  n.runelite.http.api.item.ItemClient - Error looking up prices: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.runelite.net/runelite-1.5.39/item/prices.js}
2019-11-14 13:52:38 [pool-5-thread-1] WARN  n.runelite.http.api.item.ItemClient - Error looking up prices: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.runelite.net/runelite-1.5.39/item/prices.js}
2019-11-14 14:22:38 [pool-5-thread-1] WARN  n.runelite.http.api.item.ItemClient - Error looking up prices: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.runelite.net/runelite-1.5.39/item/prices.js}
2019-11-14 14:52:38 [pool-5-thread-1] WARN  n.runelite.http.api.item.ItemClient - Error looking up prices: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.runelite.net/runelite-1.5.39/item/prices.js}
2019-11-14 15:22:38 [pool-5-thread-1] WARN  n.runelite.http.api.item.ItemClient - Error looking up prices: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.runelite.net/runelite-1.5.39/item/prices.js}
2019-11-14 15:52:38 [pool-5-thread-1] WARN  n.runelite.http.api.item.ItemClient - Error looking up prices: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.runelite.net/runelite-1.5.39/item/prices.js}
2019-11-14 16:22:38 [pool-5-thread-1] WARN  n.runelite.http.api.item.ItemClient - Error looking up prices: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.runelite.net/runelite-1.5.39/item/prices.js}
2019-11-14 16:24:08 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
com.jogamp.opengl.GLException: Error swapping buffers
	at jogamp.opengl.windows.wgl.WindowsWGLDrawable.swapBuffersImpl(WindowsWGLDrawable.java:93)
	at jogamp.opengl.GLDrawableImpl.swapBuffers(GLDrawableImpl.java:88)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1121)
	at bg.bi(bg.java:45176)
	at bg.ju(bg.java)
	at bg.run(bg.java:336)
	at java.lang.Thread.run(Thread.java:748)</code></pre></details>

**Comment by Nightfirecat** [comment] 2019-11-15 17:01
Related to/duplicate of #9889

**Closed** 2020-02-23 08:08 UTC
Labels: duplicate
