### ISSUE TITLE
Group Farming Guild timers in "Farming Contract" Time Tracking tab

### ISSUE THREAD

**Issue by zombiezrule** [runelite/runelite#11947] opened 2020-06-21 03:36 UTC
Currently, the Farming Contract tab of the Time Tracking plugin simply redirects to the tab that contains your current farming contract, e.g. clicking on it while having a herb patch-related contract opens the herb tab, with the icon next to the herb. 
It would be nice to have the option to instead list all Farming Guild-related patches in one tab, so that after multiple pre-plants it can be easy to see which patches need to be replanted, and it can be clear what is already pre-planted.

**Comment by Nightfirecat** [comment] 2020-06-21 05:22
Duplicate of #3056

**Closed by Nightfirecat** 2020-06-21 05:22 UTC
Labels: duplicate
