### ISSUE TITLE
Multi Users

### ISSUE THREAD

**Issue by Vokuar** [runelite/runelite#8863] opened 2019-05-17 19:38 UTC
**Is your feature request related to a problem? Please describe.**
no easily switching accounts

**Describe the solution you'd like**
so i know ive suggested multi tabs in the past but that is just one solution to what i want and ive thought of another
you know lastpass and other password managers
well a account manager all login details stored locally so no chance of being hacked

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**
so i went searching runelite for forks and found one which says it has this in its feature list so i know its possible im just hoping its in the scope of the vision for runelite

**Comment by Hydrox6** [comment] 2019-05-17 19:40
Duplicate of #641

**Closed by Hydrox6** 2019-05-17 19:40 UTC
