### ISSUE TITLE
Wilderness Threat Notifier

### ISSUE THREAD

**Issue by ollieatkinson** [runelite/runelite#5581] opened 2018-09-21 20:55 UTC
**Is your feature request related to a problem? Please describe.**
When PVM or Skilling in the wilderness I would like to know if there's a wilderness threat. A wilderness threat would be someone who is in the level range that could attack me, we could also have options to only warn you if they have a skull.

**Describe the solution you'd like**
Show an alert similar to the idle notifier so that I, the skiller can respond to the wilderness threat.

**Additional Context**
This is just an idea, but may be against the integrity of the game. I am looking for feedback if this is something which should be implemented and/or if other things like this should be implemented in the wilderness.

**Comment by deathbeam** [comment] 2018-09-21 22:09
Duplicate of #4282

**Closed by deathbeam** 2018-09-21 22:09 UTC
