### ISSUE TITLE
Menu Entity Swapper - Remove dead npc menus

### ISSUE THREAD

**Issue by Delirious143** [runelite/runelite#15157] opened 2022-06-19 02:19 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

In the Quest "in aid of the Myreque" the player has to kill then talk to the NPC "Gadderanks" with this setting on the quest gets soft blocked as the player isn't able to talk to him.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/106401624/174463119-f2a7c78a-63fe-40b9-8f32-def5fa11a3d0.png)

### Logs

[client.log](https://github.com/runelite/runelite/files/8934631/client.log)
[launcher.log](https://github.com/runelite/runelite/files/8934632/launcher.log)

**Comment by Nightfirecat** [comment] 2022-06-19 03:19
Duplicate of #15135

**Closed by Nightfirecat** 2022-06-19 03:19 UTC
Labels: duplicate
