### ISSUE TITLE
Decrease Size of Boost Indicators + Disable(Toggle?) their Tooltip

### ISSUE THREAD

**Issue by Honestidade** [runelite/runelite#3122] opened 2018-05-22 21:05 UTC
https://i.imgur.com/b530GWB.png

The size of the boost indicator could be reduced to about 75%~ the current size as it's currently using up a lot of wasted screen space.(Which is more of a big deal on fixed than resizable, especially when 5+ show up during a raid)

Also, even with the "tooltips" plugin off, I still get a tooltip when hovering over the boost icons which is cumbersome. Really I think the icon should be enough to tell you what skill it is, but if you want the tooltip could it at least be togglable?

**Comment by deathbeam** [comment] 2018-05-23 15:30
Duplicate of #1016

**Closed by deathbeam** 2018-05-23 15:30 UTC
