### ISSUE TITLE
Something's off with the XP Tracker

### ISSUE THREAD

**Issue by joaogardenberg** [runelite/runelite#14902] opened 2022-04-27 00:30 UTC
**Describe the bug**
I'm a defence pure 1/1/65 and the XP Tracker is showing a very wrong XP/hr @ Sand crabs, hitting 1s and 2s with the Swift blade.
It's been on for well over an hour.

**To Reproduce**
1. Have a defence pure with +43 strength bonus and swift blade
2. Attack some Sand crabs for a while

**Expected behavior**
XP/hr should be something like 5k/hr for Defence and 1.5k/hr for Hitpoints

**Screenshots**
![image](https://user-images.githubusercontent.com/6900749/165414683-20146d0e-35ad-45e6-80f7-40d0049b55c8.png)

**Environment (please complete the following information):**
 - OS: WIndows 10
 - RuneLite version: 1.8.18.3
 - Launcher version: 2.4.2

**Comment by Hydrox6** [comment] 2022-04-27 08:38
Looks to be similar to #10099?

**Comment by joaogardenberg** [comment] 2022-04-27 16:45
True

**Comment by Nightfirecat** [comment] 2022-04-28 16:53
I'm confident this is a duplicate of #10099. We don't presently have any information on what causes this issue, so if you (or someone else) can find reproduction steps, we'd love to look into it further.

**Closed by Nightfirecat** 2022-04-28 16:53 UTC
Labels: duplicate
