### ISSUE TITLE
Unlocked FPS Camera Jitter

### ISSUE THREAD

**Issue by AustinGarrettR** [runelite/runelite#14322] opened 2021-10-31 04:17 UTC
**Describe the bug**
With unlocked FPS enabled in the GPU plugin, when your character is running over uneven/sloped terrain. and you are moving your camera up and down, occasionally you will see a sudden jitter/jump in the camera then back. It appears for a single frame, it jumps. It is worst when moving the camera vertically up and down with middle mouse button. Occasionally this also happens when the character teleports a few tiles, such as when entering/exiting the corporeal beast boss room.

This is present only when GPU plugin with Unlocked FPS is on. This does not occur with GPU off, or GPU on with unlocked FPS off. This is on a 60hz monitor.

**To Reproduce**
1. Turn GPU plugin on, with unlocked FPS on.
2. Make your character run over uneven or sloped terrain.
3. While running, move your camera vertically.
4. You should see camera jumps frequently.

**Expected behavior**
The camera should not jitter/jump so drastically.

**Environment (please complete the following information):**
 - OS: Windows 11, 60hz monitor (60 FPS ingame not dropping), Runelite 64bit. Nvidia rtx 2060 super, AMD 5000 series CPU.
 - RuneLite version: 1.8.0
 - Launcher version: 2.2.0 (Also tested on 2.1.7)

**Additional context**
No logs showed anything at all related to this.
Overlays do stay with the scene and are affected by the jitter consistently as well.
The intensity of each jitter is increased when moving the camera faster.

**Comment by Nightfirecat** [comment] 2021-11-11 20:49
Upon doing a cursory test of this, I couldn't see this effect happening. Can you provide some specific location which would work well to test this, or better yet, a video demonstrating it?

**Comment by AustinGarrettR** [comment] 2021-11-12 12:25
> Upon doing a cursory test of this, I couldn't see this effect happening. Can you provide some specific location which would work well to test this, or better yet, a video demonstrating it?

I have uploaded a 4k 60 video of this. The jitters in the video are not caused by the video capture, but that's what is actually happening.

The majority of the jittering is in the very end of the short video.
https://www.youtube.com/watch?v=KIZU8bjLIW4

**Comment by JoshJ96** [comment] 2021-11-13 17:37
I noticed this happening at Sotetseg in ToB too. not sure why

**Comment by Nightfirecat** [comment] 2022-07-10 04:15
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:15 UTC
Labels: bug, gpu
