### ISSUE TITLE
Overlay bracelets of Slaughter/expeditous

### ISSUE THREAD

**Issue by jackyon1** [runelite/runelite#11025] opened 2020-03-16 23:15 UTC
Similar to how we have overlays for Fishing/Not Fishing (and cooking, etc). I often find myself forgetting to equip bracelets.

The overlay would say 'Worn/Not worn'

![image](https://user-images.githubusercontent.com/32822218/76807317-deb31b00-67db-11ea-8e2f-3063e82393b9.png)

**Comment by Hydrox6** [comment] 2020-03-16 23:17
Duplicate of #9969

**Closed by Hydrox6** 2020-03-16 23:17 UTC

**Comment by jackyon1** [comment] 2020-03-16 23:21
@Hydrox6 Hey, no this isn't a duplicate issue. Though, it isn't that far from the alleged duplicate issue

**Comment by Hydrox6** [comment] 2020-03-16 23:22
You're asking for basically the same thing; an overlay that shows the charges also shows if you have one equipped.

Also, a performance tracker-like overlay for a single state just feels incredibly wrong.

**Comment by OilyHands** [comment] 2020-03-16 23:29
Fair enough, I guess. Just because you mightn't use it doesn't mean there's not appetite for it
