### ISSUE TITLE
Possibility for the camera to default rotation to another direction other than north?

### ISSUE THREAD

**Issue by qindav** [runelite/runelite#10527] opened 2019-12-31 17:27 UTC
This is probably an unimportant request, but I'm used to playing this game as a kid with east pointing upwards on the compass. Any possibility to have it somehow default when you log in or at least "snap" when you click on the in game compass? Currently the game only supports pointing north. Looked at the camera plugin and it seems to support some aspects like with locking default zooms and such.

**Comment by Nightfirecat** [comment] 2019-12-31 17:32
Duplicate of #1770

**Closed by Nightfirecat** 2019-12-31 17:32 UTC
