### ISSUE TITLE
supply crate tracker

### ISSUE THREAD

**Issue by snitgaard** [runelite/runelite#12349] opened 2020-08-16 10:24 UTC
**Is your feature request related to a problem? Please describe.**
There's recently been added a few new trackers for for example birds nests / seed packs, and it's kind of inconsistent that there hasnt been added one for Wintertodt supply crates, as I'd like to be able to track the loot I get from wintertodt over long periods of time.

**Describe the solution you'd like**
The loot tracker expanded to check and log wintertodt supply crates, just like how we've recently got Seed packs and Birds nests added to the loot tracker

**Comment by melkypie** [comment] 2020-08-16 10:49
Duplicate of #5824

**Closed by melkypie** 2020-08-16 10:49 UTC
