### ISSUE TITLE
Improved Quest-Tracker

### ISSUE THREAD

**Issue by xferrari** [runelite/runelite#4327] opened 2018-07-14 15:29 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't open multiple quest-tabs at once. If I want to do an advanced quest, and have to complete 10 other, related quests for it, I quickly lose clarity of what to do first, what quests have I done already etc.

**Describe the solution you'd like**
An implementation of the Wiki, which also could show the quests I've already done. Or maybe a Tree with the quest I want to do as root, and quests that need to be done as "leaves".

This is how it looks on the RS3 Wiki:
`https://imgur.com/a/irp6EZH`
Helps to calculate if I need to do a lot of other quests for a specific quest.

**Describe alternatives you've considered**
Using the OSRS Wikipedia in a Browser, yet I couldn't find a plugin that could pull my account's quests that I have completed.

**Additional context**
Just a small concept I quickly drew in Paint -> `https://imgur.com/a/HvXdimf`
If you could fit the skill-requirements there as well (when you hover over a quest), it would be fantastic.

**Comment by deathbeam** [comment] 2018-07-14 15:33
Duplicate of one of or multiple of  #3038 and #2551 and #1905

**Closed by deathbeam** 2018-07-14 15:33 UTC
