### ISSUE TITLE
Client up time with logged in time per client

### ISSUE THREAD

**Issue by Scortyx** [runelite/runelite#9704] opened 2019-08-20 14:15 UTC
There was a feature on Konduit that showed client up time and below that was how many of those hours was spent logged in.
It would be in the info sidebar and it basically looked like this:

Client up time: 16:41 hours
logged in: 10:59 hours

**Comment by deathbeam** [comment] 2019-08-20 14:20
Duplicate of https://github.com/runelite/runelite/issues/5465

**Closed by deathbeam** 2019-08-20 14:20 UTC

**Comment by Scortyx** [comment] 2019-08-20 14:34
your reasons for closing the other suggestion of this was because you think it gives incentive to not close the client. They have to close it every thursday, and theres plenty of people who keep their clients open all week even without this so thats a moot point.

Its nice to see how many hours you were logged in for a specific day, its just a small little feature that does no harm but just shut it down because you think Hans "age" is anything like this.

**Comment by Adam-** [comment] 2019-08-20 14:43
I'm really indifferent to this being added, although he is referring to runelite updates which happen after game updates (the latter *do* force you to restart, but ours do not). I don't think this is really actually a problem though.

**Comment by Scortyx** [comment] 2019-08-20 14:50
It isnt a important feature at all, i just remember it was a cool little thing to have.
