### ISSUE TITLE
[Customisable Interface] Side Panels - Ability to move them to the bottom and/or left  - Have multiple open simultaneously

### ISSUE THREAD

**Issue by Vijay-Anand-V** [runelite/runelite#13970] opened 2021-08-03 09:59 UTC
I want to be able to access panels from any side of the screen, also have multiple open at the same time.

**Comment by Hydrox6** [comment] 2021-08-03 10:02
Duplicate of #1641
Duplicate of #3277

**Closed by Hydrox6** 2021-08-03 10:02 UTC
