### ISSUE TITLE
Mage Training Arena Telekinetic Room Broke

### ISSUE THREAD

**Issue by remicktr** [runelite/runelite#6299] opened 2018-11-01 18:26 UTC
Since today's Runelite update the Telekinetic Room in the Mage Training Arena has been not advancing the click area (sometimes). I did 15 puzzles yesterday with no issues. 

Notice in my video how I start on the wrong marked tile but then after I manually advance it the location square will move. I've seen this happen twice in both:

- https://oldschool.runescape.wiki/w/File:Telekinetic_theatre_maze_3.png
- https://oldschool.runescape.wiki/w/File:Telekinetic_theatre_maze_10.png (this one worked well the second time)

![twbnyhg 1](https://user-images.githubusercontent.com/31493135/47871045-5c41db00-dde1-11e8-819d-8b94812ffaf4.gif)

==

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)

Windows 10  Education (64 bit)
Iten Core i7-4790S 3.20ghz

**Comment by deathbeam** [comment] 2018-11-01 18:29
Duplicate of #3946

**Comment by deathbeam** [comment] 2018-11-01 18:29
I am pretty sure this is not new as we were not touching the MTA plugin code any

**Closed by deathbeam** 2018-11-01 18:29 UTC
