### ISSUE TITLE
Whole computer crashes randomly when using Runelite client

### ISSUE THREAD

**Issue by DDR3-1600** [runelite/runelite#14097] opened 2021-09-05 19:36 UTC
I have an AMD Vega 64 GPU and have seen crash issues before but I havent found one yet that mentions their whole computer crashing. When the bug occurs both of my monitors turn a random color and then my computer reboots. It only happens when using the runelite client. I tried turning the render distance down in the gpu plugin and reinstalling. Reinstalling worked the best but I have had another crash since then. Since the crash I have gone to the log files but didnt see anything useful.

**Environment (please complete the following information):**
 - OS: Windows 
 - RuneLite version: 1.7.21.1
 - Launcher version: 2.1.7

**Comment by Nightfirecat** [comment] 2022-07-10 04:09
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:09 UTC
Labels: needs-information, gpu
