### ISSUE TITLE
MEny Entry Swapper Teleport Item on Construction Cape

### ISSUE THREAD

**Issue by vitorebom** [runelite/runelite#11367] opened 2020-04-25 15:22 UTC
Currently with the feature on, the cape left click becomes "Teleport", which brings up the portal interface. Could this be expanded to a picklist to choose between the "Teleport" and "Tele to POH" options?

**Comment by Hydrox6** [comment] 2020-04-25 15:24
Duplicate of #6227

**Closed by Hydrox6** 2020-04-25 15:24 UTC
