### ISSUE TITLE
Per-Plugin Notification Settings

### ISSUE THREAD

**Issue by adamk33n3r** [runelite/runelite#14406] opened 2021-11-23 23:48 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to be able to set notification settings per plugin. For example, I'd like to have tempoross game notifications while in focus while still having other tray notifications when not in focus.

**Describe the solution you'd like**
Have a notification/bell button next to each plugin (like by the gear, or maybe just add it to each config automatically) where you can change the notification settings per plugin. The settings in `RuneLite` could be the default for new plugins, and then you could customize the ones you want. Could be just game, tray, in-focus settings, but if we'd go all-out, including the flash, sound, and request focus settings as well.

**Describe alternatives you've considered**
I realize this would be a moderate undertaking, so an intermediate solution could be to have separate in-focus settings for both game message notifications and tray notifications.

**Comment by Nightfirecat** [comment] 2021-11-23 23:56
Duplicate of #11679

**Closed by Nightfirecat** 2021-11-23 23:56 UTC
Labels: duplicate

**Comment by adamk33n3r** [comment] 2021-11-23 23:59
> Duplicate of #11679

I really don't think it is. I did find that one before making mine, but that one describes having different notifications per "event" and is also focused on flash/sound settings and not tray/game/in-focus settings. If you still think it's a duplicate, I can comment on that issue with my suggestions as I think I have unique information.

**Comment by Nightfirecat** [comment] 2021-11-24 00:03
Some plugins have multiple distinct sources of notifications (idle notifier for instance) which players might want to be configured differently. In any event, plugin-specific notification settings would be a subset of event-specific settings so it's the same problem needing to be solved either way.

**Comment by adamk33n3r** [comment] 2021-11-24 00:03
Gotcha, I'll go ahead and comment on that other issue. Thanks!
