### ISSUE TITLE
Rooftop Removal POH Dungeons

### ISSUE THREAD

**Issue by ReinierAarnink1996** [runelite/runelite#13951] opened 2021-07-26 12:53 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)
I did

**Describe the bug**

**To Reproduce**
1. Go to your poh
2. Enter your dungeon

**Expected behavior**
The dungeon and above ground collapse

**Screenshots**
http://prntscr.com/1g5l931

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 26/7/2021
 - Launcher version: 26/7/2021

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
Like some other guy said, a toggle for poh would be nice.

**Comment by Hydrox6** [comment] 2021-07-26 13:04
Duplicate of #13891 (the issue is basically going to end up being the same thing)

**Closed by Hydrox6** 2021-07-26 13:04 UTC
