### ISSUE TITLE
Make search in GE tab work for partial words

### ISSUE THREAD

**Issue by marubin** [runelite/runelite#4221] opened 2018-07-08 01:01 UTC
Is there a reason that the search function in the GE tab ignores partial words? E.g. searching "dragon warh" doesn't even result in dragon warhammer appearing in the results at all. This is highly counterintuitive, in my opinion. Make the search function as the in-game GE search does, or better yet, allow for the search term to appear anywhere in the item name (the GE requires that the item name begins with the search term).

**Comment by deathbeam** [comment] 2018-07-08 01:53
Duplicate of #1338

**Closed by deathbeam** 2018-07-08 01:53 UTC
