### ISSUE TITLE
Add possible monster fights on clue scrolls

### ISSUE THREAD

**Issue by dappersnapper456** [runelite/runelite#9217] opened 2019-06-26 19:12 UTC
I was frustrated recently when doing a lot of clue scrolls using the client that when I was told to dig at certain locations, I wasn't told by the client I could end up fighting certain monsters. 

I had to go to the wiki to find out on multiple occasions that depending on what part of the clue I was on, I had to fight either a bandos guardian/armadyl guardian or a brassican mage/three ancient mages. The client if possible should also tell me the best combat style to kill each. For example the armadyl guardian floats in air so is impossible to kill with melee.

**Comment by Hydrox6** [comment] 2019-06-26 19:19
Duplicate of #2580

**Closed by Hydrox6** 2019-06-26 19:19 UTC
Labels: clues, feature-request
