### ISSUE TITLE
OpenGL-related systemwide driver crash

### ISSUE THREAD

**Issue by Jakexx360** [runelite/runelite#13289] opened 2021-02-28 09:01 UTC
**Describe the bug**
Occasionally, the entire computer will freeze. Runelite will crash, and all application windows open are replaced with black screens. This happens in-game as well as on the login screen. The first Windows event log message indicating this crash was 2/13/21 (despite having used RuneLite with the same GPU settings since the plugin was released). Presuming this crash was introduced with the Compute Shaders addition to GPU plugin, I have disabled the setting and still experience the crash. My computer has not been significantly changed recently, and the only recent GPU-related problems occurred when RuneLite was open.

**The following error message is printed to the Windows event log:**

The description for Event ID 1 from source NVIDIA OpenGL Driver cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

A TDR has been detected.
The application must close.

Error code: 7
 (pid=13936 tid=2400 runelite.exe 64bit)

Visit http://nvidia.custhelp.com/app/answers/detail/a_id/3633 for more information.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/9088066/109412978-ae26ab80-7970-11eb-957c-ce925678b03e.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.1
 - Launcher version: 2.1.0
 - Hardware Acceleration set to OFF

**Additional context**
[launcher.log](https://github.com/runelite/runelite/files/6056462/launcher.log)
[client.log](https://github.com/runelite/runelite/files/6056463/client.log)

**Comment by Nightfirecat** [comment] 2022-07-10 04:50
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:50 UTC
