### ISSUE TITLE
Easy Clue Scroll: Cryptic Clue Step - Wrong Tool Leprechaun

### ISSUE THREAD

**Issue by rwgnr** [runelite/runelite#12021] opened 2020-06-28 18:46 UTC
**Describe the bug**
The Easy Clue Scroll assistance for the step "Belladonna, my dear. If only I had gloves, then I could hold you at last." is identifying the wrong Tool Leprechaun. Runelite is pointing at the Tool Lebrechaun in Port Sarim by the Spirit Tree Patch.

**To Reproduce**
1. Get a Clue Scroll (easy) with the step "Belladonna, my dear. If only I had gloves, then I could hold you at last."
2. Open the World Map and check the step to see where it is suggesting you go
3. Go to Port Sarim and see if the wrong Tool Leprechaun is being identified

**Expected behavior**
The Tool Leprechaun next to Draynor Manor's Belladonna Patch should have the tile marker, map indication, and arrow guide

**Screenshots**
N/A (Sorry I forgot to grab one)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - RuneLite version: 1.6.21.1
 - Launcher version: 2.1.3

**Additional context**
N/A

**Comment by Nightfirecat** [comment] 2020-06-28 18:47
Duplicate of #3164--this behavior affects all NPCs, not just Tool leprechauns.

**Closed by Nightfirecat** 2020-06-28 18:47 UTC
Labels: duplicate
