### ISSUE TITLE
RuneLite uses launched monitor resolution for determining resolution to expand to when "maximizing"

### ISSUE THREAD

**Issue by pullup** [runelite/runelite#9147] opened 2019-06-19 18:25 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
If you launch the client on a monitor that has a resolution of 800x600 (primary monitor) then drag it over to a monitor that is 1920x1080, when you attempt to maximize it, it will only expand to 800x600.

**To Reproduce**
1. Make your default monitor 800x600 or a lower res than monitor 2
2. Launch RuneLite
3. Drag RuneLite to the secondary (non-primary) monitor that is a greater resolution.
4. Click the "maximize" button
5. Unexpected behavior is the client will fail to properly maximize, and instead use the primary monitor's / launch monitor's max resolution to resize.

**Expected behavior**
When "maximize" is clicked the client should full screen to the new monitor's resolution.

**Screenshots**
![k1fwe3KW2x](https://user-images.githubusercontent.com/21213041/59735546-044ace00-9224-11e9-9c83-4e40b608b41f.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 64 Bit, Version 1803
 - RuneLite version: [e.g 1.5.27 SNAPSHOT]
 - Launcher version: [e.g 1.6.3 SNAPSHOT]

**Additional context**
n/a

**Comment by Alexsuperfly** [comment] 2019-09-17 22:21
duplicate of #5153

**Closed** 2019-09-19 04:25 UTC
Labels: duplicate
