### ISSUE TITLE
Configurable flash notifications

### ISSUE THREAD

**Issue by renfc01** [runelite/runelite#10826] opened 2020-02-18 14:07 UTC
I want to be able to customize the colour, frequency and opacity of the Runelite Flash notification (i.e. when idle notifications trigger)

**Describe the solution you'd like**
A colour picker for picking colour and opacity (alpha)
An input box to specify frequency (how quickly the window flashes) and length (how long it flashes for)

**Comment by dekvall** [comment] 2020-02-18 14:11
Duplicate of #10761

**Closed by dekvall** 2020-02-18 14:11 UTC
