### ISSUE TITLE
Status Bar Alignment Broken

### ISSUE THREAD

**Issue by lammin675** [runelite/runelite#13541] opened 2021-04-28 11:13 UTC
Hi,

Since tis morning the status bars are not loading in the correct place. This issue only occurs on Resizable - Classic Layout. I have deleted  .runelite to com\pletely reset  Runelite however not 100% sure if this is a local issue or not.

Tried resetting the plugin etc too.

![Capture](https://user-images.githubusercontent.com/80154783/116394390-c43ed400-a81a-11eb-9f79-d54f37bbdfc5.PNG)

**Comment by Hydrox6** [comment] 2021-04-28 11:14
Duplicate of #13540

**Closed by Hydrox6** 2021-04-28 11:14 UTC
