### ISSUE TITLE
Fishing - Aerial Fishing Glitch

### ISSUE THREAD

**Issue by SteveMeister91** [runelite/runelite#11375] opened 2020-04-26 21:00 UTC
**Describe the bug**
Multiple fishing icons when there is no fish

**To Reproduce**
Not quite sure what sets this off, fish at the Loch for a while and it started happening. Even when restarting RuneLite and restarting my laptop it happened again.

**Expected behavior**
Multiple Fishing icons, they will even turn green when nearby when there are no fish there.

**Screenshots**

![image](https://user-images.githubusercontent.com/64380403/80319556-cf76b280-8808-11ea-88fe-a7560db64b27.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.11

**Comment by Nightfirecat** [comment] 2020-04-26 21:02
Duplicate of #7702

**Closed by Nightfirecat** 2020-04-26 21:02 UTC
Labels: duplicate
