### ISSUE TITLE
Corp suggestion

### ISSUE THREAD

**Issue by Oligarchas** [runelite/runelite#1317] opened 2018-04-07 20:58 UTC
Konduit counts how many DWH, Arclight and BGS hits you have done. Would be nice if RuneLite had this feature aswell. 
Example: https://gyazo.com/a9b9500233b045ee20314fe04dbf2f08

**Comment by Kamielvf** [comment] 2018-04-07 21:04
Duplicate of #492

**Comment by deathbeam** [comment] 2018-04-07 21:08
As @Kamielvf said,
Duplicate of #492

**Closed by deathbeam** 2018-04-07 21:08 UTC
