### ISSUE TITLE
Stretched mode + GPU 0% scaling zooms the screen by a pixel 

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#6745] opened 2018-11-29 19:40 UTC
When you activate stretched mode with GPU on the screen seems to zoom in by a tiny amount, this does not happen when using CPU rendering. Regardless of any other options enabled or not and what level in game zoom you have set it happens, I also assume it does when scaling but its harder to tell since the screen moves around when enabling/disabling rapidly.

GIF example: https://i.imgur.com/3Jq04OP.mp4

**Comment by bcowell** [comment] 2018-12-16 06:15
Link is broken for me.

**Comment by theGeekPirate** [comment] 2018-12-16 06:17
@bcowell https://i.imgur.com/3Jq04OP.gif

**Comment by Nightfirecat** [comment] 2022-07-10 04:02
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:02 UTC
Labels: bug, gpu
