### ISSUE TITLE
Runelite unexpectedly closes after several hours (3 clients open at same time)

### ISSUE THREAD

**Issue by BladeBTW** [runelite/runelite#11235] opened 2020-04-09 09:47 UTC
**Describe the bug**
While playing OSRS on Runelite after usually an hour or 2 my client will randomly crash. 

Since making this post I've been tracking my crashes and you'll find timestamps in the "EDITS" at the bottom of the post this ticket with crash logs.

Might be worth noting is that every 2 - 3 days I get a BSOD. I've created a support ticket for this at Microsoft Answers, if this gets resolved I'll post information about that here too.

All I've been doing is chopping Yews in the woodcutting guild while constantly tabbing out of the game on one account.
The other account usually sits in the motherlode mine.
My 3rd account (HCIM) is the only account I actively play and I am fearing for my Red Helmet.

Useful thing to note is that I play 3 runelite windows at the same time, Runelite crashing while playing OSRS is a long standing problem with me. The way I run Runelite is by using 3 different Runelite.exe (see screenshot) I copied Runelite in AppData local and made sepparate folders hoping this would solve the crashes. But alas. I've had the crash multiple times and I will upload all of the crash logs.

**To Reproduce**

Open and play Runelite for several hours. Useful to note that this problem hasn't occured with 1 client open yet, but the thing is I'm not sure if it will crash with just a single client because I always play on 3 clients.

**Expected behavior**
The client to keep working without closing without notfication.

**Screenshots**
Runelite folder in AppData\Local which I copied multiple times for alting (hoping this would solve the crashes, but alas).
![image](https://user-images.githubusercontent.com/52164618/78880704-149f9400-7a56-11ea-9ab5-4508ec98d3e3.png)

RuneLite icons which I've changed:
![image](https://user-images.githubusercontent.com/52164618/78880926-63e5c480-7a56-11ea-9649-60e9dc339106.png)

Java version:
![image](https://user-images.githubusercontent.com/52164618/78881218-c63ec500-7a56-11ea-92f8-90e73267ea49.png)

PC Screen setup:
![image](https://user-images.githubusercontent.com/52164618/78881410-13229b80-7a57-11ea-8076-e13f3339ff44.png)

**Environment (please complete the following information):**
OS: Windows 10 Pro
RuneLite version: client-patch 489059353.87
Launcher version: "-Drunelite.launcher.version\u003d2.0.2",
RAM: 32,0GB (31,5 usable)
Processor: AMD Ryzen 7 1800x Eight-Core Processor 3.60GHz

**Additional context**
I've also tried playing on the vanilla client with 3 clients open, but the same thing happens. The vanilla client will randomly crash after a while playing on 3 clients.

I really hope some-one can help me with this, one of my accounts is a hardcore iron man and I've already had a few close calls with client crashes. :(

A thing to note is that I changed the way RuneLite icons work using a program called ResourceHacker, personally I don't think this causes the crashes because I've had the client closing randomly in the same manner months before I even changed my RuneLite icons.

You can see the icons I use in the RuneLite icons screenshot above.

I've attached any crash log I could find, just for extra information. I recommend looking at the most recent ones though. They are ordered from newest to oldest.
[client.log](https://github.com/runelite/runelite/files/4455327/client.log)
[launcher.log](https://github.com/runelite/runelite/files/4455328/launcher.log)
[jvm_crash_pid_18284.log](https://github.com/runelite/runelite/files/4455329/jvm_crash_pid_18284.log)
[launcher_2020-04-07.0.log](https://github.com/runelite/runelite/files/4455331/launcher_2020-04-07.0.log)
[client_2020-04-06.0.log](https://github.com/runelite/runelite/files/4455332/client_2020-04-06.0.log)
[launcher_2020-04-06.0.log](https://github.com/runelite/runelite/files/4455333/launcher_2020-04-06.0.log)
[jvm_crash_pid_2788.log](https://github.com/runelite/runelite/files/4455334/jvm_crash_pid_2788.log)
[client_2020-04-05.0.log](https://github.com/runelite/runelite/files/4455335/client_2020-04-05.0.log)
[launcher_2020-04-04.0.log](https://github.com/runelite/runelite/files/4455336/launcher_2020-04-04.0.log)
[launcher_2020-04-03.0.log](https://github.com/runelite/runelite/files/4455337/launcher_2020-04-03.0.log)
[launcher_2020-04-02.0.log](https://github.com/runelite/runelite/files/4455338/launcher_2020-04-02.0.log)
[client_2020-04-01.0.log](https://github.com/runelite/runelite/files/4455339/client_2020-04-01.0.log)
[launcher_2020-04-01.0.log](https://github.com/runelite/runelite/files/4455340/launcher_2020-04-01.0.log)
[launcher_2020-03-31.0.log](https://github.com/runelite/runelite/files/4455341/launcher_2020-03-31.0.log)
[jvm_crash_pid_1084.log](https://github.com/runelite/runelite/files/4455342/jvm_crash_pid_1084.log)
[client_2020-03-28.0.log](https://github.com/runelite/runelite/files/4455343/client_2020-03-28.0.log)
[launcher_2020-03-28.0.log](https://github.com/runelite/runelite/files/4455344/launcher_2020-03-28.0.log)
[client_2020-03-27.0.log](https://github.com/runelite/runelite/files/4455345/client_2020-03-27.0.log)
[launcher_2020-03-27.0.log](https://github.com/runelite/runelite/files/4455346/launcher_2020-03-27.0.log)
[client_2020-03-26.0.log](https://github.com/runelite/runelite/files/4455347/client_2020-03-26.0.log)
[launcher_2020-03-26.0.log](https://github.com/runelite/runelite/files/4455348/launcher_2020-03-26.0.log)
[client_2020-03-25.0.log](https://github.com/runelite/runelite/files/4455349/client_2020-03-25.0.log)
[launcher_2020-03-25.0.log](https://github.com/runelite/runelite/files/4455350/launcher_2020-03-25.0.log)
[client_2020-03-24.0.log](https://github.com/runelite/runelite/files/4455351/client_2020-03-24.0.log)
[launcher_2020-03-24.0.log](https://github.com/runelite/runelite/files/4455352/launcher_2020-03-24.0.log)
[client_2020-03-23.0.log](https://github.com/runelite/runelite/files/4455353/client_2020-03-23.0.log)
[launcher_2020-03-23.0.log](https://github.com/runelite/runelite/files/4455354/launcher_2020-03-23.0.log)
[client_2020-03-22.0.log](https://github.com/runelite/runelite/files/4455355/client_2020-03-22.0.log)
[launcher_2020-03-22.0.log](https://github.com/runelite/runelite/files/4455356/launcher_2020-03-22.0.log)
[client_2020-03-21.0.log](https://github.com/runelite/runelite/files/4455357/client_2020-03-21.0.log)
[launcher_2020-03-21.0.log](https://github.com/runelite/runelite/files/4455358/launcher_2020-03-21.0.log)
[client_2020-03-20.0.log](https://github.com/runelite/runelite/files/4455359/client_2020-03-20.0.log)
[client_2020-03-19.0.log](https://github.com/runelite/runelite/files/4455360/client_2020-03-19.0.log)
[launcher_2020-03-19.0.log](https://github.com/runelite/runelite/files/4455361/launcher_2020-03-19.0.log)
[client_2020-03-18.0.log](https://github.com/runelite/runelite/files/4455362/client_2020-03-18.0.log)
[launcher_2020-03-18.0.log](https://github.com/runelite/runelite/files/4455363/launcher_2020-03-18.0.log)
[client_2020-03-17.0.log](https://github.com/runelite/runelite/files/4455364/client_2020-03-17.0.log)
[launcher_2020-03-17.0.log](https://github.com/runelite/runelite/files/4455365/launcher_2020-03-17.0.log)
[jvm_crash_pid_18144.log](https://github.com/runelite/runelite/files/4455366/jvm_crash_pid_18144.log)
[client_2020-03-16.0.log](https://github.com/runelite/runelite/files/4455367/client_2020-03-16.0.log)
[launcher_2020-03-16.0.log](https://github.com/runelite/runelite/files/4455368/launcher_2020-03-16.0.log)
[client_2020-03-15.0.log](https://github.com/runelite/runelite/files/4455369/client_2020-03-15.0.log)
[launcher_2020-03-15.0.log](https://github.com/runelite/runelite/files/4455370/launcher_2020-03-15.0.log)
[client_2020-03-14.0.log](https://github.com/runelite/runelite/files/4455371/client_2020-03-14.0.log)
[launcher_2020-03-14.0.log](https://github.com/runelite/runelite/files/4455372/launcher_2020-03-14.0.log)
[client_2020-03-13.0.log](https://github.com/runelite/runelite/files/4455373/client_2020-03-13.0.log)
[launcher_2020-03-13.0.log](https://github.com/runelite/runelite/files/4455374/launcher_2020-03-13.0.log)
[client_2020-03-12.0.log](https://github.com/runelite/runelite/files/4455376/client_2020-03-12.0.log)
[launcher_2020-03-12.0.log](https://github.com/runelite/runelite/files/4455377/launcher_2020-03-12.0.log)
[client_2020-03-11.0.log](https://github.com/runelite/runelite/files/4455378/client_2020-03-11.0.log)
[launcher_2020-03-11.0.log](https://github.com/runelite/runelite/files/4455379/launcher_2020-03-11.0.log)
[client_2020-03-10.0.log](https://github.com/runelite/runelite/files/4455380/client_2020-03-10.0.log)
[launcher_2020-03-10.0.log](https://github.com/runelite/runelite/files/4455381/launcher_2020-03-10.0.log)

EDIT:
Had another crash since I made this post on 09-04-2020, here is the log of that crash (middle client crashed, XB):
[jvm_crash_pid_436.log](https://github.com/runelite/runelite/files/4455521/jvm_crash_pid_436.log)

EDIT2:
Another crash, 10 minutes later on 09-04-2020(left client, MB), log is included
[jvm_crash_pid_22404.log](https://github.com/runelite/runelite/files/4455580/jvm_crash_pid_22404.log)

EDIT3:
Another crash, 1 hour 30 minutes later on 09-04-2020 (left client, MB) log is included.
[jvm_crash_pid_20944.log](https://github.com/runelite/runelite/files/4455948/jvm_crash_pid_20944.log)

EDIT4:
Another crash, 36 minutes later on 09-04-2020 (right client, HB) log is included.
[jvm_crash_pid_1764.log](https://github.com/runelite/runelite/files/4456177/jvm_crash_pid_1764.log)

EDIT5:
Had 2 more crashes on 09-04-2020 (not sure which of the 3 clients)
logs is included
[jvm_crash_pid_16624.log](https://github.com/runelite/runelite/files/4460479/jvm_crash_pid_16624.log)
[jvm_crash_pid_8684.log](https://github.com/runelite/runelite/files/4460480/jvm_crash_pid_8684.log)

EDIT6:
Had a few more crashes
Logs included
[jvm_crash_pid_21340.log](https://github.com/runelite/runelite/files/4464815/jvm_crash_pid_21340.log)
[jvm_crash_pid_22248.log](https://github.com/runelite/runelite/files/4464816/jvm_crash_pid_22248.log)
[jvm_crash_pid_14472.log](https://github.com/runelite/runelite/files/4464817/jvm_crash_pid_14472.log)
[jvm_crash_pid_16624.log](https://github.com/runelite/runelite/files/4464818/jvm_crash_pid_16624.log)

**Comment by ivanfeli** [comment] 2020-04-11 20:13
I don't know any solution to this but all those crashes seem to be the same issue, which is linked to the Java VM itself and most likely not an issue with Runelite (and/or OSRS):

> \#
> \# A fatal error has been detected by the Java Runtime Environment:
> \#
> \#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000001f9eba90167, pid=21340, tid=15904
> \#
> \# JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
> \# Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
> \# Problematic frame:
> \# v  ~BufferBlob::vtable chunks
> \#
> \# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
> \#
> \# If you would like to submit a bug report, please visit:
> \#   https://github.com/AdoptOpenJDK/openjdk-build/issues
> \#

**Comment by BladeBTW** [comment] 2020-04-11 20:58
> I don't know any solution to this but all those crashes seem to be the same issue, which is linked to the Java VM itself and most likely not an issue with Runelite (and/or OSRS):
> 
> > #
> > # A fatal error has been detected by the Java Runtime Environment:
> > #
> > #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000001f9eba90167, pid=21340, tid=15904
> > #
> > # JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
> > # Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
> > # Problematic frame:
> > # v  ~BufferBlob::vtable chunks
> > #
> > # No core dump will be written. Minidumps are not enabled by default on client versions of Windows
> > #
> > # If you would like to submit a bug report, please visit:
> > #   https://github.com/AdoptOpenJDK/openjdk-build/issues
> > #
> 
> Are you monitoring your RAM usage around the time it crashes? You can use something like HWINFO64.
> 
> Maybe check Windows's Event Viewer for any error messages.

I had a look at my Windows's Event Viewer and looked for any error messages matching the timestamps of my crashes but couldn't find any matches. I've installed HWINFO64 and will be monitoring my RAM usage. What I've also done is enabled Minidumps for JVM crashes. Haven't had a crash since I've enabled that, so next time I get a crash I might have some more info on the JVM crash itself. Thanks for the suggestions ! I'll be looking around in the Event Viewer & googling about to make sure I am missing nothing.
Any other suggestions are very welcome, as I am still actively troubleshooting this problem.

**Comment by Nightfirecat** [comment] 2023-05-22 17:44
Duplicate of #10628, we don't know what causes this crash.

**Closed by Nightfirecat** 2023-05-22 17:44 UTC
Labels: duplicate
