### ISSUE TITLE
Medium Step  not recognoized 

### ISSUE THREAD

**Issue by ilexand** [runelite/runelite#18067] opened 2024-07-20 02:48 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

While doing medium clues, the clue "speak to Uglug Nar" doesnt get recognozied by the plugin

### Screenshots or videos

![image](https://github.com/user-attachments/assets/79354cf8-d890-4448-9781-13c3dad144ef)

### RuneLite version

Runelite version: 1.10.34
Launcher: 2.7.1

### Logs

[launcher.log](https://github.com/user-attachments/files/16318587/launcher.log)
[client.log](https://github.com/user-attachments/files/16318588/client.log)

**Comment by Felanbird** [comment] 2024-07-20 02:48
Duplicate of #18064

**Closed by Felanbird** 2024-07-20 02:48 UTC
Labels: needs-triage
