### ISSUE TITLE
Key Remapping forces Enter To Chat when unnecessary.  Give it a separate option.

### ISSUE THREAD

**Issue by BinaryElement** [runelite/runelite#9785] opened 2019-09-01 02:51 UTC
![Image](https://i.imgur.com/5beaETh.png)

I'd like to use Key Remapping simply to remap the Function keys (F1-F12, Escape), and do not want the press enter to chat feature (which was apparently implemented because of WASD camera controls).  However, if WASD camera controls is disabled, and no regular character keys are used for controls, it still forces Enter To Chat.  As in the preview image, it even forces Enter To Chat even if neither of its features are enabled.

My request is to make Enter To Chat a third, separate option.

**Comment by Alexsuperfly** [comment] 2019-09-01 03:13
duplicate of #9648 
what you want can be done in the vanilla f key interface

**Closed** 2019-09-01 06:20 UTC
Labels: duplicate
