### ISSUE TITLE
Additional Wilderness-only Player Indication option

### ISSUE THREAD

**Issue by chanmioo** [runelite/runelite#11074] opened 2020-03-26 05:43 UTC
add an additional option to highlight (non-clan member) players only while in the wilderness.
I think it would be convenient for players who go into the wilderness often and don't want to have to keep turning off and on highlighting non-clan members whenever you go to bank or GE where there's a dense amount of players.

🦄

**Comment by Nightfirecat** [comment] 2020-03-26 06:09
Duplicate of #3684

**Closed by Nightfirecat** 2020-03-26 06:09 UTC
Labels: duplicate
