### ISSUE TITLE
Show routes and traps on World map for Isafdar

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#5263] opened 2018-09-02 16:51 UTC
![image](https://user-images.githubusercontent.com/9074448/44958477-25cf0900-aee1-11e8-8050-d66e1f656154.png)
Everyone hates Isafdar for it's many traps and dangers. It would be nice to show possible routes with traps on the minimap, similar to this: https://vignette.wikia.nocookie.net/2007scape/images/5/5d/Isafdar_map.png/revision/latest?cb=20171126063612

**Comment by deathbeam** [comment] 2018-09-02 18:33
Duplicate of #4398. You are opening duplicates pretty constantly now, maybe it is time to learn how github search works

**Closed by deathbeam** 2018-09-02 18:33 UTC

**Comment by Gamer1120** [comment] 2018-09-02 18:39
I searched for Isifdar and nothing came up. I should have have put more effort into searching and will do so in the future.

**Comment by ShaunDreclin** [comment] 2018-09-02 19:36
I searched for it too cause I was pretty sure I saw this issue but that issue says "elven land" instead of Tirannwn or Isafdar, so it didn't show up.
