### ISSUE TITLE
Small Barrows Plugin Addition

### ISSUE THREAD

**Issue by tyd3** [runelite/runelite#6238] opened 2018-10-28 21:15 UTC
Barrows runs are fun, fast, and very profitable, but there is one thing that I haven't seen brought up as an issue that affects every single run: Where can I dig on the mounds?

I'd like to see a basic addition to the already existing Barrows plugin that simply highlights each Barrows brother's mound's tiles that can be dug to enter the crypt. Though it is clear that the top of the mounds are diggable tiles, there are tiles that extend off of it that are not consistent with each mound. Knowing where to dig would eventually add on minutes, and even hours to time saved during Barrows. It would be quite simple to just graphically have tiles appear, similar to how Woox is working on a plugin that shows the tiles that one cannot be in to try and reset aggro from monsters, like sandcrabs.

Maybe an entire new feature could be added to allow users to mark certain tiles on the ground and freely remove them as well. These would be remembered on login and would exist forever, so long as the player never deliberately removed them. Putting a limit on how many tiles could be highlighted would also help the game run well if this were to be added.

**Comment by Hydrox6** [comment] 2018-10-28 21:19
Duplicate of #4668

**Closed** 2018-10-28 21:36 UTC
