### ISSUE TITLE
Command that prints the raids layout

### ISSUE THREAD

**Issue by WaltervonGabain** [runelite/runelite#7736] opened 2019-02-07 07:56 UTC
After scouting for a raid I'd like it to have a !layout command so that my scouted raid gets shown in clan chat for my friends to see.

**Comment by deathbeam** [comment] 2019-02-07 09:03
I think https://github.com/runelite/runelite/pull/7715 solves this?

**Comment by WaltervonGabain** [comment] 2019-02-07 09:21
My bad, I'm glad it's already in the works!

**Comment by deathbeam** [comment] 2019-02-07 09:25
Its not merged yet, so the issue is still valid

**Closed** 2019-07-27 20:02 UTC
Labels: feature-request
