### ISSUE TITLE
Option to disable Agility shortcut highlight

### ISSUE THREAD

**Issue by Astug** [runelite/runelite#1984] opened 2018-04-26 16:51 UTC
Can an option be added to disable the newly added Agility shortcut highlights?

I actually like the highlights but for some shortcuts the highlights are so big (f.ex. [the water obelisk grapple shortcut](https://i.imgur.com/7sZpBlC.png) that I'd just prefer them off, unless it would be possible to filter certain shortcuts from being highlighted.

**Comment by deathbeam** [comment] 2018-04-26 16:52
Duplicate of #1981

**Closed by deathbeam** 2018-04-26 16:52 UTC
