### ISSUE TITLE
Option to search bank for alchables (by each)

### ISSUE THREAD

**Issue by SmithColin** [runelite/runelite#14389] opened 2021-11-19 00:41 UTC
I know there is already the feature that allows you to search bank for ha  > (some number) or even a range but when trying to find high alchs most of the things I see are stackables which total add up to greater than (some number).  So I was wondering if there is a way to search your bank for only items that each one costs more than some number.  When you examine an item it gives a total value and then a value for each of the items in the stack (HA value 2,640(1ea)) so would it be possible to search by ha > 500ea or something like that. Comparing only the each price and not the whole stack.

**Comment by raiyni** [comment] 2021-11-19 00:51
Duplicate of #12771

**Closed by raiyni** 2021-11-19 00:51 UTC
