### ISSUE TITLE
Suggestion: Toggle option for making runelite sidebar go to left or right

### ISSUE THREAD

**Issue by Jdyss** [runelite/runelite#12982] opened 2020-12-27 17:19 UTC
**I'm hoping you would add a toggle option where you can choose which side your sidebar shows. I'm thinking it would be best if you put it on runelite client settings so everyone can see it easily**

**Comment by Hydrox6** [comment] 2020-12-27 17:20
Duplicate of #1641

**Closed by Hydrox6** 2020-12-27 17:20 UTC
