### ISSUE TITLE
Fix window snapping on Windows 10 while 'Custom Window Chrome' is enabled

### ISSUE THREAD

**Issue by iawhd** [runelite/runelite#12186] opened 2020-07-18 13:53 UTC
**Describe the bug**
While the 'custom window chrome' setting is enabled, the runelite window will not snap to [Windows Snap](https://support.microsoft.com/en-gb/help/4027324/windows-10-snap-your-windows#:~:text=Use%20Snap%20to%20arrange%20all,the%20edge%20of%20your%20screen.&text=Drag%20it%20to%20the%20left,right%20half%20of%20the%20screen.) (or [Microsoft Powertoys](https://github.com/microsoft/PowerToys/wiki/FancyZones-Overview)) zones. This is inconvenient for people who play on large, high resolution monitors and don't want to have Runelite full-screen like myself. 

This setting can be found in the main 'Runelite' Plugin
![image](https://user-images.githubusercontent.com/29826207/87854228-6171f100-c908-11ea-82b9-df234f7b871f.png)

**Current behavior with 'Custom Window Chrome' enabled**
Window does not snap
![C](https://user-images.githubusercontent.com/29826207/87854208-35567000-c908-11ea-8b37-1baec28fefed.gif)

**Expected behavior**
![W](https://user-images.githubusercontent.com/29826207/87854212-3a1b2400-c908-11ea-9f29-0914534957c4.gif)

**To Reproduce**
Steps to reproduce the behaviour:
1. Drag window to edge of display with 'Custom Window Chrome' enabled.
2. Repeat step 1 with  with 'Custom Window Chrome' disabled

**Environment (please complete the following information):**
 - OS: Windows 10 May 2020 Update (v2004)
 - RuneLite version: 1.6.22
 - Launcher version: 2.1.0

**Comment by raiyni** [comment] 2020-07-18 15:39
Duplicate of https://github.com/runelite/runelite/issues/1953

**Closed by raiyni** 2020-07-18 15:39 UTC
