### ISSUE TITLE
GPU: Artifacts when using Compute Shaders

### ISSUE THREAD

**Issue by camdenmil** [runelite/runelite#11422] opened 2020-05-01 05:18 UTC
**Describe the bug**
Enabling the GPU plugin "Compute Shaders" option causes stretched artifacts to appear. Disabling compute shaders and restarting the plugin removes the artifacts.

**Expected behavior**
Compute shaders should produce geometry similar to that seen without the option enabled.

**Screenshots**
![Screenshot_2020-04-30_21-57-33](https://user-images.githubusercontent.com/10421769/80783234-eaf5fc00-8b2d-11ea-9379-7d9cc7fb1716.png)

**Environment (please complete the following information):**
 - OS: Arch Linux
   - Mesa 20.0.6-2
   - jre10-openjdk 10.0.2.u13-2 (GPU plugin causes instant crashes on jre11+ per #9630)
   - GPU Driver: xf86-video-amdgpu 19.1.0-1
 - Hardware:
   - AMD Ryzen 1700x
   - AMD RX Vega 64 8Gb VRAM
   - 16gb RAM
 - RuneLite version: 1.6.12
 - Launcher version: I'm running `runelite` from bash so I'm not sure I'm using a launcher. Info shows "Unknown" for launcher version.

**Additional context**
client.log:
```
2020-04-30 21:29:42 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-04-30 21:29:42 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-04-30 21:29:42 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 523627398.114
2020-04-30 21:29:43 [main] INFO  n.r.client.account.SessionManager - No session file exists
2020-04-30 21:29:43 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-04-30 21:29:44 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-04-30 21:29:45 [main] INFO  net.runelite.client.RuneLite - Client initialization took 4100ms. Uptime: 4635ms
2020-04-30 21:29:45 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,690,35,2188x1363,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,2188x1363,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@1e9f809a,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-04-30 21:29:46 [pool-2-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user camdenmil.
2020-04-30 21:54:22 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-04-30 21:54:23 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-04-30 21:54:23 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 523627398.114
2020-04-30 21:54:23 [main] INFO  n.r.client.account.SessionManager - No session file exists
2020-04-30 21:54:24 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-04-30 21:54:24 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-04-30 21:54:26 [main] INFO  net.runelite.client.RuneLite - Client initialization took 4330ms. Uptime: 4896ms
2020-04-30 21:54:26 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1004,31,2188x1363,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,2188x1363,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@647a7076,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-04-30 21:54:26 [pool-2-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user camdenmil.
```

**Comment by Nightfirecat** [comment] 2020-05-01 05:22
Duplicate of #11351

**Closed by Nightfirecat** 2020-05-01 05:22 UTC
Labels: duplicate
