### ISSUE TITLE
Minor bug -> Aerial fishing

### ISSUE THREAD

**Issue by MattNss** [runelite/runelite#13481] opened 2021-04-14 13:23 UTC
When Aerial Fishing on Molch Island, since the last update some spots stay highlighted. This means there is a fish seeable and the spot is surrounded, even when there is no fish available in that spot.

**Comment by Hydrox6** [comment] 2021-04-14 13:24
Duplicate of #7702

**Closed by Hydrox6** 2021-04-14 13:24 UTC
