### ISSUE TITLE
Show Non-Overhead Prayers as icon indicators.

### ISSUE THREAD

**Issue by TomMartow** [runelite/runelite#2955] opened 2018-05-19 15:46 UTC
Idea by @smkz#3832  on discord, I just created a quick concept.

Concept:

![image](https://user-images.githubusercontent.com/10462926/40270368-1a20a15a-5b84-11e8-94df-f9306917ad55.png)

**Comment by deathbeam** [comment] 2018-05-19 16:26
Duplicate of #1537

**Closed by deathbeam** 2018-05-19 16:26 UTC
