### ISSUE TITLE
Viewing any of the foliage in the Mushroom Meadow causes GPU usage to increase ~10x

### ISSUE THREAD

**Issue by Tylemagne** [runelite/runelite#6683] opened 2018-11-25 19:23 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
There's something wrong with the foliage there. It causes way more strain than it should on the GPU.

**To Reproduce**
Go to the Mushroom Meadow and zoom out. Any machine, no matter the GPU, will see a huge increase in GPU usage and a pretty big drop in framerate. I go from 50FPS/25% usage to about 20FPS/100% usage.

**Expected behavior**
It should have the same effect as other foliage. It can't just be the sheer amount. There's something with it that's very inefficient and harmful. It's making it impossible to do herbiboars.

**Environment (please complete the following information):**
Windows, latest RuneLite version, Radeon 270X.

**Additional context**
I'm aware some people have reported low framerates in this area, but I've actually investigated it. If I stand at the triple hardwoods and look at the grass, I'm fine. If I turn the camera, even just a little, to show the weird fungi over by the herbiboar holes, I get instant framerate drops.

**Comment by Nightfirecat** [comment] 2018-11-25 19:32
Duplicate of #6528

**Comment by Tylemagne** [comment] 2018-11-25 20:00
Nope. That OP's issue was due to Intel's GPU being used. This is due to the foliage.

**Closed** 2018-11-25 20:00 UTC

**Comment by deathbeam** [comment] 2018-11-25 20:01
Its still same issue, intel gpu doesnt matter in this case

**Comment by Tylemagne** [comment] 2018-11-25 20:30
Ok, I posted it there.
