### ISSUE TITLE
Respawn timers added to the slayer plugin

### ISSUE THREAD

**Issue by theIsaia** [runelite/runelite#14515] opened 2021-12-23 13:25 UTC
**Is your feature request related to a problem? Please describe.**
Currently the slayer plugin has the options to highlight npc's in the same fashion as the NPC indicator plugin, it has most of the features except respawn timers. so if I want respawn timers I have to use npc indicators AND slayer indicators at the same time.

**Describe the solution you'd like**
Adding the respawn timer functionality to the slayer plugin. 

**Describe alternatives you've considered**
Just use the Npc indicators and remember to untag the mob after im done.

**Additional context**
Not a big deal at all, would just be a nice QOL change. As it would only highlight mobs and show its respawn timers when im on task, makes it so I dont have 10 billion skeletons, dwarfs and other stuff tagged when im off task. Also is a nice way to see when I finish a task with the indicators disappearing. 
Kinda similar to this issue, https://github.com/runelite/runelite/issues/3730, but its rather old so not sure if the slayer plugin even had highlight functionality back then

**Comment by Hydrox6** [comment] 2022-01-04 18:48
Duplicate of #3730

**Closed by Hydrox6** 2022-01-04 18:48 UTC
