### ISSUE TITLE
Windows 10 - client focus on request does not work

### ISSUE THREAD

**Issue by Blinzerr** [runelite/runelite#8537] opened 2019-04-15 20:18 UTC
**Expected behavior**
Client is minimised - "Request focus on notification" should bring the RuneLite client in front of all other windows upon notification. Instead it only highlights the application and gives a tray notification.

I've also checked my notification OS and all RuneLite options have been enabled. Is there anything I can further do?

**Environment (please complete the following information):**
Windows 10
Latest RL Version

**Additional context**
I do not have this problem on my MacBook.

**Comment by Nightfirecat** [comment] 2019-04-15 20:19
Duplicate of #2335

**Closed by Nightfirecat** 2019-04-15 20:19 UTC
