### ISSUE TITLE
Pyramid Plunder

### ISSUE THREAD

**Issue by itsTwoUndeaD** [runelite/runelite#6302] opened 2018-11-01 20:27 UTC
I've noticed when doing Pyramid Plunder the doors to advance to the next room dont change every round. I was wondering if it was possible to make a plugin that tells you what door you successfully advanced in run prior to the current one. Allowing you to quickly go through the minigame to the deep levels w.o having to remember what door is the correct one to allow you to advance more quick and efficiently.

**Comment by Nightfirecat** [comment] 2018-11-01 20:32
Duplicate of #2446

**Comment by itsTwoUndeaD** [comment] 2018-11-01 20:34
Yes But is going to be implemented? or is it something that would get approved?

**Comment by steffenhauge** [comment] 2018-11-01 20:35
Highlighting/remembering the correct door, most likely not.

**Comment by itsTwoUndeaD** [comment] 2018-11-01 20:36
>           Highlighting/remembering the correct door, most likely not.
Thank you.

**Comment by Nightfirecat** [comment] 2018-11-01 20:37
That's to be discussed on the issue which this is a duplicate of. There's no reason to track this feature request twice.

**Comment by itsTwoUndeaD** [comment] 2018-11-01 20:38
@Nightfirecat No worries there man. Didnt know if reviving dead threads was a thing on here.

**Closed by Nightfirecat** 2018-11-01 20:37 UTC
