### ISSUE TITLE
Trident, Blowpipe and Serpentine Helm Charges

### ISSUE THREAD

**Issue by balong1996** [runelite/runelite#4460] opened 2018-07-23 04:35 UTC
Is it possible that we could add a display how many charges left in Trident of the Swamp or Blowpipe at the Combat Option a.k.a combat style tab, because it kinda hassle to right click and check (I'm lazy)
For Serpentine Helm, can it be displayed on the Equipment Menu? 😄 

Hope this feature goes in the client 😃

**Comment by basicDamen** [comment] 2018-07-24 17:45
Seems like this was already in the works, but, utilizes a very intricate form of tracking.. Not to sure if this would be pushed through.. #2990

**Comment by Alexsuperfly** [comment] 2019-07-28 18:52
duplicate of #953

**Closed** 2019-08-12 16:41 UTC
Labels: feature-request
