### ISSUE TITLE
Farming Timer to Show Protection status for Relevant crop plots

### ISSUE THREAD

**Issue by russel204** [runelite/runelite#8300] opened 2019-03-24 00:26 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

It' s not a problem. Just a suggestion to improve timers.

**Describe the solution you'd like**
It would be nice if the farming timers would show crop protection status. Similar to how birdhouses show green when filled in the timers and orange(ish) when you forgot the seeds. Crops/Plants could be orange(ish) when planted but unprotected and green when protected.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
Honestly haven't been able to come up with a different way to do this.

**Additional context**
Example of what I mean. This is a pic of a birdhouse that isnt filled with seeds in the timers. This could be the unprotected status of the crops/trees etes.
https://gyazo.com/29d2bdcbf7428738f9577e5daca5d2ce

**Comment by Hydrox6** [comment] 2019-03-24 00:28
Duplicate of #7941

**Closed** 2019-03-24 00:32 UTC
