### ISSUE TITLE
Efficient hours played (Ehp) on the high-score (lookup option)

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#2518] opened 2018-05-09 16:55 UTC
![image](https://user-images.githubusercontent.com/37475765/39828153-f4ab4e68-53b1-11e8-911e-3f58b0e2dd82.png)

it will be good if we can see the players ehp when we lookup someone? this will be a good feature, its not a big thing but i think it will be awesome to have?

**Comment by deathbeam** [comment] 2018-05-09 17:09
Duplicate of #720

**Closed by deathbeam** 2018-05-09 17:09 UTC
