### ISSUE TITLE
Arceuus Library Varlamore Envoy suggestion

### ISSUE THREAD

**Issue by Jskelling** [runelite/runelite#10975] opened 2020-03-07 03:53 UTC
Varlamore Envoy can only ever be used in a quest, and never be requested. Currently, there is a way to toggle off the Varlamore Envoy book in the UI, but without proper foreknowledge about this book and what it's used for it appears to just be a normal library book, which can cause confusion and needless support requests due to the fact that searching for and not finding the book will reset your library plugin layout.

I would suggest one or more of these changes:
A) Exclude the Varlamore Envoy book from resetting the plugin's library layout, as well as from contributing to finding the current layout
B) Visually differentiate between the Varlamore Envoy and every other book, thus encouraging users to look into the book more if they encounter an issue.
C) Warn the user in some way that Varlamore Envoy is ONLY used during a quest, and make them aware of the option to disable it.

**Comment by Nightfirecat** [comment] 2020-03-19 18:54
This is mostly a duplicate of #10296 in that we need better handling of the Varlamore Envoy--both in tracking it for the layout and in how and when it is shown in the overlay.

**Closed by Nightfirecat** 2020-03-19 18:54 UTC
Labels: duplicate
