### ISSUE TITLE
[Request] OSRSbeatz music replacement.

### ISSUE THREAD

**Issue by Jufinda** [runelite/runelite#11291] opened 2020-04-16 21:49 UTC
A plugin that replaces all the in-game music with the remixes produces by OSRSBeatz.

Where available, all songs that don't have a beat would remain the original until a beat was made.

**Comment by Hydrox6** [comment] 2020-04-16 21:50
Duplicate of #3390

**Closed by Hydrox6** 2020-04-16 21:50 UTC
