### ISSUE TITLE
RuneLite GPU plugin causes 100% usage with Vega64 / Mesa

### ISSUE THREAD

**Issue by joakim-i** [runelite/runelite#9254] opened 2019-07-01 02:15 UTC
**Describe the bug**
Enabling the RuneLite GPU plugin causes 100% GPU usage

**To Reproduce**
Enable the RuneLite GPU plugin
**Expected behavior**
A rational use of the GPU power
**Screenshots**

**Environment (please complete the following information):**
 - OS: Manjaro rolling release
 - RuneLite version: 1:1.5.27-1
 - Launcher version: N/A
 - GPU: Vega 64
 - OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.3.6
 - OpenGL version string: 4.5 (Compatibility Profile) Mesa 18.3.6
 - OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.3.6
 - openjdk version "1.8.0_212"

**Additional context**
Logs does not provide any useful data
Ive tried both the included Mesa version for Manjaro and also specifically compiled the older version which was mentioned by the FAQ with no better results. I might add that when I used to have a GTX 1070 I did not have the described issue with the Nvidia propietary drivers.

Not a perfectly encoded video but it demonstrates the issue very well: 
https://www.youtube.com/watch?v=zrvJ-6H2J7c

**Comment by Telavus** [comment] 2019-07-06 16:13
Tried with the mesa-git 19.2.0 version instead and it does not seem to have helped either.

**Comment by Telavus** [comment] 2019-07-14 08:21
Trace log: 
https://drive.google.com/open?id=1GP5JnWw4BTpSz0mY1KYB91js8ASJoWS_

**Comment by Telavus** [comment] 2019-07-14 22:44
lspci -vvvv
https://pastebin.com/iQ63w7H9

**Comment by Telavus** [comment] 2019-07-15 01:14
umr --top
https://pastebin.com/p2qz7Whb

**Comment by Telavus** [comment] 2019-09-06 20:32
I tried an identical setup but instead of using mesa with my Vega GPU i used the non-free drivers along with a Nvidia GTX 1050, which worked flawlessly. Just thought I'd let whoever that reads this know.

**Comment by Nightfirecat** [comment] 2022-07-10 04:01
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:01 UTC
Labels: bug, gpu
