### ISSUE TITLE
Save several client size and position settings

### ISSUE THREAD

**Issue by buldosis** [runelite/runelite#5485] opened 2018-09-14 05:40 UTC
For when you need specific client size/screen position for different acitivites.

I'd like to see a similar interface as screen markers do to save these settings. 
https://imgur.com/a/xv1XZ5W
An add setting button like screenmarkers.
After this a "save current client size" "save current client position" "save both" options.
Renaming ability. (again like screen markers)
A delete setting option.
And of course a "use" option that sets the client in position/size that one has saved.

**Comment by deathbeam** [comment] 2018-09-14 05:44
Duplicate of #4829

**Closed by deathbeam** 2018-09-14 05:44 UTC
