### ISSUE TITLE
Runecrafting Pouches QOL

### ISSUE THREAD

**Issue by pqt** [runelite/runelite#14400] opened 2021-11-22 17:10 UTC
**Is your feature request related to a problem? Please describe.**
Runecrafting sucks, Jagex seems to enjoy our pain. I'm trying to tilt the scales ever so slightly.

**Describe the solution you'd like**
- An essence count of how many are in each RC pouch.
- Secondary count (perhaps through example text or something?) showing uses left before decay effect takes place.

**Describe alternatives you've considered**
This could also be a canvas module – closer to how Slayer tasks work – instead of an item-attached visual?

**Additional context**
Partial duplicate of #1007, #4651, #8352. They consist of the decay effect but do not include details about the count of contained essence.

**Comment by Hydrox6** [comment] 2021-11-22 17:12
`Essence Pouch` on the hub does the counted essence

Duplicate of #1007

**Closed by Hydrox6** 2021-11-22 17:12 UTC
