### ISSUE TITLE
Text isn't alligned with the mouse position

### ISSUE THREAD

**Issue by rafaelntom** [runelite/runelite#11157] opened 2020-03-31 18:25 UTC
Whenever i hover over an item, npc or anything else, the option does not apper bellow the mouse, for some wierd reason it's appearing far right from it.

I did not change anything at all on runelite, it just started doing it randomly

Also when i used to hover over my items, like the rune pouch it would have an option bellow it, now it doesn't

![ezgif com-crop](https://user-images.githubusercontent.com/52077974/78061493-b262d700-7363-11ea-8aa0-ca523756bbd8.gif)

**Comment by Alexsuperfly** [comment] 2020-03-31 18:30
I believe this is caused by snapping the tooltip to a corner because it recently became layoutable.  i have fixed that in #11126.

Delete the line in your settings that contains `runelite.TooltipOverlay_preferredPosition` to fix that.  If you need more assistance on topics such as this join us on [Discord](https://runelite.net/discord), since it is much easier to provide support of this type there.

**Comment by Nightfirecat** [comment] 2020-03-31 18:46
I agree, this should be fixed in master already. For now, the solution Alex gave will address that issue for you now. After our next release, this should no longer be possible to reproduce.

**Closed by Nightfirecat** 2020-03-31 18:46 UTC
Labels: bug
