### ISSUE TITLE
[Bug] Blue line on minimap on 2005-interface

### ISSUE THREAD

**Issue by Duradel** [runelite/runelite#8951] opened 2019-05-29 20:01 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/45245047/58587256-37212800-825d-11e9-9a79-53f1372a8396.png)

**To Reproduce**
Enable 05 interface, Fixed mode, Skybox/GPU mode on

**Comment by Hydrox6** [comment] 2019-05-29 20:02
Duplicate of #7235

**Closed by Hydrox6** 2019-05-29 20:02 UTC
