### ISSUE TITLE
Side panel drawing over itself 

### ISSUE THREAD

**Issue by sammybun** [runelite/runelite#13359] opened 2021-03-20 18:22 UTC
**Describe the bug**
Opening up the side panel causes it to draw over each other. I have tried reinstalling, deleting .runelite, and using a fresh profile but the bug continues to happen.  

**To Reproduce**
1.  Open side panel

**Expected behavior**
To be able to use the side panel :(

**Screenshots**
![RuneLite_WUq18QIYUh](https://user-images.githubusercontent.com/13594065/111881560-e96c3700-897e-11eb-9f93-7c5de1f0e175.png)
![RuneLite_7T2NBXhccv](https://user-images.githubusercontent.com/13594065/111881589-0dc81380-897f-11eb-9bba-37c0164c8cac.png)

**Environment**
 - OS: [Windows]
 - RuneLite version: [1.7.2.2]
 - Launcher version: [2.1.6]
 - GPU [2080 ti]
 - CPU [i5-10600k]

**Additional context**
[client.log](https://github.com/runelite/runelite/files/6176152/client.log)

**Comment by Hydrox6** [comment] 2021-03-20 18:22
Duplicate of #11727

**Closed by Hydrox6** 2021-03-20 18:22 UTC
