### ISSUE TITLE
MenuEntrySwapper add "Cast Bloom" to silver sickle (b) as default left click

### ISSUE THREAD

**Issue by Yevey** [runelite/runelite#10426] opened 2019-12-11 09:42 UTC
Really a request. I went and tried adding it myself via making it, but I don't know how to code it in properly. I'm sure it's not too hard to begin with?

**Comment by Hydrox6** [comment] 2019-12-11 12:58
Duplicate of #1848

**Closed by Hydrox6** 2019-12-11 12:58 UTC
