### ISSUE TITLE
Seed/Sapling Identifiers Show Through Map

### ISSUE THREAD

**Issue by jcarrara** [runelite/runelite#12728] opened 2020-10-31 22:28 UTC
When you have a seed or sapling in your bank with identifier text on, 

![bank](https://user-images.githubusercontent.com/45108060/97791251-c515e680-1ba6-11eb-9bce-5576904d507e.jpg)

if you pull up the world map the text will show over it.

![map](https://user-images.githubusercontent.com/45108060/97791252-c5ae7d00-1ba6-11eb-8370-b5477d24fb39.jpg)

**Comment by Hydrox6** [comment] 2020-10-31 22:33
Duplicate of #11534

**Closed by Hydrox6** 2020-10-31 22:33 UTC
