### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by higuybye** [runelite/runelite#15216] opened 2022-06-25 22:43 UTC
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Constant crashing. Been happening for a while not sure what to do. It is random when it comes to timing but seems to happen at the worst times

### Logs

[jvm_crash_pid_5452.log](https://github.com/runelite/runelite/files/8985677/jvm_crash_pid_5452.log)

**Comment by MESLewis** [comment] 2022-06-25 22:44
Many 3rd party plugins from the pluginhub break the client in subtle or not-so-subtle ways, including causing issues like client freezes. We do not support 3rd party plugins because we do not make or quality control them, and do not recommend their use.

You can run RuneLite in safe mode to temporarily disable all 3rd party plugins via "%localappdata%\runelite\runelite.exe" --clientargs --safe-mode which will allow you to confirm the issue is caused by the plugin and isn't a core RuneLite issue.

If the issue is caused by a 3rd party plugin, you should isolate which plugin it is and then uninstall the plugin.

**Comment by problemsproblemsyes** [comment] 2022-08-20 23:06
I have similar crashes with similar error codes. Another person has the same problem. All 3 of us are using Ryzen 7/9 5800x/5900x. Maybe related to that? I have searched litereally every forum on 0xc0000005 error solutions. Non seem to work for me. Note: I have no additional plugins installed at all, just RuneLite vanilla

**Comment by Nightfirecat** [comment] 2023-05-24 05:08
Duplicate of #10628, we don't know what causes this crash.

**Closed by Nightfirecat** 2023-05-24 05:08 UTC
Labels: duplicate
