### ISSUE TITLE
Item Juggling add-on

### ISSUE THREAD

**Issue by AvOeffelen** [runelite/runelite#4139] opened 2018-07-02 22:30 UTC
Hey guys,

I was wondering that you guys can maybe make a item juggling add-on. Just as basic as possible.
Something like; If you enable the plugin that a square around the item lights up with a timer till dissapearing?

If you want a more clear explaination just mention me and i'll try to explain myself a little bit better

Armando

**Comment by deathbeam** [comment] 2018-07-02 22:32
Duplicate of #2383

**Closed by deathbeam** 2018-07-02 22:32 UTC
