### ISSUE TITLE
Idle notification doesn't work while woodcutting

### ISSUE THREAD

**Issue by jadgsolutions** [runelite/runelite#17666] opened 2024-04-02 09:36 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Idle notification doesn't work while woodcutting .

Steps to reproduce:

1. Go to Ape Atoll
2. Equip Ninja monkey greegree (as to not aggro jungle spiders)
3. Chop down teak trees
4. Witness no notification when done/interrupted

### RuneLite version

RuneLite version: 1.10.26.1
Launcher version: 2.6.7

**Comment by Felanbird** [comment] 2024-04-02 09:37
Duplicate of #547

**Closed** 2024-04-02 11:36 UTC
Labels: needs-triage
