### ISSUE TITLE
Animation smoothening bug rum deal

### ISSUE THREAD

**Issue by RobinLaevaert** [runelite/runelite#11466] opened 2020-05-04 22:41 UTC
**Describe the bug**

The signs of the zombie protesters during the rum deal quest glitch out in a major way.

**Screenshots**
![gif of issue](https://im5.ezgif.com/tmp/ezgif-5-149cdbb0d5fe.gif)

**Environment (please complete the following information):**
 - Windows
 - RuneLite version: 1.6.3
 - Launcher version: 2.0.2

**Comment by melkypie** [comment] 2020-05-04 22:44
Duplicate of #8206

**Closed** 2020-05-04 22:48 UTC
