### ISSUE TITLE
Screenshot Nearby Player Deaths

### ISSUE THREAD

**Issue by SeedPack** [runelite/runelite#9812] opened 2019-09-05 00:17 UTC
**Is your feature request related to a problem? Please describe.**
No, just an idea

**Describe the solution you'd like**
Add an option to the screenshot plugin to have the client take a screenshot of other players nearby when they die. Such as only players who are in the same clan chat and/or friend's list.

**Describe alternatives you've considered**
I'm aware that you can set a certain key to take a screenshot. So this is in the case of you not recognizing a player dying nearby or forgetting to take a screenshot etc

**Additional context**
I'd imagine it would be difficult to make this an option or even possible. It would be pretty neat to have a screenshot(s) of a friend dying to look back on in my opinion.

**Comment by Alexsuperfly** [comment] 2019-09-05 00:17
duplicate of #8744

**Closed** 2019-09-05 00:18 UTC
Labels: duplicate
