### ISSUE TITLE
Thrall hit overrides BGS spec counter

### ISSUE THREAD

**Issue by ColemanDunn** [runelite/runelite#13842] opened 2021-07-06 04:55 UTC
**Describe the bug**
Not sure if it is fixable but if I hit a BGS spec at the same tick that my thrall hits, the thrall hit takes priority for the BGS special attack counter. So if I hit a 60 and the thrall hits a 2 the counter says 2

**To Reproduce**
BGS spec an npc at the same time your thrall hits an npc

**Expected behavior**
in my example above the BGS counter should say 60

**Comment by Nightfirecat** [comment] 2021-07-13 05:04
Sadly this may not be fixable.

**Comment by Hydrox6** [comment] 2021-07-14 16:54
Duplicate of #12008

**Closed by Hydrox6** 2021-07-14 16:54 UTC
Labels: bug
