### ISSUE TITLE
Runelite closes when streaming through discord

### ISSUE THREAD

**Issue by Majst** [runelite/runelite#9346] opened 2019-07-12 03:44 UTC
When streaming the runelite application to a discord call using the screen share option, the game seems to close a lot really easily. If you click on other applications or discord it just seems to randomly instantly close. I know this may be an issue with discord but thought I would start here.

**Comment by Nightfirecat** [comment] 2019-07-12 05:16
Duplicate of #9277 (unless you have the GPU plugin off, please comment here if you are experiencing crashes with it disabled)

**Closed by Nightfirecat** 2019-07-12 05:16 UTC

**Comment by skant33** [comment] 2019-10-15 12:36
Same issue with GPU turned off on Windows 7
