### ISSUE TITLE
Seperate filter for noted & unnoted drops

### ISSUE THREAD

**Issue by Hexosaurus** [runelite/runelite#1988] opened 2018-04-26 17:19 UTC

**Comment by deathbeam** [comment] 2018-07-08 01:37
Duplicate of #1123

**Closed by deathbeam** 2018-07-08 01:37 UTC
Labels: feature-request

**Comment by khogeland** [comment] 2026-08-03 06:28
This is not a duplicate, a noted stack of 1 is a very different item than a single unnoted item. I want to be able to pick up, for example, noted ore and bars, but hide unnoted ones which will clog my inventory when spam looting barrage tasks.
