### ISSUE TITLE
Client crash with GPU plugin and discord screensharing

### ISSUE THREAD

**Issue by TnnrTS** [runelite/runelite#9277] opened 2019-07-03 22:53 UTC
Issue occurs when using the GPU plugin while using the discord screen-sharing feature -- works fine with full screen sharing but not the individual app sharing. Sometimes the runelite client will crash, other times the runelite client will behave normally, but the shared screen in discord will flash black randomly and whenever clicking off of the runelite client. 

The issue only occurs when the GPU plugin is enabled, everything works correctly with it turned off.

Have experienced this issue personally as well as with several friends on their machines. 

Windows 10, latest version of java.

![image](https://user-images.githubusercontent.com/45900650/60629456-75a98580-9dbb-11e9-92cb-901dd35cc4f5.png)

**Comment by ypperlig** [comment] 2019-07-05 00:10
I tried sharing the client as well and got the following error:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa904d19db, pid=9904, tid=0x0000000000005414
#
# JRE version: Java(TM) SE Runtime Environment (8.0_162-b12) (build 1.8.0_162-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.162-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# CGLDebugMessageHandler: GLDebugEvent[ id 0x500
	type Error
	severity High: dangerous undefined behavior
	source GL API
	msg GL_INVALID_ENUM error generated. Operation is not valid from the core profile.
	when 1562284151798
	source 4.5 (Core profile, arb, debug, compat[ES2, ES3, ES31, ES32], FBO, hardware) - 4.5.0 NVIDIA 417.35 - hash 0x1c1ced17]
  0x00007ffa904d19db

**Comment by OliverBroadbent** [comment] 2019-07-19 07:15
+1 Also getting this issue

**Comment by Nightfirecat** [comment] 2022-07-10 04:02
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:02 UTC
Labels: bug, discord, gpu, not-our-bug
