### ISSUE TITLE
Decide what goes in your infoboxes

### ISSUE THREAD

**Issue by smgithub1** [runelite/runelite#7556] opened 2019-01-25 16:38 UTC
Hello, I feel some of the timers displayed in the infoboxes could be better displayed elsewhere, such as a second list of info boxes.

An [example picture](https://i.imgur.com/L9cYzZ9.png) of where you can run into this issue. The info overlaps to a second line over items in your invent. 

I know this could be solved by making the boxes smaller but then they become hard to read. It could also be fixed by moving the info box however people have their favourite positions for the info boxes and this is common position for many players. I'm also aware you can disable boss timers and other times so they don't show, but again I don't think that is a good solution.

Ideally an option for only potion boosts/timers would be displayed in this info box and everything else such as boss respawn timers, imbued heart timer, teleport timers etc would be displayed in a second optional infobox list somewhere else.

One other fix could be an option for the overlapping info to go to a left column instead of currently defaulting to the right overlapping via the invent.

**Comment by deathbeam** [comment] 2019-01-25 16:39
Duplicate of #1785

**Closed by deathbeam** 2019-01-25 16:39 UTC
