### ISSUE TITLE
RFC: Bird House infoboxes | Hunter plugin.

### ISSUE THREAD

**Issue by PandahRS** [runelite/runelite#4058] opened 2018-06-28 20:21 UTC
**Is your feature request related to a problem? Please describe.**
Not quite a problem, but it is more a quality of life issue.

**Describe the solution you'd like**
An infobox or additional entry within the Hunter plugin to keep track of the bird houses you've set up for hunter. I'm not sure what the difficulty of this is and if there's anything in game that tracks the bird houses. I wouldn't mind working on this myself as long as I can make it accurate.

**Describe alternatives you've considered**
Setting up a timer to count down 50 minutes after the last restocked birdhouse. 

**Additional context**
N/A.

**Comment by deathbeam** [comment] 2018-06-28 20:22
Duplicate of #1224

**Closed by deathbeam** 2018-06-28 20:22 UTC
