### ISSUE TITLE
Loot Tracker Changes

### ISSUE THREAD

**Issue by hkbertoson** [runelite/runelite#10450] opened 2019-12-16 17:16 UTC
Loot Tracker shows all loot dropped even if it is not picked up. 

Is there any way to be able to toggle loot tracker to only keep track of Picked up drops?
This feature could be turned off or on at the users discretion.

**Comment by Hydrox6** [comment] 2019-12-24 17:44
Duplicate of #10245

**Closed by Hydrox6** 2019-12-24 17:44 UTC
