### ISSUE TITLE
Ground Markers button to cleanup all markers

### ISSUE THREAD

**Issue by Sovexe** [runelite/runelite#2200] opened 2018-04-30 22:35 UTC
Button that will delete all ground markers you have created rather than needing to do it one by one. May want to include a deletion confirmation.

Alternatively an easier method to quickly delete unwanted ground markers (or both).

**Comment by deathbeam** [comment] 2018-04-30 22:41
Duplicate of #1989

**Closed by deathbeam** 2018-04-30 22:41 UTC
