### ISSUE TITLE
Screen Markers: Grouping

### ISSUE THREAD

**Issue by adm1n1stra1tor** [runelite/runelite#4837] opened 2018-08-11 10:03 UTC
This would be handy to quickly enable/Disable the countless of screen markers, that some skills require. 

This would also be handy to map several Resolutions
For example;
"Lava RC - 1280 x 720"
(Group containing several markers)
"Lava RC - Fullscreen"
(Group containing several markers)
"Construction - Mahogony, Normal mode - 1280x720"

Regards

**Comment by deathbeam** [comment] 2018-08-11 10:53
Always search for existing issues first before opening new one, this is duplicate of #3205

**Closed by deathbeam** 2018-08-11 10:53 UTC
