### ISSUE TITLE
Camera Speed Control 

### ISSUE THREAD

**Issue by GigaBiteYTT** [runelite/runelite#12013] opened 2020-06-28 11:23 UTC
I downloaded RuneLite to get back into Runescape and I love the features it adds, but there's one thing that's stopping me diving in fully, that being that there doesn't seem to be a way to control the camera speed

I've gotten accustomed to games like shooters and other MMOs allowing me to control the sensitivity for controlling my mouse cursor in the menus and the sensitivity for my camera independently but I can only seem to do one or the other in Runescape.

If I focus on being able to click things and menu faster by setting a program specific DPI profile I can click things and menu comfortably but if I need to adjust my camera I find myself using only my wrist to move the camera because it's so sensitive; in every other game I'm accustomed to using more of my arm to avoid injuring my wrist.

If I focus on setting the DPI profile so that I can control the camera comfortably menuing becomes slow and tedious, I could set some sort of DPI switch specifically for controlling the camera but that seems excessive for something such as this.

Simple sliders/numeric controls for the camera speed and the mouse cursor speed independently would be very appreciated

**Comment by Hydrox6** [comment] 2021-02-02 16:53
Duplicate of #7744

**Closed by Hydrox6** 2021-02-02 16:53 UTC
Labels: feature-request, internal
