### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by bugginben** [runelite/runelite#5092] opened 2018-08-23 21:13 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to complete some calculations for the total pricing of items and I have to open up a separate calculator application to do these.

**Describe the solution you'd like**
In the calculator plugin, the addition of a normal calculator would fix this issue.

**Comment by Nightfirecat** [comment] 2018-08-23 21:15
Duplicate of #3967

**Closed** 2018-08-23 21:37 UTC
