### ISSUE TITLE
Melee Attack Timer

### ISSUE THREAD

**Issue by hrabosky** [runelite/runelite#9237] opened 2019-06-28 09:58 UTC
**Is your feature request related to a problem? Please describe.**
The problem is I am very bad at attempting to prayer flick when it comes to prayers like rigour and piety, and thought there must be a better way.

**Describe the solution you'd like**
I would like a little stop-watch like timer that times down from when your next attack will hit. that way you can turn on your prayer right between .5 and .01 and be able to consistantly time your prayer flicks

**Describe alternatives you've considered**
Looked to see if anything liked that existed. I do alright, but tasks l ike turoths when I have to switch up my melee weapon and the speeds are different throws me off.

**Additional context**
I hope it's considered, I believe many would like it.

**Comment by Nightfirecat** [comment] 2019-06-28 15:42
Duplicate of #4087

**Closed by Nightfirecat** 2019-06-28 15:42 UTC
