### ISSUE TITLE
Ability to have multiple sidebar tabs open at the same time.

### ISSUE THREAD

**Issue by MechaJeb** [runelite/runelite#10593] opened 2020-01-13 15:59 UTC
I'd really like to be able to have several sidebar tabs open at the same time, without having to switch through them. An example mock-up in attached files. 

Thank you.  

![2020-01-13_17-25-25](https://user-images.githubusercontent.com/47293991/72270773-5757f880-362e-11ea-901e-c6d77ae317c3.png)

**Comment by Hydrox6** [comment] 2020-01-13 16:04
Duplicate of #9897

**Closed by Hydrox6** 2020-01-13 16:04 UTC
