### ISSUE TITLE
Wilderness combat levels

### ISSUE THREAD

**Issue by callmekaze** [runelite/runelite#4700] opened 2018-08-04 13:39 UTC
I have been spending a lot of time in the wilderness, mostly at revs and was curious if there was a way that combat levels can be set up to show on players, so when they are around you its easier to know when to log for pkers, or how for higher levels so that you can actually get kills.

I was thinking about maybe having their names pop up in color based on cmb levels, and have it so that you can set the colors and levels up to your liking, similar to how item drops are set up.

**Comment by deathbeam** [comment] 2018-08-04 15:14
Duplicate of #3103

**Closed by deathbeam** 2018-08-04 15:14 UTC
