### ISSUE TITLE
Fishing type overlay displaying twice for some fishing spots

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#5517] opened 2018-09-16 21:10 UTC
I have no idea what is causing it, but on my screen the Fishing type overlay displays twice:
![image](https://user-images.githubusercontent.com/9074448/45600963-87c15f80-ba05-11e8-9979-86bc46e7088b.png)
![image](https://user-images.githubusercontent.com/9074448/45600968-8bed7d00-ba05-11e8-9085-945c30a1934e.png)
![image](https://user-images.githubusercontent.com/9074448/45600971-91e35e00-ba05-11e8-9aff-d33a798f7e8a.png)
A client restart will probably fix it, but this shouldn't happen in the first place. My settings:
![image](https://user-images.githubusercontent.com/9074448/45600978-a7f11e80-ba05-11e8-8ee1-22c6df6ef480.png)
![image](https://user-images.githubusercontent.com/9074448/45600992-d1aa4580-ba05-11e8-8f0c-b04c21fb2a37.png)

**Comment by deathbeam** [comment] 2018-09-16 21:11
Duplicate of #1392

**Closed by deathbeam** 2018-09-16 21:11 UTC
