### ISSUE TITLE
Fishing Icons displayed twice

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#7133] opened 2019-01-01 05:36 UTC
![Doubled Icons](https://i.imgur.com/ETUfl23.png)

Fishing icons are getting displayed twice. Not sure what's causing this, it's being displayed on fishing spots I am not fishing at as well as ones that I am fishing at.

It seems to last up until my inventory is full, at which point it fixes itself.

**Comment by Nightfirecat** [comment] 2019-01-01 06:34
Those are tiles where two fishing spots exist at the same location, it is expected behavior.

**Comment by Spedwards** [comment] 2019-01-01 06:42
Oh, didn't realise that was even a thing. Should two icons be displayed then if it's the same type of fishing spot then? Kind of redundant to show multiple.

**Comment by Nightfirecat** [comment] 2019-01-01 07:47
Duplicate of #1392

**Closed** 2019-01-01 07:47 UTC
