### ISSUE TITLE
Chat Recolor Improvement - Themes/Presets

### ISSUE THREAD

**Issue by areteCocoa** [runelite/runelite#3536] opened 2018-05-31 19:08 UTC
The Chat Recolor is very daunting to change every color manually to achieve something. Instead of the menu showing the list of colors, would it be better to have a list of presets and the colors hidden behind a "customize themes" menu? This would allow the level of customization that is currently achievable while also allowing users who don't want to manually change every color to use the feature.

Interested to know what people think. I think this feature has a lot of power that can make the chat box a little more usable.

**Comment by deathbeam** [comment] 2018-09-02 18:56
Duplicate of #2220

**Closed by deathbeam** 2018-09-02 18:56 UTC
Labels: feature-request
