### ISSUE TITLE
Bug: Hiscore not auto filling after update

### ISSUE THREAD

**Issue by Caia-OSRS** [runelite/runelite#3203] opened 2018-05-24 12:30 UTC
Hiscore does not auto fill from cc or nearby players. Also does not allow double click to auto fill username.

**Comment by Kamielvf** [comment] 2018-05-24 12:30
You can double-click the search icon inside the text field and it will lookup your own player name.

**Comment by Caia-OSRS** [comment] 2018-05-24 12:32
Ah ok fair enough, am i missing something with the other issue of nearby players and in cc?

**Comment by Adam-** [comment] 2018-05-24 12:32
duplicate of #3202

**Closed by Adam-** 2018-05-24 12:32 UTC
