### ISSUE TITLE
Set a keyboard function to take screenshot

### ISSUE THREAD

**Issue by DinklebergX** [runelite/runelite#1501] opened 2018-04-14 00:25 UTC
Currently you can only take screenshots on the client by using the camera button on the top of the client would it be possible to make it so a keyboard function can take a screenshot for you. Ex: prt sq key, home key, scr lk key, ETC

**Comment by Adam-** [comment] 2018-04-14 02:14
Duplicate of #1013

**Closed by Adam-** 2018-04-14 02:14 UTC
