### ISSUE TITLE
[Suggestion] Actions left Calc for Melee Skills depending on Enemy Max HP

### ISSUE THREAD

**Issue by DarkSoulsEater** [runelite/runelite#2965] opened 2018-05-19 18:01 UTC
Basically, one type of enemy has the same HP. 1 Dmg is 4 XP for Melee.

So why not calculate when attaking an enemy, how many enemeis of this kind you have to kill, to have a Level Up? Like when an enemy has 10 HP, so you get 40 XP for killing him in Defense/Strenght/Attack.

It would be rather useful, definetly better than "Actions left" consantly recalculating cause its based on the dmg of the last hit. Ye, good that i have to hit 200 more times with 10 Dmg, could just aswell calculate them manually.

**Comment by deathbeam** [comment] 2018-05-19 23:05
Duplicate of #1594

**Closed by deathbeam** 2018-05-19 23:05 UTC
