### ISSUE TITLE
Suggestion: OSRS Soundtrack Playlist

### ISSUE THREAD

**Issue by Blightist** [runelite/runelite#14871] opened 2022-04-16 17:32 UTC
A plugin to create playlists for the OSRS in game tracks.  

RS3 has a feature to right click a track and add it to a playlist.  
I would love to have this implemented into Runelite somehow.

**Comment by Hydrox6** [comment] 2022-04-16 18:05
Duplicate of #6093

The music engine for OSRS is really really painful to mess with, sadly. An external listening method is much easier and better.

**Closed by Hydrox6** 2022-04-16 18:05 UTC
