### ISSUE TITLE
Bird house reminder.

### ISSUE THREAD

**Issue by Floukru** [runelite/runelite#3669] opened 2018-06-07 09:42 UTC
**Is your feature request related to a problem? Please describe.**
No, it's not a problem it's just a suggestion just like the zaff staff shop (battlestaff in varrock). I always keep forgetting about my birdhouses until it's 3-4 hours.. And I need to be more efficient by coming to the bird house every 1 hour.

**Describe the solution you'd like**
A reminder to say "Check your birdhouses - they are done." Every hour or 50 minutes. 

Or maybe add a small infobox with the icon 
![image](https://user-images.githubusercontent.com/38350898/41091849-385eda08-6a50-11e8-86f1-c8efd0b1d842.png) saying "Check".

 
> The bird house must be filled with hop seeds as bait, up to a maximum of 10, or 5 if using wildblood seeds. After doing so, the bird house will passively capture birds. It can trap up to ten birds, granting 280 experience if the birdhouse is full, which will take approximately 50 minutes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Abextm** [comment] 2018-06-07 09:43
Duplicate of #1224

**Closed by Abextm** 2018-06-07 09:43 UTC
