### ISSUE TITLE
Show Fishing spot tooltip when mousing over in World Map

### ISSUE THREAD

**Issue by nlruk** [runelite/runelite#11396] opened 2020-04-28 16:39 UTC
Mining spots has specific ores in the world map when you hover over it

<img width="192" alt="Screenshot 2020-04-28 at 17 32 30" src="https://user-images.githubusercontent.com/63312904/80513493-0a96f400-8977-11ea-89de-cffea14bb4f2.png">

Can you please add the specific type of fish at the fishing spots?

<img width="250" alt="Screenshot 2020-04-28 at 17 32 51" src="https://user-images.githubusercontent.com/63312904/80513597-30bc9400-8977-11ea-9f25-1d719281cbcf.png">

**Comment by dekvall** [comment] 2020-04-28 17:26
Duplicate of #7317

**Closed by dekvall** 2020-04-28 17:26 UTC
Labels: feature-request, worldmap
