### ISSUE TITLE
colours for Runecrafting pouches

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#1451] opened 2018-04-12 20:04 UTC
Green represents full (there are rune/pure essence inside it)
Yellow/orange represents empty (there are no rune/pure essence inside it)
red represents degrading (it needs to be restored by talking to dark mage by the npc contact spell)

![image](https://user-images.githubusercontent.com/37475765/38701130-fc7d3160-3e94-11e8-84e7-5f4d6a41bb11.png)
something similar to this sorry don't have the red colour.

**Comment by deathbeam** [comment] 2018-05-13 11:51
Duplicate of #1007

**Closed by deathbeam** 2018-05-13 11:51 UTC
Labels: feature-request
