### ISSUE TITLE
[Menu Entry Swapper] Quick stairs

### ISSUE THREAD

**Issue by mthoemke** [runelite/runelite#14568] opened 2022-01-08 11:38 UTC
When using stairs in Lumbridge Castle or other similar stairs/ladders with climb options it would be nice to have [Left Click] set to menu entry [Climb-up Staircase] and have [Shift Left Click] to [Climb-down Staircase].

**Comment by geheur** [comment] 2022-01-08 11:48
duplicate of #3562

**Closed** 2022-01-08 15:33 UTC
