### ISSUE TITLE
GPU plugin tremendous RAM usage 

### ISSUE THREAD

**Issue by GottaSlay** [runelite/runelite#6713] opened 2018-11-27 16:35 UTC
GPU Plugin spikes up ram usage by HUGE amount.

**To Reproduce**
Enable GPU plugin.

**Expected behavior**
You'll see RAM usage spiking up tremendously. 
**Screenshots**
https://gyazo.com/754e706c8cc2bc57c6a5ee698c594fc1

**Environment (please complete the following information):**
 - OS: Windows 10 64-Bit PRO
 - RuneLite version: Latest at the moment. 
 - Launcher version: Latest.
- GPU: RX580 Nitro+ 8GB
**Additional context**
[application.log](https://github.com/runelite/runelite/files/2620895/application.log)

Be it expected or unexpected behavior, this is unacceptable.

**Comment by Nightfirecat** [comment] 2022-07-10 03:58
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 03:58 UTC
Labels: needs-information, gpu
