### ISSUE TITLE
Runelite sidebar is whiting out and cloning itself, weird visual bug.

### ISSUE THREAD

**Issue by albinomuffin** [runelite/runelite#11931] opened 2020-06-19 00:34 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The Runelite part of Runelite is cloning itself in weird ways, often times displaying only a white blank bar, and is essentially unusable. The screenshots will do a lot better job at defining what is happening that I can do with words.

**To Reproduce**
All I have to do to reproduce it is fire up Runelite. It happens everytime, after trying to navigate the plugins, checking highscores, checking farming timers, it doesn't matter.

**Expected behavior**
I just want the sidebar to be normal. No messing up.

**Screenshots**
![image](https://user-images.githubusercontent.com/67129783/85084349-c31c2f80-b191-11ea-97c8-1d80adc55435.png)
![image](https://user-images.githubusercontent.com/67129783/85084372-d8915980-b191-11ea-9632-bd7719dd4d8b.png)
![image](https://user-images.githubusercontent.com/67129783/85084418-f3fc6480-b191-11ea-9907-c88d0ad378be.png)
![image](https://user-images.githubusercontent.com/67129783/85084436-01b1ea00-b192-11ea-9a8a-59470b6d3876.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: Newest
 - Launcher version: Newest

**Comment by albinomuffin** [comment] 2020-06-19 00:40
**THIS SOLVED MY PROBLEM:**

Located at **THIS** link: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

Method 1: Creating a shortcut
You can create desktop shortcut with --mode=OFF at the end of the target box. make sure there is a space before the --! (Video below)

![image](https://user-images.githubusercontent.com/67129783/85084779-0cb94a00-b193-11ea-8fa6-c3df1bb142c9.png)

**Comment by albinomuffin** [comment] 2020-06-19 01:26
I lied, this only solved the problem temporarily. I have the same problem still.

**Comment by Nightfirecat** [comment] 2020-06-19 05:08
Duplicate of #11727

**Closed by Nightfirecat** 2020-06-19 05:08 UTC
Labels: duplicate
