### ISSUE TITLE
Small Hiscore plugin issue

### ISSUE THREAD

**Issue by Dhemize** [runelite/runelite#14579] opened 2022-01-10 13:30 UTC
Just noticed today when I searched myself up on the hiscore plugin so not sure if the issue is with hiscores or the plugin but Scorpia and Scotizo got swapped. It still shows the right kc and rank in the same place but since the last time I noticed, the name and icon for both swapped places. So instead of 99kc Scotizo and 50kc Scorpia, it shows up as 99kc Scorpia and 50kc Scotizo.

**Comment by Hydrox6** [comment] 2022-01-10 13:35
Duplicate of #14564

**Closed by Hydrox6** 2022-01-10 13:35 UTC
