### ISSUE TITLE
Customizable goals plugin

### ISSUE THREAD

**Issue by Jerpai** [runelite/runelite#4917] opened 2018-08-15 18:11 UTC
Runescape has so many things to do so you easily forget what you wanted/were going to do later. For example train a skill or do 3 herb runs every day.

What I'm suggesting is a plugin that lets you set up a goals list for these sort of things to help you remember and keep doing what you started. You would be able to select the days for when you want to do the task (for example every day or every monday and friday). Then you would select how much you would like to do it (for example the number of runs/boss kills/amount of xp). It would then appear in the goals tab on the sidebar on the set days. It would also have a progress bar to track how much you still have to go.

**Goal progress example:**
Herb runs
2/3 done
[XXO]

**Goal setting example:**
Task selection (farm runs/boss kills/xp)
Day selection
Amount of repeats/xp
Activate/deactivate

**Comment by deathbeam** [comment] 2018-08-15 19:35
Duplicate of #3507

**Closed by deathbeam** 2018-08-15 19:35 UTC
