### ISSUE TITLE
I'd like to have items dropped in PvM to be colored based on the droprate noted in os.rs.wiki

### ISSUE THREAD

**Issue by brainard52** [runelite/runelite#10431] opened 2019-12-12 22:17 UTC
**Is your feature request related to a problem? Please describe.**
Not related to a problem. QoL

**Describe the solution you'd like**
I would like items dropped by monsters and other PvM content (chests, for example) to be highlighted or otherwise indicated based on droprate. 

**Describe alternatives you've considered**
This would be an alternative to (or addition to) the ground items plugin.

**Comment by Hydrox6** [comment] 2019-12-12 22:20
Duplicate of #7905
(same core request)

**Closed by Hydrox6** 2019-12-12 22:20 UTC
