### ISSUE TITLE
Is is impossible to unmark object > Incense Burner

### ISSUE THREAD

**Issue by Mewchild** [runelite/runelite#10371] opened 2019-12-02 22:22 UTC
**Describe the bug**
After marking the incense burner in a player owned house, it becomes impossible to unmark it

**To Reproduce**
1. Right Click Incense Burner while it's lit, click on "Mark Object"
2. Right Click Incense burner, Unmark Object
3. Relight the burner, using a tinderbox and Marrentil Herb
4. The object remarks itself.

**Expected behavior**
When unmarking an object, the setting is remembered.

**Screenshots**
https://files.catbox.moe/xkd4dm.gif

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.42.1
 - Launcher version: 1.6.0
 - Oldschool revision 186

**Comment by Adam-** [comment] 2019-12-02 22:45
I can't reproduce this using the steps provided. The logs show it being properly removed also:

```
2019-12-02 17:37:34 [Client] DEBUG n.r.c.p.o.ObjectIndicatorsPlugin - Marking object: ObjectPoint(id=13213, name=Incense burner, regionId=7769, regionX=22, regionY=45, z=1)
2019-12-02 17:37:34 [Client] DEBUG n.r.client.config.ConfigManager - Setting configuration value for objectindicators.region_7769 to [{"id":13213,"name":"Incense burner","regionId":7769,"regionX":22,"regionY":45,"z":1}]
2019-12-02 17:37:36 [Client] DEBUG n.r.c.p.o.ObjectIndicatorsPlugin - Unmarking object: ObjectPoint(id=13213, name=Incense burner, regionId=7769, regionX=22, regionY=45, z=1)
2019-12-02 17:37:36 [Client] DEBUG n.r.client.config.ConfigManager - Unsetting configuration value for objectindicators.region_7769
```

What do your logs show when you mark and unmark it?

**Comment by dekvall** [comment] 2019-12-02 23:57
A magic wardrobe seems to behave in a similar way, i don't know if it's related, unfortunately i don't have any burners to test on. What happens if you:
 1. Mark the burner when it's not burning
 2. Light it and un-mark it when it's burning
 3. Re-light the burning one

![mark_thing](https://user-images.githubusercontent.com/25151927/70002833-8b38fc00-1561-11ea-9eee-8ab4fb6bdf60.gif)

**Comment by Mewchild** [comment] 2019-12-03 00:00
I've attached my logs here: https://pastebin.com/54MQmQ2p

**Comment by Adam-** [comment] 2019-12-03 13:48
I think that this is fixed now in 883fd21cfd6fd307fead556ddee9b172457ea31d

**Comment by Mewchild** [comment] 2019-12-10 04:34
The fix mentioned above does not seem to work. As of today:
Runelite Version 1.5.42.3
OldSchool Revision 186
Launcher Version 1.6.0

`
2019-12-09 22:31:28 [Client] WARN  n.r.c.p.o.ObjectIndicatorsPlugin - unable to find object point for unmarked object 13213
2019-12-09 22:31:29 [Client] WARN  n.r.c.p.o.ObjectIndicatorsPlugin - unable to find object point for unmarked object 13213`

https://files.catbox.moe/dxmbl4.log

**Comment by abextm** [comment] 2019-12-10 04:36
883fd21cfd6fd307fead556ddee9b172457ea31d has not been included in a release yet

**Comment by Mewchild** [comment] 2019-12-10 04:43
That would explain why it's not fixed yet 👍

**Comment by dekvall** [comment] 2019-12-17 02:27
@Mewchild Can you test this again whenever you have the time?

**Comment by Mewchild** [comment] 2019-12-17 02:50
Still an issue as of this exact moment.
https://files.catbox.moe/5efm45.mp4
Logs: https://files.catbox.moe/nuawyq.log
`2019-12-16 20:47:16 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2019-12-16 20:47:17 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2019-12-16 20:47:17 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 380960879.350
2019-12-16 20:47:19 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-12-16 20:47:20 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-12-16 20:47:21 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 5834ms. Uptime: 8121ms
2019-12-16 20:47:22 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1680x1020,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@1376921,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-12-16 20:47:22 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user Apos.
2019-12-16 20:48:26 [Client] WARN  n.r.c.p.o.ObjectIndicatorsPlugin - unable to find object point for unmarked object 13213
2019-12-16 20:48:41 [Client] WARN  n.r.c.p.o.ObjectIndicatorsPlugin - unable to find object point for unmarked object 13213
2019-12-16 20:48:42 [Client] WARN  n.r.c.p.o.ObjectIndicatorsPlugin - unable to find object point for unmarked object 13213
2019-12-16 20:49:07 [Client] WARN  n.r.c.p.o.ObjectIndicatorsPlugin - unable to find object point for unmarked object 13213
2019-12-16 20:49:10 [Client] WARN  n.r.c.p.o.ObjectIndicatorsPlugin - unable to find object point for unmarked object 13213
`

**Comment by Adam-** [comment] 2019-12-17 03:11
If you wipe your object market config is it still a problem?

**Comment by Mewchild** [comment] 2019-12-17 03:17
Where would I go in order to do so?

**Comment by Mewchild** [comment] 2019-12-17 03:19
Edit, I'm dumb. Just reset it. It's still an issue

**Comment by Adam-** [comment] 2019-12-17 13:12
I tested this earlier, on the release, with the burners as described in OP:

1) light the burner
2) mark the burner
3) unmark the burner
4) wait for the burner to go out
5) relight the burner

and it is correctly not marked.

Here are the logs:

```
2019-12-16 22:22:26 [Client] DEBUG n.r.c.p.o.ObjectIndicatorsPlugin - Marking object: ObjectPoint(id=13213, name=Incense burner, regionId=7769, regionX=17, regionY=45, z=1)
2019-12-16 22:22:26 [Client] DEBUG n.r.client.config.ConfigManager - Setting configuration value for objectindicators.region_7769 to [{"id":13213,"name":"Incense burner","regionId":7769,"regionX":17,"regionY":45,"z":1}]
2019-12-16 22:22:27 [Client] DEBUG net.runelite.client.RuneLite - Replacing archive 12/39
2019-12-16 22:22:39 [pool-2-thread-1] DEBUG n.r.http.api.config.ConfigClient - Built URI: https://api.runelite.net/runelite-1.5.44-SNAPSHOT/config/objectindicators.region_7769
2019-12-16 22:22:39 [OkHttp https://api.runelite.net/...] DEBUG n.r.http.api.config.ConfigClient - Synchronized configuration value 'objectindicators.region_7769' to '[{"id":13213,"name":"Incense burner","regionId":7769,"regionX":17,"regionY":45,"z":1}]'
2019-12-16 22:22:47 [Client] DEBUG n.r.c.p.o.ObjectIndicatorsPlugin - Unmarking object: ObjectPoint(id=13213, name=Incense burner, regionId=7769, regionX=17, regionY=45, z=1)
2019-12-16 22:22:47 [Client] DEBUG n.r.client.config.ConfigManager - Unsetting configuration value for objectindicators.region_7769
2019-12-16 22:23:09 [pool-2-thread-1] DEBUG n.r.http.api.config.ConfigClient - Built URI: https://api.runelite.net/runelite-1.5.44-SNAPSHOT/config/objectindicators.region_7769
2019-12-16 22:23:09 [OkHttp https://api.runelite.net/...] DEBUG n.r.http.api.config.ConfigClient - Unset configuration value 'objectindicators.region_7769'
```

Which correctly has no warning message about being unable to locate the object.

**Closed** 2019-12-18 13:54 UTC
Labels: bug, regression
