### ISSUE TITLE
Update !kc on opening collection log

### ISSUE THREAD

**Issue by whartd** [runelite/runelite#10257] opened 2019-11-14 01:34 UTC
Currently opening the collection log will not update the !kc command. Upon opening the coll log entry for a boss/activity, the behavior I'd expect would be an update to the !kc command.

I would like an enhancement to the !kc plugin to perform this updating.

**Comment by Hydrox6** [comment] 2019-11-14 01:37
Duplicate of #8257

**Closed by Hydrox6** 2019-11-14 01:37 UTC
