### ISSUE TITLE
All states of degradable armour should stay within the bank tags

### ISSUE THREAD

**Issue by wouter2203** [runelite/runelite#6229] opened 2018-10-28 08:33 UTC
_This might be a bug if it was never the intention to only store 1 state in a bank tag._

**Is your feature request related to a problem? Please describe.**
If you have an item like barrows and tagged it just after it was repaired, it will not be found within the tag once you have used it once and the item is in its 100% state.

1) Tag Karil's leathertop (just after it was repaired).
2) Use it 1 time so that it is degraded and in its 100% state
3) Deposit it back into your bank.
4) Open tag and notice the Karil's leathertop can't be found there anymore.

**Describe the solution you'd like**
Some items, like all barrows items, should stay in the same bank tag whenever their state changes.

**Describe alternatives you've considered**
There is no good alternative for the suggested solution.

**Additional context**
Tagged the items when they were just repaired, the items in my inventory are both on (75%). 
![image](https://user-images.githubusercontent.com/8761962/47613679-152bb100-da94-11e8-9261-f415597523a5.png)

Here I have deposited one Karil's item.
![image](https://user-images.githubusercontent.com/8761962/47613705-5f149700-da94-11e8-99ab-17859c4a1ef3.png)

**Comment by deathbeam** [comment] 2018-10-28 10:00
Duplicate of #3767

**Closed by deathbeam** 2018-10-28 10:00 UTC

**Comment by wouter2203** [comment] 2018-10-28 21:17
My mistake, I thought charged items would be different from degradable armour. I would have liked to have the above implemented, but would only like 4 doses of potions to be tagged. That was before I just saw the pull request, which would also solve the above problem. Anyway, thanks!
