### ISSUE TITLE
Unable to launch GPU plugin (Ubuntu 20.4)

### ISSUE THREAD

**Issue by janholbrouck** [runelite/runelite#12244] opened 2020-07-28 21:50 UTC
This issue is similar to https://github.com/runelite/runelite/issues/11848, although I have some different versions and a different GPU. I am unsure if I should add to the existing open issue or create a new one.

**Describe the bug**
When I try to toggle on the GPU plugin it turns itself off again and I notice an error in the terminal.

**To Reproduce**

Run RuneLite.AppImage
Wait for client to have opened
Go to plugin 'GPU'
Click on enable

**Expected behavior**
GPU Plugin turns on and works

**Environment (please complete the following information):**
OS: Ubuntu 20.04 LTS 64 bit
RuneLite version: 1.6.23 rev 190
Launcher version: 2.1.3

**Additional context**
I have a Radeon HD6730, running

 hostnamectl:
           Operating System: Ubuntu 20.04 LTS
            Kernel: Linux 5.4.0-42-generic
            Architecture: x86-64

DRI_PRIME=1 glxinfo | grep -i opengl:
OpenGL vendor string: X.Org
OpenGL renderer string: AMD TURKS (DRM 2.50.0 / 5.4.0-42-generic, LLVM 10.0.0)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.0.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 20.0.8
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:

sudo lshw -c video
    *-display                 
       description: VGA compatible controller
       product: Whistler [Radeon HD 6730M/6770M/7690M XT]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:43 memory:a0000000-afffffff memory:c6500000-c651ffff ioport:5000(size=256) memory:c6520000-c653ffff
  *-display
       description: VGA compatible controller
       product: 2nd Generation Core Processor Family Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:42 memory:c0000000-c03fffff memory:b0000000-bfffffff ioport:6000(size=64) memory:c0000-dffff

stacktrace:
2020-07-28 23:39:58 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.InternalError: XXX0 profile[2]: GL2 -> profileImpl GL3bc !!! not mapped 
	at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2098)
	at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1976)
	at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1895)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1861)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:239)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:225)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:309)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:191)
	at ch.tz(ch.java:46864)
	at client.am(client.java)
	at bn.pe(bn.java:384)
	at bn.run(bn.java:338)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Nightfirecat** [comment] 2020-07-28 22:11
This appears to be the same issue, so I am closing it as a duplicate of #11848.

**Closed by Nightfirecat** 2020-07-28 22:11 UTC
Labels: duplicate
