### ISSUE TITLE
Herb Patch Chat Notifications

### ISSUE THREAD

**Issue by whartd** [runelite/runelite#10728] opened 2020-02-04 18:25 UTC
Currently there is a feature where you will receive a chat notification when your birdhouses are ready. A similar feature for herb patches would be very helpful. 

Perhaps this one could say something like "Your herb patches are ready (x/y)" where x is the number of patches that are ready and y is the number of herb patchs you have planted. This would be due to farm ticks taking place in the middle of your run. 

Alternatively the message could wait until all herb patches that have been planted are fully grown. However, if someone planted a herb in the farming guild for a contract in the middle of their regular patches growing then this message would be delayed until the farming guild patch is fully grown. A message like "Your herb patches are ready (5/6)" would let players in that situation know that everything but their farming guild patch is ready.

This would be an alternative to keeping the time tracking tab open, and allow players i.e. to have a larger window/more screen space, or to leave open the xp/hr or loot tracker tabs while doing click intensive skilling/pvm. 

An alternative in game would be to wear an Amulet of Nature, but that item would have less functionality and would prevent players from wearing stat boosting or teleportation neck slot items.

**Comment by Nightfirecat** [comment] 2020-02-05 07:29
Duplicate of #2212

**Closed by Nightfirecat** 2020-02-05 07:29 UTC
