### ISSUE TITLE
Add warning when you're about to enter an area with Wyverns without an Elemental or other appropriate shield 

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#2694] opened 2018-05-13 22:41 UTC

**Comment by Alexsuperfly** [comment] 2019-07-28 18:10
basically duplicate of #2510

**Comment by Nightfirecat** [comment] 2019-07-29 00:06
This is effectively the same issue, and would use the same solution, so I agree.

**Closed by Nightfirecat** 2019-07-29 00:06 UTC
Labels: feature-request
