### ISSUE TITLE
Player Indicators: Text overlay shouldn't overlap

### ISSUE THREAD

**Issue by Twiglet1022** [runelite/runelite#14164] opened 2021-09-17 22:31 UTC
If you are in a crowded area with the "Name position" config set to anything other than "Disabled" and the "Highlight others" option enabled then the names of all players on the same tile will be rendered on top of each other and unreadable.

In the Ground Items plugin each item gets its own height offset so that items in the same pile are neatly rendered as a stack with no overlap. Is it possible to do the same with the player indicators plugin?

Example of the issue:
![Example](https://user-images.githubusercontent.com/29353990/133859973-0dafa4d7-95e6-4a99-848f-aa0739a772b6.png)

**Comment by Nightfirecat** [comment] 2021-09-17 22:41
Duplicate of #1144

For what it's worth, this is not easy to implement unlike ground items, because players can be shown between tiles while walking/running or animation stalled, which totally removes the possibility of having the same implementation.

**Closed by Nightfirecat** 2021-09-17 22:41 UTC
Labels: duplicate

**Comment by Twiglet1022** [comment] 2021-09-17 22:45
Oh I didn't even think of players being between tiles, just that sometimes animations change players height. Okay that does sound awful to try to fix.
