### ISSUE TITLE
NPC Triggers Chat Notifications

### ISSUE THREAD

**Issue by SandroVA** [runelite/runelite#16220] opened 2023-01-27 01:31 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

When talking to [Ashuelot Reis](https://oldschool.runescape.wiki/w/Ashuelot_Reis) she says "Hello, [Username]" this triggers chat notifications. I don't believe NPCs should be doing this.

### RuneLite version

RL Version: 1.9.8
Launcher Version: 2.4.2

**Comment by Enriath** [comment] 2023-01-27 02:04
Duplicate of #16211

**Closed by Enriath** 2023-01-27 02:04 UTC
Labels: needs-triage
