### ISSUE TITLE
Abyssal Sire disoriented timer

### ISSUE THREAD

**Issue by Toxyc** [runelite/runelite#2683] opened 2018-05-13 19:44 UTC
Hello,

It would be nice to have a timer on how long the Sire boss is disoriented. Pretty sure this won't be too hard to make, pls gib feature.

**Comment by deathbeam** [comment] 2018-07-02 14:33
Closing as duplicate of #4132 as that one is slightly better formatted

**Closed by deathbeam** 2018-07-02 14:33 UTC
Labels: feature-request
