### ISSUE TITLE
Stretched fixed mode issue

### ISSUE THREAD

**Issue by stevensnippe** [runelite/runelite#3935] opened 2018-06-21 19:41 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| Java Version | 1.8.0_161
| Operating System | Windows

Issue:
1) enable Stretched fixed mode
2) drag client to the width you want it to be
3) turn off stretched fixed mode
4) stretch client to original window
5) close client
6) open client
--> client opens with stretched with, doesn't save new width if you resize to small and exit

**Comment by Nightfirecat** [comment] 2023-07-17 06:30
Cannot reproduce this issue, so I'm closing it. Please comment if this is still affecting you.

**Closed by Nightfirecat** 2023-07-17 06:30 UTC
Labels: invalid
