### ISSUE TITLE
Game freezes and locks up when zooming in house

### ISSUE THREAD

**Issue by SamNibbles** [runelite/runelite#5998] opened 2018-10-13 22:52 UTC
Not sure entirely on the cause but if I zoom in a lot in my house the game completely freezes and I am not even able to log back in afterwards it freezes when i press click to play. I think it may be an issue with the zoom.

**Comment by deathbeam** [comment] 2018-10-13 23:42
I cant reproduce this

**Comment by SamNibbles** [comment] 2018-10-14 00:51
> I cant reproduce this

I am still unable to login on runelite after this happened, not sure what to do? I can log in on the vanilla client still

**Comment by trimbe** [comment] 2018-10-14 00:55
Could you upload application.log to pastebin and link that here?

[Click here](https://github.com/runelite/runelite/wiki/FAQ#where-can-i-find-the-logs-screenshots-or-configurations) to find the logs directory

**Comment by SamNibbles** [comment] 2018-10-14 00:58
> Could you upload application.log to pastebin and link that here?
> 
> [Click here](https://github.com/runelite/runelite/wiki/FAQ#where-can-i-find-the-logs-screenshots-or-configurations) to find the logs directory

Here you go! - https://pastebin.com/YsCsHeSH

I logged out of the RuneLite client and it then let me log in, so thinking it could be an error with a setting I had enabled, I am trying to reproduce it now!

**Comment by SamNibbles** [comment] 2018-10-14 00:59
> Could you upload application.log to pastebin and link that here?
> 
> [Click here](https://github.com/runelite/runelite/wiki/FAQ#where-can-i-find-the-logs-screenshots-or-configurations) to find the logs directory

Turns out just zooming in as far as I can is whats causing it

**Comment by Adam-** [comment] 2018-11-24 15:07
This was fixed in f614a458458b6b57bb2fcc0d3da7501340ddaf6a

**Closed by Adam-** 2018-11-24 15:07 UTC
Labels: bug, needs-information
