### ISSUE TITLE
Ground items, rune pouch, and slayer helm broken.

### ISSUE THREAD

**Issue by Olvaliance** [runelite/runelite#5085] opened 2018-08-23 18:30 UTC
**Describe the bug**
some of my items that display information in inventory or on floor are not behaving as expected. these include runepouch and slayer helm.

**Expected behavior**
I expected these items to display information.
Everything is turned on but is not working this patch.
**Screenshots**

**Environment (please complete the following information):**
windows 10
Latest update

newish to using runelite. Thank you for your help guys.
![runepouch](https://user-images.githubusercontent.com/42653812/44544759-b97e2980-a6d8-11e8-9ff9-8525eea78580.PNG)

**Comment by deathbeam** [comment] 2018-08-23 18:31
Duplicate of #5080

**Closed by deathbeam** 2018-08-23 18:31 UTC

**Comment by Olvaliance** [comment] 2018-08-23 18:33
but none of the solutions in that thread fixed my problem mate.

**Comment by deathbeam** [comment] 2018-08-23 18:34
5080 is bug and this is duplicate of that bug, mate
