### ISSUE TITLE
Feature Request: Hide Ancient Fungi pick option

### ISSUE THREAD

**Issue by dupperT** [runelite/runelite#3157] opened 2018-05-23 16:05 UTC
Swap the pick and walk option on Ancient Fungi on fossil island.
Can it either be in the menu entry swapper or the Herbiboar. Thank you

[https://gyazo.com/dfbe13d7e1eefa76e613719b341705e3](url)

**Comment by deathbeam** [comment] 2018-05-23 16:08
Duplicate of #3142

**Closed by deathbeam** 2018-05-23 16:08 UTC
