### ISSUE TITLE
Keep slayer counter in closer sync on cannon/barrage tasks

### ISSUE THREAD

**Issue by iguaan** [runelite/runelite#2147] opened 2018-04-29 20:16 UTC
My initial idea is to enable this for a specific few slayer monsters who dont have alternative versions, i.e dust or smoke devils, to keep things simple and then expand on the idea later.

The idea is to divide the gained slayer XP with the slayer XP reward from monsters if it's higher than the XP you'd get from a single kill and lower than what you get for killing a superior variant.

I know this isn't a very complex idea, but it's better than nothing and definietly an improvement over current one.

**Comment by Adam-** [comment] 2018-04-29 21:33
The underlying problem with the slayer xp drops is it is impossible to tell how many monsters you killed from the xpdrops since you can get half xp if you deal <half damage or don't get the last hit in. I think though that killing 2 monsters in 1 tick happens more often than half XP, so it might be better to try and do this despite the ambiguities.

**Comment by deathbeam** [comment] 2018-04-29 21:34
I believe this is duplicate of #1046

**Comment by iguaan** [comment] 2018-04-29 21:46
It would seem so, unfortunate that nothing came of it, I would like to start working on it but I'm utterly shit at coding, especially in Java.

My initial idea was to add more variables to the enum in Task file: slayer XP from a regular kill, slayer XP from a superior kill.

If the current task target has a slayer XP variable != null then check if slayer XP drop is > regular kill XP reward and < superior kill XP reward then do the divisions.

This obviously only works for enemies with a single type. This is only a basic idea and could be made into something more complex later on when bigger brains get interested in this.

**Comment by deathbeam** [comment] 2018-04-29 21:50
Move the discussion into #1046, this one is clearly duplicate as I stated earlier

**Closed by deathbeam** 2018-04-29 21:50 UTC
