### ISSUE TITLE
Make it so the imbued heart timer shows even while in combat

### ISSUE THREAD

**Issue by LuisRivera162** [runelite/runelite#4656] opened 2018-08-02 20:33 UTC
Sometimes when using the imbued heart special while in combat the timer won't show even if you activated it. It would be really nice if the timer displayed when activating the imbued heart and the message displaying if the heart's spec isn't available doesn't show in the chatbox, instead of relying on the spec animation of it.

**Comment by Nightfirecat** [comment] 2018-08-02 20:39
The animation (which may not appear while in combat) is the only way we're able to definitively know that an imbued heart has been used, so unfortunately there isn't a good way to fix this.

**Comment by deathbeam** [comment] 2018-08-03 09:58
Duplicate of #3516

**Closed by deathbeam** 2018-08-03 09:58 UTC
