### ISSUE TITLE
Loot Tracker - Farm Runs

### ISSUE THREAD

**Issue by 07RS** [runelite/runelite#8616] opened 2019-04-22 18:31 UTC
Would it be at all possible for the Loot Tracker to record items obtained through farm runs such as herbs, berries, fruits, etc.? I'm not sure if you'd be able to distinguish between herbs obtained through a monster drop or from a farming patch but it would be a nice addition nonetheless. Thanks

**Comment by Hydrox6** [comment] 2019-04-22 18:33
Duplicate of #4126

**Closed by Hydrox6** 2019-04-22 18:33 UTC
