### ISSUE TITLE
g.e tracker like osbuddy

### ISSUE THREAD

**Issue by farshad33** [runelite/runelite#8382] opened 2019-04-02 12:46 UTC
i notice a few features OSbuddy ,swiftkit and exilent has that runelite doesen't : price checker

**Comment by Hydrox6** [comment] 2019-04-02 12:51
Duplicate of #733

**Comment by Hydrox6** [comment] 2019-04-02 13:00
If you want to look up the prices for things, the Grand Exchange plugin already does that

**Closed** 2019-04-03 02:57 UTC
