### ISSUE TITLE
Crash after teleporting to Nardah from Iowerth Camp

### ISSUE THREAD

**Issue by kirkdl** [runelite/runelite#14852] opened 2022-04-12 05:24 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Full crash after teleporting to Nardah during Song of the Elves

**To Reproduce**
During the clue scroll task while doing song of the elves (south gate of prif), I teleported to Iowerth camp with only the master clue book in inventory. I did not gear up properly, so I tele'd to nardah using the master clue book. This caused an application crash.

**Expected behavior**
I expected the application to load into nardah, not crash. I successfully tele'd to nardah upon login.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.8.16
 - Launcher version: 2.1.3

**Additional context**
File attached to bug report
[jvm_crash_pid_19044.log](https://github.com/runelite/runelite/files/8469799/jvm_crash_pid_19044.log)

**Comment by Nightfirecat** [comment] 2022-04-12 05:27
This is a JVM crash caused by code run in the skybox plugin. Duplicate of #10549

**Closed by Nightfirecat** 2022-04-12 05:27 UTC
Labels: duplicate
