### ISSUE TITLE
New Widget Snap Position 

### ISSUE THREAD

**Issue by russel204** [runelite/runelite#10793] opened 2020-02-14 08:29 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...] Not an issue. just something I'd like to see if possible. 

**Describe the solution you'd like**
I would like to see a widget snap point directly above the inventory Where my minimap is located on the gyazo below. This is the same place the map sits in the fixed client. Without a snap point you get some funny issues like show in my second gyazo. Because the client was resized and the minimap doesn't hold its position like the snap points do it slides behind the inventory.

https://gyazo.com/9036ffb1480ed92285e6cf2ceda02bc9

https://gyazo.com/0220818f582477096bb524d0cc6a2583

**Comment by Alexsuperfly** [comment] 2020-02-14 13:55
duplicate of #8515

**Comment by Nightfirecat** [comment] 2020-02-18 04:02
Per Alex's comment, this is basically a duplicate of #8515. I don't think we plan on adding any additional default snap points currently.

**Closed by Nightfirecat** 2020-02-18 04:02 UTC
Labels: duplicate
