### ISSUE TITLE
Boss hiscores on hiscore lookup

### ISSUE THREAD

**Issue by Aegis95** [runelite/runelite#10548] opened 2020-01-04 02:20 UTC
Add a new tab that showcases a players boss hiscores on the hiscore widget. Could use small pet icons to distinguish bosses or just the monster examine icon as already present on the webpage version of hiscores.

**Comment by Hydrox6** [comment] 2020-01-04 02:23
Duplicate of #10397

**Closed by Hydrox6** 2020-01-04 02:23 UTC
