### ISSUE TITLE
Raid Scouter Overlay on till Olm.

### ISSUE THREAD

**Issue by ThisGuyy** [runelite/runelite#4444] opened 2018-07-22 10:17 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
- I would like to have the option, similar to the toggle for Chambers of Xeric to be able to keep the raid scouter overlay up till i enter the OLM Room rather then disappear as you start the raid.
Basically, im forced into using the snipping tool to keep track of what room is next, people say this is offered in other clients but i much prefer everything about runelite.

**Describe the solution you'd like**
- I would like a toggle option below the one that allows for the scouter to remain on while in the raids area, to allow for the scouter to stay on after starting the raid and disappearing as you enter the OLM room. 

**Describe alternatives you've considered**
- I have have considered even as you enter the room to maybe have the game even just throw some text into the chat with box similar to the pink text at the end of the raid with the rotation 
ie Raid Scouted - Guardians / Tekton / Muttadiles / Vasa / Unkown etc...

**Comment by deathbeam** [comment] 2018-07-22 10:36
Duplicate of #1871

**Closed by deathbeam** 2018-07-22 10:36 UTC
