### ISSUE TITLE
Pop-out sidebar

### ISSUE THREAD

**Issue by Azderi** [runelite/runelite#12804] opened 2020-11-16 15:43 UTC
Having the option to pop-out the sidebar into a separate window would allow it to be freely moved. This would really help with streaming and multitasking.

This could also be implemented as just a button to pop-out a specific tab(s) of the sidebar so it would be always open while still being able to browse through other tabs.

**Comment by Alexsuperfly** [comment] 2020-11-16 15:45
duplicate of #10416

**Comment by Hydrox6** [comment] 2020-11-16 16:05
Actually a duplicate of #2463

**Closed by Hydrox6** 2020-11-16 16:05 UTC
