### ISSUE TITLE
Visual bug, repeating images in sidebar

### ISSUE THREAD

**Issue by nonanot** [runelite/runelite#14186] opened 2021-09-23 18:47 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Repeating images of whatever screen I'm on follow my cursor and make it nearly unreadable

**To Reproduce**
1. Open Runelite sidebar
2. move the mouse or click on anything.

**Expected behavior**
The repeating images will follow the cursor and make the screen unreadable.

**Screenshots**

![RLbug](https://user-images.githubusercontent.com/43527141/134565095-30761d7b-e6ab-4883-8900-4f82a0de6aca.png)

**Environment (please complete the following information):**
 - OS: [Windows]
 - RuneLite version: [1.7.24]
 - Launcher version: [2.1.7]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Alexsuperfly** [comment] 2021-09-23 18:49
duplicate of #11727

**Closed** 2021-09-23 18:54 UTC
Labels: duplicate
