### ISSUE TITLE
Twitch chat plugin and spam

### ISSUE THREAD

**Issue by MrTIB** [runelite/runelite#7978] opened 2019-02-22 08:08 UTC
It would be nice to have the ability to disable the chat in the osrs client but still send messages in OSRS. This way the chat in-game wont be spammed with twitch chat, but you can still interact with it without clicking outside the game.

**Comment by deathbeam** [comment] 2019-02-28 23:35
Duplicate of #7893

**Closed by deathbeam** 2019-02-28 23:35 UTC
