### ISSUE TITLE
HD as cosmetics.

### ISSUE THREAD

**Issue by blablalb** [runelite/runelite#6978] opened 2018-12-16 11:23 UTC
Lots of us want HD.
If it is possible to replace/ override specific model in this client.
Maybe you can make it so we can add models ourselves and use them.
Also search community added models and use them and see what others are wearing (toggle ofc).

**Comment by deathbeam** [comment] 2018-12-19 12:19
Duplicate of #3077

**Closed by deathbeam** 2018-12-19 12:19 UTC
