### ISSUE TITLE
Spam filter list (Updated weekly)

### ISSUE THREAD

**Issue by Cornelius-Cell** [runelite/runelite#13069] opened 2021-01-16 00:19 UTC
Could we have an option to subscribe to a spam filter list(pastebin or whatever) that is updated weekly or frequently to stay up-to-date with the spammers. We could update this together as a community

example

Spending 2147m no junk please
Find Runners
Vegas
Lurers to ignore
No one here have dhcd??
Become a runner today
Seil goid
Grindswap
Invest in a rare name
Join cc [Run4less
Looking to buy Elysian
Buying sanguinesti staff
buying all good items, will pay alot
Buying twisted bow
Anyone here have bandos set?
Buying Elysian Spirit Shield
Buying Kodai wand 100m
Buying dragon claws
buying dragon hunter crossbow 120m
2b for?
Buying all valuable items!
Buying dragon hunter lance
Buying rapier
Someone just sell me dhcb
Buying all expensive items!
Spending 45b cash!
Buying armadyl set 100m!
Buying ancestral set 240m!
Buying scythe of vitur 830m!
Elysian for 1000m
for 180m!
Buying harmonised orb
with dhcb plase.
Buying dwh 62m
Buying inquisitors set
Buying bandos set
( Caw Hosts )
Ironempirecc
sceptre
antiscam
Pink Clay's Infernal Cape
"Ly RS"
Pogrs C0m
Join Discord Vanity Code 
[Dd][il]scord.Gg
[Ss]wap [Cc]c
([Ss]wap).+([0O]7)
([Ss]cam).+([Ss]ceptre)

**Comment by Hydrox6** [comment] 2021-01-16 00:21
Duplicate of #10857

**Closed by Hydrox6** 2021-01-16 00:21 UTC
