### ISSUE TITLE
Multi cryptic clues

### ISSUE THREAD

**Issue by nmq12** [runelite/runelite#4660] opened 2018-08-03 00:37 UTC
Cryptic clue with multiple clues are missing hint.
This particular clue require visiting all three location: Key Master, Piles, and digging in front of Shilo Village furnace

![image](https://user-images.githubusercontent.com/5819477/43617989-cdbd0d94-9693-11e8-9624-593992c94472.png)

**Comment by Nightfirecat** [comment] 2018-08-03 00:42
Basically a duplicate of #2923; the three-step master-level cryptic clues are not currently handled.

**Comment by deathbeam** [comment] 2018-08-03 09:57
Duplicate of #2923

**Closed by deathbeam** 2018-08-03 09:57 UTC
