### ISSUE TITLE
XP/Hr Separated from XP/Gained

### ISSUE THREAD

**Issue by ALargeDad** [runelite/runelite#4235] opened 2018-07-08 18:20 UTC
Pretty much self explanatory. Let me reset XP/hour separately from XP Gained. XP/Hour can fall out of accuracy when you need to take a break for a while, and I still want to see my total XP gained for the day or session without resetting both

**Comment by deathbeam** [comment] 2018-07-08 23:44
Duplicate of #3413

**Closed by deathbeam** 2018-07-08 23:44 UTC
