### ISSUE TITLE
Automatically select correct account type in hiscores plugin for ironmen

### ISSUE THREAD

**Issue by sadegr** [runelite/runelite#6729] opened 2018-11-28 21:50 UTC
It'd be nice if when looking up any type of ironman (regular ironman, HCIM, or UIM) in the hiscores plugin, the plugin defaulted to the appropriate hiscores category for their account type. For example, when looking up the stats for a UIM account, the hiscores plugin would immediately switch to the UIM hiscores. Currently, the hiscores plugin always shows the regular hiscores unless the user specifically selects a different category.

As this would have performance implications, this should be toggleable if implemented. As for how to make it happen, there are two options as I see it.

The simplest is probably to just look up a player more than once for each of the account types they could be, starting with the regular ironman hiscores, then checking HCIM or UIM if they exist in the regular ironman hiscores. This would be an exhaustive way of finding the "correct" hiscores category, but also a slow one, as each hiscores lookup is a separate call to the OSRS hiscores API. Additionally, I believe the OSRS hiscores API has built in rate limiting (something like 20 lookups in a short timespan, per machine) which could make this a problem.

We could also check the in-game chatbox for a matching display name (username) and check whether they have an ironman helmet symbol next to their name (and if so, which color it is) to determine which hiscores category to display. I would imagine this to be a far more performant solution, but I'm not familiar with how chat history is stored so I'm not sure.

**Comment by Nightfirecat** [comment] 2018-11-28 21:55
Mostly duplicate of #2403?

**Closed** 2018-11-29 12:09 UTC
