### ISSUE TITLE
Linux GPU screenshots wrong dimensions HiDPI

### ISSUE THREAD

**Issue by Noiseko** [runelite/runelite#11029] opened 2020-03-17 09:34 UTC
**Describe the bug**
Screenshot dimensions are wrong when GPU plugin is enabled. **regardless** of stretched mode or UI scaling type.

**To Reproduce**
GDK_SCALE=2 ./Runelite.AppImage

**Screenshots**
GPU on | Stretched mode off
![broken](https://user-images.githubusercontent.com/33142989/76842254-dede0580-6831-11ea-80f8-75a40dd5551a.jpg)
GPU off | Stretched mode off
![gpuoff](https://user-images.githubusercontent.com/33142989/76842261-e0a7c900-6831-11ea-8926-b0a7b62cc5c5.jpg)

**Environment (please complete the following information):**
OS: Arch Linux
KERNEL: 5.5.1-arch1-1
GPU DRIVER: 4.5 Mesa 19.3.3
Runelite version: 1.6.9
Launcher Version: 2.1.0

**Comment by Adam-** [comment] 2020-10-05 22:12
duplicate of #12463 and/or fixed in #12594

**Closed by Adam-** 2020-10-05 22:12 UTC
Labels: bug, gpu, platform:linux

**Comment by shuhaowu** [comment] 2020-11-13 02:37
I'm still having this problem after the fix above. Specifically, I have GDK_SCALE=2 and GPU enabled (stretched mode is disabled), which gives me this:
![2020-11-12_03-34-51](https://user-images.githubusercontent.com/338100/99021652-2044c300-252f-11eb-8d5a-24a9ef3a0407.png)

With GDK_SCALE=2 and GPU disabled (stretch disabled), I get 
![2020-11-12_03-35-01](https://user-images.githubusercontent.com/338100/99021672-2d61b200-252f-11eb-9312-62564d6997f8.png)

GDK_SCALE=1 with GPU enabled or disabled gets the correct dimensions, albeit the runelite dialog is too small to view.
