### ISSUE TITLE
Loot tracker - ring of wealth bug

### ISSUE THREAD

**Issue by EXPLOSIOOON** [runelite/runelite#5197] opened 2018-08-30 06:11 UTC
Bug found when using the loot tracker tool.

While having a ring of wealth equipped with the coin collection toggled on no coin drops show up in the tracker.

Assuming this is because the coins are directly placed in your inventory rather than spawning on the ground

**Comment by Nightfirecat** [comment] 2018-08-30 06:42
Duplicate of  #5077

**Closed** 2018-08-30 06:44 UTC
