### ISSUE TITLE
Resizable chatbox

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#13581] opened 2021-05-08 14:41 UTC
Allows you to resize your chatbox both horizontally and vertically.

This will allow you to see more than the last eight messages.

**Comment by Hydrox6** [comment] 2021-05-08 14:45
Duplicate of #11917

**Closed by Hydrox6** 2021-05-08 14:45 UTC

**Comment by Pingvinszar2** [comment] 2021-05-08 14:50
> 
> 
> Duplicate of #11917

Doesn't say anything about horizontal resizing.
