### ISSUE TITLE
Cryptic Clue Indicator Bug (proximity issue?)

### ISSUE THREAD

**Issue by osharpie** [runelite/runelite#16253] opened 2023-02-06 12:51 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

I searched through the issue listing and Q&A listings and did not find a similar addressed issue but if I missed something apologies.
Situation: solving easy clue scroll.
Cryptic clue: Belladonna, my dear. If only I had gloves, then I could hold you at last.
RuneLite clue hint: Talk to Tool Leprechaun at Draynor Manor.
Issue: on the world map, the indicator points indeed to the Belladonna patch Tool Leprechaun at Draynor Manor. The problem I encountered was that depending on proximity to either the correct Tool Leprechaun or the next closest Tool Leprechaun just north of the cabbage field south of Falador, the indicator on the view screen would point to the incorrect Tool Leprechaun. Not sure if this is case specific or indicative of a more general proximity issue regarding clue scrolls.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/43695985/216970995-32e2136f-fc88-493b-8547-8f7f6a07181f.png)
![image](https://user-images.githubusercontent.com/43695985/216971128-9e710553-1937-4006-9f20-c124204ac8a6.png)
![image](https://user-images.githubusercontent.com/43695985/216971209-d476e968-6025-4525-8c0d-b51f501f6beb.png)

### RuneLite version

RuneLite version: 1.9.9
Launcher version: 2.1.0

**Comment by Alexsuperfly** [comment] 2023-02-06 14:14
duplicate of #5231

**Closed** 2023-02-06 16:47 UTC
Labels: duplicate
