### ISSUE TITLE
GPU on Mac

### ISSUE THREAD

**Issue by Dustyroflman** [runelite/runelite#9931] opened 2019-09-27 21:33 UTC
GPU on Mac hasn’t worked since release. Figured it would’ve been coded over at this point but it could just be a bug on my end.

**Comment by Alexsuperfly** [comment] 2019-09-27 21:34
duplicate of #6482

**Closed** 2019-09-27 21:56 UTC
Labels: duplicate

**Comment by Grandmasboi** [comment] 2020-04-30 22:26
can one not just run a external gpu graphics card to make the gpu plugin work
