### ISSUE TITLE
Custom Mouse Tooltips RS3/Pre-Eoc Style feature-request

### ISSUE THREAD

**Issue by blxckmill** [runelite/runelite#11789] opened 2020-06-01 19:47 UTC
**Is your feature request related to a problem? Please describe.**
Mouse Tooltips are great, but they could even be better!

**Describe the solution you'd like**
an toggle-able option to further improve mouse tooltips, think about things like attacking npc's, selecting spells, agility shortcuts and talking to npcs. there are many more but you get the idea.

**Describe alternatives you've considered**
none.

**Additional context**
The exact thing I ( and many others probably ) want! :
https://prnt.sc/srwxkk
original source: https://runescape.wiki/w/Graphical_updates/Interfaces

**Comment by melkypie** [comment] 2020-06-01 19:49
Duplicate of #4207

**Closed by melkypie** 2020-06-01 19:49 UTC
