### ISSUE TITLE
Your loot indicator(for ironmen)

### ISSUE THREAD

**Issue by quintex1994** [runelite/runelite#5046] opened 2018-08-21 19:22 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

When camping a monster while watching a movie, i might get a few kills before looking at my screen and if there are other people, i might see a drop worth picking up but end up unable to as it wasn't from my monster. 

**Describe the solution you'd like**

Toggle-able indicator(icon/color) for ground loot to show if it dropped from my monster(presumeable trackable since loot tracker works?)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

Maybe allow for greying out/hiding loot that was not dropped for the player, could be annoying with item spawns for example though.

**Comment by deathbeam** [comment] 2018-09-12 13:16
Duplicate of #3801

**Closed by deathbeam** 2018-09-12 13:16 UTC
Labels: feature-request
