### ISSUE TITLE
Add a Food Eaten value tracker to the Loot Tracker plugin

### ISSUE THREAD

**Issue by qnnplmr** [runelite/runelite#8261] opened 2019-03-19 15:52 UTC
**Is your feature request related to a problem? Please describe.**
I would like to know the net loot value of my kills taking into account food eaten.

**Describe the solution you'd like**
Within the Loot Tracker plugin, add an option to track food consumed and subtract its GE value from the Loot value.

**Comment by psikoi** [comment] 2019-03-19 15:54
That seems oddly specific, and doesn't seem to be what a "Loot Tracker" should do

**Comment by qnnplmr** [comment] 2019-03-19 15:55
Loot Tracker currently gives a monetary value of loot gained - it would be useful to me if it gave me the option to get a Net value for my expended resources rather than just a Gross value

**Comment by Hydrox6** [comment] 2019-03-19 15:56
Duplicate of #6700

**Closed** 2019-03-19 17:25 UTC
