### ISSUE TITLE
Login button in top corner, and link in info not working.

### ISSUE THREAD

**Issue by drharlow** [runelite/runelite#2647] opened 2018-05-12 18:13 UTC
Running on Lubuntu 18.04. The login button to sync settings, as well as the link in the info panel isn't working. However, clicking the link for "Open an issue on GitHub!" works and open up my default browser, Chrome.

**Comment by jplsek** [comment] 2018-05-14 17:58
May be related to #2603

**Comment by deathbeam** [comment] 2018-05-14 18:00
Duplicate of #2603

**Closed by deathbeam** 2018-05-14 18:00 UTC
Labels: bug
