### ISSUE TITLE
Add more anchor points for draggable items

### ISSUE THREAD

**Issue by Ravyd** [runelite/runelite#12216] opened 2020-07-24 01:36 UTC
There are about 5 different anchor points in the runelite client that you can pin the minimap, exp, etc. onto. The main problem is that there are only a few of them, and they usually don't work for what I would like. If the plugin isn't pinned to one of them, then opening the side panel doesn't adjust accordingly resulting in problems like the minimap going behind your inventory. 

**Describe the solution you'd like**
A larger number of anchors, or movable anchors, so that we can choose where these points are anchored at. 

**Describe alternatives you've considered**
More anchor points, freely selectable anchor points.

**Additional context**

![anchor](https://user-images.githubusercontent.com/29013305/88353710-c8821200-cd1b-11ea-8939-f0d7ff958b96.png)

**Comment by JZomerlei** [comment] 2020-07-24 01:40
Duplicate of #8515

**Closed** 2020-07-24 02:18 UTC
