### ISSUE TITLE
Screen Marker Categories

### ISSUE THREAD

**Issue by UnhealthyKraken** [runelite/runelite#10734] opened 2020-02-05 20:50 UTC
Would it be possible to add the feature to group your screen markers into catergories? 

For example Herblore and Fletching is usually 14 of one item and 14 of another, would be nice to have a category with specific screen markers for those skills and inventory layouts.

**Comment by dekvall** [comment] 2020-02-05 20:58
Duplicate of #3205

**Closed by dekvall** 2020-02-05 20:58 UTC
