### ISSUE TITLE
Anti Drag changed to Shift Anti Drag

### ISSUE THREAD

**Issue by joshbz93** [runelite/runelite#3220] opened 2018-05-24 15:02 UTC
Revert back to original form.  Shift is the same button you use to drop items.  It was a poor decision to change this.

**Comment by Kamielvf** [comment] 2018-05-24 15:03
Also duplicate of #3200, you can continue discussion there.

**Closed** 2018-05-24 15:09 UTC

**Comment by joshbz93** [comment] 2018-05-24 15:12
Anti-drag can also be used to prevent you from dragging items when trying to quickly change gear.  So it isn't working as intended for some players, unless they disable shift-to-drop.  But since this is a duplicate post, it's closed.

**Comment by williammetcalf** [comment] 2018-05-24 15:15
you can customize the shift click option for the gear you want to switch. It may be roundabout, but still possible to work with shift
