### ISSUE TITLE
Suggestion: Add menu entry swapper for Mummy in PP

### ISSUE THREAD

**Issue by Aealm** [runelite/runelite#9594] opened 2019-08-06 12:27 UTC
The normal left click is "Talk", the right click option is "Start-minigame". Possible to add an option in menu entry swapper to make left click start minigame?

Also, possible to add a chest and sarcophagus counter?

**Comment by Hydrox6** [comment] 2019-08-06 12:28
Duplicate of #7138
The counter should be its own issue

**Closed by Hydrox6** 2019-08-06 12:28 UTC
