### ISSUE TITLE
PC Freezing / Stuttering while using Runelite. (while pick pocketing?)

### ISSUE THREAD

**Issue by KnottyDog** [runelite/runelite#10411] opened 2019-12-08 14:50 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I'm getting a bug where my PC will lock up/freeze/stutter for a few seconds ever 5 - 10 seconds eventually leading to my whole PC becoming unresponsive forcing a hard restart.
**To Reproduce**
The bug seems to be happening when I'm pick pocketing knights in west ardy. I will be clicking on the knights then suddenly my PC will freeze for a few seconds then unfreeze for 5 - 10 seconds then freeze again, repeating this over and over until i'm forced to hard restart my PC as windows becomes unresponsive.

**Expected behavior**
No stuttering/freezing

**Screenshots**

**Environment (please complete the following information):**
 Windows 10 4 bit, Runelite version 1.5.42.3 (current)

**Additional context**
N/A

**Comment by Alexsuperfly** [comment] 2019-12-08 14:51
duplicate of #10410

**Comment by KnottyDog** [comment] 2019-12-08 14:52
> duplicate of #10410

I closed it by accident... this is the re-opened one.

**Comment by KnottyDog** [comment] 2019-12-08 14:54
> duplicate of #10410

Delete the original if you're an admin or whatever

**Comment by KnottyDog** [comment] 2019-12-08 15:03
Is there any support on this forums or do people just leave snarky comments when ever someone new posts? Get over yourselves nerds and go learn some social skills.

**Comment by Hydrox6** [comment] 2019-12-08 15:04
Please do not open duplicate issues, you can just edit the original issue.

This is not a support forum, this is an issue tracker. Support is on the Discord, as I mentioned in the other issue

**Comment by KnottyDog** [comment] 2019-12-08 15:14
I think I'll just go back to RSbuddy as that didn't brick my PC like this garbage software.

**Closed** 2019-12-08 15:15 UTC
