### ISSUE TITLE
[Suggestion] Lootbeam or highlight tiles around drop

### ISSUE THREAD

**Issue by dbm5L** [runelite/runelite#11460] opened 2020-05-04 15:29 UTC
Please add lootbeams from RS3 or a highlight all tiles around a drop option. Maybe make the highlight color optional. Add a option to make a list of what drops you want highlighted. Please.

**Comment by raiyni** [comment] 2020-05-04 15:31
Duplicate of #9050

**Closed by raiyni** 2020-05-04 15:31 UTC
