### ISSUE TITLE
Loot Tracker Sorting

### ISSUE THREAD

**Issue by awodell12** [runelite/runelite#11592] opened 2020-05-14 15:50 UTC
### Problem
The problem is when killing a monster that I have killed before on my loot tracker it often ends up pretty deep down the tracker, so you have to scroll a ways to find it. 

### Solution
A way to sort the entries in the loot tracker. Preferably the most recently killed monster appears at the top, even if it is already in the log. 

### Alternative
An option to sort the display alphabetically by monster name so it would be easy to find where in the log the monster's loot is.

**Comment by Nightfirecat** [comment] 2020-05-14 15:51
Duplicate of #8519

**Closed by Nightfirecat** 2020-05-14 15:51 UTC
Labels: duplicate
