### ISSUE TITLE
Duplicate fishing sprites

### ISSUE THREAD

**Issue by Bartvhelvert** [runelite/runelite#1392] opened 2018-04-11 22:11 UTC
![image](https://user-images.githubusercontent.com/9639072/38645873-f72a5134-3de5-11e8-98c1-c5ea9a2b37e5.png)
![image](https://user-images.githubusercontent.com/9639072/38645880-fdcfcb18-3de5-11e8-9e5e-4e1c9e8cfb74.png)

Happens when there is more than 1 fishing spot in the same tile.

**Comment by ShaunDreclin** [comment] 2018-04-13 06:34
Was just about to report this myself haha

![screenshot](https://user-images.githubusercontent.com/5851433/38720186-405f2df6-3ec3-11e8-8e71-5f5e4ced7263.png)

**Comment by SomeoneWithAnInternetConnection** [comment] 2018-04-13 08:09
I want to invoke "it's a feature! not a bug" here. As long as the second icon isn't 3 miles up in the sky (which sometimes happened in the past), showing two when there are two fishing spots in the same tile seems fairly reasonable, since there are two fishing spots there after all.

**Comment by Nightfirecat** [comment] 2018-04-13 16:10
It seems redundant to show two spots of the same type. If they're for different fish, it makes sense to show both.

**Comment by MESLewis** [comment] 2018-04-13 16:16
But it is useful to know that 2 spots are occupying the same tile. I don't know about anyone else but usually when I'm fishing I know how many spots there are that I care about and I keep track of where all of them are to an extent so it's nice to know if in trying to find where all 4 spots are that 2 are in the same tile.

**Comment by Bartvhelvert** [comment] 2018-04-13 16:43
Maybe it can be shown in another way which looks less bugged. Currently it's also impossible to see how many spots there are in one place.

**Comment by SomeoneWithAnInternetConnection** [comment] 2018-04-13 19:46
The current behaviour doesn't look particularly buggy to my eyes, and also shows you how many spots there are in one place?

**Comment by Bartvhelvert** [comment] 2018-04-13 19:53
As shown in the picture on my initial post there are 3 fishing spots in one place with only 2 icons.

**Comment by ypperlig** [comment] 2018-04-13 19:53
What about instead of it floating in the air they could be shown side by side? Example:
![fishing](https://user-images.githubusercontent.com/4660715/38755196-20f7181e-3f65-11e8-8a00-0b4523b94266.png)

**Comment by Bartvhelvert** [comment] 2018-04-13 19:56
That would be confusing I think because it wouldn't match the clickbox. I suggest just having a text overlay if the amount of spots is bigger than one.

**Comment by ShaunDreclin** [comment] 2018-04-13 23:27
Having the icons stack closer together would also work, the main thing that looks wrong with them is how high the second icon floats above the first one

**Comment by nrodrigues0213** [comment] 2018-04-15 01:05
I have a fix in progress for both text and icons. 

Currently, the client draws the icons with the same distance stacked on each other. My fix will reduce this distance greatly, so the icons are stacked. 

This is how it looks like in text mode:
![after1](https://user-images.githubusercontent.com/25905465/38773927-54084670-4027-11e8-9007-76e46dc98b2e.png)
Note: The duplicate floating text will be finished when I fix the icon mode display.

**Comment by nrodrigues0213** [comment] 2018-04-15 01:51
This is how it currently looks. The dark tile under the 3 icons is due to how the icons are drawn onto the world. 

I may change the icons to display side-by-side, but I'm not sure how to do handle drawing just yet. 
![fixed](https://user-images.githubusercontent.com/25905465/38774086-8a5063b0-402d-11e8-9db7-d52cdc018515.png)

The solution isn't very elegant, so I'll be reviewing it tomorrow for any optimizations.

**Comment by Bartvhelvert** [comment] 2018-04-15 08:38
Mhm I also made a fix for this which just draws the amount on top of the icon. I don't know if we want to make everything configurable.

**Comment by nrodrigues0213** [comment] 2018-04-15 10:53
That sounds better than just stacking the icons. If you extended the fix to the text display too, then set up a pull request. I'd love to see your implementation because I'm not a fan of mine.

 I also agree with the idea of not adding config options to every little detail. I think a healthy medium would be replacing the Display Fish Icons checkbox with a  drop-down menu that includes the options: OFF, ICONS, TEXT, TILE ONLY.

**Comment by MagicfTail** [comment] 2018-04-15 11:30
How would that implementation handle different fishing spots stacking? Ex. the shark and lobster spots in the fishing guild. The current implementation handles that perfectly imo (ignore the white)

![image](https://user-images.githubusercontent.com/12607046/38777951-2b02482c-40b1-11e8-8a64-587eef8c2d66.png)

**Comment by Bartvhelvert** [comment] 2018-04-15 12:09
That would be a problem. I could add multiple text overlays but it would become messy.

**Comment by nrodrigues0213** [comment] 2018-04-15 12:26
What is the challenge you're facing with overlapping spots? You should be able to draw the count on each icon normally.

The way I implemented it involved using a hashmap to map each tile to a list of fishing spots and their counts.

**Comment by Bartvhelvert** [comment] 2018-04-15 13:05
I wasn't talking about the code getting messy. I just think that stacking 2 icons + 2 text field would be come messy and it would be hard to distinguish which text field belongs to which fish/icon.

**Comment by nrodrigues0213** [comment] 2018-04-15 13:45
I understand. I find that it's difficult to perfectly align the text within the icon at all angles. May you post a screenshot of your fix so I can offer some ideas?

**Comment by Bartvhelvert** [comment] 2018-04-15 13:57
![image](https://user-images.githubusercontent.com/9639072/38779211-8ed40f70-40c5-11e8-8900-6c0f0e251ad5.png)
I just noticed that the sprite still becomes darker. This is probably because the text tile indicator is rendered on top of the sprite.

**Comment by nrodrigues0213** [comment] 2018-04-15 15:04
I was able to implement side-by-side icon display, while also fixing tile shading. This is a work in progress:
![after3](https://user-images.githubusercontent.com/25905465/38779875-8e4c5356-409c-11e8-9fea-059882dc4815.png)

What do you think? Next step will be fixing the alignment for groups of 2.

**Comment by sethtroll** [comment] 2018-04-15 15:08
So we have the ability to change item quantity on an image, why not just do that? 

Eg. 
![this](https://user-images.githubusercontent.com/5454364/38779925-d9fa7bdc-4094-11e8-95f4-4faf66c55d1e.png)

**Comment by Bartvhelvert** [comment] 2018-04-15 15:27
That would be perfect

**Comment by nrodrigues0213** [comment] 2018-04-15 15:32
Good suggestion, just required a minor tweak to getFishImage(). 
This is how it looks:
![image](https://user-images.githubusercontent.com/25905465/38780158-7ed0c5e8-40a0-11e8-8f0d-da67b46d3b36.png)

**Comment by nrodrigues0213** [comment] 2018-04-15 20:27
That's a brilliant idea, I'll try to get that implemented tonight. There are still a few loose ends I need to tie.

**Comment by nrodrigues0213** [comment] 2018-04-19 21:25
Coming back to finish work on this. Here's a preview:
![image](https://user-images.githubusercontent.com/25905465/39010473-c1255dac-43dc-11e8-9413-4ff7983656e3.png)
Let me know where I can improve.

**Comment by ShaunDreclin** [comment] 2018-04-19 21:26
I dig it! That looks great

**Comment by Kamielvf** [comment] 2018-04-19 21:27
Try to center those images on the tile and overall it looks great :+1:

**Comment by Nightfirecat** [comment] 2018-09-16 21:53
I'm fairly certain  #1736 is related

**Comment by Digbigpig** [comment] 2019-01-11 18:34
@nrodrigues0213 Any plans on finishing work on this? Looks like you're the only one to have made significant progress on it.

**Comment by nrodrigues0213** [comment] 2019-01-12 00:32
@Digbigpig I stopped working on Runelite bugfixes after going through a couple of personal issues. It's funny that you ask now, because just last week I was considering returning. I'll get myself up to speed with the development process in the next few days. 

If I recall correctly, I had finished all the necessary tweaks to the code to make it visually appealing and functional; however, the code quality wasn't up to par with the rest of the client.

I'll update my status again in about three hours.

**Comment by nrodrigues0213** [comment] 2019-02-16 13:39
I'm finally back at work on this. I'll try my hardest to make daily progress towards finalizing the changes, although it's difficult with work and school consuming much of my time.

**Comment by nrodriguesdev** [comment] 2019-02-17 17:26
Status report: I've rewritten the solution from scratch. I'm now implementing minor graphical improvements before I submit a pull request containing the fix.

**Comment by nrodriguesdev** [comment] 2019-02-17 19:57
Done. (again) PR coming soon to a repository near you.

![image](https://user-images.githubusercontent.com/25905465/52918379-412da500-32c4-11e9-9159-a1563df4f5f5.png)

**Comment by Adam-** [comment] 2019-08-21 00:58
Fixed in 9fc04bf7e2469b4f77445c62464dedc9d117092b

**Closed by Adam-** 2019-08-21 00:58 UTC
Labels: bug
