### ISSUE TITLE
Make the 2005 Interface more Official

### ISSUE THREAD

**Issue by Veteranhd** [runelite/runelite#3666] opened 2018-06-07 06:33 UTC
**Is your feature request related to a problem? Please describe.**

Im not a fan of the way the chatbox looks and I would prefer a toggle option 
that shows the old chatbox which will make the interface official instead of looking 
like its pasted on the OSRS gameframe.
**Describe the solution you'd like**

The exact chatbox from 2005 being implemented with 
no extra stones when you click the trade/compete button 
add some features that cater to the clanchat if thats not possible im ok with it bare bones.

**Additional context**
![tgyh](https://user-images.githubusercontent.com/40017995/41082097-bb262ea4-69f2-11e8-8838-68076c0e3bdf.png)

**Comment by deathbeam** [comment] 2018-06-07 06:34
Duplicate of #3201

**Closed by deathbeam** 2018-06-07 06:34 UTC
