### ISSUE TITLE
Beginner Clue Strange Device doesnt work

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#10601] opened 2020-01-14 20:56 UTC
When using the strange device for beginner clues it doesn't show the hint arrows or the overlay text displaying possible solutions like it does in master clues. 

Not sure if an oversight or a bug as it uses a different strange device

**Comment by Hydrox6** [comment] 2020-01-14 21:00
Duplicate of #9298

Drop the clue and read it again

**Closed by Hydrox6** 2020-01-14 21:00 UTC
