### ISSUE TITLE
Color Vision Deficiency

### ISSUE THREAD

**Issue by iPillYa** [runelite/runelite#6280] opened 2018-10-31 16:23 UTC
**Is your feature request related to a problem?
I'm not sure if this has ever been mentioned before but could a plugin be created for people who have color vision deficiency or commonly known as color blindness? People who struggle with this like myself can easily confuse "alike" colors. For example, I have grabbed strength potions instead of prayer potions and not realize till I have taken a dose. Just looking for some suggestions or thoughts on this issue.

**Describe the solution you'd like**
Something to quickly identify the color(s) of an object maybe?

**Comment by trimbe** [comment] 2018-10-31 16:34
Windows has a system-wide filter in place for color blindness that might help you - http://www.brucebnews.com/2017/11/look-at-the-red-flowers-windows-10-now-includes-help-for-color-blindness/

I'd imagine there's similar things for other operating systems too if you're not on windows. 

Fixing color blindness stuff for the base game probably isn't something we want to do ourselves though.

**Comment by deathbeam** [comment] 2018-11-01 09:33
Duplicate of #1959

**Closed by deathbeam** 2018-11-01 09:33 UTC
