### ISSUE TITLE
Entity Hider: Add "Hide Random Event NPCs" to Entity Hider

### ISSUE THREAD

**Issue by Abi1024** [runelite/runelite#13501] opened 2021-04-20 02:13 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice to have an option to hide random event NPCs in the entity hider, making it easier to click in areas with lots of players like in ZMI altar/blast furnace.

**Describe the solution you'd like**
Config option in the Entity Hider plugin that allows hiding of all random event NPCs, perhaps with the further option of specifying where the player's own random event NPCs are also to be hidden. Currently there is the option of hiding menu options for other player's' random events, but this feature request is about hiding the actual NPC character models.

**Describe alternatives you've considered**
Either have an option to hide all random event NPCs or hide all random event NPCs except for those following the local player.

**Additional context**

**Comment by RuneLogApp** [comment] 2021-05-12 18:29
FYI the Random Events plugin will disable the clickable options for other's randoms. Might be useful in the meantime as a workaround.

**Comment by Hydrox6** [comment] 2022-01-20 17:25
Duplicate of #2310

**Closed by Hydrox6** 2022-01-20 17:25 UTC
