### ISSUE TITLE
Loot Tracker hiding items over zealously 

### ISSUE THREAD

**Issue by MatzeBro** [runelite/runelite#8631] opened 2019-04-24 18:06 UTC
When you Hide 'Dragon Bones' 'Babydragon bones' are also hidden.

**Comment by psikoi** [comment] 2019-07-31 08:28
/loottracker/LootTrackerPlugin.java
At line 576

Change .contains to .equals, for anyone looking for a quick first contribution :P

**Comment by pattyjogal** [comment] 2019-08-05 01:19
I don't know how you were getting that behavior, @MatzeBro 

The flow of items being checked for being ignored looks like this:

```java
// Ignored items array is defined
private List<String> ignoredItems = new ArrayList<>();
...
// Parses the item names from the CSV
ignoredItems = Text.fromCSV(config.getIgnoredItems());
...
// isIgnored method
boolean isIgnored(String name)
{
	return ignoredItems.contains(name);
}
```
There should be no substring-ing going on here; `isIgnored` merely checks if the input name is in the `ignoredItems` array.

**Comment by Nightfirecat** [comment] 2019-08-05 02:15
I can confirm that I did get a loot tracker entry containing `Big bones` when `Bones` was on my ignored items, so I'm pretty sure this isn't an actual bug.

**Comment by Nightfirecat** [comment] 2020-03-24 17:48
As no further information was provided and nobody else has been able to reproduce this, I am closing this issue. If you have some way to reproduce this issue, please comment and re-open.

**Closed by Nightfirecat** 2020-03-24 17:48 UTC
Labels: needs-information
