### ISSUE TITLE
Quick Hopping

### ISSUE THREAD

**Issue by Castro3halo** [runelite/runelite#2432] opened 2018-05-07 06:52 UTC
Similar to OSB Ctrl+ Shift + Arrowkey to hop 1 world across as Jagex's menu is very slow and laggy. Do not mean the right click hop to a friend's world from OSB.

**Comment by deathbeam** [comment] 2018-05-07 06:53
Duplicate of #1453

**Closed by deathbeam** 2018-05-07 06:53 UTC
