### ISSUE TITLE
A way to never forget to compost

### ISSUE THREAD

**Issue by Sebixer23** [runelite/runelite#14863] opened 2022-04-14 21:49 UTC
**Is your feature request related to a problem? Please describe.**
Uncomposted herb highlights!
Sometimes you forget to compost your herbs while trying to multitask other stuff.

**Describe the solution you'd like**
Highlight the herb patches like you would highlight an npc when the herb planted hasn't been composted.

**Describe alternatives you've considered**
Alt 1: If not possible then maybe an alternative louder and more noticeable sound that plays when you compost your herb patch.

Alt 2: Maybe make it so after you check how many uses your bottomless compost bucket has the game adds a tiny overlay that shows you the number at all times and it detects when you use it so you can just look at the number after you're done farming to see if you forgot to use it on a herb.
**Additional context**

**Comment by Alexsuperfly** [comment] 2022-04-14 21:55
compost tracking is a duplicate of #2472

bottomless bucket charges are a duplicate of #8387

**Comment by Adam-** [comment] 2022-05-07 20:42
duplicate of #2472

**Closed by Adam-** 2022-05-07 20:42 UTC
