### ISSUE TITLE
Game has been crashing a LOT, even after windows reinstall

### ISSUE THREAD

**Issue by rascopog** [runelite/runelite#16691] opened 2023-06-19 08:04 UTC
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10

### Bug description

My game will randomly crash half the time with an error message and half the time it just closes. It has been doing this for about a month and I tried a lot of things and I finally reinstalled windows but it is still crashing somehow. Please any help would be appreciated. 

### RuneLite version

RuneLite 1.10.5
launcher version 2.6.4

### Logs

[jvm_crash_pid_14468.log](https://github.com/runelite/runelite/files/11785726/jvm_crash_pid_14468.log)
[jvm_crash_pid_4704.log](https://github.com/runelite/runelite/files/11785727/jvm_crash_pid_4704.log)
[client.log](https://github.com/runelite/runelite/files/11785728/client.log)
[launcher.log](https://github.com/runelite/runelite/files/11785729/launcher.log)
[jvm_crash_pid_4764.log](https://github.com/runelite/runelite/files/11785730/jvm_crash_pid_4764.log)
[jvm_crash_pid_7324.log](https://github.com/runelite/runelite/files/11785731/jvm_crash_pid_7324.log)

**Comment by Nightfirecat** [comment] 2023-06-19 15:13
Duplicate of #10628, we don't know what causes this crash.

**Closed by Nightfirecat** 2023-06-19 15:13 UTC
Labels: duplicate
