### ISSUE TITLE
Add monster loot logger

### ISSUE THREAD

**Issue by hihi9190** [runelite/runelite#1235] opened 2018-04-02 02:53 UTC
A plug in on the side that lists all loot you obtained. It will be useful for tracking boss loot and slayer task loot.

**Comment by sirlaige** [comment] 2018-07-21 02:36
Some how my suggestion got labeled a duplicate of yours and has been closed.  Your suggestion doesn't seem to be like mine so I'll drop my suggestion here since ours is now linked and it is unlikely mine will be seen.  I didn't even mention loot.  Here goes  \/

Is your feature request related to a problem? Please describe.
I want to keep track of the monsters I kill via a plugin similar to the Xp tracker plugin. I would like this mainly for times that I need to know the amount of the monsters I've killed, like going for champion scrolls. The likelihood is 1in5k

Describe the solution you'd like
Add a plugin that will keep track of the number of each monster the player kills for the play session. Like the xp tracker that shows the skills you worked on during the play session except this will list all the monster you have killed and the number of times you killed them.

Describe alternatives you've considered
Another option would be the health bar plugin you guys have for monster. Just add a spot/ option to have kill count shown in addition.

Additional context
Perhaps this could integrate with other plugins, Like the examine of an item will give the value on ge, and for this perhaps examine on a monster could display their kill count.

**Closed** 2018-07-31 21:49 UTC
Labels: feature-request
