### ISSUE TITLE
2005 Interface Chatbox Fix 

### ISSUE THREAD

**Issue by Brochir** [runelite/runelite#11896] opened 2020-06-14 13:27 UTC
I use the 2005 interface since day 1 and have been loving it! Thanks for everything Runelite Team.

But the current 2005 Interface chatbox has neither the proper "torn page" effect nor does it show text properly. Sometimes the in game chatbox text gets chopped of from the side and top so I feel like its stuck in the middle of it being not like the original or better for the bigger chatbox.

I understand we cannot do the torn effect properly but making it like I have shown below it still has the 2005 aesthetic while enabling us to be able to read all text in game. 

![EabgYskX0AAG0_k](https://user-images.githubusercontent.com/66905841/84591835-878b0980-ae0f-11ea-952a-0fc439c6ca42.png)

**Comment by raiyni** [comment] 2020-06-14 13:27
Duplicate of https://github.com/runelite/runelite/issues/6041

**Closed by raiyni** 2020-06-14 13:27 UTC
