### ISSUE TITLE
GPU plugin only works ONCE before freezing and needing a reinstall

### ISSUE THREAD

**Issue by Shibalicious** [runelite/runelite#6790] opened 2018-12-02 17:38 UTC
Hi,

I am using the Windows 64-bit version. As the title mentions, Runelite GPU plugin only works once without crashing before needing a fresh reinstall. I turn Runelite on, enable the GPU plugin, it works. I close Runelite, reopen it, the game freezes at the loading screen (it says loading blah blah blah, but I am pretty sure it's just a frozen black screen). If I turn GPU plugin off before turning Runelite off, same thing happens. The only way to fix it is to fully reinstall the client.

I have tried various fixes including disabling HW acceleration, disabling compability options, using fixed size screen, enforcing to use my dedicated Nvidia GPU etc.. The launcher.log seems pretty clean too:

[application.log](https://github.com/runelite/runelite/files/2637181/application.log)
[launcher.log](https://github.com/runelite/runelite/files/2637182/launcher.log)

1. Turn on Runelite, turn GPU plugin ON.
2. Turn off Runelite.
3. Turn Runelite back ON.
4. Get stuck at the loading/black screen, the UI is still responsive but the OSRS itself is just stuck.
5. Observe jogamp_exe_tstxxxx processes still running even after the Runelite client is closed (I know they have something to do with audio/video).

Expected behavior:
Smooth toggling between ON and OFF of the GPU plugin, even after restarting Runelite.

Environment (please complete the following information):
 - OS: Windows 7 Ultimate SP1, 64-bit
 - RuneLite version: 1.5.2.1
 - Launcher version: 1.6.1
 - JRE/Java 8, 64-bit
 - Nvidia GeForce 980 Ti, latest drivers (same thing happened with 8 months old drivers)

I managed to fix it by running the standalone .jar client file. No jogamp_exe_tstxxxx files are left hanging. Clean toggling between GPU plugin ON and OFF, the client itself is much smoother as well. I am not sure what's the difference between the .jar version and the Windows version if the entire client + the game itself is written in Java..

Anyway, hope this helps someone!

**Comment by deathbeam** [comment] 2018-12-02 18:11
Duplicate of #6646

**Closed by deathbeam** 2018-12-02 18:11 UTC
