### ISSUE TITLE
Pop out side-bar or left side side-bar

### ISSUE THREAD

**Issue by MichaelUnce** [runelite/runelite#7809] opened 2019-02-11 19:38 UTC
**Describe the solution you'd like**
I think it would be more convenient if the side bar is able to be in a different place on the screen currently its always on the right side, i do a lot of herb runs so i check the side bar frequently and bird house runs.

**Comment by Spedwards** [comment] 2019-02-11 20:06
Duplicate of #1641 and #6267

**Closed** 2019-02-11 20:07 UTC
