### ISSUE TITLE
Wiki search chat command

### ISSUE THREAD

**Issue by dmxt** [runelite/runelite#7874] opened 2019-02-16 00:36 UTC
### **Is your feature request related to a problem? Please describe.**
1. Chatbox shortcut to looking up on the wiki. Examples on the next section.

2. Add plugin settings for an option to toggle the ugly[1] wiki button on the minimap, without disabling the entire wiki feature.

_[1] Subjective opinion from a professional designer, it's an eyesore. Wiki button looks very unnatural, unappealing, and out of the place and some players may not like it _

### **Describe the solution you'd like**
**1. Make some chatbox command, examples below:**
* `osrs [TAB] d scim`
* `wiki [TAB] d scim`
* `!osrs d scim`
* `!wiki d scim`
etc...

**1. Give users an option to toggle the wiki button on the minimap:**
At the moment we don't have much choice, either disable the useful plugin entirely to disable it or continue using it.

Add an option to Wiki plugin settings for users to turn off/on the wiki button on minimap without revoking all other wiki features.

Actions will follow after pressing enter on one of commands:
1. If pressed enter on [TAB], it will behave like a browser search engine i.e. `youtube [TAB] d scim` then open a browser with the argument as a search; in this instance scim`.
2. If using `!osrs` or `!wiki` commands, it will open the browser with the argument a search.

### **Wiki button plugin in Wiki settings**
* Make it toggleable to disable the wiki button on the minimap without revoking remaining wiki features

### **Additional context**
Wiki button on minimap
![image](https://user-images.githubusercontent.com/3248782/52890933-7962a580-3155-11e9-8835-d911da7c89ba.png)
One of the chat command
![image](https://user-images.githubusercontent.com/3248782/52891198-6bae1f80-3157-11e9-92cd-884c66ac83e8.png)

**Comment by Abextm** [comment] 2019-02-16 00:44
I chose the icon and I agree its moderately ugly, but no one was able to give me a icon that was better, or even fit the requirements imposed by its location. That being said a chat command is not the way to fix this.

**Comment by Nightfirecat** [comment] 2019-02-16 06:53
I think it would fit in a lot better if the edges were only white when it was selected. I might look at touching it up this weekend.

**Comment by ShaunDreclin** [comment] 2019-02-16 07:02
It should probably also have a mouseover effect to fit in better with the other minimap buttons

**Comment by Nightfirecat** [comment] 2019-04-12 06:13
The second part of this issue seems to be a duplicate of #8320, so I am updating the title to reflect that this issue should only track the request for a wiki search chat command.

**Comment by dekvall** [comment] 2020-01-31 01:02
Jagex has added this as a [vanilla feature](https://secure.runescape.com/m=news/wiki-integration?oldschool=1), you use it by typing `::wiki <query>`

**Closed by dekvall** 2020-01-31 01:02 UTC
Labels: feature-request
