### ISSUE TITLE
Loot Blocker

### ISSUE THREAD

**Issue by Feature-Request** [runelite/runelite#3752] opened 2018-06-12 08:28 UTC
**Is your feature request related to a problem? Please describe.**
Picking up unwanted items by mistake. Ex. bones, ashes & vials.

**Describe the solution you'd like**
A menu entry swapper feature that hides bones/ashes/vials.

**Describe alternatives you've considered**
'Walk here' as first option, rather than the 'take' option.

**Additional context**
The Loot Blocker feature would only block certain unwanted items like different bone types/ashes/vials.
To combat looters, the feature could be blocked in PvP situations, whether it's the wilderness or PvP worlds. This would also allow the feature to have a wider variety of items that could be blocked.

**Comment by Gamer1120** [comment] 2018-06-12 15:43
Relates to or duplicate of #1711

**Comment by bmiddle** [comment] 2018-06-12 19:11
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features last bullet point

**Comment by Nightfirecat** [comment] 2018-07-02 23:33
This can be closed, it's a feature on the rejected/rolled-back wiki page as mentioned above.

**Closed** 2018-07-08 00:33 UTC
Labels: feature-request
