### ISSUE TITLE
Allow players to change the fill color and opacity of Tile Indicators

### ISSUE THREAD

**Issue by dakoders** [runelite/runelite#14445] opened 2021-12-05 21:49 UTC
**Is your feature request related to a problem? Please describe.**
Yes - The tile indicators currently add a dark gray shade to any tile indicator that is enabled (hover, true, destination) and can often make it really difficult to tell if a portal/grasping claws is spawning under the player in Nightmare and Phosani's Nightmare.

**Describe the solution you'd like**
I'd like to be able to select the color and opacity of the tile indicators, so I can choose to either have the tile filled with a light color (like the official client), have it just outlined and the fill transparent, or have both a colored infill and outline.

**Comment by Hydrox6** [comment] 2021-12-05 21:52
Duplicate of #4188

**Comment by Adam-** [comment] 2021-12-08 17:44
added in #14447

**Closed by Adam-** 2021-12-08 17:44 UTC
Labels: feature-request
