### ISSUE TITLE
Add charge value to weapons in worn item inventory

### ISSUE THREAD

**Issue by TheStonedTurtle** [runelite/runelite#3683] opened 2018-06-08 03:49 UTC
Add a counter that shows how many charges until your weapon degrades (I.E. Trident, Archlight, Tentacle, Ibans Staff, Etc) similar to how the slayer helmet overlay looks (example: ![](https://i.imgur.com/h4oZxOR.png) )

**Comment by Alexsuperfly** [comment] 2019-07-28 18:52
basically duplicate of #953

**Comment by Nightfirecat** [comment] 2019-08-12 16:13
I don't think that's the request--as I understand it, this is simply a request to show the charges for any equipment we track charges for when on the equipment tab in addition to on the inventory tab.

**Comment by deathbeam** [comment] 2019-08-12 16:38
Both are requests to show charges for items with charges, so closing as duplicate of #953

**Closed by deathbeam** 2019-08-12 16:38 UTC
Labels: feature-request
