### ISSUE TITLE
Add an error message / dialog box when Runelite can't connect to the servers

### ISSUE THREAD

**Issue by Pikamander2** [runelite/runelite#8034] opened 2019-02-28 14:40 UTC
I tried to launch Runelite just now, but it wouldn't open. It went through the entire loading bar, but then the game never launched. I went through the troubleshooting steps, but nothing seemed to help. There were no errors in my launcher.log file either.

I tried uninstalling it and reinstalling it, but that didn't fix the issue either.

Then I checked Reddit and discovered that the servers were down due to a bug. It would have been nice if Runelite had told me that at the very start instead of silently disappearing.

Would it be possible to display an error message when the client can't connect to the server?

**Comment by Hydrox6** [comment] 2019-02-28 14:41
This is better off going in [the launcher repo](https://github.com/runelite/launcher)

**Comment by Adam-** [comment] 2019-02-28 14:43
Depending on what "the servers" means, it could easily apply to both repos.

**Comment by Pikamander2** [comment] 2019-02-28 14:50
Added it there as well: https://github.com/runelite/launcher/issues/57

**Comment by JarJarr** [comment] 2019-02-28 14:57
If I'm not mistaken the entire game is down right now in a rollback. Due to a glitch spawning Twisted Bows on the floor near the farming guild.

**Comment by Gamer1120** [comment] 2019-03-08 00:24
Duplicate of / related to #4847

**Closed** 2019-03-08 06:58 UTC
Labels: feature-request
