### ISSUE TITLE
imbued heart timer

### ISSUE THREAD

**Issue by adambtwl0l** [runelite/runelite#11041] opened 2020-03-19 16:48 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Currently it seems mainly if your character is doing another animation or has something going on, preventing the red lightning or whatever one may call it from the imbued heart from appearing when you use it, the timer for the heart will not appear. At least from practice I assume this is the cause, but it doesn't appear sometimes and this appears to be why. This is common in combat where you're being hit by multiple things such as DKs and sometimes elsewhere as well. (Also had it happen at sarachnis, perhaps due to the minions?)
**To Reproduce**

**Expected behavior**
The imbued heart timer should appear when either the client sees you've been boosted up to 109, or possibly make it work like the slayer counter with barrage tasks where refreshing it by checking the helm works, but instead make it so that clicking the heart and receiving a chatbox message will result in some sort of relatively correct timer appearing (I realize unless it's below 1 minute it just says 1 minute 2 minutes etc and it won't give accurate time until below 1 minute, but this is still better than no timer)
**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Nightfirecat** [comment] 2020-03-19 16:49
Duplicate of #3516

**Closed by Nightfirecat** 2020-03-19 16:49 UTC
Labels: duplicate
