### ISSUE TITLE
GPU-related Memory Leaks

### ISSUE THREAD

**Issue by Biice** [runelite/runelite#7390] opened 2019-01-16 14:31 UTC
**Describe the bug**
(AMD-?) GPU-related memory leaks of up to 6GB causing RuneLite to drop frames & stutter.

**To Reproduce**
Turn on the GPU-plugin and wait. Can't reproduce instantly.
Sometimes an hour or two without any issues, other times constant leaks. 
Logging out and logging back in (without closing down the client) seems to be an effective way of reproducing the bug. To remedy this, the GPU-plugin needs to be turned off and on again, in the hope of the memory not leaking thereafter.

PS: already tried rolling back my GPU driver, this did **not** fix it.
Turning off the GPU-plugin instantly stops the memory from leaking.

**Expected behavior**
Solid 50FPS without memory leaks as I've come to expect of RuneLite. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.7
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Alexsuperfly** [comment] 2019-01-16 14:34
did you roll back to 18.12.1, because thats the one that fixes it for other people

**Comment by Biice** [comment] 2019-01-16 14:39
> did you roll back to 18.12.1, because thats the one that fixes it for other people

Correct, 18.12.1 is indeed the version I rolled back to and the one I am currently using, as per Discord advice. Leaks are however still occurring quite regularly.

**Comment by bvanrosendale** [comment] 2019-04-25 03:21
I've found that fossil island tends and the arceuus library tends to trigger memory leaks much more frequently than any other area.

**Comment by Benbunnies** [comment] 2019-07-21 02:08
Is there any update on this issue? I'm still getting it when I do Arceuus library for a bit.

**Comment by Nightfirecat** [comment] 2022-07-10 04:01
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:01 UTC
Labels: needs-information, gpu
