### ISSUE TITLE
ChatMessageManager#update is not run on client thread

### ISSUE THREAD

**Issue by devLotto** [runelite/runelite#5933] opened 2018-10-11 15:59 UTC
The assertion ``assert client.isClientThread();`` in VarbitMixin#getVarbitValue fails when ChatMessageManager's refreshAll is run and you have transparent chatbox enabled. 

Because of this, the chat is not recolored if you're in developer mode with transparent chatbox enabled.

```
2018-10-11 17:51:51 [pool-2-thread-1] WARN  n.r.c.util.RunnableExceptionLogger - Uncaught exception in runnable net.runelite.client.chat.ChatMessageManager$$Lambda$136/712680575@45ebdf04
java.lang.AssertionError: null
	at client.getVarbitValue(client.java:75)
	at client.getVar(client.java:60)
	at net.runelite.client.chat.ChatMessageManager.update(ChatMessageManager.java:564)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.runelite.client.chat.ChatMessageManager.lambda$refreshAll$4(ChatMessageManager.java:601)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by Kamielvf** [comment] 2018-10-11 16:02
Duplicate of #5897

**Closed** 2018-10-11 16:08 UTC
Labels: bug
