### ISSUE TITLE
XP Globe improvement (and a bug) [Enhancement] [Bug]

### ISSUE THREAD

**Issue by SirBenvil** [runelite/runelite#2884] opened 2018-05-18 17:43 UTC
It would be nice if we could make the globes transparent like shown on the first picture on the wiki, and if we could adjust text size separately from the RuneLite Settings. Currently, to have bold text for dropped items, you'll also have it for the XP Globe tooltips. On top of that, if you're set to bold text, it will clip outside the tooltip box

**Comment by deathbeam** [comment] 2018-05-18 19:27
Duplicate of #890 and some other one

**Closed by deathbeam** 2018-05-18 19:27 UTC
