### ISSUE TITLE
Exclude/Toggle undead combat mummy as npc

### ISSUE THREAD

**Issue by dragonboi44** [runelite/runelite#9932] opened 2019-09-28 00:07 UTC
**Is your feature request related to a problem? Please describe.**
Quality of life. Currently as it stands, if i want to check my hits on the dummy while having entity hider on, it will vanish the dummy when attached to the stand.

**Describe the solution you'd like**
My suggestion would be to exclude the dummy from the entity filter since there should really be no need for it to be excluded since that filter is mainly used for combative npc's in runescape. 

A toggle could also be an alternative to appease those who may actually want it for the purpose of hiding it i guess? or heck it may be easier to do with a toggle idk :p
**Describe alternatives you've considered**

**Additional context**

**Comment by Nightfirecat** [comment] 2019-09-28 00:14
Duplicate of #2558

**Closed by Nightfirecat** 2019-09-28 00:14 UTC
Labels: duplicate
