### ISSUE TITLE
Fight Cave plugin stuck behind status bars

### ISSUE THREAD

**Issue by Jbluehdorn** [runelite/runelite#6722] opened 2018-11-28 04:12 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When playing in resizable mode, the status bars are placed above the indicator for which prayer to use against Jad.

**To Reproduce**
1. Turn on Status Bars and Fight Caves plugins
2. Fight Jad

**Expected behavior**
The status bars or Fight caves prayer indicator moveable to a different location.

**Environment (please complete the following information):**
 - OS: MacOS Mojave 10.14.1
 - RuneLite version: 1.5.2

**Comment by Nightfirecat** [comment] 2018-11-28 04:37
That's expected behavior; the anchor point for the jad overlay is in the same location as the status bars in resizable mode. You can hold Alt and move the jad prayer overlay

**Comment by Jbluehdorn** [comment] 2018-11-28 05:59
@Nightfirecat is it possible to do that when I'm not having to pray switch against Jad?

**Comment by Nightfirecat** [comment] 2018-11-28 06:06
Unfortunately, it's not possible to move overlays which are not visible on the canvas.

**Comment by sadegr** [comment] 2018-11-29 20:52
Would it be possible to set the fight caves plugin icons to be on top of the status bars by default? It doesn't make much sense to have it the other way around by default.

**Comment by deathbeam** [comment] 2018-11-30 09:01
Just move the overlay with ALT. It cant be on top of anything, because of different layers that are mostly fixed

**Comment by deathbeam** [comment] 2018-11-30 09:04
#4461 will mostly solve this, so closing as duplicate of that

**Closed by deathbeam** 2018-11-30 09:04 UTC
