### ISSUE TITLE
Toxic Blowpipe Ammo Indicator

### ISSUE THREAD

**Issue by AildirMike** [runelite/runelite#9430] opened 2019-07-21 22:33 UTC
**Toxic Blowpipe is not showing up when Ammo plugin is enabled.**
**Possibility of showing both darts and scales?**

**To Reproduce**
1. Go to Ammo Plugin
2. Put on Toxic Blowpipe (filled with ammo)
3. See error: No ammo shown.

![CaptureRLAmmo](https://user-images.githubusercontent.com/51796970/61598039-2c10c580-ac18-11e9-82bb-0d399f6dec10.PNG)

**Comment by xDemoN** [comment] 2019-07-21 23:22
#2990 has been sitting around for a long time attempting to implement it

**Comment by Alexsuperfly** [comment] 2019-07-28 21:29
duplicate of #953

**Closed** 2019-07-28 21:43 UTC
