### ISSUE TITLE
Degradable equipment not unified in Tag Search

### ISSUE THREAD

**Issue by TaxoRubio** [runelite/runelite#4440] opened 2018-07-21 22:45 UTC
**Describe the bug**
When taking degradable equipment such as Barrows or Crystal with Tag Search the placeholder disappears because it has a different name (no degradation number).

**To Reproduce**
1. Edit tags in a dagraded Barrows item
2. Tag search and take it
3. See the placeholder disappear

**Expected behavior**
The degraded item should be linked to its placeholder name and not disappear.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.8.1
 - Launcher version: Unknown, sorry

**Comment by deathbeam** [comment] 2018-07-23 06:46
Duplicate of #3767

**Closed by deathbeam** 2018-07-23 06:46 UTC
