### ISSUE TITLE
Add ETA to level up to XP globes

### ISSUE THREAD

**Issue by kbeliasas** [runelite/runelite#4380] opened 2018-07-18 07:35 UTC
Hi,

can you please add feature which shows how much time is left to level up skill. Couse now it only shows how much actions left and xp/hour rate. Time can be based on xp/houre rate and how much xp left to level up. Thanks.

**Comment by Nightfirecat** [comment] 2018-07-18 07:42
An ETA is available if you hover the tracker for the specific skill.

**Comment by kbeliasas** [comment] 2018-07-18 07:55
![image](https://user-images.githubusercontent.com/35032624/42867681-fb35b86a-8a78-11e8-8655-c92b102edb15.png)
![image](https://user-images.githubusercontent.com/35032624/42867692-02c85704-8a79-11e8-9522-53af0459620b.png)
Can't see it :(

**Comment by deathbeam** [comment] 2018-07-18 08:12
That is not xp tracker, those are xp globes. You have the ETA in sidebar.

**Comment by deathbeam** [comment] 2018-10-19 12:35
Duplicate of #1041

**Closed by deathbeam** 2018-10-19 12:35 UTC
Labels: feature-request
