### ISSUE TITLE
Ability to toggle active screen markers visible/invisible 

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#10978] opened 2020-03-07 17:52 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes I want to turn my markers off quickly to get a clean screenshot and I'm always too late when I have to open the config panel. It'd also be nice to toggle them quickly when hopping between activities as they can be an eyesore one minute and come in handy the next.

**Describe the solution you'd like**
My suggestion is a configurable keyboard shortcut that toggles screen markers visible and invisible.

**Describe alternatives you've considered**
If you're opposed to keyboard shortcut perhaps rightclicking the screenmarker panel icon could toggle markers visible/invisible.

**Comment by Nightfirecat** [comment] 2020-03-08 02:56
What situations are you in where you need to take a quick (ie. time-sensitive) screenshot where going into the screen markers panel takes too much time?

**Comment by T7000** [comment] 2020-03-08 08:36
Spontaneous moments for screenshots occur all the time for me, for friend/cute noob/celebrity sightings, fashionscape, levels, drops, random events, bugs/glitches, funny chat messages. They're an eyesore in all screenshots in my opinion and they're a hassle to toggle, by the time I've turned off the markers the ideal photo opportunity I saw might have passed.

The last few significant times for me it was coming across someone and rightclicking their character to take a screenshot with their name visible but having my markers cover the menu. I then had to move my cursor out of the game to open the configuration panel, scrolling/searching for the screen markers entry and toggling it, by then the player had moved out of sight or tele'd and I was too late. 

The screen markers panel itself doesn't have a way to toggle all currently active markers or a group of markers quickly, only individual markers with a small clickable eye icon.

If it was quick/intuitive I'd also toggle my markers regularly when hopping between activities, they're handy when doing a skill that requires banking but they're an eyesore when going for birdhouse/farm runs for example.

**Comment by dovry** [comment] 2020-03-11 09:41
Presets/grouping of screenmarkers could solve this issue

**Comment by Nightfirecat** [comment] 2020-03-12 07:16
Based on this issue description, screen marker grouping would not solve this issue, as it would require users to keep their screen marker panel open at all times.

**Comment by Nightfirecat** [comment] 2022-08-10 17:28
Duplicate of #2686

**Closed by Nightfirecat** 2022-08-10 17:28 UTC
Labels: duplicate
