### ISSUE TITLE
Customisable drop sounds for items. 

### ISSUE THREAD

**Issue by SimTar** [runelite/runelite#11167] opened 2020-04-02 16:18 UTC
**Is your feature request related to a problem? Please describe.**
Apart from possibly missing a drop because of AFKing, no.

**Describe the solution you'd like**
Ability to define different sounds for drops of different values. 
When you get a drop, the chosen sound is played.

**Describe alternatives you've considered**
Non-customisable sounds.

**Additional context**
Could be an extension to the Ground Items -plugin, as it already has a way to sort drops by value.

**Comment by ThimbleFire** [comment] 2021-01-15 19:48
idk if bumps work in github but I'd love this.
I wanted to set a custom sound notification for when a draconic visage dropped. I found a drop-dead sexy sound effect and set it as the custom notification sound for when I get a valuable drop. Only now I'm hearing it constantly, even for things that aren't drops. Don't get me wrong, I knew this was going to happen.
I just think of the sound effects from loot filters in Path of Exile and think how awesome it would be if runelite had something like that.

**Comment by Nightfirecat** [comment] 2021-01-15 22:49
Duplicate of #11679--while that issue was created after this one, it is more general as we would want to update the notification system to allow customization for any plugin, not just the ground items plugin.

**Closed by Nightfirecat** 2021-01-15 22:49 UTC
Labels: duplicate
