### ISSUE TITLE
Green stripes across display

### ISSUE THREAD

**Issue by lukenap** [runelite/runelite#11795] opened 2020-06-02 16:00 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Whenever I open RuneLite, the client runs, but the display is distorted by green stripes of various sizes

**To Reproduce**
1. Happens as soon as program opens

**Expected behavior**
A clear screen free of graphical errors

**Screenshots**
![image](https://user-images.githubusercontent.com/66322962/83541950-4f5b0100-a4c8-11ea-8bad-e3739b895b8d.png)

**Environment (please complete the following information):**
 - OS: 64-bit Windows 10 Home, version 1909, OS build 18363.836
 - RuneLite version: 1.6.17
 - Launcher version: 2.1.3

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Nightfirecat** [comment] 2020-06-02 16:03
Does this behavior happen with your GPU plugin turned on/off? Does [disabling hardware acceleration](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration) change this at all?

**Comment by lukenap** [comment] 2020-06-02 16:14
My apologies. Turning off GPU plugin got rid of the stripes. I should have checked that first, but thanks anyways.

**Comment by Nightfirecat** [comment] 2020-06-18 23:52
What have you tried? When did this start happening?

**Comment by MarshawnSkittles** [comment] 2020-06-19 05:34
I have tried uninstalling the launcher and reinstalling it. i also tried disabling hardware acceleration. Neither worked. Turning GPU plugin off gets rid of the problem but it sucks not being able to use GPU.

**Comment by raiyni** [comment] 2020-06-19 05:35
Do you have some kind of software like Riva Tuner or MSI Afterrburner installed?

**Comment by MarshawnSkittles** [comment] 2020-06-19 05:37
no i do not

**Comment by eunhon93** [comment] 2020-06-26 03:21
Same thing happening to me too. im on an intel hd 620 and the gpu plugin worked fine before no issues but now its having these issues. if a dev would like me to test anything or remote control my pc to test  just let me know. this is a fresh copy of windows so i only have runescape on it. its unplayable with out the gpu plugin since the game will run 15-30fps with out gpu

**Comment by Bram91** [comment] 2020-07-09 20:15
This bug seems to be caused by changes in the Intel graphics drivers. the `27.20.100.xxxx` drivers can produce green lines at the time of writing. Downgrading back to the `26.20.100.xxxx` seems to be resolving this problem.

**Comment by tre3tre** [comment] 2020-07-16 17:31
Did you find a solution? I'm having this problem now.

**Comment by Bram91** [comment] 2020-07-16 17:32
@tre3tre read the post above the one you just posted, alternatively you could join the discord for some easier troubleshooting.

**Comment by tre3tre** [comment] 2020-07-16 17:37
Yup rolling back the driver did it. Thank you.

**Comment by Nightfirecat** [comment] 2020-07-17 03:56
I've added the current solution to this issue to [the GPU FAQ wiki page](https://github.com/runelite/runelite/wiki/GPU-FAQ#green-stripes-are-appearing-on-my-screen). For the time being, that will serve as a better notice of the solution for this GPU bug than on the issue tracker. Thus, I'm closing this issue.

**Closed by Nightfirecat** 2020-07-17 03:56 UTC
Labels: gpu, not-our-bug

**Comment by Fieel** [comment] 2021-01-06 12:56
> @tre3tre read the post above the one you just posted, alternatively you could join the discord for some easier troubleshooting.

Downgrading drivers is no a solution. Can we find a real one please?

**Comment by Fieel** [comment] 2021-01-20 18:26
Intel released plenty of drivers since this issue has been closed and it really looks like Runelite should look into it rather than Intel, what do you think? I don't think this problem has been resolved

**Comment by TheEbolaArrow** [comment] 2022-05-23 09:55
I agree with Fieel its not an intel or a driver problem, i have found a fix hope it helps, click the **<** arrow in the top right disable and uninstall the 117 HD plugin (thats the cause of the problem) close your Runelite client, then relaunch and reinstall the 117 if you wish. let me know if this works out for you.
-cheers
