### ISSUE TITLE
No Audio with Pipewire

### ISSUE THREAD

**Issue by sangoku116** [runelite/runelite#14345] opened 2021-11-05 22:29 UTC
**Describe the bug**
There is no audio since I switched from pulseaudio to PipeWire. All other applications work fine. RuneLite also does not show up in the audio mixer.  I have ```pipewire-alsa``` installed. 

**To Reproduce**
1. Launch RuneLite
2. Unmute the lobby sound or in-game sound

**Expected behavior**
There is supposed to be sound when in-game volume is turned on.

**Environment (please complete the following information):**
 - OS: Arch Linux 
 - RuneLite version: 1.8.1
 - Launcher version: 2.2.0

**Additional context**
Client Logs:
```
2021-11-05 12:45:13 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.1 (launcher version 2.2.0) starting up, args: none
2021-11-05 12:45:20 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2021-11-05 12:45:20 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2021-11-05 12:45:20 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1743293556.307
2021-11-05 12:45:21 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-11-05 12:45:21 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.8" commit "1d290f6d64c44acd306dfdc84553952ebc96b03e"
2021-11-05 12:45:21 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" version "2.6.1" commit "68a62a0f64174b4ddfeac810557f1e04ec54423b"
2021-11-05 12:45:21 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2021-11-05 12:45:22 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 8918ms. Uptime: 15360ms
2021-11-05 12:45:22 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,2408,209,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@698ef40,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-11-05 12:45:23 [Client] INFO  rs117.hd.HdPlugin - Using device: AMD Radeon RX 6900 XT (sienna_cichlid, LLVM 12.0.1, DRM 3.42, 5.14.16-lqx1-4-lqx)
2021-11-05 12:45:23 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6 (Compatibility Profile) Mesa 22.0.0-devel (git-92215d8da8)
2021-11-05 12:45:23 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user ..zangoku.
2021-11-05 18:19:49 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.1 (launcher version 2.2.0) starting up, args: none
2021-11-05 18:19:50 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2021-11-05 18:19:50 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2021-11-05 18:19:51 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1743293556.307
2021-11-05 18:19:51 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-11-05 18:19:52 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.8" commit "1d290f6d64c44acd306dfdc84553952ebc96b03e"
2021-11-05 18:19:52 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" version "2.6.1" commit "68a62a0f64174b4ddfeac810557f1e04ec54423b"
2021-11-05 18:19:52 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2021-11-05 18:19:53 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 3653ms. Uptime: 5022ms
2021-11-05 18:19:53 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,4212,210,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@2c18fa84,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-11-05 18:19:54 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user ..zangoku.
2021-11-05 18:19:58 [Client] INFO  rs117.hd.HdPlugin - Using device: AMD Radeon RX 6900 XT (sienna_cichlid, LLVM 12.0.1, DRM 3.42, 5.14.16-lqx1-4-lqx)
2021-11-05 18:19:58 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6 (Compatibility Profile) Mesa 22.0.0-devel (git-92215d8da8)
```

**Comment by Hydrox6** [comment] 2021-11-05 22:57
Basically a duplicate of #3525

**Closed by Hydrox6** 2021-11-05 22:57 UTC

**Comment by sangoku116** [comment] 2021-11-05 22:59
> Basically a duplicate of #3525

It is not a duplicate, they are using pulseaudio here. I am using pipewire.

**Comment by Lindenk** [comment] 2021-12-15 22:18
I also have this problem using pipewire with the correct alsa and jack plugins installed

**Comment by hankjordan** [comment] 2022-05-05 21:27
Try this https://github.com/runelite/runelite/issues/3525#issuecomment-1119058063
