### ISSUE TITLE
Severe performance/deprecation/other warnings on glBufferSubData GL_STATIC_DRAW

### ISSUE THREAD

**Issue by AndreasBackx** [runelite/runelite#7320] opened 2019-01-12 22:20 UTC
**Describe the bug**
Whenever the GPU plugin is enabled the following output is spammed to the console:

```
GLDebugMessageHandler: GLDebugEvent[ id 0x3
	type Warning: implementation dependent performance
	severity Medium: Severe performance/deprecation/other warnings
	source GL API
	msg using glBufferSubData(buffer 2, offset 0, size 32) to update a GL_STATIC_DRAW buffer
	when 1547331167706
	source 4.5 (Core profile, arb, debug, compat[ES2, ES3, ES31, ES32], FBO, hardware) - 4.5 (Core Profile) Mesa 18.3.1 - hash 0x4ef97deb]
```

The GPU plugin is working as desired. No weird artefacts or anything of note.

**To Reproduce**
1. Enable the GPU plugin

**Expected behavior**
No constant warnings.

**Environment:**
 - OS: Arch Linux 4.20.0
 - RuneLite version: master branch 0f8a9b934a680e1669bc79e24840ae6aa20473a4 (this is run from IntelliJ)
 - Launcher version: unknown

**Additional context**

GPU: Radeon RX Vega 56
Driver: Mesa 18.3.1

**Comment by deathbeam** [comment] 2019-01-13 11:12
Duplicate of #7154

**Closed** 2019-07-26 08:59 UTC
Labels: bug, gpu
