### ISSUE TITLE
Easy clue step "Speak to the bartender of the Blue Moon Inn in Varrock" highlights wrong NPC

### ISSUE THREAD

**Issue by sadegr** [runelite/runelite#7838] opened 2019-02-13 00:04 UTC
The easy clue step "Speak to the bartender of the Blue Moon Inn in Varrock" causes the bartender of the Dragon Inn in Yanille to be highlighted.
![2019-02-12_19-00-37](https://user-images.githubusercontent.com/20391979/52676661-e4637080-2ef8-11e9-9ae2-de422cca6ac6.png)

... as well as the bartender of the new pub in Lumbridge.
![2019-02-12_19-06-20](https://user-images.githubusercontent.com/20391979/52676834-74091f00-2ef9-11e9-91df-89627bd275b1.png)

This appears to happen with any NPC named "Bartender."

**Comment by Nightfirecat** [comment] 2019-02-13 01:42
Duplicate of #5231

**Closed** 2019-02-13 02:59 UTC
Labels: duplicate
