### ISSUE TITLE
Elite Clue Step "Has no one told you it is rude to ask a lady her age?" is wrong.

### ISSUE THREAD

**Issue by mattDavies1997** [runelite/runelite#9729] opened 2019-08-24 21:59 UTC
The elite cryptic clue step "Has no one told you it is rude to ask a lady her age?" refers you to Lady Tangwen Trahaearn in Prifddinas, however the wiki states that it is actually speak to Mawrth in Lletya.

When I tried to talk to Lady Tangwen Trahaearn, it just had the normal dialogue which was how I noticed the issue. I looked it up on the wiki and went to Mawrth and got the next step.

Easy to fix I imagine, but figured I should let you know :)

**Comment by Hydrox6** [comment] 2019-08-24 22:00
Duplicate of #9459

**Closed by Hydrox6** 2019-08-24 22:00 UTC
