### ISSUE TITLE
Adjustable information boxes

### ISSUE THREAD

**Issue by RsRandall** [runelite/runelite#5259] opened 2018-09-02 08:10 UTC
Shown in the image, some Clue steps have skinny information boxes and others have wider ones, it would be nice to adjust their width and length to fit in similar areas of the screen.

![infobox](https://user-images.githubusercontent.com/41773445/44953772-73e10e00-aedb-11e8-98eb-095520818078.jpg)

**Comment by deathbeam** [comment] 2018-09-02 08:36
Duplicate of #3916

**Closed by deathbeam** 2018-09-02 08:36 UTC
