### ISSUE TITLE
Allow Bold, Itallics, Underline, and Strikethrough on the notes tab.

### ISSUE THREAD

**Issue by lacaze** [runelite/runelite#9134] opened 2019-06-18 05:05 UTC
**Is your feature request related to a problem? Please describe.**
No, I find that I put a lot of notes including numerous lists on the notes tab and it's very helpful to have in game though it looks very disorganized and sloppy. I think this can add more organization and make notes look nicer. 

**Describe the solution you'd like**
Allow Bold, Itallics, Underline, and Strikethrough on the notes tab so you can edit the text to make it look nicer and more organized.

**Describe alternatives you've considered**
I have added things like a lot of hyphens to organize sections but it looks messy still and is difficult to organize.

**Additional context**
Though it is a small detail and probably not a ton of people would use it. I feel those who use notes and rely on them like I do would appreciate this update a lot :)

**Comment by Nightfirecat** [comment] 2019-06-19 16:13
Duplicate of #6921

**Closed by Nightfirecat** 2019-06-19 16:13 UTC
Labels: duplicate
