### ISSUE TITLE
World hop log

### ISSUE THREAD

**Issue by FranciscoKnebel** [runelite/runelite#7866] opened 2019-02-15 16:33 UTC
**Is your feature request related to a problem? Please describe.**
OK, so I had a problem yesterday. My client crashed (it happens sometimes when opening plugins, don't have enough info about it to submit a bug report) and my character died. I knew where I was, but not the world.
RuneLite has a plugin for tracking deaths where it shows the world you died on, but it's not usable if your client crashes.
I propose keeping data about your last logged worlds, so even if the client/operating system crashes, one could re-open the client and know which world was used.

**Describe the solution you'd like**
A way to know your last used worlds. The client plugin doesn't know you died since it crashed, but keeping a log of your last used worlds is possible. A plugin could be added to check your used worlds (or an indicator in World Switcher) or just output the raw data of worlds in a separate file in logs folder, which the user could find if the client crashed, for any unrelated reason.

**Describe alternatives you've considered**
- Logfile with the last **n** worlds used.
- A small indicator in World Switcher plugin, that checks logfile for last used worlds.
- Separate plugin with a list of worlds, in order of most recently used.

**Additional context**
No additional context needed. Open to discussion on different implementations.

**Comment by Hydrox6** [comment] 2019-02-15 16:34
Duplicate of #3853

**Closed** 2019-02-15 16:35 UTC
