### ISSUE TITLE
Hunter overlay delay

### ISSUE THREAD

**Issue by DerWahreTom** [runelite/runelite#1553] opened 2018-04-15 06:29 UTC
The Hunter feature is i little bit buggy so the overlay has a pretty good delay so can you fix that

**Comment by nrodrigues0213** [comment] 2018-04-15 10:56
Could you give an example where this delay occurs? What are you catching?

**Comment by stevenoctopus** [comment] 2018-04-15 18:34
To help elaborate:

I was using this at black salamanders earlier and the plugin didn't recognize catches ~50% of the time. It would remain a yellow circle and never go from orange to green.

**Comment by SomeoneWithAnInternetConnection** [comment] 2018-04-15 18:36
This sounds like it's a duplicate of, or at least related to, #1169

**Comment by nrodrigues0213** [comment] 2018-04-15 20:25
I have diagnosed the problem. By default, the trapping trees face to the East. Every tree shares the same core object. When Jagex added these trees, they only rotated the model. The rest of the object's state remained the same. 

Thus, when the client tried looking for a successful salamander catch it failed. It was off by 1 tile! To fix this issue, I'll be separating the salamander cases to their own sections and have the program check 3 tiles around any stored tile (if and only if a null trap is detected).

**Comment by DerWahreTom** [comment] 2018-04-15 21:06
ty ;D

**Comment by nrodrigues0213** [comment] 2018-04-15 21:55
This bug has been fixed!
![after2](https://user-images.githubusercontent.com/25905465/38783826-df138de8-40d5-11e8-85cb-815d343f2dbf.png)


Now, I'll be doing some review on the changes and a pull request should be up in a few hours.

**Comment by Adam-** [comment] 2018-04-19 03:11
Fixed in #1577

**Closed by Adam-** 2018-04-19 03:11 UTC
Labels: bug
