### ISSUE TITLE
Suggestion: Ability to save RuneLite's settings / configuration as profiles that can be loaded in the client

### ISSUE THREAD

**Issue by 6butterboy9** [runelite/runelite#11032] opened 2020-03-17 23:55 UTC
Would save a lot of time for people who end up frequently changing their RuneLite settings. 
For example people with multiple types of accounts or people who have different preferred settings for different kinds of content.

**Comment by Nightfirecat** [comment] 2020-03-18 22:54
Duplicate of  #2220, though I believe #10797 presents a possible work-around for this until we end up implementing a config profile system.

**Closed by Nightfirecat** 2020-03-18 22:54 UTC
Labels: duplicate

**Comment by RobinVandeWalle** [comment] 2020-04-15 19:43
How should I use the features from #10797 as a possible workaround? I haven't found much information about it.

**Comment by Alexsuperfly** [comment] 2020-04-15 19:45
https://github.com/runelite/runelite/wiki/General-Features#playing-with-multiple-accounts
