### ISSUE TITLE
Player Best command not working for Grotesque Guardians specifically

### ISSUE THREAD

**Issue by 3Fast5You** [runelite/runelite#8760] opened 2019-05-05 17:24 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The command for showing your "Player best" time for bosses, does not seem to work for Grotesque Guardians.
Neither of these work: !pb gargs, !pb dusk, !pb grotesque guardians
The same format works for other bosses (for example Zulrah).
To my knowledge, the "!pb" command is a RuneLite feature, and in this URL, "!pb dusk" is clearly used as an example for the "Player Best" feature.
I am not the only one who are not able to do this. I really think this applies to everyone, as we discussed this in my CC a couple of months back. Several people tried.

**To Reproduce**
1. Log in to a OSRS-account that has a personal best time on Grotesque Guardians and, to compare, one other solo boss (that has Player Best, Zulrah or Vorkath f.ex.)
2. Type "!pb zulrah" and click enter to confirm this works (it does)
3. Type "!pb dusk" (or !pb gargs etc.)

**Expected behavior**
I expected to see my player best for Grotesque Guardians, like you can do with Zulrah, etc.

**Screenshots**
Screenshot attached.

**Environment (please complete the following information):**
 - OS: Windows 7
 - RuneLite version: 1.5.22.1
 - Launcher version: Unable to find version, most likely newest as per 05.05.2019
(Given the info in the final line in the description, I don't think version matters. I have observed this error for several months.)
![player best gargoyle boss](https://user-images.githubusercontent.com/50300380/57197702-d4dd4c00-6f6a-11e9-915c-0d22314bcc9e.png)

**Additional context**

**Comment by Nightfirecat** [comment] 2019-05-05 17:26
Duplicate of #8454

**Closed by Nightfirecat** 2019-05-05 17:26 UTC
Labels: duplicate
