### ISSUE TITLE
Compute current GP/HR inside of Loot Tracker

### ISSUE THREAD

**Issue by ryan10611** [runelite/runelite#6335] opened 2018-11-04 07:26 UTC
I think this could be added quite concisely through an algorithm along the lines of:
**GP/hr** = ((total value/total count) **x** ((3600)/(avg kill in seconds))

**Comment by ryan10611** [comment] 2018-11-04 07:31
Update: edit because math was terribly off

**Comment by deathbeam** [comment] 2018-11-04 09:52
Duplicate of #5592

**Closed by deathbeam** 2018-11-04 09:52 UTC
