### ISSUE TITLE
Remaining Toxic Blowpipe Zulrah Scale/Dart Counter

### ISSUE THREAD

**Issue by PuffBigDoink** [runelite/runelite#8270] opened 2019-03-20 13:02 UTC
An optional GUI feature which shows you how many Zulrah's scales and darts you have left in your toxic blowpipe would be very helpful, if possible :)
(Yes I am aware that you can right click->check on the blowpipe but it's all about that QoL mane)

**Comment by Hydrox6** [comment] 2019-03-20 13:03
Duplicate of #953

**Comment by PuffBigDoink** [comment] 2019-03-20 13:05
> Duplicate of #953

ty for swift response

**Closed** 2019-03-23 12:57 UTC
