### ISSUE TITLE
Warning for when Overdose are about to expired NMZ (15 sec remaining)

### ISSUE THREAD

**Issue by nmq12** [runelite/runelite#2221] opened 2018-05-01 14:55 UTC
Not sure if possible but this would be a great addition.

**Comment by Roughsketch** [comment] 2018-05-02 04:24
I believe it should be possible to look for the overload damage animation in order to start the timer instead of relying on boosting stats.

**Comment by deathbeam** [comment] 2018-11-27 12:44
Duplicate of #4279

**Closed by deathbeam** 2018-11-27 12:44 UTC
Labels: feature-request
