### ISSUE TITLE
Add "Note" Feature to friends list

### ISSUE THREAD

**Issue by JvckRS** [runelite/runelite#2314] opened 2018-05-03 23:57 UTC
I'm thinking along the lines of a right click option, and it would bring up a box which would allow a person to input a note for a friend. This could be used for remembering people better. OSbuddy has an option like this, and Id love to see it implemented into here. When u hover over the persons name u just created a note for, it would display a cursor-dialogue box.

**Comment by Adam-** [comment] 2018-05-03 23:58
Duplicate of #1877

**Closed by Adam-** 2018-05-03 23:58 UTC
