### ISSUE TITLE
Aerial Fishing Tagged Spot Not Disappearing

### ISSUE THREAD

**Issue by Bignen6** [runelite/runelite#12293] opened 2020-08-05 21:24 UTC
**Describe the bug**
After marking all the fishing spots with the newer feature to mark all, some spots stay marked even when there is no actual fishing spot in the marked position. I have only seen it happen on the west side of molch island. I have noticed three distinct spots that do not disappear.

**To Reproduce**
Go to the west side of molch island and aerial fish for probably around and hour or less and the bug will occur.

**Expected behavior**
The marked spots are expected to disappear when there is no fishing spot there but this does not occur for a few spots. 

**Screenshots**
![Bug 1](https://user-images.githubusercontent.com/69274948/89465309-e5690d00-d73f-11ea-8cb5-fafffd0f663c.PNG)
![Bug 2](https://user-images.githubusercontent.com/69274948/89465465-26f9b800-d740-11ea-8871-73054d6f52a3.PNG)
![Bug 3](https://user-images.githubusercontent.com/69274948/89465589-5b6d7400-d740-11ea-8549-4d958630cbfc.PNG)
These three are the bugged spots that stay on the screen.

**Environment (please complete the following information):**
 - OS: Windows 7
 - RuneLite version: 1.6.23
 - Launcher version: 1.6.0

**Additional context**

**Comment by Nightfirecat** [comment] 2020-08-05 21:29
Duplicate of #7702

**Closed by Nightfirecat** 2020-08-05 21:29 UTC
Labels: duplicate
