### ISSUE TITLE
Possible to add feature that lets us move inventory and chatbox in resizable mode?

### ISSUE THREAD

**Issue by iBrenky** [runelite/runelite#12491] opened 2020-09-13 14:21 UTC
Title pretty much says it all.

I think ive read something about the restrictions of moving the inventory around, but i cant find any posts.
Sorry if this is already answered somewhere.

**Comment by Hydrox6** [comment] 2020-09-13 14:30
Duplicate of #5233

**Closed by Hydrox6** 2020-09-13 14:30 UTC
