### ISSUE TITLE
Time Tracking - Feature to hide any undesired timers

### ISSUE THREAD

**Issue by Waywyrd** [runelite/runelite#14718] opened 2022-02-26 23:25 UTC
Self explanatory, yeah? You have all these different categories(Timers, Stopwatches, Bird Houses) and the point of the plugin is to be able to quickly see what's done. Being able to hide different categories and timers within those categories that you don't intend to use would be useful.

**Comment by Hydrox6** [comment] 2022-02-27 11:06
Duplicate of #3056

**Closed by Hydrox6** 2022-02-27 11:06 UTC
