### ISSUE TITLE
Issues when using GPU Plugin

### ISSUE THREAD

**Issue by thedannn** [runelite/runelite#12143] opened 2020-07-14 16:02 UTC
**Describe the bug**
When using the 'GPU' plugin my client displays the polygons making up the game in a strange way. Some appear normally but many are not visible. 

This affects both player model and structures. Ground seems unaffected.

I have tested this with varying settings and narrowed it down to 'Compute Shaders'.

**To Reproduce**
GPU Plugin
Draw Distance - 60 (doesn't seem to affect issue)
Remove Color Banding - [Y] (doesn't seem to affect issue)
Anti Aliasing - Disabled (doesn't seem to affect issue)
UI Scaling Mode - xBR (doesn't seem to affect issue)
Fog Depth - 0 (doesn't seem to affect issue)
Compute Shaders  - [Y]

**Expected behavior**
Polygons expected to render normally.

**Screenshots**
![runelite](https://user-images.githubusercontent.com/68291355/87448027-324f3d00-c5f3-11ea-93b7-56d23fce2e01.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.21.1
 - Launcher version: 2.1.0

Apols if user (or machine) error. Cannot seem to determine what could be causing this on my end.

**Comment by MESLewis** [comment] 2021-01-13 02:39
Join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.

**Comment by Nightfirecat** [comment] 2022-07-10 04:05
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:05 UTC
Labels: gpu
