### ISSUE TITLE
Customization of sounds to be played when a action/event is completed. I just want Drop it Like it's Hot to play when my inventory is full of fish!

### ISSUE THREAD

**Issue by Entropyed** [runelite/runelite#10208] opened 2019-11-05 19:55 UTC
Can we add an option to add our own notification music for different events?I'm always frustrated that sometimes I might not notice my inventory is full. For example,  if my inventory is full of fish setting it to play Drop it Like it's Hot by Snoop Dogg?

I would like to be able choose an action/condition that what would trigger a predetermined song from a file in .mp3 format.

**Comment by Hydrox6** [comment] 2019-11-05 21:16
Duplicate of #920

**Closed by Hydrox6** 2019-11-05 21:16 UTC
