### ISSUE TITLE
Please make a mobile version

### ISSUE THREAD

**Issue by Big-Al1992** [runelite/runelite#11922] opened 2020-06-18 14:35 UTC
It would be awesome if you guys did a mobile version for the game, obviously it couldn't fit as many plugins but it would still be very helpful, maybe I'm the only one that thinks so as I didn't see anyone else suggest it, but if you made it almost everyone would use it

**Comment by Hydrox6** [comment] 2020-06-18 14:36
Duplicate of #6685

**Closed by Hydrox6** 2020-06-18 14:36 UTC
