### ISSUE TITLE
Addition to Farming Notifications

### ISSUE THREAD

**Issue by Joshwat** [runelite/runelite#13448] opened 2021-04-07 16:10 UTC
**Is your feature request related to a problem? Please describe.**
Currently the farming notifications plugin doesnt have any difference from other notification plugins (such as idle notifier), so it is hard to know what is being notified to you

**Describe the solution you'd like**
Add two optional features to the Farming Notifications plugin:
1 - Add something similar to the Notifications on "RuneLite" plugin so you can get notified in a different way to other notifications
![image](https://user-images.githubusercontent.com/39422750/113897724-8ad9f200-97a1-11eb-90c0-362f7433fb04.png)
2 - Add a notification message to in-game chat, similar to Buckets of Sand/Battlestaves

**Describe alternatives you've considered**
None so far

**Additional context**
Adding those options would make it easier for players to know what is being notified to them, it they're idle (red flashing screen as example) or if their crops grown (light blue flashing screen as example). Also getting a text message would facilitate the players awareness about their farming crops.

**Comment by Nightfirecat** [comment] 2021-04-07 16:30
Notifications can already send chat messages, and adding plugin-specific notification settings is a duplicate of #11679.

**Closed by Nightfirecat** 2021-04-07 16:30 UTC
Labels: duplicate
