### ISSUE TITLE
FPS display and XP drops

### ISSUE THREAD

**Issue by 1337ness** [runelite/runelite#2024] opened 2018-04-27 06:30 UTC
can we please get xp drops that we can place on the screen with speed settings, color, size, etc. and can we also please get a FPS display that we can toggle on and off to see what kind of frame rates we get because the ::displayfps command is in a shit spot and also shows the memory which constantly fluctuates. So please put it in very top right corner above mini map please and thanks. Love everything else about the client though so far.

**Comment by Abextm** [comment] 2018-04-27 06:33
- Don't put multiple issues in 1 issue please
 - FPS plugin is coming. See #1350
 - We will not be adding our own XP drops as the jagex ones are quite configurable. See #1102

**Comment by deathbeam** [comment] 2018-04-27 06:52
Duplicate of #1870 and duplicate of #1102

**Closed by deathbeam** 2018-04-27 06:52 UTC
Labels: feature-request
