### ISSUE TITLE
npc indicators: Indicators aren't updated when NPCs change state

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#12810] opened 2020-11-17 16:40 UTC
I had `Afflicted` highlighted to use up my leftover Serum 208s in Mort'ton but they remained highlighted after they transformed into `Mort'ton Local`s.

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.6.32-SNAPSHOT

**Comment by Hydrox6** [comment] 2020-11-17 16:44
Duplicate of #5161

**Closed by Hydrox6** 2020-11-17 16:44 UTC
