### ISSUE TITLE
Shift click compass to view south (or any direction)

### ISSUE THREAD

**Issue by ShawnVK** [runelite/runelite#13472] opened 2021-04-12 13:13 UTC
**Is your feature request related to a problem? Please describe.**
The compass when you click it, it will point to the north, and when you right-click it has all the options for other directions. East/West is whatever but the south is most important so you can do an instant 180 camera turn easily.

**Describe the solution you'd like**
Add a toggle or something so you can shift-click the compass to make it point to the south (or configurable direction, east/west don't really matter tbh, south is the most useful)
**Describe alternatives you've considered**
An alternative feature could be to do a 180 camera turn from the direction you are currently facing when doing a shift-click on the compass, this would be the most ideal solution but IDK if that's possible hence why I suggested the above. So in this ideal situation let's say I was running while facing southwest and then I shift-click compass to make it face northeast instantly, will be real nice at certain pvm situations and just a QoL improvement IMO for general usage.

**Additional context**
![image](https://user-images.githubusercontent.com/55514944/114399471-f2f85180-9b6e-11eb-9ca7-6d78cbc938a6.png)
This is the compass in case I didn't make it clear^, Make is so when you click this while holding shift, it auto turns 180 degrees or to a configurable direction.

Thank you :)

**Comment by Hydrox6** [comment] 2021-04-12 13:15
Essentially a duplicate of #10731

**Closed by Hydrox6** 2021-04-12 13:15 UTC
