### ISSUE TITLE
Banlist plugin

### ISSUE THREAD

**Issue by Johannes234** [runelite/runelite#11669] opened 2020-05-22 12:19 UTC
add a banlist plugin similar to the one found in openosrs. It gives a notification when someone that has been reported to runewatch/wdr ban list joins your cc.

![image](https://user-images.githubusercontent.com/65769156/82666950-34220300-9c37-11ea-9f20-23afca393d93.png)

**Comment by melkypie** [comment] 2020-05-22 12:21
Duplicate of #3828

**Closed by melkypie** 2020-05-22 12:21 UTC
