### ISSUE TITLE
Wiki option on Right click

### ISSUE THREAD

**Issue by Expression7** [runelite/runelite#7396] opened 2019-01-17 00:10 UTC
It's a hassle when I need to look up the wiki page to a certain quest, item or NPC. I'd like to Right click on something in game and have a "Wiki" option on the drop down menu. Which would open a link to it in your default browser. This could be an optional toggle too.

**Comment by Alexsuperfly** [comment] 2019-01-17 00:11
duplicate of #2551

**Closed by Alexsuperfly** 2019-01-17 00:11 UTC

**Comment by Expression7** [comment] 2019-01-17 00:15
> duplicate of #2551

was #2304 added to runelite? , it looks like it was approved.
