### ISSUE TITLE
Add these for runecrafting!

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#2368] opened 2018-05-05 11:19 UTC
![image](https://user-images.githubusercontent.com/37475765/39662738-807bb592-505e-11e8-9d28-5c506e482b10.png)
add these on the screen please!
add how many charges left on duel rings and binding necklace also add how many actions you made and how much each hour you can make
and add the time to level on the xp orb!

**Comment by permedd** [comment] 2018-05-05 11:30
yeah it does but thats on the jewellery i want it to show it on the scree without me going into my inventory or armour slot

**Comment by deathbeam** [comment] 2018-06-24 23:09
Duplicate of multiple issues

**Closed by deathbeam** 2018-06-24 23:09 UTC
Labels: feature-request
