### ISSUE TITLE
something wrong here

### ISSUE THREAD

**Issue by masrourmouad** [runelite/runelite#7720] opened 2019-02-05 19:16 UTC
![](https://user-images.githubusercontent.com/403487/52213989-e726eb80-2890-11e9-995e-06f1f9295e06.png)

Disabling Hardware Acceleration change nothing

**Comment by Nightfirecat** [comment] 2019-02-05 19:16
Graphical artifacts? Try disabling hardware acceleration: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by deathbeam** [comment] 2019-02-05 19:18
Duplicate of #7703

**Closed by deathbeam** 2019-02-05 19:18 UTC
