### ISSUE TITLE
[Player Indicators] Highlights players incorrectly for a few seconds after a world hop

### ISSUE THREAD

**Issue by 4k53l** [runelite/runelite#12016] opened 2020-06-28 13:06 UTC
Currently when you hop worlds with the Player Indicators plugin turned on it will highlight all players as the "Highlight others" color, for a few seconds, even if some of the players are friends / clan members / teammates, who are supposed to be highlighted with a different color. This is pretty annoying on pk trips and such because you cant tell your teammates apart for a few seconds after a hop. Can someone look into whats causing this and fix it?

I'm guessing maybe it's caused because the friend list / clan member information comes in slower than everything else and so for a few seconds the plugin doesn't know who is who and just highlights everybody as "other". Perhaps a solution could be by "caching" or saving the players friend list / clan member list before a world hop and then using that until the real friend list / clan list loads

**Comment by Nightfirecat** [comment] 2020-06-28 18:37
Duplicate of #1682

**Closed by Nightfirecat** 2020-06-28 18:37 UTC
Labels: duplicate
