### ISSUE TITLE
Right click menu on a friend in chatbox

### ISSUE THREAD

**Issue by forsco** [runelite/runelite#2086] opened 2018-04-28 06:48 UTC
Whilst right clicking on another players name in the chatbox that is currently on your friendslist still shows 'Add friend playername' in the right click menu instead of "Message playername".

**Comment by deathbeam** [comment] 2018-04-28 11:28
Is this vanilla bug or is this caused by RuneLite?

**Comment by forsco** [comment] 2018-04-28 11:31
> Is this vanilla bug or is this caused by RuneLite?

To the best of my knowledge this only happens in Runelite.

**Comment by Nightfirecat** [comment] 2018-10-02 04:15
I can't reproduce this, I'm seeing identical behavior on official client and Runelite. (with the exception of the added "Lookup" option)

**Comment by deathbeam** [comment] 2018-10-19 12:09
Looks like this is jagex bug then, closing

**Closed by deathbeam** 2018-10-19 12:09 UTC
Labels: bug
