### ISSUE TITLE
In client Idle Notification rather than Windows Notification

### ISSUE THREAD

**Issue by JWalty** [runelite/runelite#2076] opened 2018-04-28 03:14 UTC
I love the idle notifier but the windows notification sound is loud, obnoxious, and blocks the bottom right of my screen. Would be really cool if we could have some sort of sound come from the client itself that way I know when I'm going to logout without being bothered by the windows notifications all the time

**Comment by Juzzed** [comment] 2018-04-28 11:11
As a workaround you can change the Notification sound in Sound menu. https://www.groovypost.com/howto/turn-off-change-windows-10-notification-sounds/

Also Duplicate #1884

**Comment by deathbeam** [comment] 2018-04-28 11:25
Duplicate of #1884

**Closed by deathbeam** 2018-04-28 11:25 UTC
