### ISSUE TITLE
Amount on ground items is incorrect with multiple stacks of the same item

### ISSUE THREAD

**Issue by Nachtmerrie** [runelite/runelite#4784] opened 2018-08-08 18:28 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When there are multiple stacks of the same item on the ground, the rightclick menu will show the amount of the first stack on both stacks

**To Reproduce**
Shoot arrows at evil monsters, don't pick them up
Keep shooting for over a minute. Over 30 arrows will be on the ground. 
This makes a second stack appear and tadaaa

**Expected behavior**

**Screenshots**
Both stacks show 3 iron arrows
![image](https://user-images.githubusercontent.com/10828507/43856503-fe089ea0-9b48-11e8-8e62-6ac5e83ea9fe.png)
Top stack is 3 arrows:
![image](https://user-images.githubusercontent.com/10828507/43856516-073203ae-9b49-11e8-86bc-02526dbc011d.png)
bottom stack is actually 29 arrows
![image](https://user-images.githubusercontent.com/10828507/43856535-1366bcd2-9b49-11e8-8e90-87e957a474a8.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.11
 - Launcher version: 1.5.1

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Adam-** [comment] 2018-08-08 18:34
Duplicate of #1220

**Comment by Nachtmerrie** [comment] 2018-08-08 18:35
My apologies, I really did use the search function.

**Closed** 2018-08-08 18:35 UTC
