### ISSUE TITLE
Runelite will not update

### ISSUE THREAD

**Issue by KingCraftyxix** [runelite/runelite#13672] opened 2021-05-31 17:45 UTC
**Describe the bug**
Runelite will not update

**To Reproduce**
1. Go to Runeelite
2. Click on Login
3. Scroll down to The bottom

**Expected behavior**
All plugins and functions are available

**Screenshots**
![image](https://user-images.githubusercontent.com/85128698/120227013-5ff6a200-c216-11eb-8ebe-a18c64c037b7.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows10
 - RuneLite version: [e.g 1.4.67]

**Comment by Hydrox6** [comment] 2021-05-31 17:46
Duplicate of #13671

**Closed by Hydrox6** 2021-05-31 17:46 UTC
