### ISSUE TITLE
Loot Tracker Filtering

### ISSUE THREAD

**Issue by RLsuggestions** [runelite/runelite#14016] opened 2021-08-12 15:26 UTC
The expanded view of the Loot Tracker has limited use because you can really only scroll so far. It becomes especially bad when you want to see a monsters loot in order when you killed other monsters in between.

I would like a function where, for example, I can type "Elite Clue" and only that item in the expanded view so I can see when the last time I received a master clue.

**Comment by Hydrox6** [comment] 2021-08-12 15:26
Duplicate of #10704

**Closed by Hydrox6** 2021-08-12 15:26 UTC
