### ISSUE TITLE
Ground items messed up since recent chance 

### ISSUE THREAD

**Issue by HuughesRS** [runelite/runelite#17843] opened 2024-05-14 18:01 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

You changed it so ground items are always showing now, please can you re add the feature to "only show loot" this is so annoying seeing everything on the floor.

### RuneLite version

1.10.29
2.7.1

**Comment by Nightfirecat** [comment] 2024-05-14 18:07
Duplicate of #17834

**Closed by Nightfirecat** 2024-05-14 18:07 UTC
Labels: duplicate
