### ISSUE TITLE
Filter quests for which you meet the requirements

### ISSUE THREAD

**Issue by Brcrwilliams** [runelite/runelite#12121] opened 2020-07-12 15:33 UTC
**Is your feature request related to a problem? Please describe.**
I would like to complete all of the quests for which I already meet the requirements. Finding which quests I can do involves looking up each quest on  the wiki and tediously cross-checking with my skill levels. 

**Describe the solution you'd like**
I would like to be able to filter the quest list in Runelite to show the quests which I have not completed *and* for which I have all of the requirements. 

**Describe alternatives you've considered**
No better solution comes to mind.

**Additional context**
This was previously requested in #5779 and #6466 which where closed of duplicates of #1905. #1905 added filters for the quest list, but only based on quest status, not whether the requirements are met.

**Comment by melkypie** [comment] 2020-07-12 15:38
Duplicate of #10475

**Closed by melkypie** 2020-07-12 15:38 UTC
