### ISSUE TITLE
Slayer highlight interferes with tag npc highlights, all styles

### ISSUE THREAD

**Issue by JaredEzz** [runelite/runelite#16949] opened 2023-08-21 15:29 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

If a current npc is the target of the slayer task and any of the highlight options are true (I found this on "highlight tile"), then using the "Tag [NPC]" option from the right click menu does nothing. Only by disabling and re-enabling the Slayer plugin is the expected behavior reached, where the single NPC is tagged with the desired individual tag style and the rest of the slayer-targeted NPCs are highlighted with the slayer style.

### Screenshots or videos

<img width="156" alt="image" src="https://github.com/runelite/runelite/assets/13698465/82153796-dffd-4658-a912-716bfb463145">
this is the desired result, but is only achievable after tagging the NPC while the Slayer plugin is disabled, and then re-enabling the Slayer plugin

### RuneLite version

Runelite version: 1.10.10.2
Launcher version: 2.6.2

**Comment by Alexsuperfly** [comment] 2023-08-21 15:36
duplicate of #16134

**Closed** 2023-08-21 15:37 UTC
Labels: duplicate
