### ISSUE TITLE
[Request] Notification on item drop

### ISSUE THREAD

**Issue by Azderi** [runelite/runelite#3964] opened 2018-06-23 02:07 UTC
Notifications when a certain tier (low, medium, high or insane value) item drops from a monster. Would save the hassle of using another piece of software to detect certain colors when runescape is on my secondary monitor for example.

**Comment by deathbeam** [comment] 2018-06-23 02:09
Duplicate of #3643

**Closed by deathbeam** 2018-06-23 02:09 UTC
