### ISSUE TITLE
Supplies tracker

### ISSUE THREAD

**Issue by Cootin17** [runelite/runelite#10070] opened 2019-10-15 11:16 UTC
Works like a loot tracker, except it tracks all supplies you use so you know exactly how much you spend in supplies on your trips. Have the tracker keep track of how much food you consume, pots you sip, arrows/darts you use ect. Maybe even able to keep track of things like how many zulrah scales your blowpipe and serp helm have used

**Comment by Hydrox6** [comment] 2019-10-15 11:21
Duplicate of #6700

**Closed by Hydrox6** 2019-10-15 11:21 UTC
