### ISSUE TITLE
Low Detail toggle in various areas

### ISSUE THREAD

**Issue by FoxyToaster** [runelite/runelite#11506] opened 2020-05-08 11:32 UTC
**Is your feature request related to a problem? Please describe.**
Yes it is. It would be nice to be able to use low detail mode all the time and have it disabled in areas where it doesn't play/look nice. Agility rooftops and Bloat's room in Theatre of Blood immediately come to mind.

**Describe the solution you'd like**
I would love to have a toggle for low detail mode to have it disabled in Bloat's room in Theatre of Blood, during Rooftop agility, etc.

**Describe alternatives you've considered**
It's super simple to disable low detail mode when doing various activities but it would be nice to not have to. 

**Additional context**
N/A

**Comment by Nightfirecat** [comment] 2020-05-08 21:40
Duplicate of #1481

**Closed by Nightfirecat** 2020-05-08 21:40 UTC
Labels: duplicate
