### ISSUE TITLE
Modify the herb patch timer to enable toggling patches on/off

### ISSUE THREAD

**Issue by fairyfoam48** [runelite/runelite#5368] opened 2018-09-07 11:18 UTC
For growing herb patches most players do not use the harmony patch. A helpful feature would be to hide this patch from the herb patch timer interface. This could be done with a setting interface that lets the user toggle which patches are displayed on the herb patch timer interface. 

![image](https://user-images.githubusercontent.com/43065852/45216335-4be71580-b2f4-11e8-9f51-526ddec93c05.png)

**Comment by deathbeam** [comment] 2018-09-07 12:41
We can just push the harmony patch to bottom instead of adding "toggles"  for individual patches you dont like

**Comment by oplosthee** [comment] 2018-09-07 13:06
I don't know whether that's a good fix. I personally don't use the Kourend patch, would you also push the Kourend patch to the bottom? What if I do use the Harmony patch and not the Kourend patch?

Adding toggles for every patch (trees, herbs, flowers, ..) in the settings would probably result in a lot of clutter, but perhaps we could have some kind of "edit mode" in the timers plugin where you can disable timers you would not like to see?

![](https://i.imgur.com/BcS9YTp.png)

I personally think this is really not an issue though, but perhaps someone can add it if they really want to.

**Comment by deathbeam** [comment] 2018-09-07 13:07
I would do compromise and just push the really common ones at top, e.g mostly the no req ones, and then push the ones with reqs lower as less people use it (what is also the kourend one)

**Comment by ShaunDreclin** [comment] 2018-09-07 17:39
What about automatically detecting if the patch is unlocked or not?

Could check My arm's big adventure, Making friends with my arm, Morytania elite diary, Kourend favour

**Comment by fairyfoam48** [comment] 2018-09-07 19:36
Well an edit mode would be the cleanest option. ShaunDreclins suggestion would also work very well; and in fact would require no user input and on top of that it would automatically update for each account on login.

**Comment by deathbeam** [comment] 2018-09-07 19:37
Yeah i like @ShaunDreclin 's suggestion a lot

**Comment by sirlaige** [comment] 2018-09-07 22:15
hmm if I may weigh in on this... I would like to have the disease free patches able to be listed next to eachother.  Kourend, Harmony, Troll stronghold, and the new Weiss.  Also REALLY you don't use Kourend oplosthee?  

But really ye this isn't actualy needed.  Perhaps we could have some way to show that this patch doesn't get infected.  Perhaps the herb icons could have an outline or back drop to high light is as different.  and then same outline/ backdrop for the other un-infectable patches in Kourend.

**Comment by ShaunDreclin** [comment] 2018-09-07 22:15
Well the kourend one is only disease free after a certain amount of hosidius favour iirc

**Comment by johnhamilto** [comment] 2018-09-07 22:38
What about dynamically moving all patches that have weeds in them/or are empty to the bottom of the list (and/or greying them out)?  This way, all patches would show in the list, but people who don't use certain patches would not have them in the middle of the patches they do use often.

**Comment by fairyfoam48** [comment] 2018-09-07 23:42
@sirlaige Perhaps they coud be listed at the top or have some kind of indication that they're disease free. I'm using ranarr and snapdagon seeds only in the disease free patches. 

The kourend patch is disease free with 75% favour but you may as well get the 100% and lock it in, takes less than 1 hour. 

@johnhamilto That's a really good idea. Eventually the patches you don't use will move to the bottom.

I agree that it isn't actually needed, it's more of an OCD thing for me and it's a quality of life update rather than something that will have a dramatic change in game play, but at this point most players are farming herbs and with the addition of the extra herb patch it'd be nice to tidy up the interface in some way.


Thanks everyone for the suggestions, all of these are really good ideas.

**Comment by fairyfoam48** [comment] 2018-09-07 23:45
@ShaunDreclin 's suggestion seems like a logical option because it would be all automatic and would also clean up the interface without having any user input.

**Comment by sirlaige** [comment] 2018-09-08 00:49
Shaun I didn't realize Kourend wasn't always disease free.  I looked it up and you are right it is only free after 50% H-favor.  

I do not yet have Harmony unlocked so I looked up that one as well.  You get it in the elite Mortania diary but it doesn't say it is disease free =( I may have been mistaken about that one as well, sorry.

**Comment by fairyfoam48** [comment] 2018-09-08 01:13
Ohh yes it's actually 50% hosidius  favour. and yes it turns out the harmony one isn't disease free which seems odd given the requirements for using it :\.

**Comment by sirlaige** [comment] 2018-09-08 02:07
![herb capture-example](https://user-images.githubusercontent.com/34697730/45249158-f48b7a00-b2e0-11e8-8324-a89975c19793.PNG)


This is an example of what I would think an icon outline (Kourend) and icon background (Troll) that could show that these patches wont get disease. I think I like the outline the bast.   

Other things that will never get disease are poison ivy, the falador tree patch (diary), grapes, and then also allotments that have the correct flower grown it protects them.    Example of the allotments would be watermelons won't die if nostrums are full grown in the flower patch nearby.  

Good Tip is that with these flowers you do not even need to water the allotment(wish I knew that when I started).

**Comment by raiyni** [comment] 2018-09-08 02:11
I think that is unnecessary because why do you need to know if they never disease if you already know that?

**Comment by Alexsuperfly** [comment] 2018-09-08 02:34
Compost does more than reduce disease rates, it also increases yield.  
If you're going to be farming in any capacity you'll know what patches are protected so there's no reason to clutter the UI with information that becomes obsolete.

**Comment by sirlaige** [comment] 2018-09-08 02:45
Alex doesn't have the increased yield on all plants and as for the your farming method it depends on the player.  Like iron men, and then too those that worry about $-xp ratio.  Compost add up fast mitigating loss of coin is valuable.

**Comment by raiyni** [comment] 2018-09-08 02:45
I don't know what that means.

**Comment by Alexsuperfly** [comment] 2018-09-08 02:51
any plant with a variable yield will be affected by the additional lives given by adding compost.  Its the individuals decision whether to use compost or not, so let that individual make that choice on their own don't force your decision on everyone that uses the client.

**Comment by sirlaige** [comment] 2018-09-08 03:26
I'm not sure what you mean, who would be forced to do what?  Yes everyone has a choice on their farming methods.  You have your way and this wouldn't be helpful to you, You think this useless, but there are more than just your farming method.  I believe it is useful for my method and others methods.  Does this even need to be said?  I'm only saying this for that fact I don't understand what you mean by forcing people/ or taking away choices, not to attack you.  

Now as for the compost, we don't think the same on compost.  I don't want to have a war over when it is and isn't good to use.  There has been some farming changes recently that changed the usefulness of compost, but then compost isn't the topic of this thread anyways.  

Fairy christened one response with OCD and I too share his enthusiasm.  His suggestion of being able to reorder the patches would aid me as I would reorder them put the disease free patches together and suggest an alternate way of show these safe patch. Thus taking away my need to reorder them.

**Comment by raiyni** [comment] 2018-09-08 03:30
So you want this because of OCD? Gotcha.

**Comment by sirlaige** [comment] 2018-09-08 03:32
You read all that and all you got out of it was OCD?  LOL why are you here?

**Comment by Abextm** [comment] 2018-09-08 03:33
IMO we should:
 - Push patches containing weeds to the bottom
 - Grey out patches that the player hasn't unlocked

To do this we would need to add tracking for the varbits related to diarys/quests, similar to autoweed.

Discussion about a diseased indicator should go in a separate issue.

**Comment by sirlaige** [comment] 2018-09-08 03:35
There Abextm is on topic.

**Comment by deathbeam** [comment] 2018-09-08 11:12
I would probably not push patches with weeds at bottom as that means the interface would be reordered quite often, can be confusing.

**Comment by deathbeam** [comment] 2019-01-28 20:43
Duplicate of #3056

**Closed by deathbeam** 2019-01-28 20:43 UTC
Labels: discussion, feature-request
