### ISSUE TITLE
Possible aerial fishing glitch?

### ISSUE THREAD

**Issue by derpyderpaderp** [runelite/runelite#9356] opened 2019-07-12 22:22 UTC
Seems to be exclusively on the west side of the island in aerial fishing where you get glitched fishing spots that aren't even there. I have had no issues in the north area, southern area, or eastern area, just the west. I would usually not report something like this but it seems to be in 1 area so figured it might be a bug. If this is not a but feel free to send this to invalid.

To reproduce it just fish on the western side and it will show fishing spots that aren't even there.

I could not screen shot them because they come and go faster than my screen shot tool can start.

Operating system: Windows 10
 - RuneLite version: 1.5.28
 - Launcher version: 1.6.0

**Comment by Alexsuperfly** [comment] 2019-07-12 22:27
duplicate of #7702

**Closed** 2019-07-12 23:08 UTC
Labels: duplicate
