### ISSUE TITLE
where is the anti drag config toggle?

### ISSUE THREAD

**Issue by bowplox** [runelite/runelite#3269] opened 2018-05-25 00:35 UTC
![screenshot_3](https://user-images.githubusercontent.com/39606562/40520127-4282ab90-5fc4-11e8-81ad-bd18a918f120.png)
where did this toggle option go?

**Comment by Nightfirecat** [comment] 2018-05-25 00:37
Removed in #3073.

**Comment by Infinitay** [comment] 2018-05-25 00:38
As we said in discord when you asked, it got removed. You now **have** to hold shift, there is no more toggle. See #3200 for discussion.

**Comment by bowplox** [comment] 2018-05-25 00:40
so now I have to turn off shift click dropping :'(

**Comment by Kamielvf** [comment] 2018-05-25 00:41
You can set shift-click configs for items: https://puu.sh/zVEcD/aff42db5c7.gif

**Comment by bowplox** [comment] 2018-05-25 00:43
where do I do that

**Comment by deathbeam** [comment] 2018-05-25 05:51
Duplicate of #3200

**Closed by deathbeam** 2018-05-25 05:51 UTC
