### ISSUE TITLE
Add Kingdom favor and Tears of Guthix tracking

### ISSUE THREAD

**Issue by Brianmm94** [runelite/runelite#9987] opened 2019-10-05 23:08 UTC
I think kingdom favor percentage and whether or not you can do Tears of Guthix should be added to the "Time Tracking" configuration so that you can easily reference them at any time. 

Another option would be to display each of them on the "Daily Task Indicator" configuration seeing as they both only change on a daily basis (but then you'd have to switch worlds or log out and in to check them). 

Currently, we have the "Kingdom of Miscellania" configuration which shows your favor while you're on Miscellania, but I hate having to travel to Miscellania to know what my percentage is. As for Tears of Guthix, I'm not sure if there's anything other than your quest guide that keeps track of this for you, which is a pain because you have to change to the quest tab, switch to quests if you're on another sub-tab like diaries, and then scroll through your quests to find Tears of Guthix every time you want to check whether or not you can do it.

**Comment by Hydrox6** [comment] 2019-10-05 23:30
You can talk to Juna to get notifications of when you can do Tears of Guthix.
Kingdom favour is a duplicate of #4760

**Closed by Hydrox6** 2019-10-05 23:30 UTC
Labels: duplicate, feature-request
