### ISSUE TITLE
Motherload Mine Log-In Bug.

### ISSUE THREAD

**Issue by Hogw** [runelite/runelite#5700] opened 2018-09-29 02:05 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I've had this happen a few months ago and it only happens when I'm at motherload mine, Basically I log out of mlm, I think it may have to do with me having ores in the bag possibly and logging out but I'm not completely sure. When I go to log in though, it completely exits out of the client, the only way to fix is, is to go on the vanilla client and move the account.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
2018-09-28 21:43:43 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2018-09-28 21:43:50 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-09-28 21:43:56 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-09-28 21:44:08 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 32196ms. Uptime: 61467ms
2018-09-28 21:48:17 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2018-09-28 21:48:19 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-09-28 21:48:28 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-09-28 21:48:37 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 26353ms. Uptime: 34660ms

**Comment by deathbeam** [comment] 2018-09-29 06:16
Duplicate of #5675

**Closed by deathbeam** 2018-09-29 06:16 UTC
