### ISSUE TITLE
When filter applied to stats calculator and skill button is clicked, keep filter applied

### ISSUE THREAD

**Issue by ijustlovemath** [runelite/runelite#6667] opened 2018-11-24 19:25 UTC
## Overview

When skilling, you can see how many actions to the next level by clicking the calculator icon, then a skill icon. From within a skill icon's menu, you can filter the actions you can do by searching, eg "alch" in the Magic calculator. This number does not update live, so to update it, you click the same skill icon again. This keeps the filter text, but removes the actual filtering, so all the items come back into the list of actions. You have to click the filter text and hit enter to reapply the filter. I believe this is a bug

## Version information

- RuneLite version 1.5.1
- OSRS Rev177
- Windows 10 Version 1803 (Build 17134.407)
- Java 8 Update 131

## Location

I don't exactly know where the filter events happen, but it seems to be related to here: https://github.com/runelite/runelite/tree/master/runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator

Specifically this commit: https://github.com/runelite/runelite/commit/8d8c8e475421e8528c32d6ac8fd6451372999f6d

**Comment by SirGirion** [comment] 2018-11-25 04:53
Will take this bug, suppose we would need to agree on the expected behavior; i.e. when clicking on the skill icon, should the filters stay or should they be cleared because right now it seems like its intended for them to be cleared.

**Comment by ijustlovemath** [comment] 2018-11-25 05:18
I would say it's more convenient (and hence probably expected) that the filter *doesn't* clear, if that's not too much more work.

Unfamiliar with y'all's architecture (and Java in general), but happy to help with the PR if you want it!

**Comment by ThimbleFire** [comment] 2019-04-13 21:20
I know this discussion has been closed for some time but I'd really like to see this change.

**Comment by Hydrox6** [comment] 2021-10-01 09:36
This is essentially the same request as #10445, and as such was fixed when #10895 was merged to close that issue

**Closed by Hydrox6** 2021-10-01 09:36 UTC
Labels: feature-request, skill-calc
