### ISSUE TITLE
Possibly add some kinda enhanced ge price tracker?

### ISSUE THREAD

**Issue by ShwekBoii** [runelite/runelite#6162] opened 2018-10-24 13:46 UTC
Now that Runelite clearly has become the most used osrs client, I believe it wouldn't hurt that Runelite implements its own ge price tracker as the osbuddy one probably becomes more and more inaccurate.
Just a thought, idk if the devs actually wanna spend any time in this.

**Comment by deathbeam** [comment] 2018-10-24 14:15
Duplicate of #4377

**Closed by deathbeam** 2018-10-24 14:15 UTC
