### ISSUE TITLE
Show/Hide Map Instance by default

### ISSUE THREAD

**Issue by Learthy** [runelite/runelite#4405] opened 2018-07-19 14:09 UTC
I mostly use this during Raids 1, since the layout interface disappears once raid starts (which is a different issue), I have to keep opening the map to check what room is next. Currently, to do this I have to right click the map icon and choose "show", and then "hide" the same way. 

Could it be possible to be able to reorder those so that we left clicking the map icon would choose "show/hide map instance" by default?

Cheers.

**Comment by deathbeam** [comment] 2018-07-19 14:11
Duplicate of #2324

**Closed by deathbeam** 2018-07-19 14:11 UTC
