### ISSUE TITLE
Cannot type into client macOS

### ISSUE THREAD

**Issue by jpseeley** [runelite/runelite#8701] opened 2019-05-01 13:21 UTC
**Describe the bug**
I cannot type into the client after holding down a key for a few seconds.
Running macOS Majave 10.14.4

**To Reproduce**
To reproduce:
1. Hold down any key on keyboard for 1-2 seconds
2. Keyboard no longer allows typing into Runelite or OSRS

Keyboard still works on every other application

**Expected behavior**
Holding down key should not break the keyboard.

**Environment (please complete the following information):**
Running macOS Majave 10.14.4

**Additional context**
This does not seem to be same as #2442 and that issue is closed anyway.

**Comment by AlexanderVansp** [comment] 2019-07-29 12:55
This is due to Mojave having an accent menu pop-up by default (to type ë, é, ...).
The client does not know how to handle this.
A solution is to disable the character accent menu and enable auto-repeat, type the following at the command prompt: "defaults write -g ApplePressAndHoldEnabled -bool false"

**Comment by Zirro** [comment] 2019-08-12 14:42
Duplicate of #3514.

**Closed** 2019-08-12 15:26 UTC
Labels: needs-information
