### ISSUE TITLE
Add an indication to see whether farm patches are being looked after by a farmer

### ISSUE THREAD

**Issue by yongzhong99** [runelite/runelite#6148] opened 2018-10-23 19:36 UTC
Sometimes I'd like to know what patches I have paid the farmer to take care of, adding a little indication to show whether patches are being cared for or not would be nice.

A solution for this could be a tick or a cross in the farming tab to show if patches are being taken cared of or not.

**Comment by deathbeam** [comment] 2018-10-23 19:42
Duplicate of #2472

**Closed by deathbeam** 2018-10-23 19:42 UTC
