### ISSUE TITLE
Login buttons per account on client

### ISSUE THREAD

**Issue by jwiliker** [runelite/runelite#8834] opened 2019-05-14 18:42 UTC
A great time saver for people who use several accounts.  1 button login anywhere on the client for several accounts.  This should allow you to login by automatically typing your username password and hitting the login button for you.  The buttons could display your IGN or your characters head and last gear that was equipped in the head slot.

**Comment by Nightfirecat** [comment] 2019-05-14 18:55
Duplicate of #641.

**Closed by Nightfirecat** 2019-05-14 18:55 UTC
