### ISSUE TITLE
Better sorted farming timer

### ISSUE THREAD

**Issue by Overfly97** [runelite/runelite#7613] opened 2019-01-29 09:46 UTC
Currently, the timers are grouped in a confusing manor.  When doing a tree run for example, it will show there is still time before it has finished, when your really only waiting for your hardwood trees, the rest are finished.

If we could have further organization, such as [trees, herbs, allotments, bushes, fruit trees, calquat, hardwood, spirit trees, cactus] and however else is seen fit, it would be easier to look at and see what you need to do.

**Comment by NathenSample** [comment] 2019-01-29 10:43
This ticket should probably be entitled "More granular farming groupings" or "Custom farming groups" rather than simply "better"

**Comment by deathbeam** [comment] 2019-01-29 10:44
Duplicate of #3056

**Comment by deathbeam** [comment] 2019-01-29 10:44
No need for titles when its invalid :d

**Closed by deathbeam** 2019-01-29 10:44 UTC

**Comment by Overfly97** [comment] 2019-01-29 10:46
Sorry for dupe, I never thought of just custom ones so I never looked for them
