### ISSUE TITLE
Hot Keys

### ISSUE THREAD

**Issue by MrINTJ** [runelite/runelite#6529] opened 2018-11-17 06:05 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

No, my feature is not related to any "problem." It is a quality of life update to RuneLite.

**Describe the solution you'd like**

I discovered today that RuneLite has a "WASD Camera" feature. This makes the game feel extremely smooth for me. In every other game I play on PC, my hand usually rests on the WASD, for years using the arrows made the game extremely awkward. I want to take this a step further. I'd like for the Function keys (F1-F12) to be remapped to the 1 through 0 keys. This would bring the runescape controls on the keyboard much closer together and provide an extremely smooth experience when PvMing or PvPing.

**Additional context**

**Comment by raiyni** [comment] 2018-11-17 07:33
use ahk

**Comment by deathbeam** [comment] 2018-11-18 11:19
Duplicate of #5070

**Closed by deathbeam** 2018-11-18 11:19 UTC
