### ISSUE TITLE
Expenses tracker

### ISSUE THREAD

**Issue by badjass** [runelite/runelite#9504] opened 2019-07-29 15:40 UTC
So, the loot tracker is an amazing and useful feature in runelite. I use it a lot to calculate the profits of my slayer/bossing.
But i think there is one aspect missing. Some bosses/tasks require a lot of supplies which makes it difficult to know the real profit. That's why i suggest a runelite feature that, along with your loot, tracks your expenses. For example, it would calculate the costs of Arrows/bolts, potions, food, runes etc.. consumed.
Any feedback is appreciated.

**Comment by Alexsuperfly** [comment] 2019-07-29 15:41
duplicate of #6700

**Closed** 2019-07-29 15:43 UTC
Labels: duplicate
