### ISSUE TITLE
Screen Marker Groups

### ISSUE THREAD

**Issue by keywok** [runelite/runelite#13112] opened 2021-01-25 22:19 UTC
**Is your feature request related to a problem? Please describe.**
Extended functionality to the Screen Marker's plugin.

**Describe the solution you'd like**
Allow for screen markers to be added to a group and the group to be toggled for visability.

**Describe alternatives you've considered**
Not really sure

**Additional context**
Anything along these lines to turn on multiple screen markers at once would be amazing!

**Comment by raiyni** [comment] 2021-01-25 22:34
Duplicate of https://github.com/runelite/runelite/issues/3205

**Closed by raiyni** 2021-01-25 22:34 UTC
