### ISSUE TITLE
Different flash colors for idle notifier

### ISSUE THREAD

**Issue by Jonotaku** [runelite/runelite#14365] opened 2021-11-12 04:02 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
-Kind of annoying when you get a red flash but your not sure what it is for. It could be for prayer, hp or whatever. 

**Describe the solution you'd like**
-To be able to customise the color for specific thresholds in Idle Notifier.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
for example
Prayer Pot Threshold flash could be the same color as the pot itself.
Keep the red flash for HP
Idle could be grey
Would be nice to have a threshold for when anti poison resistance is about to wear out and a green color for the flash

Its just a pretty cool QoL feature.
Removes the stress on what you actually got notified on like low HP or low prayer. With this QoL feature you would know exactly what the flash meant by color 

Happy days.

**Comment by Nightfirecat** [comment] 2021-11-12 04:26
Duplicate of  #11679

**Closed by Nightfirecat** 2021-11-12 04:26 UTC
Labels: duplicate
