### ISSUE TITLE
Let us change the skybox color.

### ISSUE THREAD

**Issue by randomChair** [runelite/runelite#9774] opened 2019-08-29 17:38 UTC
Please make it so we can change the skybox color... current cyan is way too vibrant.

**Comment by derpyderpaderp** [comment] 2019-08-30 01:29
I agree, It should be a bit darker or let us choose the color.

**Comment by Alexsuperfly** [comment] 2019-08-30 01:36
duplicate of #7481

**Closed** 2019-08-30 01:36 UTC
Labels: duplicate
