### ISSUE TITLE
'Sleek Status Bars'

### ISSUE THREAD

**Issue by gitzombify** [runelite/runelite#13928] opened 2021-07-23 01:24 UTC
This is just a design I think would make status bars look sleek for players using modern style runescape interface. Currently using status bars with the bottom menu 'compact' leads to one hanging way off the side. I thought maybe a sleek/slim style status bars would fit in this area perfectly given the inventory size.

Goes without saying, i don't think numbers/icons would be displayable in this iteration of style due to the visual-size restraint.
Concept below.
![sleek](https://user-images.githubusercontent.com/84211618/126727596-105227cd-682b-4c41-be71-b9cadfb0aef5.png)

**Comment by Nightfirecat** [comment] 2021-07-23 01:29
This is mostly a duplicate of #13928

**Closed by Nightfirecat** 2021-07-23 01:29 UTC
Labels: duplicate
