### ISSUE TITLE
League Skill Calculator

### ISSUE THREAD

**Issue by Hagerdy** [runelite/runelite#12903] opened 2020-12-09 14:01 UTC
I believe that we could benefit from having the ability to toggle options on the skill xp calculator to account for our boosted xp rates during league. Obviously the math is not difficult for us; we just take whatever the rate is in the calculator and divide/multiply by whatever our current boost is, but it would be a nice quality of life implementation for folks during the leagues. 

Thank You!

**Comment by Hydrox6** [comment] 2020-12-09 14:12
Duplicate of #3027
fwiw, osleague.tools has a calculator for league rates if you want to use one right now

**Closed by Hydrox6** 2020-12-09 14:12 UTC
