### ISSUE TITLE
Screen Resizing Issue When Closing Side Panel

### ISSUE THREAD

**Issue by csh1357** [runelite/runelite#16206] opened 2023-01-24 17:03 UTC
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

MacOS Ventura 13.1

### Bug description

When collapsing the side panel on the right while in fullscreen mode, the screen doesn't resize properly and leaves black space on the left of the screen. Video attached.

### Screenshots or videos

https://user-images.githubusercontent.com/104097714/214358202-60f2861a-cd79-4a08-b61d-1fe04ed766f5.mov

### RuneLite version

Runelite Version 1.9.8
Launcher Version 2.5.0

**Comment by Adam-** [comment] 2023-01-24 17:05
duplicate of #13303

**Closed by Adam-** 2023-01-24 17:05 UTC
Labels: needs-triage
