### ISSUE TITLE
Sidebar Plugin Rearrange

### ISSUE THREAD

**Issue by ShawnVK** [runelite/runelite#12322] opened 2020-08-10 12:11 UTC
Let us re-arrange the side bar plugins. It would be great to order them according to how the user wants, than how it is ordered default currently.
![image](https://user-images.githubusercontent.com/55514944/89781279-084d4580-dae1-11ea-97de-9a249a90df47.png)

**Comment by Hydrox6** [comment] 2020-08-10 12:13
Duplicate of #783

**Closed by Hydrox6** 2020-08-10 12:13 UTC
