### ISSUE TITLE
Galvek waves not showing on screen

### ISSUE THREAD

**Issue by greenbstud** [runelite/runelite#14093] opened 2021-09-03 14:54 UTC
I am having an issue with Runelite where it wont even show the waves that galvek uses on wave 3.
I  also had an issue when doing the Lair of Tarn Razorlor where it would not showing the moving trap actually moving.

I thought this might be down to having GPU on but no difference when i turned it off, entity hider is not on.

any ideas what might be causing this issue?

**Comment by Nightfirecat** [comment] 2021-09-14 06:24
I've never heard of either of these issues happening before. Can you upload your `client.log` file? Instructions to find it [are available on our troubleshooting wiki page](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client).

**Comment by Nightfirecat** [comment] 2022-07-10 05:07
Since this issue has not bee reproduceable and has not been updated in some time, I am closing it.

**Closed by Nightfirecat** 2022-07-10 05:07 UTC
Labels: needs-information
