### ISSUE TITLE
New elite clue cryptic "Has no one told you it is rude to ask a lady her age?" currently states lady traharn in Priff when the correct person is Mawrth in letya

### ISSUE THREAD

**Issue by kylesquad** [runelite/runelite#9759] opened 2019-08-28 17:20 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Hydrox6** [comment] 2019-08-28 17:30
Fixed in https://github.com/runelite/runelite/commit/b87e50e43b9bb4b10342d4ec1a96833e2b9f4109

**Comment by Nightfirecat** [comment] 2019-08-28 17:30
Also, duplicate of  #9459, #9700, and #9729

**Closed by Hydrox6** 2019-08-28 17:30 UTC
