### ISSUE TITLE
NMZ Point Overlay (How much each Boss gives)

### ISSUE THREAD

**Issue by Iveljetorox** [runelite/runelite#4506] opened 2018-07-26 12:37 UTC
**Is your feature request related to a problem? Please describe.**
It would be good to know which bosses are better over other for points, so you know which ones are better to prioritise during a dream since choosing all quest bosses at once with dharoks is the most efficient for points

**Describe the solution you'd like**
Appearing above the quest boss in Nightmare Zone would be the amount of points you would receieve in Hard Mode Rumble mode, either as a seperate little toolbox or at the end of the bosses name

**Describe alternatives you've considered**
Not really any alternative to this, besides checking the wiki yourself and memorising the points

**Comment by deathbeam** [comment] 2018-07-27 06:11
Duplicate of #2682

**Closed by deathbeam** 2018-07-27 06:11 UTC
