### ISSUE TITLE
minimize bug on second monitor

### ISSUE THREAD

**Issue by aloranetwork** [runelite/runelite#15672] opened 2022-09-14 06:15 UTC
### Type

Incorrect behavior

### OS Version

Windows 10

### Bug description

Every time I try to maxmize the client from the second monitor it goes back to my main monitor not even takin the whole screen that it usually does. it just goes to the top left corner and doesnt take the whole screen. but if i try to maxmize the client from my main monitor it maximizes normal and fine which is weird. if anyone can find a solution let me know, the client was working earlier really well and this problem came outta no where its juist weird.

### Screenshots or videos

<blockquote class="imgur-embed-pub" lang="en" data-id="a/Pgf5nGk"  ><a href="//imgur.com/a/Pgf5nGk">Runelite Bug</a></blockquote>
https://imgur.com/a/Pgf5nGk

This is the gif of me trying to maxmize from my second monitor and it just kept coming back to my main monitor not even takin the full screen and it locks there.

**Comment by Nightfirecat** [comment] 2022-09-14 06:17
What launcher version are you running? Does this happen on the latest launcher? (2.5.0)

**Comment by aloranetwork** [comment] 2022-09-14 06:20
> 
1.8.33 idk if thats 2.50 but the recently one on the website. I just redownloaded it 20 minutes ago i should have the up to date one

**Comment by aloranetwork** [comment] 2022-09-14 06:21
> What launcher version are you running? Does this happen on the latest launcher? (2.5.0)

1.8.33 idk if thats 2.50 but the recently one on the website. I just redownloaded it 20 minutes ago i should have the up to date one

**Comment by Nightfirecat** [comment] 2022-09-14 06:30
That's the client version, not the launcher version. That said, if you've downloaded and installed today, it ought to be 2.5.0

**Comment by aloranetwork** [comment] 2022-09-14 06:31
> That's the client version, not the launcher version. That said, if you've downloaded and installed today, it ought to be 2.5.0

yeah i downloaded it today so its up to date then. but I only redownloaded it cause this bug started happening outta no where. any solutions?

**Comment by Adam-** [comment] 2022-09-14 12:14
This should be fixed by 142234d947e6cec7e5b8851d8981663adbbb240d, it is caused by launcher 2.5.0 having java version 11.0.16.1 which the version test fails to parse

**Comment by aloranetwork** [comment] 2022-09-14 19:16
> This should be fixed by [142234d](https://github.com/runelite/runelite/commit/142234d947e6cec7e5b8851d8981663adbbb240d), it is caused by launcher 2.5.0 having java version 11.0.16.1 which the version test fails to parse
so i copy and paste that into my files?

**Closed** 2024-11-03 23:51 UTC
Labels: needs-triage
