### ISSUE TITLE
Overall XP Tracker wrong math

### ISSUE THREAD

**Issue by Draxxrs** [runelite/runelite#8087] opened 2019-03-03 17:18 UTC
**Describe the bug**
The overall XP tracker currently gives you two sets of visual data:
1.: Experience gained in every stat since the beginning of first experience drop.
2.: Total experience overall per hour.

The 2nd is calculated wrong. As of today, it does not calculate experience overall per hour.
It adds all indiviual skills' experience rate, not taking into consideration the different starting times.

**To Reproduce**
1.: Train two skills or more, starting at different time periods.

**Expected behavior**
What we expect to see, is how much experience we have gained in total(which it does), aswell as our xp/hour (which it most of times does not do correctly).

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.14
 - Launcher version: 1.6.0

**Additional context**
If I may come with a mathematical fix, the formula should be as follows:
       (Total Experience Gained)/(Time since first experience drop)
       = Experience gained per hour

**Comment by Hydrox6** [comment] 2019-03-03 17:18
Duplicate of #8086

**Closed** 2019-03-03 17:21 UTC
