### ISSUE TITLE
World Pinger

### ISSUE THREAD

**Issue by DaxterTek** [runelite/runelite#6122] opened 2018-10-21 22:49 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

-> No problem, just an addition to RL.

**Describe the solution you'd like**

-> I would like to see a plugin to ping single or multiple selected worlds and pinging based on country.
Maybe an addition to the World Hopper plugin or an entirely new plugin.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

-> Currently I use my own custom script to ping specific worlds or even ping based on country.
It would be a nice feature to have built into the client for all users to have access to.

**Additional context**

**Comment by Hydrox6** [comment] 2018-10-21 22:50
Duplicate of #2460

**Closed** 2018-10-21 22:50 UTC
