### ISSUE TITLE
Tele To POH

### ISSUE THREAD

**Issue by danjsmith4** [runelite/runelite#11471] opened 2020-05-05 13:36 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
I have the Teleport option menu entry swapper enabled, swaps the "teleport option" to left click for Con Cape. Would like it to be Tele to POH as this more useful. If this is not possible for the teleport section, can there be a specific spot for just the Construction cape.  

**Describe the solution you'd like**
A section or menu option to make left click Tele to POH on con cape. Currently only can do the teleport option which is useless. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
shift click which is okay but prefer to left click it.

**Additional context**
Only current option is to shift click it.

**Comment by Hydrox6** [comment] 2020-05-05 13:37
Duplicate of #6227

**Closed by Hydrox6** 2020-05-05 13:37 UTC
