### ISSUE TITLE
Overlay does not show for master clue step "Kill the spiritual, magic and godly whilst representing their own god"

### ISSUE THREAD

**Issue by sadegr** [runelite/runelite#9104] opened 2019-06-14 18:31 UTC
![2019-06-14_14-30-22](https://user-images.githubusercontent.com/20391979/59530239-1984cd00-8eb1-11e9-814d-0cf4b61435c4.png)

**Comment by Hydrox6** [comment] 2019-06-14 18:55
Duplicate of #2053

This is because it is a Challenge Clue, which are currently not supported. See #9000

**Closed by Hydrox6** 2019-06-14 18:55 UTC

**Comment by sadegr** [comment] 2019-06-14 19:27
@Hydrox6 Not sure I understand. There was just a typo in the code (missing `.`). I've created a pull request to fix it - #9105. If I'm misunderstanding something, please clarify.

**Comment by Hydrox6** [comment] 2019-06-14 20:32
So it turns out that this clue was added as a Cryptic already, though it should be a Skill Challenge clue.

**Comment by Nightfirecat** [comment] 2019-06-14 20:42
Let's address that in #9000?
