### ISSUE TITLE
Damage Drops

### ISSUE THREAD

**Issue by MajoraMasked** [runelite/runelite#13904] opened 2021-07-19 02:18 UTC
A plug-in for converting xp drops to floating damage numbers, for the purposes of easy damage tracking and counting.

An alternative could be faster updating of enemy health bars when using ranged/mage rather than awaiting the projectile to connect if this is possible?

This would be a fairly massive endeavor with the need for runelite to be able to track your attack style/ pvm exp modifiers/ etc. I'm just curious if it can be done. Thank you!!!

**Comment by Nightfirecat** [comment] 2021-07-19 02:24
Duplicate of #4055

**Closed by Nightfirecat** 2021-07-19 02:24 UTC
Labels: duplicate
