### ISSUE TITLE
Moveable Experience Drop

### ISSUE THREAD

**Issue by brodycragg** [runelite/runelite#5163] opened 2018-08-27 19:33 UTC
The experience drop is quite far away from the character and can be a bit hard to see. Could it be made to be positionable anywhere on the screen as to fit our needs?

**Comment by sirlaige** [comment] 2018-08-27 21:35
Hmm not 100% sure this is what your describing but I'm imagining the skill icon and number that floats up to the xp trackers when you gain xp.  I think it would be kind of nice to be able to move these little xp drops closer to the player.  We can already move the xp tracker, so these xp drops being able to be moved would be great.

**Comment by brodycragg** [comment] 2018-08-28 13:04
Yes exactly, kinda how it was positioned in OSbuddy- right next to the player. It really helps for pking. If this exp drop was movable, it'd be really helpful.

**Comment by oplosthee** [comment] 2018-08-28 13:12
The vanilla client allows repositioning of experience drops, does this achieve what you are trying to do?

![Image](https://i.imgur.com/7zvi8Av.png)

**Comment by brodycragg** [comment] 2018-08-28 13:26
Not exactly. It's a start but I'd like to be able to put it anywhere if you catch my drift. Like exactly over my character's head or something.

**Comment by William1Gray** [comment] 2018-08-28 13:28
Would #5064 apply to this or am I misunderstanding what that pull adds

**Comment by deathbeam** [comment] 2018-09-07 19:08
Duplicate of #5075

**Closed by deathbeam** 2018-09-07 19:08 UTC
Labels: feature-request
