### ISSUE TITLE
Animation Smoothing freaks out sometimes

### ISSUE THREAD

**Issue by jorisrs** [runelite/runelite#2707] opened 2018-05-14 07:15 UTC
Whilst killing hellhounds I noticed this (See the legs);
![image](https://user-images.githubusercontent.com/36892108/39983231-3bcd796c-5757-11e8-928f-b35afd9889bd.png)

I don't know if there are more animations on which this occurs.

**Comment by Kamielvf** [comment] 2018-05-14 07:17
Duplicate of #1516, relevant: #1808 #1497

**Closed** 2018-05-14 08:36 UTC
