### ISSUE TITLE
Add pickpocketing to loot tracker

### ISSUE THREAD

**Issue by zacharye08** [runelite/runelite#8520] opened 2019-04-14 07:54 UTC
Would be nice for ardy knights, ham members, master farmers, etc.

**Comment by kyle1elyk** [comment] 2019-04-16 01:56
What if this was enabled by an opt-in check box in the loottracker config, false by default?

**Comment by Hydrox6** [comment] 2019-04-16 02:00
Duplicate of #4126

**Closed by Hydrox6** 2019-04-16 02:00 UTC
Labels: feature-request
