### ISSUE TITLE
Farming contracts unavailable in time tracker

### ISSUE THREAD

**Issue by borkedborkedborked** [runelite/runelite#18261] opened 2024-09-12 01:56 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

This is somewhat similar to March's 17635 but happened under different circumstances.

Logged in after a fresh boot up.  I knew the farming contract icon contract was incorrect, but rather than reset it by checking with the guild master, I simply completed it since I remembered what it was (a yew, versus I think a bush).  Doing so appears to have permanently eliminated farming contracts on time tracker; I've reset time tracker, reinstalled Runelite, run Runelite in safe mode, and a couple other things - it now appears unable to parse the existence of a contract.

### Screenshots or videos

https://imgur.com/a/GCu0tFE

### RuneLite version

2.7.2
1.10.37

**Comment by Felanbird** [comment] 2024-09-12 01:57
Duplicate of #18260

**Closed by Felanbird** 2024-09-12 01:57 UTC
Labels: duplicate
