### ISSUE TITLE
Add custom idle notification sound

### ISSUE THREAD

**Issue by RaspberrySchnapps** [runelite/runelite#1884] opened 2018-04-24 18:28 UTC
Would be nice if there was a custom sound for when you stop skilling and start being idle. A selectable sound file for that would also prove very convenient, the current windows "BOP" isn't the most pleasant sound to hear every minute or so.

**Comment by Reasel** [comment] 2018-04-24 20:47
You can actually change the default windows notification sounds in your OS. https://www.groovypost.com/howto/turn-off-change-windows-10-notification-sounds/ Seems to be configurable. Might be able to add your own .wav file as well.

**Comment by RaspberrySchnapps** [comment] 2018-04-24 21:11
Oh, cool, I didn't know one could do that. Still, a custom sound for the client only would be a neat little feature.

**Comment by Reasel** [comment] 2018-04-24 21:14
Well maybe something could be made to make a known ingame noise instead of a windows notification. I know [#1568](https://github.com/runelite/runelite/pull/1568) will make effects noises happen if game is muted. Something like that maybe? Would be next to useless if you play with game sounds on however.

**Comment by deathbeam** [comment] 2018-05-08 18:25
Duplicate of #920

**Closed by deathbeam** 2018-05-08 18:25 UTC
Labels: feature-request

**Comment by Regular-Merc** [comment] 2020-03-24 19:08
> You can actually change the default windows notification sounds in your OS. https://www.groovypost.com/howto/turn-off-change-windows-10-notification-sounds/ Seems to be configurable. Might be able to add your own .wav file as well.

For anyone trying this out, the program event of "Default Beep" needs to be changed. (This is what Runelite sets off to give you the notification) In windows 10: Settings >Personalization > Themes > Sounds

**Comment by fedbia** [comment] 2023-08-20 18:39
> > You can actually change the default windows notification sounds in your OS. https://www.groovypost.com/howto/turn-off-change-windows-10-notification-sounds/ Seems to be configurable. Might be able to add your own .wav file as well.
> 
> For anyone trying this out, the program event of "Default Beep" needs to be changed. (This is what Runelite sets off to give you the notification) In windows 10: Settings >Personalization > Themes > Sounds

It's definitely not Default Beep on Windows 10. The sound is "Notification". That said, when I change that sound it doesn't change the Runelite notification.

Also, an easier way to reach sound is right clicking the speaker icon on the bottom right of the screen.

**Comment by LuisMCap** [comment] 2024-10-16 17:35
> > > You can actually change the default windows notification sounds in your OS. https://www.groovypost.com/howto/turn-off-change-windows-10-notification-sounds/ Seems to be configurable. Might be able to add your own .wav file as well.
> > 
> > 
> > For anyone trying this out, the program event of "Default Beep" needs to be changed. (This is what Runelite sets off to give you the notification) In windows 10: Settings >Personalization > Themes > Sounds
> 
> It's definitely not Default Beep on Windows 10. The sound is "Notification". That said, when I change that sound it doesn't change the Runelite notification.
> 
> Also, an easier way to reach sound is right clicking the speaker icon on the bottom right of the screen.

In the plugin section, search for "RuneLite", go to Notification Settings and select "Native" for Notification sound. It automatically sets "Default Beep" now, and you can change the sound by doing exactly what you did before
