### ISSUE TITLE
Hotkey for left-click walk

### ISSUE THREAD

**Issue by osrs991** [runelite/runelite#4437] opened 2018-07-21 08:41 UTC
It'd be a nice feature to have the ability to hold down a hotkey to make "Walk Here" be the default option on the menu. This would help for bosses where you need to walk under (e.g. godwars), or where theres lots of NPCs in the way (e.g. zulrah)

**Comment by deathbeam** [comment] 2018-07-21 08:42
Duplicate of #1412

**Closed by deathbeam** 2018-07-21 08:42 UTC
