### ISSUE TITLE
Menu Entry Swapper changes for Temple Trekking

### ISSUE THREAD

**Issue by RebornFX** [runelite/runelite#2402] opened 2018-05-06 11:39 UTC
Temple Trekking is a great source of certain resources for ironmen, and it would be much more tolerable if many of the pointless left-click options were replaced by their second option down. 

Some examples include:
https://i.imgur.com/gZM4zTe.jpg

Some other features would also be appreciated, such as similar features to the agility plugin (treks completed, treks/hr), certain clickboxes being highlighted, perhaps even colour coded trek companions for the easy, medium and hard companions. I have no idea how feasible any of these features would be or if they would be worth anybody's time considering temple trekking is basically only worth doing for ironmen and people hunting the lumberjack outfit.

**Comment by deathbeam** [comment] 2018-09-20 09:47
Duplicate of #5380 (as that includes only 1 suggesion and not 10 in one, open separate issues for separate requests)

**Closed by deathbeam** 2018-09-20 09:47 UTC
Labels: feature-request
