### ISSUE TITLE
Favorite farming tracker tap

### ISSUE THREAD

**Issue by iPepeep** [runelite/runelite#9194] opened 2019-06-23 23:50 UTC
**Is your feature request related to a problem? 
Not fast to find my farming patches because use a 10/60+ Farming patches only 

**Describe the solution you'd like**
A tap that we can use our favorite farming patched to show up only and ignore other

**Describe alternatives you've considered**
1- favorate farming tap
2- enable/disable farming patches
3- showing farming patches if it used only

**Additional context**
N/A

**Comment by Hydrox6** [comment] 2019-06-23 23:52
Duplicate of #8893

**Closed by Hydrox6** 2019-06-23 23:52 UTC
