### ISSUE TITLE
Adding a ping checking type thing

### ISSUE THREAD

**Issue by Saelem** [runelite/runelite#4129] opened 2018-07-02 10:36 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to glance at my in-game interface and be able to check my ping.

**Describe the solution you'd like**
Add a ping checker to the top of the interface similar to that of the fps one currently in-game.

**Describe alternatives you've considered**
Perhaps a ping checker to the side on the panels that we could use.
 
Thanks
Saelem

**Comment by deathbeam** [comment] 2018-07-02 10:51
Duplicate of #2640

**Closed by deathbeam** 2018-07-02 10:51 UTC
