### ISSUE TITLE
Some items don't work in price checker / bank overlay

### ISSUE THREAD

**Issue by Ben1220** [runelite/runelite#4096] opened 2018-06-30 00:55 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| Java Version | x.y.z
| Operating System | e.g. Ubuntu/Windows/MacOS

I noticed this on the toxic staff of the dead - some items that are currently untradeable on the ge due to not being full or empty charge or due to being altered in some way do not give the correct price.  This also occurs for some items with (g) trims from clue scrolls such as Dragon full helm (g) - Price is for the trim not the helmet + trim which are easily separated.  Some of these items need different rules in order to give accurate bank worth values.

**Comment by Nightfirecat** [comment] 2018-07-02 22:47
Duplicate of #3909.

**Closed** 2018-07-02 22:48 UTC
Labels: bug
