### ISSUE TITLE
Openjdk11 SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by jdamata** [runelite/runelite#6657] opened 2018-11-24 04:05 UTC
**Describe the bug**
Can't launch runelite

**To Reproduce**
1. Run ```java -jar RuneLite.jar --mode=OFF```

**Expected behavior**
Runelite runs

**Environment (please complete the following information):**
 - OS: Fedora 29
 - RuneLite version: [1.5.1]
```
┌─[23:03:09 joel-damata ~/Downloads]
└─╼ java --version
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode, sharing)
```

**Additional context**
```bash
┌─[22:59:52 joel-damata ~/Downloads]
└─╼ java -jar RuneLite.jar --mode=OFF
2018-11-23 23:00:01 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2018-11-23 23:00:01 [main] ERROR net.runelite.launcher.Launcher - error fetching bootstrap
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:265)
	at net.runelite.launcher.Launcher.main(Launcher.java:168)
```

**Comment by jdamata** [comment] 2018-11-24 04:07
Works on openjdk10

**Comment by deathbeam** [comment] 2018-11-24 12:52
Duplicate of #6221

**Closed by deathbeam** 2018-11-24 12:52 UTC
