### ISSUE TITLE
Highlight doors in Pyramid Plunder

### ISSUE THREAD

**Issue by Redfighter96** [runelite/runelite#6079] opened 2018-10-19 10:15 UTC
Pyramid Plunder doors aren't always that easy to see.

It would be great if the doors which let you advance to the next room were highlighted in some way to make them more distinguishable. 

There is currently no way to highlight this.

Thank you in advance.

**Comment by deathbeam** [comment] 2018-10-19 10:31
Duplicate of #2446

**Closed by deathbeam** 2018-10-19 10:31 UTC
