### ISSUE TITLE
IncompleteAnnotationException: Unable to Start Runelite

### ISSUE THREAD

**Issue by sean-duffy** [runelite/runelite#4201] opened 2018-07-06 17:54 UTC
| Question    | Answer
| ------------| ---------------
| Java Version | 8.0.1710.11
| Operating System | Windows 10

When I build the latest version of master, it builds correctly then when I run it in IntelliJ I get the below exception and the client fails to start. Prior to this it was working fine.

<details>
 <summary>stack trace</summary>
 
 ```
"C:\Program Files\Java\jdk1.8.0_171\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.4\lib\idea_rt.jar=50493:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_171\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\rt.jar;C:\Users\seand\github\runelite\runelite-client\target\classes;C:\Users\seand\.m2\repository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;C:\Users\seand\.m2\repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;C:\Users\seand\.m2\repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;C:\Users\seand\.m2\repository\net\sf\jopt-simple\jopt-simple\5.0.1\jopt-simple-5.0.1.jar;C:\Users\seand\.m2\repository\com\google\guava\guava\23.2-jre\guava-23.2-jre.jar;C:\Users\seand\.m2\repository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar;C:\Users\seand\.m2\repository\com\google\errorprone\error_prone_annotations\2.0.18\error_prone_annotations-2.0.18.jar;C:\Users\seand\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;C:\Users\seand\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar;C:\Users\seand\.m2\repository\com\google\inject\guice\4.1.0\guice-4.1.0-no_aop.jar;C:\Users\seand\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;C:\Users\seand\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;C:\Users\seand\.m2\repository\com\google\code\gson\gson\2.8.5\gson-2.8.5.jar;C:\Users\seand\.m2\repository\net\runelite\pushingpixels\substance\8.0.02\substance-8.0.02.jar;C:\Users\seand\.m2\repository\net\runelite\pushingpixels\trident\1.5.00\trident-1.5.00.jar;C:\Users\seand\.m2\repository\org\apache\commons\commons-text\1.2\commons-text-1.2.jar;C:\Users\seand\.m2\repository\org\apache\commons\commons-lang3\3.7\commons-lang3-3.7.jar;C:\Users\seand\github\runelite\runelite-api\target\classes;C:\Users\seand\github\runelite\runescape-api\target\classes;C:\Users\seand\.m2\repository\net\runelite\injected-client\1.4.7-SNAPSHOT\injected-client-1.4.7-20180705.123949-3.jar;C:\Users\seand\github\runelite\runelite-scripts\target\classes;C:\Users\seand\github\runelite\http-api\target\classes;C:\Users\seand\.m2\repository\com\squareup\okhttp3\okhttp\3.7.0\okhttp-3.7.0.jar;C:\Users\seand\.m2\repository\com\squareup\okio\okio\1.12.0\okio-1.12.0.jar;C:\Users\seand\.m2\repository\net\runelite\discord\1.0\discord-1.0.jar;C:\Users\seand\.m2\repository\net\java\dev\jna\jna\4.5.1\jna-4.5.1.jar" net.runelite.client.RuneLite
2018-07-06 18:50:56 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-07-06 18:50:57 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-07-06 18:50:57 [main] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.annotation.IncompleteAnnotationException: net.runelite.client.config.ConfigGroup missing element value
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:81)
	at com.sun.proxy.$Proxy9.value(Unknown Source)
	at net.runelite.client.config.ConfigManager.setDefaultConfiguration(ConfigManager.java:401)
	at net.runelite.client.plugins.PluginManager.loadDefaultPluginConfiguration(PluginManager.java:179)
	at net.runelite.client.RuneLite.start(RuneLite.java:260)
	at net.runelite.client.RuneLite.main(RuneLite.java:207)
 ```
</details>

**Comment by deathbeam** [comment] 2018-10-12 13:03
This was probably just caused by wrong build, closing

**Closed by deathbeam** 2018-10-12 13:03 UTC
Labels: bug
