### ISSUE TITLE
Screen marker delete warning hides behind client if client always on top is on.

### ISSUE THREAD

**Issue by Kiskis1** [runelite/runelite#3197] opened 2018-05-24 11:53 UTC
Have to open task manager and try to end the task. The client is not moving and gives sounds when trying to click anything.

**Comment by TzZek** [comment] 2018-05-24 11:55
Temp fix would probs just to be hit enter to confirm the deletion.

**Comment by MESLewis** [comment] 2018-05-24 11:55
As a work around for now you can hit enter when this happens and it will delete the marker.

**Comment by deathbeam** [comment] 2018-05-24 12:04
Duplicate of #2690

**Closed by deathbeam** 2018-05-24 12:04 UTC
