### ISSUE TITLE
Mage Training Arena - Telekinetic room solutions are not always correct

### ISSUE THREAD

**Issue by Majst** [runelite/runelite#5269] opened 2018-09-02 22:22 UTC
Some of the solutions in the room tell you to cast telekinetic grab in a tile highlighted on the ground, when you cast telekinetic grab on the guardian it doesn't move, so the solution is not correct / efficient.

These should be fixed to have the correct tiles highlighted on the ground, there is more than 1 room with an issue.

It appears that the tile does not update, as if I step off the tile it stays green like I am standing on it, not turning red like it should be.

https://i.imgur.com/OXppsox.png Standing on the tile
https://i.imgur.com/OjbPEf6.png Standing off the tile, but it is still green like I am standing on it

The solution is also incorrect in the screenshots, maybe the final solution is not switching / not registered that I already cast telekinetic grab in that position.

Windows 10, Runlite 1.4.15 with launcher 1.5.2

**Comment by Majst** [comment] 2018-09-02 22:30
Here is another incorrect solution.

https://i.imgur.com/aFj6Npi.png Standing on the tile
https://i.imgur.com/ri9o3Vc.png However this tile turns red when not standing on it.

**Comment by ShaunDreclin** [comment] 2018-09-03 00:46
Can confirm this issue, noticed it myself when I was getting bones to peaches the other day

**Comment by Alexsuperfly** [comment] 2018-10-07 18:30
duplicate of #3946

**Closed** 2018-10-07 18:31 UTC
Labels: bug
