### ISSUE TITLE
Menu Entry Swapper: Butterfly Jars

### ISSUE THREAD

**Issue by persecom** [runelite/runelite#8606] opened 2019-04-21 16:20 UTC
**Is your feature request related to a problem? Please describe.**
Right-clicking to empty a butterfly jar.

**Describe the solution you'd like**
Have the empty option as a left click.

**Describe alternatives you've considered**
Suggesting this change on the weekly Q&A.

**Comment by Hydrox6** [comment] 2019-04-21 16:21
Duplicate of #6210

Use [Shift Click Configuration](https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper#shift-click-configuration)

**Closed by Hydrox6** 2019-04-21 16:21 UTC
