### ISSUE TITLE
Add the option to turn on notifications for when a specified potion runs out

### ISSUE THREAD

**Issue by zygaloo** [runelite/runelite#10362] opened 2019-12-01 12:02 UTC
I only saw that there was this option for overloads, I think it would be useful for a lot of players including myself.

**Comment by Hydrox6** [comment] 2019-12-01 12:11
If it has a chat message, use Chat Notifications

Duplicate of #9913

**Closed by Hydrox6** 2019-12-01 12:11 UTC

**Comment by zygaloo** [comment] 2019-12-01 12:23
> If it has a chat message, use Chat Notifications
> 
> Duplicate of #9913

It doesn't have a chat message, what can I do then?

**Comment by Hydrox6** [comment] 2019-12-01 13:28
What potion is it?

**Comment by zygaloo** [comment] 2019-12-01 14:16
> What potion is it?

Super combat potion

**Comment by Hydrox6** [comment] 2019-12-01 14:19
That's what the Threshold option in the Boosts Information plugin is for

**Comment by zygaloo** [comment] 2019-12-01 14:23
> That's what the Threshold option in the Boosts Information plugin is for

I want to know exactly when it ends, not when there's 1 minute remaining. The minimum amount you can set there is 1

**Comment by Hydrox6** [comment] 2019-12-01 14:24
so yeah, Duplicate of #9913

**Comment by zygaloo** [comment] 2019-12-01 14:28
> so yeah, Duplicate of #9913

You didn't help me at all, thanks

**Comment by Hydrox6** [comment] 2019-12-01 14:30
This is not a support forum, this is an issue tracker. Questions should be for the Discord
