### ISSUE TITLE
Barrows- Prayer Drain Timer is producing duplicates, is stuck on after leaving.

### ISSUE THREAD

**Issue by arisingangel** [runelite/runelite#12537] opened 2020-09-22 23:45 UTC
I currently have 5 "Prayer Drain" timers active despite no longer being at barrows. These persist after logging out and travelling far away.
I had some lag when doing barrows earlier, this may have contributed.

**Comment by Hydrox6** [comment] 2020-09-22 23:46
Duplicate of #10902

**Closed by Hydrox6** 2020-09-22 23:46 UTC
