### ISSUE TITLE
Puro Puro, impling spaces will not despawn

### ISSUE THREAD

**Issue by edenojack** [runelite/runelite#3037] opened 2018-05-20 22:40 UTC
I'm looking at a series of 35 impling spawns from across worlds that aren't dissapearing. Is this intended?

**Comment by Adam-** [comment] 2018-05-20 22:43
Duplicate of #2913. Was fixed in 1.3.9.1.

**Closed by Adam-** 2018-05-20 22:43 UTC
Labels: duplicate

**Comment by edenojack** [comment] 2018-05-20 23:00
This is an ongoing issue in 1.3.9.1. Going from one world, to another world does not remove previous world's markers, every new "tile" (I think thats what the world is divided into) the player enters, the spaces reload, based on the player's position. So if there is a dragon impling 10 spaces north in one world, you change, the dragon impling's marker will still be there. Then you can teleport, and wherever you teleport to, there will still be a marker there.

**Comment by Adam-** [comment] 2018-05-21 00:27
If you click the info panel.. what version is listed there?
