### ISSUE TITLE
!kc command not working in PMs

### ISSUE THREAD

**Issue by FearrMe** [runelite/runelite#4368] opened 2018-07-17 15:43 UTC
title explains the bug, works fine outside of PMs

**Comment by Rpearson94** [comment] 2018-07-21 15:33
@FearrMe I could not reproduce the issues where it was not sending in PM. How did you reach that error?

**Comment by FearrMe** [comment] 2018-07-22 20:50
@Rpearson94 I've just tested something and it seems to work fine if you type it in regular chat first, and then in PMs after. It doesn't work the first time in PMs. (note that in the picture I sent _!kc bandos_ in PMs, then regular chat, then PMs again)
![example](https://user-images.githubusercontent.com/1979467/43049983-7e43fa10-8e01-11e8-8869-20ad8fe322d8.png)

**Comment by Adam-** [comment] 2018-07-22 23:45
Fixed in 37c95ff75e459d5c334d3af26425b3b5e74ddef7

**Closed by Adam-** 2018-07-22 23:45 UTC
Labels: bug
