### ISSUE TITLE
Client does not load with gpu plugin turned on

### ISSUE THREAD

**Issue by Gurpreet83** [runelite/runelite#11944] opened 2020-06-20 10:55 UTC
**Describe the bug**
The game gets stuck at various points of the Jagex loading screen

**Screenshots**
https://imgur.com/9mafPEx

**Environment (please complete the following information):**
 - OS: Win 10, 980 ti gpu
 - RuneLite version: 1.6.2
 - Launcher version: 2.1.0

**Comment by GFerdinand** [comment] 2020-06-23 17:17
I had the same issue on MacOS 10.5.5. Basically the client would load and then immediately stop responding as soon as the runescape loading screen hit, requiring a force quit. I'm not sure if the logs show anything interesting but the issue was resolved by setting gpu to false in the settings file. After doing that I cannot replicate the issue even by toggling GPU back to on. 

[client.log](https://github.com/runelite/runelite/files/4820879/client.log)
[launcher.log](https://github.com/runelite/runelite/files/4820880/launcher.log)

**Comment by GFerdinand** [comment] 2020-06-30 18:48
It happened again today. I had to once again go into the settings file (~/.runelite/settings.properties) to disable the gpu plugin or else the client would instantly stop responding. Mind you this happens before the client has fully loaded so you cannot disable the plugin through the configuration pane. Nontechnical Mac users might not know how to fix the problem causing their runelite client to be completely bricked.

**Comment by Adam-** [comment] 2020-06-30 18:49
> 
> 
> It happened again today. I had to once again go into the settings file (~/.runelite/settings.properties) to disable the gpu plugin or else the client would instantly stop responding. Mind you this happens before the client has fully loaded so you cannot disable the plugin through the configuration pane. Nontechnical Mac users might not know how to fix the problem causing their runelite client to be completely bricked.

FWIW you can pass `--clientargs "--safe-mode"` to the launcher which will also disable it.

**Comment by Nightfirecat** [comment] 2022-07-10 04:34
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:34 UTC
Labels: needs-information
