### ISSUE TITLE
Open World Map on correct coordinates when you open a coordinates Clue scroll

### ISSUE THREAD

**Issue by Andreluppers** [runelite/runelite#5653] opened 2018-09-26 13:23 UTC
Currently when you get a coordinates clue, you have to open your world map, and press the clue scroll picture to get located to the right place to dig.

Would be nice if the world map opens automaticly when opening a clue with coordinates. 
I know that OSBuddy has this feature. 

If it's tedious to automaticly open the map, maybe create a button on the clue, to open the map on the correct way. It saves a lot of times for us clue hunters👍

**Comment by deathbeam** [comment] 2018-09-26 13:55
Duplicate of #2746

**Closed by deathbeam** 2018-09-26 13:55 UTC
