### ISSUE TITLE
[Suggestion] Search Option for loot tracker

### ISSUE THREAD

**Issue by LewisKappa** [runelite/runelite#10940] opened 2020-03-03 16:48 UTC
Because of the loot tracker being spammed after a while, and not wanting to reset it. It would be nice for a search option.

**Comment by Alexsuperfly** [comment] 2020-03-03 16:50
the placing of the most recently killed monster is a duplicate of #8519 
could you narrow the scope of this request to only be the searching

**Comment by Chee-RS** [comment] 2020-03-04 01:25
kinda off-topic but I think (like 99.8% sure) the loot tracker sometimes slows down my game so I have to reset it to not lag, is there a way to fix this?

**Comment by ypperlig** [comment] 2020-05-09 13:41
Duplicate of #10704

**Closed** 2020-05-09 14:05 UTC
Labels: feature-request
