### ISSUE TITLE
Anti-Scam protection

### ISSUE THREAD

**Issue by BSpawns** [runelite/runelite#8290] opened 2019-03-22 16:06 UTC
**Is your feature request related to a problem? Please describe.**
The scamming in OSRS has gotten out of hand and I think a simple plugin could fix a lot of the issues not all of them but a lot of them.

**Describe the solution you'd like**
Would like to have a feature where we can highlight names of ignored people (if we ignore the scammer) or highlight certain users even when they're not friends.

**Describe alternatives you've considered**
I've tried adding them to friends but they won't be highlighted as they are not adding me back.

**Additional context**

**Comment by BSpawns** [comment] 2019-03-22 16:09
Wouldn't be opposed to having customizable databases that clans can use to add blacklistings of scammers and or whomever they choose to not affiliate with and it could be used by the entire clan.

**Comment by Hydrox6** [comment] 2019-03-22 16:11
Duplicate of #4944 and #4622

**Closed** 2019-03-23 12:56 UTC
