### ISSUE TITLE
Supply usage tracker

### ISSUE THREAD

**Issue by CreamOSRS** [runelite/runelite#6700] opened 2018-11-26 16:18 UTC
Keeps track of the supplies you use on task , bossing or pking so you know exactly how much you earn.  Used along side Loot tracker or an addition to it.

**Comment by raiyni** [comment] 2018-12-24 16:18
Duplicate #4126

**Comment by raiyni** [comment] 2020-05-04 15:54
Duplicate of #6700

**Closed by raiyni** 2020-05-04 15:54 UTC
Labels: feature-request
