### ISSUE TITLE
Upgraded Camulet swap options when equipped says "teleport", selecting it switches to "Temple", no way to make it "Surface" on the equipment screen.

### ISSUE THREAD

**Issue by Raisoshi** [runelite/runelite#15224] opened 2022-06-27 19:00 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10 Pro

### Bug description

The camulet has the option of teleporting to the surface, right beside the granite/sand mining spot, after completion of the Desert Hard Diary. I have the upgraded version with unlimited charges.

I tried setting it to teleport to the surface with a left click while equipped, on the equipment window, the only options given to me to swap to were "Teleport" and "Check". The options available should probably be "Temple", "Surface" and "Check".

Selecting "Teleport" switches the left click to "Temple", so I don't see a way to pick "Surface". I believe this to be either a bug or something was overlooked about this item, maybe something to do with the hard diary or it being upgraded.

### Screenshots or videos

Default left click:
![image](https://user-images.githubusercontent.com/60229317/176015365-2a3fd2ac-77f7-4a91-ab24-23337e999895.png)
Right click options:
![image](https://user-images.githubusercontent.com/60229317/176015171-84027a04-66ba-47fa-90a5-6ae2861ae77f.png)
Shift-right clicking to switch the left click option using menu entry swapper:
![image](https://user-images.githubusercontent.com/60229317/176015233-7dfe6529-efe9-467b-b10d-8343157d674d.png)
This is the left click hover option after selecting "Swap left click Teleport Camulet":
![image](https://user-images.githubusercontent.com/60229317/176015298-4ff95d19-8be4-49c7-869c-6ad30fe70daf.png)

### RuneLite version

RuneLite version: 1.8.24.3
Launcher version: 2.4.2
Oldschool revision: Rev 206

**Comment by Hydrox6** [comment] 2022-06-27 19:04
Duplicate of #15150

**Closed by Hydrox6** 2022-06-27 19:04 UTC
Labels: needs-triage
