### ISSUE TITLE
Silver Jewelry Notifications

### ISSUE THREAD

**Issue by null-zero** [runelite/runelite#3564] opened 2018-06-02 03:12 UTC
**Is your feature request related to a problem? Please describe.**

I'm not always paying attention to chat when skilling, so I might miss or mix up the notifications on when my jewelry breaks.

**Describe the solution you'd like**

Add a a toggle option for notifications using the idle notifier for when silver jewelry breaks

**Describe alternatives you've considered**

**Additional context**

**Comment by Adam-** [comment] 2018-06-22 00:33
Going to assume this is specifically about dodgy necklace since it is so vague. Duplicate of #3031

**Closed by Adam-** 2018-06-22 00:33 UTC
Labels: feature-request
