### ISSUE TITLE
Ba overlay monsters left 

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#2274] opened 2018-05-03 00:05 UTC
Just a neat thing to add. Would show how much penance is left on screen

In order to not have so much clutter would be best if it only showed the penance relating to your role though. So if your defender you see runners, healer sees healers, attacker sees ranger/fighter

Also due to how the wave spawns work, would be best to show total left. instead of how many are left on screen.

Example being wave 7 for healer. Initially 4 will spawn but 3 additional ones will spawn later after 3 have died. So in the overlay would be best (imo) to show 7 remaining at the start.

Heres all the spawns that would be needed
Format: Initial Spawn-Latespawn (total)

![image](https://user-images.githubusercontent.com/33562756/39555015-e8a96258-4e2a-11e8-8977-cf16cf9294ed.png)

**Comment by deathbeam** [comment] 2018-07-08 01:43
Duplicate of #3691

**Closed by deathbeam** 2018-07-08 01:43 UTC
Labels: feature-request
