### ISSUE TITLE
Rock Thrownhammer With Loot Tracker Bug

### ISSUE THREAD

**Issue by Areorah** [runelite/runelite#15603] opened 2022-09-01 04:23 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When using 'Rock thrownhammer' on Gargoyles (I do have the auto-smasher unlock), it doesn't always register the drop to Loot Tracker. I am safe-spotting them in the Canifis Slayer Dungeon. Something else I have noticed, is that I am using a 'Ring of Wealth' when killing and all of the 'Coins' drops aren't showing up in the log. I have killed 270 Gragoyles today using the 'Rock thrownhammer' and only it only shows 157 in the Loot Tracker tab. It hasn't shown any coin drops and I know for a fact that I have gotten several 10,000 coin drops (as shown in the picture below.) 

### Screenshots or videos

![image](https://user-images.githubusercontent.com/19559232/187830561-0ebf601e-62db-4fbc-87ee-3e49fe6fb5a9.png)

### RuneLite version

RuneLite version: 1.8.32.2
Launcher version: 2.1.7

### Logs

[launcher.log](https://github.com/runelite/runelite/files/9466812/launcher.log)
[client.log](https://github.com/runelite/runelite/files/9466813/client.log)

**Comment by Nightfirecat** [comment] 2022-09-01 05:30
Duplicate of #5077, this is mostly unfixable.

**Closed by Nightfirecat** 2022-09-01 05:30 UTC
Labels: duplicate
