### ISSUE TITLE
Half the verticies on the magic tree animation is reversed

### ISSUE THREAD

**Issue by Dternity** [runelite/runelite#6620] opened 2018-11-21 19:32 UTC
When the GPU plug-in is enabled half of the vertices if the magic tree animation is reversed in other words the starts go up instead of down. 

Enable GPU plug-in > Look at the magic tree from above to clearly see it. 

**Expected behavior**
All the stars should be going down.

**Screenshots**
Without the GPU plug-in: https://i.imgur.com/JWl17VL.gifv 
With the GPU plug-in: https://i.imgur.com/nPmss5u.gifv

**Environment (please complete the following information):**
 - OS: Windows 10 Pro Build 17134
 - RuneLite version: 1.5.0

**Additional context**
This is probably one of many small graphical glitches that is to be expected with such a large plug-in. 
Will continue to report graphical glitches as i encounter them.

**Comment by Adam-** [comment] 2018-11-21 19:34
Duplicate of #6601

**Closed by Adam-** 2018-11-21 19:34 UTC
