### ISSUE TITLE
Mobile Quantity Left-Click Option

### ISSUE THREAD

**Issue by geeseyeet** [runelite/runelite#4665] opened 2018-08-03 07:24 UTC
Like in Mobile, you can change the left-click option when withdrawing from the bank from 1 to 5, 10, X and All

**Comment by Abextm** [comment] 2018-08-03 07:25
Duplicate of #1647

https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Closed by Abextm** 2018-08-03 07:25 UTC
Labels: duplicate
