### ISSUE TITLE
Run and Prayer Remaining Time Notifier 

### ISSUE THREAD

**Issue by FidgetyJester** [runelite/runelite#9762] opened 2019-08-29 03:45 UTC
I check alot of times and see how much time are left for run and prayer before it runs out.

So I think it would be cool if it just shows how much time are left in the screen instead. Kinda like with the XP drop, but shows the time limit for Run and Prayer instead and elsewhere in the screen.

**Comment by Hydrox6** [comment] 2019-08-29 06:08
The % on the run energy orb can already be replaced with the time remaining; check the `Run Energy` plugin.
As for prayer, Duplicate of #9579

**Closed by Hydrox6** 2019-08-29 06:08 UTC
