### ISSUE TITLE
Verticle Zoom bug during Grotesque Guardians

### ISSUE THREAD

**Issue by RsRandall** [runelite/runelite#4526] opened 2018-07-27 06:42 UTC
When I hold the Mouse scroll wheel down to verticle zoom it goes off my players focus.
Not sure at what point it accrues but as shown in the GIF provided I have only experienced this bug during this boss. 
https://i.imgur.com/2tuXTzx.gifv

**Comment by Abextm** [comment] 2018-07-27 06:50
Duplicate of #4290
Thanks for the gif

**Closed by Abextm** 2018-07-27 06:50 UTC
Labels: duplicate
