### ISSUE TITLE
Entity Hider Expanded

### ISSUE THREAD

**Issue by IronPerish** [runelite/runelite#9495] opened 2019-07-28 07:21 UTC
I noticed the entity hider can hide just player, just NPCs but you can't hide specific NPC. For instance, I'd like to hide all random events other than Genie and Imp.
Could someone add a feature where you can type the NPC's name and it will only disable that NPC? Similar to if you type an NPC's name in the tagging feature it only tags them.
Just thought this would be handy since I'm constantly clicking on people's random events when doing things with lots of people close by. Or being able to hide that damned Zammy mage next to the altar at ZMI.

**Comment by Nightfirecat** [comment] 2019-08-12 16:09
Duplicate of #2310 and #6854

**Closed by Nightfirecat** 2019-08-12 16:09 UTC
Labels: duplicate
