### ISSUE TITLE
"Remember last Tag Tab" option only works if closing the bank with "X" button

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#6212] opened 2018-10-27 06:35 UTC
Closing the bank with "Esc" does not remember the current tag

**Comment by deathbeam** [comment] 2018-10-27 08:32
Duplicate of #6198

**Closed by deathbeam** 2018-10-27 08:32 UTC

**Comment by Nightfirecat** [comment] 2018-10-27 16:41
I guess? 6198 didn't explain anything about how to reproduce. :man_shrugging:

**Comment by deathbeam** [comment] 2018-10-27 16:41
I believe it is exactly same issue, widget not being nulled
