### ISSUE TITLE
Show if master clue fight is Ancient Wizards or Brassican Mage

### ISSUE THREAD

**Issue by TrevorMartz** [runelite/runelite#11171] opened 2020-04-02 19:21 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice to see if the master coord step is in multi so we know which fight we need to be prepared for.

**Describe the solution you'd like**
Some text on the clue info box that indicates if the fight is Ancient Wizards or Brassican Mage, similar to how it tells you it requires a spade.

**Additional context**
The wiki already has all of the data here. https://oldschool.runescape.wiki/w/Treasure_Trails/Guide/Coordinates/Master

**Comment by Hydrox6** [comment] 2020-04-02 19:23
Duplicate of #2580

**Closed by Hydrox6** 2020-04-02 19:23 UTC
