### ISSUE TITLE
Face North for other directions

### ISSUE THREAD

**Issue by PossessedRyd** [runelite/runelite#10537] opened 2020-01-03 03:11 UTC
**Is your feature request related to a problem? Please describe.**
Im always frustrated that i when i spin my camera to face east or west i cant get it lined up right and it bothers me immensely.

**Describe the solution you'd like**
Theres already a solution in game for facing north! Id really enjoy some way to get a button or a right click option somewhere to face east west and also south. When you click this button or whatever it is you click to implement it itll face you exactly in the direction you chose. Just like how it does when you click to face north

**Describe alternatives you've considered**
Im not really sure of any alternatives.

**Additional context**
I think that this feature could be really helpful to alot of people and for those of us who get frustrated with imperfect camera turning it would make my day.

**Comment by Alexsuperfly** [comment] 2020-01-03 04:16
duplicate of #1770

**Closed** 2020-01-03 05:34 UTC
