### ISSUE TITLE
Mythical cape left click options

### ISSUE THREAD

**Issue by Vanillablows** [runelite/runelite#13915] opened 2021-07-21 02:01 UTC
This one I believe would be pretty simple, but to be able to change the left click option on the mythical cape would be great. Currently you can have it changed with the where the left click is the teleport option, but it would be nice to have it follow some of the other frequently used items like karamja gloves where it has its own commands in the plug in. I hope that made sense, anyways I keep teleporting when I go to change gear for the dragon war hammer spec

**Comment by Vanillablows** [comment] 2021-07-21 02:03
Also first time using github so I’m sure I’m doing something wrong so please bear with me.

**Comment by Nightfirecat** [comment] 2021-07-21 05:37
Maybe setting [a customizable shift-click option](https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper#customizable-shift-click) for the mythical cape would be the best solution for you? That way, you can set that option specifically for the cape and nothing else.

**Comment by Hydrox6** [comment] 2021-07-24 08:22
Duplicate of #9695

**Closed by Hydrox6** 2021-07-24 08:22 UTC
