### ISSUE TITLE
Ignore list player indicator addition

### ISSUE THREAD

**Issue by bl0delysians** [runelite/runelite#13925] opened 2021-07-22 20:55 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
My suggestion is to include an option as part of the player indicator plugin to have coloured names show up above players who are on someones ignore list the same way we have player names show up above their character for friends, friends chat, team members, others etc. 
**Describe the solution you'd like**
to have a toggle-able option added to player indicator plugin in addition to the ones already there for people on one's ignore list. this might prevent trolls and unsportsmanlike players to troll/scam in one's raids or groups.
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Nightfirecat** [comment] 2021-07-22 20:57
Duplicate of #4944

**Closed by Nightfirecat** 2021-07-22 20:57 UTC
Labels: duplicate

**Comment by zaiah9** [comment] 2024-06-12 19:04
I'd like to see this added as well
