### ISSUE TITLE
Increase render distance

### ISSUE THREAD

**Issue by mzchen** [runelite/runelite#4306] opened 2018-07-13 07:34 UTC
A large step up over RuneLite which OSBuddy has is extra render distance. It helps sense of direction and overall aesthetic of the game. For a game which was rebooted more than 5 years ago, it's somewhat shameful they still haven't gotten over the graphical limitations of 10 years ago. A plugin which increases render distance should make OSRS more attractive and modernized by an enormous margin. 

Ideally, this would be a plugin which renders a fairly large distance and is toggleable/editable for those on lower-end pcs.

Alternatively, anything that reduces the blandness of the giant black box would be nice as well. One of the best changes to RS3 was increasing draw distance and killing fog. Moving from there to here, the big black box was by far the most shocking change.

To close, I'm relatively new to this community and to OSRS as a whole, so maybe this is impossible/hard to do, or unnecessary, or whatever, so go easy I guess? I'd love to hear any options in this regard.

**Comment by deathbeam** [comment] 2018-07-13 07:35
Duplicate of #513

**Closed by deathbeam** 2018-07-13 07:35 UTC
