### ISSUE TITLE
Runelite wont load

### ISSUE THREAD

**Issue by Thann7** [runelite/runelite#4169] opened 2018-07-04 15:47 UTC
Hey guys, when I tried to open runelite it begins to open but does not surpass 0% then immediately closes. I attempted a reinstall or searching through other issues with no prevail on fixing the issue. Here is a copy of the launcher logs. 

2018-07-04 12:39:20 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-1.4.5.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of slf4j-api-1.7.25.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-classic-1.2.3.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-core-1.2.3.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jopt-simple-5.0.1.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guava-23.2-jre.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jsr305-1.3.9.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of error_prone_annotations-2.0.18.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of j2objc-annotations-1.1.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of animal-sniffer-annotations-1.14.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guice-4.1.0-no_aop.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of javax.inject-1.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of aopalliance-1.0.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gson-2.8.5.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of substance-8.0.02.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of trident-1.5.00.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-text-1.2.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-lang3-3.7.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runelite-api-1.4.5.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runescape-api-1.4.5.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of injected-client-1.4.5.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of scripts-1.4.5.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of http-api-1.4.5.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okhttp-3.7.0.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okio-1.12.0.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of discord-1.0.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-4.5.1.jar
2018-07-04 12:39:22 [main] INFO  net.runelite.launcher.Launcher - Verified signature of net.runelite:client:jar:1.4.5

Any help would be greatly appreciated!

**Comment by Alexsuperfly** [comment] 2018-07-04 15:57
one thing you can do is delete the repository folder located in `%userprofile%/.runelite`, thats a common fix for things like this.  Or post your application logs since that would show if you have a problem connecting to the RS servers to fetch the official client.

**Comment by Thann7** [comment] 2018-07-04 16:03
Just tried to delete the repository folder and attempted to reopen it, no difference. I cant post any application logs because there isnt any. I deleted all the Runelite files as I read in another thread with the same concern they deleted everything and installed it and rectify the issue. 

This is the only available file in %userprofile%/.runelite
[launcher.log](https://github.com/runelite/runelite/files/2163798/launcher.log)

**Comment by Alexsuperfly** [comment] 2018-07-04 16:04
could you try using the all platforms launcher?

**Comment by Thann7** [comment] 2018-07-04 16:07
I downloaded that .jar previously but couldnt find much information on how to launch it.

**Comment by Alexsuperfly** [comment] 2018-07-04 16:10
You need to install java onto your system to launch jar files.

**Comment by Thann7** [comment] 2018-07-04 16:12
Just tried that, does the same thing unfortunately.

**Comment by Alexsuperfly** [comment] 2018-07-04 16:12
right click open with java

**Comment by Thann7** [comment] 2018-07-04 16:13
Sorry that wasn't clearly stated, it attempts to open but does the exact same thing as the windows 64bit.

**Comment by Alexsuperfly** [comment] 2018-07-04 16:13
anything different in the logs?

**Comment by deathbeam** [comment] 2018-07-04 16:14
Duplicate of https://github.com/runelite/launcher/issues/18

**Comment by Thann7** [comment] 2018-07-04 16:14
I was just posted that!
[application.log](https://github.com/runelite/runelite/files/2163825/application.log)

**Comment by deathbeam** [comment] 2018-07-04 16:14
I would prefer for the discussion be kept in their specific issues so feel free to move it there

**Closed by deathbeam** 2018-07-04 16:14 UTC

**Comment by Thann7** [comment] 2018-07-04 16:15
Moving there now, sorry.

**Comment by kekkemeister** [comment] 2019-08-25 06:05
I had same problem using the 64-bit version of runelite, the problem just appeared out of nowhere so I tried re-installing it, did not work. So I downloaded the 32-bit version and it ran normally. mine had error code 0x0000005 or something don't remember and think it referred to corrupt windows files, didn't try to re-install windows but I think that might have worked as a fix also.

**Comment by Iconiic** [comment] 2020-08-28 16:40
Hi Guys, Im having the same kinda issue mentioned above. I used to use the 64bit Runelite client, but it suddenly stopped working out of no where. I am unable to open the client, every time I click it nothing happens. I was able to download the 32bit version, but for some reason with the 32bit version, I drop frames a lot. I never dropped frames prior with the 64bit version. Somebody please help.
