### ISSUE TITLE
(NON IDLE) notifcation when you've reached 28 coin pouches from thieving

### ISSUE THREAD

**Issue by Duradel** [runelite/runelite#6716] opened 2018-11-27 18:49 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Nice for e.g. Ardy knight and other thieving things

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Hydrox6** [comment] 2018-11-27 18:52
There's a message when you try to pickpocket with 28 coin pouches. Add this message to the Chat Notifications plugin, that'll do what you want.

**Comment by deathbeam** [comment] 2018-11-27 20:04
Duplicate of #4308

**Closed by deathbeam** 2018-11-27 20:04 UTC
