### ISSUE TITLE
Corporeal beast special attack counter

### ISSUE THREAD

**Issue by DrewDey** [runelite/runelite#1378] opened 2018-04-11 17:24 UTC
Add a counter for how many successful special attack hits for DWH and arclight and a counter for BGS damage.

Thanks :)

**Comment by Kamielvf** [comment] 2018-04-11 17:26
Duplicate of #492

**Comment by DrewDey** [comment] 2018-04-11 17:34
Woops. Thanks.

**Closed** 2018-04-11 21:27 UTC
