### ISSUE TITLE
Don't show items below certain quantity ground items plugin

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#2572] opened 2018-05-10 21:15 UTC
I'm not interested in seeing a 1 coin stack, but I am interested in a 10k stack. I'm not interested in 1 raw, noted lobster but I am interested in 10 raw noted lobsters.

**Comment by Reasel** [comment] 2018-05-10 22:29
This seems super subjective and will vary from item to item. 10k is fine for gp, but noted raw lobsters 10k is a metric buttload. This seems really specific imho

**Comment by kilbyjmichael** [comment] 2018-05-10 22:45
I would guess that @Gamer1120  is suggesting the user could change the number/items for their specific needs

**Comment by Gamer1120** [comment] 2018-05-10 22:48
Exactly

**Comment by SomeZer0** [comment] 2018-05-10 22:53
This would be useful.

Fire giants drop big bones. I don't want to see 100 fire giant bones highlighted on the screen. That's clutter. I would like to block these.

Kurasks drop noted big bones. These do not cause any clutter, I actually pick these up and would like to highlight them.

Currently either block both or deal with both.

Although it looks like what I'm talking about is different, and would be easier to implement

(block unnoted item, highlight noted version)

**Comment by Reasel** [comment] 2018-05-10 22:54
I agree with noted items highlight toggle.

**Comment by Gamer1120** [comment] 2018-05-10 22:56
@SomeZer0 There are monsters which drop 1 raw noted lobster (Dagannoth?) and monsters which drop 10 (Brine Rat). Noted does matter.

**Comment by deathbeam** [comment] 2018-05-25 16:45
From duplicate: The overall request do not makes much sense when it can be done in better way (e.g hiding items < value). I have also PR that adds new option to highlight items over value if that helps, but I dont think something like this is useful to implement. Also probably duplicate of another issue.

**Comment by SomeZer0** [comment] 2018-05-25 17:59
I think this would be a good way of doing it:

"Show Noted/Stacks of these items (even if on block list)"
[Input Box] (optional syntax in the box like: Big Bones>5, Coins>1000, 
(Optionally, instead of using syntax in the box above, we could have a universal minimum stack)
(optionally)"Minimum stack requirement to highlight"
[Input Box]

**Comment by Gamer1120** [comment] 2018-06-29 21:22
Another place where this would be useful is Ourania Altar. I don't want to see the 1 or 2 runes that UIM dropped, but I'm interested in seeing rune drops (like above 5) in general.

**Comment by deathbeam** [comment] 2018-07-08 00:40
Duplicate of #1123

**Closed by deathbeam** 2018-07-08 00:40 UTC
Labels: feature-request
