### ISSUE TITLE
Valuable Ground Item Notification

### ISSUE THREAD

**Issue by c5gaspar** [runelite/runelite#3643] opened 2018-06-05 19:55 UTC
**Is your feature request related to a problem? Please describe.**
When AFKing monsters (i.e., for slayer) we have system notifications for: combat inactivity, low hitpoints, low prayer, etc. However, if you're AFKing some monster and receive a valuable drop, currently there is no notification to alert you to this fact. In all likelihood the item will disappear with the user being none the wiser. 

**Describe the solution you'd like**
I think an optimal solution would be to implement a valuable item notifier where once a pre-determined threshold is met, a system notification could be generated to alert the user to the item. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by marshdevs** [comment] 2018-06-05 21:14
Are you imagining these notifications always on? Or only while idle?

**Comment by c5gaspar** [comment] 2018-06-05 21:16
**Only while idle**. There seems to be a catch-22 in the current implementation of these notification. In order to get notifications about health, prayer, combat you need to have the window non-focused (minimized), but in order to see items you need to have the window in view (likely in focus).

**Comment by deathbeam** [comment] 2018-06-05 21:18
You can configure that in "RuneLite" settings. Also what does "idle" mean. All I would do here is just send the notification when valuable item drops, uncoditionally and leave rest to global configuration. Also, this issue is duplicate.

**Comment by deathbeam** [comment] 2018-06-05 21:20
Oh, actually it is not? Or at least I can't find the original issue, but I swear i saw it.

**Comment by c5gaspar** [comment] 2018-06-05 21:23
> Also what does "idle" mean
I think he meant when the window is non-focused. Perhaps I should have been more explicit in my original post that this is underlying condition of the notification. AFAIK there aren't any system notifications for monster ground items, regardless of the focus state of the client and so this is the true purview of my suggestion/request.

**Comment by marshdevs** [comment] 2018-06-05 21:26
Working on this

**Comment by brace110** [comment] 2018-10-04 22:30
Is this feature added to the client ?

**Comment by unmrshl** [comment] 2018-10-04 22:33
https://github.com/runelite/runelite/pull/3647

PR has been open for a while.

**Comment by deathbeam** [comment] 2018-10-05 06:56
Reopened as this issue was not resolved yet so it should not be closed

**Comment by deathbeam** [comment] 2018-10-05 07:04
Oh actually, we already have issue open for this so maye that is why it was closed, so lets close it properly as duplicate of #1469

**Closed by deathbeam** 2018-10-05 07:04 UTC
Labels: feature-request

**Comment by seitzcasey** [comment] 2019-11-20 00:47
I may be stupid but it seems that #1469 and this were both closed due to there being duplicates

**Comment by sethtroll** [comment] 2019-11-20 00:51
This was implemented in #3647

**Comment by seitzcasey** [comment] 2019-11-20 00:56
> This was implemented in #3647

I realize this now. Thank you. I'm looking for functionality to do a window notification for a drop over a certain value threshold. Is that currently implemented?

**Comment by sethtroll** [comment] 2019-11-20 01:01
The interface has since changed from that PR, but if you enable `Notify for highlighted drops` in the `ground items` plugin, then set a `Highlight>Value` it will notify you of items higher than that value (granted you have notifications on).

**Comment by seitzcasey** [comment] 2019-11-20 01:06
> The interface has since changed from that PR, but if you enable `Notify for highlighted drops` in the `ground items` plugin, then set a `Highlight>Value` it will notify you of items higher than that value (granted you have notifications on).

thank you
