### ISSUE TITLE
Suggestion: Ignore list player indicators 

### ISSUE THREAD

**Issue by tobignorelist** [runelite/runelite#12065] opened 2020-07-05 03:13 UTC
The problem is having 100s of trolls and cancer players on your ignore list with no easy way to spot them.

The easy solution is highlight people on your ignore list in red the same way people are highlighted green on your friends list with the player indicators plugin. 

This would be massively helpful at Theatre of blood where you could easily spot people on your ignore list to avoid raiding with them instead of finding out that they are trolls too late.

**Comment by Nightfirecat** [comment] 2020-07-05 03:27
Duplicate of #10515

**Closed by Nightfirecat** 2020-07-05 03:27 UTC
Labels: duplicate
