### ISSUE TITLE
Plugging HDMI cable to external monitor when the client is open makes it crash (GPU plugin)

### ISSUE THREAD

**Issue by FQuen** [runelite/runelite#12153] opened 2020-07-15 16:09 UTC
**Overview of the Issue** 
When the GPU plugin is enabled, plugging the macbook to an external monitor with an HDMI cable crashes RuneLite. I don't know if this is a Mac-specific issue.

If I disable the GPU plugin I have no problem. So I think the plugin is the issue there.

**Reproduce the Error**
1. Launch RuneLite
2. Make sure GPU plugin is enabled
3. Restart RuneLite
4. Wait until login screen is displayed
5. Plug macbook to external monitor

**Java Version and Operating System**
- Macbook Pro Early 2015
- MacOS Catalina 10.15.5
- RuneLite 1.6.21.1
- Java version 8, update 261

**Comment by MESLewis** [comment] 2021-01-13 02:44
Duplicate of #12930

**Closed by MESLewis** 2021-01-13 02:44 UTC

**Comment by miikaj1** [comment] 2021-11-30 06:02
This seems similar to #12390, but I believe it is a different issue because this issue only occurs with GPU plugin on. #12390 
occurs either way: ["this occurs with the RL GPU turned on and off"](https://github.com/runelite/runelite/issues/12930#issuecomment-760628558). This issue should be reopened because although the trigger (plugging HDMI cable to external monitor) is the same, the cause is likely different. There are other issues of people reporting this problem, but I do not see any error logs in any of these previous issues. Adding here:
```
2021-11-29 21:12:51 [AppKit Thread] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: Apple M1 Max
2021-11-29 21:12:51 [AppKit Thread] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 2.1 Metal - 76.1
2021-11-29 21:13:09 [Client] ERROR client-patch - Client error: null
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.asIntBuffer()" because the return value of "com.jogamp.opengl.GL4.glMapBuffer(int, int)" is null
	at jogamp.nativewindow.macosx.OSXUtil.RunOnMainThread(OSXUtil.java:324)
	at net.runelite.client.plugins.gpu.GpuPlugin.invokeOnMainThread(GpuPlugin.java:1764)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1077)
	at ai.g(ai.java:64853)
	at ai.run(ai.java:368)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.asIntBuffer()" because the return value of "com.jogamp.opengl.GL4.glMapBuffer(int, int)" is null
	at net.runelite.client.plugins.gpu.GpuPlugin.prepareInterfaceTexture(GpuPlugin.java:1113)
	at net.runelite.client.plugins.gpu.GpuPlugin.drawFrame(GpuPlugin.java:1134)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$draw$8(GpuPlugin.java:1077)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:143)
error_game_crash
```

I would like to clarify that the game freezes but the rest of the client (settings, etc.) work fine. This issue does not occur when _disconnecting_ external monitor. It also does not make a difference if the client is changing displays or staying on the same display. I think this error log should help to reopen this issue, but I would also be happy to collect more debugging information as this issue can be reliably reproduced (enable GPU plugin and connect external HDMI display on Mac OS).
