### ISSUE TITLE
Extremely High GPU Usage

### ISSUE THREAD

**Issue by Jademalo** [runelite/runelite#8458] opened 2019-04-10 07:16 UTC
**Describe the bug**
Occasionally, RuneLite will start hammering my GTX970 at 100% causing the game to stutter like crazy for no discernable reason

**To Reproduce**
This is not 100% consistent, but it seems to be the way I can get it to happen most frequently.
1. Open Runelite in fullscreen
2. With GPU enabled, window the game and make it relatively small
3. Double click the title bar/maximise button to fullscreen the game
4. If that didn't work, click the arrow in the title bar to collapse the side bar

**Expected behavior**
I expect it to keep using about 30% of my GPU and to stay buttery smooth. However, it hammers my GPU at near 100%. 

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.18
 - Launcher version: 

**Additional context**
This is an extremely weird and intermittent bug. It seems to be somewhat related to resizing the game, as that's when it tends to happen.
If the game is a small window and it's maximized, that can cause it. If the side bar is collapsed and the game made bigger, that can cause it.

It doesn't seem related to custom window chrome, nor does it seem related to Stretched Mode. However, enabling/disabling stretched mode can cause it to "fix" itsself.
Disabling the GPU plugin always fixes it, which makes me fairly sure it's some weird GPU issue.

If the game is in Fixed mode, this doesn't happen. It's only in resizable, and it only manifests when the game is resized.

**Comment by gccltl** [comment] 2019-04-10 17:15
I've noticed RuneLite consuming more resources, too. 
My graphics card is nVidia's GTX 750 Ti, running on Windows 10 (build 17763).
The GPU driver is **419.67**. RuneLite version **1.5.18**

**Comment by Jademalo** [comment] 2019-04-10 20:58
It's not so much generally higher resources, it's a very specific bug that spikes from 30% to 99% GPU usage. This isn't just a slight inefficiency

**Comment by Druxlolz** [comment] 2019-04-11 09:58
my 1070 uses 30% of the gpu on runelite and it uses 1-2 closer to 2 GB of ram. 
And i will have to restart runelite atleast 2 times a day cause of to much lag.

**Comment by zertap** [comment] 2020-11-06 15:58
Indeed, also getting extreme lag when doing bird house runs (when running from the bank to the nearest bird house). Causes whole system to start lagging, cursor movement stuttering etc. i7 4790k & RTX 480 with GPU plugin enabled. Win10.
Though my friend experiences similar issues with the same GPU running linux, in the same spot doing bird house runs.

**Comment by Nightfirecat** [comment] 2022-07-10 04:18
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:18 UTC
Labels: bug, gpu
