### ISSUE TITLE
Tarn Razorlor quest completion marked as a kill on slayer task (Vorkath)

### ISSUE THREAD

**Issue by ExperimentMonty** [runelite/runelite#15451] opened 2022-08-05 21:28 UTC
### Type

Incorrect behavior

### Bug description

When a friend had an active Vorkath slayer task, and completed the Tarn Razorlor miniquest, it marked that as a Vorkath kill for him. I think because that miniquest gives slayer XP that Runelite got confused and thought he must have gotten a kill.

**Comment by Nightfirecat** [comment] 2022-08-05 21:36
Duplicate of #7984. It's a known issue that non-slayer sources of slayer exp trigger a decrement in the task counter

**Closed by Nightfirecat** 2022-08-05 21:36 UTC
Labels: duplicate
