### ISSUE TITLE
Experiencing heavy issues within menu

### ISSUE THREAD

**Issue by 114167** [runelite/runelite#1489] opened 2018-04-13 16:12 UTC
Experiencing heavy issues within the menu, this happened just after installation of the app, never used it before.
I am currently using windows 10.

I'll provide several screenshots of the issue.

![explorer_2018-04-13_18-01-18](https://user-images.githubusercontent.com/9083720/38745860-19ff7548-3f46-11e8-8140-b65be69216cc.jpg)
![runelite_2018-04-13_18-01-40](https://user-images.githubusercontent.com/9083720/38745863-1c070842-3f46-11e8-97f9-05eea4cfd1b7.jpg)
![explorer_2018-04-13_17-59-22](https://user-images.githubusercontent.com/9083720/38745845-11e33598-3f46-11e8-9ee3-7cfdb636bc8e.jpg)

This issue seems similar to issue #1458 but am not sure if it's the same, hence the new issue

**Comment by Kamielvf** [comment] 2018-04-13 16:13
see https://github.com/runelite/runelite/issues/1449#issuecomment-380942422

**Comment by deathbeam** [comment] 2018-04-13 19:05
Duplicate of #1449 

Check the issue for temporary solution too.

**Closed by deathbeam** 2018-04-13 19:05 UTC
Labels: invalid
