### ISSUE TITLE
UI Anchor point above inventory.

### ISSUE THREAD

**Issue by bluelightzero** [runelite/runelite#12908] opened 2020-12-10 09:53 UTC
Right now there are 7 anchor points (when you hold alt and move overlays, indicated by #)

It would be nice to have 1 above the inventory to anchor the map and orbs to. (Indicated by @)

    ............................................................................
    . #######                     #######                 #######      ####### .
    . #######                     #######                 #######      ####### .
    . #######                     #######                 #######      ####### .
    . #######                     #######                 #######      ####### .
    .                                                                          .
    .                                                                          .
    .                                                                          .
    .                                                                          .
    .                                                                          .
    .                                                                          .
    .                                                                          .
    .                                                                          .
    .                                                                  @@@@@@@ .
    .                                                                  @@@@@@@ .
    .                                                                  @@@@@@@ .
    .                                                                  @@@@@@@ .
    . #######                     #######                 #######  ____________.
    . #######                     #######                 ####### |____________.
    . #######                     #######                 ####### |            .
    . #######                     #######                 ####### |            .
    .____________________________________                         |            .
    .                                    |                        |            .
    .                                    |                        |            .
    .                                    |                        |            .
    .____________________________________|                        |____________.
    .                                    |                        |            .
    ............................................................................

**Comment by Hydrox6** [comment] 2020-12-10 09:56
Duplicate of #8515 (See comment [here](https://github.com/runelite/runelite/issues/10793#issuecomment-587267537) for reasoning)

Love the pixel art though, honestly great.

**Closed by Hydrox6** 2020-12-10 09:56 UTC
