### ISSUE TITLE
Bug in XP Tracker

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2166] opened 2018-04-30 04:50 UTC
https://i.imgur.com/iztUlM8.jpg

Guessing that if the integer of remaining experience to level is less than the action you've been doing, the tracker doesn't count it as an action required for level when fetching that number.

**Comment by Unmoon** [comment] 2018-04-30 04:54
Duplicate of #1735

**Closed** 2018-04-30 04:56 UTC
