### ISSUE TITLE
Agility shortcuts not rendering at long distance anymore

### ISSUE THREAD

**Issue by bloodred** [runelite/runelite#7040] opened 2018-12-21 05:39 UTC
After today's update the Agility shortcut outlines only show up if you're within render distance of it with the GPU plugin turned off. Now that we have the GPU renderer that allows us to see far away why would you remove the ability to see the Agility shortcuts as far as we can see?

Example: https://gfycat.com/ColorfulAgreeableIndianskimmer

Yesterday I was able to see this shortcut outline from the farthest runestone, now it doesn't show. This is really annoying in multiple areas I've noticed

**Comment by Abextm** [comment] 2018-12-21 05:40
They were removed because 
1) They hurt performance in many areas
2) You can't actually click on them, so showing the clickbox is incorrect

**Comment by bloodred** [comment] 2018-12-21 05:41
> 2. You can't actually click on them, so showing the clickbox is incorrect

I'm still able to click on this shortcut even when it isn't highlighted

**Comment by GobbleMe** [comment] 2018-12-21 22:32
As soon as I reloaded my client I noticed this too in the same area actually.  Its bugging the crap out of me because I used the boxes as a quick click reference (basically like screenmarkers but better since I move my camera) and losing them really hurts.  A simple toggle to render agility shortcuts when they're out of the clickable range would be an easy fix, no parties lose out.

**Comment by bloodred** [comment] 2018-12-22 00:02
> As soon as I reloaded my client I noticed this too in the same area actually. Its bugging the crap out of me because I used the boxes as a quick click reference (basically like screenmarkers but better since I move my camera) and losing them really hurts. A simple toggle to render agility shortcuts when they're out of the clickable range would be an easy fix, no parties lose out.

That’s exactly how I use them too, shows me where I need to click with a quick glance

**Comment by Adam-** [comment] 2018-12-22 00:42
Until we figure out a better (more performant) way to do this we probably cannot render then much further away than currently. The issue is mostly the Tirannwn area with the dense forest.

**Comment by deathbeam** [comment] 2018-12-23 09:54
Duplicate of #1360

**Closed by deathbeam** 2018-12-23 09:54 UTC
