### ISSUE TITLE
Replace monsters with their older models from 2004~2006

### ISSUE THREAD

**Issue by ForgotMyPasswordLOL** [runelite/runelite#13527] opened 2021-04-25 14:17 UTC
Title. 

I would love a plugin that replaces the models of monsters with their original look. The old models are still in the cache and earlier this year Mod Ash added animations to most of the original models for OSRS's birthday event, so I assume this plugin would be a lot more easier to make nowadays.

Thank you.

**Comment by Hydrox6** [comment] 2021-04-25 15:18
Duplicate of #3261

**Closed by Hydrox6** 2021-04-25 15:18 UTC
