### ISSUE TITLE
Client Notepad Doesn't Word Wrap

### ISSUE THREAD

**Issue by CharlesLove** [runelite/runelite#1823] opened 2018-04-23 02:10 UTC
See image below.

![image](https://user-images.githubusercontent.com/5576972/39103924-55dd5cea-4673-11e8-95c4-5f9c0714a6a1.png)

**Comment by Gamer1120** [comment] 2018-04-23 06:12
Duplicate of #1824

**Closed** 2018-04-23 06:30 UTC
