### ISSUE TITLE
client loads at 0% then closes

### ISSUE THREAD

**Issue by EternalGaze** [runelite/runelite#6830] opened 2018-12-06 01:02 UTC
windows, latest version of runelite. i open it up, loading bar shows up, stays at 0% for like 1 second then immediately closes.

[application.log](https://github.com/runelite/runelite/files/2651216/application.log)

**Comment by deathbeam** [comment] 2018-12-07 00:13
Duplicate of #4287

**Closed by deathbeam** 2018-12-07 00:13 UTC
