### ISSUE TITLE
Dropped item timer

### ISSUE THREAD

**Issue by AliAlhabib** [runelite/runelite#4609] opened 2018-08-01 06:24 UTC
Hello,

Can we please get a dropped item timer, maybe switches colors or something to show when the item is visible to public? 

Example:
Blue from 1:59 to 1:01 and red from 01:00 till it disappears at zero?

Thank you.

**Comment by deathbeam** [comment] 2018-08-01 06:25
Duplicate of #2383

**Closed by deathbeam** 2018-08-01 06:25 UTC
