### ISSUE TITLE
Herb run timer 

### ISSUE THREAD

**Issue by Pkersdemise** [runelite/runelite#8758] opened 2019-05-05 10:52 UTC
I would like it if we could have a herb run timer to tell us when our herbs are done. The bird houses have a notification, which i understand is an outlier, but i dont see why herb runs shouldn't have one too. Thanks!

**Comment by Hydrox6** [comment] 2019-05-05 10:55
Duplicate of #2212

**Closed by Hydrox6** 2019-05-05 10:55 UTC
