### ISSUE TITLE
Farming compost indicator

### ISSUE THREAD

**Issue by pettrs** [runelite/runelite#13965] opened 2021-07-31 10:35 UTC
**Is your feature request related to a problem? Please describe.**
I often ask myself did i compost that patch, even right after doing it, especially since i struggle with memory.

**Describe the solution you'd like**
An indicator, maybe colored in hull on the patch that indicates if it has been composted.

**Describe alternatives you've considered**
an icon over the patch with a compost bucket if it has not yet been composted, possibly also an additoin to the farming tracker plugin where it shows an icon on the patches that have not been composted, similat to how farming contracts are tagged

**Additional context**

**Comment by Hydrox6** [comment] 2021-07-31 10:36
Duplicate of #2472

**Closed by Hydrox6** 2021-07-31 10:36 UTC

**Comment by pettrs** [comment] 2021-07-31 10:38
holy shit, ye that wasn't an original idea lmao. fastest close ive seen lmao

**Comment by pettrs** [comment] 2021-07-31 10:39
is it already an added feature, if so, how do i enable it?

**Comment by Nightfirecat** [comment] 2021-07-31 15:47
We have not yet implemented it. Once the linked issue is closed, it should be added.
