### ISSUE TITLE
Collection Log for Skilling

### ISSUE THREAD

**Issue by syberbagel** [runelite/runelite#11629] opened 2020-05-16 18:13 UTC
**Is your feature request related to a problem? Please describe.**
When skilling, there is no tracker to see what resources I have collected during the session.

**Describe the solution you'd like**
A tracker similar to the loot tracker that will show a log of whatever you have collected during that skilling session separated by skill being used

**Describe alternatives you've considered**
There are no alternatives currently.

**Comment by Nightfirecat** [comment] 2020-05-16 22:39
Duplicate of #7177

**Closed by Nightfirecat** 2020-05-16 22:39 UTC
Labels: duplicate
