### ISSUE TITLE
Lag/Fps spikes

### ISSUE THREAD

**Issue by username989898** [runelite/runelite#9867] opened 2019-09-14 18:11 UTC
Getting lag spikes only in a specific space which is the demonic gorilla tunnels. It doesn't happen anywhere else but its very annoying there because it happens every 30 seconds. Have a good computer so probably not the reason.. Any ideas?

**Comment by Hydrox6** [comment] 2019-09-14 18:29
Duplicate of #9329
In short, get the newest launcher (version 2.0.0 or 2.0.2 depending on your OS)

**Closed by Hydrox6** 2019-09-14 18:29 UTC
