### ISSUE TITLE
In-bank notifier for when you have 3 dark totem pieces in the bank

### ISSUE THREAD

**Issue by dan-ashe** [runelite/runelite#6324] opened 2018-11-03 13:25 UTC
I would like the option to toggle on an icon or something in my bank that lights up/highlights when I have 3 dark totem pieces so that I can combine them and get more from future drops in the catacombs. This solves the problem of forgetting to combine them and missing out on the opportunity for more.

**Comment by deathbeam** [comment] 2018-11-03 17:41
Duplicate of #2856

**Closed by deathbeam** 2018-11-03 17:41 UTC
