### ISSUE TITLE
Screenshot Plugin - screenshot on collection log addition

### ISSUE THREAD

**Issue by DivineInsanity** [runelite/runelite#13695] opened 2021-06-05 09:50 UTC
Would love to see another category of screenshots be for "Collection Log" where it can screenshot whenever you get the chatbox message / popup indicator for a new collection log. This way it could cover more niche elements of the game that some users may like to document.

**Comment by Hydrox6** [comment] 2021-06-05 09:51
Duplicate of #13673

**Closed by Hydrox6** 2021-06-05 09:51 UTC
