### ISSUE TITLE
Quest filtering system

### ISSUE THREAD

**Issue by jacksonben1331** [runelite/runelite#5363] opened 2018-09-07 01:40 UTC
**Is your feature request related to a problem? Please describe.**
Yes, im kind of new to osrs. Not too new, been playing for a month or 2 but one reason i dont like doing quests is cause i dont know which ones to start on, which ones to do, or which ones are too hard or i cant even do.

**Describe the solution you'd like**
A filter that you could adjust, like it could pull your stats and reccomend quests for you to do based on your stats, and for certain quests that have safespots, add in text that says you can safespot this boss, possibly. It would also say the rewards gained such as items and exp. Also possibly have a story line filter.

**Describe alternatives you've considered**
Going to the wiki, but personally i dont like using the wiki, it doesnt feel as satisfying for me to look at the wiki. Also its just annoying to look through lots of quests to see if you can even do them.

**Additional context**
This plugin would really help out new players, by incentiveizing them  to do quest based on rewards and by them knowing that they can do this easy quest.

**Comment by Joshua-F** [comment] 2018-09-07 03:09
#3024 adds some filtering, might not be exactly what you're asking though.

**Comment by jacksonben1331** [comment] 2018-09-07 04:28
sweet, hope it gets finished and added asap.

**Comment by deathbeam** [comment] 2018-09-11 09:37
Duplicate of #1905

**Closed by deathbeam** 2018-09-11 09:37 UTC
Labels: feature-request
