### ISSUE TITLE
Clue scroll show hidey holes

### ISSUE THREAD

**Issue by JorisvanRoy** [runelite/runelite#8355] opened 2019-03-30 16:51 UTC
Whenever you open a clue that requires items to wear it shows if you have it in your inventory. Would it be possible to check if you have built the hidey hole and also put in the items, so you dont bring it twice.

Maybe we can visualize it by having a blue check mark instead of a red/orange/green check mark

**Comment by deathbeam** [comment] 2019-03-30 17:28
Duplicate of #1742

**Closed by deathbeam** 2019-03-30 17:28 UTC
