### ISSUE TITLE
A hotkey to reset game size to values in RuneLite config

### ISSUE THREAD

**Issue by Azebu** [runelite/runelite#11760] opened 2020-05-30 11:43 UTC
Hey, in RuneLite settings I have my game size set to 1280x720. However, for some situations, I drag the window size to make it smaller.
To return to 720p, I have to navigate to the RuneLite configuration tab, and click one of the arrows up and down.

I'd like to request an option to set a hotkey, which will reset window size to the values defined by user.

**Comment by raiyni** [comment] 2020-06-17 05:20
Duplicate of https://github.com/runelite/runelite/issues/4829

**Closed by raiyni** 2020-06-17 05:20 UTC
