### ISSUE TITLE
Multi-Lines

### ISSUE THREAD

**Issue by PerishBtw** [runelite/runelite#11265] opened 2020-04-14 10:04 UTC
Seeing as Deadman mode is coming back, I was wondering if someone could add a graphical overlay that lets you see where multi lines are around Runescape. Added with this idea, I'd like safe zone lines to also be added.

**Comment by Hydrox6** [comment] 2020-04-14 10:06
Banned by the [Jagex Statemet](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1): `Indicates multicombat zone boundaries`

Also, Duplicate of #1764

**Closed by Hydrox6** 2020-04-14 10:06 UTC
