### ISSUE TITLE
Coinpurse notification

### ISSUE THREAD

**Issue by harrisonjraben** [runelite/runelite#8144] opened 2019-03-08 00:17 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

When picking the pockets of Ardy knights i always miss when the coin purses are at their max stack

**Describe the solution you'd like**

A notification system when the stack reaches a number, either locked to ~26 or controllable by the player

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

Cant think of any other system to use

**Additional context**

no any additional context needed

**Comment by Nightfirecat** [comment] 2019-03-08 00:21
Duplicate of #4308

**Closed** 2019-03-08 06:58 UTC
