### ISSUE TITLE
Upload and Download other players Tile Markers

### ISSUE THREAD

**Issue by BoothOSRS** [runelite/runelite#13000] opened 2021-01-01 00:12 UTC
Instead of people having to show via screen share where to put their tile markers, would it not be easier to be able to upload/download your tile markers?

for example zulrah, its not game breaking to know where the safespots are.

**Comment by llamositopia** [comment] 2021-01-01 00:14
This is borderline against the rules that [Jagex lays out here](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1).

> Anything that automatically indicates where to stand, or not to stand. This applies to only automatic indicators, and not tiles which have been manually marked.

Since it's not the active player which is the one marking the tiles, it's probably illegal.

**Comment by Adam-** [comment] 2021-01-01 00:15
The existing tile markers aren't against the rules, so a way to easily share them wouldn't be. If someone can figure out a good ux for this I don't see why it can't be added. Maybe something like the bank tags export/import thing.

**Comment by Hydrox6** [comment] 2021-01-01 00:18
Duplicate of #7853

**Closed by Hydrox6** 2021-01-01 00:18 UTC
