### ISSUE TITLE
Grouping Screen Markers or Adding Skill Icons to the names

### ISSUE THREAD

**Issue by Psyda** [runelite/runelite#4763] opened 2018-08-07 15:21 UTC
**Is your feature request related to a problem? Please describe.**
I find Screen Markers frustrating to navigate. If you have many configurations for different skills and each utilizing multiple markers they blend in making it difficult to use even with specific names.

**Describe the solution you'd like**
I'd propose collapsible groups with skill icons as an idea scenario.

**Describe alternatives you've considered**
A more simple option could be configurable Skill Icons that show beside the names of each marker.

Sidenote: As of right now I don't think you can rearrange markers, maybe they could sort by alphabetical.

**Comment by deathbeam** [comment] 2018-09-07 19:20
Duplicate of #3205

**Closed by deathbeam** 2018-09-07 19:20 UTC
Labels: feature-request
