### ISSUE TITLE
Enhanced RuneLite Notes

### ISSUE THREAD

**Issue by fatassdab** [runelite/runelite#14650] opened 2022-01-30 04:17 UTC
I like to leave a lot of notes in the Notes section of RuneLite, but after awhile it gets pretty cluttered.

It would be nice if there were a way to have personally titled tabs within the Notes section so I could have notes on Farming, Friends, Quests, etc. all separated instead of having one long notepad with everything in one area.

**Comment by Hydrox6** [comment] 2022-01-30 04:32
Duplicate of #5822

**Closed by Hydrox6** 2022-01-30 04:32 UTC
