### ISSUE TITLE
Pet cat plugin

### ISSUE THREAD

**Issue by 984514566554** [runelite/runelite#12114] opened 2020-07-11 15:50 UTC
A complete plugin for your pet cat. 

- Notify whenever your kitten is hungry or needs attention
- Infoboxes with timers till next actions
- Pet kitten growth timer infobox to Cat
- Cat growth timer infobox to Overgrown Cat
- Wily cat reversal timer infobox to Lazy Cat
- Cat hitpoints threshold notification while fighting Hell-rat behemoth/King rat
- Cat training NPCs highlight/indicator
- Configurable Hell-rat behemoth indicator or colored highlight according to the appropriate spice color

**Comment by Nightfirecat** [comment] 2020-07-13 05:18
Duplicate of #3815

**Closed by Nightfirecat** 2020-07-13 05:18 UTC
Labels: duplicate
