### ISSUE TITLE
Idle notifier plugin ability to notify directly on target kill (when it's hp reaches 0)

### ISSUE THREAD

**Issue by Scape070** [runelite/runelite#14523] opened 2021-12-27 00:48 UTC
**Is your feature request related to a problem? Please describe.**
I farm alot of brutal black dragons on my alt, and right now the idle notifier plugin only has the ability to notify you that you are out of combat. However, since these monsters are aggressive and attack from a long distance, I am never out of combat and this leads to me not receiving a notification after kills, as well as taking unnecessary damage/deaths when I have my eyes off the screen for a moment. I cannot use the game sounds themselves to remind me because I have a medical condition (hyperacusis, sensitive hearing) for which I have to play in silence with earmuffs on.

**Describe the solution you'd like**
I would like for the idle notifier plugin to be able to notify me directly upon killing my current target (when it's hp reaches 0). This should come as a separate toggleable checkbox option in the plugin menu and should not interfere with the already existing "out of combat" notifications.

**Describe alternatives you've considered**
There is currently a similar plugin in the plugin hub called "Health Notifier". However, it's outdated and doesn't work in certain situations e.g. bursting, and on monsters that were already below full health to begin with, from being damaged and left by another player.

**Additional context**
n/a

**Comment by Scape070** [comment] 2021-12-27 05:14
I found two similar posts after some digging but the authors weren’t clear. Apologies for not reading the rules thoroughly.

Nonetheless, I hope it can be taken into consideration. As I know many players, including myself, have atleast once sought this feature during their time in OSRS. I think it would be a healthy addition to the already existing idle interaction notifications and would benefit many players. Thank you for your time and all of the amazing work you’ve done for this game, Scape070.

**Comment by Nightfirecat** [comment] 2021-12-27 06:38
Duplicate of #13840

**Closed by Nightfirecat** 2021-12-27 06:38 UTC
Labels: duplicate
