### ISSUE TITLE
NPC kill count in Barrows Crypt

### ISSUE THREAD

**Issue by MattRKing** [runelite/runelite#10948] opened 2020-03-04 10:43 UTC
While doing Barrows I tend to afk it heavily and lose track of what I have killed while in the crypt.  Since I can't remember what I have killed I tend to end up with the wrong reward potential %.  It would be nice if there was an option in the barrows plugin to have a kc tracker for in the crypt.

I was thinking something similar to the slayer task info box.  For example if I have killed 2 skeletons and 1 bloodworm there will be little info boxes which are labelled with the type of monster killed and the amount of them; an image of a skeleton with the number 2 and an image of the bloodworm with the number 1.  Alternatively there could be a little extension to the Barrow's Brothers tracker info box which updates to track what you have killed.  Using the same example before, it may update under the list of Barrow's Brothers and say 'Skeleton: 2' and 'Bloodworm: 1' under it.

If it doesn't take too much effort, this minor plugin would be a huge help in the long run.  Thanks, and keep up the good work guys :)

**Comment by Alexsuperfly** [comment] 2020-03-04 13:54
duplicate of #10439

**Closed** 2020-03-04 17:23 UTC
Labels: duplicate
