### ISSUE TITLE
Additonal infobox for vengeance to show it has been cast but not used: request

### ISSUE THREAD

**Issue by ptfo-rs** [runelite/runelite#4416] opened 2018-07-19 20:50 UTC
Shows that the vengeance spell is active, disappears when the player is hit and the spell is used. Separate infobox from the 30 second timer for when the spell can be cast again. Beneficial when the spell is still active and hasn't been cast in a while so the player doesn't cast the spell when they don't have to.

**Comment by deathbeam** [comment] 2018-07-19 20:51
Duplicate of #3809

**Closed by deathbeam** 2018-07-19 20:51 UTC
