### ISSUE TITLE
GPU Plugin is freezing client/game when trying to enable.

### ISSUE THREAD

**Issue by rangerxxll** [runelite/runelite#6523] opened 2018-11-17 00:04 UTC
How to reproduce: 
1) Open client and let the game load
2) log into game.
3) Open the side menu and enable GPU plugin.
4) Everything freezes.

CPU: Intel Core i7 6700k
GPU: GTX 1060 6GB.

If additional information is required please let me know.

**Comment by MagicfTail** [comment] 2018-11-17 00:05
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration Try this?

**Comment by raiyni** [comment] 2018-11-17 00:06
Turn off compatibility mode if you have it enabled.

**Comment by rangerxxll** [comment] 2018-11-17 01:13
I have done both of the suggestions. None have worked so far.

**Comment by Popedigoz** [comment] 2018-11-17 11:18
I had the same issue.

GPU: GTX 1070 Ti
CPU: i5-6600K @3,5 GHz

Funny thing is, I already had disabled hardware acceleration - or at least I think so, as I've done it for sure.
No idea what could've re-enabled it though.

**Comment by diadras** [comment] 2018-11-18 21:11
I have the same issue, when I turn on GPU mode with far draw distance it draws the far away objects for 1 second, Freezes the game for a bit, then locks up my mouse for a bit and shows 99% GPU usage in task manager, Then frees up my mouse and shows 0% GPU usage in task manager for Runelite. If I then perform actions in the game the game will stay frozen. Then when I disable GPU mode it shows that my actions have been completed and the game works.

CPU: 6700HQ
GPU: 970m

None of the hardware "Disable hardware acceleration" solutions solve the issue

**Comment by diadras** [comment] 2018-11-19 17:19
Mobile GPU [SOLVED}
I noticed that I launch Runelite by default with my intel GPU, When I select my 970m from the context menu the GPU mode works perfectly. My issue has been resolved!!

**Comment by Popedigoz** [comment] 2018-11-19 19:21
> 
> 
> Mobile GPU [SOLVED}
> I noticed that I launch Runelite by default with my Intel GPU, When I select my 970m from the context menu the GPU mode works perfectly. My issue has been resolved!!

How did you launch RL with GPU rather than Intel GPU?

**Comment by AlecPeery** [comment] 2018-11-20 19:52
I also have this bug. 

OS: Windows 10 64bit
GPU: GeForce GTX 980
CPU: Intel Core i5-3570k @3.40GHz
Ram: 16gb
1920x1080, 144Hz

**Comment by deathbeam** [comment] 2018-11-30 09:02
Same issue here, when enabling the GPU plugin canvas "freezes" and disabling it does not help at all.

GPU: Intel UHD 620 (integrated)

**Comment by deathbeam** [comment] 2018-11-30 17:29
So, for me #6578 solved this issue

**Comment by Vexhal** [comment] 2019-01-09 21:10
> compatibility

Windows compatibility troubleshooter set mode as 'Windows 8' and it fixed the problem 🤔

**Comment by sopadimacaco** [comment] 2019-05-23 22:38
i am having this same problem, tried the hardware acceleration but still gpu freezes my runelite. 

 i7 3770K 3.50 Ghz
nvidia geforce gtx 1060 6gb GIGABYTE

what could fiz thix??

**Comment by tangohosts** [comment] 2019-08-03 16:41
I'd like to throw in my 2 cents. I'm in a bit of a weird scenario - Optimus hybrid graphics on a Lenovo Thinkpad w520 - i7 2960XM and a Quadro 2000M DGPU running Manjaro linux  Kernel 5.2.4-1

Bumblebee switchable graphics, works by copying the framebuffer off the cpu gpu to the DGPU actually works fine with Runelite with hardware acceleration off - good performance, actually slightly better than Windows 10. However most other games (like all those launched with steam) and other programs that rely on the DGPU crash with the Bumblebee implementation 

Optimus-Manager based solution - Switches the GPU that runs the Xorg session on the fly, sorta like PRIME mode or just running with the integrated HD3000 graphics disabled - Everything OTHER than Runelite works fine - Runelite Crashes to desktop if I try to turn on GPU plugin and All I see in the log is "Setting hardware acceleration to OPENGL" then the start of the next launch. Sigh. oh well.

**Comment by RyanCopley** [comment] 2020-01-08 17:45
I noticed that I was getting this while I had accidentally installed the 32 bit version of runelite. I reinstalled the 64 bit version and it started working as expected.

**Comment by Marsak3** [comment] 2021-01-10 13:08
> I noticed that I was getting this while I had accidentally installed the 32 bit version of runelite. I reinstalled the 64 bit version and it started working as expected.

This has worked for me, try downloading the 64-bit version.

**Comment by Nightfirecat** [comment] 2022-07-10 04:05
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:05 UTC
Labels: bug, gpu
