### ISSUE TITLE
Quick-hop

### ISSUE THREAD

**Issue by Chayekx** [runelite/runelite#2618] opened 2018-05-11 23:15 UTC
Hello, I would like to have an feature similar to Osbuddy, so you could hop-to friendlist people's world by r-click choose "hop-to", or alternatively by double clicking their name or something. Is this possible to be added ?

**Comment by Adam-** [comment] 2018-05-11 23:17
Duplicate of #1617

**Closed by Adam-** 2018-05-11 23:17 UTC
