### ISSUE TITLE
WASD Camera stuck

### ISSUE THREAD

**Issue by creibsome** [runelite/runelite#6731] opened 2018-11-29 02:46 UTC
**Describe the bug**
WASD camera controls get stuck if released during loading events.

**To Reproduce**
1. Hold down a WASD key
2. Trigger a "loading" event in game (walking to a new area, teleporting to unrendered area, taking a boat, etc)
3. Release the WASD key _during_ the loading event

**Expected behavior**
Screen rotation should stop.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.1
 - Launcher version: 1.5.2

**Comment by deathbeam** [comment] 2018-11-29 12:10
Duplicate of #6548

**Closed by deathbeam** 2018-11-29 12:10 UTC
