### ISSUE TITLE
Poison & Venom Information

### ISSUE THREAD

**Issue by 1RuneKing** [runelite/runelite#4919] opened 2018-08-15 22:03 UTC
Coming from using Konduit, I am used to seeing current information on how much damage I will take per hit of poison, and watch it tick down, knowing if I need to remove it or just wait it out. Similar with venom, and how worried I will need to be.

Currently on RuneLite we only get information on if we are poisoned or venomed, we do not get any information on damage and possibly how long until it hits or changes damage. 

If possible making this information available would definitely be a nice QoL, but it is not a life or death issue.

**Comment by deathbeam** [comment] 2018-08-15 22:03
Duplicate of #1005

**Closed by deathbeam** 2018-08-15 22:03 UTC
