### ISSUE TITLE
1.5.19 Release HD Health Bars 

### ISSUE THREAD

**Issue by NoobsLegit** [runelite/runelite#8479] opened 2019-04-11 15:27 UTC
Love the new health bars! I am using them with the default look, but it would be very nice to be able to have a prayer bar that matches it because the one currently being used is the same as the old health bars. It looks very odd having a big rounded hp bar above your head with a tiny squared prayer bar underneath.

**Comment by Hydrox6** [comment] 2019-04-11 15:28
Duplicate of #8470

**Closed** 2019-04-11 22:48 UTC
Labels: duplicate
