### ISSUE TITLE
#3376 closed as duplicate but linked post is different 

### ISSUE THREAD

**Issue by duracell33** [runelite/runelite#3399] opened 2018-05-28 00:38 UTC
#3376

**Comment by Abextm** [comment] 2018-05-28 00:44
You can reopen #3376 if you want, but its still a duplicate of #3289, they are both about shift not working when loosing focus.

**Closed** 2018-05-28 00:47 UTC
Labels: invalid

**Comment by duracell33** [comment] 2018-05-28 02:03
but im not swaping or losing focus at any point

**Comment by duracell33** [comment] 2018-05-28 02:41
i never had this issue with osbuddy and it seems to be more related to the screen flash, like it only stops registering at the start/end of the flashing

**Comment by Abextm** [comment] 2018-05-28 02:42
If you turn off screen flashing does it stop happening?

**Comment by duracell33** [comment] 2018-05-28 02:53
i had forgot that was in the runelite settings tbh, still happens, noticed same happens when navigating and changing options on the settings tab is that know?

**Comment by Abextm** [comment] 2018-05-28 03:03
Yes, any interaction outside of the gameframe in subject to the bug/lack of feature mentioned in #3289
