### ISSUE TITLE
Plugin sidebar graphical bug

### ISSUE THREAD

**Issue by inslowmotion** [runelite/runelite#13719] opened 2021-06-10 15:41 UTC
While navigating through/using the sidebar plugins, a graphical bug starts to cause them to overlap onto each other and essentially cause the plugin sidebar to be totally unusable. Screenshot will be attached below.

**To Reproduce for Myself**
1. Go to any sidebar plugin
2. Click on and attempt to use any of the sidebar plugins
3. They begin to bug out and overlap onto one another
4. 

**Expected behavior**
I expected the sidebar plugins to work as normal. I have another PC with Runelite installed that doesn't have this issue whatsoever.

**Screenshots**
![Bug1](https://user-images.githubusercontent.com/85694819/121554614-274d8a00-c9c7-11eb-829d-77b91a0363e9.png)
![Bug2](https://user-images.githubusercontent.com/85694819/121554641-2ae11100-c9c7-11eb-83dd-bc9fe440a197.png)
![Bug3](https://user-images.githubusercontent.com/85694819/121554647-2caad480-c9c7-11eb-8177-c5d116516fc5.png)

Alternative links if for some reason the screenshots don't upload:

 https://gyazo.com/a37a30da76c75a9962b12c98ee1120da
https://gyazo.com/24eb4d688c83d14d5a432456b925cccb
https://gyazo.com/6486636b5b045654ea7836ae79529bf9

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.11.2
 - Launcher version: 2.1.7

**Additional context**
This graphical bug happens regardless of doing a complete uninstall and deleting all my RuneLite data folders. Have tried CMD Prompting RL, disabling hardware acceleration, etc to try and solve the issue on my end and I'm just stuck... The bug occurs regardless of which plugin interface I am attempting to use, and gets to the point where if I just mouseover the plugin sidebar at all it just starts bugging out causing graphical overlapping.

**Comment by Hydrox6** [comment] 2021-06-10 15:43
Duplicate of #11727

**Closed by Hydrox6** 2021-06-10 15:43 UTC
