### ISSUE TITLE
Timer to reset exp tracker in a skill that has not been trained in "x" amount of time

### ISSUE THREAD

**Issue by Caia-OSRS** [runelite/runelite#3372] opened 2018-05-27 04:01 UTC
It would be nice to have the skills that you have not gained exp in the past 5 mins for example to be reset automatically. I can see this being useful for resetting skills that you gain random exp in such as agility shortcuts. Hope this makes sense and is not a duplicate issue, I did search before posting :)

**Comment by Alexsuperfly** [comment] 2018-10-07 03:28
duplicate of #1961

**Closed** 2018-10-07 08:10 UTC
Labels: feature-request
