### ISSUE TITLE
Add collection log completion counter

### ISSUE THREAD

**Issue by riabcinskis** [runelite/runelite#12224] opened 2020-07-24 19:20 UTC
Add a command some like '!log' or something like that doesnt matter to check how many items completed in collection log out of total ammount.

Example: 
Command: !log
Response in chat: I have completed 200/1256 collection log items.

(I dont know exactly how many items are in total in collection log, numbers are just for example purposes)

**Comment by Hydrox6** [comment] 2020-07-24 19:21
Duplicate of #9025

**Closed by Hydrox6** 2020-07-24 19:21 UTC
