### ISSUE TITLE
 Only render the dungeon where the player is located

### ISSUE THREAD

**Issue by Millc** [runelite/runelite#8830] opened 2019-05-13 19:53 UTC
Map regions can consist of multiple dungeons (also locations like: Blast Furnace, Random Events etc.) that are being rendered when the GPU plugin is active. It would be nice if only the dungeon that the player is located in, is being rendered. Other dungeons could be completely hidden or fog could appear around the borders of the dungeon where the player is standing in.

Before:
![image](https://user-images.githubusercontent.com/21034060/57649748-4a7b9480-75c9-11e9-8d12-200dec3a2b11.png)

After:
![image](https://user-images.githubusercontent.com/21034060/57649829-7b5bc980-75c9-11e9-9584-6f8ad7a1a5cb.png)

**Comment by Nightfirecat** [comment] 2019-05-13 20:03
Duplicate of #6478, also this is possible for some locations without using the GPU plugin.

**Closed by Nightfirecat** 2019-05-13 20:03 UTC
Labels: duplicate
