### ISSUE TITLE
60 FPS Option Like Runeloader

### ISSUE THREAD

**Issue by cmonguys666** [runelite/runelite#7515] opened 2019-01-23 10:16 UTC
If you know Runeloader, it's a client that it's pretty much garbage but it had an option for 60 fps, when you toggle it your fps would fly to the roof.

It was the only way I could play but now Runeloader is closed, can you guys add this, I know there is already a low detail option on RL but it doesn't do anything, for me at least.

**Comment by Hydrox6** [comment] 2019-01-23 10:20
Duplicate of #6856

**Closed** 2019-01-23 10:21 UTC
Labels: duplicate

**Comment by nlruk** [comment] 2020-04-29 10:51
Was this ever added?
