### ISSUE TITLE
Screenshot Plugin: Upload to custom url with api key

### ISSUE THREAD

**Issue by Temeez** [runelite/runelite#8056] opened 2019-03-01 06:31 UTC
**Is your feature request related to a problem? Please describe.**
You can already upload screenshots to Imgur but it would be nice if I could upload them to any URL with or without API key. The api key would be in the `Authorization` header.

**Describe the solution you'd like**
Add "URL" and "API key" text fields to the screenshot plugin, below the "Upload to imgur" checkbox. If the "URL" field is empty then it would be disabled.

**Describe alternatives you've considered**
Another way to do this would be to change the "Upload to imgur" checkbox into "Upload to URL" and then pre-fill the below URL text field with imgur image upload api url and "API" field would have to be pre-filled with `"Client-ID " + IMGUR_CLIENT_ID`

**Additional context**
Looking at the `uploadScreenshot(File screenshotFile)` this should be very easy to do as it could be re-used with minimal changes.

**Comment by deathbeam** [comment] 2019-03-01 07:14
Duplicate of #2120

**Closed by deathbeam** 2019-03-01 07:14 UTC

**Comment by Temeez** [comment] 2019-03-01 08:00
@deathbeam I disagree. Adding text fields for custom url and api key is not the same as supporting imgur login credentials. My feature request has basically nothing to do with imgur unlike #2120. :stuck_out_tongue: 

In addition I was thinking about doing this as it seems easy enough (and I need it for a cool thing).

**Comment by deathbeam** [comment] 2019-03-01 08:01
Well it achieves same thing, and I dont think uploading to custom url makes sense? because then everything will overwrite everything else

**Comment by Temeez** [comment] 2019-03-01 08:03
> because then everything will overwrite everything else

I'm sorry but I don't understand. If I want to upload screenshots automatically to `https://mycoolpage.com/image/upload` instead of imgur then what does it overwrite?

**Comment by deathbeam** [comment] 2019-03-01 08:08
Oh. Well, I dont think we want to support arbitrary upload endpoints, because every host is different and might require different headers or different request, so that is just dumb.
