### ISSUE TITLE
Rearrangeable XP Trackers

### ISSUE THREAD

**Issue by Zendeco** [runelite/runelite#10469] opened 2019-12-18 04:11 UTC
While I don't mind clearing and restarting trackers for skills, I'd like the ability to rearrange them, either by clicking an up or down arrow beside each skill to move them up or down by 1 space, or possibly drag & drop.

**Comment by dekvall** [comment] 2019-12-18 04:15
Duplicate of #2029

**Closed by dekvall** 2019-12-18 04:15 UTC
