### ISSUE TITLE
Inventory tag item stuck

### ISSUE THREAD

**Issue by 420swagxxx69** [runelite/runelite#7238] opened 2019-01-08 20:40 UTC
When using the inventory tags if you don't assign a group it acts like you are hovering over the item all the time.

https://i.imgur.com/Nsl9Qmd.gifv

**Comment by Hydrox6** [comment] 2019-01-08 20:43
This should be fixed with the release this Thursday

**Comment by Nightfirecat** [comment] 2019-01-08 20:53
That is to say, this is a duplicate of  #5579

**Closed** 2019-01-10 16:07 UTC
