### ISSUE TITLE
Ring of Wealth Loot Tracker

### ISSUE THREAD

**Issue by SpartanSurvivor** [runelite/runelite#10417] opened 2019-12-09 01:25 UTC
Generate a way to track loot collected by things like ring of wealth or bone crusher even if they don't drop on floor, coins-tokul-numulite

Maybe track inventory for adjustments in currency per kill or track exp for adjustments in pray exp per kill(bone-crusher)

Sorry I read over the guidelines but this is my first contribution or use of github ever, hopefully this makes sense.

**Comment by dekvall** [comment] 2019-12-09 01:30
Duplicate of #5077

**Closed by dekvall** 2019-12-09 01:30 UTC
