### ISSUE TITLE
Enter to Chat and WASD camera movement

### ISSUE THREAD

**Issue by AmGxWaVy** [runelite/runelite#2424] opened 2018-05-07 01:18 UTC
OSBuddy implemented a way to use WASD keys to rotate the camera and making a way to type by pressing enter. However, it has issues and sometimes it does not work as designated. It would be nice for some to have this feature in Runelite.

**Comment by deathbeam** [comment] 2018-05-07 12:05
Duplicate of #1008

**Closed by deathbeam** 2018-05-07 12:05 UTC
