### ISSUE TITLE
Superior Slayer Highlight Color

### ISSUE THREAD

**Issue by ConoYPP** [runelite/runelite#12753] opened 2020-11-06 08:13 UTC
Some of the slayer monsters (Abyssal demon) for instance can be tough to tell apart from the other spawns. When not paying full attention, it can be easy to catch the chat notification after the enemy has meandered off. I'd like to be able to select a secondary highlight color for Superior monsters if possible.

**Comment by Hydrox6** [comment] 2020-11-06 08:56
Duplicate of #1960

For the time being, you can highlight the superiors with the NPC Indicators plugin and use a different colour for that. The Slayer highlight system really needs some love; it's very behind what NPC Indicators can do.

**Closed by Hydrox6** 2020-11-06 08:56 UTC
