### ISSUE TITLE
AMDGPU mesa GPU plugin rendering issues on Linux

### ISSUE THREAD

**Issue by Worfhard** [runelite/runelite#6841] opened 2018-12-06 12:57 UTC
Enabling GPU plugin produces incorrect rendering

<img src="https://i.imgur.com/g7t0WPh.png"/>

 - Arch Linux AMD RX 480 OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.0.0-devel (git-3b2ad8b290) and LLVM 8.0.0svn_r348456
 - RuneLite version 1.5.3
 - Launcher version 1.6.1

Logs:
[launcher.log](https://github.com/runelite/runelite/files/2653103/launcher.log)
[application.log](https://github.com/runelite/runelite/files/2653104/application.log)

**Comment by deathbeam** [comment] 2018-12-06 13:15
Can you post output of your `glxinfo`?

**Comment by deathbeam** [comment] 2018-12-06 13:16
Also, what if you try https://github.com/runelite/runelite/pull/6578 (its shot in dark, but I had some trouble with master branch without that PR for no apparent reason, other than probably driver bug).

**Comment by Worfhard** [comment] 2018-12-06 13:20
[glxinfo output.txt](https://github.com/runelite/runelite/files/2653186/glxinfo.output.txt)

**Comment by Worfhard** [comment] 2019-01-13 11:18
Apitrace file(s)
https://drive.google.com/file/d/1t7_LUeRsMsZ99YrXLpGSihznIAUt41QB

**Comment by Worfhard** [comment] 2019-02-22 14:16
This was cause of a bug in LLVM, should be fixed.

**Comment by Worfhard** [comment] 2019-02-22 18:30
Sorry, I was too hasty

**Comment by tom-seewald** [comment] 2019-03-13 01:27
> This was cause of a bug in LLVM, should be fixed.

Can you please provide a link to the LLVM bug report?

**Comment by PureTryOut** [comment] 2019-04-03 12:46
I just started experiencing this issue too, after updating my kernel from 5.0.1 to 5.0.5 (the only thing I can think of that _might_ have an impact on this). 

RuneLite version 1.5.18
Launcher version 1.6.1

```
▶ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.27.0, 5.0.5-gentoo, LLVM 8.0.0) (0x67df)
    Version: 19.0.1
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.27.0, 5.0.5-gentoo, LLVM 8.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.0.1
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.0.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by legofarmer** [comment] 2019-04-11 15:37
Same issue here.

RuneLite Version: 1.5.19
RuneLite Launcher: 1.6.2  

```
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 5.0.6-arch1-1-ARCH, LLVM 8.0.0) (0x67df)
    Version: 19.0.1
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 7689 MB, largest block: 7689 MB
    VBO free aux. memory - total: 8122 MB, largest block: 8122 MB
    Texture free memory - total: 7689 MB, largest block: 7689 MB
    Texture free aux. memory - total: 8122 MB, largest block: 8122 MB
    Renderbuffer free memory - total: 7689 MB, largest block: 7689 MB
    Renderbuffer free aux. memory - total: 8122 MB, largest block: 8122 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 16384 MB
    Currently available dedicated video memory: 7689 MB
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 5.0.6-arch1-1-ARCH, LLVM 8.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.0.1
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.0.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by tom-seewald** [comment] 2019-04-11 19:53
Someone (probably Worfhard) has already filed a mesa bug here: https://bugs.freedesktop.org/show_bug.cgi?id=109370

I have not found any reported bug related to this on LLVM's tracker, I'm not sure if Worfhard was just speculating about the issue residing with LLVM or if they actually confirmed it.

PureTryOut, so this issue does not happen on your machine when you use 4.19.x or 5.0.1?

**Comment by PureTryOut** [comment] 2019-04-11 21:49
Well... It didn't. I'm not sure if that is the reason it started occuring, but it's the only change on my machine that I can recall from that time. I'll install an older kernel tomorrow and test.

**Comment by legofarmer** [comment] 2019-04-12 00:29
I tested with 5.0.1 and mesa 18.3 or something and still had the issue. It is likely llvm. I rolled llvm back to version 7 and had boot issues, I probably have to roll back the llvm libraries back for that to work properly. I'll give it a shot tomorrow and report back too.

**Comment by PureTryOut** [comment] 2019-04-12 10:01
Rolling back the kernel did not fix the issue. However looking at the logs of my package manager, I had an LLVM update around the same time (from 7.0.1 to 8.0.0). So yes it's very likely that this is a LLVM issue.

**Comment by tom-seewald** [comment] 2019-04-12 15:43
If it's definitely a regression from LLVM 7 to 8 then it should probably be reported upstream.
https://bugs.llvm.org/

**Comment by utsukami** [comment] 2019-04-13 11:20
Reverting from LLVM 8.0.0 to 7.0.1 fixed this for me.

**Comment by MESLewis** [comment] 2021-01-13 02:58
Does this happen on the latest release of RuneLite?

**Comment by Adam-** [comment] 2022-02-28 22:34
Very late but this was fixed in https://docs.mesa3d.org/relnotes/19.1.0.html

**Closed by Adam-** 2022-02-28 22:34 UTC
Labels: bug, gpu, not-our-bug
