### ISSUE TITLE
stretched fixed mode won't work correctly

### ISSUE THREAD

**Issue by colebaker25** [runelite/runelite#6549] opened 2018-11-17 21:33 UTC
when i try to increase the client size, it won't work properly. It seems like when it tries to scale, the clicks scale, but the visual screen doesn't.

**Comment by RichardU1995** [comment] 2018-11-17 22:20
I am having the exact same problem right now. I toggled ground items from 'off' to 'on' and suddenly my client is doing this. I have tried toggling all settings back to default and reinstalling the client but still having the same problem. I really hope this is fixed.

**Comment by bregger** [comment] 2018-11-17 22:44
I'm also having the same issue currently. Must have broken in a recent merge.

**Comment by OTRD5k** [comment] 2018-11-18 05:49
Happens for me when GPU plugin is active.

Screenshot demonstrating the problem:
![image](https://user-images.githubusercontent.com/9359529/48669128-d2299000-eacb-11e8-9554-70534e787f92.png)

**Comment by oplosthee** [comment] 2018-11-18 13:00
The GPU plugin does not work with stretched mode as of now. It's mentioned in the GPU FAQ as well: https://github.com/runelite/runelite/wiki/GPU-FAQ#my-stretched-fixed-mode-is-broken. Disable either the GPU plugin or the stretched mode plugin for now.

Also duplicate of https://github.com/runelite/runelite/issues/6487.

**Closed** 2018-11-18 18:00 UTC
