### ISSUE TITLE
Slayer Plugin counts incorrectly when kills happen simultaneously

### ISSUE THREAD

**Issue by TylerNichols** [runelite/runelite#3466] opened 2018-05-29 20:02 UTC
There is a problem where the count of remaining monsters for the given task is wildly off when killing multiple monsters at once. This is most noticeable when bursting a task such as dust devils.

**Comment by TylerNichols** [comment] 2018-05-29 20:11
From looking at SlayerPlugin.java , it looks like we are saying every xp change is one kill. 


To fix this I think we need to know the HP or XP rewarded from a single monster and compare our XP difference to get the count killed. I would be interested in fixing this unless there is blocker that I am not aware of.

**Comment by deathbeam** [comment] 2018-05-29 20:13
Duplicate of #1046

**Closed by deathbeam** 2018-05-29 20:13 UTC
