### ISSUE TITLE
Implement wiki quest plugin into side bar

### ISSUE THREAD

**Issue by velsheda7** [runelite/runelite#4120] opened 2018-07-01 13:41 UTC
Hello Rune Lite :) 

I feel like adding a quest plugin into the sidebar would be very beneficial. That way players could follow along in game in the sidebar without having to switch back and forth between different tabs. Many players I feel would enjoy this feature and would make questing that much more enjoyable and actually encourage players to begin the quest grind journey!

I hope you implement this quest plugin! 

All the best,

Cheers :)

**Comment by deathbeam** [comment] 2018-07-01 13:45
Related or even duplicate of #3038.

**Closed** 2018-07-14 15:34 UTC
Labels: feature-request
