### ISSUE TITLE
Choose how many coins to ignore

### ISSUE THREAD

**Issue by Wonderer4393** [runelite/runelite#8930] opened 2019-05-26 20:43 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...] No

**Describe the solution you'd like**
There is a lot of ground items and I like to clean it up by making it so I cannot see those that I do not want to pick up. Right now there is no way to change it so that way you can choose under how many coins you want to not see.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
I think it would be really cool if there was a way to set it so you could not see coins under a certain amount but see coins on the ground over that amount. Example: creatures like kalphites drop coins in the 5-70 region. Make it so you could set it so you will only see coins on the ground over a certain point that you can change in the settings.

**Additional context**

**Comment by Hydrox6** [comment] 2019-05-26 20:45
Duplicate of #1123

**Closed by Hydrox6** 2019-05-26 20:45 UTC
