### ISSUE TITLE
Combat Calculator in Skill Calculator Interface

### ISSUE THREAD

**Issue by persecom** [runelite/runelite#3118] opened 2018-05-22 20:25 UTC
Please add another option in the skill calculator interface that allows you to calculate what your combat level would be with specific combat skill levels. 

Also, if possible, maybe even an option to retrieve the levels of an account we can specify to make the inputting of levels slightly easier?

I don't know how to add the label 'feature request' myself.

**Comment by deathbeam** [comment] 2018-05-23 15:26
Duplicate of #857

**Closed by deathbeam** 2018-05-23 15:26 UTC
