### ISSUE TITLE
Mage Training Arena - Telekenatic bug

### ISSUE THREAD

**Issue by troypressley1** [runelite/runelite#5587] opened 2018-09-22 16:06 UTC
This has been happening about once every 5 mazes. The spot it says to use Telekinetic Grab on the Maze Guardian doesn't move it. The correct spot would be one block to the east and one block north of my character.

![mage training arena - runelite bug](https://user-images.githubusercontent.com/25185645/45919173-94a7de00-be5f-11e8-8127-d7d6671c81da.png)

**Comment by deathbeam** [comment] 2018-09-22 16:09
Duplicate of #3946

**Closed by deathbeam** 2018-09-22 16:09 UTC
