### ISSUE TITLE
Add special attack tracker for Corp

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1708] opened 2018-04-19 20:57 UTC
OSBuddy has a nice Special Attack tracker for Corp. Would be nice to have that too.
![image](https://user-images.githubusercontent.com/9074448/39017953-fea70638-4424-11e8-87b6-5516f83490b9.png)

**Comment by ypperlig** [comment] 2018-04-19 20:58
Duplicate of #492

**Closed** 2018-04-19 21:02 UTC
