### ISSUE TITLE
Timers Tab

### ISSUE THREAD

**Issue by PeckishDino** [runelite/runelite#6413] opened 2018-11-09 20:56 UTC
In the timers tab, instead of having to click through each button to identify which crops are done, make it so that you can make groups, for example, a new group button and I can add any crops or other timers that aren't already in the same area.

Essentially it's so I can put all my farm runs together, trees/fruit trees, spirit trees, hardwood, herbs, birdhouses etc all together and ignore all the other crops I don't use.

**Comment by deathbeam** [comment] 2018-11-10 10:35
Duplicate of #4834

**Closed by deathbeam** 2018-11-10 10:35 UTC
