### ISSUE TITLE
I'd like to a list of quests I meet the requirements for

### ISSUE THREAD

**Issue by Frostytude** [runelite/runelite#5779] opened 2018-10-03 14:46 UTC
**Is your feature request related to a problem? Please describe.**
Quality of life addition to the client

**Describe the solution you'd like**
A program that checks your stats and then checks what quests are be able to be done.

**Additional features**
Sort by alphabet and/or difficulty
Maybe clicking on a quest to open a guide?

**Comment by deathbeam** [comment] 2018-10-03 14:49
Duplicate of #1905

**Closed by deathbeam** 2018-10-03 14:49 UTC
