### ISSUE TITLE
Add Wilderness Level Icon to Obelisks on world map

### ISSUE THREAD

**Issue by DuhFonzz** [runelite/runelite#4929] opened 2018-08-16 09:18 UTC
Adding icons similar to other teleport locations would help people not as familiar with the wild that are doing clues etc, that have the hard diary done to pick teleport levels.

Like for the pic, there is the rev cave teleport icon, and you see the obelisk there near the clue scroll, but it isn't inherently clear what wild level that is, and thus what obelisk to teleport to. 

Would like an icon similar to the rev cave one just indicating the obelisk level.

![image](https://user-images.githubusercontent.com/39390790/44200076-b5b83900-a113-11e8-9606-160e842a236b.png)

**Comment by deathbeam** [comment] 2018-08-16 14:08
Duplicate of #4216

**Closed by deathbeam** 2018-08-16 14:08 UTC
