### ISSUE TITLE
Can't log in on the client

### ISSUE THREAD

**Issue by R2KUM** [runelite/runelite#5699] opened 2018-09-29 01:44 UTC
**Describe the bug**
When I try to log on, the whole client freezes and then closes. I uninstall the client and re download it, but it keeps doing it. 

**Environment (please complete the following information):**
 - Windows

**Comment by ftbcoders** [comment] 2018-09-29 03:50
Same issue. Windows 64 bit. working on my brothers PC but not mine. Deleted cache, still not working. reinstalled twice.

**Comment by deathbeam** [comment] 2018-09-29 06:16
Duplicate of #5675

**Closed by deathbeam** 2018-09-29 06:16 UTC
