### ISSUE TITLE
Different "profiles" for differnet computers/accounts

### ISSUE THREAD

**Issue by BrendanMesters** [runelite/runelite#11392] opened 2020-04-28 11:32 UTC
I've found that I have to change settings often when I switch from using my PC to my laptop as one feature may be very useful on one but not on the other due to preformance or screen size. I've also found that my loot tracker tracks loot on my RuneLite account and thus doesn't seperate my "loot checker" for my different accounts. could we maybe have some options to setup different profilers that remember your preferences that you can switch between (maybe they could even remember your username in case you want to switch accounts and have a long email) 

p.s. If this Feature Request is in any way not compliant with the way your team does feature requests just let me know and I'll fix it, or delete it :D thanks for making such an awesome client

**Comment by Nightfirecat** [comment] 2020-04-29 03:59
Duplicate of #2220.

See https://github.com/runelite/runelite/wiki/General-Features#playing-with-multiple-accounts for a more manual workaround in the meantime.

**Closed by Nightfirecat** 2020-04-29 03:59 UTC
Labels: duplicate
