### ISSUE TITLE
Ensouled bloodveld head

### ISSUE THREAD

**Issue by troypressley1** [runelite/runelite#1740] opened 2018-04-20 19:02 UTC
The ensouled bloodveld head doesn't show its GE price on the ground or when examining it. The GE searcher also doesn't show the item anywhere. 

It is tradeable and found on the GE at about 4.9K currently.

**Comment by deathbeam** [comment] 2018-04-20 19:03
Duplicate of #1045

**Comment by deathbeam** [comment] 2018-04-20 19:04
For context, the item on ground is actually untradeable for a while due to how the ensouled heads work.

**Closed by deathbeam** 2018-04-20 19:03 UTC
Labels: duplicate
