### ISSUE TITLE
Ground Items highlight/hide priority not behaving as intended.

### ISSUE THREAD

**Issue by Henness0666** [runelite/runelite#16620] opened 2023-05-23 21:31 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

WIndows 11

### Bug description

According to #5768 at the request of #3942, Ground Items was updated to highlight and/or hide items using the following prioritization; `prioritize highlight specific > block specific > highlight wildcards > block wildcards`. This however is not how the items are being prioritized. 

Example 1:
If you highlight all bones using `*Bones` in the `Highlighted Items` section and then ignore regular bones using `Bones` in the `Hiden Items` section. The bones will still be highlighted, completely ignoring the `Hidden Items` list.

In this situation, Bones should be ignored because `block specific` is prioritized higher than `highlight wildcards`,

Example 2:
If you highlight all runes containing more than 9 in a stack using `* rune>9` in the `Highlighted Items` section and then ignore Body runes using `Body runes` in the `Hiden Items` section. The Body runes will still be highlighted, completely ignoring the `Hidden Items` list.

In this situation, Body runes should be ignored because `block specific` is prioritized higher than `highlight wildcards`,

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/3048692/83bfbadc-bc35-4ed5-b915-c4dc074c0817)
![image](https://github.com/runelite/runelite/assets/3048692/4458327e-349b-498e-99c2-0089d103a71c)

![image](https://github.com/runelite/runelite/assets/3048692/788944c5-0512-43c0-adce-7c8f3c3d5a0a)
![image](https://github.com/runelite/runelite/assets/3048692/8ff087a4-6b1c-4168-b8fc-7c28dec59180)

### RuneLite version

RuneLite version: 1.10.0.7
Launcher version: 2.1.5

### Logs

N/A

**Comment by Alexsuperfly** [comment] 2023-05-23 21:42
#5768 wasn't merged so this is just a well worded duplicate of #3942

**Closed** 2023-05-23 21:47 UTC
Labels: duplicate
