### ISSUE TITLE
Completing Lair of Tarn Razorlor incorrectly reduces Slayer task progress

### ISSUE THREAD

**Issue by gonX** [runelite/runelite#12340] opened 2020-08-14 21:10 UTC
**Describe the bug**
When the miniquest Lair of Tarn Razorlor is completed, the Slayer plugin incorrect thinks that you've killed a task monster, supposedly because of the Slayer XP drop.

**To Reproduce**

*prereq*: Not having completed Lair of Tarn Razorlor
1. Ensure you have an active Slayer task
2. Complete miniquest 'Lair of Tarn Razorlor'
3. Slayer task progress indicators now show 1 less than they did before.

**Expected behavior**
Completing the miniquest should not decrease Slayer task progress.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - RuneLite version: 1.6.25-SNAPSHOT (commit 7c19a6c73b)

**Comment by Hydrox6** [comment] 2020-08-14 21:16
Duplicate of #7984

**Closed by Hydrox6** 2020-08-14 21:16 UTC
