### ISSUE TITLE
menu swap the new runecrafting pouch bank fill option with the deposit option?

### ISSUE THREAD

**Issue by GrimyPothead** [runelite/runelite#5685] opened 2018-09-28 11:54 UTC
**Is your feature request related to a problem? Please describe.**                                                                        with the release of the new runecrafting pouch bank fill option it would be nice to have it swapped into the place of the 1st deposit option so we can click once to fill while in bank without having to right click them all individually which is 4+ clicks.

**Describe the solution you'd like**
menu swap new runecraft bank fill option with depost option - maintain functionality with All quantity

**Additional context**
![examplerunelite](https://user-images.githubusercontent.com/43673428/46206974-91d34000-c2da-11e8-9274-2f4d5643b386.png)

**Comment by forsco** [comment] 2018-09-28 12:30
Duplicate of #5668

**Closed** 2018-09-28 20:14 UTC
