### ISSUE TITLE
Calculate the difference between the xp in the skill calculator

### ISSUE THREAD

**Issue by Majst** [runelite/runelite#5875] opened 2018-10-08 03:49 UTC
Could there be another box added to the skill calculator, so when you calculate lets say from 90 to 99, it will show the difference between 99 (13034431) and 90 (5346332) somewhere on the pane? 

Sorry about the poor photoshop but I hope it gives you an idea. 

![image](https://user-images.githubusercontent.com/30551516/46591853-d26d4f00-ca7a-11e8-942e-8bb284b27fb8.png)

**Comment by Alexsuperfly** [comment] 2018-10-08 03:51
duplicate of #4816

**Closed** 2018-10-08 03:51 UTC
