### ISSUE TITLE
Let XP Globe on screen while cursor is hovering it.

### ISSUE THREAD

**Issue by TaxoRubio** [runelite/runelite#2033] opened 2018-04-27 10:45 UTC
Right now, if I want to read the xp information from the globe I see it disappear before finishing reading it. It would be really nice if it could stay on screen while the mouse is still over it.

**Comment by jpabeem** [comment] 2018-04-27 13:42
Duplicate of #1892

**Closed** 2018-04-27 15:41 UTC
Labels: feature-request
