### ISSUE TITLE
I don't want to see random event & the text above them, Entity hider hiding too much

### ISSUE THREAD

**Issue by doxxide** [runelite/runelite#4858] opened 2018-08-11 20:57 UTC
I want to turn off random events. So turn off NPCs right?
Sure, now I don't see the NPC, but I see the messages these NPCs come with. So turn off NPCs 2d right?
Okay, I'm fishing but because 'fishing spot' is considered an NPC 2d, now I can't fish.

I'd like to not see random events and their messages, but I want to see fishing spots. Entity hider solves the random event issue, but then I can't see fishing spots.

Suggestion: Disable random events & their messages while allowing me interact with fishing spots or anything related to that nature. 

Is it too petty of me to not want to see random events & their messages? I like my random events like my bloatware: non existent.

Edit: apparently sounds are still on when they're disabled. Like Evil Bob's random event sounds are annoying af.

**Comment by deathbeam** [comment] 2018-08-11 21:32
Duplicate of #2558

**Closed by deathbeam** 2018-08-11 21:32 UTC

**Comment by doxxide** [comment] 2018-08-11 23:29
random events are the equivalent of bloatware, they may not affect u much but its useless. dismissing them interrupts my actions. so no, its not a worthless sugg


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Tomas Slusny <notifications@github.com> Date: 8/11/18  4:32 PM  (GMT-06:00) To: runelite/runelite <runelite@noreply.github.com> Cc: doxxide <jeberhardt@madisoncollege.edu>, Author <author@noreply.github.com> Subject: Re: [runelite/runelite] I don't want to see random event & the text above them, Entity hider hiding too much (#4858) 
Closed #4858.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/runelite/runelite","title":"runelite/runelite","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/runelite/runelite"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #4858."}],"action":{"name":"View Issue","url":"https://github.com/runelite/runelite/issues/4858#event-1783932464"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/runelite/runelite/issues/4858#event-1783932464",
"url": "https://github.com/runelite/runelite/issues/4858#event-1783932464",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [runelite/runelite] I don't want to see random event \u0026 the text above them, Entity hider hiding too much (#4858)",
"sections": [
{
"text": "",
"activityTitle": "**Tomas Slusny**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@deathbeam",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/runelite/runelite/issues/4858#event-1783932464"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 367344269\n}"
}
],
"themeColor": "26292E"
}
]
