### ISSUE TITLE
Adjust camera pan speed when using arrow keys

### ISSUE THREAD

**Issue by Ballistikk** [runelite/runelite#11338] opened 2020-04-21 23:28 UTC
**Is your feature request related to a problem? Please describe.**
I'm used to using the arrow keys/WASD to rotate/pan the camera around my character. That being said, I've always felt like the pan speed is too slow and would like to have an option to increase it.

**Describe the solution you'd like**
I, and I'm sure many others too, would like there to be an option to change the speed at which the camera pans/rotates around your character when using the arrow keys (or any button they're mapped to), under the Camera plugin.

**Describe alternatives you've considered**
 I'm aware that the camera can be panned/rotated using the middle mouse button, but I've always preferred using keyboard keys.

**Additional context**
There already is a "zoom speed" parameter under the Camera plugin, so a "pan speed" one doesn't seem like it would be too difficult to implement. Thanks!

**Comment by Hydrox6** [comment] 2021-02-02 16:54
Duplicate of #7744

**Closed by Hydrox6** 2021-02-02 16:54 UTC
Labels: feature-request
