### ISSUE TITLE
Nmz 

### ISSUE THREAD

**Issue by palister** [runelite/runelite#4008] opened 2018-06-25 13:47 UTC
So when runeloader was still alive, I can say it was the best nmz client that I have used because of its features. I was wondering can runelite integrate the same? 
The overload and prayer notifications sound is just not loud enough. Osbuddy, konduit and runelite all use windows notifications which just isn’t loud. Runeloader has a loud beep when prayer points reached 3 different levels. And overload potion when worn off it will make another sound. But runelite is just windows notifications which again isn’t loud. Can a developer add this? 

Loud beep for prayer points has reached 3 different levels defined By user. Like beep at 30, beep at 20 and beep at 10? And another loud sound for overloads?

**Comment by deathbeam** [comment] 2018-06-25 15:19
You can modify windows notification sounds. Also, there is already open issue for custom notification sounds, so this is mostly duplicate of that.

**Closed by deathbeam** 2018-06-25 15:19 UTC
