### ISSUE TITLE
XP Globes show inaccurate timer for Agility

### ISSUE THREAD

**Issue by clebauer** [runelite/runelite#16059] opened 2022-12-22 16:47 UTC
### Type

Incorrect behavior

### Operating System

None

### OS Version

MacOS Monterey

### Bug description

Needing 21 more laps, the calculator says it should only take me 2m13s left.
I've done nothing else since logging in other than than 9 laps recorded, so no other activities are influencing the XP per hour.

(My guess: could it possibly be taking the xp related to the large xp drop at the end of completing the course and multiplying THAT by the number of actions taken, rather than the rolling average? that would explain why it thinks i'm making XP BANK rather than just 240 a lap)

Currently at Canifis.

### Screenshots or videos

<img width="1409" alt="Screen Shot 2022-12-22 at 11 42 59 AM" src="https://user-images.githubusercontent.com/31354379/209183767-cf82da2a-ba44-46cc-9c56-11f9bc08dbb0.png">
(photo at 11:42AM)

**Comment by clebauer** [comment] 2022-12-22 16:52
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/31354379/209185977-75812293-724b-4096-8cae-6cb0de4c3432.png">

updated photo as I go.

**Comment by Alexsuperfly** [comment] 2022-12-22 16:53
duplicate of #10099 most likely

**Comment by Nightfirecat** [comment] 2022-12-22 17:01
Agreed, looks like #10099 strikes again.

**Closed by Nightfirecat** 2022-12-22 17:01 UTC
Labels: duplicate
