### ISSUE TITLE
Loot Tracker Not Saving Loot Between Sessions

### ISSUE THREAD

**Issue by Kspaeth93** [runelite/runelite#7588] opened 2019-01-27 23:53 UTC
**Describe the bug**
Despite being logged into RuneLite using a Google account, enabling Loot Tracker and enabling saving of loot between sessions, loot is not saved when closing and restarting the RuneLite client.

**To Reproduce**
1. Open RuneLite and login to the client using a Google account.
2. Enable Loot Tracker widget and enable saving of loot between sessions.
3. Log into a RS account. Kill something. Verify that loot has been tracked in the loot tracker.
4. Logout of RS account. Close and then restart RuneLite client.
5. Verify that previously tracked loot has disappeared and is no longer saved/loaded.
6. (Optional) Log into RS account. Kill same monster. Verify that loot has been tracked in the loot tracker, but no previous loot data is aggregated.

**Expected behavior**
When enabling Loot Tracker and enabling saving of loot between sessions (and when logged into RuneLite client with a Google Account) loot that is tracked in the loot tracker is saved and re-loaded automatically between client sessions.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 (64-bit)
 - RuneLite version: RuneLite 1.5.9 (32-bit)
 - Launcher version: 1.6.0

**Additional context**
- Java Version: Java(TM) SE Runtime Environment (build 1.8.0_201-b09)

**Comment by Hydrox6** [comment] 2019-01-27 23:54
Duplicate of #7579

**Closed** 2019-01-28 00:48 UTC
