### ISSUE TITLE
Can't get past 0% on Runelite launcher

### ISSUE THREAD

**Issue by korolex1** [runelite/runelite#2281] opened 2018-05-03 07:34 UTC
Tried everything to do with changing internet dns, restarting, redownloading etc.. Something about error in bootstrapping, Here are the logs
[launcher.log](https://github.com/runelite/runelite/files/1969943/launcher.log)

**Comment by bloodma** [comment] 2018-05-03 08:01
Also experiencing this issue, tried uninstalling and reinstalling, resetting my router and computer, standard osrs launcher works fine. 

[launcher.log](https://github.com/runelite/runelite/files/1970024/launcher.log)

**Comment by deathbeam** [comment] 2018-05-03 08:14
Duplicate of https://github.com/runelite/launcher/issues/18

**Closed by deathbeam** 2018-05-03 08:14 UTC
Labels: duplicate

**Comment by korolex1** [comment] 2018-05-03 08:41
@deathbeam literally no response on that one in 2 days but this one gets a response in 20mins?
