### ISSUE TITLE
Extra Chat Messages from Boss/Slayer Log opening

### ISSUE THREAD

**Issue by Gjgarr** [runelite/runelite#13390] opened 2021-03-26 21:20 UTC
**Overview of the Issue**
Checking the Boss Log or Slayer Log causes some debugging messages to appear in the chatbox.

**Reproduce the Error**
1. Check Log option of Slayer helmet from Worn Equipment tab, or Ring of Wealth Boss Log, or either from Adventurer's Log
2. Observe debugging chat messages

![image](https://user-images.githubusercontent.com/12751399/112690070-2d60af80-8e49-11eb-98ab-126874af14d4.png)
![image](https://user-images.githubusercontent.com/12751399/112690121-45383380-8e49-11eb-8868-07c3a0ce7933.png)

**Comment by Hydrox6** [comment] 2021-03-26 21:21
Duplicate of #13385

**Closed by Hydrox6** 2021-03-26 21:21 UTC
