### ISSUE TITLE
Missing Beginner Cryptic clue info

### ISSUE THREAD

**Issue by DanGM96** [runelite/runelite#9022] opened 2019-06-04 17:45 UTC
> Buried beneath the ground, who knows where it's found.
> Lucky for you, A man called Reldo may have a clue.
https://oldschool.runescape.wiki/w/Treasure_Trails/Guide/Cryptic_clues/Beginner

Just got this clue and there is no tips for it. Checked here:
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

**Comment by Hydrox6** [comment] 2019-06-04 17:47
That's because it's not a Cryptic Clue, but a Hot/Cold clue. Beginners are currently not supported, but PR #8974 should fix that

**Comment by xDemoN** [comment] 2019-06-04 17:50
You could call this a duplicate of #8504

**Closed** 2019-06-04 17:52 UTC
Labels: clues, duplicate
