### ISSUE TITLE
Combine the 'Loot Tracker' & the 'Supplies Used Tracker' and call it a 'Profit -plugin'

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#13821] opened 2021-07-01 19:21 UTC
**Suggestion/Feature Request:** Merge the '**Supplies Used Tracker**' and the '**Loot Tracker**', so we can see how much **actual** profit we actually make, without having to calculate that by ourselves.

It should also count the Blowpipe's Zulrah Scales used, darts used (and with assembler only kept/saved darts and without vice-versa), **in example**.
Basically **any** gp you **lose** vs. gp you **gain**. _Actual profit tracker_.

**E:** Forgot to mention, '**Loot Tracker**' side should also have the ability to toggle loot you only pick up, meaning if you leave it on the ground it won't be counted as 'loot'. A tick box under the plugin, yes.

**Comment by Hydrox6** [comment] 2021-07-02 11:18
The loot tracker's job is to track loot, which is does. The supplies tracker is a hub plugin, and has nothing to do with RL core.

What you're asking for is essentially an addition to supplies tracker, so I'd recommend you ask them to make a profit mode or something.

Duplicate of #10245

**Closed by Hydrox6** 2021-07-02 11:18 UTC
