### ISSUE TITLE
Cant relaunch game after closing it

### ISSUE THREAD

**Issue by chillbears** [runelite/runelite#6996] opened 2018-12-17 16:37 UTC
When I start my computer, I'm able to launch runelite perfectly fine. There are no bugs and very little delays in launching. The issue comes in when I close the programme, and then try to reopen it. It then get stuck on some part of the launching proccess such as the prepared sound engine or connecting to update server section of the launch. However, if I restart my laptop and try to launch runelite, it works as per normal. Is there something I'm doing wrong or something I can do to fix it?

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45945886/50100242-f14a4780-025a-11e9-970b-9f7c92223ad8.png)

**Environment (please complete the following information):**
 - OS: Windows 8
 - RuneLite version: 1.5.4
 - Launcher version:1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
[logs.zip](https://github.com/runelite/runelite/files/2686975/logs.zip)

**Comment by deathbeam** [comment] 2018-12-18 16:57
With GPU plugin? If yes we already have issue open for this

**Comment by deathbeam** [comment] 2018-12-19 12:15
Probably duplicate of #6646 (and no reply, so, yeah no point in having this open)

**Closed by deathbeam** 2018-12-19 12:15 UTC
Labels: needs-information
