### ISSUE TITLE
Swap 1 to all on an item when within trade

### ISSUE THREAD

**Issue by Wiedersehen** [runelite/runelite#8870] opened 2019-05-18 16:17 UTC
else if (option.equals("offer") && target.equals("raw shark")){
            swap("offer-all",option, target, true);
        }

Just an example what i'm trying to say, can be done using shift

**Comment by deathbeam** [comment] 2019-05-18 16:34
Duplicate of #8859

**Closed by deathbeam** 2019-05-18 16:34 UTC
