### ISSUE TITLE
Menu Entry Swapper option for Rock Cake

### ISSUE THREAD

**Issue by holyzucchini** [runelite/runelite#12985] opened 2020-12-28 15:36 UTC
Would it be possible to add the Guzzle option of the Rock Cake to the Menu Entry Swapper plugin?
 This could make thing like NMZ easier instead of having to right click everytime. 

![2020-12-28 (2)_LI](https://user-images.githubusercontent.com/76696637/103225472-a7f55e00-4932-11eb-8403-f8dd98ba879b.jpg)

**Comment by bluelightzero** [comment] 2020-12-28 15:39
For the time being, you could use Shift-click with customisable shift-click.

**Comment by Hydrox6** [comment] 2020-12-28 15:41
Duplicate of #1860

**Comment by Adam-** [comment] 2020-12-28 15:42
This is so commonly requested I'd be okay if someone just added it. It's like 5 lines.

**Closed by Hydrox6** 2020-12-28 15:41 UTC

**Comment by holyzucchini** [comment] 2020-12-28 15:42
yea my first time on this github didnt see it was posted before
