### ISSUE TITLE
Grouping of screen makers

### ISSUE THREAD

**Issue by Gamingtank** [runelite/runelite#12573] opened 2020-09-30 14:10 UTC
I think that screen makers are great but one annoying thing about them is having to turn all individually. So could there be a way to group them up so its one-click turn on and off, for example, I use screen makers for BF but I think it should be able to group them up so I can just click once and I'm ready for BF or whatever other content I choose to have screen markers for.

**Comment by Hydrox6** [comment] 2020-09-30 14:12
Duplicate of #3205

**Closed by Hydrox6** 2020-09-30 14:12 UTC
