### ISSUE TITLE
Improvement for the ground markers plugin 

### ISSUE THREAD

**Issue by GreasyLips** [runelite/runelite#6965] opened 2018-12-15 16:31 UTC
Request: The ability to have each marker numbered numerically when placing them. So each tile would have a number above them such as 1-4 depending on the order of the tiles placed

**Describe the solution you'd like**
Just implement it as an option within the ground markers settings so anyone can disable/enable it.

It would be extremely useful for a lot of pvm content

**Comment by Nightfirecat** [comment] 2018-12-15 17:11
This is a duplicate of #1989

**Closed** 2018-12-15 23:12 UTC
