### ISSUE TITLE
Quest Guide

### ISSUE THREAD

**Issue by tanneruwu** [runelite/runelite#9751] opened 2019-08-27 20:50 UTC
What if we had an in-game quest guide such as the clue guide is except for questing.

We've already got all the quests planned out with instructions on the wiki, but I think it'd be a good QoL to have the overlay on runelite so we don't have to flip back and forth from rs to wiki if you're playing on single monitor.

I'm not too sure how easy it would be to code but I assume it'd be similar to how clues and agility work with telling you where to click/move to, except with how clues tell you on the minimap to click on the cluescroll in order to see where the location is it could be super similar.

If anyone can provide any additional ideas for this I would greatly appreciate it as i'm not too fond of thinks like this :)

**Comment by Hydrox6** [comment] 2019-08-27 21:43
Duplicate of #5042

**Closed by Hydrox6** 2019-08-27 21:43 UTC
