### ISSUE TITLE
Minor issue with farming interface

### ISSUE THREAD

**Issue by Fuzzmonkey14** [runelite/runelite#15814] opened 2022-10-17 14:09 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Minor issue with the side bar interface. 
Client shows a green "Ready" for special patches, when I've never planted a special patch at all? 
Not sure if it's intended, but misleading to very the least. 

### Screenshots or videos

[https://gyazo.com/2d31651c7ce78c82f3ba04a3ea61d5b1](url) 
[https://gyazo.com/1fc9e7e8f8aff180064027752c70837a](url)

### RuneLite version

Runelite 1.9.1
Launcher 2.4.2

### Logs

[launcher.log](https://github.com/runelite/runelite/files/9801308/launcher.log)
[client.log](https://github.com/runelite/runelite/files/9801309/client.log)

**Comment by Nightfirecat** [comment] 2022-10-17 15:22
Duplicate of #13006

**Closed by Nightfirecat** 2022-10-17 15:22 UTC
Labels: duplicate
