### ISSUE TITLE
Client position not remembered.

### ISSUE THREAD

**Issue by TX-J-Cor** [runelite/runelite#12809] opened 2020-11-17 10:29 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Client position isn't remembered when opening Runelite

**To Reproduce**
Open and close client

**Expected behavior**
I keep Runelite on the left hand side of my screen and when I open the client it centers itself but it remembers the size I left the client at.

**Screenshots**
![Screenshot (9)](https://user-images.githubusercontent.com/74596695/99378469-130c3900-288d-11eb-82b7-9ede4309419d.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Hydrox6** [comment] 2020-11-17 10:31
Duplicate of #12308

**Closed by Hydrox6** 2020-11-17 10:31 UTC
