### ISSUE TITLE
GPU causing flicking floor tiles and character models.

### ISSUE THREAD

**Issue by Bonesanblood** [runelite/runelite#6556] opened 2018-11-18 06:31 UTC
![2018-11-18_01-23-41](https://user-images.githubusercontent.com/39714241/48669383-94c80100-ead1-11e8-9f8c-de13f65f4127.png)

**Comment by Bonesanblood** [comment] 2018-11-18 06:32
![2018-11-18_01-27-18](https://user-images.githubusercontent.com/39714241/48669396-c0e38200-ead1-11e8-9d87-7ae7bc680ad8.png)

**Comment by deathbeam** [comment] 2018-11-18 18:01
What GPU do you have?

**Comment by Bonesanblood** [comment] 2018-11-18 19:47
AMD Radeon HD 7500 Series

**Comment by deathbeam** [comment] 2018-11-18 22:19
I think this is duplicate of #6491

**Closed by deathbeam** 2018-11-18 22:19 UTC
Labels: bug, gpu
