### ISSUE TITLE
Bank plugins not working

### ISSUE THREAD

**Issue by Exquze** [runelite/runelite#11586] opened 2020-05-14 12:28 UTC
After the last Runelite update i've noticed some issues with plugins regarding the bank. First the bank tags: The box is checked but there aren't any tabs to the left and when right-clicking an item the option to add tags is also gone.

In the Bank plugin only "keyboard bankpin" works out of the 5 plugins i'm using. Show GE/HA/Seed prices and bank value don't work.

The icon for depositing worn items is also a bit weird.

Tried enabling/disabling, restarting the client but it didn't do anything. 

![Bank Tags](https://user-images.githubusercontent.com/56490005/81934227-e5e58200-95ee-11ea-9a8d-70e2476afb64.png)
![Seed](https://user-images.githubusercontent.com/56490005/81934269-f990e880-95ee-11ea-8cf1-b65dc33a9de6.png)

**Comment by Hydrox6** [comment] 2020-05-14 12:29
Duplicate of #11585

**Closed by Hydrox6** 2020-05-14 12:29 UTC
Labels: duplicate
