### ISSUE TITLE
Prevent opening impling jars with clue scroll in inventory

### ISSUE THREAD

**Issue by SemicolonStruggles** [runelite/runelite#12811] opened 2020-11-17 21:24 UTC
Whenever I'm doing medium clue scrolls I open a lot of eclectic impling jars to get the clues. However I somehow always manage to waste an impling or two when I just received a clue but still automatically click the next jar.

It would be awesome if runelite would have an option to prevent the opening of impling jars that give clue scrolls if the player already has a clue scroll in their inventory (Maybe automatically set the left click option to 'use'?)

Of course there would be limitations to this. Since you can open multiple implings per tick it will not be possible to prevent impling from being wasted in the same tick. However, when opening single implings per tick this feature would save a lot of imps from being wasted when doing clue scroll as a consistent money maker.

**Comment by Hydrox6** [comment] 2020-11-17 21:58
Duplicate of #9351

**Closed by Hydrox6** 2020-11-17 21:58 UTC
