### ISSUE TITLE
Custom Cursor Scaling/Resizing

### ISSUE THREAD

**Issue by kwilt** [runelite/runelite#11717] opened 2020-05-27 20:47 UTC
When playing on a 1440p monitor, the custom cursor plugin makes the cursor too small in my opinion. If there's a way to program cursor resizing/scaling, that would be a great addition to the plugin.

**Comment by Nightfirecat** [comment] 2020-05-27 20:52
Duplicate of #8782

**Closed by Nightfirecat** 2020-05-27 20:52 UTC
Labels: duplicate
