### ISSUE TITLE
GPU Plugin Graphical Glitches and Low FPS 50% of the time, high FPS and Working 50% of the time

### ISSUE THREAD

**Issue by RahilSagarwala** [runelite/runelite#11213] opened 2020-04-07 08:12 UTC
I am trying to find the issue, however this is very random and hard to pinpoint. 

PC: Lenovo Y510P Gaming Laptop
OS: Windows 8.1 64-bit
GPU: Nvidia GT 750M
RAM: 8GB
VRAM: 2GB
CPU: Intel(R) HD Graphics 4600
RuneLite: 1.6.10.1

Here are the problems I have faced:
1) The FPS can start at 9, significantly lag, Jump to around 25, fluctuate more, and then the process stops responding. This occurs when GPU plugin is already on but also when turning it on.
2) Mostly upon turning the GPU plugin on, there are extreme graphical glitches. Sometimes rainbow colored strobe effects, other times distorted characters and environments.
3) The game runs perfectly at 50 FPS sometimes when the GPU plugin is already on and sometimes when turned on after not having it on.
4) When the game is at 50 FPS and I go to a new area (mostly caves and enclosed spaces), the FPS drops to 25-40 with no way of bringing it back up.

Things I have tried (already referred to the GPU FAQ):
1. GPU Nvidia Gaming Ready Driver Versions 417.01 and  425.31. These are a year apart 2018 and 2019. There are roughly 12 more drivers in between that I have not tried.
2) Disabling hardware acceleration using both methods
3) Adding RuneLite to the Nvidia Control Panel's 3D Settings and setting it to use the GPU
4) Enabled and disabled Windows 8.1 Compatibility
5) Looking for the supposed process to be killed in the task manager (jogamp_exe_tst). I was not able to find this process at all.
6) Keeping CPU and GPU Temps down though use of multiple fans
7) Restarting RuneLite 10+ times in order to get GPU plugin to work, and repeating after around 10-30 minutes when the FPS drops

[client.log](https://github.com/runelite/runelite/files/4442786/client.log)
[launcher.log](https://github.com/runelite/runelite/files/4442787/launcher.log)

EDIT: Found possible issue. The end of the client log specifies the task that must be killed (jogamp). I cannot find this however in the task manager when I click the small arrow on the RuneLite task when the client is open and the GPU plugin is on.

EDIT2: Seems to be an ongoing issue: https://github.com/runelite/runelite/issues/9889
Support on this would be great so some us don't have to spend $750+ on a new computer when the current one is quite capable. Please do get back to me, thank you.

**Comment by xandyman999** [comment] 2020-04-08 07:05
Compare fps dips with changes in your cpu clock speed as well as temperatures.

Sounds like your gpu is attempting to be in adaptive mode where large open spaces without much to render work fine, but areas with lots of textures are too much to handle, especially from a reduced use state. You need to go from  say 50% use to 75% before you can finally get up to 100%.  Turning on and off the plugin causing you to go from near 0 to whatever you % you need to render requires. 

You should consider reducing render draw distance, def turn off sky box and fog, animation smoothing, as well as turning on low memory. 

You could try running gpu in max performance, in power options use max performance, but this will likely result in overheating maybe even eventual throttling. 

Should def repaste your cpu and gpu with thermal grizzly if you go down that route. 

Playing while laptop is plugged helps tons vs. unplugged. If your laptop is older, replacing battery might help as it might not be as effective. Check it using PowerCfg command. Reducing client size is also extremely useful. The game is designed to only require fixed mode, if you play full screen, consider scaling back your client with to only being 1.5x the aspect ratio of fixed. At first it might feel weird, but it makes it much easier to Netflix and scape.

**Comment by RahilSagarwala** [comment] 2020-04-08 17:05
I am 99% sure I know what the issue is based off of the logs. It is jogamp exe pertaining to Open GL. I cannot even find it in the task manager as many people say where it is found. The GPU FAQ says to end the process twice. 

For reference, OSBuddy's OpenGL plugin works flawlessly at 50FPS and rarely drops to maybe 45FPS with all the more advanced graphics options enabled (even disabling low detail mode). 

In terms of temps, I've been at 50FPS at higher temp. Meaning for example if both my GPU and CPU is at 83C, I can get 50FPS but it drops even if the temp is maybe 75C. It is sporadic in that sense. I have a fan underneath the laptop and an external fan blowing into the areas that feel warm. 

I turned off skybox, fog, animation, and put the client into low detail mode. My laptop is set to high performance mode. As for draw distance, I bring it down all the way to 0 and slowly increase. Sometimes it fixes but it seems abnormal that FPS also drops when the drop distance is only at about 10 which is right when the character renders and very few objects.

My laptop is plugged in. Yes battery is old, I have not gotten around to purchasing a new one. One thing to note is that I am playing on a 55 in. TV. This issue occurs both when connected to the TV and just on the laptop. I would rather play full screen.

**Comment by j-c-o-n** [comment] 2020-04-10 21:24
I'm having this problem as well, same PC.

**Comment by Nightfirecat** [comment] 2020-04-16 16:54
Related to/duplicate of #9889

**Closed by Nightfirecat** 2020-04-16 16:54 UTC
Labels: duplicate
