### ISSUE TITLE
Reorder Farming timers 

### ISSUE THREAD

**Issue by OilyHands** [runelite/runelite#11887] opened 2020-06-12 20:49 UTC
**Describe the solution you'd like**
Similar to [today's update](https://runelite.net/blog/show/2020-06-12-1.6.19-Release/) allowing rearrangement of xp trackers

**Comment by Nightfirecat** [comment] 2020-06-14 08:03
Duplicate of #3056

**Closed by Nightfirecat** 2020-06-14 08:03 UTC
Labels: duplicate
