### ISSUE TITLE
Request: Ligtbox solver

### ISSUE THREAD

**Issue by weebvirgin** [runelite/runelite#3291] opened 2018-05-25 11:44 UTC
Hello. Is this possible to make something like this: https://osrs-lightbox-solver.fletom.com/ ?
I don't know anything about coding and if it's possible. But it would be nice to have something like that site inside the client, so instead of manualy typing which lights are on on the site, the client would recognize it itself and give you a solution.

**Comment by deathbeam** [comment] 2018-05-25 11:50
Duplicate of #1826

**Closed by deathbeam** 2018-05-25 11:50 UTC
