### ISSUE TITLE
Impling overlay randomly breaks

### ISSUE THREAD

**Issue by orlp** [runelite/runelite#4940] opened 2018-08-16 15:55 UTC
The impling overlay sometimes does not work for a specific impling. For example I have the impling overlay enabled and nature implings enabled yet the impling is not highlighted:

https://i.imgur.com/Mzjkfxo.png

I'm playing on Windows 7 with the latest runelite version, 1.4.12.

EDIT: I also just noticed that there are sometimes dots on the minimap not corresponding to anything. They do move as I move - perhaps the minimap is centered on the wrong location?  https://i.imgur.com/qWEU0Uf.png

EDIT2: further findings, newly spawned imps are 'broken' nearly always, even if I add their name into the highlight tag filter. If I then also manually tag them it works, but strangely enough only if I tag them *twice*.

**Comment by Adam-** [comment] 2019-07-12 15:59
duplicate of #3533, which was just fixed

**Closed by Adam-** 2019-07-12 15:59 UTC
Labels: bug
