### ISSUE TITLE
Recording the last bought/sold price of an item in GE

### ISSUE THREAD

**Issue by Asymons** [runelite/runelite#5018] opened 2018-08-20 04:06 UTC
Looking to add another feature into GE where it records your last purchase price and last sold price. This can also be timestamped.

This helps flippers when they're price checking items manually and will eliminate steps in either recording on a notepad or look up the GE history (which has limited history slots).

**Comment by Abextm** [comment] 2018-08-20 04:08
Duplicate of #1767

**Closed by Abextm** 2018-08-20 04:08 UTC
