### ISSUE TITLE
Idle logout timer is not correctly adjusted for combat

### ISSUE THREAD

**Issue by Snitt** [runelite/runelite#4669] opened 2018-08-03 11:12 UTC
**Describe the bug**
Currently the idle timer will notify you that you will log out due to being idle for too long whilst you're in combat which that won't actually kick you out from unlike other activities.

The main issue with this is that when AFK splashing, you will get many false alerts to say you will be logged out for idling. 

**To Reproduce**
1. Get full splash gear 
2. Go AFK splashing and don't interact with the game for 5 minutes
3. Ignore all alerts for idle activity logout. Your account won't be logged out despite the alerts saying you will.

**Expected behavior**
The idle logout alert doesn't apply to combat scenarios until reaching the combat idle timeout. I'm unsure what this number is but i think it might be hours if something is attacking you constantly.

**Environment (please complete the following information):**
 - OS: Experienced in Windows 10 and mac
 - RuneLite version: Current
 - Launcher version: Current
Not applicable as this is a logic error but including it for consistency.

**Additional context**
Combat idling is dealt with differently to idling with other tasks in Runescape. Note the following scenario:
If you are splashing on a spider, after around 10 - 15 mins your account will stop attacking the spider but the spider will continue to attack you. I'm unsure if RuneLite picks up on this combat being broken and alerts properly.
If the spider were to stop attacking you (If somebody else attacked it whilst it was hitting you and you weren't hitting it back) then your account would instantly be logged out if past the regular 5 minute idle logout timer.

I don't know how long you can stay logged in for when being attacked back even if you're not attacking it but i think it's in the hours. Possibly even 6 hours.

**Comment by deathbeam** [comment] 2018-08-05 09:58
Duplicate of #925

**Closed by deathbeam** 2018-08-05 09:58 UTC
