### ISSUE TITLE
Whitelist NPC names for Entity hider

### ISSUE THREAD

**Issue by aekramer** [runelite/runelite#14605] opened 2022-01-17 22:00 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A text field, where you could provide NPC names (seperated by comma) that would not be hidden by the Entity hider.

**Describe alternatives you've considered**
Writing my own 3rd party plugin for the plugin hub?

**Additional context**
At the moment, if you enable Entity hider (NPCs) all NPCs will be hidden, but occasionally you will require access to only a single one, for example:
While at Ourania altar, you require access to "Eniola" the banker, however you are still swamped by other peoples random events, and the annoying chaos druids near the ladder, it would be great to be able to hide these but still have access to Eniola.

**Comment by Adam-** [comment] 2022-01-17 22:01
This is considered "unfair" by Jagex since people use it for nylo room at raids - so we're not supposed to add it.

**Comment by Hydrox6** [comment] 2022-01-17 22:03
Duplicate of #6854

**Closed by Hydrox6** 2022-01-17 22:03 UTC

**Comment by aekramer** [comment] 2022-01-18 00:40
> This is considered "unfair" by Jagex since people use it for nylo room at raids - so we're not supposed to add it.

I see, what about hardcoded options? For example for Eniola, or if anything an option to hide random events, those frogs swarming us is just annoying lol
