### ISSUE TITLE
Inaccurate GE prices 

### ISSUE THREAD

**Issue by kg-89** [runelite/runelite#3955] opened 2018-06-22 18:47 UTC
Items with ornament kits only display the price of the ornament kit, when they should add the value of the ornament kit plus the item. 

Here is an example: 
https://i.imgur.com/L3bDBvh.png

**Comment by deathbeam** [comment] 2018-06-22 18:49
Duplicate of #3909

**Closed by deathbeam** 2018-06-22 18:49 UTC
