### ISSUE TITLE
Runelite crashes unexpectedly on mouse button input

### ISSUE THREAD

**Issue by mfboulos** [runelite/runelite#16616] opened 2023-05-23 07:03 UTC
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Runelite has crashed twice today unexpectedly. The most I can gather is that it seems to happen on mouse inputs. No other major interface changes happened either time. One was at turoths on a right click, and the other was at the GE on a yellow left click. I don't have enough info about this to reproduce it effectively, but hopefully the crash logs can illuminate on the issue

### RuneLite version

Runelite version: 1.10.0.7
Launcher version: 2.6.2

### Logs

[jvm_crash_pid_34124.log](https://github.com/runelite/runelite/files/11540521/jvm_crash_pid_34124.log)
[jvm_crash_pid_39496.log](https://github.com/runelite/runelite/files/11540522/jvm_crash_pid_39496.log)

**Comment by mfboulos** [comment] 2023-05-24 05:03
Update: I'm beginning to think it may be a hardware issue on my end. If there's anything you guys can glean from the logs that can help me figure out what's going wrong, I would be immensely grateful

**Comment by Nightfirecat** [comment] 2023-05-24 05:07
Duplicate of #10628, we don't know what causes this crash.

**Closed by Nightfirecat** 2023-05-24 05:07 UTC
Labels: duplicate
