### ISSUE TITLE
Mac Mini Crash - AppleIntelKBLGraphicsGLDriver

### ISSUE THREAD

**Issue by robrichardson13** [runelite/runelite#15222] opened 2022-06-27 14:10 UTC
### Type

Crash or hang

### Operating System

MacOS

### OS Version

MacOS Monterey

### Bug description

Every day or so I've gotten the client to crash. There doesn't seem to be a specific event I'm doing when it happens. I run Runelite on 2 computers and the client has crashed on both of them, which makes me think it might be a plugin or setting I have, but I'm having a hard time replicating as this crash is random and sometimes won't happen for 2 days.

2018 Mac Mini - 3.2 GHz 6-Core Intel Core i7 (macOS Monterey)
2018 Macbook Pro - 2.5GHz Dual-Core Intel Core i7 (macOS Big Sur)

### RuneLite version

RunLite version: 1.8.24.3
Launchr version: 2.4.3

### Logs

[jvm_crash_pid_60181.log](https://github.com/runelite/runelite/files/8992740/jvm_crash_pid_60181.log)
[client.log](https://github.com/runelite/runelite/files/8992741/client.log)
[launcher.log](https://github.com/runelite/runelite/files/8992744/launcher.log)

[jvm_crash_pid_41991.log](https://github.com/runelite/runelite/files/8992746/jvm_crash_pid_41991.log)
[client_2022-06-26.0.log](https://github.com/runelite/runelite/files/8992747/client_2022-06-26.0.log)
[launcher_2022-06-24.0.log](https://github.com/runelite/runelite/files/8992748/launcher_2022-06-24.0.log)

**Comment by Adam-** [comment] 2022-06-27 14:12
The GPU plugin uses OpenCL, you can disable `compute shaders` to disable it, but it makes the draw distance smaller.

**Comment by Adam-** [comment] 2022-06-27 14:24
Disabling compute shaders would fix it. But I don't know why this is crashing.

**Comment by Nightfirecat** [comment] 2022-07-10 05:15
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 05:15 UTC
Labels: needs-triage
