### ISSUE TITLE
Timers still overlayed after leaving NMZ

### ISSUE THREAD

**Issue by twoodward1** [runelite/runelite#3355] opened 2018-05-26 17:49 UTC
Disconnected in NMZ and the overlays for the Overload were still on my screen as seen in picture
![image](https://user-images.githubusercontent.com/34960782/40578961-7a3322ca-6115-11e8-8a51-7ef3a1fa2c7d.png)
Edit: I just left the NMZ instance **without** disconnecting and the Overload timer still appears on my screen.

**Comment by deathbeam** [comment] 2018-09-02 19:00
Duplicate of #4773

**Closed by deathbeam** 2018-09-02 19:00 UTC
Labels: bug
