### ISSUE TITLE
Screen marker getting deleted when creating a new one

### ISSUE THREAD

**Issue by soulsword285** [runelite/runelite#3244] opened 2018-05-24 18:58 UTC
Open RuneLite > log in to an rs account > Create 2 screen markers > Delete the first one you created > Any consecutive markers you create replace the most recent

It seems this only fixes itself once you delete all screenmarkers.

https://gyazo.com/9163c39ea78247499f883bfe3f769dde

**Comment by Juzzed** [comment] 2018-05-24 19:00
duplicate #3240

**Comment by deathbeam** [comment] 2018-05-24 19:00
Duplicate of #3240

**Closed** 2018-05-24 19:00 UTC
