### ISSUE TITLE
[World map] Incorrect teleport mark

### ISSUE THREAD

**Issue by Pirocchio** [runelite/runelite#18084] opened 2024-07-23 23:25 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

windows 11

### Bug description

In the Dagannoth Kings dungeon, there is an extra "Key master teleport" icon. 

The aforementioned scroll is the one that leads to Cerberus, not DKs - currently, there is no scroll to the DKs.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/02d9e8a5-3852-43b1-870d-e599052f90f9)

### RuneLite version

rl version 1.10.35
launcher version 2.6.7

**Comment by Nightfirecat** [comment] 2024-07-24 00:11
Duplicate of #13073

**Closed by Nightfirecat** 2024-07-24 00:11 UTC
Labels: duplicate
