### ISSUE TITLE
Angle bracket regex within chat filter does not remove message

### ISSUE THREAD

**Issue by MarcDirven** [runelite/runelite#14971] opened 2022-05-15 00:58 UTC
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

Example message that needs filtering out: 
`[15:23] userz5332: <> biggets payouts <>`

My filter:
```regex
<>(.*?)<>
```

Message does not get removed by the Chat Filter plugin.

### Screenshots or videos

![regex test](https://i.imgur.com/No4nsji.png)

### RuneLite version

RuneLiteVersion 1.8.19.1
Launcher. 2.4.2

### Logs

client.log
<details open>
2022-05-15 02:04:23 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.19.1 (launcher version 2.4.2) starting up, args: none
2022-05-15 02:04:24 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2022-05-15 02:04:24 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2022-05-15 02:04:25 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 2315351504.132
2022-05-15 02:04:26 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2022-05-15 02:04:26 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.1.1" commit "d60a9215cf6313388a621fb1b12df04cb6b67e57"
2022-05-15 02:04:26 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.2" commit "51790d94159cbb85893de04d90efc5c0c20d819a"
2022-05-15 02:04:26 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" version "3.0.3" commit "898f035bf088e3288f00264e70546b57f81a23b0"
2022-05-15 02:04:26 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "guardians-of-the-rift-helper" version "1.01" commit "9f2925a9dde2dcd2fec8f33188dfba58681206ad"
2022-05-15 02:04:26 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "wikisync" version "2.0" commit "8246ef597be7554010737e8c47559b23d689410f"
2022-05-15 02:04:26 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" version "1.4" commit "0affbd89a039aeceded80695568e8f9c36023afb"
2022-05-15 02:04:26 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2022-05-15 02:04:26 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "skills-tab-progress-bars" version "1.2" commit "9ea27934275a809456d7bb6ebd636009787f94f3"
2022-05-15 02:04:27 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2022-05-15 02:04:29 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 5592ms. Uptime: 9164ms
2022-05-15 02:04:29 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,-8,-8,1936x1096,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,8,31,1920x1057,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2022-05-15 02:04:29 [Client] INFO  rs117.hd.HdPlugin - Using device: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
2022-05-15 02:04:29 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6.0 NVIDIA 512.59
2022-05-15 02:04:29 [Client] INFO  rs117.hd.HdPlugin - Client is 32-bit
2022-05-15 02:04:29 [Client] INFO  rs117.hd.lighting.LightConfig - Loaded 1446 lights
</details>

launcher.log
<details open>
2022-05-15 02:04:20 [main] INFO  net.runelite.launcher.Launcher - RuneLite Launcher version 2.4.2
2022-05-15 02:04:20 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-1.8.19.1.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of slf4j-api-1.7.25.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-classic-1.2.9.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-core-1.2.9.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jopt-simple-5.0.1.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guava-23.2-jre.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guice-4.1.0-no_aop.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of javax.inject-1.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of aopalliance-1.0.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gson-2.8.5.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of substance-8.0.02.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of trident-1.5.00.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-text-1.2.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-lang3-3.7.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-csv-1.4.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of archive-patcher-applier-1.2.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-5.9.0.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-platform-5.9.0.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jsr305-3.0.2.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-rl-2.4.0-rc-20220318.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-rl-2.4.0-rc-20220318-natives-windows-i586.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.4.0-rc-20220318.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.4.0-rc-20220318-natives-windows-i586.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jocl-1.0.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-patch-1.8.19.1.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of http-api-1.0.0.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okhttp-3.14.9.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okio-1.17.2.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of discord-1.4.jar
2022-05-15 02:04:23 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runelite-api-1.8.19.1-runtime.jar

</details>

**Comment by Adam-** [comment] 2022-05-15 01:00
The client represents these internally as `<lt>` and `<gt>` so it would probably work if you matched those

**Comment by MarcDirven** [comment] 2022-05-15 01:04
Thanks, that works.

**Comment by Nightfirecat** [comment] 2022-05-15 01:51
Duplicate of #9155

**Closed by Nightfirecat** 2022-05-15 01:51 UTC
Labels: duplicate
