### ISSUE TITLE
Multiple profiles for different devices

### ISSUE THREAD

**Issue by itsSimplex** [runelite/runelite#5460] opened 2018-09-12 12:59 UTC
Just wondering if we can store different profiles and use specific ones when we are on different devices. Such as if I'm on a PC with a 30-inch screen, but I also use a 13-inch Macbook, I would need to keep changing my plugin locations on my screen

**Comment by deathbeam** [comment] 2018-09-12 13:14
Duplicate of #2220

**Closed by deathbeam** 2018-09-12 13:14 UTC
