### ISSUE TITLE
Yanille Hard Map Clue wrong tile.

### ISSUE THREAD

**Issue by nmq12** [runelite/runelite#3771] opened 2018-06-13 16:04 UTC
This was showing up with the correct tile for my previous clues at this spot. Not sure why this time it was off.
![image](https://user-images.githubusercontent.com/5819477/41363432-e136e4a8-6f01-11e8-8d7f-889facf1c906.png)
![image](https://user-images.githubusercontent.com/5819477/41363437-e934fb90-6f01-11e8-86fc-9a67039fa9d2.png)

**Comment by Kamielvf** [comment] 2018-06-13 16:16
The tile was moved because it is faster to dig on the now highlighted spot. You do not have  to run all the way behind this building and can instead dig inside of it.

**Comment by Nightfirecat** [comment] 2018-06-13 16:22
Duplicate of #3541

**Closed** 2018-06-13 16:23 UTC
