### ISSUE TITLE
Swap dream on Dominic onion at NMZ

### ISSUE THREAD

**Issue by Kmtfwtm** [runelite/runelite#11560] opened 2020-05-12 12:11 UTC
These would be awesome additions to the menu swapper!

**Comment by melkypie** [comment] 2020-05-12 12:16
Left click guzzle is a duplicate of #1860.

**Comment by Broooklyn** [comment] 2020-05-13 19:48
Exists within Menu Entry Swapper Extended on the Plugin Hub under "Minigames"

**Closed** 2020-05-13 19:48 UTC
Labels: feature-request

**Comment by Kmtfwtm** [comment] 2020-05-20 00:58
> Exists within Menu Swapper Extended on the Plugin Hub under "Minigames"

It doesn't work

**Comment by Broooklyn** [comment] 2020-05-20 04:34
@Kmtfwtm It should be fixed now

**Comment by Kmtfwtm** [comment] 2020-05-20 22:54
@Broooklyn Very nice thank you it works (: 
Could you add left click guzzle on rock cake? ;o

**Comment by Broooklyn** [comment] 2020-05-20 23:00
@Kmtfwtm Don't thank me, thank raiyni—He fixed it, I just pointed it out to him.  

You can find left click guzzle for rock cake in the `NMZ Utilities` plugin on the hub.

**Comment by Kmtfwtm** [comment] 2020-05-20 23:08
@Broooklyn Sweeet thank you! Idk why no1 mentioned that before haha I just got told it was a duplicate request.
