### ISSUE TITLE
Suggestion: Custom cursor from 2010

### ISSUE THREAD

**Issue by rabbit99999** [runelite/runelite#5722] opened 2018-09-30 21:04 UTC
Hello I was wondering if it's possible that someone could make the custom dynamic cursor from 2010? The gold one that would change depending on what action you were trying to complete. Example: it showed an apple when you Hovered over a piece of food, and a beer over a drink or potion. This would make an awesome combination with the 2010 interface style. Thank you if possible!

**Comment by Nightfirecat** [comment] 2018-09-30 21:05
Duplicate of #4207

**Closed** 2018-09-30 21:52 UTC
