### ISSUE TITLE
Chambers of Xeric Opponent info changes

### ISSUE THREAD

**Issue by Kurama2121** [runelite/runelite#12230] opened 2020-07-26 07:02 UTC
With the addition of native health bars in chambers of xeric it would be nice to be able to not have to turn the Opponent info plugin off while in certain rooms of chambers of xeric of free up screen space. In rooms like Tekton or Olm, there is a built in HP tracker so the opponent info health bar isnt needed (see image) but in guardians where there isnt a native health bar, the opponent info bar would still be needed.

![unknown](https://user-images.githubusercontent.com/39833426/88473510-f2863080-cee3-11ea-8e1a-f69591ea958c.png)

**Comment by makingcomment** [comment] 2020-07-26 18:17
Related (but not quite the same): #12137

**Comment by Hydrox6** [comment] 2020-11-27 08:09
Duplicate of #5570

**Closed by Hydrox6** 2020-11-27 08:09 UTC
Labels: feature-request
