### ISSUE TITLE
RuneLite Bar is at 0% then closes

### ISSUE THREAD

**Issue by badgerx3** [runelite/runelite#4195] opened 2018-07-06 00:55 UTC
I am on Mac OS.

When I try and launch RuneLite it sits at 0% for a few seconds then closes. I had no problems with it for weeks then this afternoon it won't load.

I have tried restarting my computer, force quitting everything and restarting the app. I have redownloaded RuneLite, updated Java and Flash, and ran the manual launcher and none have worked. There were similar results to mine back in April, but what I read either didn't work or I couldn't comprehend how to do it

**Comment by Chubateo** [comment] 2018-07-06 07:30
I have the same problem. I wonder if this is caused by the same bug...

**Comment by NathenSample** [comment] 2018-07-06 07:41
I have genuinely no idea what prompted you to update flash of all things, but hey ho.

Try clear out your `/repository/` folder - this can be found in `~/.runelite/repository/` on unix systems, and `%userprofile%\.runelite\repository\` on windows.

If this doesn't rectify your issue, please capture your logs, and upload them either either [pastebin](https://pastebin.com/), or [gist.github](https://gist.github.com/). Please note these logs tend to include full paths, and thus in many cases may reveal your name, if you're cautious about that sort of information, make sure to sanitise the file before uploading it.

You should see logs following the format of `application.log` `launcher.log` and the same but followed by `xxxx-xx-xx` date stamps. You want the ones without the data stamps, and for this specific scenario, `launcher.log` is the most pertinent.

**Comment by deathbeam** [comment] 2018-07-06 13:17
Duplicate of https://github.com/runelite/launcher/issues/17

**Closed by deathbeam** 2018-07-06 13:17 UTC
Labels: bug

**Comment by badgerx3** [comment] 2018-07-06 13:44
i continued messing around with it and ran rm -rf ~/.runelite in terminal then it worked
