### ISSUE TITLE
Kingdom of Misthalania Otto's Grotto Screenshot

### ISSUE THREAD

**Issue by Tarnis10100** [runelite/runelite#12807] opened 2020-11-17 01:54 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**
1. Go to Otto
2. Get the Barbarian Skills book
3. Open the book and flip through pages
4. Screenshots of the open book will be saved in the "kingdom Rewards" screenshot folder

**Expected behavior**
No screenshot should be taken, and shouldnt be saved as kingdom reward

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.31.1
 - Launcher version: 2.1.3

**Additional context**
![Kingdom 2020-11-11 2020-11-11_13-52-01](https://user-images.githubusercontent.com/74576965/99331286-3ff12980-2856-11eb-9200-04b351492d9c.png)

**Comment by dekvall** [comment] 2020-11-17 02:19
This should be fixed, if you restart your client and open a book, can you check that it actually captures a new screenshot?

**Comment by dekvall** [comment] 2020-11-17 02:31
Duplicate of #12773

**Closed by dekvall** 2020-11-17 02:31 UTC
