### ISSUE TITLE
Using the Wiki button on your current Slayer task could open entry for that monster

### ISSUE THREAD

**Issue by kcallicoat** [runelite/runelite#8267] opened 2019-03-20 00:07 UTC
As a newer player, often when I start a slayer task I'm not always sure where to locate a monster, it's weaknesses and other important information required to complete the task. Typically I will just open the wiki and search for that monster, which is pretty easy.

The new wiki button is really helpful for learning more about the game as I'm walking through the world, however it's not so useful for slayer because I can't directly look up a monster until after I've found the monster somewhere in the world.

It would be nice if I could click on the wiki button, then click on the slayer task progress icon, and have the wiki open up to the monster I'm currently assigned.

**Comment by trini0n** [comment] 2019-03-20 02:20
The wiki button also has a right click option to bring up a search option to the wiki. It's an extra few keystrokes but you could just do that in case what you're describing doesn't get implemented.

**Comment by deathbeam** [comment] 2019-03-20 10:30
Duplicate of #8229

**Closed by deathbeam** 2019-03-20 10:30 UTC
