### ISSUE TITLE
Auto-Collapse LVL tracker

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#2476] opened 2018-05-08 15:01 UTC
Whenever the client is restarted I have to manually collapse my levels, the whole point for me is to see xp / h & time until next level, let's save clicks!

https://i.imgur.com/67HF6b9.gifv

**Comment by Caia-OSRS** [comment] 2018-05-08 15:10
I think this is similar to #974 I posted a while back

**Comment by Popedigoz** [comment] 2018-05-08 15:12
Yeah. Damn, Mar16? Apply this to the next update please devs
c;<

**Comment by deathbeam** [comment] 2018-05-08 15:13
Duplicate of #974

**Comment by deathbeam** [comment] 2018-05-08 15:13
Also, this will be solved with the Obsidian theme redesign

**Closed by deathbeam** 2018-05-08 15:13 UTC

**Comment by Popedigoz** [comment] 2018-05-08 15:15
what's obsidian theme redesign doe..:/?

**Comment by ypperlig** [comment] 2018-05-08 15:17
See #1419
