### ISSUE TITLE
Clue tag only shows emote items

### ISSUE THREAD

**Issue by orlp** [runelite/runelite#13164] opened 2021-02-06 19:17 UTC
**Describe the bug**
Items tagged with 'clue' do not show up when searching for 'clue' or 'tag: clue' on the bank, only emote items or clues are shown when searching for this tag.

**To Reproduce**
1. Edit tags on some items in the bank, giving them the 'clue' tag.
2. Search for 'clue'.
3. The items are not shown.

**Expected behavior**
I expect items with the 'clue' tag to be shown when searching for clue.

**Screenshots**
![image](https://user-images.githubusercontent.com/202547/107127706-35c05380-68b8-11eb-8e1d-bc4ee3a4fbfd.png)
![image](https://user-images.githubusercontent.com/202547/107127712-407ae880-68b8-11eb-8d22-ec16a9741ed1.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.39
 - Launcher version: 2.1.0

**Additional context**
This used to work a while back, where searching for 'clue' would conveniently show any clue scrolls in your bank, plus any items you manually tagged 'clue'.

**Comment by Adam-** [comment] 2021-02-06 19:22
This has been fixed already in f13be14280d8fc7d6f12c05ea0f3807daabaddf4 and will be in the next update. Until then you can rename the tab to something other than `clue`. 

Duplicate of #13162

**Closed by Adam-** 2021-02-06 19:22 UTC

**Comment by orlp** [comment] 2021-02-06 19:28
@Adam- Sorry, I checked for duplicates but I think it didn't find it because it was closed already.

**Comment by Adam-** [comment] 2021-02-06 19:28
No problem
