### ISSUE TITLE
Barrows plugin improvements: highlights

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#11180] opened 2020-04-03 11:59 UTC
I would like the barrows plugin to highlight two things: The region on the mound where you can dig and then the doors with with "Open" option in the tunnels. The former can be achieved with tile markers, but object markers apparently do not work on the later.

**Comment by Hydrox6** [comment] 2020-04-03 12:01
1) Duplicate of #4668
2) Duplicate of #2588

**Closed by Hydrox6** 2020-04-03 12:01 UTC
