### ISSUE TITLE
Improve tooltips for Hunter training sites on world map

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#10988] opened 2020-03-09 14:45 UTC
In a recent update, the tooltips of mining sites have been improved to show the numbers of available rocks. Similarly, we could improve the Hunter training site icons by stating what kind of creature(s)  can be hunted there. It could be helpful to new players.

**Comment by dekvall** [comment] 2020-03-09 15:10
Duplicate of #6848

**Closed by dekvall** 2020-03-09 15:10 UTC
