### ISSUE TITLE
Advanced Sound Effect Blocker

### ISSUE THREAD

**Issue by Chdata** [runelite/runelite#2484] opened 2018-05-08 17:55 UTC
Enables you to make a list of specific sound effects to block.

Don't like the stomping sound of that skotizo pet?

Want to eliminate the sounds of Dust Devils attacking you while you burst them?

Hate the sound of Humidify at the bank?

This plugin would allow a user to 'listen' to sound ids to add to a block list.

**Comment by deathbeam** [comment] 2018-05-08 18:26
Duplicate of #2240

**Closed by deathbeam** 2018-05-08 18:26 UTC
