### ISSUE TITLE
Trigger notification on low hellcat health vs. Hell-Rat Behemoths

### ISSUE THREAD

**Issue by Marstead** [runelite/runelite#11833] opened 2020-06-06 16:38 UTC
**Is your feature request related to a problem? Please describe.**
Fighting Hell-Rat Behemoths with a Wily hellcat is safe over 90% of the time, meaning it is a task players will want to afk. However, there is a risk of the Behemoth getting a string of lucky hits and killing your cat.

**Describe the solution you'd like**
I would like to be able to configure RuneLite (or a PluginHub plugin) to trigger a notification when my cat's health becomes critical while fighting Hell-Rat Behemoths

**Describe alternatives you've considered**
Setting the health threshold to an arbitrary value or % instead of letting players control the notification level would be fine.

**Additional context**
The "Health Notifier" PluginHub plugin does not seem to work for this use case; I assume Wily hellcat health is treated differently from other NPC health.

**Comment by raiyni** [comment] 2020-07-11 17:57
Duplicate of #3337

**Closed by raiyni** 2020-07-11 17:57 UTC
Labels: feature-request
