### ISSUE TITLE
[SUGGESTION] Add a plugin that will track users G.E transactions.

### ISSUE THREAD

**Issue by boopert** [runelite/runelite#11289] opened 2020-04-16 20:13 UTC
**Is your feature request related to a problem? Please describe.**
I currently use GE-tracker for accurate prices but im always skeptical of high value items being manipulated. In-fact today i was buying an item higher than what ge tracker was saying there were sales for, which must be impossible cause mine didnt buy.

**Describe the solution you'd like**
I would like runelite to get a feature to track this and put "average trading price" next to the items you are buying/selling in the ge.

**Comment by Hydrox6** [comment] 2020-04-16 20:18
If you're asking for your own trades to be tracked, the website already has this information if you're logged in with an account.

If you're asking for something similar to OSB's tracker, this is not something we're going to do due to not being able to verify the data, requiring an insane amount of effort to even try to prevent manipulation.

If it's something else you want, please specify it, as your post currently does not say what you're asking for well enough.

**Comment by boopert** [comment] 2020-04-16 20:22
Yeah im asking for something similar to OSB because they are manipulating their prices

**Comment by Hydrox6** [comment] 2020-04-16 20:25
Duplicate of #4377

**Closed by Hydrox6** 2020-04-16 20:25 UTC
