### ISSUE TITLE
Time Tracker Plug-IN

### ISSUE THREAD

**Issue by runeliteabuser** [runelite/runelite#14722] opened 2022-02-28 18:41 UTC
Hey guys I wanted to make a suggestion on the Time-Tracker 'Farming' Plugin

Is there a way we can choose specific patches into specific categories and delete some others? (Obviously being able to 'undelete' them in the settings).

It's so clumped and scattered where everything is and it's combined with other patches that I don't use. I would love the idea if we can make the whole thing customizable and making farm runs easier. 

Thank you for reading my post

**Comment by Hydrox6** [comment] 2022-02-28 19:09
Duplicate of #3056

**Closed by Hydrox6** 2022-02-28 19:09 UTC
