### ISSUE TITLE
fetch loot tracker data on sign in with client open

### ISSUE THREAD

**Issue by NewGuy274** [runelite/runelite#8202] opened 2019-03-13 21:35 UTC
To be able to update loot tracker upon signing in to an account that already has loot tracked without signing in to a new client.  
  
This is what I mean. https://imgur.com/a/352Pa0x
currently if you sign out for any reason and close the client, when you reopen the client and sign in, your loot tracker will be cleared. Once you reopen the client again all your loot will show. Can it be made to bring up loot on sign in rather than reopening a signed in client?

**Comment by deathbeam** [comment] 2019-03-19 00:39
Duplicate of #7896

**Closed by deathbeam** 2019-03-19 00:39 UTC
