### ISSUE TITLE
Examiner marked by clue plugin isnt clue related

### ISSUE THREAD

**Issue by vitorebom** [runelite/runelite#12205] opened 2020-07-22 16:47 UTC
This Examiner is marked for the clue plugin but she doesnt give the puzzle box

![image](https://user-images.githubusercontent.com/55747379/88204519-bf147f00-cc21-11ea-8998-9cb1c3a33401.png)

**Comment by Broooklyn** [comment] 2020-07-22 16:49
The wiki says `You might need to talk to several different examiners.`

**Comment by Nightfirecat** [comment] 2020-07-22 16:51
Duplicate of #3164

**Closed by Nightfirecat** 2020-07-22 16:51 UTC
Labels: duplicate
