### ISSUE TITLE
Addition to daily task indicator

### ISSUE THREAD

**Issue by Floukru** [runelite/runelite#3112] opened 2018-05-22 18:02 UTC
http://oldschoolrunescape.wikia.com/wiki/Robin

This task requires
- Morytania Med
- Morytania Hard
- Morytania Elite

> After the completion of the Morytania Diary, Robin will exchange bones for bone meal and buckets of slime daily. He will give 1 pot of bone meal (same type as the bones you give), and 1 bucket of slime for every bone you give him. He does not accept noted bones, and does not give noted items, so you will need free inventory space. He will exchange 13 bones per day after the completion of the medium morytania diary, 26 per day for hard diary, and 39 per day for elite diary.

Pretty sure everyone who has a bonecrusher uses this guy.

Would love to see a daily message saying 
"Robin is now available for you"

**Comment by deathbeam** [comment] 2018-05-22 18:19
Duplicate of #1863

**Closed by deathbeam** 2018-05-22 18:19 UTC
Labels: feature-request
