### ISSUE TITLE
[Suggestion] Implement reordering and categorizing of spells in spellbook

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1255] opened 2018-04-03 12:34 UTC
I saw this on Reddit: https://i.redd.it/c8agf58banp01.png , and it would be really nice if Runelite would support this.

**Comment by Adam-** [comment] 2018-04-03 12:38
Duplicate of #1038

**Closed by Adam-** 2018-04-03 12:38 UTC

**Comment by dappersnapper456** [comment] 2020-04-02 17:08
Hi,

Why has this been closed?

This feature would be incredibly useful for runecrafting so I could use the Ourania Altar and NPC contact spell without having to go searching in the spellbook for each.

**Comment by dappersnapper456** [comment] 2020-04-02 17:11
Oh admins I think both #1038 and #1255 were categorised as duplicates of each other and were both closed as such, meaning that there is no version of this feature request that is open currently. @Adam- @deathbeam @ShaunDreclin

**Comment by Nightfirecat** [comment] 2020-04-02 17:11
[It is forbidden by Jagex.](https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1)

> Can unhide, hide, move, or resize interface components on the Prayer and Spellbook interfaces
