### ISSUE TITLE
anti aliasing is broken 

### ISSUE THREAD

**Issue by kage21** [runelite/runelite#12391] opened 2020-08-25 09:15 UTC
msaax2 is fine atm but anything above it causes the screen to freeze or just turn black and any text or custom ground markers just ghost and duplicate as you turn the camera was working fine a few days ago but when i logged in my screen was black and after tricking and unticking different settings the msaa setting seem to be the culprit. iv tried uninstalling and reinstalling but it didnt fix it also tried clearing the cache also did not fix it 
![Capture](https://user-images.githubusercontent.com/29508269/91156164-c8b25c00-e691-11ea-8c6e-324d4c623c82.PNG)

**Comment by Hydrox6** [comment] 2020-08-25 09:20
Duplicate of #7197

**Closed by Hydrox6** 2020-08-25 09:20 UTC
