### ISSUE TITLE
Hidey Hole/Stash Helper

### ISSUE THREAD

**Issue by ellsbellssmells** [runelite/runelite#5045] opened 2018-08-21 18:52 UTC
It always annoys me when I'm doing clues and forget which hideys I have built and which ones I haven't.

I was wondering if an enhancement could be made in terms of the clue scroll helper. Not too sure if this is possible or not, but I think it would be a good addition.

👍

**Comment by deathbeam** [comment] 2018-08-21 18:56
Duplicate of #1662 and #1742

**Closed by deathbeam** 2018-08-21 18:56 UTC
