### ISSUE TITLE
[Suggestion] Make An Alert Whenever the Message in the Chatbox says, "A Champion's scroll falls to the ground as you slay your opponent."

### ISSUE THREAD

**Issue by Exstatic** [runelite/runelite#1681] opened 2018-04-19 05:06 UTC
According to the OSRS Wiki listed [here](http://oldschoolrunescape.wikia.com/wiki/Champions%27_Challenge). A message appears titled "A **Champion's scroll falls to the ground as you slay your opponent.**" whenever you get a champions scroll in the chat. Its in red and cannot be filtered.

The problem is, since it takes forever to get (usually 1/5000), we may not be paying attention. I propose an alert pops up when it does happen

**Comment by deathbeam** [comment] 2018-04-19 08:56
Duplicate of #1469

**Closed by deathbeam** 2018-04-19 08:56 UTC
Labels: duplicate
