### ISSUE TITLE
Remap Keys

### ISSUE THREAD

**Issue by ZebGasm** [runelite/runelite#8484] opened 2019-04-11 19:02 UTC
**Is your feature request related to a problem? Please describe.**

when i try to turn my camera with LAlt i can move things wich is nice but i get anoyed when all my hidden loot shows with the yellow bars that show up

**Describe the solution you'd like**

i would love to see that you can edit the LAlt problem above 
i would also love to see a section where you can remap the Fkeys to anything on you keyboard within the client im using ahk now

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

would love to not see the hidden loot and that the yellow bars are not shown when i press alt would love to have the ability to be able to change the alt key to ctrl or something
https://i.imgur.com/nNBubKs.png

**Comment by Hydrox6** [comment] 2019-04-11 23:18
Duplicate of #7831

**Closed by Hydrox6** 2019-04-11 23:18 UTC
