### ISSUE TITLE
Ability to 'favourite' certain farm patches for the timers

### ISSUE THREAD

**Issue by SlowpokeOSRS** [runelite/runelite#7518] opened 2019-01-23 16:19 UTC
Give the ability to favourite certain patches on the farming timers side bar so they can be compiled into one tab.
e.g. If you don't have 99 farming and have two spirit trees planted (leaving 3 empty), or don't have a tree planted at the farming guild. The occupied patches would be compiled into the one **Favourites Tab** making it easier to read, search, check times your trees are done. QOL update basically. PLS

**Comment by deathbeam** [comment] 2019-01-25 16:40
Duplicate of #3056

**Closed by deathbeam** 2019-01-25 16:40 UTC
