### ISSUE TITLE
Add Konar Chest/Seedpacks to Loottracker?

### ISSUE THREAD

**Issue by Hopeofhell** [runelite/runelite#7946] opened 2019-02-20 16:19 UTC
So with Barrows you can track the loot via the tracker, so im wondering if we can add the new Chest for the BrimStone keys from Konar to the tracker.
Adding the Seedpacks would be nice as well.

Thanks Hopeofhell

**Comment by deathbeam** [comment] 2019-02-20 17:47
Duplicate of #7749

**Closed by deathbeam** 2019-02-20 17:47 UTC
