### ISSUE TITLE
Mourner Clue Scroll

### ISSUE THREAD

**Issue by TCNorris** [runelite/runelite#3721] opened 2018-06-09 22:18 UTC
On the cryptic clue whose message is "Stop crying! Talk to the head." the arrow for the client will point to the head mourner on the surface in West Ardougne.  (The one in the building next to the entrance to the city).  It is not possible to complete the clue with this NPC however - the head mourner the clue refers to is the one underground by the jail cell, which is also pointed to by the arrow.

**Comment by Nightfirecat** [comment] 2018-06-18 19:46
Would be fixed by #2202.

**Comment by Roughsketch** [comment] 2018-06-18 21:35
The methods for fixing this are in #2202, but that clue in particular doesn't look like it's locked. I can add it after I finish working out the rebase, but since I'm on vacation it might not be for a while.

**Comment by deathbeam** [comment] 2018-09-22 23:03
Duplicate of #5231

**Closed by deathbeam** 2018-09-22 23:03 UTC
Labels: clues
