### ISSUE TITLE
GPU plugin crashes client

### ISSUE THREAD

**Issue by psilocyber420** [runelite/runelite#6596] opened 2018-11-19 22:45 UTC
when i try to load the client with gpu enabled it will freeze on login screen, if i turn on during game it freezes client. it worked all last night so i do not understand whats going wrong.  i dont have compatibility mode enabled, i have tried with hardware acceleration off. and ive tried the bat file.

**Comment by deathbeam** [comment] 2018-11-20 07:43
Duplicate of #6523

**Closed by deathbeam** 2018-11-20 07:43 UTC
