### ISSUE TITLE
Add option to use previous hiscores filter

### ISSUE THREAD

**Issue by whartd** [runelite/runelite#10977] opened 2020-03-07 17:50 UTC
Currently, if you type a player's name into the hiscores plugin it will search using whatever filter you have selected. After a lookup the filter you've selected will persist for future searches. However, if you right click a player's character or messages and hit "lookup", you will always search the normal hiscores. I would an option to have the right click lookup function the same way as typing a name.

Use Case 1: I'm often curious when I see people if they're an ironman or not. If I type their name out with the Ironman filter selected I can check pretty quickly. The ironman hiscores load very quickly. However, if I right click->lookup I have to sit and wait for the normal scores to finish loading, fail loading, or get stuck loading and fix it. Then I have to click on the ironman filter and search again. This is time consuming and annoying. 

Use Case 2: On my ironman I often engage in late game group content with other ironmen, and am in ironman only ccs. When forming teams or chatting, I frequently want to look the other players up to check stats/kc. Once again, the issues from Use Case 1 are encountered.

Alternative solutions: I'm not sure if it would be possible, but an alternative I considered was making a right-click->lookup automatically search the filter for the game-mode of the player. This would be even more convenient, but I expect it would be harder or impossible to implement.

**Comment by Nightfirecat** [comment] 2020-03-08 02:53
Use case 1 is primarily an issue due to the slow hiscore loading, and we're not really interested in changing code to account for Jagex's slow hiscore servers, particularly since they plan to update it to work closer to how it did previously which was notably faster.

Use case 2 is, as you mentioned, the same as use case 1.

Automatic lookup of ironman stats is a duplicate of the `wontfix` request #2403. We can't cleanly implement this because there is no client nor hiscore API data which indicates a player's account status.

**Closed** 2020-03-08 05:15 UTC
