### ISSUE TITLE
Sound issues Linux AppImage

### ISSUE THREAD

**Issue by razing32** [runelite/runelite#10060] opened 2019-10-14 09:33 UTC
**Describe the bug**
Sound behavior is odd.
If I start the AppImage sound works normally but videos stop buffering on any sites I tried in different browsers while App is running.
If a video is playing while i start the App the App stays muted permanently.

**To Reproduce**
1.Start App. Then open a video on Youtube etc. 
2.Leave a Youtube video playing then start the App

**Expected behavior**
Either video should not load or app should remain muted 

**Screenshots**
n/a

**Environment (please complete the following information):**
OS : Arch Linux - kernel 5.3.1
Audio : Pulse 13.0-2

**Additional context**

**Comment by abextm** [comment] 2019-10-14 09:59
Probably a duplicate of #3525

**Comment by razing32** [comment] 2019-10-14 11:44
OH interesting. I looked for duplicates but missed that one.

**Closed** 2019-10-14 12:44 UTC
