### ISSUE TITLE
[Feature Request] Window minitaturization

### ISSUE THREAD

**Issue by Winhert** [runelite/runelite#2979] opened 2018-05-19 22:14 UTC
https://image.ibb.co/gCBX6T/default.png

In default client when you make window sufficiently small you will get scroll bar on the right allowing you to view certain part of rendered game screen. This allows to alch/pocket ardies/other clickies while watching a video on decent resolution.

**Comment by deathbeam** [comment] 2018-11-26 13:58
Duplicate of #3937

**Closed by deathbeam** 2018-11-26 13:58 UTC
Labels: feature-request
