### ISSUE TITLE
Wrong quantity displayed on ground items

### ISSUE THREAD

**Issue by cmg5461** [runelite/runelite#6006] opened 2018-10-14 02:23 UTC
![java_2018-10-13_21-49-43](https://user-images.githubusercontent.com/9099791/46911911-7b61f100-cf36-11e8-832b-5cec3ebe4b33.png)

Seems to happen on tiles which contain one visible to public item & one visible to player item.

Index 0 coins quantity is 3,000.

**Comment by Adam-** [comment] 2018-10-14 02:28
Duplicate of #1220

**Closed by Adam-** 2018-10-14 02:28 UTC
