### ISSUE TITLE
Screen marker positions

### ISSUE THREAD

**Issue by ValgeHunt07** [runelite/runelite#4402] opened 2018-07-19 11:53 UTC
When marking something with a screen marker and then closing the right side bar of the runelite stuff such as screen marker, etc. The screen markers get moved from the screen that much. The examples on the pictures.
![image](https://user-images.githubusercontent.com/41432145/42940805-5c9a0774-8b63-11e8-9e49-f3bead1f48ce.png)
![image](https://user-images.githubusercontent.com/41432145/42940822-6d430f62-8b63-11e8-8d7c-01a0246e4172.png)

**Comment by Kamielvf** [comment] 2018-07-19 11:55
This is working as intended, and I believe this could be filed as a duplicate of #3283

**Comment by deathbeam** [comment] 2018-08-03 17:53
Duplicate of #3784

**Closed by deathbeam** 2018-08-03 17:53 UTC
