### ISSUE TITLE
Profiles for cloud-synced accounts

### ISSUE THREAD

**Issue by rswindows10** [runelite/runelite#5634] opened 2018-09-25 14:41 UTC
**Is your feature request related to a problem? Please describe.**
When using multiple accounts which need different settings (e.g.: Ground Item plugin settings), having to change those settings every time you load up the client becomes a tad annoying and unnecessary. 

**Describe the solution you'd like**
Having the possibility to save different settings into different profiles (e.g. "Main", "Lurer", "Rune Dragons", "1414 Skilling", "Bossing", etc), either as new plugin or as an extension of the "Account" plugin would be a good solution as it would allow you to save different profiles and switch them depending on the type of account you're playing in a specific client.

**Describe alternatives you've considered**
The only alternative I can think of would be to logout/login different google accounts every time I want to use a different type of account. But that's also annoying and cumbersome.

**Comment by deathbeam** [comment] 2018-09-25 14:44
Duplicate of #2220

**Closed by deathbeam** 2018-09-25 14:44 UTC
