### ISSUE TITLE
Implings plugin showing implings from previous world when hopping

### ISSUE THREAD

**Issue by TheSweeet** [runelite/runelite#2913] opened 2018-05-19 02:42 UTC
Implings plugin showing implings from previous world when hopping
![bc154a26b6d1f70571d74b487bb7eebd](https://user-images.githubusercontent.com/25854089/40264218-dcc43aca-5aec-11e8-9ab0-67a2781c64f3.png)

**Comment by TheSweeet** [comment] 2018-05-19 02:43
Only way to fix so far has been restarting the client.

**Comment by TheSweeet** [comment] 2018-05-19 03:05
Note: Teleporting also causes this bug.

**Comment by LeviSchuck** [comment] 2018-05-19 20:43
Where do I go to replicate the issue? 
Are there any quest or skill requirements?

**Comment by LeviSchuck** [comment] 2018-05-19 21:10
Found a gormet impling, but was not able to reproduce with world hopping. 
Maybe this is only in that maze area?

**Comment by sanderdegroot** [comment] 2018-05-20 10:10
I have spotted what may be the same issue. For me, I see magpie impling overlays in lots of places (found one in the Kourend catacombs, one near the Warriors' Guild, several other places) where there is no magpie impling. It's only happening with magpies. Not sure what caused it.

**Comment by forsco** [comment] 2018-05-20 10:11
#2999

**Comment by TheSweeet** [comment] 2018-05-20 13:46
The Impling outlines stay from hopping worlds whenever you load new parts of the map; including teleporting. If there is a bugged impling outline 13 blocks northeast of you it will follow you as you move loading new parts of the map.

**Comment by deathbeam** [comment] 2018-05-20 13:51
Yeah this has already been fixed in master.

**Closed by deathbeam** 2018-05-20 13:51 UTC
Labels: bug
