### ISSUE TITLE
Crystal shield shows bonuses on inventory mouse-over even when it is inactive

### ISSUE THREAD

**Issue by Uwila** [runelite/runelite#15406] opened 2022-07-26 10:34 UTC
### Type

Incorrect behavior

### OS Version

N/A

### Bug description

When the Crystal Shield is inactive, it gives no additional bonuses (it has to be recharged and become 'active' again), but if you hover your mouse over it while it is in your inventory, it will show the bonuses of a regular Crystal Shield.

### RuneLite version

Runelite version: 1.8.28
Launcher version: 2.1.0

**Comment by Hydrox6** [comment] 2022-07-26 13:10
This was an issue with the wiki showing stats for the inactive shield. I've confirmed that it doesn't (thanks Rheon) and updated the wiki, so the next time the stats scraper runs, it should be fixed.

If anyone wants to confirm the Bow and Halberd, that would be very useful; They're likely the same, but since they're weapons it would be useful to make sure.

**Comment by Nightfirecat** [comment] 2022-08-10 00:00
I am closing this for now. If this turns out to be an issue with the crystal bow and/or halberd (it probably is), this should be corrected on the wiki side [similar to how Hydrox fixed it for the shield](https://oldschool.runescape.wiki/w/Crystal_shield?diff=14306829&oldid=14296237).

**Closed by Nightfirecat** 2022-08-10 00:00 UTC
Labels: bug, item-stats
