### ISSUE TITLE
Pyramid Plunder Plugin

### ISSUE THREAD

**Issue by FrozenPigs** [runelite/runelite#5877] opened 2018-10-08 09:09 UTC
**Is your feature request related to a problem? Please describe.**
Finding the doors in pyramid plunder when you're not used to it can be a bit annoying, and also finding the right one.

**Describe the solution you'd like**
You can  highlight the doors a color like red, and if the plugin sees that a person went through it highlight it green as it has a chance of being your door too.

**Describe alternatives you've considered**
If tracking when a user goes through the door is a concern to some people just highlighting the door in general could still assist new players.

**Comment by deathbeam** [comment] 2018-10-08 09:13
Duplicate of #2446

**Closed by deathbeam** 2018-10-08 09:13 UTC
