### ISSUE TITLE
Kill counter plugin

### ISSUE THREAD

**Issue by sirlaige** [runelite/runelite#4415] opened 2018-07-19 20:44 UTC
**Is your feature request related to a problem? Please describe.**
I want to keep track of the monsters I kill via a plugin similar to the Xp tracker plugin.  I would like this mainly for times I need to know the amount of the monster kills, like going for champion scrolls.  The likelihood is 1in5k 

**Describe the solution you'd like**
Add a plugin for that will keep track of the number of each monster the player kills for the play session.  Like the xp tracker that shows the skills you worked on during the play session except this will list all the monster you have killed and the number of times you killed them.

**Describe alternatives you've considered**
Another option would be the health bar plugin you guys have for monster.  Just add a spot/ option to have kill count shown in addition.   

**Additional context**
Perhaps this could integrate with other plugins,  Like the examine of an item will give the value on ge,  perhaps examine on a monster could display their kill count.

**Comment by deathbeam** [comment] 2018-07-19 20:45
Duplicate of #1235

**Closed by deathbeam** 2018-07-19 20:45 UTC

**Comment by deathbeam** [comment] 2018-07-21 16:58
The tracker will include kill counts as well. Otherwise we have !kc command what is for bosses.
