### ISSUE TITLE
Mouse cursor 'trail' only when runelite client is focused

### ISSUE THREAD

**Issue by animaticps** [runelite/runelite#8993] opened 2019-06-02 12:33 UTC
**Describe the bug**

When moving the mouse on the runelite client it appears there is a second mouse cursor that slightly lags behind my actual one and it gets very annoying. This goes away completely when the runelite client is not focused, even if you move your mouse over the client. As soon as you click down again the behaviour starts to happen again.

I tested this in the official RS client and it does not happen there, nor any other application.

**EDIT** I just disabled the GPU setting and the problem completely went away, as soon as the GPU setting is re-enabled the problem arises again, it appears this is the root cause.

**To Reproduce**
1. Click on runelite client to bring it into focus
2. Move mouse around at any speed
3. Observe a trailing mouse cursor behind your actual one.

**Expected behavior**
No trailing mouse cursor and the mouse to perform the same as the rest of windows 10.

**Screenshots**
Here is a gifv (https://imgur.com/a/xD1BWaF) of me moving the mouse and then clicking and the trailing mouse cursor appearing. This behaviour doesn't look quite as bad as it actually is in the low framerate video (It's really annoying on a 144hz monitor).

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.25
 - Launcher version: 1.5.2

**Additional context**

**Comment by Alexsuperfly** [comment] 2019-11-14 20:46
duplicate of #9891 

solution: https://github.com/runelite/runelite/wiki/GPU-FAQ#there-are-two-mouse-cursors-when-gpu-is-on

**Closed** 2019-11-14 20:51 UTC
Labels: duplicate
