### ISSUE TITLE
The ability to have the sidebar be opened upon launching.

### ISSUE THREAD

**Issue by saw141** [runelite/runelite#11885] opened 2020-06-12 10:54 UTC
I just think it'd be really nice if this were an option to just have the sidebar automatically expanded, and potentially select which tab it opens to.

**Comment by Nightfirecat** [comment] 2020-06-14 08:07
Duplicate of #2312

**Closed by Nightfirecat** 2020-06-14 08:07 UTC
Labels: duplicate

**Comment by saw141** [comment] 2020-06-21 04:25
Well it's been a point of interest for over 2 years, if possible we should make it happen.
