### ISSUE TITLE
FPS Control Plugin can cause the Runelite sidebar to become unresponsive

### ISSUE THREAD

**Issue by SwampyApple** [runelite/runelite#14613] opened 2022-01-20 14:55 UTC
**Describe the bug**
When using the FPS Control plugin to limit the unfocused FPS it will immediately reduce the Runelite client refreshrate when clicking on the sidebar outside of the osrs game window. With a low enough unfocused FPS target this will cause the runelite sidebar to be poorly responsive as it will stutter on all input.

**To Reproduce**
1. Go to the FPS Control plugin settings menu
2. Set the Unfocused FPS target to 5 and enable the unfocused FPS target limit
3. Apply the settings
4. Click in the game window to get the regular FPS target
5. Click on the RL sidebar and try to search for settings by typing or interact with it in other ways. It is especially apparent when you try to highlight your search string with the mouse.
6. Inputs will be missed and the experience is generally poor

**Expected behavior**
The osrs game client window will be unfocused and capped but the RL client window should still refresh at an independent rate.

**Environment:**
 - OS: [macOS] (M1)
 - RuneLite version: [1.18.10]
 - Launcher version: [2.3.0]
 - GPU plugin enabled. It seems like this issue isn't present with the GPU plugin disabled.

**Comment by Nightfirecat** [comment] 2022-07-10 05:14
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 05:14 UTC
Labels: platform:macos
