### ISSUE TITLE
Hide (others) Random Event NPCs?

### ISSUE THREAD

**Issue by aekramer** [runelite/runelite#14614] opened 2022-01-20 17:23 UTC
****Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A plugin that hides random event NPCs, either all or only for other players.

**Describe alternatives you've considered**
Writing my own 3rd party plugin for the plugin hub?

**Additional context**
At the moment, if you enable Entity hider (NPCs) all NPCs will be hidden, but occasionally you will require access to only a few ones.
If you are in public skilling areas (for example ZMI) the altar/trapdoor/banker are all often swarmed with others their random event NPCs which can be quite annoying.

I understand a specific white list is not allowed, but perhaps if it only hides random events it would be?

**Comment by Hydrox6** [comment] 2022-01-20 17:25
Duplicate of #2310

**Closed by Hydrox6** 2022-01-20 17:25 UTC
