### ISSUE TITLE
Wilderness multi zone line

### ISSUE THREAD

**Issue by kgozi** [runelite/runelite#1922] opened 2018-04-25 16:15 UTC
This is a huge feature which I would leave my OSB Pro for, an overlay which shows multi/single zones in the wilderness, currently, Exilent uses this feature.

![multi](https://user-images.githubusercontent.com/38731474/39258512-21aa3d56-4882-11e8-9146-0b8230db6956.JPG)

**Comment by deathbeam** [comment] 2018-04-25 16:50
Duplicate of #1764

**Closed by deathbeam** 2018-04-25 16:50 UTC
