### ISSUE TITLE
Newly spawned Implings do not get Highlighted

### ISSUE THREAD

**Issue by slasso93** [runelite/runelite#5491] opened 2018-09-14 16:59 UTC
When catching implings in Puro Puro, newly spawned implings do not get highlighted.

**To Reproduce**
1. Go to Puro Puro
2. Catch an impling and wait for it to respawn (I am using the northwest corner where nature, magpie, ninja, dragons spawn.
3. After about two minutes, the impling respawns but no highlighting unless i hop worlds and hop back (I tried with show spawn locations on and off. These imps are dynamic spawning and spawn in the general corner area, not a specific tile).

Impling should be highlighted on spawn. Not tested on static spawning imps.

![broken highlight](https://user-images.githubusercontent.com/20825067/45563945-e081d400-b81c-11e8-95ac-e4341f5c37b9.png)
![broken highlight2](https://user-images.githubusercontent.com/20825067/45563948-e37cc480-b81c-11e8-85f8-8c3a6865c5db.png)

**Environment**
 - OS: Windows 10
 - RuneLite version: 1.4.17
 - Launcher version: 1.6

**Comment by deathbeam** [comment] 2018-09-14 17:01
Duplicate of #4940

**Closed by deathbeam** 2018-09-14 17:01 UTC
