### ISSUE TITLE
Weapon swing timer

### ISSUE THREAD

**Issue by Bodinodo** [runelite/runelite#12435] opened 2020-09-02 05:44 UTC
Would it be possible to code a progressbar that fills to show when you and your enemy will hit?

For example, when I fight a Mountain Troll with my Dragon Scimitar I have two progress bars pop up (for example below the mountain trolls health bar). When my progress bar is full, I will swing with my Dragon Scimitar, and when the Troll's bar is full, he will hit me and so on. This would make it a lot easier to prayer flick consistently.

**Comment by Broooklyn** [comment] 2020-09-02 06:02
Duplicate of #4087.

Next attack prediction is also prohibited by [Jagex's statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients)

**Closed by Broooklyn** 2020-09-02 06:02 UTC
