### ISSUE TITLE
Possibility to make a custom Farming Timer list?

### ISSUE THREAD

**Issue by mertino11** [runelite/runelite#5561] opened 2018-09-20 14:03 UTC
Right now I am currently farming the following:

Yew Trees
Papaya Trees
Calquat Trees
Mahogany Trees
Spirit Trees

However, they are all separated in different tabs/categories.

I was wondering if you can make a new tab and add patches/trees to see all those trees above in one tab.

Like the following: https://imgur.com/a/uMABZng

(of course with the ability to scroll instead of showing everything at once :)

**Comment by deathbeam** [comment] 2018-09-20 21:42
Duplicate of #4834

**Closed by deathbeam** 2018-09-20 21:42 UTC
