### ISSUE TITLE
Client crashed when it tried to take a screenshot after completing Jad

### ISSUE THREAD

**Issue by theinterestingstory** [runelite/runelite#10808] opened 2020-02-15 17:05 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I finished Jad and the client crashed right when I was TP'd out of the Fight Cave. I think it was trying to take a screenshot at the exact time. There is no screenshot in the folder.

**To Reproduce**
Enable screenshots. Finish Jad. Crash.

**Expected behavior**
Not to crash. To have successfully taken a screenshot.

**Screenshots**
No screenshots available in the folder.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - RuneLite version: 1.6.6.1
 - Launcher version: 2.1.0

I do have the GPU plugin enabled as well.

**Additional context**

Logs show nothing:

Client: 
```
2020-02-15 10:32:36 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-02-15 10:32:36 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-02-15 10:32:37 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 436887693.44
2020-02-15 10:32:37 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-02-15 10:32:38 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-02-15 10:32:39 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 3135ms. Uptime: 4973ms
2020-02-15 10:32:39 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,28,809x1250,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x1250,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@106c5353,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
```

Launcher: 
```
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - RuneLite Launcher version 2.1.0
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2020-02-15 10:32:35 [main] WARN  net.runelite.launcher.PackrConfig - error updating packr vm args!
java.io.FileNotFoundException: /tmp/.mount_RuneLi8oqrfq/config.json (Read-only file system)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at net.runelite.launcher.PackrConfig.updateLauncherArgs(PackrConfig.java:84)
	at net.runelite.launcher.Launcher.main(Launcher.java:239)
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-1.6.6.1.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of slf4j-api-1.7.25.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-classic-1.2.3.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-core-1.2.3.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jopt-simple-5.0.1.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guava-23.2-jre.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jsr305-1.3.9.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of error_prone_annotations-2.0.18.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of j2objc-annotations-1.1.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of animal-sniffer-annotations-1.14.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guice-4.1.0-no_aop.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of javax.inject-1.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of aopalliance-1.0.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gson-2.8.5.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of substance-8.0.02.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of trident-1.5.00.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-text-1.2.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-lang3-3.7.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-amd64.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-i586.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-amd64.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-i586.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-amd64.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-i586.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-linux-amd64.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-linux-i586.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of archive-patcher-1.0.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-4.5.1.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-platform-4.5.1.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runelite-api-1.6.6.1.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-patch-1.6.6.1.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of http-api-1.6.6.1.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okhttp-3.7.0.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okio-1.12.0.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-csv-1.4.jar
2020-02-15 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of discord-1.1.jar
```

**Comment by Nightfirecat** [comment] 2020-02-18 03:08
Your client and launcher logs do not show any information which would indicate the cause of this crash. Do you have any other log files in your logs folder aside from client and launcher logs?

**Comment by theinterestingstory** [comment] 2020-02-24 00:42
I do not. I only have client and launcher, sadly.

If I go back and try to reproduce, is there something I should do?

**Comment by Nightfirecat** [comment] 2020-02-25 04:10
Not that I can think of. I would expect to see a `jvm_crash_pid` file in your logs directory if you see a client crash. For now, I am closing this issue as the information provided isn't sufficient to meaningfully troubleshoot for this bug. If you run into it again, take a look in your logs directory and see if you can find such a file. (or find some kind of fatal error message in your `client.log` file) If you do, feel free to re-open this issue with that new information.

**Closed by Nightfirecat** 2020-02-25 04:10 UTC
Labels: needs-information
