### ISSUE TITLE
Add the abiltity to toggle between OSB API prices and GE

### ISSUE THREAD

**Issue by HSJ-OSRS** [runelite/runelite#1670] opened 2018-04-18 20:47 UTC
the sole reason i havent switched to using this as my main client is some of the less traded items prices can be off by as much as 50m for example Ely's ge price is 665m when its trading for 690m and then there are a bunch of low traded clue items that show they are worth 500K+ when they trade for less than 50k im not asking for it to only use OSB API prices but atleast add a toggle for it please

**Comment by tr33s** [comment] 2018-04-18 20:53
See also #733

**Comment by deathbeam** [comment] 2018-04-18 21:11
Duplicate of #733

**Closed by deathbeam** 2018-04-18 21:11 UTC
