### ISSUE TITLE
Persistent map icons.

### ISSUE THREAD

**Issue by swordsith** [runelite/runelite#5479] opened 2018-09-13 21:25 UTC
**Describe the bug**
Custom runelite icons are persistent above menus in the fullscreen map.

**To Reproduce**
1. Open the floating world map
2. Move bottom middle of screen over a custom runelite map icon.
3. Open the level selector at the bottom of the floating map
4. See icon is above the menu.

**Expected behavior**
Like other icons runelite ones should not show up above the menu.

**Screenshots**
https://i.imgur.com/n359DpU.png
You can see the cooking guild teleport is above the level selector.

**Environment (please complete the following information):**
OS: Windows 10
 - RuneLite version: 1.4.17
 - Launcher version: 1.6.0

**Additional context**
This can also bee seen with the overview map, but not the left map menu.

**Comment by deathbeam** [comment] 2018-09-13 21:56
Duplicate of #3264

**Closed by deathbeam** 2018-09-13 21:56 UTC
