### ISSUE TITLE
OSBuddy Pricing on Hover in Inventory

### ISSUE THREAD

**Issue by Isafdor** [runelite/runelite#6555] opened 2018-11-18 02:06 UTC
We have the option to enable/toggle OSBuddy Pricing when accessing the GE but not when we hover over or examine items in our inventory only High Alch and Exchange Guide Price.

I think it would be extremely beneficial to everyone if a toggle was added to the Item Prices plugin that allows us to enable OSBuddy actively traded prices.

If not it would be nice to see RuneLite work on their own GE tracker that tracks actively traded prices as we all know GE's Guide prices are never accurate for getting sales and buying items.

New UI with Toggle
![new](https://user-images.githubusercontent.com/45134576/48667798-85978200-ead6-11e8-8665-3743a4cfb39a.png)

Old UI
![2](https://user-images.githubusercontent.com/45134576/48667801-8f20ea00-ead6-11e8-9200-3b2cc0aace2a.PNG)

**Comment by deathbeam** [comment] 2018-11-18 11:17
Basically duplicate of #3927, read discussion there why this is not very good idea

**Closed by deathbeam** 2018-11-18 11:17 UTC
