### ISSUE TITLE
JOGL window is not closed properly on client exit, causing leftover processes running and client breakage

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#6646] opened 2018-11-23 12:35 UTC
We never call plugin shutDown on client close, and so the GL resources are never freed properly, what can cause major issues on some platforms (hanging jogl/javaw processes in task manager and GPU plugin breakage after client restart).

**Comment by Pineapplezz** [comment] 2018-11-29 19:18
I am running Ubuntu 18.04 and Runelite often crashes after trying to close the client. The message, "Are you sure you want to exit?" Comes up so I click yes but nothing happens, clicking close nothing happens(The message isn't locked either, clicking X makes it pulse still), and I can't close the client without having to go to the task manager and killing the process. I have noticed this occures more often on older hardware, ALTHOUGH it still happens on newer hardware.

**Comment by Abextm** [comment] 2019-03-13 02:48
The fix for this never worked and causes #7633

**Comment by Chrushop** [comment] 2020-10-27 19:35
Why does this keep being closed when there is no apparent fix? I have reinstalled Runelite and it still fails to load being stuck on Prepared Sound Engine

**Comment by Nightfirecat** [comment] 2022-07-10 04:04
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:04 UTC
Labels: bug, gpu
