### ISSUE TITLE
Lumbridge Elite Diary: RC Requirement not showing level needed. 

### ISSUE THREAD

**Issue by PapaRed99** [runelite/runelite#13519] opened 2021-04-23 19:55 UTC
**Describe the bug**
Runecrafting level requirement is not shown for Elite Lumbridge & Draynor diary. 

**To Reproduce**
1. Go to 'Achievement Diaries'
2. Click on 'Lumbridge & Draynor'
3. Scroll down to 'Elite'
4. Only states: "Craft 140 or more Water runes at once from Essence."

**Expected behavior**
Show required Runecrafting level to produce 140 Water runes at one time. 
Expected detail "(76 Runecrafting)"

**Screenshots**
<img width="435" alt="Screen Shot 2021-04-23 at 3 53 43 PM" src="https://user-images.githubusercontent.com/83092963/115923437-3ba3ea80-a44c-11eb-97bc-6b6139629a96.png">

**Environment (please complete the following information):**
 - OS: [macOS]
 - RuneLite version: [1.6.0]
 - Launcher version: [1.6.0]

**Comment by Nightfirecat** [comment] 2021-04-23 20:01
Duplicate of #13480. We've fixed this in master already, it will be fixed in our next release.

**Closed by Nightfirecat** 2021-04-23 20:01 UTC
Labels: duplicate
