### ISSUE TITLE
Show where to kill slayer monsters

### ISSUE THREAD

**Issue by Asymons** [runelite/runelite#5065] opened 2018-08-22 19:25 UTC
Using the same indicators as we do for clue scroll locations, we could do the same to show where to kill slayer monsters. Could even suggest what teleport to use to get there quickest.

Could start slow and start with common ones (nechs, gargoyles etc) with settings to determine which one you want to go to.

Would save the hassle in referencing a map constantly and would be super useful for those early obscure slayer assignments.

**Comment by deathbeam** [comment] 2018-08-22 19:26
Duplicate of #3843

**Closed by deathbeam** 2018-08-22 19:26 UTC
