### ISSUE TITLE
STASH unit plugin

### ISSUE THREAD

**Issue by Floukru** [runelite/runelite#2957] opened 2018-05-19 16:22 UTC
So basically what I'm suggesting is a plugin that is called "stash unit". Where it'll you if you already constructed the stash unit and have items inside it or not. (Enum?)

So, how to use the plugin is, when doing a clue scroll.. You'll always have under the info box on the left 

"Stash Unit: Yes" //If you built the unit and have items inside it
"Stash Unit: Empty" //If you built the unit and have no items inside it
or 
"Stash Unit: No" //Didn't build one

It'll update every time you're in the area/region.. And once you click on it?

I was grinding like 50 medium clues today.. I was questioning myself if I have stash unit built or not.. so yea.

**Comment by deathbeam** [comment] 2018-05-19 16:27
Duplicate of #1742 and #1662

**Closed by deathbeam** 2018-05-19 16:27 UTC
