### ISSUE TITLE
Client repeatedly crashing

### ISSUE THREAD

**Issue by Dethbyzebra** [runelite/runelite#16878] opened 2023-08-03 19:43 UTC
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Client repeatedly crashing when doing a wide variety of activities, sometimes even when completely AFK. Have tried to uninstall and reinstall the client but still running into the same issue.

### RuneLite version

1.10.9.1
2.6.4

### Logs

2023-08-03 00:35:48 CDT [Client] ERROR client-patch - Client error
java.lang.ArrayIndexOutOfBoundsException: Index -817582258 out of bounds for length 104
	at iz.zq(iz.java:1141)
	at iz.kn(iz.java)
	at iz.uu(iz.java:54229)
	at bb.iz(bb.java:4893)
	at bl.ls(bl.java:10735)
	at bl.ls(bl.java:10766)
	at az.lv(az.java:10630)
	at client.kz(client.java:4623)
	at client.be(client.java:1167)
	at bq.bb(bq.java:389)
	at bq.run(bq.java:343)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Nightfirecat** [comment] 2023-08-03 19:49
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run:
```
"%localappdata%\runelite\runelite.exe" --safe-mode
```

Or on Mac: In Terminal, run:
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --safe-mode
```

**Comment by Dethbyzebra** [comment] 2023-08-03 20:26
Just did some testing with safe mode and it worked for a little while but still crashed and received this jvm_crash_pid.

[jvm_crash_pid_6624.log](https://github.com/runelite/runelite/files/12254776/jvm_crash_pid_6624.log)

**Comment by Nightfirecat** [comment] 2023-08-03 20:48
Duplicate of #10628, we don't know what causes this crash.

**Closed by Nightfirecat** 2023-08-03 20:48 UTC
Labels: duplicate
