### ISSUE TITLE
Drop log table disappears when given a blank (only 100% items) drop, if those items are toggled off.

### ISSUE THREAD

**Issue by AncientDawn** [runelite/runelite#6321] opened 2018-11-03 04:56 UTC
**Describe the bug**
When doing slayer (specifically only tested at Kurasks so far) and you get bones only drop the table will disappear in its [ entirety, while preserving the number killed and value.](https://i.gyazo.com/thumb/1200/cb5463437712a68eeec746fe56b6b943-png.jpg)

**To Reproduce**
1. Go to Kurasks
2. Get bones only drop while bones drops are toggled off.
3. Cry

**Expected behavior**
Table will disappear. Following this if gaining any other drop it will reappear -- seems to be a purely visual bug.

**Screenshots**
[This](https://i.gyazo.com/thumb/1200/cb5463437712a68eeec746fe56b6b943-png.jpg)

**Environment (please complete the following information):**
- Windows 10
- Runelite v.1.4.24
- Launcher v.1.6.0

**Comment by AncientDawn** [comment] 2018-11-03 05:00
Small note: Saw another issue similar but it claimed to be from Ring of Wealth equip. I can confirm either this is an entirely separate issue or not at all caused by the ring of wealth as this bug happens with or without the ring equipped -- this is almost certainly caused by the 100% drop being toggled off, as when I toggled it back on and got a 100% drop it did not occur, whereas otherwise, it had a 100% occurrence rate.

**Comment by deathbeam** [comment] 2018-11-03 17:42
Duplicate of #6240

**Closed by deathbeam** 2018-11-03 17:42 UTC
