### ISSUE TITLE
Add damage prediction overheads or along side the exp drop

### ISSUE THREAD

**Issue by bobthesly** [runelite/runelite#5420] opened 2018-09-10 09:27 UTC
Make it so when you attack a monster the health left bar on the top left is updated at the same time as an exp drop, or a preloaded damage splash (different color even) based on exp drop

**Comment by Unmoon** [comment] 2018-09-10 09:30
I believe OSB Matthew commented on this discussion some months ago, and said that Jagex had asked them to remove this kind of plugin from OSB. Considering how long ago it was, it's likely that Jagex's stance has changed.

**Comment by deathbeam** [comment] 2018-09-10 10:11
Duplicate of #4055

**Closed by deathbeam** 2018-09-10 10:11 UTC
Labels: enhancement
