### ISSUE TITLE
Add a chat command for total collection log slots earned

### ISSUE THREAD

**Issue by AngelaScape** [runelite/runelite#14802] opened 2022-03-30 02:11 UTC
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
A chat command that shows the total collection log slots you have earned similar to how killcount commands work.

**Additional context**
It would be really cool to share your log progress with others.

**Comment by Hydrox6** [comment] 2022-03-30 08:04
Duplicate of #9025

**Closed by Hydrox6** 2022-03-30 08:04 UTC
