### ISSUE TITLE
2010 Interface Style Issue

### ISSUE THREAD

**Issue by iStarbucks** [runelite/runelite#5123] opened 2018-08-25 12:52 UTC
**Describe the bug**
When using the 2010 interface style tool, the inventory icon has moved to be underneath the prayer icon - making the stone that's supposed to house the backpack icon, blank. 

**Screenshots**
![image](https://user-images.githubusercontent.com/42696248/44618457-0810fc80-a86e-11e8-922b-439bc443833f.png)

**Environment (please complete the following information):**
Latest release: 1.4.14

**Comment by deathbeam** [comment] 2018-08-25 12:53
Duplicate of #5105

**Closed by deathbeam** 2018-08-25 12:53 UTC
