### ISSUE TITLE
Unable to paste username or password into client

### ISSUE THREAD

**Issue by douglasg14b** [runelite/runelite#4684] opened 2018-08-03 20:46 UTC
**Describe the bug**
Unable to paste login credentials into client, other clients support this.

**To Reproduce**
1. Open rslite
2. Try pasting username or password from a password manager

**Expected behavior**
Password to paste into login box

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - RuneLite version: 1.4.10
 - Launcher version: 1.6.0

**Comment by Nightfirecat** [comment] 2018-08-03 20:47
Duplicate of #3793

**Closed** 2018-08-03 20:51 UTC
