### ISSUE TITLE
mac m1 pro UI - no access to plugin hub sidebar, screenshots etc

### ISSUE THREAD

**Issue by downloader55** [runelite/runelite#17424] opened 2024-01-27 19:01 UTC
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

os 12.6 Monterey

### Bug description

Opened application and UI was different. No access to plugin hub, screenshot tool etc. Also for the first time it shows a fullscreen option (green top left) which has never appeared nor would I use

Client had changed over last few days a few times. Just visual apart from client size changing randomly occasionally and having to reset this in the plugin 'runelite'

Screenshots attached of how it was originally (Tuesday as an example), Friday (yesterday) where visually it changed, then today where it's unusable.

Note that it appears some plugins are functioning, e.g. bank tag layouts and ground items appear, but I cannot access the sidebar

### Screenshots or videos

<img width="1240" alt="Tuesday" src="https://github.com/runelite/runelite/assets/94248809/aaaaea11-b8ad-493a-bd06-7364721b6be7">
<img width="1162" alt="Friday" src="https://github.com/runelite/runelite/assets/94248809/b26b1ec7-2886-4a8c-99a9-fad2fb522ed3">
<img width="1256" alt="Today" src="https://github.com/runelite/runelite/assets/94248809/3b209931-64f4-459c-87d9-0eb6660cc0ed">

### RuneLite version

2.6.11 it seems as i have re-downloaded which didn't solve it.

**Comment by reganlawton** [comment] 2024-02-15 05:47
Seems like a dupe of #14642 Did you try  Ctrl/Cmd + F11 @downloader55 ?

**Closed** 2024-05-23 14:15 UTC
Labels: needs-triage
