### ISSUE TITLE
Suggestion: Make Chambers of Xeric layout overlay stay open after starting raid

### ISSUE THREAD

**Issue by waltteri151** [runelite/runelite#3795] opened 2018-06-14 17:38 UTC
Currently if you start a raid the overlay disappears and if I don't screenshot the layout I usually forget and it would be nice to know what's next even though I know it's a good raid.

Another option if it's too intrusive is to have it listed in the chatbox so you could scroll up to check

Apologies if this feature is somewhere in the settings but I couldn't find it.

**Comment by Pashweetie** [comment] 2018-06-14 18:39
Yeah I'd like it as well if it stayed open and maybe marked your progess or next room. Be interested in looking into it, we dont have a wiki page for it yet so I dont blame you if you missed a feature i dont have my computer right now so i cant check

**Comment by deathbeam** [comment] 2018-06-14 20:27
Duplicate of #1871

**Closed by deathbeam** 2018-06-14 20:27 UTC
