### ISSUE TITLE
Aerial Fishing Spot Tiles Occasionally Showing Incorrectly - Fishing Plugin

### ISSUE THREAD

**Issue by Elite-Mercenary-Raven** [runelite/runelite#15946] opened 2022-11-22 06:00 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Win10

### Bug description

Occasionally when aerial fishing, RL will incorrectly highlight fishing spots that aren't there any more. They start to build up after a long session and can be distracting. This might be caused by tabbing to another app then back to RL. I'm not sure. 

If a real fishing spot spawns on top of a falsely marked one, it doesn't automatically clear it. Teleporting away doesn't clear them either. Logging out and back in again doesn't seem to clear them consistently, but seems to work sometimes. 

Coming back to type this-- I just did a little experiment. I uninstalled ver 2.4.0 (which I was testing my fps with at ToA) and reinstalled 2.5.0. I must have been aerial fishing on 2.5.0 before because I came back to see different falsely marked fishing spots. I believe they were saved from another session, but idr when I was last there. 

I also just noticed that logging out for a few minutes cleared 1 of the mis-marked spots. So weird.

The attached image is from a session using 2.4.0. In my 2.5.0 session the mis-marked spots are all different, none overlapping. 

### Screenshots or videos

![Aerial Fishing Glitch](https://user-images.githubusercontent.com/112131069/203228804-7b3f42d3-c186-43b7-8519-1364e7262a72.PNG)

### RuneLite version

1.9.3
32 bit 2.4.0 

and

1.9.3
32 bit 2.5.0

**Comment by Nightfirecat** [comment] 2022-11-22 06:15
Duplicate of #7702

**Closed by Nightfirecat** 2022-11-22 06:15 UTC
Labels: duplicate
