### ISSUE TITLE
Client crashes seemingly randomly

### ISSUE THREAD

**Issue by Dane-Ramen** [runelite/runelite#16357] opened 2023-03-08 20:34 UTC
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Playing the game it seems to randomly crash the last few days. I wish I could give details but it has happened at both tempeross, graador and the GE. I fully uninstalled runelite, lost all my settings, and when standing at the GE setting them back up it crashed again.

### RuneLite version

Runelite version 1.9.11.2
Oldschool version Rev 211
Launcher version 2.2.0

### Logs

[client.log](https://github.com/runelite/runelite/files/10924220/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10924221/launcher.log)
[jvm_crash_pid_17592.log](https://github.com/runelite/runelite/files/10924227/jvm_crash_pid_17592.log)
[jvm_crash_pid_20888.log](https://github.com/runelite/runelite/files/10924228/jvm_crash_pid_20888.log)
[jvm_crash_pid_8376.log](https://github.com/runelite/runelite/files/10924229/jvm_crash_pid_8376.log)

**Comment by Dane-Ramen** [comment] 2023-03-30 08:46
more reports
[jvm_crash_pid_24920.log](https://github.com/runelite/runelite/files/11109635/jvm_crash_pid_24920.log)
[jvm_crash_pid_23056.log](https://github.com/runelite/runelite/files/11109637/jvm_crash_pid_23056.log)
[jvm_crash_pid_26668.log](https://github.com/runelite/runelite/files/11109638/jvm_crash_pid_26668.log)
[jvm_crash_pid_17468.log](https://github.com/runelite/runelite/files/11109640/jvm_crash_pid_17468.log)
[jvm_crash_pid_13516.log](https://github.com/runelite/runelite/files/11109642/jvm_crash_pid_13516.log)
[jvm_crash_pid_21744.log](https://github.com/runelite/runelite/files/11109645/jvm_crash_pid_21744.log)

**Comment by johnyuki** [comment] 2023-05-22 14:33
This happens often to me too, I'd say at least once per day. It happens to me mostly when I am buying on the GE and I press the Collect All button in the top right. I'll get logs next time it happens.

**Comment by Nightfirecat** [comment] 2023-05-22 17:45
Duplicate of #10628, we don't know what causes this crash.

**Closed by Nightfirecat** 2023-05-22 17:45 UTC
Labels: duplicate
