### ISSUE TITLE
Slayer Monster Wiki in Slayer Gem or Slayer plugin popup buff thing

### ISSUE THREAD

**Issue by keeks22** [runelite/runelite#11379] opened 2020-04-27 02:11 UTC
**Is your feature request related to a problem? Please describe.**
If I don't know a slayer monster I always wiki it to see what if I can range / mage / or melee it

**Describe the solution you'd like**
The Runelite client knows my slayer monster so I would like to be able to right click my slayer gem or the slayer popup thing and go straight to the monster page, and not have to type it out in the existing feature.  Would save a lot of time and annoyance

**Describe alternatives you've considered**
Slayer Gem, Slayer Helmet, Slayer popup thing could all be used

**Additional context**
Just like the current "Check" option on a slayer gem, just a "Wiki" option added :)

**Comment by Nightfirecat** [comment] 2020-04-27 06:51
Duplicate of #8229

**Closed by Nightfirecat** 2020-04-27 06:51 UTC
Labels: duplicate
