### ISSUE TITLE
Custom cursor don't limit to 32x32

### ISSUE THREAD

**Issue by kentor** [runelite/runelite#12344] opened 2020-08-15 05:39 UTC
**Is your feature request related to a problem? Please describe.**
I'm using the custom cursor.png for the Custom Cursor plugin, but the image is limited to 32x32. 

**Describe the solution you'd like**
Not limit the size to 32x32. I would like a bigger cursor

**Describe alternatives you've considered**
None

**Additional context**
I play on a 4k screen, and play on 2x integer scaled fixed mode. My system cursor is typically 19 pixels tall. I want to double my cursor to 38 pixels tall.

**Comment by Nightfirecat** [comment] 2020-08-15 06:37
Duplicate of #8782

**Closed by Nightfirecat** 2020-08-15 06:37 UTC
Labels: duplicate
