### ISSUE TITLE
Incorrect Tool Tip on Items

### ISSUE THREAD

**Issue by Sokarip** [runelite/runelite#6936] opened 2018-12-13 23:20 UTC
**Describe the bug**
Farming cape (possibly more) incorrectly shows prayer bonus when not trimmed.

**To Reproduce**
1. Have farming cape
2. Don't have otehrs

**Expected behavior**
+0 Prayer for untrimmed capes

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.4]
 - Launcher version: [e.g 1.6.0]

**Comment by deathbeam** [comment] 2019-01-13 13:56
As #7048 is better worded with some images, closing this one as duplicate of that one

**Closed by deathbeam** 2019-01-13 13:56 UTC
Labels: item-stats
