### ISSUE TITLE
Farm timer is useless because farm clocks are not universal

### ISSUE THREAD

**Issue by yoboseo** [runelite/runelite#3312] opened 2018-05-25 20:38 UTC
I feel this fact isn't well known, but ever since the farming rework there has not been one global farm clock shared by all as there once was, but instead multiple clocks spread out. So when it tells me my herbs are going to be done at 17:20, for some that may be accurate, but for others like myself that time is not correct at all. I'm not sure what the best solution would be but as it stands the farm timer as it is currently is completely inaccurate.

I'm familiar enough with farm ticks to know when my herbs are actually going to be done, but for some I imagine confusion when it says something is done and they arrive at the patch to find that it isn't.

**Comment by Nightfirecat** [comment] 2018-05-25 21:41
Duplicate of #2491?

**Closed** 2018-05-25 21:42 UTC
