### ISSUE TITLE
Boosts Information tool tip toggle

### ISSUE THREAD

**Issue by Honestidade** [runelite/runelite#4517] opened 2018-07-27 01:05 UTC
Would be nice to be able to toggle the tooltip that pops up when hovering over your boosts and also slayer task infoboxes.

https://i.imgur.com/UmuEsV3.png

https://i.imgur.com/u2F5pwP.png

**Comment by deathbeam** [comment] 2018-07-27 06:09
Duplicate of #3342

**Closed by deathbeam** 2018-07-27 06:09 UTC
