### ISSUE TITLE
Cannon:  Show World

### ISSUE THREAD

**Issue by theSpacePilot** [runelite/runelite#10120] opened 2019-10-22 23:18 UTC
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I use quick world hopper to avoid pkers in the wildy with my cannon but i forget what world my cannon was originally on.  

**Describe the solution you'd like**
I would like a Heads-up display (like in example picture provided) to be included when hovering over the cannon countdown timer with your mouse is performed.  

**Describe alternatives you've considered**
Remembering to place my cannon in an easily rememberable world or to remember to check what world my cannon is originally on in the first place.  Would be helpful considering nothing is there as of now.

**Additional context**

![Cannon World Switcher](https://user-images.githubusercontent.com/13990215/67342584-66c01d80-f4e7-11e9-80f3-1d4363733728.png)

**Comment by deathbeam** [comment] 2019-10-22 23:19
Duplicate of #3700

**Closed by deathbeam** 2019-10-22 23:19 UTC
