### ISSUE TITLE
Highlight all emote step related items.

### ISSUE THREAD

**Issue by SirDylan** [runelite/runelite#11009] opened 2020-03-14 04:34 UTC
There's a ton of random items which are required for certain clue steps. When playing iron man mode it's especially hard to know what you should keep, and what you should alch.

It would be awesome for all emote/clue related items to be highlighted in your inventory.
They could be color coded to easily identify which level of clue they are required for.

Option to no longer highlight the items if they are already in your STASH unit.

**Comment by Nightfirecat** [comment] 2020-03-14 04:35
Duplicate of #3105

**Closed by Nightfirecat** 2020-03-14 04:35 UTC
Labels: duplicate
