### ISSUE TITLE
Number formatting improvement suggestion

### ISSUE THREAD

**Issue by Meow764** [runelite/runelite#1974] opened 2018-04-26 12:45 UTC
* Culture specific number formatting
  * So the client seems to format numbers based on your culture information. 
Ok, that's pretty cool. However, I (and probably other people as well) do not like this. My culture's number formatting looks very out of place for rs
  * What does it look like in my culture?
    * 14 583 instead of 14,582 (14 thousand)
    * 126,10 instead of 126.10 (decimal)
    * [Ugly formatting in action](https://image.prntscr.com/image/y5uNJs23QGCf-TL25nN5UA.png)
  * So maybe a little checkbox to check if you want to use your own culture's number formatting, or traditional US formatting, or maybe even the ability to choose which culture's formatting you want to use, or a custom format

**Comment by deathbeam** [comment] 2018-04-26 12:48
This is a bit subjective, and adding toggle for it do not makes sense at all. I would just leave it as it is. You can always change your OS number formatting if you dislike it so much.

**Comment by Meow764** [comment] 2018-04-26 12:51
I don't see how there could be a downside to this addition, or how it could not make sense.
And me disliking what it looks like on rs (looks very out of place for rs, as I said) doesn't mean I want to change it for my whole operating system.

**Comment by deathbeam** [comment] 2018-04-26 13:08
Ability to choose how your numbers are displayed in sidebar are more nit-picking than anything. Probably making the number formatter just follow the OSRS number formatting would be nice.

**Comment by Meow764** [comment] 2018-04-26 13:31
It's not only in the sidebar, but also everywhere in the viewport where it draws text (as seen from my screenshot). So in like item prices, combat level, etc.

**Comment by deathbeam** [comment] 2018-06-28 14:00
Duplicate of #4054 (as that one is more nicely written)

**Closed by deathbeam** 2018-06-28 14:00 UTC
Labels: feature-request
