### ISSUE TITLE
Farming favorites

### ISSUE THREAD

**Issue by TerrorNisse** [runelite/runelite#14478] opened 2021-12-14 10:40 UTC
Time tracking plugin

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [I need to look in each category to see what is ready and not (even if I have notifications ON)]

**Describe the solution you'd like**
I would like to see a list of either favorites or only the one I have alerts on in a list. The overview just doesn't do it for me sadly

**Describe alternatives you've considered**
None, which is why I am requesting a favorites list :D

**Additional context**
None.

**Comment by Hydrox6** [comment] 2021-12-14 11:15
Duplicate of #3056

**Closed by Hydrox6** 2021-12-14 11:15 UTC
