### ISSUE TITLE
Runelite with Google Translate Chat Functionality 

### ISSUE THREAD

**Issue by Molay911** [runelite/runelite#13036] opened 2021-01-09 23:59 UTC
**Is your feature request related to a problem? Please describe.**
Yes, there are many STARVING Venezuelans playing OSRS that NEED TO FKING EAT.

A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]  I'm frustrated knowing I either have to learn spanish or germany or russian to speak to EVERY PLAYER IN THE GAME. #UniversalLanguagePlz

**Describe the solution you'd like**

I really really really would like it if you could somehow add, AT THE VERY LEAST, a Google Translate plugin with chat functionaility or possible an automatic converter from all languages directly to your CHOSEN language.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

There are none, just do it?

**Additional context**

Please, I will pay this project handsomely for this amazing feature, I promise.

**Comment by raiyni** [comment] 2021-01-10 00:00
duplicate of #10591

**Closed by raiyni** 2021-01-10 00:00 UTC
