### ISSUE TITLE
Seperate tabs for current session loot and total loot for each entity

### ISSUE THREAD

**Issue by Shabyoob** [runelite/runelite#14318] opened 2021-10-28 03:50 UTC
I always like to reset my loot tracker for a boss whenever I start a new session to farm it. I get frustrated when I reset my boss loot kills to track the new session. I also would like to see the total loot I have accumulated since I started farming the boss (at least since I enabled loot tracker obv).

Having two tabs at the top of the loot tracker, one for current session loot and one for total loot all the way (or what is possible) from when the loot tracker was enabled for a specific entity (zulrah,vorkath,red dragon, etc...)

Another option I thought about, although not very practical possibly, I would like to store the loot tracker data/content into a bundle/chest that stays in the loot tracker itself. For example I tracked the loot of my 1-50 kc of zulrah, I would now like to put all of the loot I got in a bundle that appears in the loot tracker of the boos, when you hover over it it would tell you that kc, date and value. You can then proceed to hide this and start your new loot session kc 51-60. When I would like to see all of my loot I would just unpack the boxes see all of what I got from kc 1-60 and then repack for a new session.

Another option, would be having two tabs at the top of the loot tracker, one for current session loot and one for total loot since loot tracker was enabled for a specific entity (zulrah,vorkath,red dragon, etc...)

**Comment by Hydrox6** [comment] 2021-11-02 16:44
Duplicate of #10346

**Closed by Hydrox6** 2021-11-02 16:44 UTC
