### ISSUE TITLE
Idle notifier doesn't work with cat

### ISSUE THREAD

**Issue by jamalt5** [runelite/runelite#8429] opened 2019-04-06 02:14 UTC
**Describe the bug**
With idle notifier, I don't get notifications when stopped fishing when I'm interrupted by my cat(being needy.) I get notifications normally though

**To Reproduce**
No clue, maybe just try fishing with a cat?

**Expected behavior**

**Environment (please complete the following information):**
 - OS:Windows
 - RuneLite version: latest

**Comment by zwilkin** [comment] 2019-08-21 17:31
Not just for cat interruptions; it happens when gaining a level too.

**Comment by deathbeam** [comment] 2019-08-23 09:06
Duplicate of #9714

**Closed by deathbeam** 2019-08-23 09:06 UTC
Labels: bug
