### ISSUE TITLE
Jonny the beard is incorrectly highlighted when on a Bear slayer task

### ISSUE THREAD

**Issue by JoshDavis97** [runelite/runelite#14551] opened 2022-01-04 13:36 UTC
**Describe the bug**
Title - when you are on a Bear slayer task, the slayer plugin highlights Jonny the beard. Presumably because the plugin matches any NPC with "bear" in their name.

**To Reproduce**
Be on a Bear slayer task and go to Varrock's Blue Moon Inn to see the bug, with one of the highlight settings active on the Slayer plugin.

**Expected behavior**
Jonny the beard should not be highlighted on a Bear slayer task.

**Screenshots**
![image](https://user-images.githubusercontent.com/45068854/148067148-56e611a0-2395-4252-8ad3-6fec8a268047.png)

![image](https://user-images.githubusercontent.com/45068854/148066621-c29f6880-9976-4195-abfd-3dcdcf2f53ec.png)

**Environment (please complete the following information):**
 - OS: Microsoft Windows 10 Home 10.0.19043
 - RuneLite version: 1.8.8
 - Launcher version: 2.1.7

**Additional context**
Confirmed that killing him does not count as a bear for the slayer task. The plugin does not decrement the counter when you kill him.

**Comment by Nightfirecat** [comment] 2022-01-04 18:37
Duplicate of #6285

**Closed by Nightfirecat** 2022-01-04 18:37 UTC
Labels: duplicate
