### ISSUE TITLE
Side Bar Graphical Glitch

### ISSUE THREAD

**Issue by DarkRaGaming** [runelite/runelite#12505] opened 2020-09-17 10:20 UTC
I have stumbled upon an issue with the sidebar. I have attached images to show the issue. it changes around when you hover over other icons. I have tried reinstalling the client. closing and opening the sidebar. the only thing that solves it (temporarily) is closing the client and reopening it. my friend says he doesnt get this issue. if there is a fix for this please let me know. If it helps 

![image](https://user-images.githubusercontent.com/49731556/93457761-41bd6180-f894-11ea-8e6c-c2b810e396a8.png)

I have tried a fresh install and all

Here is my computer specs

Processor : Intel Core i7-6820hk CPu 2.70GHz
Ram : 64GB
System Type : Window 10 64 bit
Graphic Card: Geforce 980

**Comment by Hydrox6** [comment] 2020-09-17 10:21
Duplicate of #11727 (and many more)

**Closed by Hydrox6** 2020-09-17 10:21 UTC
