### ISSUE TITLE
Add a method to EntityHiderBridgeMixin to hide specific NPCs

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#9775] opened 2019-08-29 21:53 UTC
![image](https://user-images.githubusercontent.com/9074448/63978970-05b43480-cab8-11e9-87c3-212f3cddebab.png)
I want to hide Ancient Fungi, this is currently not possible. Add a method here which accepts a list of Strings of NPC's to be hidden, and from there this feature could be implemented.

**Comment by Nightfirecat** [comment] 2019-09-17 06:34
Duplicate of #6854

**Closed by Nightfirecat** 2019-09-17 06:34 UTC
