### ISSUE TITLE
Item Charges: Gricoller's can

### ISSUE THREAD

**Issue by wagey** [runelite/runelite#10456] opened 2019-12-17 02:23 UTC
It would be really nice if the Item Charges plugin was updated to support the "Gricoller's can" you get as a reward from the Tithe Farm minigame. There's an option that already exists on this plugin for regular Watering cans so hopefully this makes enough sense.

https://oldschool.runescape.wiki/w/Gricoller%27s_can

**Comment by dekvall** [comment] 2019-12-17 02:25
Duplicate of #8937

**Closed by dekvall** 2019-12-17 02:25 UTC
