### ISSUE TITLE
Player Indicators Plugin suggestion

### ISSUE THREAD

**Issue by troywingert21** [runelite/runelite#14894] opened 2022-04-24 21:49 UTC
I think it would be a wonderful feature to add a players combat level above their head in addition to their name. If possible, it would also be cool to see their clan and clan rank.

**Comment by Hydrox6** [comment] 2022-04-24 22:00
Duplicate of #6567

iirc the plugin already shows icon of the clan rank for the clan you're in. The client has no way of getting users of a clan that you're not in.

**Closed by Hydrox6** 2022-04-24 22:00 UTC

**Comment by troywingert21** [comment] 2022-04-24 22:57
The main point of this was combat level next to name
