### ISSUE TITLE
Ground items on/off toggle-button

### ISSUE THREAD

**Issue by Anthedon** [runelite/runelite#1524] opened 2018-04-14 14:58 UTC
Like CTRL or something.

This would be really good for people like me who likes to pk and don't want to see a lot text on screen all the time.

Would be good everywhere else too.

**Comment by Nightfirecat** [comment] 2018-04-14 16:32
OSBuddy has this feature, using the Alt key. +1

**Comment by deathbeam** [comment] 2018-04-15 05:27
Duplicate of #1141

**Closed by deathbeam** 2018-04-15 05:27 UTC
Labels: feature-request
