### ISSUE TITLE
More loot tracker stuff (skilling-related)

### ISSUE THREAD

**Issue by towelcat** [runelite/runelite#6094] opened 2018-10-20 08:07 UTC
Pickpocketing, fishing, mlm, etc. Anything with variable yield, really. (i.e. H.A.M. members, fishing spots that yield multiple types of fish, mlm giving different ores, and so on.)

It'd be nice for collecting approximate drop rates without bugging jmods on twitter.

Farming would be neat but would probably be better suited to have its own plugin to track yield, as it would require extra work for tracking how many you get per patch (and you'd probably want a custom display).

**Comment by deathbeam** [comment] 2018-10-20 09:36
Duplicate of #4126

**Closed by deathbeam** 2018-10-20 09:36 UTC
