### ISSUE TITLE
Group screen markers

### ISSUE THREAD

**Issue by A7mad3absi** [runelite/runelite#8726] opened 2019-05-02 18:22 UTC
**Is your feature request related to a problem? Please describe.**
A suggestion, not a problem.

**Describe the solution you'd like**
Allow users to create a whole group for markers.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/48586145/57097182-bc2d2600-6d1f-11e9-86e5-b44c2cde3436.png)

* Note: I usually delete markers so I can assign new ones, because I hate to scroll and test each marker and see what/where it's currently positioned.

Instead of that, add a new icon which makes a new "group" but not a new marker. Inside this group you can add/remove the markers that you have on the main interface? Me scrolling down to 50 different markers is kinda lame (I know that I can decrease that amount) but I'd like to have a group system. Here's an example.

1. 3t fishing
     -marker  spot 1 (usually water)
     - marker spot 2 (usually inventory)
2. Herblore 
     -marker  spot 1 (usually water)
     - marker spot 2 (usually inventory)

And so on.

**Comment by Hydrox6** [comment] 2019-05-02 18:28
Duplicate of #3205

**Closed by Hydrox6** 2019-05-02 18:28 UTC
