### ISSUE TITLE
Master clue improvements

### ISSUE THREAD

**Issue by alexbowers** [runelite/runelite#3980] opened 2018-06-23 20:34 UTC
When doing a master clue that is a 3-step step, there are no solutions visible in Runelite for what to do to complete each step.

When doing a master clue, there is no indication as to what is going to spawn (eg. 3 wizards, etc).

**Comment by Nightfirecat** [comment] 2018-06-23 23:18
First issue is a duplicate of #2923.
#3352 has been opened to try to address this feature,so if merged it will address that.

Second issue is a duplicate of #2580.

**Closed** 2018-07-02 22:52 UTC
Labels: clues
