### ISSUE TITLE
GPU plugin using integrated graphics

### ISSUE THREAD

**Issue by ABagOfMilk** [runelite/runelite#10031] opened 2019-10-10 22:25 UTC
Simple request. I'm using a Late 2013 MacBook Pro (13 inch) and as it has no dedicated gpu (only integrated) and unfortunately the GPU plugin for RuneLite does not use integrated graphics. Could this possibly be added in the future? Pls no Mac vs Pc. I have my gaming desktop for that sort of stuff.

**Comment by Alexsuperfly** [comment] 2019-10-10 22:27
https://github.com/runelite/runelite/wiki/GPU-FAQ#when-will-there-be-support-for-macos

**Comment by ABagOfMilk** [comment] 2019-10-10 22:27
> https://github.com/runelite/runelite/wiki/GPU-FAQ#when-will-there-be-support-for-macos

Thanks. Silly me. I just assumed integrated graphics would work the same across all operating systems.

**Comment by Nightfirecat** [comment] 2019-10-10 22:34
Duplicate of #6482

**Comment by Nightfirecat** [comment] 2019-10-10 22:35
There is big interest in adding support for MacOS systems, but we've not had much work put toward it because it's unfortunately a nontrivial effort to support them.

**Closed by Nightfirecat** 2019-10-10 22:34 UTC
Labels: duplicate
