### ISSUE TITLE
Ground Items - Hidden Ground Item list per account

### ISSUE THREAD

**Issue by hillj17** [runelite/runelite#7289] opened 2019-01-11 14:03 UTC
When switching between my main and my noob ironman account, I typically see ground items hidden that are on my main's list that I want to be shown on my noob's list, and visa versa.

I'd like to see a hidden item list be saved per account.  An alternative to this, which might be easier and not as limiting is to be able to save a given list with a name, then select the lists from a dropdown.  Option 1 would default to the user's current hidden items list, then the bottom option would be an empty list which the user can add items to as they go.

The alt-add, alt-remove options would need to allow insertion into the currently selected list as well.

**Comment by Adam-** [comment] 2019-01-11 16:34
duplicate of #2220

**Closed by Adam-** 2019-01-11 16:34 UTC
