### ISSUE TITLE
Runelite application freezing when I approach the boulder at GWD

### ISSUE THREAD

**Issue by sidneydavis** [runelite/runelite#10807] opened 2020-02-15 17:03 UTC
I move past the trolls to get to the boulder and once I hit the snowy part the game freezes and I am forced to close the application. Each time I try to log back in when I'm standing near the boulder it just immediately freezes. I disabled the GPU plugin and there is no behavior change, it is still just completely frozen. I used the OldSchool client to push back the boulder, logged back in on RL and the game is still frozen. I used the OldSchool client to move down the rope into GWD and logged back into RL and the freezing stopped and I could play again. Not entirely sure what's going on here but thought I would let you know.

**Comment by Nightfirecat** [comment] 2020-02-18 03:09
Can you please post your logs? [You can find them in your `%userprofile%\.runelite\logs` folder on **Windows**, or your `$HOME/.runelite/logs` folder on **MacOS/Linux**](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client).

**Comment by sidneydavis** [comment] 2020-02-18 03:26
2020-02-15 09:53:20 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-02-15 09:53:20 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-02-15 09:53:20 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 436887693.44
2020-02-15 09:53:21 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-02-15 09:53:22 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-02-15 09:53:23 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 4099ms. Uptime: 6731ms
2020-02-15 09:53:23 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,313,0,1295x1533,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1295x1533,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@580d02fb,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-02-15 09:53:24 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user squidbillies.
2020-02-15 09:56:47 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
java.lang.ArithmeticException: / by zero
	at dx.bo(dx.java:654)
	at ig.iy(ig.java:9357)
	at ig.iy(ig.java:9138)
	at ig.iy(ig.java:9137)
	at gb.io(gb.java:8995)
	at ig.iy(ig.java:9141)
	at ig.iy(ig.java:9137)
	at gb.io(gb.java:8995)
	at client.tp(client.java:4179)
	at client.ac(client.java:1282)
	at bf.pg(bf.java:373)
	at bf.run(bf.java:327)
	at java.lang.Thread.run(Thread.java:748)
2020-02-15 09:58:33 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-02-15 09:58:34 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-02-15 09:58:34 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 436887693.44
2020-02-15 09:58:35 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-02-15 09:58:35 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-02-15 09:58:36 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 3840ms. Uptime: 5576ms
2020-02-15 09:58:36 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,313,0,1295x1533,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1295x1533,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@2c7c276a,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-02-15 09:58:37 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user squidbillies.
2020-02-15 09:58:52 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
java.lang.ArithmeticException: / by zero
	at dx.bo(dx.java:654)
	at ig.iy(ig.java:9357)
	at ig.iy(ig.java:9138)
	at ig.iy(ig.java:9137)
	at gb.io(gb.java:8995)
	at ig.iy(ig.java:9141)
	at ig.iy(ig.java:9137)
	at gb.io(gb.java:8995)
	at client.tp(client.java:4179)
	at client.ac(client.java:1282)
	at bf.pg(bf.java:373)
	at bf.run(bf.java:327)
	at java.lang.Thread.run(Thread.java:748)
2020-02-15 10:01:02 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-02-15 10:01:02 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-02-15 10:01:02 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 436887693.44
2020-02-15 10:01:03 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-02-15 10:01:04 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-02-15 10:01:05 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 3911ms. Uptime: 5843ms
2020-02-15 10:01:05 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,313,0,1295x1533,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1295x1533,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@10f89bed,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-02-15 10:01:06 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user squidbillies.
2020-02-15 10:01:20 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
java.lang.ArithmeticException: / by zero
	at dx.bo(dx.java:654)
	at ig.iy(ig.java:9357)
	at ig.iy(ig.java:9138)
	at ig.iy(ig.java:9137)
	at gb.io(gb.java:8995)
	at ig.iy(ig.java:9141)
	at ig.iy(ig.java:9137)
	at gb.io(gb.java:8995)
	at client.tp(client.java:4179)
	at client.ac(client.java:1282)
	at bf.pg(bf.java:373)
	at bf.run(bf.java:327)
	at java.lang.Thread.run(Thread.java:748)
2020-02-15 10:02:14 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-02-15 10:02:14 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-02-15 10:02:14 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 436887693.44
2020-02-15 10:02:15 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-02-15 10:02:16 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-02-15 10:02:17 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 4144ms. Uptime: 5911ms
2020-02-15 10:02:17 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,313,0,1295x1532,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1295x1532,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@69eae785,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-02-15 10:02:18 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user squidbillies.
2020-02-15 17:46:29 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-02-15 17:46:29 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-02-15 17:46:29 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 436887693.44
2020-02-15 17:46:31 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-02-15 17:46:31 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-02-15 17:46:32 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 4057ms. Uptime: 6469ms
2020-02-15 17:46:32 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,313,0,1295x1532,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1295x1532,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@10f89bed,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-02-15 17:46:33 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user squidbillies.
2020-02-15 21:26:52 [pool-3-thread-1] WARN  n.r.c.plugins.hiscore.HiscorePanel - Error fetching Hiscore data timeout
2020-02-15 21:27:03 [pool-3-thread-1] WARN  n.r.c.plugins.hiscore.HiscorePanel - Error fetching Hiscore data Read timed out

**Comment by Alexsuperfly** [comment] 2020-02-18 03:30
your window size is too tall make it shorter than 1500px and i believe it will be fixed, if not just keep going shorter

**Comment by sidneydavis** [comment] 2020-02-18 03:37
While that does fix it at GWD, it's only a problem at this specific spot. In every other part of the game it is functioning properly at the same size. I'll keep it smaller if I have to come back this way but that's a little confusing for me.

**Comment by Alexsuperfly** [comment] 2020-02-18 03:38
it will do that with any snow overlay

**Comment by Nightfirecat** [comment] 2020-02-18 03:41
Duplicate of #4730

**Closed by Nightfirecat** 2020-02-18 03:41 UTC
Labels: duplicate
