### ISSUE TITLE
Fermenting vats timer

### ISSUE THREAD

**Issue by githubber08** [runelite/runelite#12601] opened 2020-10-05 02:16 UTC
**Is your feature request related to a problem? Please describe.**
There should be a timer for when fermentation is completed for vats in Keldagrim and Port Phasmaty’s.
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
The problem is that i dont know when the fermenting vat is completed and I can withdraw the ales from the vat into my beer glass
**Describe the solution you'd like**
There needs to be a timer added for the fermentation vats, just like there’s a timer for birdhouses and tree/herb runs.
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
None.
**Additional context**
None.

**Comment by Unmoon** [comment] 2020-10-05 05:45
Duplicate of #2648

**Closed** 2020-10-05 05:58 UTC
Labels: duplicate
