### ISSUE TITLE
Add a hotkey to completely hide the sidebar

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#449] opened 2018-01-26 11:08 UTC
Title.

Also, hotkeys to pop open the sidebar to a specific tab would be nice too.

Possibly something like Ctrl-Esc to close, Ctrl-F1 for first tab, Ctrl-F2 for second, etc.

**Comment by Adam-** [comment] 2018-04-27 17:55
Duplicate of #656

**Closed by Adam-** 2018-04-27 17:55 UTC
Labels: feature-request

**Comment by ShaunDreclin** [comment] 2018-04-27 18:02
Uhh #656 is a duplicate of *this* issue :p
