### ISSUE TITLE
Show Inventory Tags in Inventory Viewer 

### ISSUE THREAD

**Issue by OliverBroadbent** [runelite/runelite#9507] opened 2019-07-29 18:06 UTC
**Is your feature request related to a problem? Please describe.**
I'm currently using the "tan leather" spell to train my magic with my setup looking like this http://prntscr.com/olmf0r. The problem is that I'm sometimes finding it hard to tell the difference between the leather and hides and don't know when to stop casting the spell. I decided to try the "inventory tags" plugin to rectify that, however, the tags don't show in the inventory viewer plugin (example: http://prntscr.com/olmhks) bringing me back to square one. Sorry for the bad explanation :S

**Describe the solution you'd like**
Add support for the inventory tags in the inventory viewer plugin.

**Comment by Darkkgreen** [comment] 2019-07-30 00:48
The inventory tag is the 'outline' in the item?

**Comment by OliverBroadbent** [comment] 2019-07-30 04:39
> The inventory tag is the 'outline' in the item?

Yeah

**Comment by Darkkgreen** [comment] 2019-07-31 17:48
I'll look into it when I can

**Comment by Darkkgreen** [comment] 2019-07-31 19:20
![image](https://user-images.githubusercontent.com/4364890/62241236-2735d980-b3af-11e9-89ed-ab83c394e5a1.png)

Like this, right?

**Comment by OliverBroadbent** [comment] 2019-07-31 19:56
> ![image](https://user-images.githubusercontent.com/4364890/62241236-2735d980-b3af-11e9-89ed-ab83c394e5a1.png)
> 
> Like this, right?

Exactly like that! Looks perf

**Comment by Darkkgreen** [comment] 2019-08-01 01:55
It'll stay on hold since we have to figure out some things

**Comment by raiyni** [comment] 2019-10-04 21:49
duplicate of https://github.com/runelite/runelite/issues/5049 ?

**Closed** 2019-10-04 21:50 UTC
Labels: duplicate
