### ISSUE TITLE
Screen Marker Merge

### ISSUE THREAD

**Issue by AlexZabe** [runelite/runelite#11926] opened 2020-06-18 18:05 UTC
Would it be possible to merge multiple screen markers together so you can view/hide multiple screen markers at once. I use like 4-5 at a time when doing bank standing skills and it would be awesome if it were possible to do this.

**Comment by Nightfirecat** [comment] 2020-06-18 18:21
Duplicate of #3205

**Closed by Nightfirecat** 2020-06-18 18:21 UTC
Labels: duplicate
