### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) Runelite Client Crash

### ISSUE THREAD

**Issue by problemsproblemsyes** [runelite/runelite#15554] opened 2022-08-25 09:04 UTC
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 11

### Bug description

At Random intervals and without warning/known trigger the Runelite client shuts off/crashes. Can be within 3 minutes, can be after an hour. Can be without even doing anything when client is up. Always the same errors: EXCEPTION_ACCESS_VIOLATION (0xc0000005).
What have I tried?

- Reinstalling Java
- Reinstalling c++ visual studio
- Reinstalling Runelite
- Updating Motherboard bios
- Updating Motherboard chipset
- Updating Nvidia Drivers, multiple tested
- Disabling XMP in bios
- Removing all runescape and Runelite related files/folders/programs
- No 3rd party plugins

### Screenshots or videos

Client info:
`2022-08-25 10:51:15 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.plugins.crowdsourcing.movement.CrowdsourcingMovement.onGameTick(CrowdsourcingMovement.java:73)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:197)
	at client.of(client.java:17085)
	at client.g(client.java)
	at ab.ya(ab.java:362)
	at ab.run(ab.java:341)
	at java.base/java.lang.Thread.run(Unknown Source)`

### RuneLite version

Runelite version 1.8.32
Launcher version 2.4.5

### Logs

[client.log](https://github.com/runelite/runelite/files/9423170/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9423176/launcher.log)
[jvm_crash_pid_14388.log](https://github.com/runelite/runelite/files/9423180/jvm_crash_pid_14388.log)

**Comment by Nightfirecat** [comment] 2023-05-22 17:44
Duplicate of #10628, we don't know what causes this crash.

**Closed by Nightfirecat** 2023-05-22 17:44 UTC
Labels: duplicate
