### ISSUE TITLE
Sound issues in client

### ISSUE THREAD

**Issue by mvklein** [runelite/runelite#2705] opened 2018-05-14 06:13 UTC
Hi all,
I have been having some strange sound issues in my client. For example, when the RuneLite client is open and I am logged in, other system sounds do not play or even show up on the audio manager. When the RuneLite client is up and sound is coming from another source, RuneLite dosen't register or play any audio. Tried this on both the jar and exe, same issue on both. I am not using low detail and am on win7.

**Comment by deathbeam** [comment] 2018-11-27 13:07
Duplicate of #3525 or invalid

**Closed by deathbeam** 2018-11-27 13:07 UTC
Labels: bug, jvm-bug
