### ISSUE TITLE
Add a side panel to show highest value items/stacks in bank.

### ISSUE THREAD

**Issue by offZills** [runelite/runelite#4649] opened 2018-08-02 16:26 UTC
would be a nice add on if you can add a plugin to show you what is the highest value items and/or item stacks you got in bank,like the one runeloader had.
"sorry for telling the name of another client in your github, but that`s where i saw it"

**Comment by Alexsuperfly** [comment] 2019-07-28 19:02
duplicate of #2062

**Closed** 2019-07-28 19:02 UTC
Labels: feature-request
