### ISSUE TITLE
Death Animation Bug

### ISSUE THREAD

**Issue by jukeboxbrass17** [runelite/runelite#15471] opened 2022-08-09 20:00 UTC
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

killin kq p2 it dies
but it doesnt die
skip 2 around 2:40
to see me coming bak

### Screenshots or videos

https://youtu.be/VAI180AoyVQ

### RuneLite version

https://i.imgur.com/RUYhnvL.png

**Comment by Nightfirecat** [comment] 2022-08-09 20:04
Duplicate of #15394

**Closed by Nightfirecat** 2022-08-09 20:04 UTC
Labels: duplicate
