### ISSUE TITLE
GPU plugin immediately shuts itself off when I try to turn it on

### ISSUE THREAD

**Issue by SilverLugia1992** [runelite/runelite#10621] opened 2020-01-19 17:59 UTC
I originally thought it did that the plugin didn't work for me because I only have integrated graphics on my laptop, but someone who appears to work on Runelite told me on reddit that it should still work regardless. I'm using a Toshiba Satellite P755 (it's pretty old, a decade I'd say). Should the GPU plugin still work for me, and if so, how can I get it to work?

**Comment by Hydrox6** [comment] 2020-01-19 18:02
Duplicate of #6552
Your GPU is not supported
For further questions of support, please join the Discord

**Closed by Hydrox6** 2020-01-19 18:02 UTC
