### ISSUE TITLE
Diary Requirements - Enabled, not working.

### ISSUE THREAD

**Issue by NotAyden1** [runelite/runelite#15716] opened 2022-09-22 18:17 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Upon opening Diaries, no requirements were shown, I have checked. It is enabled. 
No customization option so I did not change anything, restarting client does not resolve the issue. (tried that)

### Screenshots or videos

![Screenshot (11555)](https://user-images.githubusercontent.com/114182611/191821343-03634113-8ca3-448b-b54a-9d2984c2582a.png)

### RuneLite version

Runelite 1.8.33.1
Oldschool Revision; Rev 2008 
Launcher Version: 2.4.5

**Comment by Nightfirecat** [comment] 2022-09-22 18:19
Duplicate of #15710; we've just merged a fix in cc14fd999d017f38e22c0a88cafca152c367f0db

**Closed by Nightfirecat** 2022-09-22 18:19 UTC
Labels: duplicate
