### ISSUE TITLE
Client Stuck Loading at 99%

### ISSUE THREAD

**Issue by chip0tle** [runelite/runelite#5889] opened 2018-10-09 21:00 UTC
When trying to launch Runelite for the first time, the client loads quickly up until it stops when loading okhttp-3.7.0.jar at 99%. I've tried deleting the repository, but it did not solve the problem and it gets stuck loading at the same point. My logs only have one line repeated for each time I've tried to launch the client, but it still has yet to fully launch. 

**Environment (please complete the following information):**
 - Windows 10
 - RuneLite version: [1.4.20]
 - Launcher version: [1.4.20]

**Additional context**
[launcher.log](https://github.com/runelite/runelite/files/2462192/launcher.log)

**Comment by deathbeam** [comment] 2018-10-11 05:44
Duplicate of https://github.com/runelite/launcher/issues/35

**Closed by deathbeam** 2018-10-11 05:44 UTC
