### ISSUE TITLE
Menu entry swapper for wilderness lever

### ISSUE THREAD

**Issue by datashe12** [runelite/runelite#5550] opened 2018-09-19 13:43 UTC
Are you guys able to add a menu entry swapper option to change the left click of the wilderness lever to be to edgeville instead of ardougne?

**Comment by raiyni** [comment] 2018-09-19 13:44
There is a pr open for and there is discussion if it is necessary

**Comment by deathbeam** [comment] 2018-09-19 13:45
Duplicate of #5516

**Closed by deathbeam** 2018-09-19 13:45 UTC
