### ISSUE TITLE
beginner clue step draynor manor shows indicator for lumbridge cow patch

### ISSUE THREAD

**Issue by sl0anage** [runelite/runelite#10467] opened 2019-12-18 00:32 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When you use the hot/cold step and the step is discovered to be Draynor wheat field, the indicator on runelite directs the screen to dig at the lumbridge cow patch instead.

**To Reproduce**
1. Open a hot/cold Beginner clue scroll 
2. Use the indicator to find that you are supposed to dig at draynor manor.
3. Watch as you get close to draynor by way of lumbridge and notice the arrow directing a dig at the lumbridge cow field.

<img width="1197" alt="Screen Shot 2019-12-17 at 12 39 06 PM" src="https://user-images.githubusercontent.com/11018681/71045628-81c79c00-20ea-11ea-9194-cfbfc1145e77.png">

The indicator should direct the character to dig at the draynor manor dig site instead of lumbridge cow field

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: 1.5.43
 - Launcher version: 2.1.0

**Comment by Nightfirecat** [comment] 2019-12-18 00:35
Your screenshot doesn't really show what you're describing. Are you saying that if I get a beginner scroll with the draynor hot/cold location, narrow the solver down to that location, then walk toward another one and continue testing, it will have the hint arrow on some other location?

**Comment by sl0anage** [comment] 2019-12-18 00:56
oh whoops i was just too late I guess.

No once I know it's Draynor Manor, if I walk by the cow patch it points me to the cow patch. It doesn't happen every time but I wasn't paying attention and kept digging where the arrow was directing me at the cow patch but the clue step showed it was at the Manor.

**Comment by Nightfirecat** [comment] 2020-01-27 01:41
Likely duplicate of #10370, which I am looking at today.

**Closed by Nightfirecat** 2020-01-27 01:41 UTC
