### ISSUE TITLE
OpenGL stretched mode glitches out screenshots

### ISSUE THREAD

**Issue by robinwithes** [runelite/runelite#6663] opened 2018-11-24 17:16 UTC
**Describe the bug**
When having the screenshot plugin enabled as well as gpu and the stretched mode plugin, it glitches out the screenshots to appear like this: https://gyazo.com/180c38e0cc02efd02db8a6e778a02c08

**To Reproduce**
1. Enable the plugins listed above
2. Enabled fixed mode
3. Configure stretched mode like this https://gyazo.com/f63054edc1afd23d484593acb9fb6dcd
4. Get the screenshot plugin to take a screenshot (I havent tested anything else then barrows automatic screenshots but i assume it all uses the same method)

**Expected behavior**
That screenshots make a screenshot of the full screen
**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.1

**Comment by forsco** [comment] 2018-11-24 17:20
Duplicate of #6649

**Closed** 2018-11-25 00:09 UTC
