### ISSUE TITLE
Farming Contract Timers

### ISSUE THREAD

**Issue by Karambwa** [runelite/runelite#7774] opened 2019-02-09 19:25 UTC
Would be cool if runelite could pop up a little square similar to the slayer tasks square, that keeps track of your current farming contract and its growth time left. Fiddling around with the current timer menu, and having to remember what contract you are on can be tedious.

**Comment by deathbeam** [comment] 2019-02-09 19:29
Duplicate of #7634

**Closed by deathbeam** 2019-02-09 19:29 UTC
