### ISSUE TITLE
Notification for amulet of chemistry break

### ISSUE THREAD

**Issue by Majst** [runelite/runelite#5669] opened 2018-09-27 12:14 UTC
**Describe the solution you'd like**
When your amulet of chemistry breaks while doing herblore, a notification similar to bird nest dropping since you can toggle to stop crafting potions when the amulet breaks. If you are tabbed the game will flash, etc.

**Comment by deathbeam** [comment] 2018-09-27 12:15
Duplicate of #504

**Closed by deathbeam** 2018-09-27 12:15 UTC

**Comment by Nightfirecat** [comment] 2018-09-27 15:54
FYI, you can configure your Chat Notification plugin to notify you on the break text.
