### ISSUE TITLE
Show untradeable item values in bank

### ISSUE THREAD

**Issue by jaruds** [runelite/runelite#2399] opened 2018-05-06 10:37 UTC
Show the prices of the tradeable versions to make bank value more accurate

Ex. 
Verac's plateskirt 25/50/75/100 -> Verac's plateskirt price
Slayer helmet/Slayer helmet (i)/Any different colored slayer helmets  -> Black mask price
Berserker ring (i) -> Berserker ring price
Toxic blowpipe/Trident -> Same price as when they're empty and tradeable

Not sure if suggested already

**Comment by ypperlig** [comment] 2018-05-06 10:47
Duplicate of #1045 

There's' this which will resolve it: #1750

**Closed** 2018-05-06 10:48 UTC
