### ISSUE TITLE
Farming timers 'compost display'

### ISSUE THREAD

**Issue by wokeRS** [runelite/runelite#9225] opened 2019-06-27 06:21 UTC
It would be very nice to be able to see if a patch is composted while on the farming timers tab. I usually dont pay much attention while doing farm runs and sometimes second guess if I composted a patch or not. I hope i'm not alone lol. 
![6b84bd57f11ccd04bfb63647f0dd832c](https://user-images.githubusercontent.com/52272049/60241873-4d34ff00-9882-11e9-8835-bdb8f7762961.png)

**Comment by dappersnapper456** [comment] 2019-06-27 16:50
This is a very good idea tbh.

**Comment by Hydrox6** [comment] 2019-06-27 16:50
Duplicate of #2472

**Closed by Hydrox6** 2019-06-27 16:50 UTC
