### ISSUE TITLE
Addition to Screen Markers

### ISSUE THREAD

**Issue by amagician-rs** [runelite/runelite#13740] opened 2021-06-15 22:37 UTC
This isn't really anything new, rather combining the features of a few other plugins. 

But I think it would be neat to have a plugin or an addition to the Screen Markers plugin that would allow you to save your screen markers, camera position + client size together as Custom "Scenes".

This then allowing you to have multiple scenes you can select through dependent on what content you're doing in-game.

For myself who doesn't play fixed, I often will adjust my client size depending on what I'm doing and how many accounts I'm playing on. Having the ability to quickly switch between different client sizes and the option to include camera angle + screen markers would be a great addition for those who often jump between different content.

**Comment by PoopCrusher** [comment] 2021-06-17 21:20
This already exists in a plugin called "Camera Positions". It's similar to 'inventory setups' but with camera zoom and angle being saved

**Comment by amagician-rs** [comment] 2021-06-17 21:25
> This already exists in a plugin called "Camera Positions". It's similar to 'inventory setups' but with camera zoom and angle being saved

Does it also save client size?

**Comment by PoopCrusher** [comment] 2021-06-17 21:27
> > This already exists in a plugin called "Camera Positions". It's similar to 'inventory setups' but with camera zoom and angle being saved
> 
> Does it also save client size?

I do not believe it has client size but that would be a great addition.

**Comment by Xloade** [comment] 2021-06-30 11:38
yeah it would be nice to be able at least group screen markers, when you have 50 of them it becomes bit unmanageable

**Comment by Hydrox6** [comment] 2021-07-02 11:30
Duplicate of #3195
Duplicate of #3205
Duplicate of #3784

**Closed by Hydrox6** 2021-07-02 11:30 UTC
