### ISSUE TITLE
Cannon overlay doesn't render at Cave Horrors

### ISSUE THREAD

**Issue by Leo288** [runelite/runelite#13210] opened 2021-02-13 09:59 UTC
**Describe the bug**
At a common Cave Horrors cannon spot, the tile marker intermittently renders, and "balls left" text overlay fails to render at all. Tooltip infobox always shows 30 cannonballs remaining.

**To Reproduce**
1. Go to location in screenshot
2. Set down a cannon

**Expected behavior**
Overlays to render as they do in other locations.

**Screenshots**
![cannon](https://user-images.githubusercontent.com/78256408/107847276-22464880-6de2-11eb-86ba-9473b3f78b63.PNG)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.39
 - Launcher version: 2.1.6

**Comment by Hydrox6** [comment] 2021-02-13 12:36
The cannon overlay works off of the player's animation of placing the cannon down, as it needs to know where the cannon is placed. Cave horrors can override this animation with their screaming attacks. If this ever happens elsewhere, re-place the cannon, preferably when not under attack.

This is somewhat of a duplicate of quite a few other issues, though none of them actually explained this :d
As far as I understand it, there's not really a good way to make the detection better without introducing potential confusion that the current method was supposed to stop.

**Closed by Hydrox6** 2021-02-13 12:36 UTC

**Comment by Leo288** [comment] 2021-02-13 13:27
I thought it could be something to do with their animation stall. It makes melee go weird too and become some semi-ranged weapon, up to 8 tiles away at times.
