### ISSUE TITLE
Ground Items plugin shows incorrect # on right click for noted mithril bar drops

### ISSUE THREAD

**Issue by pelletier2017** [runelite/runelite#12876] opened 2020-12-02 21:08 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Runelite ground items shows 2 stacks of (6) noted mithril bars but there are only two stacks of (3) noted bars as seen in the image. Its likely an issue with showing multiple stacks of noted items on the ground that have dropped from a monster.

**To Reproduce**
Kill mithril dragons and have noted mithril bars spawn ontop of each other. I could not reproduce it by dropping two different stacks of notes ontop of each other.

**Expected behavior**
There should be two (3) mithril bars to pick up rather than two (6) mithril bars.

**Screenshots**
Screenshot of 6 mithril bars seen on the ground while right clicking shows two sets of (6) bars when it should be two sets of (3) bars.
https://imgur.com/a/rCtbHUl

**Environment (please complete the following information):**
Windows 10
Runelite 1.6.33
Launcher 1.6.0

**Additional context**
N/A

**Comment by Alexsuperfly** [comment] 2020-12-02 21:15
duplicate of #1220

**Closed** 2020-12-02 21:16 UTC
Labels: duplicate
