### ISSUE TITLE
[SUGGESTION] Indicator that shows whether a farming patch contains plant/compost

### ISSUE THREAD

**Issue by Seahawkward** [runelite/runelite#11456] opened 2020-05-04 02:00 UTC
Many times my plants have died because I forgot to add my compost, and many times I forgot to add a seed at all, since they're pretty hard to see when just planted.

**Describe the solution you'd like**
I'd like a little indicator, preferably above the patch, that shows if a patch contains compost or contains a plant. An indication of the growth state would also be cool, so when I'm skilling at the farming guild bank for example I can easily see when the plant is almost done.

**Describe alternatives you've considered**
I've considered not being an idiot when doing farming runs. So far that has not worked out.

**Additional context**
I envision something like this; but maybe a bit more elegant and a bit less conspicuous. I'd try to code it myself but I can't even writeln 'hello world' without making my computer crash.

![Screenshot_11](https://user-images.githubusercontent.com/64760485/80931646-8d76df00-8dbb-11ea-9a91-5e67407d8fc9.png)

**Comment by Nightfirecat** [comment] 2020-05-04 03:21
I know this isn't exactly what is listed in #2472, but that would effectively cover what's being asked here, so I am closing this issue accordingly.

Duplicate of #2472

**Closed by Nightfirecat** 2020-05-04 03:21 UTC
