### ISSUE TITLE
Tag tab gets deselected when entering custom default quantity

### ISSUE THREAD

**Issue by hjdarnel** [runelite/runelite#7007] opened 2018-12-18 08:19 UTC
**Describe the bug**
When I set a custom X amount (in the bottom of the bank interface) and type Enter to finish, I'm taken out of the tag tab that I'm looking at.

**To Reproduce**
1. Go to a preexisting tag tab.
2. Click on quantity: x
3. Type a number
4. Press enter

**Expected behavior**
Nothing. The quantity should be set like vanilla.

**Actual behavior**
I'm taken back to the default first tab.

**Screenshots**
This quantity button. https://i.imgur.com/GaFgqmW.png

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.5.4
 - Launcher version: unknown

**Comment by deathbeam** [comment] 2018-12-18 16:59
Duplicate of #2362

**Closed by deathbeam** 2018-12-18 16:59 UTC
