### ISSUE TITLE
Minimise Option not working on OSX

### ISSUE THREAD

**Issue by shivharikulhari** [runelite/runelite#9588] opened 2019-08-06 04:59 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Its a simple one, when you click the minimise button, nothing happens.

**To Reproduce**
Try minimising it, it won't work 

**Expected behavior**
It should minimise.

**Screenshots**
https://gyazo.com/e8cac4425197082e058e5ec8572ed0f4.gif

**Environment (please complete the following information):**
 - OS: macOS Mojave 10.14.3
 - RuneLite version: 1.6.1
 - Launcher version: Don't know how to check, let me know and I will tell you.

**Comment by deathbeam** [comment] 2019-08-06 06:19
Duplicate of #2967

**Closed by deathbeam** 2019-08-06 06:19 UTC
Labels: bug
