### ISSUE TITLE
Client freeze when running with openjdk 10 on Linux

### ISSUE THREAD

**Issue by legofarmer** [runelite/runelite#3999] opened 2018-06-24 18:23 UTC
**Java Version:** openJDK 10.0.1 (java-10-openjdk) 
**OS:** Arch Linux w/ Linux 4.17.2-1 

When I open up the client, everything works just fine. I can log in, change settings, etc. After a certain amount of time with the client open, it becomes problematic. Let's say I open up the ground items settings and click "back" to get back to the settings menu, the client freezes up which forces me to end the process.  

This occurs with HW Acceleration enabled or disabled as I have tried it both ways. Perhaps I should use java-8-openjdk instead?  

Any help would be great. Here is a log:  

[launcher.log](https://github.com/runelite/runelite/files/2131078/launcher.log)

**Comment by jplsek** [comment] 2018-06-24 18:32
We will need the `application.log` when a crash occurred found in `~/.runelite/logs/`. This specific log does contain personally identifiable information. So if you are going to post it, delete the lines containing your email address (if you use sync) and [past] username.

**Comment by legofarmer** [comment] 2018-06-24 18:45
application.log doesn't contain useful information here as I have to force close the client (since it freezes), so I guess it doesn't log whatever error it had.  

All it contains is: 
``2018-06-24 10:29:07 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-06-24 10:29:07 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-06-24 10:29:08 [main] INFO  n.r.client.account.SessionManager - No session file exists

**Comment by jplsek** [comment] 2018-06-24 18:48
Huh that's unfortunate. I was mostly looking if there was exception somewhere at the bottom of the file.

**Comment by legofarmer** [comment] 2018-06-24 18:50
I will set jdk8 to default in a bit, that might fix it. I will keep the thread updated with any relevant findings. Have any suggestions?

**Comment by legofarmer** [comment] 2018-06-24 22:04
Hmm. I haven't had the issue since making jdk8 default... Odd, but I'll take it.

Arch users who might be reading this: I installed RuneLite from the AUR, my AUR Helper (yay) installed jdk10 instead of jdk8 (this is because runelite demands java>=8) probably just because it's newer. It might be worth sticking to jdk8 if you use an AUR helper to install runelite to avoid the same issue I had.

Should I run into the issue later on, I will report back.

**Comment by HSJ-OSRS** [comment] 2018-06-25 09:40
i had the same issue using jdk10 after running the client for little while if i changed anything in the plugins settings its just froze completely unresponsive

**Comment by legofarmer** [comment] 2018-06-25 22:05
@HSJ-OSRS I suppose we can reliably conclude that the culprit is jdk10 then. I haven't had a problem since switching to jdk8.

**Comment by tjb0607** [comment] 2018-06-27 11:31
I've had the same freezes a few times when toggling settings on Oracle java-10-jdk as well on Arch. Therefore, the problem is likely with java 10 in general, independent of whether it's openjdk/oracle.

**Comment by 000000653** [comment] 2018-06-27 11:36
I'm not sure if it's relevant, but I've experienced similar freezes on Windows 7, Java version 8.0.1710.11, has happened even just when hovering over icons in the sidebar, not just when clicking them, and it resolves after several minutes of being frozen.

**Comment by 000000653** [comment] 2018-07-13 15:36
I've since updated to launcher version 1.6.0 and have tried replicating the issue and not been able to, so whatever was causing my issue seems to have been solved, still not sure if it was related though

**Comment by nighthawk9** [comment] 2018-10-07 20:30
Same issue occurring on openjdk 10 on KDE Neon based off of 18.04 Ubuntu. It freezes using any features outside of just running the client, this include price checking, calculators, notes and settings.

I have since switched to openjdk 8 and haven't run into the issue.

Some more debugging information is that crash CPU usage spikes.

If there are any other ideas on what the problem is I can aid in the debugging process if a developer cannot reproduce the issue.

**Comment by theGeekPirate** [comment] 2018-11-19 10:11
If it helps any, I've only encountered a freeze while messing with the menu—whether it be opening/closing, or toggling individual options.

**Comment by Lekensteyn** [comment] 2019-03-23 22:09
This appears to be Java bug, I was able to trigger this bug several in multiple occasions on Ubuntu 18.04 with openjdk-11-jre 10.0.2+13-1ubuntu0.18.04.4 although I do not have reliable steps to reproduce. So far it has been triggered when changing settings, toggling a CoX option, toggling impling visibility on the minimap, etc.

The investigation can be found below, but the executive summary is:
- OpenJDK 8: confirmed working
- OpenJDK 9: potentially okay as well (based on https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8202580)
- OpenJDK 10: **DO NOT USE**, is affected by the bug
- OpenJDK 11 and newer: bug is fixed

Recommended versions for various distros:
- Arch Linux:
  - Recommended: jre8-openjdk (8.u212-1)
  - Note: latest version at the moment is jre10-openjdk (10.0.2.u13-1) which is **affected**, do not use.
- Ubuntu 18.10 and newer:
  - Recommended: openjdk-11-jre (11.0.1+13-3ubuntu3) or newer. (openjdk-8-jre should also work though.)
- Ubuntu 18.04 and older:
  - Recommended: openjdk-8-jre (8u191-b12-2ubuntu0.18.04.1)
  - Note: openjdk-11-jre (10.0.2+13-1ubuntu0.18.04.4) is **affected**, do not use.
___
To debug this, start Runelite with a debugger listening on a TCP port (1234 was arbitrary chosen), for example:
```
java -agentlib:jdwp=transport=dt_socket,server=y,address=1234,suspend=n -Dsun.java2d.opengl=false -jar runelite.jar
```
Once the problematic situation has occurred, execute `jdb -attach 1234` to attach a debugger. Use `help` to see available commands. Debugger session:

Discover the Thread ID of the AWT Event Dispatcher thread using the "threads" command.
> &gt; **threads**
> ...
> `  (java.awt.EventDispatchThread)0x23f4                                                   AWT-EventQueue-0            running`

Select the AWT Event Dispatcher thread and print the call trace using `where [Thread ID]` and use `suspend` command to freeze execution if necessary.
> &gt; **where 0x23f4**
> Current thread isn't suspended.
> AWT-EventQueue-0[1] **suspend**
> All threads suspended.
> AWT-EventQueue-0[1] **where**
> [1] sun.java2d.marlin.DRenderer.addLine (DRenderer.java:323)
> [2] sun.java2d.marlin.DRenderer.lineTo (DRenderer.java:683)
> [3] sun.java2d.marlin.DStroker.emitLineTo (DStroker.java:675)
> [4] sun.java2d.marlin.DStroker.lineTo (DStroker.java:548)
> [5] sun.java2d.marlin.DStroker.lineTo (DStroker.java:517)
> [6] sun.java2d.marlin.DDasher.emitSeg (DDasher.java:233)
> [7] sun.java2d.marlin.DDasher.goTo (DDasher.java:272)
> [8] sun.java2d.marlin.DDasher.lineTo (DDasher.java:372)
> [9] sun.java2d.marlin.DMarlinRenderingEngine.pathToLoop (DMarlinRenderingEngine.java:673)
> ...

Use the `step up` command to finish execution of a function and navigate up the call stack. Repeat until the `Step completed` text no longer appears. That suggests that the most recently function is stuck in an infinite loop.
> AWT-EventQueue-0[1] **step up**
> &gt;
> Step completed: "thread=AWT-EventQueue-0", sun.java2d.marlin.DRenderer.lineTo(), line=684 bci=28
> 
> AWT-EventQueue-0[1] **step up**
> &gt;
> Step completed: "thread=AWT-EventQueue-0", sun.java2d.marlin.DStroker.emitLineTo(), line=676 bci=11
> ...
>
> AWT-EventQueue-0[1] **step up**
> &gt; 
> Step completed: "thread=AWT-EventQueue-0", sun.java2d.marlin.DDasher.lineTo(), line=374 bci=285
>
> AWT-EventQueue-0[1] **step up**
> &gt;

Since it is stuck in an infinite loop, you have to suspend the threads again and use `step up` to end up in the problematic function. It turns out that we are stuck in method `sun.java2d.marlin.DDasher.lineTo`. Let's inspect some local variables once we are back:

> AWT-EventQueue-0[1] **step up**
> &gt; 
> Step completed: "thread=AWT-EventQueue-0", sun.java2d.marlin.DDasher.lineTo(), line=374 bci=285
>
> AWT-EventQueue-0[1] **locals**
>
>     Method arguments:   
>     x1 = 990.5
>     y1 = 433.5
>     Local variables:
>     dx = 26.0
>     dy = 0.0
>     len = NaN
>     cx = 1.0
>     cy = 0.0
>     _curCurvepts = instance of double[16] (id=9223)
>     _dash = instance of double[256] (id=9224)
>     _dashLen = 2
>     _idx = 0
>     _dashOn = true
>     _phase = 0.0
>     d = 4.0
>     leftInThisDashSegment = 4.0
>     dashdx = 4.0
>     dashdy = 0.0

These variables do not change on subsequent iterations. Very suspicous. `len` being `NaN` is also very suspicous. To see what effect it has, download and unpack the corresponding source code:

    apt download openjdk-11-source
    dpkg-deb -x openjdk-11-source_*.deb .
    unzip usr/lib/jvm/openjdk-11/lib/src.zip

The DDasher source code can be found at `java.desktop/sun/java2d/marlin/DDasher.java`. If `len` is `NaN`, then it there will indeed be an infinite loop because the `if` condition below never matches:
```java
double len = dx*dx + dy*dy;
// ...
double _phase = phase; // Note: this is a member variable of this class instance
// ...
while (true) {
    d = _dash[_idx];
    leftInThisDashSegment = d - _phase;

    if (len <= leftInThisDashSegment) {
        // ...
        return;
    }

    // ...

    goTo(_curCurvepts, 0, 4, _dashOn);

    len -= leftInThisDashSegment;
    // Advance to next dash segment
    _idx = (_idx + 1) % _dashLen;
    _dashOn = !_dashOn;
    _phase = 0.0d;
}
```

Now why was `len` NaN? It was initially valid as dx and dy were valid. It can only become invalid if `leftInThisDashSegment` is invalid. Initially this variable is `d - _phase`. Variable `_phase` was originally initialized from a member variable `phase`. What's inside? Well...

> AWT-EventQueue-0[1] **dump phase**
> phase = NaN

So there you go, problem confirmed.

Going through the commit history of the above file (https://github.com/openjdk/jdk/commits/master/src/java.desktop/share/classes/sun/java2d/marlin/DDasher.java) we can find commit https://github.com/openjdk/jdk/commit/4fd00b356a6ddb1809259bc65a356dea2aa9faff which matches the problem description in this bug:
> 8202580: Dashed BasicStroke randomly painted incorrectly, may freeze application
The linked bug is https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8202580 which suggests that the bug did **not** occur in Java 8. The commit suggests that the fix was released with jdk-11+14 (May 17, 2018) and newer which seems to have ended up in **OpenJDK 11**  based on the schedule from https://openjdk.java.net/projects/jdk/11/

**Comment by Adam-** [comment] 2019-03-23 22:41
I think this issue is sufficient to document the issue. The 3 launchers we distribute all package Java 8. 10 is also both EOL and also not LTS so I'm okay just closing this bug. Maybe we could put a note on the wiki?

**Comment by Lekensteyn** [comment] 2019-03-23 23:46
I have updated https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-freezing with the new information.

This is a documentation issue, but hopefully the wiki change is sufficient. Feel free to close this issue!

**Closed** 2019-03-23 23:46 UTC
Labels: bug, jvm-bug
