### ISSUE TITLE
HP Notifier (Notify me when HP is about to increase to 2) 

### ISSUE THREAD

**Issue by NeverReturning** [runelite/runelite#10588] opened 2020-01-11 07:58 UTC
Suggestion: HP Notifier.
Idea: Notify me when My health is **about** to hit 2 HP. 
Reason: NMZ Training. Would make Dhoraks a lot easier to do ,and more afkable. If I could like get notified like 5 seconds before it happens.

Hope you have a good day! I know you guys have a HP Notifier for when your HP gets too low ,but I need the opposite of that.  Thanks in advance! Hope you all have a good day! :)

Hope this is the right area to post!

**Comment by chestnut1693** [comment] 2020-01-11 12:02
This can be achieved by another plugin #10330.
It is otherwise worked on by #10513.

**Comment by NeverReturning** [comment] 2020-01-11 12:38
Thank you so much for telling me this! Hope you have a good day.

**Comment by Alexsuperfly** [comment] 2020-01-11 13:51
duplicate of #10330

**Closed** 2020-01-11 13:52 UTC
