### ISSUE TITLE
Add this information

### ISSUE THREAD

**Issue by IanWONeill** [runelite/runelite#8681] opened 2019-04-28 18:31 UTC
2019-04-28 18:21:10 [Client] WARN  n.r.c.p.cluescrolls.ClueScrollPlugin - Encountered unhandled clue text: How many pigeon cages are<br>there around the back of<br>Jerico's house?

**Comment by Hydrox6** [comment] 2019-04-28 18:33
Duplicate of #2740

**Closed by Hydrox6** 2019-04-28 18:33 UTC
