### ISSUE TITLE
Add an X to the end of the plugin search bar to clear the field

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4850] opened 2018-08-11 12:47 UTC
Mockup: 
![image](https://user-images.githubusercontent.com/9074448/43991845-5401b19c-9d75-11e8-9942-d78ad1ff21b4.png)
If you're just using your mouse to play, it saves you from having to use the keyboard to erase the field.

**Comment by Justsofun** [comment] 2018-08-11 12:47
How do you search anything without using the keyboard?

**Comment by Gamer1120** [comment] 2018-08-11 12:51
There are cases in which you already have something typed and just want to erase it to show all options again.

**Comment by Nightfirecat** [comment] 2018-08-11 17:51
Duplicate of #3222

**Closed** 2018-08-11 17:51 UTC
