### ISSUE TITLE
Add farming notifier

### ISSUE THREAD

**Issue by Ozencb** [runelite/runelite#3615] opened 2018-06-04 12:14 UTC
Notifying players when plants fully grow through in-game chat would be a good addition for hardcore farmers. This can be added directly to farming tracker menu and notifiers can be set or cancelled by right clicking on crops.

![Menu](https://user-images.githubusercontent.com/18405305/40916199-8c95ef12-6807-11e8-8a58-cf11e811550f.png)

![Game message](https://user-images.githubusercontent.com/18405305/40916828-e3e4a720-6809-11e8-9ea9-0c6e267c2199.png)

**Comment by deathbeam** [comment] 2018-06-04 12:15
Duplicate of #2212

**Closed by deathbeam** 2018-06-04 12:15 UTC
