### ISSUE TITLE
Customisable Farming Timer Tab 

### ISSUE THREAD

**Issue by Clempwnzu** [runelite/runelite#13759] opened 2021-06-19 18:05 UTC
The farming timers are great, and I love the idea, but I was wondering if there was a way you could have a customised tab where you can add 1 of each crop e.g 1 cactus patch, 1 hardwood patch, 1 fruit tree patch.

If it was user customisable, different farmers using different sets of farming runs could have a single page with various timers on that doesn't include the plants they're not actively farming and at the same time helps them keep track of what they're supposed to be farming 

I'm farming stuff from all over the timer sets for the pet which is why I ask

thanks for reading :) 
Clem

**Comment by Hydrox6** [comment] 2021-06-19 18:34
Duplicate of #3056

**Closed by Hydrox6** 2021-06-19 18:34 UTC
