### ISSUE TITLE
Slayer task timer

### ISSUE THREAD

**Issue by Curbridge** [runelite/runelite#10984] opened 2020-03-08 21:41 UTC
**Is your feature request related to a problem? Please describe.**
Not a current problem or bug - I would like to know rough time to task completion for slayer task. 

**Describe the solution you'd like**
Similar to exp drops working out your exp/hr, a timer for a rough time on task completion. So if I'm getting 3 exp drops a minute = 3 kills a minute, 150 kills left would be 50 minutes.

I know that this would be inaccurate when killing multiples using multicast spells/chins due to deaths occuring in the same game tick, but that is a current bug with the slayer counter anyway.

**Comment by Nightfirecat** [comment] 2020-03-12 06:02
Duplicate of #5392, #7349

**Closed by Nightfirecat** 2020-03-12 06:02 UTC
Labels: duplicate
