### ISSUE TITLE
Treat Sherlock Clues separately from Cryptics

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#2053] opened 2018-04-27 16:51 UTC
Currently, Sherlock clues simply say to talk to Sherlock, and are counted as Cryptics. Realistically, they should be considered Challenge Clues, and could show the task required for the clue & whether it has been completed.

**Comment by deathbeam** [comment] 2018-11-26 13:45
Duplicate of #2740

**Closed by deathbeam** 2018-11-26 13:45 UTC
Labels: clues
