### ISSUE TITLE
Antipoison timer is not right

### ISSUE THREAD

**Issue by WoneTooPhree** [runelite/runelite#6850] opened 2018-12-07 00:06 UTC
Hello,
There is 2 bug with how antipoison timer works.

> **Describe the bug**
> Clicking but not drinking antipoison potion makes the timer start.
> 
> **To Reproduce**
> 1. Drink a random potion
> 2. Click antipoison potion (before the character finishes the last one)
> 3. Antipoison timer will start
> 
> **Screenshots**
> [gif](https://imgur.com/4WTL6T9)
> 
> **Expected behavior**
> Timer should not appear.

Also

> **Describe the bug**
> Clicking the heartorb while poisoned and having an antipoison in inventory will cure poison but not start the timer
> 
> **To Reproduce**
> 1. Get poisoned
> 2. Click hearth orb with antipoison in inventory
> 3. Antipoison timer will not start
> 
> **Expected behavior**
> Timer should appear.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.3
 - Launcher version: 1.6.0

**Additional notes**
Same with super antipoison
Should also check for relicym's balm and venom.

Thank you.
Wone.

**Comment by deathbeam** [comment] 2018-12-07 00:10
Duplicate of #1471

**Closed by deathbeam** 2018-12-07 00:10 UTC
