### ISSUE TITLE
[Suggestion] Gem Bag Overlay / Icons

### ISSUE THREAD

**Issue by AmazingJesus** [runelite/runelite#6905] opened 2018-12-11 13:46 UTC
This can be done in 2 ways.
An option like Rune Pouch to show whats inside of the Gem Bags.
![](https://i.gyazo.com/de9fccf5811721762438355f6658d841.png)

Or a hover option like RS3
![](https://i.gyazo.com/6c1105072cd314a0d32e415eb98909f3.png)

Idk if its a lot of work, its a simple thing to have :)

**Comment by Nightfirecat** [comment] 2018-12-11 16:23
I don't believe the client has any information on what gems exist within the gem bag, and it wouldn't be reliable to try and track when gems are added to it.

**Comment by AmazingJesus** [comment] 2018-12-11 17:44
What if it updates when u check?

**Comment by raiyni** [comment] 2018-12-11 18:03
then it's fairly useless because you already checked it to know what's in it

**Comment by AmazingJesus** [comment] 2018-12-12 01:38
You telling me that this would be the only plugin on the client that you would need to check before it displays the correct information?

**Comment by deathbeam** [comment] 2018-12-12 01:41
"correct" information, you would still need to track deposits/withdrawals from gem bag, and that sounds unreliable (same problem as with rune pouches)

**Comment by deathbeam** [comment] 2018-12-15 23:01
Duplicate of #5133

**Closed by deathbeam** 2018-12-15 23:01 UTC
