### ISSUE TITLE
Weird GPU rendering bugs, screen clipping

### ISSUE THREAD

**Issue by Rexicon226** [runelite/runelite#16119] opened 2023-01-06 20:42 UTC
### Type

GPU

### Operating System

Windows

### OS Version

Windows 11

### Bug description

The bug is that when I use the GPU render mode, the screen only renders the bottom left. It's a little hard to explain but, the UI elements such as the skills, the tabs, and the minimap, are all rendering correctly. The problem is with that the game window. The window is only rendering the top left part. I just say look at the screenshots, because I don't see a way to explain it.

RTX 3050 laptop
AMD Ryzen 9 6900hs
32 GB RAM

No GPU issues in other games.

Same problem with 117 HD, but no bugs on plugins :)

I've reinstalled GPU drivers, and I'm 99% sure that the GPU isn't the issue here.

### Screenshots or videos

![image1](https://user-images.githubusercontent.com/87927264/211095504-2333ca02-304f-4dc0-ab13-8bfeaedb11a3.jpg)
![image2](https://user-images.githubusercontent.com/87927264/211095639-629ca96f-6be5-4095-babd-e4a5f107df5b.jpg)

### RuneLite version

RuneLite version: 1.9.6
Launcher version: 2.5.0

### Logs

[client_2023-01-05.0.log](https://github.com/runelite/runelite/files/10362938/client_2023-01-05.0.log)
[launcher_2023-01-05.0.log](https://github.com/runelite/runelite/files/10362939/launcher_2023-01-05.0.log)

**Comment by Adam-** [comment] 2023-01-06 21:03
This is caused by the AA setting in the gpu plugin, but if you can answer these questions it might be helpful to us:

Are you using the *windows launcher*, from RuneLiteSetup.exe? How many displays do you have? What are each of their resolutions, and scaling size? Which displays does this problem happen on? Have you changed the high DPI settings on RuneLite.exe?

**Comment by Rexicon226** [comment] 2023-01-06 21:37
I don't actually know for the first question, I don't think so. I'm launching by running the %localappdata%/RuneLite/Runlite.exe (not directly the exe, it's pinned to the taskbar). I don't know how to change to a high DPI (good idea). 1 display. 3072x1920 16:10 display. I am passing no arguments into the launcher.

**Comment by Adam-** [comment] 2023-01-06 21:45
Go into Windows Display settings, is the `Scale and layout` set to something other than 100%? Or if you go into "Advanced scaling settings", is `Custom scaling` set?

Also can you run `"%localappdata%\runelite\runelite.exe" --debug`, confirm the issue still happens with that, and then upload the launcher log file (it will contain debug logs)?

**Comment by Rexicon226** [comment] 2023-01-06 21:53
Custom scaling is not set, and I changed the scales around and there was no effect on the problem.
Attached are the logs with the debug argument.
[client.log](https://github.com/runelite/runelite/files/10363355/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10363356/launcher.log)

**Comment by Adam-** [comment] 2023-01-06 21:56
is the `Scale and layout` set to something other than 100%?

**Comment by Rexicon226** [comment] 2023-01-06 21:56
its 200%

**Comment by Rexicon226** [comment] 2023-01-06 21:56
which is default for this system.

**Comment by Adam-** [comment] 2023-01-08 16:56
duplicate of #11984. I think this is fixed in c720686183323f6754c8285dd44bc7ce68f54b52

**Closed by Adam-** 2023-01-08 16:56 UTC
Labels: bug, duplicate, gpu
