### ISSUE TITLE
Ground Items Hidden Items Return to previous state

### ISSUE THREAD

**Issue by DalderupMaurice** [runelite/runelite#15772] opened 2022-10-06 11:18 UTC
### Type

Incorrect behavior

### OS Version

Windows 11

### Bug description

Over the years I've built up an ignore list ("Hidden Items" comma-separated list of items). 
However, I'd like to remove everything in this list and use the "Hide under value" feature.

Whenever I remove EVERY entry from the "Hidden Items" list, I close RuneLite and start it back up. The old values are returned in the "Hidden Items" field. 

The conclusion is that changes are NOT saved when shutting down RuneLite, which is the intended behaviour.

### RuneLite version

RL: 1.9
Rev 208
Launcher 2.4.2

**Comment by Alexsuperfly** [comment] 2022-10-06 11:32
duplicate of #8457

**Closed** 2022-10-09 13:47 UTC
Labels: needs-triage
