### ISSUE TITLE
Plugin to change the login screen to different pictures.

### ISSUE THREAD

**Issue by badgehunter** [runelite/runelite#10361] opened 2019-12-01 04:28 UTC
I was frustrated in 2017 when the inferno and the login screen was absolutely horrible https://oldschool.runescape.wiki/w/Main_Menu#/media/File:Inferno_login_screen.png and i hoped that there would been option to just have standard or own login screen.

**Describe the solution you'd like**
Solution: the login screen would be changed to fit the picture what the user is giving, could potentially grow into large with help of bored discord artists.

**Describe alternatives you've considered**
Just flat out overlay that would make potentially horrible background into just buttons being horrible https://i.imgur.com/atLxUEC.png

**Additional context**
2017 inferno login screen was the most horrible login screens ever. I suggested this to protecting eyes for future possible similar horrible screens.

**Comment by Nightfirecat** [comment] 2019-12-01 07:57
Duplicate of #9082

**Closed by Nightfirecat** 2019-12-01 07:57 UTC
