### ISSUE TITLE
Discord intergration with screenshot plugin

### ISSUE THREAD

**Issue by VincentvanDuijn** [runelite/runelite#13596] opened 2021-05-13 14:49 UTC
I have been using runelite for a couple of years already, but found out it could also make screenshots. these are getting placed in the user file of the machine. i found out these where not saved in the cloud or any thing like that, so i am missing some cool screenshots :( 

that made me look into the plugin hub of runelite, here i found some plugins that use webhooks to upload the screenshots to any discord channel. these plugins work fine, but as far as i can see the standard screenshot plugin has more options. it would be realy nice if this plugin could use webhooks aswell. 

i see an option to upload the screenshots to imgur, but i cant find any documentation to link it with my imgur account.

**Comment by Hydrox6** [comment] 2021-05-13 15:38
You can always set up the folder to be synchronised with your preferred web service. Duplicate of #3147

Integrating into Discord webhooks is, like you said, already something that hub plugins do. It would likely be better if those plugins expanded their options.

The screenshot plugin uploads to Imgur through the RL API, and is heavily rate limited. Duplicate of #2120

**Comment by VincentvanDuijn** [comment] 2021-05-13 16:21
ahh okay thanks for the clear awnser :)

**Comment by Nightfirecat** [comment] 2021-05-18 07:12
As these requests are covered by other issues, I am closing this issue.

**Closed by Nightfirecat** 2021-05-18 07:12 UTC
Labels: duplicate
