### ISSUE TITLE
Favorite toggles

### ISSUE THREAD

**Issue by yoghurtis** [runelite/runelite#3975] opened 2018-06-23 12:38 UTC
Add a tab for favorite toggles. There are way to many toggles. This will make it easy to turn on an off features you only use some times, but is annoying when you dont need them.

![tog](https://user-images.githubusercontent.com/39596338/41809729-bb16fca6-76f2-11e8-81b6-c3debce9acdc.PNG)

**Comment by deathbeam** [comment] 2018-06-23 13:32
Isnt this duplicate of #3599?

**Comment by Jasper-ketelaar** [comment] 2018-06-25 20:10
Not exactly. #3599 only suggests pinning settings to the top of the settings panel. This one suggests adding a whole new panel to which you can add stuff from config panels/other panels and group them together. 

I don't think that this feature is very realistic however. Implementing this would either require a large rewrite of the plugin code base with this feature in mind or it would require some very hacky code.

**Comment by deathbeam** [comment] 2019-01-01 03:12
Yeah I think #3599 solved this well enough.

**Closed by deathbeam** 2019-01-01 03:12 UTC
Labels: feature-request
