### ISSUE TITLE
Resizable and/or Small Version of Status Bars

### ISSUE THREAD

**Issue by EXpoZuR** [runelite/runelite#13374] opened 2021-03-22 07:49 UTC
The **Status Bars** plugin is one of the most useful plugins that RuneLite provides. It allows players to quickly see status bars of any two of the following pieces of character information: Prayer, Hitpoints, Run Energy, or Special Attack Energy. 

When the game client is in "Fixed" or "Resizable - Classic" Layouts, these bars are overlaid on the "pillars" of the player's inventory area. However when the player is using the "Resizable - Modern" Layout, the bars are directly to the left of the player's inventory. On several occasions, these bars will obscure important game information (usually during 
mini-games) and/or a small portion of the game world that would otherwise be visible with the plugin turned off. 

I would like to propose an additional setting to the Status Bars plugin which either allows for the free resizing (percentage or number value I would assume) of the status bar width or, more simply, a "small" or "compact" view of the Status Bars. Having compact Status Bars could also allow for the opportunity to provide all four pieces of character information side-by-side while  taking up the same or even less room than that of the current Status Bars.

I have attached a concept design for reference.

Thank you for your consideration.

![Status Bars - RuneLite Feature Suggestion](https://user-images.githubusercontent.com/59267695/111956249-f002c780-8ac0-11eb-80d7-03e3039b1db8.png)

P.S. I am a User Experience Designer with a focus on Interaction Design and Functional Prototyping. If you have any questions, or would need assistance brainstorming or visualizing new features, I would be happy to help.

**Comment by Nightfirecat** [comment] 2021-03-22 07:53
Duplicate of #12846. I think the customizable width suggested there would be roughly equivalent to this use case.

**Comment by EXpoZuR** [comment] 2021-03-22 07:53
Sounds good, thanks!

**Closed by Nightfirecat** 2021-03-22 07:53 UTC
Labels: duplicate
