### ISSUE TITLE
[Suggestion] Alert player when name is mentioned in chat

### ISSUE THREAD

**Issue by s-williams** [runelite/runelite#2982] opened 2018-05-19 22:41 UTC
When the players name is said in chat by another player, the client should release an alert sound and focus the window (like what is done to get the players attention when the player is idle). The alert should also optionally be released when only part of the name is said in the chat.

**Comment by deathbeam** [comment] 2018-05-19 23:11
Duplicate of #1161

**Closed by deathbeam** 2018-05-19 23:11 UTC
