### ISSUE TITLE
[Feature request] Aggro line

### ISSUE THREAD

**Issue by yaze1** [runelite/runelite#3311] opened 2018-05-25 20:09 UTC
At monsters where it's needed: rock crabs, sand crabs, ammonite crabs, 

could there be aggro lines which shows exactly how far you need to run away from them and back to get them to re-aggro you?

**Comment by deathbeam** [comment] 2018-05-25 21:48
Duplicate of #1765

**Closed by deathbeam** 2018-05-25 21:48 UTC
