### ISSUE TITLE
Cannot close client after importing settings

### ISSUE THREAD

**Issue by raiyni** [runelite/runelite#8071] opened 2019-03-02 19:26 UTC
1. Import settings file
2. Wait for config manager to post
3. Try and close the client

`2019-03-02 13:19:40 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.Error: Cannot call invokeAndWait from the event dispatcher thread
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1303)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at net.runelite.client.plugins.PluginManager.stopPlugin(PluginManager.java:363)
	at net.runelite.client.RuneLite.shutdown(RuneLite.java:309)
	at net.runelite.client.ui.ClientUI.lambda$null$5(ClientUI.java:323)
	at net.runelite.client.util.SwingUtil$2.windowClosing(SwingUtil.java:219)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.Window.processWindowEvent(Window.java:2054)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)`

**Comment by Adam-** [comment] 2019-03-02 19:34
duplicate of #7633

**Closed by Adam-** 2019-03-02 19:34 UTC
