### ISSUE TITLE
Loot tracker does not keep track of all kills

### ISSUE THREAD

**Issue by AbdelelKharbachi** [runelite/runelite#8598] opened 2019-04-20 20:54 UTC
A friend of mine was killing zulrah and had 50 kills one day the next day he had 31 on loot tracker. 

Could u guys have a look into that please? thanks :)

**Comment by Hydrox6** [comment] 2019-04-20 20:55
Duplicate of #8596 
You should join the Discord and discuss it in there

**Closed by Hydrox6** 2019-04-20 20:55 UTC
