### ISSUE TITLE
Birdhouses timer

### ISSUE THREAD

**Issue by riabcinskis** [runelite/runelite#4256] opened 2018-07-10 16:01 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add the timer so we could know when to do bird house runs, since a lot of people started doing those.
**Describe alternatives you've considered**

**Additional context**

**Comment by Nightfirecat** [comment] 2018-07-10 16:05
Duplicate of #1224

**Closed** 2018-07-10 17:50 UTC
