### ISSUE TITLE
Client crash on fade-to-black

### ISSUE THREAD

**Issue by Wessie** [runelite/runelite#10189] opened 2019-11-02 23:07 UTC
Game crashes when a fade-to-black occurs, such as when starting/ending a cutscene and when using canoes to travel. The most reliable way to trigger it is to use a canoe.

Log indicates an out of bounds exception:

```
2019-11-03 00:02:35 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: 1880717
	at lx.gh(lx.java:695)
	at bt.kn(bt.java:11432)
	at v.kd(q.java:11333)
	at je.ja(je.java:9508)
	at je.ja(je.java:9533)
	at bi.jb(bi.java:9391)
	at client.fq(client.java:4539)
	at client.au(client.java:1683)
	at bg.ez(bg.java:381)
	at bg.run(bg.java:335)
	at java.lang.Thread.run(Thread.java:748)
```

- OS: Windows 10
- RuneLite version: 1.5.38
- Launcher version: 1.5.2
- Oldschool revision: Rev 185

**Comment by Wessie** [comment] 2019-11-02 23:13
Did some more testing

- GPU Plugin makes no difference
- Hardware acceleration makes no difference

**Comment by abextm** [comment] 2019-11-02 23:41
Do you have your minimap moved out of it's normal location?

**Comment by Wessie** [comment] 2019-11-02 23:44
Indeed I do, moving it back to its normal position seems to fix it. I've had it snapped to the bottom-right snapbox

**Comment by abextm** [comment] 2019-11-03 02:37
so to repro this I need
 - Stretched mode enabled
 - The minimap locked into one of the bottom snap points
   - having it not in a snap point does not cause the crash
 - Client size must be ~1900x1050 or higher
 - There must be a dot drawn somewhere near the bottomish of the minimap
 - for canoes atleast, I need the bottom line tli, not the box tli

**Comment by abextm** [comment] 2019-11-03 05:24
So this is caused by the overlayrenderer always layouting stuff to where it should have been last frame, which happens to be off the frame in this case

**Comment by abextm** [comment] 2019-11-14 12:04
Apparently this can happen somehow on login now with some other odd configuration

**Comment by abextm** [comment] 2019-11-14 12:19
Turns out I didn't test when the the minimap isn't snapped and is off the canvas...

**Comment by abextm** [comment] 2020-01-07 14:27
This was fixed internally.

**Closed by abextm** 2020-01-07 14:27 UTC
Labels: bug
