### ISSUE TITLE
Kills left indicator incorrect when training on controlled.

### ISSUE THREAD

**Issue by Mkerian10** [runelite/runelite#13453] opened 2021-04-08 06:26 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The kills left indicator in the xp plugin is incorrect when training on controlled. In the given example I have 102k experience left for attack and 126k experience left for defense. However it shows me as requiring 200 kills for attack and 670 for defense in order to get the next level which is not correct.

https://imgur.com/a/hvcjYmQ

**To Reproduce**
Train melee on controlled, maybe other combat styles I haven't tested.

**Expected behavior**
Attack should be at roughly 550-600ish kills left.

**Screenshots**
https://imgur.com/a/hvcjYmQ

**Environment (please complete the following information):**
Windows 10, most recent version of Runelite

**Comment by Nightfirecat** [comment] 2021-04-08 06:57
Duplicate of #6479

**Closed by Nightfirecat** 2021-04-08 06:57 UTC
Labels: duplicate
