### ISSUE TITLE
Hidden Ground Items Resetting AGAIN

### ISSUE THREAD

**Issue by T1biriy** [runelite/runelite#15500] opened 2022-08-15 12:54 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10 Version 21H2

### Bug description

Exactly the same bug stated in [this closed 2019 bug report.](https://github.com/runelite/runelite/issues/8457)
[The workaround posted by MarcusOtter](https://github.com/runelite/runelite/issues/8457#issuecomment-564522544) did not work for me.

**Describe the bug**
When removing all or some items from the "Hidden" Ground Items list, after quitting and restarting the client, they are back.

**To Reproduce**

- Go to Ground Items
- Erase everything in "Hidden"
- Close RuneLite
- Open RuneLite
- Check Ground Items

**Expected behavior**
Field should stay cleared after clearing.

### RuneLite version

RuneLite Version 1.8.30
Launcher Version 2.4.2

### Logs

[launcher - changed hidden items.log](https://github.com/runelite/runelite/files/9337302/launcher.-.changed.hidden.items.log)
[launcher - items reset to default.log](https://github.com/runelite/runelite/files/9337303/launcher.-.items.reset.to.default.log)
[client - changed hidden items.log](https://github.com/runelite/runelite/files/9337305/client.-.changed.hidden.items.log)
[client - items reset to default.log](https://github.com/runelite/runelite/files/9337306/client.-.items.reset.to.default.log)

**Comment by Alexsuperfly** [comment] 2022-08-15 13:00
The client sees the empty field as unset, if its unset it sets it with the default value, if you do not want the default value set it with something else.

**Comment by Hydrox6** [comment] 2022-08-15 13:02
Duplicate of #8457

**Closed by Hydrox6** 2022-08-15 13:02 UTC
Labels: needs-triage

**Comment by T1biriy** [comment] 2022-08-15 13:05
> The client sees the empty field as unset, if its unset it sets it with the default value, if you do not want the default value set it with something else.

> [https://github.com/runelite/runelite/issues/8457#issuecomment-564522544](The workaround posted by MarkusOtter) did not work for me.
