### ISSUE TITLE
Announcments

### ISSUE THREAD

**Issue by PerishBtw** [runelite/runelite#12289] opened 2020-08-04 07:36 UTC
@TheStonedTurtle 
Probably better fits as a plugin.
Optional global announcements disabled by default.
Global announcements say when a player in the world maxes their account or when a HCIM dies over a certain total world (maybe customizable so you can choose to have it at 250+ or 2000+)
Example:
"Hardcore Ironman [Player] has fallen. Their total level was [0000] their highest skill being [skill] with [0m xp]"
"Congratulations [Player] for reaching the total level of 2277 and getting their max cape!"

CC announcements that tell you when a player reaches the level 99 or 200mxp
CC announcement that tells you when a failed pure has gotten a defense level. - You know why I'm putting this in here
Example:
"[Player] has achieved the max level of 99 in [skill]! Congratulations!"

Maybe also allow friendlist announcements, so if your friend gets a milestone and isn't in your CC, you can know about it.

Allow us to customize the text color

Any other ideas are welcome.

**Comment by Hydrox6** [comment] 2020-08-04 09:17
Duplicate of #9727
Duplicate of #11399

**Closed by Hydrox6** 2020-08-04 09:17 UTC
