### ISSUE TITLE
Medium clue inaccurate information

### ISSUE THREAD

**Issue by Dharr223** [runelite/runelite#17287] opened 2023-12-17 18:47 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Father Aereck Lumbridge Church challenge clue guide says that "19 or 20" are acceptable answers to Father Aereck's challenge clue.

However, when you try '20', he says 'that is not right'
When you answer '19', he says it is correct. 

### RuneLite version

1.10.17.2
2.6.1

**Comment by YvesW** [comment] 2023-12-17 18:49
Then you did not feel to Jarvis during the  2017 Halloween event.

> Father Aereck is the solution to the medium anagram clue: AREA CHEF TREK. The answer to his challenge scroll is 19 (20 if players failed to save Jarvis during the 2017 Halloween event).

**Comment by Felanbird** [comment] 2023-12-17 18:57
Duplicate of #15526

**Closed** 2023-12-17 20:25 UTC
Labels: duplicate
