### ISSUE TITLE
Recent Clan Chat Bug

### ISSUE THREAD

**Issue by k9mancer** [runelite/runelite#6114] opened 2018-10-21 12:28 UTC
Weird bug with the wording stuff

(https://user-images.githubusercontent.com/33012005/47266951-d36ca900-d56f-11e8-96cf-a1165369327d.png)

**Comment by deathbeam** [comment] 2018-10-21 15:44
Duplicate of #6069

**Closed by deathbeam** 2018-10-21 15:44 UTC
