### ISSUE TITLE
Add "use" instead of "eat" for chocolate bars (Menu Entry Swapper)

### ISSUE THREAD

**Issue by SinMentality** [runelite/runelite#12228] opened 2020-07-25 22:27 UTC
Thousands of chocolate bars are eaten every day on accident. Please assist my quest to never waste another chocolate bar again with an addition to the Menu Entry Swapper plug-in.

Alternative solutions are AHK scripts but I really don't want to use the 'MouseMove' command and risk getting banned by their spotty bot detection system when this is could be so much easier and more widely used for all players. 

This is super straight forward. When 'use' is accepted by Jagex for 'bury' commands, I see nothing wrong with this addition--just as frustrating eating a chocolate bar as it is burying a bone on accident.

**Comment by Hydrox6** [comment] 2020-07-25 22:28
Duplicate of #10159

**Closed by Hydrox6** 2020-07-25 22:28 UTC
