### ISSUE TITLE
Slayer count missing mobs

### ISSUE THREAD

**Issue by ashame** [runelite/runelite#5132] opened 2018-08-26 01:21 UTC
**Describe the bug**
Slayer mobs miscounting while bursting

**To Reproduce**
1. Get a slayer task / update mob count by checking an item
2. Go somewhere to stack mobs / burst
3. Watch the counter, then later 'check' a slayer helm / ring / gem

**Expected behavior**
Number of kills left on the counter to match up with the 'checked' kills, assuming you did the entire task with the slayer plugin enabled / did not switch clients between.

**Environment (please complete the following information):**
 - OS: Windows 10 (Ver. 1803, Build 17134.228)
 - RuneLite version: 1.4.14
 - Launcher version: Unknown

**Additional context**
Assuming it's due to mobs dying simultaneously

**Comment by Abextm** [comment] 2018-08-26 04:01
Duplicate of #1046

**Closed by Abextm** 2018-08-26 04:01 UTC
Labels: duplicate
