### ISSUE TITLE
Hunllef Plugin

### ISSUE THREAD

**Issue by jjs451** [runelite/runelite#9468] opened 2019-07-26 14:44 UTC
The Hunllef follows an attack pattern very similar to demonic gorillas.  It cycles between range and mage about every 4 attacks with some special attacks mixed in.  

A plugin like the demonic gorilla plugin that shows the current attack style would be very helpful.

**Comment by Hydrox6** [comment] 2019-07-26 14:47
Duplicate of #9464

**Closed by Hydrox6** 2019-07-26 14:47 UTC
