### ISSUE TITLE
[Loot Tracker] Add an option to automatically reset loot tracker after killing a separate target from the one it was tracking

### ISSUE THREAD

**Issue by Veeeeeeeee** [runelite/runelite#5814] opened 2018-10-04 18:17 UTC
Sometimes I would forget to right click the bag icon in the Loot Tracker and hit 'reset all' would be nice to add an option so it automatically resets the Loot Tracker if you were to kill for example, a Blue dragon after you were tracking Gargoyles.

**Comment by deathbeam** [comment] 2018-10-04 18:19
Duplicate of #4659

**Closed by deathbeam** 2018-10-04 18:19 UTC
