### ISSUE TITLE
Slayer plugin has wrong icon for Fire Giant Task

### ISSUE THREAD

**Issue by AugusDogus** [runelite/runelite#8884] opened 2019-05-21 21:55 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The slayer task plugin info box for fire giants displays an icon of a fire battlestaff.

**Expected behavior**
To have an icon that better represents the monster. EX: Hellhounds have a hellhound icon.

**Screenshots**
<details>
  <summary>Fire Giant Icon</summary>

![Screenshot_2](https://user-images.githubusercontent.com/9794679/58133216-f97f2800-7be8-11e9-8d39-aeb153dafa48.png)
</details>

<details>
  <summary>Hellhounds Icon</summary>

![hellhounds](https://user-images.githubusercontent.com/9794679/58133287-27646c80-7be9-11e9-9ab4-4b6ce70994da.png)
</details>

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: 1.5.23
 - Launcher version: 1.6.0

**Comment by Kamielvf** [comment] 2019-05-21 21:56
Duplicate of #1562

**Closed by Kamielvf** 2019-05-21 21:56 UTC
