### ISSUE TITLE
Kitten timer for growing cats

### ISSUE THREAD

**Issue by Wingspan005** [runelite/runelite#10130] opened 2019-10-23 17:30 UTC
**Is your feature request related to a problem? Please describe.**
I'm always
frustrated when my  cat runs away from me trying to train him while skilling/doing other things. 

**Describe the solution you'd like**
A timer for all the types of ways you can feed/play/interact with your kitten and the amount of time before the kitten will need more attention. All info for timing I found from the wiki page about kittens in osrs. 

**Describe alternatives you've considered**
A timer for only the best possible way to train a kitten into a cat. aka a ball of wool (51 minutes)

**Additional context**
I'm not good with coding and I thought it would help a lot of people while not being too strong.

**Comment by BlackFalcons** [comment] 2019-10-24 12:54
This seems relevant, would like to see this in Runelite.

**Comment by Hydrox6** [comment] 2019-10-24 12:56
You already get chat messages when your cat is needing attention or food, which can be made to notify you with `Chat Notifications`

**Comment by Nightfirecat** [comment] 2020-07-13 05:17
Duplicate of #3815

**Closed by Nightfirecat** 2020-07-13 05:17 UTC
Labels: duplicate
