### ISSUE TITLE
Add NPC whitelist or blacklist feature to Loot Tracker

### ISSUE THREAD

**Issue by IdeaGuy17** [runelite/runelite#5405] opened 2018-09-09 07:59 UTC
In raids you want to only record the chest drop at the end, you don't want to see 7+ records of Seeds from Guardians, Shamans, and Mystics. As well as loads of junk from 10+ Scavengers. 

I'd like to suggest several features to combat this issue, as well as similar issues.

Please allow players to blacklist NPC's by alt-clicking an NPC's drop record and/or by manually typing the names into a whitelist text bow. 
It would also be convenience to have a shift+click feature similar to Windows OS folder setup so you can hold shift and select the ones you don't want and delete them at the same time, or right-click for a "Reset Others" option, similar to OSBuddy's exp tracker feature.

A very easy work-around would just be to whitelist the ones you do care about, and have a button that makes them show separate from everything else.

**Comment by Kamielvf** [comment] 2018-09-09 08:28
Most likely duplicate of some issue already, and this has been planned to be improved from when the loot tracker was added into the client. 

Something like this will solve your issue:
![img](https://camo.githubusercontent.com/2ac74dd8dcfee738dbea96dab743f9544a4eb9c9/68747470733a2f2f692e6779617a6f2e636f6d2f36666534626539633436383565613431623339373930643539373839633637632e706e67)
![img](https://camo.githubusercontent.com/97a903e0beeaeabf63c11519e624e4a02854a87a/68747470733a2f2f692e6779617a6f2e636f6d2f63663135373233616466666330363730313665353533656331636431313562652e706e67)

**Comment by deathbeam** [comment] 2018-09-09 11:00
Duplicate of #4659

**Closed by deathbeam** 2018-09-09 11:00 UTC

**Comment by IdeaGuy17** [comment] 2018-09-09 12:14
I apologize if I made a duplicate. I made only a weak effort to find another post regarding a similar suggestion.
