### ISSUE TITLE
HD Prayer Bar

### ISSUE THREAD

**Issue by zombiezrule** [runelite/runelite#9265] opened 2019-07-02 15:29 UTC
The "Interface Styles" plugin has the HD Health bar, and the "Prayer" plugin gives an overhead prayer bar similar to the normal health bar. Would be nice if the overhead prayer bar could have a HD option, although not sure how difficult this would be.

**Comment by Hydrox6** [comment] 2019-07-02 15:30
Duplicate of #8470

**Closed by Hydrox6** 2019-07-02 15:30 UTC
