### ISSUE TITLE
combat level calculator

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#12220] opened 2020-07-24 11:06 UTC
suggestion:
add a combat level calculator (similar to what osbuddy pro has)

Solution 1:
this will be a separate calculator to the skilling calculator this will show what combat level you will be if you get a certain combat style level up.

for example
60 attack
1 defence
99 prayer/range/magic/strength

you will be 88.93 combat level, and so on...

**Comment by Hydrox6** [comment] 2020-07-24 11:09
Duplicate of #10741
As I mentioned in there, this feature is better served by the [wiki's combat level calculator](https://oldschool.runescape.wiki/w/Combat_level#Wiki_combat_calculator) anyway

**Closed by Hydrox6** 2020-07-24 11:09 UTC
