### ISSUE TITLE
Jogamp

### ISSUE THREAD

**Issue by kcgillette** [runelite/runelite#11288] opened 2020-04-16 20:03 UTC
Hi there, whenever i try to load the client, the game does not load until i manually end this process and one of a similar name that appears when this one is closed. AFAIK my java is all updated to the recent, anyonelse having this issue?  The files themselves are in my Temp folder.

Any help greatly appreciated.
![jogamp](https://user-images.githubusercontent.com/63816633/79501254-a6466d00-8025-11ea-8bae-676f20b4de70.png)

Thanks

**Comment by Hydrox6** [comment] 2020-04-16 20:06
Duplicate of #11159

**Closed by Hydrox6** 2020-04-16 20:06 UTC
