### ISSUE TITLE
Varrock rooftop agility course. one of the screen markers does not turn red when there is a mark on the floor

### ISSUE THREAD

**Issue by oob1234** [runelite/runelite#13484] opened 2021-04-14 18:43 UTC
This marker on the screen does not turn red when there is a mark of grace on the floor
https://i.imgur.com/ydGCypb.png

**Comment by Nightfirecat** [comment] 2021-04-14 18:47
Duplicate of #4076

**Closed by Nightfirecat** 2021-04-14 18:47 UTC
Labels: duplicate
