### ISSUE TITLE
Loot tracker tracking coins from ring of wealth + Seed box

### ISSUE THREAD

**Issue by LeeW95** [runelite/runelite#12315] opened 2020-08-09 20:40 UTC
So I'm just wondering if it's possible to track loot for example from a ring of wealth the coins that would drop automatically get picked up and therefore don't get tracked on the loot tracker, same goes for seeds you pickpocket from a master farmer if they were to go into the seed box they aren't tracked, not sure if there's any other interactions this happens with but I always like to see the exact drops/values of items so hopefully this is something that is fixable.

**Comment by melkypie** [comment] 2020-08-09 20:43
Duplicate of #5077 and #11290

**Closed by melkypie** 2020-08-09 20:43 UTC
