### ISSUE TITLE
Show xp drops if you don't hit as 0

### ISSUE THREAD

**Issue by githubber08** [runelite/runelite#12869] opened 2020-12-01 17:49 UTC
**Is your feature request related to a problem? Please describe.**

Ok so is it possible for runelite to show 0 as an xp drop if you miss an attack or hit a 0 on the npc?

**Describe the solution you'd like**
I want a 0xp drop for runelite whenever you hit 0s on an npc

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Nightfirecat** [comment] 2020-12-01 17:55
You should already be able to achieve this by using the "Fake Xp Drop delay" setting of the XP Drop plugin. Set it to the same tick speed as your weapon and you'll always get a drop when you attack, whether it's a real or fake one.

**Comment by acdvs** [comment] 2020-12-02 05:33
@Nightfirecat That's an unreasonable workaround. You'd have to know the tick speed of every weapon you use and also deal with enabling/disabling it every time you enter/leave a fight.

**Comment by Hydrox6** [comment] 2020-12-10 10:16
Duplicate of #10658

**Closed by Hydrox6** 2020-12-10 10:16 UTC
