### ISSUE TITLE
Colourblind trouble

### ISSUE THREAD

**Issue by Antedekebab** [runelite/runelite#3169] opened 2018-05-23 20:34 UTC
In reziseablemode/transparent mode the Clan chatt text appears as red, so do the drop notification texts. I have changed those colours in the runelite tools but it seems to not apply why? The colour gets changed when I type !Price.

**Comment by deathbeam** [comment] 2018-05-23 22:36
Duplicate of #2224

**Closed by deathbeam** 2018-05-23 22:36 UTC
