### ISSUE TITLE
Chat message not sent, key remapping plugin issue perhaps

### ISSUE THREAD

**Issue by T7000** [runelite/runelite#9266] opened 2019-07-02 16:18 UTC
The vast majority of my messages get sent but I notice my messages not sending like 3 to 5 times per day, I believe I've started noticing it the past week. Usually I've been busy with something and disregarding it, thinking I must've cancelled typing a message by pressing escape but just now it happened again and I'm 100% sure that's not what happened.

**Steps to reproduce the behavior:**
1. Press Enter/Return to start chatting (because that's required with the key remapping plugin)
2. Type message
3. Press Enter/Return to send
4. Rarely, the message isn't sent and the input box resets to the "Press Enter to Chat...." text from the key remapping plugin

**Expected behavior**
Message is sent ;)

Windows 10
RuneLite 1.5.27
Launcher 1.6.0

**Comment by nickwigton** [comment] 2019-07-29 03:51
Additional information - I can recreate this consistently. It is only showing up when you have key remapping turned on. Steps to reproduce:

Start typing in clan chat ("/hello")
Press escape, which clears the text chat
Type a new message ("/world")
Press enter
The message "world" does not show up.

This only shows up in clan chat for me.

**Comment by Adam-** [comment] 2019-08-06 12:46
This was due to a change introduced which cleared the chatbox input when enter was pressed in typing mode. It races with the client's keyhandler which can cause the message to sometimes not send. Fixed in 0e8d377adfe688e5b9a98f5564ae2e2b4f46692f

**Closed by Adam-** 2019-08-06 12:46 UTC
Labels: bug
