### ISSUE TITLE
Calculate total value of herbs when checking herb sack

### ISSUE THREAD

**Issue by yjiang0** [runelite/runelite#11060] opened 2020-03-24 08:55 UTC
**Is your feature request related to a problem? Please describe.**
Not able the value of herbs my herb sack is holding.

**Describe the solution you'd like**
When 'check' an herb sack, it should display to total value of herbs in herb sack. Similiar to the price check feature when examine an item.

**Comment by Hydrox6** [comment] 2020-03-24 09:14
Duplicate of #4573

**Closed by Hydrox6** 2020-03-24 09:14 UTC
