### ISSUE TITLE
Partial completion of farming timers

### ISSUE THREAD

**Issue by Maaziasq** [runelite/runelite#11428] opened 2020-05-01 22:49 UTC
Would it be possible for the timer plugin to display if say 3/4 of my fruit trees have grown? This would stop the longer lasting grows like spirit trees and calquats from blocking me from seeing the whether the other plants have grown without having to constantly click in to the individual menus.

**Comment by raiyni** [comment] 2020-05-02 01:57
Like #8893 ?

**Comment by Maaziasq** [comment] 2020-05-02 15:12
A little bit like that but I don't see why they would be mutually exclusive. I think the idea of being able to favorite timers is great but also seeing partial completion would be very useful and involve less manual tinkering.

**Comment by raiyni** [comment] 2020-05-04 15:43
Duplicate of #9445

**Closed by raiyni** 2020-05-04 15:43 UTC
Labels: duplicate, feature-request
