### ISSUE TITLE
Xp drops show away from the xp globes if they are still in the middle.

### ISSUE THREAD

**Issue by offZills** [runelite/runelite#4650] opened 2018-08-02 16:28 UTC
whenever i set the xp globes to me in the middle of the screen,then i get xp in any sill the xp drops shows either on the very right or the very left of the screen,it doesn`t show right under the globes,i have to set the globes to be on the left as well,please fix this <3

**Comment by deathbeam** [comment] 2018-08-02 16:34
Move the xp drops to the center as well https://github.com/runelite/runelite/wiki/XP-Drop. Might be duplicate of #1757 also.

**Closed by deathbeam** 2018-08-02 16:34 UTC

**Comment by offZills** [comment] 2018-08-02 18:05
xp drops still shows and the very left while globes are in the middle
