### ISSUE TITLE
Account based bank tags / Unique bank tags for different accounts

### ISSUE THREAD

**Issue by MichaelUnce** [runelite/runelite#8182] opened 2019-03-12 02:41 UTC
So at the moment bank tags are based on your profile that you use to log in the runelite client ( i think) it might also just save your bank tags in a json file somewhere too, but the point is its only profile based as someone who plays more than 1 account at a time i run into an issue where both my bank tags interfere with the other account. For example if i do farming on both since stats are different i have to use 2 different bank tag types so that its unique for each account but i still see my bank tags that are on my main account which makes an extra bank tag slot on my alt that just takes up space for no reason. So it would be nice if bank tags were account based such as it sees the account username and just associates the appropriate bank tags that were saved with it. Also not sure if this is a bug but if i have a bank tag named "farming runs" and another called "farming" because the same keyword is used it will see the bank tag as the same this is the samething when i want them to be unique samething applies if i use the same farming runs bank tag and another with just "fa" because the same characters are in there and it looks like it reads it linearly.

Now this is a feature as i described would not just be useful for people who play 2 accounts at once but if they want to go on there pk account or w.e if someone has a solution to this that works let me know i'd love to have unique bank tags for each account without seeing tags that i already used

**Additional context**

**Comment by deathbeam** [comment] 2019-03-17 17:42
Duplicate of #6118

**Closed by deathbeam** 2019-03-17 17:42 UTC
