### ISSUE TITLE
Prayer Potion Notifier (request)

### ISSUE THREAD

**Issue by FaLLeNShoTz** [runelite/runelite#3178] opened 2018-05-24 00:12 UTC
Is anyone able to add a prayer notifier in an in-game overlay similar to the one osbuddy uses. It will pop up with a little flashing icon on screen when the ideal time to drink a prayer pot is. Let me know!

**Comment by Infinitay** [comment] 2018-05-24 00:14
#3089 is working on this and nearly complete if I'm not mistaken.

**Comment by FaLLeNShoTz** [comment] 2018-05-24 00:17
Okay thanks! Yeah I see it now. Someone me tioned a comment to make it more noticeable. But that's much better than nothing!

**Comment by FaLLeNShoTz** [comment] 2018-05-24 00:17
Hope it gets added soon!

**Comment by Adam-** [comment] 2018-05-24 00:45
Duplicate of #598

**Closed by Adam-** 2018-05-24 00:45 UTC
