### ISSUE TITLE
MAC Client not launching

### ISSUE THREAD

**Issue by Choopathingy** [runelite/runelite#1938] opened 2018-04-25 21:50 UTC
MAC client will either just sit on the bar and 'bounce' or it will open the client but stay stuck at 0%.

**Comment by richardbadman** [comment] 2018-04-25 22:01
I managed to successfully run it from the`dmg` and pulling from the latest master.
My mac is running `macOS Sierra v10.12.6` _(If that helps)_

**Comment by deathbeam** [comment] 2018-04-26 09:13
Closing in favour of https://github.com/runelite/launcher/issues/17

**Closed by deathbeam** 2018-04-26 09:13 UTC
Labels: bug

**Comment by miratepuffin** [comment] 2018-05-13 15:17
I don't know if you are still having this problem, but I just the same thing. Run the exec inside of the dmg and it was because I didn't have OpenGL installed.

For a quick way to get it, open your terminal and install homebrew (https://brew.sh/)
and then type:
brew install glfw3
brew install glew

Should run fine after that.

**Comment by jorisrs** [comment] 2018-05-13 16:53
The solution of @miratepuffin worked like a charm.  The client didn't launch on OS X 10.13.4 (17E199)

**Comment by miratepuffin** [comment] 2018-05-13 18:51
Glad to here it helped :)

**Comment by Fredgusta** [comment] 2018-09-08 15:01
Still doesn't work with version 10.13.6 (17G65). Even after the @miratepuffin fix.

**Comment by deathbeam** [comment] 2018-09-08 15:01
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client

**Comment by tripleee12** [comment] 2018-11-12 22:01
> I don't know if you are still having this problem, but I just the same thing. Ran the exec inside of the dmg to see what the error was and I didn't have OpenGL installed. (I assume not included in a fresh MacOS install)
> 
> For a quick way to get it, open your terminal and install homebrew (https://brew.sh/)
> and then type:
> brew install glfw3
> brew install glew
> 
> Should run fine after that.

Hey this fixed my problem immediately to run Runelite, however I am now no longer able to run youtube videos properly across multiple browsers and with a steady internet connection. I have next to zero computer programming knowledge so I am wondering if you have any suggestions as to how I should proceed?

**Comment by deathbeam** [comment] 2018-11-12 22:02
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration try this as alternative

**Comment by tripleee12** [comment] 2018-11-12 22:32
> https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration try this as alternative

No dice man but I appreciate your help!

**Comment by miratepuffin** [comment] 2018-11-21 14:03
Hi @tripleee12 apologies for the slow reply! Without seeing the machine for myself I can't really make suggestions for why this would be occurring, though I would be surprised if openGL was the cause. Have you installed anything else recently which could have caused it?
