### ISSUE TITLE
Player indicators for dangerous areas only

### ISSUE THREAD

**Issue by stefan-visser** [runelite/runelite#14059] opened 2021-08-24 07:07 UTC
Please make it so there's a toggle/option to only indicate other players when you're in a dangerous area (e.g. Wilderness), so that you won't see a screen full of names when you're at the Grand Exchange for example. Would be much appreciated.

**Comment by Bram91** [comment] 2021-08-24 07:11
Duplicate of #3684

**Closed** 2021-08-24 07:17 UTC
Labels: duplicate
