### ISSUE TITLE
Challenge scroll answers

### ISSUE THREAD

**Issue by adambtwl0l** [runelite/runelite#10517] opened 2019-12-29 07:52 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise what the problem is. Ex. I'm always
frustrated when [...]
When doing a clue it's pretty inconvenient for the answer to a challenge scroll step (Question/answer version) to close out and remove the answer because the clue scroll itself isn't active / left your inventory and the item ID changed, meaning you have to either remember the answer (sometimes challenging especially the spirit tree in tree gnome village which is something like 133222111) or look it up which more or less defeats the purpose of the plugin giving it to you in the first place. This is annoying because you have to open the clue obviously to read what the next step is anyways, as well as in the case of elites to answer it since those steps are different for elites.

**Describe the solution you'd like**
If possible make the interface/overlay showing the question stay open until you receive a new clue step instead of just the challenge scroll, or make it display the applicable answer to the challenge scroll upon opening. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
Not many alternatives besides remembering / looking up the answer.

**Additional context**

**Comment by Hydrox6** [comment] 2019-12-29 15:51
Duplicate of #2740

**Closed by Hydrox6** 2019-12-29 15:51 UTC
