### ISSUE TITLE
Mage training arena telekinetic plugin broken

### ISSUE THREAD

**Issue by tonkk** [runelite/runelite#7558] opened 2019-01-25 20:59 UTC
**Describe the bug**
The 'Enable telekinetic room' plugin for mage training arena doesn't work correctly. After 1/24/19 patch it  shows the npc indicator for Maze Guardian when moving it but no tile indicator as to where to stand/cast Telekinetic Grab. I tried it on both fixed & resizable, doesn't work on either.

**To Reproduce**
1. Go to Mage Training Arena
2. Click on Enter Telekinetic Teleport
3. Attempt to solve the maze with runelite plugin
4. End up solving it yourself

**Expected behavior**
The telekinetic room plugin is supposed to show you what's the next tile for your maze to cast telekinetic grab at, updating the appropriate tile after each step

**Screenshots**
https://imgur.com/a/zLejD0d

**Environment (please complete the following information):**
 - OS: windows 10 educational
 - RuneLite version: 1.5.9
 - Launcher version: 1.6.0

**Comment by Nightfirecat** [comment] 2019-01-25 20:59
Duplicate of #7546, will be fixed with next week's update.

**Closed** 2019-01-25 21:05 UTC
