### ISSUE TITLE
Windows notification for monster drops

### ISSUE THREAD

**Issue by Griffinsnore** [runelite/runelite#3760] opened 2018-06-12 22:05 UTC
It would be nice to have the option to toggle a Windows notification for drops over a certain GE or alch value so as to not miss out on good drops when afk'ing certain monsters such as Abyssal Demons.

**Comment by Nightfirecat** [comment] 2018-06-12 22:08
Duplicate of #3643

**Closed** 2018-06-12 22:09 UTC
