### ISSUE TITLE
Silver bracelet charge indicator overlay

### ISSUE THREAD

**Issue by slazum** [runelite/runelite#3840] opened 2018-06-16 09:33 UTC
Cannonballs have a counter under your stat-boost. Would be nice if silver bracelets had the same thing so you wouldn't have to keep looking in your inventory.

**Comment by jpabeem** [comment] 2018-06-16 10:04
related to #1176

**Comment by Alexsuperfly** [comment] 2018-10-07 04:43
i believe this can be considered a duplicate of #1318 since that one encompasses all jewelry

**Closed** 2018-10-07 08:09 UTC
Labels: enhancement
