### ISSUE TITLE
[Request] Display which STASH units you've put items into while doing a clue

### ISSUE THREAD

**Issue by Fathlete** [runelite/runelite#3846] opened 2018-06-16 17:27 UTC
This would be an awesome addition IMO. Sometimes(everytime for me) you don't know if you've put items into that specific location and you end up wasting time getting duplicates OR you think you've put items there and you walk all the way to the clue location but the STASH is empty. Would be nice to have an additional X below the items if you haven't got anything stashed at that location and a little check-mark if you do.

[img]https://i.imgur.com/wOTi6s3.png[/img]

Here's a list of all stash locations;
http://oldschoolrunescape.wikia.com/wiki/STASH

I don't know much about coding but I figured if you can know you've planted a ranarr in Canifis while being on Zeah this might be possible too. 

Thank you!

**Comment by Abextm** [comment] 2018-06-16 17:38
Duplicate of #1662

**Closed by Abextm** 2018-06-16 17:38 UTC
