### ISSUE TITLE
Greater Volume Control

### ISSUE THREAD

**Issue by twayneguitar** [runelite/runelite#6352] opened 2018-11-05 07:43 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

Very simple concept - the volume control is extremely limited.  I typically use Windows Volume Mixer, and I have to bring it all the way down between 1-4 out of 100, 4 being loud and 2 and 1 typically being around where I leave it, but very drastic changes between those 4 levels.  I also use notch 1 in the settings on OSRS.

**Describe the solution you'd like**

A simple in-client 0-100 master volume control for OSRS output.  I'd like to be able to use this in conjunction with Windows Volume Mixer to have better volume control, so I can keep it pretty low so I can listen to other things while watching twitch or youtube, still hear what I need to hear on OSRS, without it being too distracting.  Hard to achieve in current setup.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

As I previously stated, I utilize Windows Volume Mixer but it's extremely limited.  This is really the only option I have to adjust.

**Additional context**

![image](https://user-images.githubusercontent.com/42355980/47984420-942c7500-e0a4-11e8-9942-e91ea21ca3cf.png)

Thanks for your time!

**Comment by deathbeam** [comment] 2018-11-05 08:58
Duplicate of #2213

**Closed by deathbeam** 2018-11-05 08:58 UTC

**Comment by Seppobb** [comment] 2020-12-06 10:44
@deathbeam @twayneguitar  I belive this plugin/update on RL has been broken due to Jagex updating the settings menu. I tried searching for a solution to this but couldn't find one. Will this be adapted in the RL itself, or maybe the music plugin?
