### ISSUE TITLE
Ground Timers

### ISSUE THREAD

**Issue by Castro3halo** [runelite/runelite#2639] opened 2018-05-12 16:07 UTC
No idea how possible this is, but a timer that starts when you drop an item until other players can see it, and until it disappears. Potentially also a timer until drops from monsters disappear as well (makes juggling inventories at bosses etc a lot easier).

**Comment by Hydrox6** [comment] 2018-05-12 16:08
Duplicate of #2383

**Closed** 2018-05-12 16:08 UTC
