### ISSUE TITLE
Runelite Hangs on 'Connecting to update server' on Client Launch

### ISSUE THREAD

**Issue by gnubis** [runelite/runelite#11806] opened 2020-06-04 12:43 UTC
**Description**
Runelite fails to connect to update server on client launch and hangs indefinitely

**Steps To Reproduce**
1. Launch Application
2. Observe hang on 'Connecting to update server'

**Expected behavior**
Update server is connected to successfully and a login screen is eventually seen instead of application hang

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/63074015/83757993-8f3bf880-a62e-11ea-9d6e-7b0ae86e6e1d.png)

**Environment:**
 - OS: Arch-Linux 5.6.15 x86_64 and macOS Mojave 10.14.3
 - RuneLite version: 1.6.17 (Linux) and 2.1.2 (macOS)
 - Launcher version: 2.1.0

**Additional context**
Logs from Linux machine attached
[client.log](https://github.com/runelite/runelite/files/4730025/client.log)
[launcher.log](https://github.com/runelite/runelite/files/4730026/launcher.log)

**Comment by Hydrox6** [comment] 2020-06-04 12:43
Duplicate of #11805

**Closed by Hydrox6** 2020-06-04 12:43 UTC
