### ISSUE TITLE
expeditious bracelet charge overlay doesn't reset to 30 after breaking one

### ISSUE THREAD

**Issue by abra238** [runelite/runelite#3787] opened 2018-06-14 11:59 UTC

**Comment by sethtroll** [comment] 2018-06-15 23:18
I've tested this, and it does in fact reset the value when I break one. It checks for the break widget text every game tick, and it's possible the widget was opened/closed before it was able to detect it.

**Comment by Alexsuperfly** [comment] 2019-07-28 21:07
unable to reproduce, even exiting the message that says charge count reset as quickly as possible

**Comment by Nightfirecat** [comment] 2019-07-29 00:38
@abra238 Are you able to reproduce this?

**Comment by Nightfirecat** [comment] 2019-07-31 16:06
I think we're safe to close this one for the time being. Please comment if this is coming up again and we will re-investigate.

**Closed by Nightfirecat** 2019-07-31 16:06 UTC
Labels: needs-information
