### ISSUE TITLE
Game Frame freeze when GPU plugin enabled. (AMD)

### ISSUE THREAD

**Issue by therealmattshady** [runelite/runelite#6544] opened 2018-11-17 17:53 UTC
How to reproduce:

Open client and let the game load
log into game.
Open the side menu and enable GPU plugin.
Everything freezes. (besides the side menu)

I've tried:
enable/disable compatibility
run as admin
disable HD acceleration (with .bat)
restarting runelite
checked for GPU and windows updates

**Environment:**
Runelite version: 1.5.0
Launcher Version: Unknown

---Graphics Chipset - AMD Radeon (TM) R9 390 Series---
Radeon Settings Version - 2018.0516.1451.24901
Driver Packaging Version - 18.40.11.01-181107a-335518E-RadeonSoftwareAdrenalin
Provider - Advanced Micro Devices, Inc.
2D Driver Version - 8.1.1.1634
Direct3D® Version - 9.14.10.01363
OpenGL® Version - 24.20.11000.13542
OpenCL™ Version - 25.20.14011.1003
AMD Mantle Version - Not Available
AMD Mantle API Version - Not Available
AMD Audio Driver Version - 7.12.0.7728
Vulkan™ Driver Version - 2.0.55
Vulkan™ API Version - 1.1.82

---OS:	Microsoft Windows 7 Home Premium---
Version : 6.1.7601 Service Pack 1 Build 7601
System Type	x64-based PC
Processor	AMD FX(tm)-8350 Eight-Core Processor, 4000 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 2701, 3/24/2016
SMBIOS Version	2.7
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB

If additional information is required please let me know.

**Comment by therealmattshady** [comment] 2018-11-17 18:01
FIXED 

For some reason Method 3: Starting the launcher with HW accel disabled from CMD using "java -jar %localappdata%\RuneLite\RuneLite.jar --mode=OFF" worked... but adding the  " --mode=OFF" in the .bat file didnt work.....

**Comment by deathbeam** [comment] 2018-11-19 15:43
Duplicate of #6523 looks like

**Closed by deathbeam** 2018-11-19 15:43 UTC
Labels: bug, gpu

**Comment by Jakexx360** [comment] 2018-11-25 04:55
> FIXED
> 
> For some reason Method 3: Starting the launcher with HW accel disabled from CMD using "java -jar %localappdata%\RuneLite\RuneLite.jar --mode=OFF" worked... but adding the " --mode=OFF" in the .bat file didnt work.....

Experienced the same issue with GTX 1070, latest drivers, and this worked
