### ISSUE TITLE
Have an option the Time Tracking plugin to notify you when your current contract is grown

### ISSUE THREAD

**Issue by avirunes** [runelite/runelite#13945] opened 2021-07-25 05:53 UTC
**Is your feature request related to a problem? Please describe.**
Currently the best way to keep track of your current contracts growth time is to have the plugin track every patch within the farming guild. Since you usually have multiple things growing at once you get 1 useful notification and then 3-4 that you ignore. The best way to complete many hard contracts is to pre-plant the most common contracts you get, so that you complete 3-4 at once, then replant those while waiting for your current contract. 

**Describe the solution you'd like**
An option within the plugin to keep track of your farming contracts growth. The plugin already knows which patch is your farming contract, as it puts a farming pack symbol next to it in the side panel.

**Describe alternatives you've considered**
You could manually select/de-select your contract each time, but that's a pretty tedious approach

**Comment by Hydrox6** [comment] 2021-07-25 09:43
Duplicate of #13675

**Closed by Hydrox6** 2021-07-25 09:43 UTC
