### ISSUE TITLE
Accurate Pricing in Price Lookup

### ISSUE THREAD

**Issue by ElevatedLife** [runelite/runelite#4543] opened 2018-07-28 17:56 UTC
Its a nightmare trying to figure out the actual value of items as the RL pricing is super inaccurate. The GE atleast has the feature to enable the osb price guide when searching items.

Solution: Replace the current price lookup which only gives ge values and not actual street value, with the osb pricing that is used on GE lookup.

**Comment by deathbeam** [comment] 2018-07-28 17:58
Mostly duplicate of #3927, we had similar discussion there that lead to at least expanding the GE lookup with it.

**Closed by deathbeam** 2018-07-28 17:58 UTC
