### ISSUE TITLE
Player-Owned House Plug-in Compatibility Issue with Client Resize-able Mode

### ISSUE THREAD

**Issue by klbowling** [runelite/runelite#11982] opened 2020-06-25 13:03 UTC
**Describe the bug**
When using resize-able mode, POH indicators from the Player-Owned House plugin are not positioned correctly on the minimap.  They appear to be centered on the compass icon rather than the minimap.

**To Reproduce**
1. Enable resize-able mode in the Options menu
2. Enable the Player-Owned House plug-in in the Runelite client
3. Ensure the Client is maximized (click maximize in the top right corner of the client)
4. Enter Player-Owned House
5. See Error

**Expected behavior**
I would expect to see the portal, restoration, etc. indicators in the correct positions on the minimap

**Screenshots**
![POH_Plugin_Fixed_Maximized](https://user-images.githubusercontent.com/67422123/85724890-a10b3b80-b6c2-11ea-8013-fa82c147592c.PNG)
- Fixed Mode Plugin Indicators
![POH_Plugin_Resizeable_Maximized](https://user-images.githubusercontent.com/67422123/85724891-a10b3b80-b6c2-11ea-8985-756a26176a0e.PNG)
- Resizeable Mode Plugin Indicators

IMGUR Backup: [https://imgur.com/a/VS8lSG1]

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.20
 - Launcher version: 2.1.0
 - Oldschool revision: Rev 190

**Comment by Hydrox6** [comment] 2020-06-25 13:12
Duplicate of #11981

**Closed by Hydrox6** 2020-06-25 13:12 UTC
