### ISSUE TITLE
runelite isn't auto resizing with portrait mode on alternate monitor

### ISSUE THREAD

**Issue by Nikipally** [runelite/runelite#10377] opened 2019-12-03 16:52 UTC
So I never had this issue before, basically I play the game on my secondary monitor and usually pull the client to the top of the screen and window's maximizes it. Something changed and it doesn't do that anymore and thinks the monitor is in landscape mode. Pictures below.

runelite:
https://i.gyazo.com/691d5be2cd89da745a657b1f830ec0ca.png

normal osrs client by jagex:
https://i.gyazo.com/cbc7eefa0ef66975abe2c9a3ca4c327e.png

**Comment by Alexsuperfly** [comment] 2019-12-03 16:58
In "runelite" settings turn off custom chrome.    Otherwise join the discord for further inquiries of this type.

**Comment by Nikipally** [comment] 2019-12-03 17:01
settings: https://i.gyazo.com/67afe76156263adb4e03600280bbfd21.png

**Comment by Hydrox6** [comment] 2019-12-03 17:16
Duplicate of #5153

**Closed by Hydrox6** 2019-12-03 17:16 UTC
