### ISSUE TITLE
ground items categories 

### ISSUE THREAD

**Issue by Odinnh** [runelite/runelite#13972] opened 2021-08-03 21:43 UTC
During my grinding of certain monsters i came across the issue where i wanted to separate the drops i got by category of items instead of value a.e. herbs, weapons/gear (maybe metal types) ingredients, etc... 

I would love to see an option to choose either "color drops based on value (ge/ ha)" or "color drops based on categories "

we currently have the ability to "ignore" and "highlight" items, if pre existing categories are an issue i would love an option to group the drops myself 

the drop highligh beams could also be enabled/disabled per group instead of value+

**Comment by Hydrox6** [comment] 2021-08-03 21:55
Duplicate of #12274

**Closed by Hydrox6** 2021-08-03 21:55 UTC
