### ISSUE TITLE
Animation Smoothing causes the Zombie Protesters on Braindeath Island to bug out.

### ISSUE THREAD

**Issue by Zythixx** [runelite/runelite#11057] opened 2020-03-23 05:53 UTC
**Describe the bug**
When NPC Animation Smoothing is enabled the Zombie's protest signs spin when they move.

![ZombieProtestor_ASBug](https://user-images.githubusercontent.com/62533923/77285964-ac586080-6ca8-11ea-8118-890600d9f7f0.gif)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.9
 - Launcher version: 2.1.0

**Comment by Nightfirecat** [comment] 2020-03-23 05:59
Duplicate of #8206

**Closed by Nightfirecat** 2020-03-23 05:59 UTC
Labels: duplicate
