### ISSUE TITLE
GPU Plugin/Unlock Framerate

### ISSUE THREAD

**Issue by timbojim** [runelite/runelite#14319] opened 2021-10-29 05:13 UTC
When uncapped frame rate is enabled on either GPU plugin or the 117HD plugin, click registration on the ground only happens 10% of the time for both right and left clicks. For example if you spam left click to walk somewhere only a couple of clicks will actually go through (same with right click). However this only happens when trying to click the ground as I can interact with banks/NPCs/GE without any issue. I have tried both GSYNC on and off. I am running Ryzen 5600x 1070sc @ 144HZ.

**Comment by Nightfirecat** [comment] 2022-07-10 05:09
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 05:09 UTC
