### ISSUE TITLE
Menu swapping on rune essence pouch

### ISSUE THREAD

**Issue by choocher13** [runelite/runelite#5979] opened 2018-10-13 01:50 UTC
To right click and press Fill from within the bank is quite tedious.

I would like it to be possible to swap the order so Fill is on left click while in the bank.

Maybe Jagex would deem this as OP and easyscape but it would be awesome if possible. Thanks for hearing me out.

**Comment by Nightfirecat** [comment] 2018-10-13 01:51
Duplicate of  #5668

**Comment by choocher13** [comment] 2018-10-13 01:52
I see. Thank you for pointing it out.

**Closed** 2018-10-13 01:51 UTC
