### ISSUE TITLE
Anti Aliasing not working on GTX 1080 ti

### ISSUE THREAD

**Issue by mattgriffi** [runelite/runelite#11984] opened 2020-06-25 17:34 UTC
**Description**
This issue is likely related to #7197, but is somewhat different in my case. With anti aliasing enabled, there are graphical glitches in the top and right sections of the game window. The game world does not redraw in this section when moving or rotating the camera, but Runelite overlays are drawn, and UI elements such as the minimap and inventory are functional, but exhibit the same graphical glitch as the overlays.

The correctly-drawn section in the bottom left works normally with no issues at all, and this section resizes proportionally when the Runelite window is resized; it is only the top and right parts of the screen that exhibit this bug regardless of resolution.

Unlike #7197, this issue is present on all levels of anti aliasing. Also, disabling the Interface Styles plugin has no effect. It is also present on a fresh install of Runelite.

**Environment**
 - OS: Windows 10
 - RuneLite version: 1.6.21
 - Launcher version: 2.1.3
 - GPU: GTX 1080 ti
 - Nvidia Driver versions: tested on 446.14 (5/27/2020) and 451.48 (6/24/2020)

**Screenshots**
![Demonstration of graphical glitch](https://i.imgur.com/qGtflBf.jpg)

**Comment by zacharydwaller** [comment] 2020-07-07 00:26
I was having this same problem when my Windows 10 Scaling was set at 125% or higher. The issue went away after I updated Java (now at Version 8 Update 251).

**Comment by mattgriffi** [comment] 2021-11-05 15:32
I am still experiencing this issue. In the past year, I have replaced several PC parts including the CPU (now a Ryzen 7 5800X) and the GPU (now a 3080), have updated the launcher and Runelite versions (now 1.8.1 and 2.1.7), have reinstalled Java with the latest version (now 1.8.0_311), and have updated Nvidia drivers several times (now 496.49). The issue has persisted through all of this.

The issue occurs with both the GPU plugin and 117's HD plugin.

[Video of issue](https://gfycat.com/AjarLastingAfricanelephant)

@Nightfirecat What additional information would help with this issue?

**Comment by Nightfirecat** [comment] 2021-11-11 22:28
Does this issue happen with the Stretched Mode plugin disabled?

**Comment by mattgriffi** [comment] 2021-11-11 22:53
Yes, it still happens with Stretched Mode disabled. It also happens with both resizable and fixed layouts.

https://i.imgur.com/SHADs6r.png

**Comment by cigary1** [comment] 2021-11-29 20:05
Did you ever find a solution? I have the same problem. RTX 2060. Turning off interface styles does nothing. Nvidia Control Panel does nothing. Very frustrating. My game looked perfect before I tried the fullscreen plugin, now I can't use anti-aliasing at all.

**Comment by raiyni** [comment] 2022-05-13 14:49
Is this issue still present after all of the driver updates?

**Comment by mattgriffi** [comment] 2022-05-13 15:01
I just updated to the latest Nvidia driver yesterday and the issue is still present when enabling anti aliasing in the GPU plugin.

Interestingly, the anti aliasing in 117's HD plugin now has a different issue. The GPU plugin still has the issue shown above, but 117's plugin now renders overlays correctly, but is otherwise blacked out on the top and right sides. So, there must have been some change in 117's plugin that partially fixed this issue.

With GPU plugin
![GPU plugin issue](https://i.imgur.com/v1ICHSi.jpeg)

With 117's HD plugin
![117 HD plugin issue](https://i.imgur.com/ROeaXxq.jpeg)

**Comment by Nightfirecat** [comment] 2022-07-10 04:17
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Comment by mattgriffi** [comment] 2022-07-10 17:49
@Nightfirecat The issue is still happening. Is there any additional information I can provide to help with reproducibility?

**Comment by Adam-** [comment] 2023-01-08 16:55
We think this is fixed in c720686183323f6754c8285dd44bc7ce68f54b52. It is caused by using both aa and also j2d display scaling at once. The FBO used for aa was not accounting for the scaling applied by j2d. By default, RL won't use j2d scaling unless you pass --scale, or possibly mess with the Windows high dpi settings of the RuneLite executable.

**Closed by Adam-** 2023-01-08 16:55 UTC
Labels: bug, gpu
