### ISSUE TITLE
Compost Status Overlay

### ISSUE THREAD

**Issue by al3x-huang** [runelite/runelite#12123] opened 2020-07-12 21:19 UTC
**Is your feature request related to a problem? Please describe.**
Currently, there is no visual feedback on whether a farming patch has been treated with compost.

**Describe the solution you'd like**
Add an overlay similar to the agility overlay. Have the color be red when a patch has not been treated with compost and green if it has. There are other improvements to farming (#8387, #10794) that can be rolled into this as its own farming plugin.

Alternatively, have a plugin called "Overlay reminder" that allows users to set color overlay reminders when something has not been done. Good use case for extending to #3013.

**Additional context**
I forget to ultracompost my patches sometimes and it makes big sad when herbs die because of my incompetence.

**Comment by melkypie** [comment] 2020-07-13 05:47
Duplicate of #2472

**Closed by melkypie** 2020-07-13 05:47 UTC
Labels: duplicate
