### ISSUE TITLE
Game crash when going to GWD

### ISSUE THREAD

**Issue by tyboyd** [runelite/runelite#4730] opened 2018-08-06 01:08 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
the game runs perfectly fine. I'll be running through troll mountain to the dungeon and when i turn the corner and the snow hits the screen my client freezes. I have to run the osrs client to get to the dungeon then switch

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: windows 7
 - RuneLite version: 1.4.10 fresh download, java is up to date as are my gpu drivers

**Additional context**
2018-08-05 20:26:52 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-08-05 20:26:53 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-08-05 20:26:54 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 4635ms. Uptime: 7480ms
2018-08-05 20:27:18 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@5aa17bf0 opened
2018-08-05 20:27:19 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1044,109,1751x1586,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1751x1586,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@7b2deeaf,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-05 20:31:53 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-08-05 20:31:54 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-08-05 20:31:54 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 3973ms. Uptime: 5735ms
2018-08-05 20:38:06 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-08-05 20:38:07 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-08-05 20:38:08 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 4093ms. Uptime: 5905ms
2018-08-05 20:40:16 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@7f771b6a opened
2018-08-05 20:40:17 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1986,6,1880x1586,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1880x1586,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@5894df73,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-05 20:40:36 [Thread-7] ERROR net.runelite.client.RuneLite - Game crash
java.lang.ArithmeticException: / by zero
	at da.r(da.java:654)
	at dy.ix(dy.java:9333)
	at dy.ix(dy.java:9086)
	at dy.ix(dy.java:9085)
	at iy.ip(iy.java:8624)
	at dy.ix(dy.java:9089)
	at dy.ix(dy.java:9085)
	at iy.ip(iy.java:8624)
	at client.fi(client.java:3481)
	at client.aq(client.java:947)
	at ap.an(ap.java:436)
	at ap.copy$run(ap.java:390)
	at ap.run(ap.java:68)
	at java.lang.Thread.run(Thread.java:748)
2018-08-05 20:41:11 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@618fd512 opened
2018-08-05 20:41:12 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1867,28,1880x1586,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1880x1586,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@291b50b1,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-05 20:41:43 [Thread-7] ERROR net.runelite.client.RuneLite - Game crash
java.lang.ArithmeticException: / by zero
	at da.r(da.java:654)
	at dy.ix(dy.java:9333)
	at dy.ix(dy.java:9086)
	at dy.ix(dy.java:9085)
	at iy.ip(iy.java:8624)
	at dy.ix(dy.java:9089)
	at dy.ix(dy.java:9085)
	at iy.ip(iy.java:8624)
	at client.fi(client.java:3481)
	at client.aq(client.java:947)
	at ap.an(ap.java:436)
	at ap.copy$run(ap.java:390)
	at ap.run(ap.java:68)
	at java.lang.Thread.run(Thread.java:748)
2018-08-05 20:43:16 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@549c7d49 opened
2018-08-05 20:43:17 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1673,86,1880x1586,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1880x1586,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@6f585515,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-05 20:44:07 [Thread-7] ERROR net.runelite.client.RuneLite - Game crash
java.lang.ArithmeticException: / by zero
	at da.r(da.java:654)
	at dy.ix(dy.java:9333)
	at dy.ix(dy.java:9086)
	at dy.ix(dy.java:9085)
	at iy.ip(iy.java:8624)
	at dy.ix(dy.java:9089)
	at dy.ix(dy.java:9085)
	at iy.ip(iy.java:8624)
	at client.fi(client.java:3481)
	at client.aq(client.java:947)
	at ap.an(ap.java:436)
	at ap.copy$run(ap.java:390)
	at ap.run(ap.java:68)
	at java.lang.Thread.run(Thread.java:748)
2018-08-05 20:47:39 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-08-05 20:47:40 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-08-05 20:47:42 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 5469ms. Uptime: 7436ms
2018-08-05 21:03:58 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@311a5538 opened
2018-08-05 21:03:58 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@3f1dc140 opened
2018-08-05 21:03:59 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1673,86,1880x1586,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1880x1586,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@753be711,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-05 21:03:59 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1673,86,1880x1586,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1880x1586,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@1d717968,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-05 21:07:13 [Thread-7] ERROR net.runelite.client.RuneLite - Game crash
java.lang.ArithmeticException: / by zero
	at da.r(da.java:654)
	at dy.ix(dy.java:9333)
	at dy.ix(dy.java:9086)
	at dy.ix(dy.java:9085)
	at iy.ip(iy.java:8624)
	at dy.ix(dy.java:9089)
	at dy.ix(dy.java:9085)
	at iy.ip(iy.java:8624)
	at client.fi(client.java:3481)
	at client.aq(client.java:947)
	at ap.an(ap.java:436)
	at ap.copy$run(ap.java:390)
	at ap.run(ap.java:68)
	at java.lang.Thread.run(Thread.java:748)
2018-08-05 21:29:56 [Thread-7] ERROR net.runelite.client.RuneLite - Game crash
java.lang.ArithmeticException: / by zero
	at da.r(da.java:654)
	at dy.ix(dy.java:9333)
	at dy.ix(dy.java:9086)
	at dy.ix(dy.java:9085)
	at iy.ip(iy.java:8624)
	at dy.ix(dy.java:9089)
	at dy.ix(dy.java:9085)
	at iy.ip(iy.java:8624)
	at client.fi(client.java:3481)
	at client.aq(client.java:947)
	at ap.an(ap.java:436)
	at ap.copy$run(ap.java:390)
	at ap.run(ap.java:68)
	at java.lang.Thread.run(Thread.java:748)
2018-08-05 21:30:30 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@5392266b opened
2018-08-05 21:30:31 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,491,155,1880x1586,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1880x1586,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@9d66772,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-05 21:31:06 [Thread-7] ERROR net.runelite.client.RuneLite - Game crash
java.lang.ArithmeticException: / by zero
	at da.r(da.java:654)
	at dy.ix(dy.java:9333)
	at dy.ix(dy.java:9086)
	at dy.ix(dy.java:9085)
	at iy.ip(iy.java:8624)
	at dy.ix(dy.java:9089)
	at dy.ix(dy.java:9085)
	at iy.ip(iy.java:8624)
	at client.fi(client.java:3481)
	at client.aq(client.java:947)
	at ap.an(ap.java:436)
	at ap.copy$run(ap.java:390)
	at ap.run(ap.java:68)
	at java.lang.Thread.run(Thread.java:748)
2018-08-05 21:38:40 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@310300b3 opened
2018-08-05 21:38:41 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1448,268,1880x1586,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1880x1586,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@6e800dd6,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-05 21:38:51 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-08-05 21:38:52 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-08-05 21:38:53 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 4273ms. Uptime: 6280ms
2018-08-05 22:42:34 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@166f3185 opened
2018-08-05 22:42:36 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1448,268,1880x1586,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1880x1586,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@63123de7,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-05 22:49:28 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@2eb3ea5f opened
2018-08-05 22:49:29 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1448,268,1880x1586,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1880x1586,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@26f0c56f,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-05 23:25:34 [OkHttp https://api.runelite.net/...] WARN  net.runelite.client.account.WSClient - Error in websocket
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-05 23:25:57 [OkHttp https://api.runelite.net/...] WARN  net.runelite.client.account.WSClient - Error in websocket
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-05 23:26:05 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@2dbc2433 opened
2018-08-05 23:26:28 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@7347345e opened
2018-08-06 01:18:34 [OkHttp https://api.runelite.net/...] WARN  net.runelite.client.account.WSClient - Error in websocket
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-06 01:18:58 [OkHttp https://api.runelite.net/...] WARN  net.runelite.client.account.WSClient - Error in websocket
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-06 01:19:05 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@5c06cf9e opened
2018-08-06 01:19:28 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@185b28b6 opened
2018-08-06 01:29:58 [OkHttp https://api.runelite.net/...] WARN  net.runelite.client.account.WSClient - Error in websocket
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-06 01:30:04 [OkHttp https://api.runelite.net/...] WARN  net.runelite.client.account.WSClient - Error in websocket
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-06 01:30:28 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@4ab78747 opened
2018-08-06 01:30:35 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@3c2cd9f1 opened
2018-08-06 01:32:04 [OkHttp https://api.runelite.net/...] WARN  net.runelite.client.account.WSClient - Error in websocket
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-06 01:32:28 [OkHttp https://api.runelite.net/...] WARN  net.runelite.client.account.WSClient - Error in websocket
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-06 01:32:35 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@98651c6 opened
2018-08-06 01:32:58 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@94bb0ef opened

**Comment by tyboyd** [comment] 2018-08-06 18:20
how do i go about getting the logs? I tried the same area with all my plugins disabled as well.

**Comment by tyboyd** [comment] 2018-08-06 18:27
ok I updated the log section! Sorry!

**Comment by tyboyd** [comment] 2018-08-06 21:22
no and the zoom level was as far out as the standard would allow. It doesnt matter which tile I was on. As soon as the snow hit the screen the game would crash. Is there a way to remove the snow clutter? I know it's not my pc. I am running a high end gaming pc so that cant be the problem.

**Comment by tyboyd** [comment] 2018-08-06 21:25
I could hop on quick and get a screen shot though if its necessary.

**Comment by Kamielvf** [comment] 2018-08-06 21:25
Would it be possible to take a gif/recording/screenshot of your client crashing?

**Comment by Adam-** [comment] 2018-08-07 11:37
Can you try this same thing with the vanilla client?

**Comment by tyboyd** [comment] 2018-08-08 01:44
yes, it works with vanilla, konduit and osbuddy. Only runelite freezes up

**Comment by tyboyd** [comment] 2018-08-08 17:56
ok update: I tried to do this exact same thing but not with my client scaled out. I shrunk my game client down to a small size and no freezing!! I don't think it's cpu related though, is it?

**Comment by Adam-** [comment] 2018-08-08 17:58
What are the dimensions of the crashing client?

**Comment by tyboyd** [comment] 2018-08-08 18:06
i have no idea of the dimensions. How would I go about getting those? They are about 1/3 of my screen as I run 2 clients. I do have a 4k monitor so idk if that would be the problem or not.

**Comment by jdpowell1** [comment] 2018-12-31 16:42
I've been getting the same issue with a 3k screen. This bug might be something to do with screen resolution.

**Comment by Alexsuperfly** [comment] 2020-02-18 03:48
this seems to be caused by having a client size taller than 1500px which causes [this script](https://github.com/RuneStar/cs2-scripts/blob/master/scripts/%5Bproc,model_dynamiczoom%5D.cs2) to hit a default case which somehow results in a divide by zero error.  @abextm was the one to identify this on discord when assisting someone else with this same problem the other day, so maybe he could provide more detailed information.

**Comment by abextm** [comment] 2020-03-02 23:51
This has been fixed in client patch versions >= 456150200.62

**Closed by abextm** 2020-03-02 23:51 UTC
Labels: bug, jagex-bug
