### ISSUE TITLE
Searching for "w(3" in the item lookup thing doesn't find anything.

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#3634] opened 2018-06-05 14:54 UTC
The search bar doesn't register "(" or ")" apparently.
If you search for "brew(", it still shows Bandit's Brew. If you search for brew(3), it still shows everything with brew in its name.
Searching for "w(3" doesn't show anything.
It doesn't seem to search like the ge search works, i.e. showing any matches with the search term instead of what it is now.
Also, the results aren't sorted alphabetically.
Screenshots:
![image](https://user-images.githubusercontent.com/34870401/40983920-f4ce3a74-68e0-11e8-8def-c2e299b84cc6.png)
![image](https://user-images.githubusercontent.com/34870401/40983962-0f954636-68e1-11e8-890c-1db8ed550215.png)
![image](https://user-images.githubusercontent.com/34870401/40983941-003d9954-68e1-11e8-8908-38f076aae110.png)

**Comment by deathbeam** [comment] 2018-06-05 15:47
Duplicate of other issue.

**Closed by deathbeam** 2018-06-05 15:47 UTC
