### ISSUE TITLE
Anti Drag not working equipment menu

### ISSUE THREAD

**Issue by joeamansfield** [runelite/runelite#17192] opened 2023-11-14 20:24 UTC
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Ubuntu 22.04

### Bug description

When you enter the worn items menu in your bank to equip gear, anti drag doesn't work. The same issue presents in the equipment stats interface out of the bank. In normal bank interface and out of bank interface it works normally.

### RuneLite version

Runelite version: 1.10.13.2
Launcher version: 2.6.9

### Logs

[client.log](https://github.com/runelite/runelite/files/13355794/client.log)
[launcher.log](https://github.com/runelite/runelite/files/13355795/launcher.log)

**Comment by Felanbird** [comment] 2023-11-14 20:26
Duplicate of #17164

**Closed** 2023-11-14 20:26 UTC
Labels: duplicate
