### ISSUE TITLE
Remaining kills on xp tracker does not take into account shared xp attack style

### ISSUE THREAD

**Issue by TimvdLippe** [runelite/runelite#11597] opened 2020-05-14 21:38 UTC
**Describe the bug**
The xp tracker for combat skills does not take into account the "shared xp" option when calculating the remaining kills for the next level/goal.

**To Reproduce**
1. Use a weapon with shared xp (E.g. whip with Lash)
2. Observe that the xp tracker reports an X amount of kills.
3. Observe that the X amount of kills is too low, since xp is shared between the various skills.

**Expected behavior**
The xp tracker should take into account I am using shared xp as a combat method and should count the remaining kills accordingly.

**Screenshots**
![image](https://user-images.githubusercontent.com/5948271/81988391-4696ae00-9633-11ea-8240-d71b484ce76b.png)

I was killing Lizardmen which have 60 hitpoints, which is around 100 strength xp or so. I would need to kill 300 of them, instead of only the 126 reported.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.15
 - Launcher version: 2.1.0

**Additional context**

**Comment by Hydrox6** [comment] 2020-05-14 21:41
Duplicate of #6479

**Closed by Hydrox6** 2020-05-14 21:41 UTC

**Comment by TimvdLippe** [comment] 2020-05-14 21:44
Apologies. I had searched for existing issues but searched for "shared xp" instead.
