### ISSUE TITLE
Custom world map icons render on top of Overview window

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#4985] opened 2018-08-18 04:14 UTC
![screenshot](https://user-images.githubusercontent.com/5851433/44295660-9dfbc480-a27b-11e8-8974-fa6fd7e11efd.png)

**Comment by Abextm** [comment] 2018-08-18 04:14
Duplicate of #3456

**Closed by Abextm** 2018-08-18 04:14 UTC
Labels: duplicate
