### ISSUE TITLE
Plugin folders

### ISSUE THREAD

**Issue by potato529** [runelite/runelite#14018] opened 2021-08-13 12:21 UTC
Add a folder icon next to the star, to be able to sort plugins and maybe be able to turn a folder on and off

![image](https://user-images.githubusercontent.com/88888476/129355816-7e6696d0-ef05-4125-b36e-04cda769e799.png)

**Comment by Hydrox6** [comment] 2021-08-13 12:30
Essentially a duplicate of #11417

**Closed by Hydrox6** 2021-08-13 12:30 UTC
