### ISSUE TITLE
Hover Bug

### ISSUE THREAD

**Issue by Nvmb** [runelite/runelite#1924] opened 2018-04-25 16:57 UTC
When using the toolbar on the side of the client as I hover over each option it creates drop downs or something and makes it impossible to use. There is a screenshot linked
![hover bug](https://user-images.githubusercontent.com/38732493/39260667-2c9fd0da-4888-11e8-9e03-015f550a37f6.PNG)

**Comment by Unmoon** [comment] 2018-04-25 16:58
Re-download your launcher from the website.

**Comment by deathbeam** [comment] 2018-04-25 16:58
Duplicate of #1449

**Closed** 2018-04-25 16:58 UTC
Labels: duplicate
