### ISSUE TITLE
Vorkath flash notifier

### ISSUE THREAD

**Issue by DreamyRS** [runelite/runelite#6407] opened 2018-11-09 08:56 UTC
As with the combat notifiers, the client would flash red when Vorkath is about to do his special attacks (Zombie spawn, acid pool and fire ball), to increase AFK time for people using Vorkath accounts as alt accounts. Currently the best way of doing this is to turn on volume to listen to the attacks, which can be inconvenient at times, so a flash notifier would definitely be ideal.

**Comment by deathbeam** [comment] 2018-11-09 09:12
Basically duplicate of #2447

**Closed by deathbeam** 2018-11-09 09:12 UTC
