### ISSUE TITLE
Toggle Anti-drag [Suggestion]

### ISSUE THREAD

**Issue by memis245** [runelite/runelite#10350] opened 2019-11-29 10:08 UTC
Runelite currently only has shift antidrag, where if you hold shift items wont drag for a certain time, a lot of people have shift drop and thats why we dont use it. It would be nice if you can toggle antidrag with a user picked keybind. For example, if i press ctrl, antidrag will be enabled. If I press it again, it will be disabled

**Comment by Hydrox6** [comment] 2019-11-29 12:33
You could have just added a comment to #10343

Duplicate of #9974

**Closed by Hydrox6** 2019-11-29 12:33 UTC
