### ISSUE TITLE
Customcursor- not scaling on 4K

### ISSUE THREAD

**Issue by tomw00** [runelite/runelite#11278] opened 2020-04-15 22:38 UTC
Custom cursor plugin does not scale with 4K monitor - cursor becomes tiny.

**To Reproduce**
Enable custom cursor plugin on high res screen

**Expected behavior**
Cursor should scale

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: latest
 - Launcher version: latest

**Comment by Nightfirecat** [comment] 2020-04-15 22:43
Duplicate of #8782

**Closed by Nightfirecat** 2020-04-15 22:43 UTC
Labels: duplicate

**Comment by tomw00** [comment] 2020-04-15 22:49
@Nightfirecat - Is anyone looking at #8782 ? Looks to be nearly a year old :-)

**Comment by Nightfirecat** [comment] 2020-04-15 22:50
Not to my knowledge.

**Comment by tomw00** [comment] 2020-04-15 22:51
Okay, thanks
