### ISSUE TITLE
Dodgy Necklace Jewellery Counter

### ISSUE THREAD

**Issue by gruntamasta** [runelite/runelite#3680] opened 2018-06-08 01:35 UTC
Pretty much sums it up in the title. It would be super useful to have a counter showing on dodgy necklaces similar to how expeditious bracelets work. Since thieving is so afk, it's especially obnoxious to keep track of when the necklace breaks, so this would be a big help!

**Comment by Abextm** [comment] 2018-06-08 07:45
Duplicate of #2931

**Closed by Abextm** 2018-06-08 07:45 UTC
