### ISSUE TITLE
Ground Markers with Text

### ISSUE THREAD

**Issue by zuleger5656** [runelite/runelite#8918] opened 2019-05-24 23:31 UTC
I'd be happy to do this myself, but I have no idea where to start, if someone was willing to guide me onto the right path that'd be great, otherwise I just want this plugin a thing.

The idea of it is exactly what it sounds like, Ground Markers with text. You can type out the message or maybe even have a numbered option. So once you click on the numbered option, the first tile you mark would be a '1' with that Marker color, then the next mark would be '2' with that Marker color, up until the user turns off the numbered option. Then the next time the numbered option is selected again, it would start again at 1. (Maybe add an option that allows it to continue from a specified number too)

**Comment by Nightfirecat** [comment] 2019-05-25 06:49
Duplicate of #8451

**Closed** 2019-05-25 14:21 UTC
Labels: duplicate
