### ISSUE TITLE
Ground Items: allow us to toggled whether or not highlighted item colors take priority over value tier colors.

### ISSUE THREAD

**Issue by ARuneLiteUser** [runelite/runelite#11198] opened 2020-04-05 00:12 UTC
RuneLite release 1.6.9 saw a change to the **Ground Items** plugin that made _highlight_ colors take priority over _value tier_ colors (low, medium, high, and insane). This change may have been made with the intention of giving the user an option to create a list of specific item names which would highlight over all other colors. However, as a secondary result, the _value tier_ feature is made irrelevant if the user chooses to set an automatic _highlight-over_ value which is lower than a _value tier_ threshold.

For example: if one's _highlight-over_ value is set to 10k, and their _insane_ value is set to 10M, a dropped item worth greater than 10M would appear with the _highlight_ color rather than the expected _insane_ color.

Allow me to describe my **Ground Items** settings in order to explain why I would request this feature:

I have a _highlight-over_ value of 10k (GE). I also have _Show Highlighted items only_ enabled, so only item names with a GE value of over 10k get shown by the plugin. This configuration allows me to keep my interface free of cheap item names, while giving me the option to hold ALT to reveal all item names, with highlighted and non-highlighted item names distinguished by color. I then have my _value tiers_ set to 100k, 1M, 2.5M, and 10M respectively. This way, I can easily tell if a particularly valuable piece of loot is dropped.

Or rather, I could, until highlighted item colors took priority over value tiers.

Thank you for reading and considering my feature request.

**Comment by Nightfirecat** [comment] 2020-04-25 08:42
Duplicate of #10961

**Closed by Nightfirecat** 2020-04-25 08:42 UTC
Labels: duplicate
