### ISSUE TITLE
OpenGL causing game crash

### ISSUE THREAD

**Issue by little-shippy** [runelite/runelite#11266] opened 2020-04-14 11:05 UTC
**Bug**
My friend recently upgraded to Java 8 Update 241 (he tried 221 too) and is having issues while launching the client. He also uninstalled RuneLite, cleared his cache and reinstalled RuneLite.

Every time he opens his client it either gets stuck with an invisible client and a loading cursor, or it loads the client window but with an invisible game window.

After finding out that it was an OpenGL issue we turned the GPU plugin on and off several times while testing the client run and on launch, all tests resulted in the same error.

He also tried disabling hardware acceleration but had no luck.

**Error**
We managed to pull these logs out of his client logs
```
2020-04-14 19:11:03 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
com.jogamp.opengl.GLException: Error swapping buffers
    at jogamp.opengl.windows.wgl.WindowsWGLDrawable.swapBuffersImpl(WindowsWGLDrawable.java:93)
    at jogamp.opengl.GLDrawableImpl.swapBuffers(GLDrawableImpl.java:88)
    at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1107)
    at br.ro(br.java:17951)
    at br.q(br.java)
    at br.run(br.java:317)
    at java.base/java.lang.Thread.run(Unknown Source)
```
 **Source**
The error seems to be coming from this line
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java#L1107

**Environment**
OS: Windows 10
RuneLite version: 1.6.10.1
Launcher version: 1.6.0
Java version: 8 Update 241 (and 221)

**Comment by Nightfirecat** [comment] 2020-04-16 16:44
Related to/duplicate of #9889

**Closed by Nightfirecat** 2020-04-16 16:44 UTC
Labels: duplicate
