### ISSUE TITLE
BUG: GPU Renderer Freezes client indefinitely if I have it on inside a POH

### ISSUE THREAD

**Issue by hellohiretrowow** [runelite/runelite#9573] opened 2019-08-04 16:54 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Runelite freezes indefinitely and I have to end the system process every time I teleport to or enter a POH with GPU renderer turned on. Or if I turn on the GPU renderer plugin whilst inside.

Doesn't happen anywhere else in the game for me. This happens 100% of the time and has always happened since the gpu feature was added I've just always kept the feature off but now hopefully someone can look into this and fix it :)

**Video**
https://imgur.com/a/JjcbPZ6

**Environment (please complete the following information):**
Windows 10 
Runelite rev 1.5.30.1

<details><summary>client.log</summary><pre><code>2019-08-04 17:36:20 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 265295622.215
2019-08-04 17:36:20 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-08-04 17:36:21 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-08-04 17:36:23 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@62aa9071,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-08-04 17:36:23 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-08-04 17:36:25 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 11164ms. Uptime: 22295ms
2019-08-04 17:37:42 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.plugins.gpu.GpuPlugin.uploadScene(GpuPlugin.java:1245)
	at net.runelite.client.plugins.gpu.GpuPlugin.onGameStateChanged(GpuPlugin.java:1240)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:136)
	at client.um(client.java:4338)
	at cv.ei(cv.java:1105)
	at gb.gi(gb.java:5372)
	at client.ad(client.java:920)
	at bz.dr(bz.java:364)
	at bz.run(bz.java:343)
	at java.lang.Thread.run(Thread.java:748)
2019-08-04 17:41:18 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 265295622.215
2019-08-04 17:41:18 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-08-04 17:41:19 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-08-04 17:41:20 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@23c3235a,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-08-04 17:41:20 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-08-04 17:41:23 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 10618ms. Uptime: 12601ms
2019-08-04 17:43:36 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 265295622.215
2019-08-04 17:43:37 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-08-04 17:43:38 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-08-04 17:43:40 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@327c1711,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-08-04 17:43:40 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-08-04 17:43:44 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 14912ms. Uptime: 17479ms
2019-08-04 17:55:10 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 265295622.215
2019-08-04 17:55:10 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-08-04 17:55:11 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-08-04 17:55:12 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@7fc2ac5f,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-08-04 17:55:13 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-08-04 17:55:15 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 10023ms. Uptime: 12131ms</code></pre></details>

**Comment by MESLewis** [comment] 2021-01-13 03:05
Does this happen on the latest release of RuneLite?

**Comment by Nightfirecat** [comment] 2022-07-10 04:06
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:06 UTC
Labels: bug, gpu
