### ISSUE TITLE
Client freezes with GPU plugin active on new nvidia drivers

### ISSUE THREAD

**Issue by Azderi** [runelite/runelite#13371] opened 2021-03-22 01:52 UTC
Client seems to freeze with GPU plugin turned on and Compute shaders. The two cases I've encountered both had a GeForce 900 series  graphics card and driver from March 15th running on Windows 10. Downgrading to driver version 459 fixed the problem in both cases.

No crash output or anything out of ordinary in log files.

**Comment by Astronought** [comment] 2021-04-04 08:42
I'm having the exact same issue.

**Comment by Astronought** [comment] 2021-04-09 23:01
Small update, this issue has seemingly now been fixed. Not sure what changed since my first reply though.

**Comment by Astronought** [comment] 2021-04-14 16:05
Issue has returned after the recent update :(

**Comment by Nightfirecat** [comment] 2021-04-14 16:05
We have still not made any updates to the GPU plugin

**Comment by Astronought** [comment] 2021-04-14 17:36
I mean the most recent OSRS update seems to have caused the issue again.

**Comment by Nightfirecat** [comment] 2022-07-10 04:08
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:08 UTC
Labels: needs-information, gpu
