### ISSUE TITLE
Elite challenge scrolls close clue overlay

### ISSUE THREAD

**Issue by Rheon-D** [runelite/runelite#2043] opened 2018-04-27 13:53 UTC
Elite clue challenges are unique (_I think_) in the sense they replace the clue scroll in the players inventory with a separate challenge scroll item, the Clue plugin is picking up on the fact there are no clue scrolls left in the players inventory.

Just including challenge scrolls into the item check in `ClueScrollPlugin::onItemContainerChanged` will still leave cases where the player will be unable to trigger the overlay, such as Logging out.

Including above, I'm thinking a fix for this would be either
- A new `ClueScroll` type to handle only the challenge scrolls for elites, displaying a new overlay with the answer and who to hand it to.
- Changing the text parameter on all/affected `ClueScroll` types to take multiple/strings to identify all related clue components, ie; One for the clue text, one for the challenge text

Thoughts?

**Comment by deathbeam** [comment] 2018-11-26 13:51
Duplicate of #2740

**Closed by deathbeam** 2018-11-26 13:51 UTC
Labels: clues
