### ISSUE TITLE
Cryptic Clue: Incorrect NPC when on screen

### ISSUE THREAD

**Issue by DanielHutt** [runelite/runelite#8878] opened 2019-05-21 00:40 UTC
I got the Easy clue scroll "Belladonna, my dear. If only I had gloves, then I could hold you at last."

This is supposed to be the Draynor manor leprechaun. If you go to the Port Sarim leprechaun the indicator points to him. If you don't have the Port Sarim tool leprechaun on screen then it points in the right direction.

**Comment by Nightfirecat** [comment] 2019-05-21 01:27
Duplicate of #3164 and #5231.

**Closed** 2019-05-21 01:27 UTC
Labels: duplicate
