### ISSUE TITLE
Add a plugin for QoL with the wiki button

### ISSUE THREAD

**Issue by Bluntveld** [runelite/runelite#11473] opened 2020-05-05 18:29 UTC
I was thinking of maybe some code that would be able to read the wiki page (since all pages are laid out identically) and it would then format the page onto the sidebar for use

possible features could be:
- drop down menus for each subject to organize the subjects, but not crowd the area
-checklists if the topic searched was a quest
- if not too OP, a simplistic overlay system to aid the user in the completion of these quests, whether it be direct guidance or general direction

**Comment by dekvall** [comment] 2020-05-05 18:31
Wouldn't it be easier to just use a browser?

**Comment by Hydrox6** [comment] 2020-05-05 18:32
Duplicate of #3038
The quest helper is a duplicate of #5042

**Closed by Hydrox6** 2020-05-05 18:32 UTC
