### ISSUE TITLE
Graphical issues with linux

### ISSUE THREAD

**Issue by AdamMe12** [runelite/runelite#11685] opened 2020-05-24 14:00 UTC
while trying to play osrs on linux. (i used pop os and kubuntu) got the same issue. 
![bug](https://user-images.githubusercontent.com/41500182/82756045-37a4be00-9de0-11ea-899f-61ad378539d1.png)

**Comment by Hydrox6** [comment] 2020-05-24 14:03
Duplicate of #11351

**Closed by Hydrox6** 2020-05-24 14:03 UTC
