### ISSUE TITLE
Side Bar Artifact (Even when Hardware Acceleration is disabled)

### ISSUE THREAD

**Issue by PixelPacker** [runelite/runelite#11727] opened 2020-05-28 12:35 UTC
When interacting with the side bar it will artifact making it unusable until relaunching the client. However disabling hardware acceleration as covered at https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration does not solve the issue.

**Steps to reproduce the behavior**
1. Open side bar.
2. Interact with the side bar by either moving the mouse around or clicking around.

**Expected Behavior**
For the side bar to function without artifacts.

**Screenshots**

![](https://cdn.discordapp.com/attachments/442492468307427330/715538106819936376/unknown.png)

![](https://cdn.discordapp.com/attachments/442492468307427330/715538200113971301/unknown.png)

![Runelite Bugs](https://user-images.githubusercontent.com/9503337/83153171-e1739b80-a0bb-11ea-8c76-03b2903b511b.gif)

**Enviroment**
 - OS: Windows 10
 - RuneLite version: 1.6.16
 - Launcher version: 2.1.3

**Additional context**
- The time is inconsistent when the bug happens and seems to take longer with hardware acceleration disabled.
- Testing for the bug with the GPU plugin both enabled and disabled does not change the results.
- Reinstalling the client and wiping the client cache and settings does not fix the issue.
- Resizing the client can fix the issue for a small amount of time.

**Temp Workaround**
This issue is caused by having programs like Riva Tuner Statistics Server open.

**Comment by Zaaraflaf** [comment] 2020-05-28 15:30
I have the exact same problem, tried the same fixes you've mentioned.

**Comment by Nightfirecat** [comment] 2020-05-28 15:50
For what it's worth, disabling hardware acceleration has historically resolved this issue for players. It is only as of about a month ago that we started seeing reports that this fix no longer worked, so it's likely that some external update (driver or Windows update perhaps) caused this.

**Comment by PixelPacker** [comment] 2020-05-28 16:43
If there is anything that I could supply to help you guys solve this let me know!

**Comment by Zaaraflaf** [comment] 2020-05-28 20:41
Are there more things that I could try to fix the problem? Cause it sure seems not everyone is having this problem.

**Comment by Nightfirecat** [comment] 2020-05-28 20:51
As of now we do not know any commonalities between people's setups who encounter this, or what differentiates them from people who do not. If we are able to cause it to happen on one of our computers, we could likely debug this further. For now, it would help for each person encountering this issue to post full environment details of their computers so we have records of that:

* Operating system and version
* RuneLite installation method (32- or 64-bit Windows installer, MacOS installer, Linux AppImage, Linux snap, or all-platform JAR)
* Launcher and client version
* GPU make/model and GPU driver version

**Comment by Zaaraflaf** [comment] 2020-05-28 21:11
> As of now we do not know any commonalities between people's setups who encounter this, or what differentiates them from people who do not. If we are able to cause it to happen on one of our computers, we could likely debug this further. For now, it would help for each person encountering this issue to post full environment details of their computers so we have records of that:
> 
> * Operating system and version
> * RuneLite installation method (32- or 64-bit Windows installer, MacOS installer, Linux AppImage, Linux snap, or all-platform JAR)
> * Launcher and client version
> * GPU make/model and GPU driver version


- Operating system and version
Windows 10 Pro version 1909 (Build 18363.836) 

- RuneLite installation method (32- or 64-bit Windows installer, MacOS installer, Linux AppImage, Linux snap, or all-platform JAR)
64-bit installation method (default settings) on SSD

- Launcher and client version
Runelite version: 1.6.17 
Launcher version: 2.1.3

- GPU make/model and GPU driver version
NVIDIA GeForce GTX 760
Driver version: 446.14


Hope this helps

**Comment by Zaaraflaf** [comment] 2020-05-28 21:25
I've managed to solve the problem for me. 
I was fooling around a bit with some settings to see if I could find anything.

When I turn off RivaTuner Statistics (I think it was turned on automatically) and I disable it. I don't get the sidebar artifacts anymore. 

I don't have enough understanding of PC's to figure out what causes the interference, but it worked for me!

**Comment by annamarie0408** [comment] 2020-05-29 00:41
My MSI GS66 does the same thing. However, I have noticed it occurs way more often when I have more than one client open on one monitor (triple monitor setup)

Operating system and version
Windows 10 Pro version 1909 (Build 18363.836)

RuneLite installation method (32- or 64-bit Windows installer, MacOS installer, Linux AppImage, Linux snap, or all-platform JAR)
64-bit installation method (default settings) on SSD

Launcher and client version
Runelite version: 1.6.17
Launcher version: 2.1.3

GPU make/model and GPU driver version
NVIDIA GeForce RTX 2070 with Max-Q Design
Driver version: 26.21.14.4223

**Comment by PixelPacker** [comment] 2020-05-29 01:32
I can confirm closing riva turner statistics server fixed the issue. Even with hardware acceleration enabled.

**Comment by fridaym** [comment] 2020-05-29 08:23
> As of now we do not know any commonalities between people's setups who encounter this, or what differentiates them from people who do not. If we are able to cause it to happen on one of our computers, we could likely debug this further. For now, it would help for each person encountering this issue to post full environment details of their computers so we have records of that:
> 
> * Operating system and version
> * RuneLite installation method (32- or 64-bit Windows installer, MacOS installer, Linux AppImage, Linux snap, or all-platform JAR)
> * Launcher and client version
> * GPU make/model and GPU driver version

Windows 10 Home 64-bit Version 1903 OS Build 18362.778
Runelite 64-bit installer
Dont know how to check Runelite launcher and client version
Nvidia GeForce GTX 1070 with Max-Q Design, Driver version 26.21.14.4614

I dont have RivaTuner statistics server so cant try that.

**Comment by osrsAnnexin** [comment] 2020-05-29 21:45
Windows 10 Home / Version 1909 / Build 18363.836
    Windows 64-Bit Installer
    Runelite Version : 1.6.17
    Runelite Installer: 2.1.3
    
    GPU : RTX 2080 Super
     Driver : 445.87

**Comment by Simpgod999** [comment] 2020-05-30 09:33
Same problem, this really needs to be fixed:......(

**Comment by VizierofChaos** [comment] 2020-05-31 05:36
Hi same issue 
Windows 10 Home Ver 10.0.18362
Windows 64-Bit Installer
Runelite Version 1.6.13
Launcher 2.1.3
Graphics NVIDIA GeForce GTX 1080
Driver 446.14 
Processor i7-7700

**Comment by Nightfirecat** [comment] 2020-06-01 06:36
As an update to earlier comments, the following programs have been reported to cause this issue:

*  rivatuner
* sonic suite
* cFosSpeed

If none of those are installed, or removing them and restarting RuneLite still does not resolve the issue, you can try running the following command (in a command prompt window):

```
%localappdata%/runelite/jre/bin/java.exe -jar %localappdata%/runelite/runelite.jar --mode=OFF
```

**Comment by Simpgod999** [comment] 2020-06-01 16:39
@Nightfirecat The %localappdata%/runelite/jre/bin/java.exe -jar %localappdata%/runelite/runelite.jar --mode=OFF command FIXED the problem for me! thanks alot <3

**Comment by annamarie0408** [comment] 2020-06-01 17:40
I will try this tonight and I will report back to see if this fixes my issue.

**Comment by lceCubed** [comment] 2020-06-01 17:47
System info for good measure
Windows 10 Home 64-bit, version 1903 (Build 18362.836)
Graphics NVIDIA GeForce GTX 1070, Driver version 446.14
Processor i5-2500K
Runelite Version 1.6.17
Launcher 2.1.3

RivaTuner seems to have been the cause for me too. Didn't have to close the program though, just turn off the on-screen display.
Hardware acceleration doesn't change this. Works with or without the "--mode=OFF" fix as long of RivaTuner's on-screen display is off.

**Comment by PixelPacker** [comment] 2020-06-01 21:31
Can confirm, disabling on "On-Screen Display Support" fixes the issue. This issue may be related to third party overlays.

**Comment by annamarie0408** [comment] 2020-06-03 13:55
> As an update to earlier comments, the following programs have been reported to cause this issue:
> 
> * rivatuner
> * sonic suite
> * cFosSpeed
> 
> If none of those are installed, or removing them and restarting RuneLite still does not resolve the issue, you can try running the following command (in a command prompt window):
> 
> ```
> %localappdata%/runelite/jre/bin/java.exe -jar %localappdata%/runelite/runelite.jar --mode=OFF
> ```

So I did this on my computer and it has seemed to be working, ran it for 2 days and did not encounter the lag issue once. Though I swear the texture looks different

**Comment by PixelPacker** [comment] 2020-06-06 23:24
I tested this issue with my new hardware (Asus Prime x570-P and Ryzen 5 3600) and the issue is still there when having the riva tuner overlay on. So I can only assume this isn't a hardware specific issue.

**Comment by jlapine** [comment] 2020-06-07 07:30
I don't have rivatuner, sonic suite, or cFosSpeed.

Just got a brand new computer and I'm seeing this and its really ruining my ability to use runelite at all.

System Info:
Alienware Aurora R10
Windows 10 Home Version 10.0.18363
Processor: AMD Ryzen 5 3500
GPU: AMD Radeon RX 5700 XT 8GB GDDR6

**Comment by haloboyvash** [comment] 2020-06-13 08:28
Same as above ^

I tried opening runelite the same way you mentioned through command prompt and it's working for now for whatever reason.

Sys info:
Windows 10 Home 64-bit
Intel Core i7-8700 
GeForce RTX 2080

**Comment by gasmar** [comment] 2020-06-27 18:29
This fixes the issue but it's a little complicated for streaming because the streaming software doesn't detect the window as a game, or at all. I have to use display capture which is kind of buggy at times and the window needs to be a certain size. If it's possible to fix this bug, it would be much help.

**Comment by PotentGemini** [comment] 2020-07-04 01:35
**********IMPORTANT DISCOVERY ********

If you have an alienware computer it is the alienware command center that is causing the issue. You can save you light colour then uninstall it and it will stay that way. Finally after 4 months I read this then said I'm uninstalling it and boom fixed!

@jlapine

**Comment by annamarie0408** [comment] 2020-07-07 13:03
> **********IMPORTANT DISCOVERY ********
> 
> If you have an alienware computer it is the alienware command center that is causing the issue. You can save you light colour then uninstall it and it will stay that way. Finally after 4 months I read this then said I'm uninstalling it and boom fixed!
> 
> @jlapine

I find this ironic since I had this issue on my MSI GS66 and GS65 so I ended up switching to an Alienware M17 R2 and the issue is completely gone away and I have the AlienWare Command Center on my PC running at full force. This error is just an odd bug in general

**Comment by PotentGemini** [comment] 2020-07-07 15:13
> > **********IMPORTANT DISCOVERY ********
> > If you have an alienware computer it is the alienware command center that is causing the issue. You can save you light colour then uninstall it and it will stay that way. Finally after 4 months I read this then said I'm uninstalling it and boom fixed!
> > @jlapine
> 
> I find this ironic since I had this issue on my MSI GS66 and GS65 so I ended up switching to an Alienware M17 R2 and the issue is completely gone away and I have the AlienWare Command Center on my PC running at full force. This error is just an odd bug in general

It’s all hardware and OS dependent. I agree it’s an odd bug. Just like some people will have other programs listed on this thread but yet it works fine. I’ve had my Alienware for about a year and disabled command centre from the beginning as I never used it. Later on down the road I formatted the PC to clear out junk and a bad driver mix. 
Downloaded runelite then started having this issue. I tried everything. Lowered my monitor from 240hz to 59. Nothing. Disabled G Sync nothing. Then I realized I didn’t have command centre on when reading this thread so I uninstalled it. BOOM gone and hasn’t come back since. It’s a very odd bug. Also another odd thing is when the menu glitched I would drag it to my secondary monitor and it would go back to normal for a moment then start again.

Personally I believe it’s with newer GPUs, Something to do with any software that tries to prioritize it, And windows focus assist. But who knows. I think if they knew what the exact problem was it would be fixed. I’m just very happy it works again, It was a nightmare dealing with it.

**Comment by jalexander93** [comment] 2020-07-09 03:42
> Hi same issue
> Windows 10 Home Ver 10.0.18362
> Windows 64-Bit Installer
> Runelite Version 1.6.13
> Launcher 2.1.3
> Graphics NVIDIA GeForce GTX 1080
> Driver 446.14
> Processor i7-7700
> 
> Hey everyone I fixed the issue, I have a program pre installed on my computer called sonic suite. I disabled it and it worked. I'd check apps that you have running and try closing something after you've disabled hardware acc. I have that enabled now and it doesn't affect the menu anymore.

was wondering if this sonic stuido 3 hes refering to or sonic radar? only two that "sonic" related programs that came with my z390-E mobo

**Comment by PotentGemini** [comment] 2020-07-09 15:04
> > Hi same issue
> > Windows 10 Home Ver 10.0.18362
> > Windows 64-Bit Installer
> > Runelite Version 1.6.13
> > Launcher 2.1.3
> > Graphics NVIDIA GeForce GTX 1080
> > Driver 446.14
> > Processor i7-7700
> > Hey everyone I fixed the issue, I have a program pre installed on my computer called sonic suite. I disabled it and it worked. I'd check apps that you have running and try closing something after you've disabled hardware acc. I have that enabled now and it doesn't affect the menu anymore.
> 
> was wondering if this sonic stuido 3 hes refering to or sonic radar? only two that "sonic" related programs that came with my z390-E mobo

It could for sure be sonic radar as it’s a overlay program. Basically what I’m finding is any overlay, Game control, game enhancing programs are what’s causing the menu glitch. Not for everyone but for some. I’m not sure if this is hardware related, Or luck of the draw. I do notice a lot of people with 2060s and above are seeing this. 

If you have this issue uninstall radar. If it goes away perfect. If it doesn’t just reinstall it from your Mobos website.

**Comment by jalexander93** [comment] 2020-07-09 16:12
> > > Hi same issue
> > > Windows 10 Home Ver 10.0.18362
> > > Windows 64-Bit Installer
> > > Runelite Version 1.6.13
> > > Launcher 2.1.3
> > > Graphics NVIDIA GeForce GTX 1080
> > > Driver 446.14
> > > Processor i7-7700
> > > Hey everyone I fixed the issue, I have a program pre installed on my computer called sonic suite. I disabled it and it worked. I'd check apps that you have running and try closing something after you've disabled hardware acc. I have that enabled now and it doesn't affect the menu anymore.
> > 
> > 
> > was wondering if this sonic stuido 3 hes refering to or sonic radar? only two that "sonic" related programs that came with my z390-E mobo
> 
> It could for sure be sonic radar as it’s a overlay program. Basically what I’m finding is any overlay, Game control, game enhancing programs are what’s causing the menu glitch. Not for everyone but for some. I’m not sure if this is hardware related, Or luck of the draw. I do notice a lot of people with 2060s and above are seeing this.
> 
> If you have this issue uninstall radar. If it goes away perfect. If it doesn’t just reinstall it from your Mobos website.

Yea thought this was the fix helped a little then happened again unfortunately. I’ll just keep them uninstalled as they were messing with my work vpn (took it as a game) as well. Not sure if it’s a 2060 issue tho I’m running a 1660 super and this still occurs. Strangely enough when I use my laptop that just has the basic intel graphics everything runs smooth hope it gets resolved soon

**Comment by lordsherman** [comment] 2020-07-10 00:05
> I don't have rivatuner, sonic suite, or cFosSpeed.
> 
> Opening runlite with:
> `%localappdata%/runelite/jre/bin/java.exe -jar %localappdata%/runelite/runelite.jar --mode=OFF`
> appears to fix it but I would really prefer not to have to open runelite from the cmd prompt forever.
> 
> System Info:
> Alienware Aurora R10
> Windows 10 Home Version 10.0.18363
> Processor: AMD Ryzen 5 3500
> GPU: AMD Radeon RX 5700 XT 8GB GDDR6

This seems to work the best for me.  Even when trying to run it in a batch script it doesn't seem to work but manually so far has been working well which really confuses me :|

**Comment by gasmar** [comment] 2020-07-10 00:19
It's weird cause if I launch the jar, it works just fine. However, if I do it that way it literally takes twice, sometimes more resources than the regular client, which still has the artefacts. This is a problem because if I'm streaming, the cpu gets super iverloaded and a lot of it comes from the batch file.

Another problem I'm running into is that the GPU plugin is freezing both versions and I have to close and reopen them, but if it's not toggled off before running it again, it simply doesn't load. This makes it impossible to have better performance.

**Comment by Adam-** [comment] 2020-07-10 00:20
> 
> 
> It's weird cause if I launch the jar, it works just fine. However, if I do it that way it literally takes twice, sometimes more resources than the regular client, which still has the artefacts. This is a problem because if I'm streaming, the cpu gets super iverloaded and a lot of it comes from the batch file.
> 
> Another problem I'm running into is that the GPU plugin is freezing both versions and I have to close and reopen them, but if it's not toggled off before running it again, it simply doesn't load. This makes it impossible to have better performance.

Unrelated to the issue, but if you pass `-Xmx512m` to the jar it will use a similar amount of memory.

**Comment by Joshposh70** [comment] 2020-07-11 10:39
This issue has been driving me insane for months. 
Based on what people have been saying in this post (regarding Overlays) I found that Logitech Options was the cause on my machine. It has a process running called 'LogiOverlay' that is used to notify of things (e.g Low Battery) 

This is still clearly a fault with RuneLite, but disabling this allowed RuneLite to at least be useable.

**Comment by gasmar** [comment] 2020-07-11 17:43
Honestly I ended up reinstalling Windows completely with no junkware. That fixed it, so apparently some of the programs that come out of the box (at least in gaming pc's) screw with it :/ it works like a dream now

**Comment by Danny9865** [comment] 2020-07-24 15:58
%localappdata%/runelite/jre/bin/java.exe -jar %localappdata%/runelite/runelite.jar --mode=OFF

guys create a shortcut
![image](https://user-images.githubusercontent.com/58650168/88410687-9b426c00-cdce-11ea-9818-47862b579264.png)

put the above statement in the box like so

![image](https://user-images.githubusercontent.com/58650168/88410764-b44b1d00-cdce-11ea-8ebb-cbc9d9fff29e.png)

name it runelite, and you have a fully working application, and if you're really bothered you can change the icon. This will also close cmd down for you so its literally just a Runelite application

**Comment by DarkRaGaming** [comment] 2020-09-17 10:22
I have tried a fresh install and all

Here is my computer specs

Processor : Intel Core i7-6820hk CPu 2.70GHz
Ram : 64GB
System Type : Window 10 64 bit
Graphic Card: Geforce 980

I am also having the same problem.

**Comment by jasepellerin** [comment] 2020-10-03 19:14
![Screenshot 2020-10-03 121056](https://user-images.githubusercontent.com/9395127/94999949-cc2ee200-0571-11eb-8aa3-3d959ef6bab5.png)

This little thing was the culprit for me. Exiting that allowed me to start with GPU plugin enabled (this was causing hanging on startup before) and fixed `--mode=OFF` not working (sidebar was still artifacting).

**Comment by PotentGemini** [comment] 2020-10-03 19:57
@jasepellerin Thats right! As I mentioned before which for some odd reason people wanted to challenge because they weren’t having the same issue. But anyways I’ll say it again.

The error seems to come from programs that have anytype of game enhancing overlay, Game finder, Game graphic setter etc etc etc.

GeForce
Alienware Commend Centre
Rivatuner
Sonic suite 

The list goes on. If you’re going to reply back stating “well that’s weird because I have that program and it doesn’t do this.” I don’t care. Straight and simple.

Myself it’s my Alienware command Centre that did it. But yet I can have my GeForce running and have no issues. 

Jase here is the opposite. He has Alienware command Centre but GeForce is causing the issue.

I can confirm mine as I went to change my light colours so had to redownload AC and the moment I did it came back. Changed my colours uninstalled it boom gone again.


Plan and very simple folks. If you have this issue look for any game enhancing, game library holding, programs wether it’s one you download or one that’s came with OEM manufacturers/MOBO’s and delete it or close it.

**Comment by jasepellerin** [comment] 2020-10-03 20:04
@PotentGemini I don't actually have Alienware Command Centre, just the GeForce program. Another weird thing is I have my in-game overlay setting turned off in GeForce experience.

![image](https://user-images.githubusercontent.com/9395127/95000803-e1f3d580-0578-11eb-9814-bd55e5935644.png)

**Comment by runeliteisbroken** [comment] 2020-10-08 05:36
This is total crap. I never thought in 2020 with all of this computing power that I'd be spending so much time getting pretty much ancient tech to cooperate. I'm having the same issue, and I've jumped through every single troubleshooting hoop. This is my last gasp for help before I throw this client in the trash.

**Comment by ttimmons** [comment] 2020-10-09 13:39
I am having the same issue, however my issue seems to only be happening when I have an external monitor plugged in.

Runelite version: 1.6.28 (Launcher: 2.1.3)
Processor: Intel i7-1750H
RAM: 32GB
OS: Windows 10
Graphics: NVIDIA GeForce RTX 2070 Super with Max-Q Design

I don't seem to have any overlay programs running on my machine when the issue is occurring.

**Comment by Skxpath** [comment] 2020-10-22 22:21
I was able to fix artifacting by maximizing the window then returning it to the regular size. I don't play on full screen though (1000x705).

**Comment by skadooba** [comment] 2020-10-31 20:38
I encountered this issue, and did a bit of testing that may be helpful to some.  I have three monitors @1440p, two 60hz and one 144hz.  For convenience, I will refer to these as monitors 1, 2, and 3:

Monitor 1: HP Pavilion 1440p 60hz
Monitor 2: Acer Predator 1440p 144hz
Monitor 3: HP Pavilion 1440p 60hz

Monitors 1 and 2 are connected to my GPU, monitor 1 via an HDMI 2 cable, Monitor 2 via Displayport.  Monitor 3 is connected directly to my motherboard via an HDMI 2 cable.  See below for PC hardware/software specs.

I installed via the Windows x64 installer, and launched via the automatically added desktop shortcut.  I was able to consistently reproduce the issue after launching and clicking on an item in the add-ons menu.  Notably, however, this issue was only able to be reproduced on monitors 1 and 2, not 3 - i.e. the monitors that use the GPU as a graphics adapter.  I was not able to reproduce the issue on monitor 3, unless I triggered the effect on a different monitor then moved the screen over to monitor 3, in which case the issue would persist, only solvable by restarting the program.  I then tested each monitor in direct connection with the motherboard, and saw the same results: that when connected to the GPU, the issue was replicable; when connected to the motherboard, it was not.

Other solutions attempted with no results:
Exit RamCache III
Exit Nvidia Overlay
Disable GSync
Reduce monitor refresh rate
Disable Hardware Acceleration

Hope this info helps someone out

Specs:
Motherboard: ASUS ROG STRIX Z390-E BIOS 2401
CPU: Intel 17-9700K
GPU: EVGA GTX 1080 SC Driver 456.71
RAM: 2x Corsair Vengeance LPX DDR4 8GB
HD: WD_BLACK SN750 NVMe 1TB
PSU: EVGA SN 850 G2

**Comment by DustinBrash** [comment] 2021-04-12 00:59
OS: Windows 10 version 10.0.19042 build 19042
RuneLite installation method: 64-bit
Launcher: 2.1.0
Runelite version: 1.7.4
GPU make/model: Nvidia GeForce RTX 2060
GPU driver version: 27.21.14.6589

I'm also having this issue, and have been able to reproduce it 100% of the time by hovering over anything in the sidebar that would bring up a tooltip. Once the tooltip appears, the graphical issues begin. None of the problem-causing programs are running. Video of issue attached.


https://user-images.githubusercontent.com/5695534/114327797-834f7b80-9b08-11eb-9a9b-1664fc18bb60.mp4

**Comment by vatsake** [comment] 2021-05-19 16:04
Any update on the fix? Hardware acceleration off decreases fps so it's unplayable...
![image](https://user-images.githubusercontent.com/36108180/118846025-f8b32680-b8d4-11eb-9b70-27a48ec7ad3e.png)

**Comment by dan-drews** [comment] 2021-06-09 23:56
The workaround of the  command `%localappdata%/runelite/jre/bin/java.exe -jar %localappdata%/runelite/runelite.jar --mode=OFF` works perfectly for me. 

However, I'm digging into some other items and debugging the code directly, and I cannot figure out what the equivalent of this is as a flag for the debugger.

I have tried using `--mode=OFF` and `mode=OFF` but neither of those work. Has anybody had luck debugging runelite while also using this flag?

**Comment by SlaQr** [comment] 2021-08-07 22:02
Some of the other comments tipped me off to look at Nvidia Shadowplay. Looks like it only affects the sidebar if instant replay is enabled. Turned it off and the problem has stopped!

**Comment by Dedx1337** [comment] 2021-08-17 19:29
Deleted AMD Chipset Driver and Realtek Audio Driver and it fixed it.

**Comment by Dedx1337** [comment] 2021-08-17 19:54
Realtek Audio Driver

**Comment by FreeShirt** [comment] 2021-08-23 07:36
Same problem here. I have a system that has Radeon Software (which wasn't the problem) and Alienware Command Center (I cannot uninstall this if I value having a backlit keyboard, and I do). I am hoping this program can be fixed as I just downloaded Runelite.

- Operating system and version
 Windows 10 64-bit Version	10.0.19042 Build 19042
- RuneLite installation method (32- or 64-bit Windows installer, MacOS installer, Linux AppImage, Linux snap, or all-platform JAR)
32 and 64 bit do not work
- Launcher and client version
RL: 1.7.20.1 Launcher: 2.1.7
- GPU make/model and GPU driver version
AMD Radeon 5600M 27.20.22023.1004

**Comment by startjim** [comment] 2021-09-09 21:41
just gone leave it here tooltips

so wen you hover over menu and let a tooltip come up 
BAM its broken

if you go ever the menus and click on them and move the mouse of it quick so tooltips dont pop-up does no happen this does not happen doing some testing disable HA (-mode=off)

this does not fix shit
disabled every programs that creats overlays nothing still same problem

so is there away to disable tooltips?

**Comment by Unholypanda** [comment] 2021-09-09 22:11
Thought I would add my experiences with the same issue.

Windows 10, GTX 3080, GSync & ShadowPlay enabled.

The two big issues I would have were 1.) The sidebar artifacting, and 2.) When I had the GPU plugin installed the client rendering will break when the GPU plugin kicks in. 

I was never able to fix #2 and its pretty easy to just ignore and work around, but #1 I fixed by setting the J2D_D3D enviroment variables to false. None of the shortcut stuff ever worked reliably for me but this solved the problem completly.

![image](https://user-images.githubusercontent.com/13141332/132769276-499315ca-ec11-4917-a931-497668a51857.png)

**Comment by ChildishForces** [comment] 2021-09-13 19:39
> Thought I would add my experiences with the same issue.
> 
> Windows 10, GTX 3080, GSync & ShadowPlay enabled.
> 
> The two big issues I would have were 1.) The sidebar artifacting, and 2.) When I had the GPU plugin installed the client rendering will break when the GPU plugin kicks in.
> 
> I was never able to fix issue 2 and its pretty easy to just ignore and work around, but issue 1 I fixed by setting the J2D_D3D enviroment variables to false. None of the shortcut stuff ever worked reliably for me but this solved the problem completly.
> 
> ![image](https://user-images.githubusercontent.com/13141332/132769276-499315ca-ec11-4917-a931-497668a51857.png)

This solves a lot of my issues Win 10, 3080 RTX

**Comment by JacobDrivers** [comment] 2021-10-17 18:18
> Deleted AMD Chipset Driver and Realtek Audio Driver and it fixed it.

I can say that after I installed Asus's latest Realtek drivers for my system/motherboard, I started to have this issue. Googling led me here. Strangely too it seems to just happen on my main/middle 1st monitor (I have 3 screens). No idea how audio drivers would cause this, and I wish there was a fix, because Asus's audio drivers include more enhancements to audio, etc. and I really don't want to have to uninstall.

**Comment by Unmoon** [comment] 2021-10-17 18:19
> 
> 
> > Deleted AMD Chipset Driver and Realtek Audio Driver and it fixed it.
> 
> I can say that after I installed Asus's latest Realtek drivers for my system/motherboard, I started to have this issue. Googling led me here. Strangely too it seems to just happen on my main/middle 1st monitor (I have 3 screens). No idea how audio drivers would cause this, and I wish there was a fix, because Asus's audio drivers include more enhancements to audio, etc. and I really don't want to have to uninstall.

Realtek drivers include Nahimic which breaks the sidebar.

**Comment by JacobDrivers** [comment] 2021-10-17 18:21
> Realtek drivers include Nahimic which breaks the sidebar.

It's actually fixed when disabling 117 HD, sadly... I don't see how Nahimic would cause graphical issues as it seems to be an audio API for sound enhancements/proccesing improvement.

**Comment by Unmoon** [comment] 2021-10-17 18:22
> 
> 
> > Realtek drivers include Nahimic which breaks the sidebar.
> 
> It's actually fixed when disabling 117 HD, sadly... I don't see how Nahimic would cause graphical issues as it seems to be an audio API for sound enhancements/proccesing improvement.

We don't know why either, but it does.

**Comment by JacobDrivers** [comment] 2021-10-17 18:24
> We don't know why either, but it does.

Thank you for the heads-up. Also disabling 117's plugin just fixes it temporarily it seems. Also strange it seems to be fine on my other monitors. Very strange bug indeed.

**Comment by Adam-** [comment] 2022-03-07 02:00
We made a launcher 2.4.0 release which prevents several specific programs from hooking into it and breaking it (mostly rivatuner and Nahimic). So we think that this effectively fixes this issue. If you can still reproduce this issue after updating to 2.4.0, open an issue with a native library dump obtained from the debug plugin and we can look at adding additional dlls to the blacklist.

**Closed by Adam-** 2022-03-07 02:00 UTC
Labels: bug, needs-information, not-our-bug, platform:windows

**Comment by samfrjn11** [comment] 2022-03-16 15:19
@Adam- I wasn't using the 2.4.0 launcher yet, but for me it was the Sonic suite. As soon as I uninstalled it, side bar glitch was gone. So if not already, definitely worth adding it to the list.

**Comment by Whayme** [comment] 2022-09-14 19:07
Unsure of if this is a related problem, but I'm getting different artifacts on Linux:

![image](https://user-images.githubusercontent.com/63085504/190241341-4db7dbf6-543f-4864-b0ad-57a0ee14db8d.png)
