### ISSUE TITLE
Make a "Cost Tracker" similar to loot tracker but instead track items used

### ISSUE THREAD

**Issue by luisferrassini** [runelite/runelite#6531] opened 2018-11-17 07:56 UTC
**Is your feature request related to a problem? Please describe.**
Couldn't find anything related.

**Describe the solution you'd like**
Make a "Cost Tracker" similar to loot tracker but instead track items used (it could be inside the loot tracker tab). Example: If you use a teleport tab, add that to Cost Tracker together with the GE updated prices, if you use a brew, add that to the cost list too and so on. It would make a lot easier to track your total costs when doing anything in the game.

**Describe alternatives you've considered**
A alternative is to track costs by yourself, which is a pain and fairly unnaccurate.

**Additional context**
This is my first suggestion, I would love to have this in the client. I already love RuneLite, keep up the good work guys!

**Comment by Popedigoz** [comment] 2018-11-17 11:07
Support.

**Comment by Kyle-Newton** [comment] 2018-11-19 19:47
There was actually an amazing one done by DWhite72, but for some reason he removed it and we haven't heard from him.

https://github.com/runelite/runelite/pull/4906#issuecomment-413294389

**Comment by raiyni** [comment] 2020-05-04 16:03
Duplicate of #6429

**Closed by raiyni** 2020-05-04 16:03 UTC
Labels: feature-request
