### ISSUE TITLE
Client ping/notification when farming patch is complete

### ISSUE THREAD

**Issue by nkacena** [runelite/runelite#3807] opened 2018-06-14 23:03 UTC
**Describe the solution you'd like**
Either when you are playing, or the next time that you login, if you have a completed farming patch, have the client notify/ping you similar to the "you're idle" notification.

**Comment by deathbeam** [comment] 2018-06-15 06:38
Duplicate of #2212

**Closed by deathbeam** 2018-06-15 06:38 UTC
