### ISSUE TITLE
Add plugin categories

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#3085] opened 2018-05-21 20:46 UTC
![image](https://user-images.githubusercontent.com/37475765/40328667-1423aee8-5d3f-11e8-88d6-ed1db8e467a6.png)
plugin should be a bit more organised as in different categories to find the plugins that we are trying to find, this will help us if we forget what the plugin is called all we need to do is look at the category and find the plugin.  

are you able to make it so it is categorised as in: 

skilling = if we click the skilling category it will take us to the next page and will show us all the skilling plugins, in that category.

pvm = all pvm plugins
pk = pk plugins
client = all client plugins?
                                        etc etc

i'm trying to say is to make plugins a bit more easier to find/organised even if we don't remember the name what the plugin is called etc not everyone uses discord, so it will be a big help for them as well :)
if you got any question that you didn't understand let me know.

**Comment by Infinitay** [comment] 2018-05-21 21:38
As for your back arrow request, there is a back button already available.

Also, we were focusing on updating the client UI redesign for this weeks update. That and I think someone who posted their PR for config categories closed it, but someone was working on it before

**Comment by jplsek** [comment] 2018-05-28 20:13
Duplicate of #2411

**Closed** 2018-05-28 20:14 UTC
Labels: feature-request
