### ISSUE TITLE
Cryptic clue "The effects of this fire are magnified." doesnt work

### ISSUE THREAD

**Issue by crypticher** [runelite/runelite#7829] opened 2019-02-12 13:40 UTC
**Describe the bug**
The cryptic hard clue scroll "The effects of this fire are magnified." does not trigger the clue solver

**To Reproduce**
1. Get a hard clue scroll
2. if it says "The effects of this fire are magnified."
3. See error

**Expected behavior**
The clue scroll solver should display the panel at top right and explain the clue scroll

**Environment (please complete the following information):**
 - OS: Windoes 10
 - RuneLite version: 1.5.11
 - Launcher version: 1.5.2

**Additional context**
Cryptic clue wiki link: https://oldschool.runescape.wiki/w/Treasure_Trails/Guide/Cryptic_clues#/media/File:Cryptic_clue_-_dig_Kebos_Swamp.png

**Comment by Hydrox6** [comment] 2019-02-12 13:41
Duplicate of #7275

**Closed** 2019-02-12 13:46 UTC
Labels: duplicate
