### ISSUE TITLE
Loot Tracker QOL

### ISSUE THREAD

**Issue by SandroVA** [runelite/runelite#13950] opened 2021-07-26 00:22 UTC
**Is your feature request related to a problem? Please describe.**
The loot tracker is currently unrealistic to use as a profit calculator because some monsters drop a lot of items that you wouldn't pick up.

**Describe the solution you'd like**
- I'd like to see the individual items price on hover inside of the loot tracker (currently it only shows the value of the entire stack). 
- I would also like the ability to hide loot under a certain value.

**Comment by Hydrox6** [comment] 2021-07-26 08:01
Please don't make one issue with three completely different unrelated requests.


* Duplicate of #10245 ([comment](https://github.com/runelite/runelite/issues/10245#issuecomment-553140200))

* I have an older branch for the second thing that I'll likely PR soon

* The third thing has been mentioned before, but doesn't have its own issue. Just from the description there it's not very actionable though. Please make a new issue *just* for that, following the full feature request template.

**Closed by Hydrox6** 2021-07-26 08:01 UTC
