### ISSUE TITLE
Oziach hard clue puzzle solver isn't working 

### ISSUE THREAD

**Issue by runeliteisgreat** [runelite/runelite#4901] opened 2018-08-14 18:07 UTC
I am using windows 8 64 bit. I have puzzle solvers enabled in the client, but neither the remaining moves nor the arrows appear in the puzzle.

**Comment by Kamielvf** [comment] 2018-08-14 18:08
The current release has an issue with the arrows, you can enable the dots from inside the plugin's settings and they should work.

**Comment by Nightfirecat** [comment] 2018-08-14 18:12
Duplicate of #4797; a fix has already been added and will be live on Thursday. Like Kamiel said, you can use the dots setting in the plugin until then to make it work.

**Comment by runeliteisgreat** [comment] 2018-08-14 18:13
Thanks guys

**Closed** 2018-08-14 18:14 UTC
