### ISSUE TITLE
Add a dark custom UX theme

### ISSUE THREAD

**Issue by Saer-Dev** [runelite/runelite#1893] opened 2018-04-24 20:24 UTC
It would be really nice if we could have a dark theme for the custom UX, or even better an RGB slider for changing the UX element colours.

The Win98-style light grey contrasts poorly with modern OS' UX design.

**Comment by Juzzed** [comment] 2018-04-24 20:28
Will be done with #1419

**Comment by Saer-Dev** [comment] 2018-04-24 21:15
Looks good, excited to see it implemented! 😄

**Comment by deathbeam** [comment] 2018-04-25 10:29
Duplicate of #1342

**Closed by deathbeam** 2018-04-25 10:29 UTC
