### ISSUE TITLE
Ground Items Color with more Customisation 

### ISSUE THREAD

**Issue by Jonotaku** [runelite/runelite#14347] opened 2021-11-07 01:11 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
-I'm annoyed that I can only have one custom item list on one colour. I want to manually set per color or add more colors for differently named items that i pick and choose.

**Describe the solution you'd like**
A clear and concise description of what you want to happen:

- I would like the option to have an Item list for EACH colour/OR a 'add more (+)' option to add seperate colors/god rays for items that pop up on ground

**Additional context**
Its just kind of annoying that theres only one highlighted item list.
And that the other colors are based on value. I want more options

**Comment by Hydrox6** [comment] 2021-11-07 01:23
Duplicate of #12274

**Closed by Hydrox6** 2021-11-07 01:23 UTC
