### ISSUE TITLE
[Menu Entry Swapper] Add a shift click option for House Portals

### ISSUE THREAD

**Issue by Ryu2kGit** [runelite/runelite#14858] opened 2022-04-13 16:02 UTC
Being able to configure a secondary option like build mode or friends house as shift click option for house portals would come in super handy!

Cheers

**Comment by Nightfirecat** [comment] 2022-04-13 16:04
Duplicate of #14813

**Closed by Nightfirecat** 2022-04-13 16:04 UTC
Labels: duplicate

**Comment by Ryu2kGit** [comment] 2022-04-13 17:25
Hi there, not sure if this still counts as duplicate or not, but i was referring to a shift click object swap on house portals, opposed to a UI swap for the house teleport spell as the other thread suggested.
