### ISSUE TITLE
Items not showing lootbeam when spawning.

### ISSUE THREAD

**Issue by Sir2Medis** [runelite/runelite#16353] opened 2023-03-06 13:08 UTC
I have Seaweed spores in my highlight list so I notice where they are when they spawn, at one point in the near past it stopped showing the lootbeam when they spawn in. Only When they spawn, if i drop them the lootbeam is still present.

When I drop them:
![Seaweed Spore Drop](https://user-images.githubusercontent.com/42140556/223118841-d4cbf4eb-f4ac-4904-a6b9-9f27a9f82c90.jpg)

When they spawn in:
![Seaweed Spore Spawn](https://user-images.githubusercontent.com/42140556/223118846-bbe28624-f1f2-42bf-91bd-8878d9d0114d.jpg)

**Comment by Nightfirecat** [comment] 2023-03-07 06:11
Duplicate of #11601

**Closed by Nightfirecat** 2023-03-07 06:11 UTC
Labels: duplicate
