### ISSUE TITLE
NPC Indicator's Tag Is Not Appearing on Some NPCs

### ISSUE THREAD

**Issue by Infinitay** [runelite/runelite#4206] opened 2018-07-07 03:30 UTC
NPC Indicator's Tag option doesn't appear on some NPCs like [Torfinn](http://oldschoolrunescape.wikia.com/wiki/Torfinn), Bandits and Villagers in [Pollnivneach](http://oldschoolrunescape.wikia.com/wiki/Pollnivneach). I think it's because there's too many menu options, because that the only correlation I see.

<details>
 <summary>stack trace</summary>
 
 ```
  2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Menaphite Thug (3550)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6138) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=0
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Villager (3557)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6140) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=0
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Ali the Camel (3543)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: Ali the Camel (3543) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=0
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Ali the Camel (3543)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: Ali the Camel (3543) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i].equals(npcOption) - i=0, Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Menaphite Thug (3550)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6138) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i].equals(npcOption) - i=0, Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Monkey (23)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: Monkey (23) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=1
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Menaphite Thug (3550)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6138) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i].equals(npcOption) - i=0, Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Rug Merchant (19)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: Rug Merchant (19) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=1
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Menaphite Thug (3550)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6138) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i].equals(npcOption) - i=0, Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Villager (3554)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6139) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=0
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Menaphite Thug (3550)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6138) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i].equals(npcOption) - i=0, Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Menaphite Thug (3550)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6138) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i].equals(npcOption) - i=0, Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Menaphite Thug (3550)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6138) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i].equals(npcOption) - i=0, Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Snake (3545)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: Snake (3545) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=0
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Ali the Snake Charmer (3542)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: Ali the Snake Charmer (3542) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=1
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Street urchin (3539)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: Street urchin (3539) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=1
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Villager (3560)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6141) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=0
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Villager (3557)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6140) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i].equals(npcOption) - i=0, Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Drunken Ali (3534)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: Drunken Ali (3534) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=1
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Ali The barman (3535)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: Ali The barman (3535) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=1
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Aristarchus (3569)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: Aristarchus (3569) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=1
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Menaphite Thug (3550)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6138) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i].equals(npcOption) - i=0, Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Villager (3554)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6139) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i].equals(npcOption) - i=0, Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Menaphite Thug (3550)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: null (6138) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i].equals(npcOption) - i=0, Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - Crocodile (4184)
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - AddNPCOption: Crocodile (4184) - Tag
2018-07-06 22:31:48 [AWT-EventQueue-0] DEBUG n.runelite.client.menus.MenuManager - actions[i] == null && unused == -1 - i=0

 ```
</details>

[Shows for the Rug Merchant](https://i.imgur.com/RoJzK6a.png)
[Doesn't show for Menaphite Thug](https://i.imgur.com/QFysJLw.png)

[First portion is the method I added the debug statements to try and figure out what was going on. The second portion is the output. This hastebin is also provided within the stacktrace above.](https://hastebin.com/exocoyasos.java)

**Comment by Alexsuperfly** [comment] 2018-07-07 03:32
its because the actions list for some npcs are already full so we cant place a tag option onto them, this is already known

**Comment by Infinitay** [comment] 2018-07-07 03:34
Oh I wasn't aware that was known and even possible. A **suggestion** I have is to (add an option to) change `Examine` to `Tag` in cases like such.

 Thoughts?

**Comment by Nightfirecat** [comment] 2018-07-07 05:18
Mostly a duplicate of #3844

**Closed** 2019-01-26 17:10 UTC
Labels: bug
