### ISSUE TITLE
Add multiple tabs to notes

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#6008] opened 2018-10-14 09:03 UTC
Not sure about everyone else but I've noticed my notes tends to get a tad long and be annoying to scroll through

Would be really nice and good for helping organization if you could have multiple note tabs (like bank tabs) to help keep stuff cleaner. 

Like for example you could have a list of skilling goals in one, gear goals in another and bossing methods in another. 

Dunno how many you can add w/o making it to cluttered but I would guess maybe 3-5? Perhaps being able to color code them (just the tabs themselves aka these: https://i.imgur.com/XQ0i6pj.png not the whole tab) to be able to easily see the difference between them but thats just nit picking at stuff.

Cheers

**Comment by deathbeam** [comment] 2018-10-14 09:12
Duplicate of #5822

**Closed by deathbeam** 2018-10-14 09:12 UTC
