### ISSUE TITLE
Menu Entry Swapper Fragments

### ISSUE THREAD

**Issue by DavitoJohnson** [runelite/runelite#14654] opened 2022-01-30 19:09 UTC
**Is your feature request related to a problem? Please describe.**
It's ungodly annoying to unequip and equip fragments when changing activities.

**Describe the solution you'd like**
Menu entry swapper integration allowing for customizable left click or shift left click to unequip (from top row) or equip (bottom left side of UI) in one click instead of right clicking 14 times per swap.

**Describe alternatives you've considered**
Dragging is unreliable due to tick timings.

**Additional context**
SS attached for reference. 
![image](https://user-images.githubusercontent.com/98709623/151713793-046d23ef-b8ce-4d98-b853-74adecd632d3.png)

**Comment by Hydrox6** [comment] 2022-04-04 21:44
Basically a duplicate of #14625

**Closed by Hydrox6** 2022-04-04 21:44 UTC
