### ISSUE TITLE
DPS Tracker at Theatre of Blood [Suggestion]

### ISSUE THREAD

**Issue by ElevatedLife** [runelite/runelite#8640] opened 2019-04-25 17:11 UTC
Tracks how much DPS you and your teammates have done during the theatre of blood raid. dps directly correlates to MVP so it is information some people may like to see. Myself included.

**Comment by Kamielvf** [comment] 2019-04-25 17:13
Duplicate of #3894

**Closed by Kamielvf** 2019-04-25 17:13 UTC
