### ISSUE TITLE
Different Target color for superior slayer monsters

### ISSUE THREAD

**Issue by CrossBowKill** [runelite/runelite#4756] opened 2018-08-07 11:21 UTC
Would be a nice addition to the slayer plugin especially for abyssal demons where its sometimes difficult to spot the superior in the slayer tower.

**Comment by forsco** [comment] 2018-08-07 11:30
I personally don't use notifications so I can also understand why it would be useful if utilizing the slayer plugin overlays on NPC's.

**Comment by Gamer1120** [comment] 2018-09-20 08:59
This is 100% necessary IMO. I just nearly lost my Hardcore status (12 hp before I panic ectophiald) due to not being able to distinguish a Greater Abyssal Demon from a regular one and not putting Protect from Melee up. For now, I'll manually highlight all superiors with NPC Indicators, but I think this should be added as a default.

**Comment by Nightfirecat** [comment] 2018-09-21 21:55
Duplicate of #1960

**Closed** 2018-09-21 22:07 UTC
Labels: feature-request
