### ISSUE TITLE
History tab for GE tab

### ISSUE THREAD

**Issue by TheeWiki** [runelite/runelite#1767] opened 2018-04-21 16:29 UTC
Would be nice to see a extended history that collects GE History data into a tab for the GE widget sidebar thing.
https://i.imgur.com/3majf7u.png

**Comment by Kambren** [comment] 2018-06-07 02:35
Do you mean extend past the 20 slots that are given in the GE?

**Comment by Abextm** [comment] 2018-08-20 04:08
I'm closing this as a duplicate of #1767 because that one has some discussion

**Closed by Abextm** 2018-08-20 04:08 UTC
Labels: feature-request
