### ISSUE TITLE
Add Bracelets of Slaughter and Expeditious charges to Info Boxes

### ISSUE THREAD

**Issue by thebubbsy** [runelite/runelite#11150] opened 2020-03-31 03:30 UTC
Same as how teleport charges can be shown in an info box via the "item charges' plugin, it would be very useful to be able to see the current amount of charges these bracelets have when worn.

**Comment by Hydrox6** [comment] 2020-03-31 08:26
Duplicate of #2407

**Closed by Hydrox6** 2020-03-31 08:26 UTC
Labels: feature-request
