### ISSUE TITLE
Interface Styles jitters with 2010 and 2005

### ISSUE THREAD

**Issue by MattRKing** [runelite/runelite#10947] opened 2020-03-04 10:32 UTC
The always stack option and the location of each tile's symbol has been fixed in the past 2 weeks, however they're still a minor issue.

With both the 2005 and 2010 styles a few of the tiles shake/jitter whenever a tile is clicked.  I have noticed that with the 2005 style it is only the quest, equipment and inventory tiles.  With the 2010 style it is the entire top row of tiles that jitters when clicked.

I tested with the 2010 style to see if it still did it with the always stack option off, and found that the former top tiles still do it.  I did not test this with the 2005 style as I assume the outcome would still be the same.

**Comment by Hydrox6** [comment] 2020-03-04 13:16
Duplicate of #10861

**Closed by Hydrox6** 2020-03-04 13:16 UTC
