### ISSUE TITLE
roofs have dissapeared during agility course how do i get them back

### ISSUE THREAD

**Issue by berks041** [runelite/runelite#1940] opened 2018-04-25 21:53 UTC

**Comment by Gamer1120** [comment] 2018-04-25 21:53
A screenshot would be incredibly helpful.

**Comment by Kamielvf** [comment] 2018-04-25 21:54
This is caused by the low detail plugin, try disabling it.

**Comment by deathbeam** [comment] 2018-04-25 21:54
Duplicate of #1481

**Closed by deathbeam** 2018-04-25 21:54 UTC
Labels: duplicate
