### ISSUE TITLE
Can't search for Extended antifire(4)

### ISSUE THREAD

**Issue by Jaso66** [runelite/runelite#2998] opened 2018-05-20 02:46 UTC
If you alt click Extended antifire(4) it will show a bunch of different antifire results other than the extended antifire(4).

**Comment by Hydrox6** [comment] 2018-05-20 02:50
This is down to how the Official GE Tracker handles words. It will search for the full words (Extended and Antifire) but not words that contain those words, and so it doesn't find Extended antifire(4).

I hope that made sense, it's a little confusing

**Comment by Jaso66** [comment] 2018-05-20 02:59
If it is enclosed in quotes like "Extended antifire(4)" it does return it correctly. Maybe instead this can be a feature request to add a check box to the GE plugin to auto encapsulate it in quotes when alt clicking.

**Comment by deathbeam** [comment] 2018-05-20 08:27
Duplicate of #1338

**Closed by deathbeam** 2018-05-20 08:27 UTC
