### ISSUE TITLE
Clan color text

### ISSUE THREAD

**Issue by Whishkey** [runelite/runelite#2937] opened 2018-05-19 11:26 UTC
Hello I was just wondering as to why the plugin for coloring the text of the clan chat wouldn't even work? Can you fix this problem please? Thanks

**Comment by Whishkey** [comment] 2018-05-19 11:30
![capture](https://user-images.githubusercontent.com/39434416/40268145-b9d45424-5b68-11e8-8d5a-abe82c6dc3c8.PNG)

Picture proof

**Comment by Hydrox6** [comment] 2018-05-19 11:31
The colouring options there are for the chat commands, they are not for actual chat recolouring

**Comment by Whishkey** [comment] 2018-05-19 11:32
@Hydrox6 
Do you think it's possible to add this feature?

**Comment by Hydrox6** [comment] 2018-05-19 11:33
I have a working version (#2473 and subsequently #2608), but there are issues with the configuration that means it won't get merged for a while.

**Comment by deathbeam** [comment] 2018-05-19 11:36
Duplicate of #2224

**Closed by deathbeam** 2018-05-19 11:36 UTC
