### ISSUE TITLE
Skilling section in loot tracker

### ISSUE THREAD

**Issue by Elenafalk** [runelite/runelite#9839] opened 2019-09-09 13:53 UTC
The PvM loot tracker is great. While skilling, it would be very helpful to show a similar tracker for loot aquired from certain types of ores, trees etc.

_Example:_
Crystals:
86x Amethyst
5x Uncut Sapphire
1x Uncut Emerald

Rocks:
27x Coal

**Comment by Hydrox6** [comment] 2019-09-09 13:58
Duplicate of #4126

**Closed by Hydrox6** 2019-09-09 13:58 UTC
