### ISSUE TITLE
Camera Lock Option?

### ISSUE THREAD

**Issue by JoeBandy** [runelite/runelite#9618] opened 2019-08-08 17:52 UTC
Is it possible to add an option under the Camera Zoom to lock the camera position so only you can adjust the angle?

For example, when you traverse over hills and certain terrain the game will auto adjust the camera angle, which is rather annoying. Can it be made to where the camera will not change unless you move it yourself?

**Comment by Alexsuperfly** [comment] 2019-08-08 18:33
duplicate of #5308

**Closed** 2019-08-08 18:36 UTC
