### ISSUE TITLE
GPU plugin crash [linux 5.4] [mesa 19.3.3] [navi10] [LLVM 9.0.1]

### ISSUE THREAD

**Issue by aviau** [runelite/runelite#10706] opened 2020-01-31 23:52 UTC
As soon as I turn on the GPU plugin, it crashes the client

**Environment**

- Ubuntu 20.04
- Linux 5.4.0
- RuneLite version 1.6.5
- Launcher version 2.1.0
- Mesa 19.3.3
- AMD RX 5700 XT

```
$ glxinfo  | grep Device
    Device: AMD NAVI10 (DRM 3.35.0, 5.4.0-13-generic, LLVM 9.0.1) (0x731f)
```

```
$ glxinfo | grep "OpenGL version"
OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.3.3
```

```
$ java -version
openjdk version "14-ea" 2020-03-17
OpenJDK Runtime Environment (build 14-ea+32-Ubuntu-1)
OpenJDK 64-Bit Server VM (build 14-ea+32-Ubuntu-1, mixed mode, sharing)
```

**Additional context**

This only happens when launching with the jar (using ``java -jar RuneLite.jar``). The appimage does not reproduce this issue.

I couldn't find logs that seemed relevant. But I am attaching client and launcher logs.

[client.log](https://github.com/runelite/runelite/files/4141894/client.log)
[launcher.log](https://github.com/runelite/runelite/files/4141896/launcher.log)
[glxinfo.log](https://github.com/runelite/runelite/files/4141904/glxinfo.log)

Are there steps that I can do to help with providing better logs? Also let me know if this should be closed or merged with another bug.

**Comment by MESLewis** [comment] 2021-01-13 02:29
With the 5700xt uses have seen disabling hardware acceleration fix the crashing on windows, hopefully the fix will apply to Linux as well. https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Nightfirecat** [comment] 2022-07-10 04:40
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:40 UTC
Labels: jvm-bug
