### ISSUE TITLE
Sidebar 

### ISSUE THREAD

**Issue by lucastimothy** [runelite/runelite#9686] opened 2019-08-17 19:30 UTC
Possible to have the client remember if you had the sidebar closed when last opened? Currently, when booting up the client, the sidebar is open/visible by default. Could it be done that if you have the sidebar open when you close the client, it will be open the next time it is booted up, and the same if you had it closed?

It's a little thing but closing the sidebar upon launching everytime is somewhat annoying as I never play with it visible, would be nice to remember the preferences of the user.

**Comment by Gamer1120** [comment] 2019-08-17 19:37
Duplicate of #2312

**Closed** 2019-08-18 11:22 UTC
