### ISSUE TITLE
Minnows Timer

### ISSUE THREAD

**Issue by Padregrassi3** [runelite/runelite#4210] opened 2018-07-07 13:00 UTC
Would it be possible to display a timer on screen showing how much time is left until the minnows stop starts moving? 
According to the wiki minnows move every 15 seconds so i think this would help people that afk minnows

Thanks

**Comment by deathbeam** [comment] 2018-07-07 16:53
Duplicate of #2734

**Closed by deathbeam** 2018-07-07 16:53 UTC
