### ISSUE TITLE
Aerial fishing spot icons/tiles sticking 

### ISSUE THREAD

**Issue by stellarlick** [runelite/runelite#11998] opened 2020-06-27 03:59 UTC
I log on to aerial fish, tiles start appearing and dissappearing, every so often a tile marking will stay after the spot has moved. it doesn't go away until i relog, so the tiles keep sticking until the water is covered with them.

1. log on 
2. Aerial fish
3. Aerial fish more
4. Aerial fish while squinting 

**Screenshots**

**Environment 

 - OS: macOS
 - RuneLite version: 1.6.21.1
- Launcher version: 2.1.2

**Comment by Nightfirecat** [comment] 2020-06-27 04:06
Duplicate of #7702

**Closed by Nightfirecat** 2020-06-27 04:06 UTC
Labels: duplicate
