### ISSUE TITLE
Client resizes to smallest possible window after opening and closing side panel

### ISSUE THREAD

**Issue by Unmoon** [runelite/runelite#298] opened 2017-12-29 19:51 UTC
1. Resize client width to minimum and height to non-minimum
2. Open and close sidebar
3. Client is resized to smallest possible size

Should probably resize back to previous size.

**Comment by UniquePassive** [comment] 2018-01-02 17:40
I can't reproduce this. 
What system are you on?
Can you record a video of it?

**Comment by l2-** [comment] 2018-01-02 20:45
i can't reproduce this for min width and non-min height but i can reproduce something similar where the width is set to smallest possible when the width isn't big enough to fit the game AND the sidepanel. In that case after opening and closing the sidepanel the width is set to minimum. 
example https://i.imgur.com/q0eUHaT.gifv

**Comment by Unmoon** [comment] 2018-01-03 03:42
I'm on Windows 7. https://streamable.com/bj49o

Seems like with the latest release it no longer resize's the height, only width (just like @l2- commented).

**Comment by Adam-** [comment] 2018-01-10 00:25
We think this is fixed in #325

**Closed by Adam-** 2018-01-10 00:25 UTC
