### ISSUE TITLE
World map "Open Map" tooltip covers place name tooltip

### ISSUE THREAD

**Issue by mercster** [runelite/runelite#5820] opened 2018-10-05 06:27 UTC
Title: World map "Open Map" tooltip covers place name tooltip
Reproducible: 100%
Version: Latest RuneLite
Steps to reproduce:

1. Open World map 
2. Hover mouse over any dungeon with its own map
3. Note that the "Open Map" tooltip obscures the tooltip which contains the dungeon's name or label

Suggestion: Either set an offset for the "Open Map" tooltip, let us set an offset or position, or allow us to turn off the "Open Map" tooltip entirely.  As a new player, I am still learning place names, and it's very frustrating to have to try and read what's underneath the "Open Map" tooltip.

Thanks!  Love this client!  Wouldn't play OSRS without it!

**Comment by deathbeam** [comment] 2018-10-05 06:28
Duplicate of #3278

**Closed by deathbeam** 2018-10-05 06:28 UTC
