### ISSUE TITLE
Levels left to next combat level calculator

### ISSUE THREAD

**Issue by SkrillexAkaCraft** [runelite/runelite#857] opened 2018-03-06 14:21 UTC
So i am using a web page to see how many levels in a certain combat skill i have to gain to increase my combat level, so i was thinking why not add something like this into the client itself?

https://gyazo.com/b30c2287ef101c7e15f0dbd2268c5230

**Comment by Joshua-F** [comment] 2018-03-06 17:43
I believe #725 implements this somewhat, it shows xp until a new combat level instead of how many levels.

**Comment by ShaunDreclin** [comment] 2018-03-09 22:05
That PR actually has an option to show XP needed, levels needed, or target level until your next combat level.

**Comment by deathbeam** [comment] 2018-09-13 09:51
Duplicate of #448

**Closed by deathbeam** 2018-09-13 09:51 UTC
Labels: feature-request
