### ISSUE TITLE
Toggle Showing Rooftops with a key

### ISSUE THREAD

**Issue by FranciscoMurias** [runelite/runelite#11376] opened 2020-04-26 21:09 UTC
Currently if you want to show or hide rooftops you have to go through several settings inside runescape itself: go to the settings tab, then go to graphics settings and click on custom then click on remove roofs option. This is extremely tedious to keep doing repeatedly.

It would be useful if this could be bound to a key (set inside the plug in settings) and allowed for players to toggle between showing rooftops or hiding them by just pressing a button.

This is not an overpowered feature and would be a very welcome quality of life thing to have.
Also should not be too difficult to implement as the command "::toggleroofs" already exists. 

Thank you for all the work, hope this gets added.

**Comment by nlruk** [comment] 2020-04-27 09:33
I think it would be better to turn on rooftops when runelite detects we are doing agility and then turns off when we aren't for x amount of time. It would be better than pressing a key

**Comment by FranciscoMurias** [comment] 2020-04-28 01:54
I think those are different things. The show rooftop options has nothing to do with agility. Its just a quality of life thing.

**Comment by dekvall** [comment] 2020-04-30 11:33
I don't see much benefit with a hotkey over just typing `::toggleroof`. In what scenario do you need to toogle roofs so often that the command is too slow? Finding that setting in the interface is also just 4 clicks at the most.

**Comment by Hydrox6** [comment] 2020-04-30 11:37
Duplicate of #8943

**Closed by Hydrox6** 2020-04-30 11:37 UTC
Labels: feature-request
