### ISSUE TITLE
Launch Location

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#10222] opened 2019-11-08 05:59 UTC
Very minor request here, but it would be excellent if Runelite remembered where the window was located when it was last open and launched there, instead of the same spot every time. If you look at just about every other program (Chrome, Discord, Windows Explorer, etc.) they will all open where they were last open.

An alternative is to launch the window on whichever display your mouse is on. This is another popular option I see a lot.

Again, this is very minor, but I just find it really annoying having to restore the window, drag to the other display, then maximise again.

**Comment by abextm** [comment] 2019-11-08 06:03
There is an option for this under `RuneLite` > `Remember client position`. Is that off for you? Also do you open it on the non primary monitor?

**Comment by Spedwards** [comment] 2019-11-08 12:42
> There is an option for this under `RuneLite` > `Remember client position`. Is that off for you? Also do you open it on the non primary monitor?

Didn't realise that was an option but it is enabled. I have the client maximised on my right monitor (non-primary) and when I close and re-open, it opens maximised on my left monitor (primary).

**Comment by Alexsuperfly** [comment] 2019-11-14 21:02
duplicate of #4778

**Closed** 2019-11-15 09:46 UTC
