### ISSUE TITLE
More accurate loot tracker

### ISSUE THREAD

**Issue by cinolt** [runelite/runelite#10245] opened 2019-11-12 21:46 UTC
**Is your feature request related to a problem? Please describe.**
The current loot tracker lists the items that an npc/player dropped on death, however players don't always pick up every drop, Also, it does not count the gp lost from supplies like food, runes etc.

**Describe the solution you'd like**
It would be nice if there is a configuration option, or maybe even an alternate tab like "Item Tracker", that records every time the player actually picks up an item, and also records every time the player eats a food, drinks a potion, or even drops an item, anything that effects the gp value the player is holding. Then it should display an overall gp loss/gain number.

**Comment by Nightfirecat** [comment] 2019-11-12 22:10
The loot tracker is only intended to track dropped loots, not picked-up loots and supply usage. That bit of this request is a duplicate of #6700.

**Closed by Nightfirecat** 2019-11-12 22:10 UTC
