### ISSUE TITLE
Metronome independent from ingame sounds

### ISSUE THREAD

**Issue by tehbabybear** [runelite/runelite#9060] opened 2019-06-08 04:48 UTC
The metronome is a very helpful resource as I have no internal sense of rhythm however, the game sounds drown out the metronome once I begin prayer flicking. 

Can the metronome have a separate volume control so we can make it louder or quieter as we please?

Another solution could be having the ability to turn on the metronome without having game sounds on.

**Comment by JacobThompson** [comment] 2019-06-08 05:08
This is probably due to stack smashing with the rl client being a wrapper on top of the jagex client plus it’s running various plugins that could be flooding the call stack. Try disabling more plugins as a temp fix and i might have time to look into the runelite execution pipeline to see if we could split more things up between threads and pipes to fix the issue. We may not have the time, effort, or energy as a community to fix this problem as it will likely require lots of analysis and refactoring.

**Comment by Nightfirecat** [comment] 2019-06-08 06:15
Duplicate of #530
Also this has nothing to do with stack smashing.

**Closed by Nightfirecat** 2019-06-08 06:15 UTC
