### ISSUE TITLE
Bug during Bone Voyage quest.

### ISSUE THREAD

**Issue by Cfourr** [runelite/runelite#13417] opened 2021-03-31 05:14 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The bug will not allow you to steer the boat at the end of the Bone Voyage quest.

**To Reproduce**
1. Start the final section of the quest where you steer the boat towards Fossil Island.

**Expected behavior**
When you try to click the left or right arrows to steer, its as if it is not registering your clicks at all. The boat has no response to your course corrections.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite download 1.7.3.1
 - Launcher version: 2.1.6

**Additional context**

**Comment by Nightfirecat** [comment] 2021-03-31 05:16
I've completed this quest using RuneLite multiple times and never encountered this, or other issues with the quest. Does this still happen with all hub plugins disabled?

**Comment by Cfourr** [comment] 2021-03-31 05:23
I'm not sure. I know when I tried the first time, nothing registered except the sail speed, but I thought it was just me. Second time it did the same thing and I started getting skeptical. Third time I closed out of Runelite and logged into the official Runescape launcher and completed it, by doing exactly the same thing, the first time with no issues whatsoever. So I'm really not sure what happened with that.

**Comment by Nightfirecat** [comment] 2021-03-31 05:27
[Using the instructions at the top of this wiki page](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client), can you please upload your client log?

**Comment by Cfourr** [comment] 2021-03-31 05:34
[client.log](https://github.com/runelite/runelite/files/6233985/client.log)

Not sure if I did this right, if not just lemme know. Thanks for the help!

**Comment by oplosthee** [comment] 2021-04-02 13:28
I had a similar issue in the past while using OSBuddy during this quest, which was caused by their OpenGL/GPU plugin. Not sure if that's also what's causing this issue for RuneLite, but I thought it was worth mentioning.

**Comment by Nightfirecat** [comment] 2022-07-10 04:55
Since this issue is lacking information and has not been updated in some time, I am closing it.

**Closed by Nightfirecat** 2022-07-10 04:55 UTC
Labels: needs-information
