### ISSUE TITLE
Idle Notifier 5 Hour 40 Minute unwanted notification bug

### ISSUE THREAD

**Issue by WonderfulDeath** [runelite/runelite#17890] opened 2024-05-28 02:37 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Regarding the "Idle Notifier" plugin and it's bug-every time the log out timer that i have enabled to replace the report button reaches 5 hours and 40 minutes in the current session played i get a notification from specifically this plugin(i don't think this is related to the plugin that replaces the report button, it's just how i found out about this bug), i do not get this unwanted notification when i have this plugin disabled, this notification happens regardless if have the "Idle Logout Notifications" enabled or not- as long as the plugin is turned on i will get this notification at 5 hours 40 minutes played every single time. for more information i also enabled chatbox notifications that give explanations for what it's notifying me for and it's something along the lines of "you're going to be logged out!" notification in the chatbox so i suspect it's related to the idle logout notifications part of the plugin always being active, i even enabled the idle logout notification plugin but turned all of it off in the little cog next to it so it wouldn't notify me but that hasn't worked either- it will notify me regardless as long as the plugin is enabled

### Screenshots or videos

i could give this in an addendum- but i'm unsure of how helpful it would be- also i would need at least 5 hours and 40 minutes to demonstrate it in a screenshot

### RuneLite version

RuneLite Version: 1.10.31.2 Launcher Version: 2.6.7

### Logs

[client.log](https://github.com/runelite/runelite/files/15463246/client.log)
[launcher.log](https://github.com/runelite/runelite/files/15463251/launcher.log)

**Comment by Speeddymon** [comment] 2024-05-28 04:31
Hello, could you clear out the client.log and launcher.log files completely and then run a session until the sound happens, then exit the client and upload the logs again? The current logs attached span over a month, and it's impossible to know with all of the profile switching and errors from other plugins when the issue occurred to try to narrow down a source.

As a suggestion, create a profile will all other plugins except for this one turned off and use that for a session to see if you can reproduce the issue with only this plugin enabled.

Demonstrating the issue by turning off this plugin only reveals part of the problem. Because this plugin generates chat messages, its possible another plugin is picking up the chat message near the 6 hour mark from this plugin and playing a sound as a result. Turning off everything but this and then still being able to reproduce the issue demonstrates that this plugin is the actual source of the sound.

Hope this helps!

**Comment by Alexsuperfly** [comment] 2024-05-28 11:50
are you saying you want the 6hr logout notification to be behind a config option so you can turn it off?

**Comment by WonderfulDeath** [comment] 2024-05-28 12:37
> are you saying you want the 6hr logout notification to be behind a config option so you can turn it off?

if that's what that notification is, yes; i don't want this unnecessary notification that you can't even toggle and isn't mentioned in the settings- but if that is what this notification is, why is it not listed anywhere even under the idle notifier github page?

**Comment by Speeddymon** [comment] 2024-05-28 13:37
Are you using any part of the plug-in? You mentioned turning every setting
off, so I'm not clear on what you're using.

I also suggested just clearing the log without turning off all plugins.
Could you at least do that, give us a log from a single play season where
the issue happens?

**Comment by WonderfulDeath** [comment] 2024-05-29 02:34
> Are you using any part of the plug-in? You mentioned turning every setting off, so I'm not clear on what you're using. I also suggested just clearing the log without turning off all plugins. Could you at least do that, give us a log from a single play session where the issue happens?

yea the only part of the idle notifier plugin i'm using is for prayer so just the "Prayer Threshold", next time i reach 5 hours and 40 minutes i'll disabled all plugins and see it if still persists- probably tomorrow

**Comment by Speeddymon** [comment] 2024-05-29 22:12
Thanks this is helpful. 

I'll run through the events as I see them in the log. Please let me know if I get anything wrong. 

So looking at this, you started your play session at 09:53:30 EDT. Normal play time stuff happens for a few hours. 

Then at 15:33:54 EDT, you created a new profile, renamed it to TEST, and switched to it:

```
2024-05-29 15:33:54 EDT [AWT-EventQueue-0] INFO  n.r.c.plugins.config.ProfilePanel - Creating new profile: New Profile
2024-05-29 15:33:58 EDT [AWT-EventQueue-0] INFO  n.r.c.plugins.config.ProfilePanel - Renaming profile ConfigProfile(id=96876503879400, name=New Profile, sync=false, active=false, rev=-1, defaultForRsProfiles=[]) (96876503879400) to TEST
2024-05-29 15:33:58 EDT [AWT-EventQueue-0] INFO  n.r.client.config.ProfileManager - Old profile file New Profile-96876503879400.properties does not exist
2024-05-29 15:33:59 EDT [pool-3-thread-1] INFO  n.r.client.config.ConfigManager - Switching profile to: TEST (96876503879400)
```

Question 1: Did you hear the sound before creating and switching to the TEST profile? 

I ask because there's nothing logged for an hour between 14:30:39 and 15:33:54. I'm assuming you didn't hear anything yet. 

So then you switched to the new profile and disabled some plugins as requested:

```
2024-05-29 15:34:00 EDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Stopping external plugin "class com.qolting.QoltingPlugin"
2024-05-29 15:34:00 EDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Stopping external plugin "class com.banktaglayouts.BankTagLayoutsPlugin"
2024-05-29 15:34:00 EDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Stopping external plugin "class melky.resourcepacks.ResourcePacksPlugin"
2024-05-29 15:34:00 EDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Stopping external plugin "class com.defaulttab.DefaultTabPlugin"
2024-05-29 15:34:00 EDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Stopping external plugin "class info.sigterm.plugins.zoom.ZoomPlugin"
2024-05-29 15:34:00 EDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Stopping external plugin "class com.noexamine.NoExaminePlugin"
2024-05-29 15:34:00 EDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Stopping external plugin "class com.adamk33n3r.runelite.watchdog.WatchdogPlugin"
2024-05-29 15:34:00 EDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Stopping external plugin "class com.mouseovertextdisabler.MouseoverTextDisablerPlugin"
```

Then just 5 minutes later, you switched back to the Vyrewatch Sentinel profile and deleted the TEST profile. 

```
2024-05-29 15:40:35 EDT [pool-3-thread-1] INFO  n.r.client.config.ConfigManager - Switching profile to: Vyrewatch Sentinel (389381914600)
-snip-
2024-05-29 15:41:01 EDT [AWT-EventQueue-0] INFO  n.r.c.plugins.config.ProfilePanel - Deleting profile TEST
```

I'm guessing you heard the sound during this 5 minutes. There is one log entry coming from the bank tags plug-in

```
2024-05-29 15:34:07 EDT [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
	at net.runelite.client.plugins.banktags.tabs.TabInterface.deinit(TabInterface.java:410)
	at net.runelite.client.plugins.banktags.BankTagsPlugin.lambda$shutDown$0(BankTagsPlugin.java:168)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
	at client.dd(client.java:260)
	at client.bp(client.java)
	at be.ag(be.java:371)
	at be.fk(be.java)
	at be.run(be.java:31308)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I don't think this is the cause of the sound but I need to know when you heard the sound to be able to narrow this down. 

After deleting the test profile there's one more error message from the Qolting plug-in:

```
2024-05-29 15:42:49 EDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.qolting.AccountManager.QoltingAccountInfo.fromString(QoltingAccountInfo.java:61)
	at com.qolting.AccountManager.QoltingAccountInfo.<init>(QoltingAccountInfo.java:46)
	at com.qolting.AccountManager.QoltingAccountManager.getAllAccountInfo(QoltingAccountManager.java:39)
	at com.qolting.QoltingPlugin.isAnyAccountLowPrayer(QoltingPlugin.java:331)
	at com.qolting.QoltingPlugin.updateBlackout(QoltingPlugin.java:228)
	at com.qolting.QoltingPlugin.onGameTick(QoltingPlugin.java:734)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:220)
	at client.dd(client.java:260)
	at client.bp(client.java)
	at be.ag(be.java:371)
	at be.fk(be.java)
	at be.run(be.java:31308)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Is THIS when you heard the sound?

After this it looks like you shut down the game for a couple of hours and then created a duplicate of your Vyrewatch Sentinel profile and switched to it, but there's no log entry after that so no indication of how long you played or if you heard the sound after this timestamp: 

```
2024-05-29 15:42:49 EDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.qolting.AccountManager.QoltingAccountInfo.fromString(QoltingAccountInfo.java:61)
	at com.qolting.AccountManager.QoltingAccountInfo.<init>(QoltingAccountInfo.java:46)
	at com.qolting.AccountManager.QoltingAccountManager.getAllAccountInfo(QoltingAccountManager.java:39)
	at com.qolting.QoltingPlugin.isAnyAccountLowPrayer(QoltingPlugin.java:331)
	at com.qolting.QoltingPlugin.updateBlackout(QoltingPlugin.java:228)
	at com.qolting.QoltingPlugin.onGameTick(QoltingPlugin.java:734)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:220)
	at client.dd(client.java:260)
	at client.bp(client.java)
	at be.ag(be.java:371)
	at be.fk(be.java)
	at be.run(be.java:31308)
	at java.base/java.lang.Thread.run(Unknown Source)
```

So if you could confirm roughly the timeframe when you heard the sound that will help figure out further what's the cause.

I do agree that a checkbox for this notification would be a nice feature to add to this plugin so I'll look at implementing it soon and submitting a pull request.

**Comment by WonderfulDeath** [comment] 2024-05-29 22:49
@Speeddymon i'm sorry i wasn't logging what time it was when i heard the sounds(to be clear it's not even necessarily a sound, just a runelite notification which can also be just the screen blinking a certain color or a tray notification). since that post i've created a second test profile and i didn't get the notification even with idle notifier enabled(i disabled half the plugins)- would it help if i posted that runelite profile? either way i'm gonna continue to try and narrow down which confluence of plugin(s) that when activated along with idle notifier is givine me this notification, i think you were spot on with it being at least two plugins creating this notification

**Comment by Nightfirecat** [comment] 2024-05-29 22:55
I think this conversation has gone on enough--we understand the request, which is to add a toggle for the 5-hour-40-minute notification, I don't think further discussion is needed here.

**Comment by Adam-** [comment] 2024-12-23 21:22
Configuration for the 6hr logout notification has been added in e4d42a625cd8fbcefe147cd9e19478e793abc8a3

**Closed by Adam-** 2024-12-23 21:22 UTC
Labels: feature-request
