### ISSUE TITLE
MacOS Big Sur Compatibility

### ISSUE THREAD

**Issue by Harrisonlift** [runelite/runelite#12327] opened 2020-08-11 20:54 UTC
The GPU plugin is no longer working on MacOS Big Sur. 

If you enable the GPU plugin the game screen either completely freezes, or the screen goes black until the GPU plugin is disabled. I've tried this on both the iGPU and the dGPU.

I am on MacOS Big Sur Beta 4. This plugin was working in Beta's 1-3, but whatever is different, I don't expect to get fixed in a beta update.

**Comment by Nightfirecat** [comment] 2020-08-11 20:59
Duplicate of #11965

For now, disable your GPU plugin until Apple fixes whatever they broke in the beta. If this is still occurring once Big Sur is no longer in beta, we will investigate and address the issue.

**Closed by Nightfirecat** 2020-08-11 20:59 UTC
Labels: duplicate
