### ISSUE TITLE
Make Side Bar A Separate Window

### ISSUE THREAD

**Issue by Ur0nlyParents** [runelite/runelite#10416] opened 2019-12-08 23:11 UTC
It would be nice if there was an option to make the sidebar separate from the client to place on a second screen, make it bigger or smaller, etc. No clue how this could be done but having a pop out sidebar is something I've always wanted to put on a second monitor.

**Comment by Hydrox6** [comment] 2020-11-16 16:05
Duplicate of #2463

**Closed by Hydrox6** 2020-11-16 16:05 UTC
Labels: feature-request
