### ISSUE TITLE
Settings presets plugin

### ISSUE THREAD

**Issue by qriqenas** [runelite/runelite#13823] opened 2021-07-02 11:18 UTC
Don't know if anyone actually suggested this, but I bet many of players have different accounts like pures, alts, dolo alts.

What I mean by this, I guess it would be helpful to have a choice of settings by pressing one button. 
For ex. Doing corp solo on my mid-tier laptop with another account holding the instance opened is kind of stressful for my mid-tier laptop. Everytime I close RL, I have to go through settings everytime to change fps, gpu, stretched mode settings. Having presets for different activities would give efficiency, I guess, for various activities once you set settings.

**Comment by Hydrox6** [comment] 2021-07-02 11:21
Duplicate of #2220

**Closed by Hydrox6** 2021-07-02 11:21 UTC
