### ISSUE TITLE
Maximize uses settings of primary display

### ISSUE THREAD

**Issue by Niteman555** [runelite/runelite#5434] opened 2018-09-11 07:41 UTC
**Describe the bug**
When maximizing the runelite client on my second display (which has the taskbar on the left), it uses the settings of my primary monitor (which has the taskbar on the right of the screen)
**To Reproduce**
Set up two displays with differing locations for the taskbar
Maximize Runelite in primary display
Restore runelite window
move to second display
maximize in secondary display
observe that the size is now fitted to the primary display, but on the second display

**Expected behavior**
The display should fill the second display using its taskbar location

**Screenshots**
https://imgur.com/nz4iuEJ

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - RuneLite version: [1.4.16]
 -

**Comment by deathbeam** [comment] 2018-09-11 08:01
What if you disable custom window chrome? In "RuneLite" settings

**Comment by Niteman555** [comment] 2018-09-12 18:04
I disabled the setting, and now the client behaves as expected, but what is "custom window chrome?"

**Comment by deathbeam** [comment] 2018-09-12 18:05
The custom window decorations that we have around the window. It mostly only causes problems like this and many more and its not even pretty :d

**Comment by raiyni** [comment] 2018-10-02 14:30
duplicate of https://github.com/runelite/runelite/issues/5153

**Closed** 2018-10-02 15:14 UTC
Labels: bug
