### ISSUE TITLE
Ground items issue at Whisperer

### ISSUE THREAD

**Issue by Justin13467** [runelite/runelite#16934] opened 2023-08-16 21:04 UTC
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

For example, if i get a manta ray, prayer restore, and ancient brew drop and i only pick up the prayer restore and ancient brew, over the course of the next few kills, it seems that the manta ray drop ground item indicator starts saying there is more and more manta rays. in the screenshot im providing it shows 15 manta rays and i right clicked it and there is still only 3 on the ground but the loot overlay from ground items says 15 still

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/142451741/63c1dfe4-42be-4c91-919f-22eb8b99949a)

### RuneLite version

![image](https://github.com/runelite/runelite/assets/142451741/d63b2dd3-fe7d-4f9d-b1a8-f7e98ad53bfc)

**Comment by YvesW** [comment] 2023-08-16 21:08
Restart your client. It's fixed in 1.10.10.1

**Comment by Justin13467** [comment] 2023-08-16 21:10
thanks

**Comment by Justin13467** [comment] 2023-08-17 04:39
![image](https://github.com/runelite/runelite/assets/142451741/ee151e41-e989-4788-b925-4c3fc9ee941c)

**Comment by Justin13467** [comment] 2023-08-17 04:40
im still having the issue after updating client

**Comment by Nightfirecat** [comment] 2023-08-17 04:41
That screenshot looks accurate? Ground items says you have one 3-dose prayer potion, which your minimenu confirms

**Comment by Nightfirecat** [comment] 2023-08-17 04:41
Also, this is a duplicate of #16930

**Closed by Nightfirecat** 2023-08-17 04:41 UTC
Labels: duplicate
