### ISSUE TITLE
Lightbox solver

### ISSUE THREAD

**Issue by alex-vincent** [runelite/runelite#3674] opened 2018-06-07 20:46 UTC
https://osrs-lightbox-solver.fletom.com/

This site you put in what your box has and go through each step. Would be awesome if could integrate this in runelite and tells you what to click to complete it!

**Comment by Nightfirecat** [comment] 2018-06-07 20:50
Duplicate of #1826, and #2360 has already been opened to implement it.

**Comment by Abextm** [comment] 2018-06-08 07:43
Duplicate #1826

**Closed by Abextm** 2018-06-08 07:43 UTC
Labels: duplicate
