### ISSUE TITLE
Cooldown Bar When Stunned (Theiving)

### ISSUE THREAD

**Issue by hansjm10** [runelite/runelite#13016] opened 2021-01-07 01:18 UTC
I was doing some pick-pocketing on the Master Farmer and I'd prefer not to break my mouse or click intensively when I am stunned. The birds floating above your head while its an indicator doesn't really give any sense of time other than just letting you know you are stunned.

I would like a bar similar to the HP bar to appear above the players head, it can be a different color as to not cause confusion. When you are stunned the bar starts completely full and over the length of time you are stunned the bar goes down. 

I'd consider enabling this feature with snares however could cause some unbalance in PvP if one player is using Runelite and the other isn't.

**Comment by Hydrox6** [comment] 2021-01-07 01:33
Duplicate of #12720

**Closed by Hydrox6** 2021-01-07 01:33 UTC
