### ISSUE TITLE
Packing for Debian

### ISSUE THREAD

**Issue by kennyaj123** [runelite/runelite#7114] opened 2018-12-30 23:12 UTC
**Is your feature request related to a problem? Please describe.**
The current install process for RuneLite on Debian-based distros is suboptimal. A Debian package would streamline this. 

**Describe the solution you'd like**
RuneLite packaged for Debian (downloadable .deb file). Explore adding RuneLite to apt (though non-free components may make this impossible). 

**Describe alternatives you've considered**
Continuing with the current install process. No other packaging option really exists.

**Comment by deathbeam** [comment] 2018-12-31 00:38
Duplicate of https://github.com/runelite/launcher/issues/36

**Closed by deathbeam** 2018-12-31 00:38 UTC
