### ISSUE TITLE
Return to Tag Tab After Closing In-Bank Equipment Screen

### ISSUE THREAD

**Issue by Grendagon** [runelite/runelite#10964] opened 2020-03-06 02:34 UTC
When using Jagex's newly-provided equipment screen accessible in the top left of the bank interface, I encounter the following scenario:

I open a PvM related tag tab, withdraw equipment, use the new interface to equip it, and then close the interface intending to withdraw supplies from the same tag tab.

However the current behaviour is that the bank returns to the top-level view when this interface is closed if it was opened while viewing a RuneLite tag tab. 

With the in-built tabs, it returns to the last-open one - I would like this behaviour to be duplicated for RuneLite tag tabs also.

**Comment by Alexsuperfly** [comment] 2020-03-06 02:35
duplicate of #10824

**Closed** 2020-03-06 03:18 UTC
Labels: duplicate
