### ISSUE TITLE
Changing timer plugin colors for status bar

### ISSUE THREAD

**Issue by OsmiumOG** [runelite/runelite#9894] opened 2019-09-20 18:12 UTC
When farming patches are growing, the green on green status bar is only like 2 shades different creating an eye sore. Thus causing the actual timer bars to be essentially not used. From talking, most people just search for the "Done at 1:45 PM" text to check crops and just ignore the status bars unless it's red.

It would be handy to make the background default bar like a light-medium gray and then have the red for dead, green for growing, etc on top of gray.

Optional: Upon being fully grown, have a yellow border around the green?

**Comment by Alexsuperfly** [comment] 2019-09-20 18:17
duplicate of #8262

**Closed** 2019-10-06 14:44 UTC
