### ISSUE TITLE
Entity hider on in aid of the myreque

### ISSUE THREAD

**Issue by Bjdufre1** [runelite/runelite#15799] opened 2022-10-13 20:51 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

During the quest "In Aid of The Myreque" when killing Gadderanks with entity hider enabled with hide dead npc's also enabled, Gadderanks disappears after killing him and if you click off on the auto dialog from him, there is no way to restart the dialog since he is not visible, if you disable the plugin, he will show back up but is missing the talk to option.

### RuneLite version

RL Version: 1.9.1
Launcher: 2.1.0

**Comment by Enriath** [comment] 2022-10-14 12:23
Duplicate of #15323

**Closed by Enriath** 2022-10-14 12:23 UTC
Labels: needs-triage
