### ISSUE TITLE
Aerial fishing markers bug

### ISSUE THREAD

**Issue by dazardor** [runelite/runelite#10960] opened 2020-03-05 23:18 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When aerial fishing, the markers which highlight the fishing spots become glitched and
 freeze in place

**To Reproduce**
1. Go to molch island
2. aerial fish with amounts of lag will cause fishing spot highlights to freeze
3. this is reset by switching worlds

**Expected behavior**
i expect these 

**Screenshots**
![2020-03-05_19-46-29](https://user-images.githubusercontent.com/61852829/76034686-2b643f80-5f1a-11ea-9581-2905c0c40001.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Alexsuperfly** [comment] 2020-03-05 23:19
duplicate of #7702

**Closed as completed** 2020-03-05 23:20 UTC
Labels: duplicate
