### ISSUE TITLE
Barbarian Assault: Use Alt/Ctrl modifier for calling

### ISSUE THREAD

**Issue by Unmoon** [runelite/runelite#738] opened 2018-02-28 13:00 UTC
Currently the BA plugin simply changes the option order to make it a single click, removing some player interaction/effort from the minigame (making the plugin OP).

**Comment by deathbeam** [comment] 2018-09-13 09:52
Duplicate of #861 (as that one has more context)

**Closed by deathbeam** 2018-09-13 09:52 UTC
Labels: feature-request
