### ISSUE TITLE
Crash when undocking

### ISSUE THREAD

**Issue by loegare** [runelite/runelite#15148] opened 2022-06-18 18:19 UTC
### Type

Crash or hang

### Operating System

MacOS

### OS Version

Monterey 12.4 M1 Pro

### Bug description

When moving from dock->undock or undock-> dock runelite crashes

### Screenshots or videos

[launcher.log](https://github.com/runelite/runelite/files/8934109/launcher.log)

### Logs

[launcher.log](https://github.com/runelite/runelite/files/8934111/launcher.log)

**Comment by LlemonDuck** [comment] 2022-06-18 20:58
Maybe related to #12930? However in that issue it only happens on undocking.

Are you using the GPU plugin? Does the issue still happen when not using the GPU plugin?

**Comment by loegare** [comment] 2022-06-20 19:01
> 

as pure coincidence i just switched from GPU plugin to 117s and this time it didnt crash when undocking. which is interesting

**Comment by Adam-** [comment] 2022-06-20 20:56
> > 
> 
> as pure coincidence i just switched from GPU plugin to 117s and this time it didnt crash when undocking. which is interesting

this is most likely a duplicate of #12930 - 117 has a workaround in place to prevent the crashing

**Closed** 2022-06-20 21:28 UTC
Labels: bug, needs-information
