### ISSUE TITLE
GE Buying history

### ISSUE THREAD

**Issue by nighthawk15015** [runelite/runelite#7830] opened 2019-02-12 14:28 UTC
Today i was merching in the GE and looking for margins between items but the old items i bought are out of my order history. 
Maybe it would be possible to make an plugin or somethings which shows your last 50/100 buys from GE where items stack >= 5 or  GP value >=100k (you can chose the minimum).

**Comment by Hydrox6** [comment] 2019-02-12 14:29
Duplicate of #4377

**Closed** 2019-02-12 14:30 UTC
Labels: duplicate
