### ISSUE TITLE
Phosanis HighScores suggestion 

### ISSUE THREAD

**Issue by Brundles1** [runelite/runelite#14524] opened 2021-12-27 04:19 UTC
Just a suggestion about the in game high-scores feature to change the icon of phosanis nightmare to the same icon featured on the official osrs high scores 
I just think along with the nex logo and the 2 nightmares side by side it would be cool to change it up and make it more definable 
![E8E49242-9EA8-4578-AAC8-976D70B5744B](https://user-images.githubusercontent.com/96711176/147433969-0cdd7e6b-81fc-4c6a-88e4-3151bacfcb87.jpeg)

**Comment by Brundles1** [comment] 2021-12-27 04:27
Also not sure if this is the right place to post or if this has been brought up before I am new to GitHub and have no idea what I’m doing lol 😂

**Comment by MESLewis** [comment] 2022-06-22 15:25
Duplicate of #14214

**Closed by MESLewis** 2022-06-22 15:25 UTC
Labels: enhancement
