### ISSUE TITLE
Ground Items are out of order

### ISSUE THREAD

**Issue by Bkh1994** [runelite/runelite#8910] opened 2019-05-24 13:14 UTC
**Describe the bug**
Runelite's ground items do not match the order of the actual ground items. For example, at blue dragons there is a coin drop. The coins are always on top with the Runelite Ground items. But when you click to pick something up, the top item is actually blue dragonhide. 

Runelite is showing the list based on the order stuff is dropped in, not the actual order they are on the ground. 

To show this behavior, you can drop the blue dragonhide first, coins second, and dragon bones third. That will result in the Runelite order of: (top) blue dragonhide, coins, dragon bones (bottom). But in reality the drops are in order of high alch value -- blue dragonhide, dragon bones, coins.

Runelite should show the ground items in order based on high alch value to match the OSRS ground items functionality. 

![image](https://user-images.githubusercontent.com/39202184/58330087-20fe0c80-7e04-11e9-90c9-7b1ab18c4c5b.png)

 - OS: Windows 7 and 10
 - RuneLite version: 1.5.23

**Comment by deathbeam** [comment] 2019-05-24 16:06
Duplicate of https://github.com/runelite/runelite/issues/4404

**Closed by deathbeam** 2019-05-24 16:06 UTC
Labels: duplicate
