### ISSUE TITLE
Half-charged jewelry on Ground item plugin

### ISSUE THREAD

**Issue by Grabbin** [runelite/runelite#881] opened 2018-03-07 17:33 UTC
Half charged jewelry (like a ring of wealth (2)) doesn't get filtered by the Groud Item plugin "Hide < ge value".
Should be updated to automatically take the price of the uncharged jewelry.
(See screenshot here: https://i.imgur.com/Gtaq1F7.png - the ring has the value of an uncharged ring of wealth in the trade screen)

For jewelry like rings of dueling I guess you could take the price of a fully charged one, as they don't have an uncharged version, but are also not worth a lot.

Edit: It's actually a problem for (I think) all items that are not tradeable through the ge, but are tradeable through the trade screen to other players. For example waters skin (1) - (3).

**Comment by Unmoon** [comment] 2018-03-07 17:34
Also applies to ensouled heads, barrows armor and imbued items. Whatever is untradeable, but tradeable in another form.

**Comment by Adam-** [comment] 2018-03-07 17:36
We need to build a mapping of untradeable -> tradeable versions. There's several features that could use this.

**Comment by deathbeam** [comment] 2018-04-27 10:52
Duplicate of #1045

**Closed by deathbeam** 2018-04-27 10:52 UTC
Labels: feature-request
