### ISSUE TITLE
Runelite settings for multiple accounts

### ISSUE THREAD

**Issue by Wallasaki** [runelite/runelite#5899] opened 2018-10-10 10:11 UTC
**Is your feature request related to a problem? Please describe.**
As you see, I have multiple accounts. Pure, main, ironman (btw) etc. and I don't want to play on them with the same settings as I have on my main.

**Describe the solution you'd like**
For my pure I'd like to disable the defence attack, rechange my prayer orders and some Ground item changes.
But it's a pain in the ass to change them everytime whenever I hop on accounts.
So my suggestion was what if the system remembers each runescape account and saves the settings for that specific account. That would be a dream come true for many many people.

Thanks,

**Comment by deathbeam** [comment] 2018-10-10 10:11
Duplicate of #2220

**Closed by deathbeam** 2018-10-10 10:11 UTC
