### ISSUE TITLE
Item tooltip appears 1 block too high after killing unicorn and going through a fairy ring and back

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#5330] opened 2018-09-06 06:49 UTC
![image](https://user-images.githubusercontent.com/9074448/45139873-8300de00-b1b1-11e8-9899-38a2f81ad240.png)
I killed 2 unicorns, then went through the fairy ring and bcak and the left unicorn horn tooltip was 1 block higher than it should be. I tried several times, and it only appears to be happening when I kill a unicorn that drops loot on that specific spot. Just to be clear, ,before I went though the fairy ring, the tooltips were at a correct height.

**Comment by trimbe** [comment] 2018-12-19 19:58
This appears to be caused by tiles having the incorrect `ItemLayer` height at the time of the `ItemSpawned` event. 

Can be reproduced by going to Lumbridge kitchen and entering the trap door to the cellar. 

The knife spawn's label will be on the ground, and the bucket's label will be far above the table. The knife is on scene tile `55, 57` and the bucket is on scene tile `56, 57`. 

![](https://i.imgur.com/IsekWJg.png)

In the previous scene (Lumbridge castle), those scene tiles are pictured:

![](https://i.imgur.com/O8qSyaj.png)

The knife is positioned lower as the previous `ItemLayer` height was on the ground, and the bucket presumably is basing its `ItemLayer` height on the height of the statue.

If you drop an item on the doorway tile and climb down and back up the cellar trapdoor, the item label's height is that of an item on the table.

![](https://i.imgur.com/3ol4nBP.png)

**Comment by Nightfirecat** [comment] 2019-07-09 22:56
This has been fixed internally with build `246877236.189`.

**Closed by Nightfirecat** 2019-07-09 22:56 UTC
Labels: bug, internal
