### ISSUE TITLE
Add a "Swap Herb clean/use" option to MenuEntrySwapper

### ISSUE THREAD

**Issue by cubemike99** [runelite/runelite#12574] opened 2020-09-30 18:45 UTC
I greatly enjoy doing herb runs, but doing them on a laptop without a mouse is sometimes frustrating. I don't clean my herbs before noting them, and with my touchpad, it's easy to accidentally left click on a herb and start cleaning them when I meant to right click.

The simple solution to this is to have a MenuEntrySwapper toggle that would swap the Clean and Use option on grimy herbs, making the left click on ALL herbs Use. There's already precedent for this with the MenuEntrySwapper toggle that swaps Bury and Use for bones.

The alternative offered by other RuneLite contributors has been to use the configurable shift click option to set the shift click of grimy herbs to be Use. However, in my opinion this is not a solution for several reasons: 

1. It adds an additional step to using a herb on something (pressing down shift). 
2. It forces the use of a second hand.
3. Still allows for the possibility of accidentally cleaning herbs by forgetting to press down shift.
4. It's not feasible to somehow lock shift down, since this interferes with other RuneLite functionality (e.g. using right click to move the camera, since shift right click is used for marking tiles).

Many requests for this feature have been opened in the past, showing there is a clear desire for it among users. If a toggle for swapping Bury and Use on bones can be included (which is arguably a much more powerful and significant toggle, as it greatly speeds up offering bones at the dangerous chaos altar), I don't see why a swap for Clean and Use on herbs can't be included.

**Comment by Hydrox6** [comment] 2020-10-01 08:04
Duplicate of #10159
Duplicate of #6049

Using the bone swap as a precedent isn't a good idea, since we only added that for parity with OSB. As we've said with basically every item swap added in the last few years: just use Shift Click. Also, just clean all your herbs when doing a farm run? Takes barely any time, and you can make them into potions later faster.

Also also, it's really bad form to make an issue *just* to make a PR directly after, especially when it's a duplicate issue

**Closed by Hydrox6** 2020-10-01 08:04 UTC
