### ISSUE TITLE
Binding Necklace Notification

### ISSUE THREAD

**Issue by OGNinjaT** [runelite/runelite#4537] opened 2018-07-27 23:14 UTC
**Is your feature request related to a problem? Please describe.**
I notice that you have the overlay on binding necklaces only for the number of charges it has, but no visual notification.

**Describe the solution you'd like**
 When the binding necklace disintegrates, some sort of Windows notification or a floating text notification in-game (such as Konduit's RC Plugin notifier).

**Comment by deathbeam** [comment] 2018-07-27 23:33
Duplicate of #504

**Closed by deathbeam** 2018-07-27 23:33 UTC
