### ISSUE TITLE
Clue Scroll Plug In Courtesy Emote Bank Tag Toggle

### ISSUE THREAD

**Issue by JwowRS** [runelite/runelite#7778] opened 2019-02-09 21:35 UTC
Man, what a horrible title. Anyways, I noticed that while doing an emote clue (specifically the Jig at Jiggig step if that matters) that the items required for that step are given the bank tag "clue" for the duration of the clue step. However, I already use the bank tag "clue" for my general clue gear, and was looking for a way to disable this feature, but currently there is no toggle for this specific part of the clue scroll plugin, only a toggle for hint arrows and the whole thing.

So, I am formally requesting this feature of emote clue items receiving the bank tag "clue" to be toggleable.

You could even make the tag itself customizable, so I could maybe change it to "emote" instead of "clue".

Thank you kind admins.

**Comment by deathbeam** [comment] 2019-02-09 21:38
This can be easily solved by #6486 (e.g you simply renaming your `clue` tab). I will close this as duplicate of that issue as it is better solution.

**Closed by deathbeam** 2019-02-09 21:38 UTC
