### ISSUE TITLE
[Request] 240FPS request for 240HZ

### ISSUE THREAD

**Issue by Nugamus420** [runelite/runelite#6857] opened 2018-12-07 12:51 UTC
The normal refresh rate is now 240hz unless your poor lol so stop was ting your time on stupid things like Zulrah helper and buts just give me 240FPS support so I can play the game right now it's unplayable

Don't tell me to do it myself because you know that you waste u time not doing it

Also 240FPS animations thanks

I know HTML if that helps???

**Comment by deathbeam** [comment] 2018-12-07 12:54
Duplicate of #6856

**Closed by deathbeam** 2018-12-07 12:54 UTC
