### ISSUE TITLE
Slayer Plugin Update

### ISSUE THREAD

**Issue by ez1ollie** [runelite/runelite#10935] opened 2020-03-03 07:03 UTC
Is it possible to update the slayer plug in to add highlighting options like the NPC indicator plug in has. Current option only allows for the hull highlight.

current highlighting - https://i.imgur.com/j8Uvui1.png
slayer plug in options - https://i.imgur.com/0tkLtqQ.png
npc indicator plug in options - https://i.imgur.com/iAmphK1.png

**Comment by Nightfirecat** [comment] 2020-03-03 07:06
Duplicate of #4606

**Closed by Nightfirecat** 2020-03-03 07:06 UTC
