### ISSUE TITLE
Swap the grotesque guardians bell options.

### ISSUE THREAD

**Issue by Malfuryent** [runelite/runelite#5962] opened 2018-10-12 11:50 UTC
If you accidentally left click the bell you have to watch the whole cutscene, which can get annoying when you are a little tired and missclick or just accidentally click on it as you can't cancel the cutscene.

https://i.imgur.com/onloqJx.png

Swap these 2 around.

**Comment by deathbeam** [comment] 2018-10-12 13:02
Duplicate of #1459

**Closed by deathbeam** 2018-10-12 13:02 UTC
