### ISSUE TITLE
Menu Entry Swapper: Add option to set left click to "Edgeville" on Wilderness Lever.

### ISSUE THREAD

**Issue by JacoboMoral** [runelite/runelite#8736] opened 2019-05-03 04:52 UTC
Wilderness Hard Diary allows you to choose between Ardougne and Edgeville to teleport to. As Edgeville is a more common location to teleport, it'd be nice to be the left-click option.

**Comment by Nightfirecat** [comment] 2019-05-03 05:19
Duplicate of  #5516

**Closed by Nightfirecat** 2019-05-03 05:19 UTC
