### ISSUE TITLE
Progress bars in farming timers have too little contrast

### ISSUE THREAD

**Issue by Reisz** [runelite/runelite#11971] opened 2020-06-24 17:35 UTC
When doing herb runs I like to keep track of the patches I already visited using the timers in the sidebar. However, the low contrast of the green progress bar against the slightly darker green background makes it very hard to scan all the timers quickly, as every bar just looks fully green at a glance.

I would suggest using a shade of gray (different from the shade used for the panel or the text) for the progress bar background regardless of foreground color.

Alternatively if the colored backgrounds have to stay, they would have to become considerably darker than they are now and / or the foreground color would have to become lighter.

![farming_timers_suggestion](https://user-images.githubusercontent.com/2815249/85604599-b8f6a700-b651-11ea-936e-f22e7a5b1d97.png)

**Comment by Nightfirecat** [comment] 2020-06-24 17:37
Duplicate of #8262

**Closed by Nightfirecat** 2020-06-24 17:37 UTC
Labels: duplicate
