### ISSUE TITLE
Opponent freeze timer

### ISSUE THREAD

**Issue by Mirano98** [runelite/runelite#3786] opened 2018-06-14 10:22 UTC
Hi, i would love if you guys added an opponent freeze timer like the one in exilent. It shows how long your opponent is frozen. Look at the pic.
![freeze timer](https://user-images.githubusercontent.com/40264964/41406690-61f4c698-6fcd-11e8-80a7-e937445ce0cf.PNG)

**Comment by deathbeam** [comment] 2018-06-14 17:30
Duplicate of #2011

**Closed by deathbeam** 2018-06-14 17:30 UTC
