### ISSUE TITLE
Grand exchange history

### ISSUE THREAD

**Issue by extreme4all** [runelite/runelite#11048] opened 2020-03-21 12:18 UTC
**Is your feature request related to a problem? Please describe.**
i like flipping and it would be nice to keep track of what items i bought/sold when & what price, the history does an okay job but is very limited especially when you are price checking you lose a lot of valuable information

**Describe the solution you'd like**
I would like runelite to track my trade as a personal log similar to how runelite tracks xp gains, for ease of use it should be also possible to export this information

**Describe alternatives you've considered**
The ingame trade history tab could be longer so it keeps track of all my trades

**Comment by Hydrox6** [comment] 2020-03-21 12:23
Duplicate of #4377

**Closed by Hydrox6** 2020-03-21 12:23 UTC
