### ISSUE TITLE
Menu Entry Swapper not allowing shift click bury or wear with "Bury" or "Teleport item" enabled in MES

### ISSUE THREAD

**Issue by jevonsp** [runelite/runelite#11987] opened 2020-06-25 23:42 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Both Bones and Teleport items are not using their configured shift click action if that action is the one original swapped from left click. 
Example: Bones with "Bury" Checked under Item Swaps in MES cannot be buried with a shift click. The Explorer's Ring with "Teleport item" Checked (also under Item Swaps in MES) cannot be equipped with shift click to wear.

**To Reproduce**
1. Enable either "Bury" or "Teleport item" in MES under Item Swaps.
2. Enable "Customizable shift-click" and change Bones' shift-click option to Bury and/or a teleport item (Amulet of Glory for example) to Wear, then save.
3. Shift Click the item that you changed shift click behavior for.
4. Only the left click action will input

**Expected behavior**
When Shift clicking either bones or a teleport item after configuring it's shift click, the action saved in customizable shift click should occur (as it does with every other item)_. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - RuneLite version: 1.6.21
 - Launcher version: 1.6.0

**Additional context**
Not sure what else to add

**Comment by Nightfirecat** [comment] 2020-06-25 23:42
Duplicate of #11986

**Closed by Nightfirecat** 2020-06-25 23:42 UTC
Labels: duplicate
