### ISSUE TITLE
Minimap only hides when side panels are in "side-stones arrangement"

### ISSUE THREAD

**Issue by Lalonde33** [runelite/runelite#976] opened 2018-03-15 15:42 UTC
http://prntscr.com/irmlch
This has to be toggle off for the minimap to hide.

**Comment by SomeoneWithAnInternetConnection** [comment] 2018-03-15 15:45
I can't seem to convince the minimap to hide by toggling the "Sidepanels can be closed by the hotkeys" option. Looking at the code, it appears as though `RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID` is just wrong. It's currently set to 161, but I'm seeing 164 in the inspector

**Comment by SomeoneWithAnInternetConnection** [comment] 2018-03-15 15:50
Whoops. I've just been informed that it's the collapsible sidepanels themselves, not the hotkey toggle, that causes the problem (which, admittedly, makes more sense). The problem is still roughly the same though: the widget group:ID isn't right when sidepanels aren't collapsible. The minimap's widget group is `RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID` (164) when collapsible panels are turned on, and `RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID` when the panels aren't collapsible.

**Closed** 2018-07-22 01:29 UTC
Labels: bug
