### ISSUE TITLE
Every runelite update leaves empty "C:\\Users\\Adam" directory in the home directory (Linux)

### ISSUE THREAD

**Issue by Jimbimanim** [runelite/runelite#2974] opened 2018-05-19 20:52 UTC
on Linux every time there is a runelite update an empty directory named "C:\\\Users\\\Adam" is created in the user's /home directory

**Comment by deathbeam** [comment] 2018-05-19 23:08
Duplicate of some issue in launcher repository, and has been resolved already, but no new launcher release yet.

**Closed by deathbeam** 2018-05-19 23:08 UTC
