### ISSUE TITLE
Different color overlay agility shortcuts if you're unable to do them

### ISSUE THREAD

**Issue by theinterestingstory** [runelite/runelite#4675] opened 2018-08-03 17:49 UTC
**Is your feature request related to a problem? Please describe.**
Agility shortcuts are always green even if you're unable to use them.

**Describe the solution you'd like**
Have agility shortcuts be able to be color coded if they're unable to be done and maybe another color if they're able to be boosted.

**Describe alternatives you've considered**
Maybe an option to turn off the agility shortcut color overlay if they're unable to be done.

**Additional context**
N/A

**Comment by deathbeam** [comment] 2018-08-03 17:50
Duplicate of #3754

**Closed by deathbeam** 2018-08-03 17:50 UTC
