### ISSUE TITLE
Adding Ore Timers in MLM

### ISSUE THREAD

**Issue by Asymons** [runelite/runelite#4910] opened 2018-08-15 15:01 UTC
Someone in my clan chat was complaining that there weren't ore timers on the rocks they've mined in mother load mine.

What could happen is on top of every empty mined vein, we could set a timer and display it like an empty dial getting fuller and fuller until the vein is restored. 

Issues that could arise is it may get a bit crowded with a bunch of dials.

EDIT: 
Possibly related #4392

**Comment by deathbeam** [comment] 2018-09-02 19:00
Duplicate of #3097

**Closed by deathbeam** 2018-09-02 19:00 UTC
Labels: feature-request
