### ISSUE TITLE
GPU Plugin - GPU that meets blog specs fails

### ISSUE THREAD

**Issue by Dgc2002** [runelite/runelite#6509] opened 2018-11-16 16:14 UTC
GPU Plugin - GPU that meets blog specs fails

Enabling the GPU plugin on my laptop results in a 'frozen' game client. Disabling it does not return it to working order.  
  

  
[Detailed GPU Specs](https://www.notebookcheck.net/NVIDIA-Quadro-M1200-Benchmarks-and-Specs.207414.0.html)

-|-
------------ | -------------
Laptop Model | Thinkpad P51
OS | Windows 10  
GPU Name | NVIDIA Quadro M1200  
GPU OpenGL | 4.5  
GPU RAM | 4096 MB  
GPU Driver Version | 24.21.13.9836
GPU Driver Date | 6/24/2018

**Comment by sfitz0** [comment] 2018-11-16 18:16
I too am having the exact problem. My graphics card is GeForce 1050 4g ddr5

**Comment by sethtroll** [comment] 2018-11-16 18:17
any logs? hard to really guess what the issue is

**Comment by sfitz0** [comment] 2018-11-16 18:23
https://gyazo.com/d0e7a95cb9535c361bec1daf79502447
This is all I have. I'm fully updated with geforce game ready driver
version 416.94

**Comment by sfitz0** [comment] 2018-11-16 18:31
is it possible that my java may be outdated and won't run it?

**Comment by raiyni** [comment] 2018-11-16 18:31
No we ship Java with the windows build.

**Comment by sfitz0** [comment] 2018-11-16 18:33
does anyone have an idea how to fix this issue? I'm running a decent gaming laptop.

**Comment by Kamielvf** [comment] 2018-11-16 18:37
@sfitz0 Try setting your 1050 as main GPU, so runelite does not try to use your integrated graphics for the GPU plugin.

**Comment by sfitz0** [comment] 2018-11-16 18:51
@Kamielvf  1050 is set as main GPU runelite still gives me the error. how do I access the logs so i can post it for you?

**Comment by Kamielvf** [comment] 2018-11-16 18:53
The logs are located in `C:\Users\<username>\.runelite\logs` easiest way getting there is right-clicking the screenshot button, open screenshot folder and then go up one directory.

**Comment by sfitz0** [comment] 2018-11-16 18:57
[application.log](https://github.com/runelite/runelite/files/2590520/application.log)

**Comment by sfitz0** [comment] 2018-11-16 18:57
that's it?

**Comment by sfitz0** [comment] 2018-11-16 19:31
Any solutions?

**Comment by sfitz0** [comment] 2018-11-16 20:56
So I clicked on the "x" button on the error and it bypassed it seems to
work now as long as I dont restart runelite

**Comment by Dgc2002** [comment] 2019-05-13 15:02
User Photon-Phoenix on Discord contacted me with a potential work-around for this issue. So far it's worked consistently for me.  
  
I'll quote them directly:  
  

> [3:33 PM] Photon-Phoenix: could you test it again for me? I've recently found that killing jogamp_exe_tst*.exe twice results in a working client and it worked for someone else in #support today
> [3:33 PM] Photon-Phoenix: it gets stuck on some windows 10 environments unpacking its natives
> [3:33 PM] Photon-Phoenix: and won't continue until killed  
  
In other words  
  
* Enable the GPU plugin  
* `Ctrl+Shift+Esc` to bring up Windows Task Manager  
* Go to the `Details` tab  
* Find a process named `jogamp_exe_tst*.exe` where `*` represents a random(?) set of characters. To make this easier you can sort by process name.  
* Kill the process. You will likely seen another process `jogamp_exe_tst*.exe`. Kill that as well. At this point your GPU plugin might be in working order!

**Comment by MESLewis** [comment] 2021-01-13 04:24
Does this happen on the latest release of RuneLite?
Join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.

**Comment by Nightfirecat** [comment] 2022-07-10 04:06
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:06 UTC
Labels: gpu
