### ISSUE TITLE
FEATURE REQUEST: 2002ish-2006 UI OVERHAUL Toggle 

### ISSUE THREAD

**Issue by LoveRune** [runelite/runelite#13321] opened 2021-03-09 07:22 UTC
•An option to toggle old style hit splash.

**Additional context**
I would pay a monthly fee for this service option . Please 
![Screenshot_20210309-020935_YouTube](https://user-images.githubusercontent.com/80310874/110434728-2c293780-8080-11eb-929b-79fc422eda30.jpg)

**Comment by Nightfirecat** [comment] 2021-03-09 07:30
1. Side stone sprites can already be toggled via the Interface Styles plugin
2. Old-style model replacements are a duplicate of request #3261

The 2002-style hitsplats and item sprite requests are unique requests, but we are not likely to add the ability to change inventory item sprites.

**Comment by LoveRune** [comment] 2021-03-09 07:37
I am just returning to the game once again , after a year or so hiatus . I've been on mobile the past 2 days . I'll have to check out the ground toggle option when I get on my pc.  Thanks

**Comment by LoveRune** [comment] 2021-03-09 07:40
> 1. Side stone sprites can already be toggled via the Interface Styles plugin
> 2. Old-style model replacements are a duplicate of request #3261
> 
> The 2002-style hitsplats and item sprite requests are unique requests, but we are not likely to add the ability to change inventory item sprites.


I am just returning to the game once again , after a year or so hiatus . I've been on mobile the past 2 days . I'll have to check out the ground toggle option when I get on my pc.  Thanks

**Comment by abextm** [comment] 2021-03-09 07:42
Duplicate #9849

**Closed by abextm** 2021-03-09 07:42 UTC
Labels: feature-request, interface-styles, internal

**Comment by LoveRune** [comment] 2021-03-09 07:46
> Duplicate #9849

I fixed my post

**Comment by LoveRune** [comment] 2021-03-09 07:47
> Duplicate #9849

He doesn't show reference of the old style hit splat though
