### ISSUE TITLE
Room time splits plugin for Challenge Mode CoX

### ISSUE THREAD

**Issue by fridayfrog** [runelite/runelite#12117] opened 2020-07-11 20:16 UTC
Feature request:
Could a plugin be added for timesplit in CM CoX? As it stands the only indication of progress/speed of the run is the completion of each floor as opposed to the completion of each room. It would be nice to a get a more precise breakdown of each run especially when doing less casual/more sweaty attempts in teams. Ideally a 'room completion' message would appear in the chat box after passing through the relevant exit to each room, ie, after going through the otherside of the passage after tekton.

![tek exit](https://user-images.githubusercontent.com/68165771/87233031-dc1ba780-c402-11ea-8024-5b8e344b34c0.JPG)

**Comment by melkypie** [comment] 2020-07-11 20:18
Duplicate of #10608

**Closed by melkypie** 2020-07-11 20:18 UTC
