### ISSUE TITLE
Group loot by source since last opening client - Loot Tracker Feature Request

### ISSUE THREAD

**Issue by DragginMyself** [runelite/runelite#12569] opened 2020-09-29 17:12 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to see the loot that I got since opening my client. Currently with "Synchronize panel contents" on. In the "Group loot by source" tab you see all of your loot ever and in the "Show each kill separately" tab you see the loot since you last opened the client in individual lines.

**Describe the solution you'd like**
A 3rd tab on the loot tracker that shows loot grouped by source since the last time you started your client. The symbol could be a little stopwatch symbol with a bar to the side. The data could be sourced from where the "Show each kill separately" tab data is and just shown in a different layout. 

**Additional context**
Icon placed roughly where the red square is in the picture below. 
![image](https://user-images.githubusercontent.com/72096637/94590427-a6919800-0254-11eb-88eb-5a4acd2e7ff0.png)

**Comment by Hydrox6** [comment] 2020-09-29 17:16
Duplicate of #10346

**Closed by Hydrox6** 2020-09-29 17:16 UTC
