### ISSUE TITLE
Herbiboar plugin optimization

### ISSUE THREAD

**Issue by SithrilRS** [runelite/runelite#10493] opened 2019-12-24 17:35 UTC
the herbiboar plugin doesnt wether the mudpatch or the smelly mushroom is the right thing to click. on the wiki on herbiboar you can see theres certian situations where there is a guranteed trail to be correct.
https://oldschool.runescape.wiki/w/Herbiboar
![image](https://user-images.githubusercontent.com/59207591/71421595-311ce980-267c-11ea-9041-1f93a594a1b3.png)

**Comment by Hydrox6** [comment] 2019-12-24 17:38
Duplicate of #5466

**Closed by Hydrox6** 2019-12-24 17:38 UTC
