### ISSUE TITLE
Slayer plugin shows wrong monster icon for ghost task

### ISSUE THREAD

**Issue by TayyabDev** [runelite/runelite#13119] opened 2021-01-27 18:05 UTC
**Describe the bug**
When on a ghost task, the icon shows a ghostspeak amulet instead of a ghost icon

**To Reproduce**
1. Get a ghost slayer task
2. Kill a ghost

**Expected behavior**
Ghost icon should show.

**Screenshots**
![image](https://user-images.githubusercontent.com/19651696/106033486-d08e8600-609f-11eb-94da-88629ecf3fed.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.38
 - Launcher version: 2.1.3

**Additional context**
Not too big of a deal, but maybe this problem is leaking over to other monster tasks as well?

**Comment by Hydrox6** [comment] 2021-01-27 18:07
Duplicate of #1562

**Closed by Hydrox6** 2021-01-27 18:07 UTC
