### ISSUE TITLE
Negative cannonballs left

### ISSUE THREAD

**Issue by maxbla** [runelite/runelite#13494] opened 2021-04-16 16:32 UTC
**Describe the bug**
Under certain circumstances, the cannon overlay can show a negative number.

**To Reproduce**
1. Place cannon, fill with 30 cannonballs
2. fire some cannonballs, say 10, so 20 are left
3. log out (this step is probably optional, haven't tested extensively)
4. wait until the cannon breaks then disappears (35 minutes)
5. log in
6. retrieve cannon from Nulodion and place it. It will actually have 30 cannonballs, but will show as 20. After firing 25 cannonballs, it will show as -5

**Expected behavior**
Placing a cannon should reset `CannonPlugin.java`'s `int cballsLeft` to 0. I don't know the best way to detect a player placing a cannon.

**Screenshots**
![negativecballs](https://user-images.githubusercontent.com/13515803/115054548-31567f00-9e95-11eb-8a0a-bcbe8776bbca.png)

**Environment (please complete the following information):**
 - OS: linux
 - RuneLite version: 1.7.5
 - Launcher version: 2.1.3

**Comment by Hydrox6** [comment] 2021-04-16 16:34
Duplicate of #13105

**Closed by Hydrox6** 2021-04-16 16:34 UTC

**Comment by maxbla** [comment] 2021-04-16 16:36
My apologies. I searched the issues and didn't find that one.
