### ISSUE TITLE
Shift click in bank to eat/drink/equip

### ISSUE THREAD

**Issue by scv-m** [runelite/runelite#10582] opened 2020-01-10 11:44 UTC
**Is your feature request related to a problem? Please describe.**
With the new eating, drinking & equipment while in the bank, you're required to right-click > eat/drink/equip. Being able to shift+click to perform these actions would be great.

https://secure.runescape.com/m=news/eating-in-the-bank?oldschool=1
![image](https://user-images.githubusercontent.com/965541/72150905-dd8bf900-33fa-11ea-9219-b0927a3530ea.png)

**Comment by Hydrox6** [comment] 2020-01-10 11:50
Duplicate of #10572

**Closed by Hydrox6** 2020-01-10 11:50 UTC
