### ISSUE TITLE
Show Ground Markers on the minimap

### ISSUE THREAD

**Issue by Andrek25** [runelite/runelite#8243] opened 2019-03-17 21:05 UTC
Is there a way to do it?

**Comment by xDemoN** [comment] 2019-03-17 21:59
It's being worked on, #7906

**Comment by Nightfirecat** [comment] 2019-03-17 22:06
I'm pretty sure that is not what this request is asking for.

**Comment by Andrek25** [comment] 2019-03-19 03:07
I forget explain that i would like ground markers on the minimap to be easy to click, in this way to be able to move without seeing the ground markers. Thanks!

**Comment by xDemoN** [comment] 2019-03-19 14:11
My bad, I totally misinterpreted this. Although, it does look like a duplicate of #7968

**Closed** 2019-04-07 14:48 UTC
Labels: feature-request, good-for-first-contribution
