### ISSUE TITLE
Tar's in Herblore calculator 

### ISSUE THREAD

**Issue by L337Murd3r** [runelite/runelite#5462] opened 2018-09-12 19:52 UTC
**Is your feature request related to a problem?  just would like to see amount of tars

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by deathbeam** [comment] 2018-09-12 22:05
Duplicate of #3504

**Closed by deathbeam** 2018-09-12 22:05 UTC
