### ISSUE TITLE
client mini-freeze every time it's minimized/maximized or sidebar is opened

### ISSUE THREAD

**Issue by FloppyAl** [runelite/runelite#6607] opened 2018-11-20 14:51 UTC
Latest runelite client, turning GPU on or off does not change anything, started after the GPU update went live.

Windows 7, AMD R7 260x.

**Comment by Alexsuperfly** [comment] 2018-11-20 14:53
duplicate of #6508

**Closed** 2018-11-20 14:59 UTC
