### ISSUE TITLE
Suggestion: Supplies Used Plugin

### ISSUE THREAD

**Issue by DenverC116** [runelite/runelite#6954] opened 2018-12-15 06:10 UTC
Idea is that a tab is available to check what supplies you have used during your login session. Very similar to the loot tracker. Would be convenient to calculate profit from things like slayer and bossing.

**Comment by basicDamen** [comment] 2018-12-15 06:38
This would be nice.. but, would have to consider the concept that if you pick up drops that are consumables.. would it need to be logged or not?

**Comment by DenverC116** [comment] 2018-12-15 06:47
If you used the looted consumables it should count in supplies used, yes

**Comment by raiyni** [comment] 2018-12-24 16:17
Duplicate #4126

**Comment by Adam-** [comment] 2018-12-29 00:09
Duplicate of #6700

**Closed by Adam-** 2018-12-29 00:09 UTC
Labels: feature-request
