### ISSUE TITLE
Show Agility Arena Timer Without Overlays

### ISSUE THREAD

**Issue by Hacerio** [runelite/runelite#8599] opened 2019-04-20 21:37 UTC
Currently, it is not possible to use the agility arena timer without also having the overlays enabled, which I find unnecessary and slightly annoying in the agility arena because there are so many click box overlays that it just clutters up the screen. I would love to be able to use the timer while having the overlays turned off entirely.

**Comment by deathbeam** [comment] 2019-04-20 22:07
Duplicate of #3206

**Closed by deathbeam** 2019-04-20 22:07 UTC
