### ISSUE TITLE
Anti aliasing issue

### ISSUE THREAD

**Issue by IMKRYPTIX** [runelite/runelite#7058] opened 2018-12-23 01:03 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**To Reproduce**
 turn on anti ali 

**Screenshots**
![image](https://user-images.githubusercontent.com/46077677/50379873-c5620400-0656-11e9-91f9-0cd049d8f841.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

Anyone else?

**Comment by Hydrox6** [comment] 2018-12-23 01:14
Turn off AA, it's broken with the latest AMD driver (which I guess you have, since you didn't provide any information)

Also, this is not how to fill out a bug report. Those headings are there to be filled out

Also also, this is the perfect kind of question for the #support channel in the community Discord. You can get there through a link in the Info sidebar panel.

**Comment by IMKRYPTIX** [comment] 2018-12-23 01:17
I really do apologise, it’s late. I’ll join the discord.

Yes indeed AMD USER

**Comment by deathbeam** [comment] 2018-12-23 09:52
Duplicate of #6949

**Closed by deathbeam** 2018-12-23 09:52 UTC
