### ISSUE TITLE
Option to change the size of specific UI such as hitsplats and overhead prayers.

### ISSUE THREAD

**Issue by zeakzz** [runelite/runelite#13507] opened 2021-04-21 06:35 UTC
**Is your feature request related to a problem? Please describe.**
Yes, when using highly upscaled ui the hitsplats and overheads cover the player when zoomed out and makes things hard to see
frustrated when [...]
I cant tell if i swapped gear fully during bosses because hitsplats and overheads are covering it.

**Describe the solution you'd like**
A more configurable Stretched mode that allows options of individual ui scaling customization. 

**Describe alternatives you've considered**
Another alternative to fix this issue would just be to have a box that doesnt scale hitsplats and overheads when using stretched mode. but this wouldnt allow for making hitsplats and overheads smaller than the vanilla so it wouldn't be ideal.

**Additional context**
N/A

**Comment by Hydrox6** [comment] 2021-04-21 08:22
Due to how the system works, the UI Scaling is always applied uniformly across all UI elements. This is not changeable due to the crazy inner workings of the UI system. If you're having trouble with switches, you'd probably be better off with an Equipment Viewer instead (#4353).

Essentially a duplicate of #6749

**Closed by Hydrox6** 2021-04-21 08:22 UTC
