### ISSUE TITLE
Runelite Display Scaling Feature Request 

### ISSUE THREAD

**Issue by Eythrope** [runelite/runelite#3225] opened 2018-05-24 15:28 UTC
Please find an example below whilst showing when using the option to change my display scaling on Windows 10 from 100% to 175% whilst using Konduit & Runelite. I have both Konduit and Runelite open to show how this feature appears on both clients. I know this feature request is supported on the official client & Konduit, however, this would be great add-on for Runelite too.

<a href="https://gyazo.com/55e7fe275808b33a6ab9da194c7873a6"><img src="https://i.gyazo.com/55e7fe275808b33a6ab9da194c7873a6.png" alt="https://gyazo.com/55e7fe275808b33a6ab9da194c7873a6" width="1862"/></a>

This changes the chatbox, inventory, and minimap to appear larger when playing in resizable mode. I feel this would be a great feature to allow easier playgame and less drag time when interacting with the mouse. I personally enjoy playing on resizeable and find it's quite the laid back casual gaming approach. However, I have bad eyesight and often find it difficult to read the chat box, especially when speaking with friends over PM. I would recommend trying this feature request out for yourselves on the official client too.

I would appreciate and encourage any form of feedback against this request.

**Comment by Snufalufugus** [comment] 2018-05-24 16:08
This was once upon a time being worked on as an official feature by Jagex:
https://twitter.com/MrIanGower/status/607698751482765313

**Comment by TzZek** [comment] 2018-05-24 16:37
I'd personally love to see this as well. (ignoring the fact that its OSHD aspect) , https://twitter.com/OSHDcom/status/873264929138147328 , They seemed to have a nice way to set different levels of scaling via the client.

**Comment by Hydrox6** [comment] 2018-05-24 16:38
This is actually quite a bit more difficult than it sounds, especially now that the Deobbed client is closed source. Maybe some day

**Comment by deathbeam** [comment] 2018-05-24 16:40
I believe we added support for scaling already. Are you using the installer?

**Comment by deathbeam** [comment] 2018-05-24 17:29
Duplicate of #858

**Closed by deathbeam** 2018-05-24 17:29 UTC
