### ISSUE TITLE
Random event notifications

### ISSUE THREAD

**Issue by king-koda** [runelite/runelite#1634] opened 2018-04-17 15:09 UTC
Title

**Comment by deathbeam** [comment] 2018-04-17 15:12
First part is duplicate of #1469, second part is already implemented.

**Comment by king-koda** [comment] 2018-04-17 15:28
even for random events? or like a filter so you aren't notified about drunken dwarf etc

**Comment by deathbeam** [comment] 2018-04-17 17:15
no, that is why you should create separate issues for multiple feature requests. Just edit your issue to just contain the request for random event notifications.

**Comment by couxo** [comment] 2018-05-13 16:05
and add toggles to which randoms you would or wouldn't want to be notified on.

**Comment by damane888** [comment] 2018-05-23 09:05
Can this be added? I like A friend strategy to get stamina pots on an ironman - in the long term by random event. Its seriously a good idea.

**Comment by king-koda** [comment] 2018-05-23 09:40
Yeah when I was on my iron man is when I thought of it tbh because I don't care about dwarf but maze and shit are great to be notified about.

**Comment by SirGirion** [comment] 2018-12-19 02:07
I will start development on this one

**Comment by JJGrootveld** [comment] 2019-01-18 12:34
Any progress on this issue? @SirGirion

**Comment by dylanvoll** [comment] 2019-02-08 01:27
I picked up this feature request a few days ago, the development is almost done. I should have this PR'd soon.

**Comment by dylanvoll** [comment] 2019-02-08 07:01
I've submitted a PR for this request.

https://github.com/runelite/runelite/pull/7755

**Comment by iRoxor** [comment] 2019-04-29 02:01
To be honest, I would be fine with notifying the player if a Random Event NPC appeared regardless of who it is for.

This implementation could suffice temporarily until a more practical solution is found.

**Closed** 2019-10-16 18:16 UTC
Labels: feature-request
