### ISSUE TITLE
Shift click teleports not working for some construction cape teleports

### ISSUE THREAD

**Issue by 57LeafClover** [runelite/runelite#17749] opened 2024-04-17 22:54 UTC
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Whenever you set a shift click teleport for the construction cape while it is in your inventory but not equipped, the teleport will not work the majority of the time.  Most teleports will go through eventually if you keep trying, but Rellekka seems to almost never go off.  This only happens while the construction cape is in your inventory, not equipped, and your teleport is set to shift click.

### RuneLite version

Runelite Version: 1.10.27.1
Launcher Version: 2.6.8

**Comment by GMKirby** [comment] 2024-04-18 18:56
Also happening with Max Cape. Seems to be when you press shift before hovering over the item and then move the mouse over the item. If your mouse is already over the item and then you press shift it works as expected

**Comment by notheowner** [comment] 2024-04-18 20:22
> Also happening with Max Cape. Seems to be when you press shift before hovering over the item and then move the mouse over the item. If your mouse is already over the item and then you press shift it works as expected

I can reproduce it like this.

**Comment by Adam-** [comment] 2024-04-19 00:27
I think this is fixed in 1.10.27.2

**Closed by Adam-** 2024-04-19 00:27 UTC
Labels: bug, internal
