### ISSUE TITLE
[Loot Tracker] Track both how much you've earned in the current session and how much you've earned across sessions

### ISSUE THREAD

**Issue by Palyon-dev** [runelite/runelite#14807] opened 2022-03-31 03:57 UTC
With the current system, you have to choose whether you want the loot tracker to show you only how much you've earned total across sessions (Remember loot on), or only how much you've earned in the current session (Remember loot off). It would be nice if we could configure it to show both simultaneously. I like to know how much I've made just in my current session of playing the game, but I'd prefer not to have to sacrifice the loot tracker remembering my loot across sessions in order to get that information.

**Comment by Hydrox6** [comment] 2022-03-31 08:49
Duplicate of #10346

**Closed by Hydrox6** 2022-03-31 08:49 UTC
