### ISSUE TITLE
Ground Markers Tab and Ground Marker Management

### ISSUE THREAD

**Issue by 2mustange** [runelite/runelite#12576] opened 2020-09-30 21:09 UTC
**Is your feature request related to a problem? Please describe.**
I dislike that there is no easy way to manage ground markers and quickly mark tiles with different colors. 

**Describe the solution you'd like**
A tab, like screen markers, that allows you to add ground markers but saves the configuration like screen markers. Where you can name, edit color, and indicate if that grouping of ground markers should be active or not. Add the ability to determine which marker is active for the shift+right click add marker.

**Additional context**
I did the search but the same similar suggestion did not appear very concise.

**Comment by Hydrox6** [comment] 2020-10-01 08:06
Duplicate of #11781

**Closed by Hydrox6** 2020-10-01 08:06 UTC
