### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Runescaper123** [runelite/runelite#4197] opened 2018-07-06 08:14 UTC
It'd be cool if you could add a way to reset the max default zoom option when expand outer zoom is enabled. I like being able to zoom out more, but also like to return to the normal default zoom limit without having to turn off the zoom plugin.

**Comment by Nightfirecat** [comment] 2018-07-06 08:35
Sounds like a duplicate of #919.

**Closed** 2018-07-06 08:55 UTC
Labels: duplicate
