### ISSUE TITLE
macOS minimize (iconify) bug

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#1458] opened 2018-04-12 20:55 UTC
when i try to minimize my client, the client just bugs out the right hand side panels disappear.
here are the screenshots
![image](https://user-images.githubusercontent.com/37475765/38703705-e66edfde-3e9b-11e8-9969-f6ef18803b6d.png)
^ this shows how it looks like before i minimize it

![image](https://user-images.githubusercontent.com/37475765/38703736-f88b7042-3e9b-11e8-90ae-172cfea02150.png)
^this shows that i have clicked the minimize (iconify) icon its highlighted

![image](https://user-images.githubusercontent.com/37475765/38703769-105aed74-3e9c-11e8-854c-7a00793ad119.png)
^this shows that the right hand side pannel just disappears and i can't minimize it and i have to close it from the windows or what ever you call it on MAC 
![image](https://user-images.githubusercontent.com/37475765/38703815-339bf9d6-3e9c-11e8-9967-0521c8204cce.png)
^ thats how i close it to re-open the client

**Comment by deathbeam** [comment] 2019-01-26 11:47
Is this still issue?

**Comment by Adam-** [comment] 2019-06-01 01:02
This is a duplicate of #2967

**Closed by Adam-** 2019-06-01 01:02 UTC
Labels: bug
