### ISSUE TITLE
Client crashes on Macbook Pro Early 2015 HDMI update

### ISSUE THREAD

**Issue by a-jennings** [runelite/runelite#12592] opened 2020-10-03 19:18 UTC
When client is open and HDMI cable is unplugged the game crashes and forces a RuneLite restart. Only the game itself crashes, whereas all of the other features such as timers, hiscores etc. continue to work

Macbook Pro Early 2015
MacOS 10.14.4
Runelite V 1.6.27

**Comment by jessegoeman** [comment] 2020-10-05 10:04
I am trying to understand your issue.
I can come up with the 2 following scenario's.

1 - The game is running, you unplug a hdmi cable and the game crashes.
2 - The game crashes when no hdmi cable is present

Could you please let us know which one of the two it is so I can look further into the issue

**Comment by a-jennings** [comment] 2020-10-05 11:05
Scenario 1 is the issue I am having

**Comment by MESLewis** [comment] 2021-01-13 03:26
Duplicate of #12930

**Closed by MESLewis** 2021-01-13 03:26 UTC
