### ISSUE TITLE
Translator Plugin

### ISSUE THREAD

**Issue by kgtheg** [runelite/runelite#11663] opened 2020-05-22 04:59 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when someone chats with me in a different language that I cannot understand. 

**Describe the solution you'd like**
Open for whatever. 

**Describe alternatives you've considered**
Sometimes it's hard to copy the text in Google since there are wierd character letters. 

**Additional context**
A side plugin maybe?

**Comment by Nightfirecat** [comment] 2020-05-22 05:27
Duplicate of #10591

**Closed by Nightfirecat** 2020-05-22 05:27 UTC
Labels: duplicate
