### ISSUE TITLE
Allow font change for ground item text and remove the 'Ex:

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2079] opened 2018-04-28 05:38 UTC

**Comment by forsco** [comment] 2018-04-28 05:40
You can already hide the exchange price. Refer: https://lambda.sx/9Wx.png

Unless you're just wanting the actual 'Ex:' removed before the price.

**Comment by Jalopyy** [comment] 2018-04-28 05:41
Yes, that. I want to see the GE value of things that drop, but I don't care about the 'EX' (or 'HA') prefixes.

**Comment by SomeZer0** [comment] 2018-04-28 05:52
> Yes, that. I want to see the GE value of things that drop, but I don't care about the 'EX' (or 'HA') prefixes.

I could see possibly removing the prefix, only when one of either "Show EX Price" or "Show HA Price"  is enabled.
But in a scenario where both are on, removing the prefix from one/both wouldn't be a good change IMO.

**Comment by Jalopyy** [comment] 2018-04-28 05:54
Fine with me since I don't use both unless it's in the bank via tooltip.

**Comment by deathbeam** [comment] 2018-04-28 11:26
You can already change font. Second part is duplicate of #1479

**Closed by deathbeam** 2018-04-28 11:26 UTC
