### ISSUE TITLE
Shift click, walk here

### ISSUE THREAD

**Issue by Justin222111** [runelite/runelite#3016] opened 2018-05-20 13:50 UTC
Adding a shift click option in the menu swapper, to walk here instead of picking up items, or attacking might be an interesting feature. i think the option to walk here instead of attack might be op, but the item one, might not be a problem.

**Comment by deathbeam** [comment] 2018-05-20 13:54
Duplicate of #2145

**Closed by deathbeam** 2018-05-20 13:54 UTC
