### ISSUE TITLE
Clue Scroll Fight Indicator

### ISSUE THREAD

**Issue by post-async** [runelite/runelite#8464] opened 2019-04-11 06:47 UTC
**Is your feature request related to a problem? Please describe.**
When doing clue scrolls (specifically coordinate clues), the panel shows a description of the area, but not the fight. 

**Describe the solution you'd like**
An indication of if and who a clue will have you fight.

**Describe alternatives you've considered**
Obviously all this information is available on the wiki. As well, the fights are predictable (zammy wizard for hard wildy clues, sara wizard for other hard clues, armadyl or bandos guard for elite, etc) but I don't think this is widely known. I only learned this because I was working on writing a solution for this.

**Additional context**
I've got this feature mostly written, but didn't want to work on it more once I realized it might not be necessary. Basically, just wanted opinions on if I should keep working on this.

**Comment by xDemoN** [comment] 2019-04-14 04:03
Duplicate of #2580

**Closed** 2019-04-14 04:54 UTC
Labels: clues, duplicate
