### ISSUE TITLE
Imbued Heart timer doesn't want to work.

### ISSUE THREAD

**Issue by MattRKing** [runelite/runelite#12292] opened 2020-08-05 05:36 UTC
Title.

Just does not show up when I use it, I have checked and it is enabled (enabling it on/off does not make it appear).

I typically notice it does not show up when I am on a Kraken task killing Kraken.

**Comment by Nightfirecat** [comment] 2020-08-05 06:08
Duplicate of #3516

**Closed by Nightfirecat** 2020-08-05 06:08 UTC
Labels: duplicate
