### ISSUE TITLE
Rune pouch repair count down

### ISSUE THREAD

**Issue by SUGGlSTlON** [runelite/runelite#8352] opened 2019-03-30 03:33 UTC
It would be nice to have a "countdown" of sorts to when your rune pouch will degrade, one similar to slayer tasks, but when it hits 0, your weakest pouch will degrade. I say weakest, because most people will try to keep all of them up, and repair them one their "weakest" (in terms of how many times you can fill it) is about to break.

**Comment by deathbeam** [comment] 2019-03-30 17:28
Duplicate of #1007

**Closed by deathbeam** 2019-03-30 17:28 UTC
