### ISSUE TITLE
problem with client please help

### ISSUE THREAD

**Issue by bradleeds** [runelite/runelite#2231] opened 2018-05-01 20:56 UTC
I am new to this client but on the menu at the right it keeps doing whats shown in the photo. I have updated java and reinstalled the client 3 times

![untitled](https://user-images.githubusercontent.com/38894247/39493329-6523cd7e-4d8a-11e8-894e-c1eb08873a56.png)

**Comment by Unmoon** [comment] 2018-05-01 21:01
Check this -> https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by deathbeam** [comment] 2018-05-01 21:03
Duplicate of #1449

**Closed by deathbeam** 2018-05-01 21:03 UTC
