### ISSUE TITLE
Small bug with Kraken boss task counter and no icon

### ISSUE THREAD

**Issue by ltvill** [runelite/runelite#5958] opened 2018-10-12 10:57 UTC
![image](https://user-images.githubusercontent.com/40988464/46865574-aceb9700-ce26-11e8-98ef-ec388bc59d81.png)

![image](https://user-images.githubusercontent.com/40988464/46865559-a3622f00-ce26-11e8-87fd-8b5a1dbbdf6e.png)

![image](https://user-images.githubusercontent.com/40988464/46865586-baa11c80-ce26-11e8-9302-acef02b4e3dd.png)

**Comment by ollieatkinson** [comment] 2018-10-12 11:13
Can you please add some more description to exactly what the problem is so we do not have to decipher from the images.

**Comment by ltvill** [comment] 2018-10-12 11:14
It says "The Cave Krakenboss" once you get the task, but if you check what your task is it says "The Cave Kraken boss". Either way, there is no icon.

**Comment by ollieatkinson** [comment] 2018-10-12 11:17
I think this is fixed by this pull request (https://github.com/runelite/runelite/pull/5907) and will be in the next hot fix

**Comment by deathbeam** [comment] 2018-10-12 11:17
This was fixed in #5907

**Comment by deathbeam** [comment] 2018-10-12 11:19
Actually, only partially, there is still problem with "Cave Kraken boss"

**Closed** 2018-10-12 13:20 UTC
Labels: bug
