### ISSUE TITLE
[Suggestion] Skilling Progress

### ISSUE THREAD

**Issue by CorleonexD** [runelite/runelite#14459] opened 2021-12-09 14:22 UTC
Basically id love to get a skilling progress box sort of thing, like they've got on Runescape 3. 
As an example. 
Lets say you're making broad arrows, you'd have a box showing you've made 1/10 sets & time remaining. 
Could be a thing for many skills like, Crafting, Fletching, Smithing etc. Just quality of life Imo.
Hopefully this could be a thing, much appreciated.

**Comment by JoshJ96** [comment] 2021-12-09 16:42
You mean like this?

![image](https://user-images.githubusercontent.com/33074635/145438638-4051a271-0eae-4d0f-8586-2ab3ab131775.png)

I'm assuming this would be more of a plugin hub thing

**Comment by Hydrox6** [comment] 2021-12-09 16:53
Duplicate of #12167

**Closed by Hydrox6** 2021-12-09 16:53 UTC
