### ISSUE TITLE
Tile Indicator - Save/Load Tiles

### ISSUE THREAD

**Issue by Infinitay** [runelite/runelite#1172] opened 2018-03-28 23:35 UTC
Would be cool if we were able to highlight tiles we choose. To be frank, only requesting this so I can use to to mark my MM2 path to get to maniacal monkeys. Nonetheless, I think being able to highlight tiles would be pretty nice and beneficial to other things, such as the inferno, marking NPC spawns yourself (hunting), marking where to place traps, marking safespots you find/currently using, etc.

**Comment by sethtroll** [comment] 2018-03-28 23:48
I think @TheLonelyDev was working on something like this

**Comment by Adam-** [comment] 2018-03-28 23:51
Duplicate of #949

**Closed by Adam-** 2018-03-28 23:51 UTC
Labels: feature-request
