### ISSUE TITLE
Make the Ctrl button in the Camera-plugin a toggle.

### ISSUE THREAD

**Issue by GitAlt** [runelite/runelite#12158] opened 2020-07-16 10:03 UTC
When using the Control button in the Camera-plugin today - which sets your camera to a predefined zoom distance - you have to manually zoom back to the distance you had before. I think it would be better to have the control button work as a toggle in this situation. If you use it and your camera is at the predefined zoom distance, then your camera will return to the zoom distance you had prior to pressing control.

Example: If you're runecrafting, and you're very zoomed out, you might want to zoom in more when at the altar or the bank. A toggle between two zoom distances would be perfect. The same goes for a lot of skilling activities. When you're stationary you usually want to zoom in a lot (Mining, fishing, runecrafting, hunter, etc.) but when you're moving around or banking etc. you want to zoom out a lot.

Extra: It would be extremely convenient to be able to remember the camera direction as well. 

Something like this, where the height parameter is needed to set the camera to exact positions so screenmarkers are still in the right place etc:
![image](https://user-images.githubusercontent.com/68376031/87658768-eddfb080-c75c-11ea-9878-51e12c4e4f2f.png)

**Comment by GitAlt** [comment] 2020-07-20 22:27
Just to clarify the numbers in the picture here, 0-360 in "direction" refers to degrees on the compass, to specify a direction for the camera. That number can of course be in any increments you'd like to program it with.

The 0-90 in the "height" parameter refers to the degree angle you're looking at your character from, where 0 is "eye" level, and 90 is looking vertically down on your character's head. This also can obviously be changed.

The idea is to jump between two preset camera angles, by pressing Ctrl. So you toggle between two camera angles. The main use that I can see is for skilling, as mentioned above. Zoom in when you need to click accurately, zoom out when you need to move. Jumping between the same two camera positions makes things predictable and more convenient.

Perhaps this can be made together with #12193

**Comment by Hydrox6** [comment] 2021-02-02 17:02
This is essentially two separate requests: for Ctrl to remember the old zoom, and for ctrl to completely change how the camera is facing.

**Comment by Hydrox6** [comment] 2021-02-23 15:56
For the features requested here:
* The first is a duplicate of #919
* The second is rejected (see #3195)

**Closed by Hydrox6** 2021-02-23 15:56 UTC
