### ISSUE TITLE
Incorrect Z-index on Tropical trees (GPU plugin)

### ISSUE THREAD

**Issue by Yttrium-tYcLief** [runelite/runelite#7888] opened 2019-02-17 01:17 UTC
**Describe the bug**
Should be pretty obvious: Tropical trees (at least on Ape Atoll) have an incorrect Z-index that causes the leaves to render on top of everything, including ground and other objects that should occlude them. Does not apply to the trunk; only the leaves.

**To Reproduce**
1. Go to Ape Atoll
2. Tilt the camera near the gates where terrain is elevated

**Screenshots**
https://i.imgur.com/tNQXj1G.png

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - RuneLite version: 1.5.12
 - Launcher version: 1.6.0

**Comment by Adam-** [comment] 2019-02-17 01:18
duplicate of #6515

**Comment by Yttrium-tYcLief** [comment] 2019-02-17 01:19
Sorry, my bad. Didn't see that issue when searching for some reason.

**Closed by Adam-** 2019-02-17 01:18 UTC
