### ISSUE TITLE
Camulet menu entry swapper entries are incorrect

### ISSUE THREAD

**Issue by benjl** [runelite/runelite#16945] opened 2023-08-19 18:25 UTC
### Type

Incorrect behavior

### Operating System

None

### Bug description

The camulet's right-click options when equipped are Remove, Check, Temple, and Surface. The swap shift-click menu has the entries Check and Teleport.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/32750171/9b72b132-258c-465d-bdf8-bbe708da46d8)
![image](https://github.com/runelite/runelite/assets/32750171/4c2e9fa3-00da-4908-b941-c41475557862)

### RuneLite version

1.10.10.2
2.4.2

**Comment by Adam-** [comment] 2023-08-19 18:30
duplicate of #15150

**Closed by Adam-** 2023-08-19 18:30 UTC
Labels: needs-triage
