### ISSUE TITLE
Multiple Darts on the floor show the same amount of darts, when the quantities are not the same

### ISSUE THREAD

**Issue by Drows** [runelite/runelite#3371] opened 2018-05-27 02:06 UTC

**Comment by Drows** [comment] 2018-05-27 02:09
![asdafa1](https://user-images.githubusercontent.com/1242994/40581872-636841d0-6131-11e8-9500-7b0573da3d2b.png)

**Comment by Nightfirecat** [comment] 2018-10-16 21:57
Duplicate of #1220

**Closed** 2018-10-16 22:00 UTC
Labels: bug
