### ISSUE TITLE
Client randomly crashes with no warning

### ISSUE THREAD

**Issue by Karua51** [runelite/runelite#15639] opened 2022-09-08 18:37 UTC
### Type

Crash or hang

### Operating System

Windows

### OS Version

windows 10

### Bug description

the client crashes with no warning or pop up

### RuneLite version

Runelite Version 1.8.33
Launcher Version 2.4.5

### Logs

[launcher.log](https://github.com/runelite/runelite/files/9529730/launcher.log)
[client.log](https://github.com/runelite/runelite/files/9529732/client.log)
[jvm_crash_pid_13308.log](https://github.com/runelite/runelite/files/9529734/jvm_crash_pid_13308.log)

**Comment by Karua51** [comment] 2022-09-09 19:34
[launcher.log](https://github.com/runelite/runelite/files/9538183/launcher.log)
also once every few times it crashes it fails to launch

**Comment by Karua51** [comment] 2022-09-16 00:54
[client.log](https://github.com/runelite/runelite/files/9579769/client.log)

**Comment by Felanbird** [comment] 2024-06-18 00:45
This was a duplicate of #10628 but fortunately in the time since, that issue has been updated with resolution(s) that a large amount of people have confirmed to have resolved their issue.

**Closed by Felanbird** 2024-06-18 00:45 UTC
Labels: needs-triage
