### ISSUE TITLE
Twitch chat after clan update

### ISSUE THREAD

**Issue by vitorebom** [runelite/runelite#13713] opened 2021-06-09 19:00 UTC
When using the "Twitch" plugin, it's setup to use "//" as the prefix which as of the clan update is used for clan chat messages. Attempting to send a message to a twitch chat gives a "You are not chatting in the channel of your own clan at the moment" but messages can be received normally in the Channel tab
Worth noting that I'm not in a clan so I can't test if it works while in one.

**Comment by Adam-** [comment] 2021-06-09 21:50
duplicate of #13677

**Closed by Adam-** 2021-06-09 21:50 UTC
