### ISSUE TITLE
F2P members items

### ISSUE THREAD

**Issue by MJJH** [runelite/runelite#5804] opened 2018-10-04 12:53 UTC
The other day I was on a F2P world and obviously the names of my member items were unavailable and got named "members item".
But to my surprise, rl was able to give me the ge and ha value on examine on these items to still make it able to find out which seed and herb was which.

So if it is possible to get the these price checks on members items, wouldn't is also be possible to get the name, as the examine texts also shows "members item". I'd assume the price check is via some item Id, names would be linked to that id as well?
Either showing the name in the examine text or even better on the hover, but still making it visible that it is in fact a members item by coloring the text of putting in a indicator "MI" or so.

**Comment by NathenSample** [comment] 2018-10-04 12:55
Duplicate of #5597

**Closed** 2018-10-04 12:55 UTC
