### ISSUE TITLE
Infernal eels

### ISSUE THREAD

**Issue by KantSpell** [runelite/runelite#4400] opened 2018-07-19 10:12 UTC
When fishing the infernal eels in the inferno place the plugin just hovers over fishing spots that aren't even there

**Comment by Alexsuperfly** [comment] 2018-10-07 05:11
i just finished doing infernal eels for a long time and didn't notice anything of this sort, unless you mean the rendering of the overlay floating above the fishing spot when there are multiple fishing spots at the same tile.  In that case this would be a duplicate of #1392

**Closed** 2018-10-07 08:07 UTC
