### ISSUE TITLE
Better Interface Styles

### ISSUE THREAD

**Issue by MaxedPek** [runelite/runelite#11231] opened 2020-04-08 19:58 UTC
**Is your feature request related to a problem?
Not a problem, just a suggestion.

**Describe the solution you'd like**
It would be nice if someone could make more accurate interface styles for each era of Runescape.

**Describe alternatives you've considered**
First off, I'm happy we have the option to change our interface styles to new and old, however, they aren't accurate. What I mean by this is, all that's being changed on the screen is some sprites, some of these sprites aren't even being sent to the correct spots on the interface. I've posted some pictures below on how this could be possible. 

**Additional context**
Toggleable:
![Data orbs](https://user-images.githubusercontent.com/63365260/78821378-3fbeb080-798e-11ea-9664-3b640fc947dd.png)

2010 Data orb positioning: (Ignore the sloppy photoshop)
![Map2](https://user-images.githubusercontent.com/63365260/78827446-03904d80-7998-11ea-9495-bb7dc1501b0b.png)

**Comment by Nightfirecat** [comment] 2020-04-08 20:10
Duplicate of #11152

**Closed by Nightfirecat** 2020-04-08 20:10 UTC
Labels: duplicate
