### ISSUE TITLE
KC doesnt track if wearing ring of wealth and coin drop.

### ISSUE THREAD

**Issue by Alext162** [runelite/runelite#8314] opened 2019-03-25 23:20 UTC
Was killing Gargs and noticed loot tracker KC and the actual coin drop doesnt count when wearing a ring of wealth (coins auto collected).

Kill anything with coin drop and wear ring of wealth.

Windows
 RuneLite version: 1.5.17.1

**Comment by Hydrox6** [comment] 2019-03-25 23:21
Duplicate of #5077

**Comment by Alext162** [comment] 2019-03-25 23:22
Oh sorry.

**Closed** 2019-03-25 23:23 UTC
