### ISSUE TITLE
Please add the option to manually give ground items a specific color unrelated to their value

### ISSUE THREAD

**Issue by Pushkasuggests** [runelite/runelite#13514] opened 2021-04-23 07:10 UTC
I'm always frustrated when there's a lot of items on the ground and i cant find the specific ones i need without reading all of their names because there's so much orange text. Examples: getting secondaries in CoX, finding specific items in your deathpile as an ultimate ironman

**Describe the solution you'd like**
Allow us to manually give specific items on the ground specific colors.

**Describe alternatives you've considered**
Holding alt and pressing the +, but this gives all the items the color purple.

**Comment by Hydrox6** [comment] 2021-04-23 08:01
Duplicate of #12274

**Closed by Hydrox6** 2021-04-23 08:01 UTC
