### ISSUE TITLE
Game crashes randomly

### ISSUE THREAD

**Issue by jackpakela-pq** [runelite/runelite#13486] opened 2021-04-15 00:10 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Screen freezes. Graphics go crazy. Microsoft says the process is not responding, and I have no other choice but to exit out.

**To Reproduce**
Totally random. Occurs once every couple of days (usually once a week)

**Expected behavior**
I was traveling to the Island of Stone for a Basilisks Knight task. The moment I arrive and get off the boat, the screen freezes and glitches like crazy. I can't move or unpause the screen. The moment I start to try and turn on/off plugins is when the program stops responding and exits out.

**Screenshots**
Finally I do have a screenshot. Here you go. **https://ibb.co/c8KkX81** (stats and total exp redacted)
From this image, we see the inside of my POH, We see parts of the Island of Stone, and we also see parts of Relleka. We are seeing three different areas in OSRS through this weird screen glitch. Also, I believe you can still click around and move, but the screen is totally frozen with this graphical craziness. It's not even worth it - it eventually crashes and stops responding anyways...

**Environment (please complete the following information):**
Windows 10. Latest launcher/version of RL
**Additional context**
Nothing in the logs. I turned off hardware acceleration already using a .bat file. I'm not sure what it is. The only thing I can think of that might be related is this: There's a section in the latest **launcher.txt** file that states:

-XX:ErrorFile=C:\Users\JackR\.runelite\logs\jvm_crash_pid_%p.log, net.runelite.client.RuneLite]

Now, there is no jvm_crash_pid_%p.log file in the logs folder, so I'm not sure why it says that. I'm just very confused...

This is stated every time I open up the RL program when clicking on the .bat file executable (disabling hardware acceleration). Nonetheless, this glitch happens with hardware acceleration enabled/disabled.
Please help me. This glitch is so frustrating. I generally always die when this happens, but this time I didn't. **Please help.**

**Comment by killzone111** [comment] 2021-04-29 11:22
Hmm same thing happens to me...

**Comment by Nightfirecat** [comment] 2022-07-10 04:08
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:08 UTC
Labels: needs-information, gpu
