### ISSUE TITLE
Loot Tracker bug: Ring of wealth

### ISSUE THREAD

**Issue by ArashiJoe** [runelite/runelite#14873] opened 2022-04-17 04:53 UTC
(From the OSRS Wiki) [Ring of wealth](https://oldschool.runescape.wiki/w/Ring_of_wealth): _Wearing this ring (whether charged or not) while killing monsters will automatically pick up [coins](https://oldschool.runescape.wiki/w/Coins), [tokkul](https://oldschool.runescape.wiki/w/Tokkul), or [numulites](https://oldschool.runescape.wiki/w/Numulites) dropped by monsters._
However, the Loot Tracker plugin does not seem to track currency items automatically picked up by the ring's effect.

Not sure how this would be fixed though ... maybe a line of code for each currency item to automatically track quantities in the inventory? That way, the tracker can update with currency items immediately after they are added to the inventory--the same way, and at the same time, it updates all loot as it appears on the ground. (My programming knowledge is **extremely** rusty, so I'm not even sure how to execute that suggestion.)

**Comment by Nightfirecat** [comment] 2022-04-17 04:58
Duplicate of #5077
This is a mostly unfixable problem

**Closed by Nightfirecat** 2022-04-17 04:58 UTC
Labels: duplicate

**Comment by ArashiJoe** [comment] 2022-04-18 02:51
ah, gotcha; my bad
