### ISSUE TITLE
killedOne gets called once per slayer drop, not once per creature killed

### ISSUE THREAD

**Issue by Olofsson99** [runelite/runelite#6968] opened 2018-12-15 18:51 UTC
**Describe the bug**
When two or more creatures you're assigned to kill gets killed on the same game tick, you get one exp drop for the both of them. Since the function killedOne that subtracts from the amount left gets called once per slayer exp drop the amount you have left to kill is not correct. So basically, if you have 150 left to kill, you kill two on the same game tick, according to the plugin you have 149 left to kill when in reality it's 148.

**To Reproduce**
Kill two or more slayer creatures during a task on the same game tick (really common when barraging tasks).

**Expected behavior**
Reduce the amount left to kill by the amount killed. slayerExpGained/hpOfCreature should return the amount killed. Should probably pass the result of the division to the function killedOne and then subtract division result from the variable assigned.

**Screenshots**
N/A

**Environment (please complete the following information):**
Windows 10, RL 1.5.4

**Comment by 15987632** [comment] 2018-12-15 18:56
Duplicate of #1046

**Closed** 2018-12-15 18:57 UTC
