### ISSUE TITLE
Dedicated low health indicator/Better flash notification controls

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#3623] opened 2018-06-04 19:59 UTC
**Is your feature request related to a problem? Please describe.**
I've been using the Idle Notifier plugin to send notifications whenever my health reaches a certain value, and I have RuneLite set to flash that one red overlay a couple times when notifications happen.

It's a really good way of showing me when my health is low when I may not be looking directly at my screen, and many other games do something like this, but this is a kind of hacky solution and the flashing overlay wasn't really meant to be used like this. I have to disable every other notification, or deal with every non-urgent notification flashing my screen for no reason.

I'd like to be able to let my screen flash red when my health is low, without having every other notification also trigger the same screen flashing.

**Describe the solution you'd like**
If possible, I think the Idle Notifier plugin could have its own setting to enable flashing the red overlay when at low health, separate from RuneLite config. Then the option in RL config could be left disabled, so low health would flash the screen while everything else would only send notifications to system tray.

**Describe alternatives you've considered**
Alternatively, you could have controls to toggle flashing separately for any enabled notifications. Throw in some customization options so you can set a different color for each notification, or increase/decrease the speed/duration, and this would likely cover every possible case anyone may need, but of course this would be a lot more work and, well, I don't know how feasible it would be.

**Additional context**
I have no additional context to give, so I'll just leave a thank you for anybody dedicating their free time towards RL. It's very appreciated c:

**Comment by deathbeam** [comment] 2018-09-02 18:55
Duplicate of #2593

**Closed by deathbeam** 2018-09-02 18:55 UTC
Labels: feature-request
