### ISSUE TITLE
Loot tracker doesn't always send the items to the cloud.

### ISSUE THREAD

**Issue by Jadp0wn** [runelite/runelite#7380] opened 2019-01-16 02:45 UTC
**the issue**
the loot tracker doesn't retrieve all the drops you get from the monsters after you restart the client, i set the cap from 1024 to 65536 so there is no problem with pulling the amount of drops of the cloud cause of this, it looks like the loot tracker  doesn't always send it to the cloud or the cloud doesn't recieve it. Please look in to this <3

**Comment by deathbeam** [comment] 2019-02-10 12:40
Possible duplicate of #7784, otherwise it always sends the data unless your internet connection is not working.

**Closed by deathbeam** 2019-02-10 12:40 UTC
Labels: needs-information
