### ISSUE TITLE
overlay color setting not loading from file at launch

### ISSUE THREAD

**Issue by osrs-nerd-guy** [runelite/runelite#12343] opened 2020-08-15 03:36 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
"Overlay Color" [`RuneliteConfig.backgroundOverlayColor`](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java#L357) setting does not load from `settings.properties` file at startup

**To Reproduce**
1. Launch the RuneLite client
2. Navigate to the RuneLite Configuration panel
3. Scroll down to the Overlay Settings section
4. Modify the Overlay Color value from the default `#BA1A1A1A` to the value `#00000000`
5. Verify in `settings.properties` file: `runelite.overlayBackgroundColor=0`
6. Close the RuneLite client
7. Launch the RuneLite client 
8. Navigate to the RuneLite Configuration panel
9. Scroll down to the Overlay Settings section
10. note the Overlay Color value in the UI
11. note the  `runelite.overlayBackgroundColor` value in `settings.properties` file
12. close the RuneLite client
13. note the  `runelite.overlayBackgroundColor` value in `settings.properties` file

**Expected behavior**
5. (file) expect to see `runelite.overlayBackgroundColor` configured  `0`, actually see the configured `0` 👍 
10. (ui) expect to see Overlay Color set to `#00000000`, actually see the default `#BA1A1A1A` 👎 
11. (file) expect to see `runelite.overlayBackgroundColor` configured  `0`, actually see the configured `0` 👍 
13. (file) expect to see `runelite.overlayBackgroundColor` configured  `0`, actually see the default `#BA1A1A1A` value rendered as an integer: `-1172694502` 👎 

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: 1.6.24.1
 - Launcher version: 2.1.3

**Additional context**

This behavior does not occur for other items in the config group, such as Block Extra Mouse Buttons.  It also does not occur for the nearby color setting, Notification Flash Color.  Both of these configuration settings persist correctly in `settings.properties` and are loaded at launch.

example client startup logs:

```
2020-08-14 23:22:19 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.6.24.1 (launcher version 2.1.3) starting up, args: none
2020-08-14 23:22:20 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-08-14 23:22:20 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-08-14 23:22:21 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 683232803.225
2020-08-14 23:22:21 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2020-08-14 23:22:22 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-08-14 23:22:22 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "resource-packs" version "1.2.0" commit "c6d543b0f9ced23c13fdf44162607df4f1d916a6"
2020-08-14 23:22:23 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-08-14 23:22:25 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 6126ms. Uptime: 10064ms
2020-08-14 23:22:25 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,876,433,809x534,layout=java.awt.BorderLayout,title=RuneLite,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@1858082c,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-08-14 23:22:26 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user osrs-nerd-guy.
```

**Comment by Nightfirecat** [comment] 2020-10-05 23:38
I do not get this behavior. Changing the overlay background color to fully-transparent black (`#00000000`) and closing the client causes both the UI and properties file to maintain their expected values during subsequent client sessions. Are you logged in with the Account plugin?

**Comment by chroniquee** [comment] 2022-01-03 17:03
Commenting here for future reference, this issue is caused by having "Allow overlay color to be changed" option enabled in the "Resource packs" plugin. It will override any setting you choose any time you restart the client.  Thanks to geheur on Discord for pointing this out.

**Comment by Nightfirecat** [comment] 2022-01-05 00:11
I am closing this issue as a likely invalid one. If further information is found, we can revisit it.

**Closed by Nightfirecat** 2022-01-05 00:11 UTC
Labels: invalid
