### ISSUE TITLE
Twitch chat in game

### ISSUE THREAD

**Issue by William1Gray** [runelite/runelite#2382] opened 2018-05-06 00:33 UTC
Would be nice for Twitch streamers to be able to show their chat in the in-game chat window. Only issue I can think of at the moment is you most likely would have to give the OAuth token which some people might not be comfortable doing.

**Comment by deathbeam** [comment] 2018-05-06 00:34
Duplicate of #762

**Closed by deathbeam** 2018-05-06 00:34 UTC
