### ISSUE TITLE
High GPU usage w/ GPU plugin

### ISSUE THREAD

**Issue by OtterLord41** [runelite/runelite#9960] opened 2019-10-02 16:32 UTC
I'm not sure if it's normal, but the GPU plugin uses 45-60% of my gpu. Whether I'm logged in or just on the title screen it seems to have high usage. Even if I turn the draw distance to 1 with anti aliasing off, the usage is still around 40%. Is this normal? Only asking because it makes my gpu begin to heat up a bit. Thanks for your help :)
 - OS: Windows 10
 - RuneLite version: 1.5.34
 - Launcher version: 2.0.2
 - RTX 2080, i7-9700k, Asus Z390-F

**Comment by Nightfirecat** [comment] 2022-07-10 04:01
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.

**Closed by Nightfirecat** 2022-07-10 04:01 UTC
Labels: bug, gpu
