### ISSUE TITLE
Bank tag 'clue' no longer shows anything

### ISSUE THREAD

**Issue by cdxdir** [runelite/runelite#13204] opened 2021-02-11 23:33 UTC
**Describe the bug**
Having a bank tag called 'clue' no longer displays any tagged items.

**To Reproduce**
1. Create a bank tag called 'clue'
2. Add items to 'clue' bank tag
3. No items are being displayed.

**Expected behavior**
The 'clue' tag should work as other tags. This was previously working (1-2 months ago)

**Screenshots**
![image](https://user-images.githubusercontent.com/25249937/107711920-26367580-6cd1-11eb-868f-29dd80925aa9.png)
![image](https://user-images.githubusercontent.com/25249937/107711954-3b130900-6cd1-11eb-9a4d-ba912742e74b.png)
![image](https://user-images.githubusercontent.com/25249937/107711995-49f9bb80-6cd1-11eb-9792-00b1ca2de3e0.png)
![image](https://user-images.githubusercontent.com/25249937/107712102-7b728700-6cd1-11eb-96a4-3d00c3a6a66d.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.39
 - Launcher version: 2.1.3

**Additional context**
It's interesting that with the 'clue' tag, you could've also seen 'clue' emote items, when the corresponding step is active. I haven't re-checked if this still is the case, but it was a nice addition. (even if unintended feature)

**Comment by Nightfirecat** [comment] 2021-02-11 23:34
Duplicate of #13162

**Comment by Nightfirecat** [comment] 2021-02-11 23:34
For a work around until next release, you can rename your tag to something else.

**Closed by Nightfirecat** 2021-02-11 23:34 UTC
Labels: duplicate
