### ISSUE TITLE
Windows 10 fullscreen bug

### ISSUE THREAD

**Issue by ImNotSatan** [runelite/runelite#12301] opened 2020-08-07 08:38 UTC
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When scaling is set to "Application" (which is the only way my game looks good at 150% scaling).
The game gets extremely small when using the fullscreen button.

- Dragging it to fullscreen manually does work
- Also happens when Custom Window Chrome is enabled.

**To Reproduce**
0. Set windows scaling to 150%
1. Rightclick on runelite.
2. Compatibility.
3. DPI Settings
4. Set it to Application

**Expected behavior**
Actually going fully fullscreen.

**Screenshots**
Screenshot after pressing the fullscreen button.
https://snipboard.io/Q2KiWb.jpg

**Environment (please complete the following information):**
Windows 10

**Additional context**
None

**Comment by raiyni** [comment] 2020-08-26 04:44
duplicate of https://github.com/runelite/runelite/issues/5153

**Closed by raiyni** 2020-08-26 04:44 UTC
