### ISSUE TITLE
Screen freeze after GPU plugin update when resizing canvas

### ISSUE THREAD

**Issue by iPillYa** [runelite/runelite#6508] opened 2018-11-16 15:17 UTC
**Describe the bug**
Clicking to open and close sidebar freezes screen for about 3 seconds maybe a little more. Sometimes the entire runelite will disappear and it will show my desktop background. I could possibly take a screenshot of what it looks like if it will help. I don't have the GPU plug in on. This may sound kinda minor problem however it is quite frustrating being a person who messes with the sidebar often.

**Environment (please complete the following information):**
 - OS: Windows 7
 - RuneLite version: 1.5.0
 - Launcher version: 1.6.0

**Comment by Alexsuperfly** [comment] 2018-11-16 20:39
this is caused by any resizing of the game window, and happens regardless of GPU plugin use or not.

**Comment by MESLewis** [comment] 2018-11-18 20:30
Does not happen when using fixed mode (stretched or not)

**Comment by Alexsuperfly** [comment] 2018-11-18 20:32
There are tiny studders but not nearly whats experienced in resizeable.

**Comment by Alexsuperfly** [comment] 2018-11-18 21:38
here is a pretty good demonstration of whats going on when resizing: [!](https://streamable.com/705mq)

this was taken with GPU on, afterwards i disabled GPU and was able to recreate all but the weird resolution changes

**Comment by deathbeam** [comment] 2018-11-19 19:52
This was fixed in https://github.com/runelite/runelite/commit/98b4e5aedef2b7f60616c00ca5722cd21607d8ea

**Closed by deathbeam** 2018-11-19 19:52 UTC
Labels: gpu, regression
