### ISSUE TITLE
Add specific birdhouse/herb patches to canvas like you can for XP tracker

### ISSUE THREAD

**Issue by clownshoe123** [runelite/runelite#14629] opened 2022-01-23 15:50 UTC
My problem is that I'm doing wintertodt and that requires me to constantly have the "wintertodt scouter" plugin active on the sidebar instead of "time tracking" thus when constantly hopping worlds and getting notification spammed by wintertodt I'm sometimes late for my hourlies (bird/herb run)

It would be amazing if you could add birdhouses/herb patches to the canvas like you can with the xp tracker so you'll always see them as soon as they're ready. Ideally asap since only 100m fm left but I'm sure it'll help people out in the future regardless ;) thanks a lot

**Comment by Hydrox6** [comment] 2022-01-23 15:53
Duplicate of #14629

**Closed by Hydrox6** 2022-01-23 15:53 UTC
