### ISSUE TITLE
Ornate Maul Handle when pk'ed doesn't register as a 497,263gp drop in Loot Tracker

### ISSUE THREAD

**Issue by ruhtain** [runelite/runelite#9841] opened 2019-09-10 21:33 UTC
Noticed this while pking

Thanks :)

**Comment by Hydrox6** [comment] 2019-09-10 21:39
Duplicate of #1387
The item never actually drops to the ground, but is converted to coins before dropping; as a result, we can't tell where those coins came from. The limit for quantity for ground items is just over 65k, and outside of some major bodging, there's nothing we can do about it

**Closed by Hydrox6** 2019-09-10 21:39 UTC
