### ISSUE TITLE
[Clue] Traiborn is on the 1st floor, not 2nd.

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#2232] opened 2018-05-01 21:15 UTC
Runescape uses british floor numbering, so the "area" for clue 19764 needs to be changed to say 1st floor

**Comment by Nightfirecat** [comment] 2018-05-02 00:40
Duplicate of #1882

**Comment by ShaunDreclin** [comment] 2018-05-02 00:43
Not duplicate, that one is talking about the floor numbering in general

**Comment by Nightfirecat** [comment] 2018-05-02 00:43
Ah, good point. It does make specific mention to this clue, but you're right.

**Closed** 2018-05-02 17:11 UTC
