### ISSUE TITLE
An option to make a custom timer tab

### ISSUE THREAD

**Issue by Neumod** [runelite/runelite#14456] opened 2021-12-09 10:59 UTC
Would be really nice to to have a custom timer tab, so you don't have to jump from birdhouse to special, to trees, to fruit trees and so on. Giving the user a possibility to mark certain timers, would make it easier to track those timers without having to click and additional 5 times every time.

**Comment by Hydrox6** [comment] 2021-12-09 11:48
Duplicate of #3056

**Closed by Hydrox6** 2021-12-09 11:48 UTC
