### ISSUE TITLE
Quest Requirement tracker

### ISSUE THREAD

**Issue by jrobinallsopp** [runelite/runelite#12004] opened 2020-06-27 19:45 UTC
Could somebody change the current quest menu modifier, or, create a new plug in that suggests which quests you already have the requirements to start? It would clean the quest menu up loads and be useful for deciding which quest to start without having to trawl through them all?

**Comment by Hydrox6** [comment] 2020-09-01 07:58
Duplicate of #12004

**Closed by Hydrox6** 2020-09-01 07:58 UTC
