### ISSUE TITLE
[Request] XP/Level Goal

### ISSUE THREAD

**Issue by Treedot** [runelite/runelite#1900] opened 2018-04-24 22:44 UTC
Currently thieving til my fingers fall off, would be nice to set a long term goal in the tracker.

**Comment by jpabeem** [comment] 2018-04-25 07:28
Possible duplicate of https://github.com/runelite/runelite/issues/1168

**Comment by deathbeam** [comment] 2018-04-25 10:30
Duplicate of #1168

**Closed by deathbeam** 2018-04-25 10:30 UTC
